### ISSUE TITLE
As an admin, I would like to see task type on admin dashboard

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1006]
something like this:
![image](https://cloud.githubusercontent.com/assets/41906/10032005/68443ef6-614e-11e5-9fa5-1ce1141ceebd.png)

**Comment by dhcole** [comment]
This mock-up doesn't really show whether the counts should apply to the published row, or total row, or both, so while implemented this, it seems to make most sense to just offer type as a filter that applies to all of the rows:

<img width="331" alt="screen shot 2015-09-27 at 10 35 02 pm" src="https://cloud.githubusercontent.com/assets/170641/10126933/2c6a2ac6-6568-11e5-8be2-c5695efe43ea.png">

**Comment by jeremiak** [comment]
This looks good to me! My only question is if we should add "Full time" to the task type selection?

It shouldn't hold us up from merging this before the end of the FY, so we can open a new issue if its important.

**Comment by ultrasaurus** [comment]
Sorry not to respond quicker... can we please not have this under a menu?  It make it really much harder to sum up stats at end of month/quarter.  If you must have two states, then could be All / Task Type.  But seems ok for not to display totals and by type.

**Comment by dhcole** [comment]
>  But seems ok for not to display totals and by type.

I am not sure what you mean by this. How would you do this without a menu? What rows of the table do you want broken out? The menu gives the you option to see each row split by task time. Without it, we'd either triple the size of the table or provide admin users with less data.

> My only question is if we should add "Full time" to the task type selection?

Yes, I think I just started before that was available and didn't reconcile.

**Comment by kbwagner** [comment]
resolved
