### ISSUE TITLE
Let's get rid of skill & interest tags (since we want to do something different)

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#1013]
Radical idea: let's get rid of skills and interest tags for everything. Instead, let's encourage people to write good task descriptions that include the key words they're looking for in a participant match, and let's encourage people to write good bios that include their interests.

Then lets allow people to search on full text (we already do) and let's suggest tasks that are similar to that task being viewed or past completed tasks based on relationships identified by a search index.

Rationale: 
- tags don't scale: we have over 1,000 tags in the production database and they're a mess. Most are duplicates or near matches. The quality varies widely. Some are single words, others are whole bullet points from job descriptions, Some tasks / profiles have a few, some have dozens (https://github.com/18F/midas/issues/962#issuecomment-142110064)
- standardizing and validating user input is hard: we'd need to have a bunch of filters in place to try to catch duplicate tasks, and doing so would destroy capitalization and spacing. we'll never catch them all (write, writer, writing)
- looking at the data, there is mass confusion even on profiles about what is a skill and what is an interest / topic. the same terms are frequently in both. I see no path to de-duplicating tags without combining these types
- depending on tags for search misses related terms: the "web mapping" tag search would miss "web maps" in the description
- it's just another field on the forms we ask our users to fill out
- until recently (and still in large part) we don't actually do anything with these tags
- nearly all of these problems are already solved by search engines: processing and tokenizing user input, finding related content, handling high volumes of arbitrary content are the main functions of search engines. Anything we try to do with tasks will be building a lot of extra code to deliver a substandard search experience as opposed to setting up a decent full-text index.

Miscellany:
- people can still list skills in their profiles, and in fact, I think they should. but we should treat this as a plain text string, not tags that are unique data models
- we'll still need tags for any discrete known vocabulary, like agencies, locations, and durations
- yes, we could probably do skills / topics tags AND better full text search, but tags will always be an unscalable mess and less useful than better full text search. Instead of splitting effort, let's do one thing right.

What do you think? @GailSwanson @jeremiak @ultrasaurus 

I'm very deep in search and tags this week, which is why I raise this now. If we all agree to make this move, I avoid a ton of work around trying to better standardize tags that will ultimately fall short, and instead I can spend that time on better search.

In practice, this is not a complicated switch. We simply hide some form fields and add some more descriptive text about including your skills in your bio (Jeremia is already working on this page this week).

We'd also want to add links to things like "Find more tasks like this" instead of linking tags.

If we can decide on this tomorrow (Thursday 9/23) I think I can get a basic pass of this done this week, which would improve on our find-ability goal.

**Comment by dhcole** [comment]
Supporting evidence: https://gist.github.com/dhcole/28fe1cc9ac03b5f5c49c

**Comment by kbwagner** [comment]
Closing - skills and interests will be reevaluated with 1561
