### ISSUE TITLE
my name doesn't show up to an opportunity I've signed up for (until I refresh)

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1017]
This looks a little weird:
![image](https://cloud.githubusercontent.com/assets/41906/10088585/d248f8b8-62e9-11e5-9fb2-0734672e4856.png)

**Comment by jeremiak** [comment]
@ultrasaurus is this after you click participate or when you go to a task page for which you've already volunteered? If the former, does it go away on refresh?

**Comment by ultrasaurus** [comment]
Yep, it was right after I clicked "I'm in" -- If I refresh the page it looks like this:
![image](https://cloud.githubusercontent.com/assets/41906/10088797/7adb46ba-62eb-11e5-8856-c7db81777e4c.png)

**Comment by LisaLNelson** [comment]
This is no longer an issue
