### ISSUE TITLE
As an admin, I would like to be able to remove someone from a task without sending them an email that says "this task has been assigned to someone else".

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1024]
If someone accidentally signs up for a task they cannot remove themselves so they send me an email asking me to remove them. When I remove them an email gets sent to the person and to the task creator telling them someone else was selected.  This is confusing to the task creator who then sends me an email to find out what is happening,

**Comment by dhcole** [comment]
@jeremiak done, right?

**Comment by mtorres253** [comment]
Per @LisaLNelson this has not happened lately. Let's move it to a low priority and in the icebox

**Comment by kbwagner** [comment]
This will be covered by the managing opportunities feature enhancements that will separate assigned participants from regular applicants.  Therefore only assigned participants will receive the emails.
