### ISSUE TITLE
Version Eye: 29 packages need a version refresh

### ISSUE THREAD

**Issue by NoahKunin** [openopps/openopps-platform#1027]
Let's get as many of those yellows to flip to green as possible.

**Comment by ultrasaurus** [comment]
yellow to green is more about feature compatibility, @dhcole has reviewed for security concerns, we are deferring for now

**Comment by ultrasaurus** [comment]
It seems we're now using [Version Eye](https://www.versioneye.com/user/projects/57297a80a0ca35004baf7d09#tab-dependencies)

**Comment by kbwagner** [comment]
Resolved
