### ISSUE TITLE
Attempting to sign up with an existing account doesn't show a useful error message

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#1030]
This checkbox shouldn't be green and the message could be more helpful.

![image](https://cloud.githubusercontent.com/assets/170641/10226894/3cfa48bc-6838-11e5-89bc-3684b6ecab5f.png)

**Comment by ultrasaurus** [comment]
How about:  "You already have an account.  Please sign in"  (with a link to sign in)

**Comment by kbwagner** [comment]
Resolved
