### ISSUE TITLE
investigate a tool for data analysis / viz

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1035]
We're going to want a bunch of more admin capability, like
- charts 
- better table view
- annotations of events

Questions we would like to answer:
- current charts 
- # agencies who have members, participants, and task creators
- cross-agency connections
- users over time
- users by agency
- list of  users from a specific agency who have not yet participated
- histogram of time from open to assigned

**Comment by dhcole** [comment]
Looks like Kibana may work well here. Over to Jeremia, who is looking into this for another project.

**Comment by Piglady64** [comment]
We will determine what our current users want and create new tickets. Closing
