### ISSUE TITLE
make it easy to make front end changes

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1038]
@jeremiak suggested using the US Web Design standards for this

after this https://github.com/18F/open-opportunities-theme should have only assets and maybe colors

**Comment by dhcole** [comment]
Per slack conversation with @jeremiak, here are the tasks associated with this. We should break these out into separate tickets once we feel like this is list is set:

1. move as much of the `openopps-theme` repo as possible into the main repo, and try to consolidate all differences into one place, perhaps a single json document
2. consolidate variable replacement to a single file that is more logical than language codes
3. reorganize the files in the backbone application so it’s easier to maintain (do we need views and controller (not actually a thing in backbone) as separate files? should we ditch the “app” subdirectory structure)
4. refactor the backbone models and collections to closely match the API endpoint, removing ad-hoc AJAX requests
5. simplify views across the application to make better use of reusable subviews / components (consider react) (this should cut down on a lot of duplicate code)
6. review vendor libs and see if we can simplify all the external dependencies / get more in line with the #frontend consensus for things like multi-selects
7. remove bootstrap and custom styles and replace it with the webstandards (probably much easier to do this after refactoring / “componentizing" the view and template layer)
8. centralize static content so it’s editable under Federalist

**Comment by jeremiak** [comment]
Just adding the blocked label to this right now because as a team we're not confident that this is the best task to pick up next.

**Comment by kbwagner** [comment]
Resolved
