### ISSUE TITLE
Update Time Commitment label on task create page

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#1051]
From @LisaLNelson 

> We need to fix the Time Commitment so that it doesn't say per week for a one-time task.  That should only show if it is an on-going task. 
> ![image](https://cloud.githubusercontent.com/assets/170641/10396234/686bcd76-6e6f-11e5-9cb2-c64074312051.png)

**Comment by kbwagner** [comment]
Close - refer to 1644
