### ISSUE TITLE
As a user I would like to see the right number of tasks created and completed on the landing page of the platform.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1052]
Right now it appears to have the total number on tasks created since the beginning.

![image](https://cloud.githubusercontent.com/assets/9039852/10459278/dd1f21ce-719c-11e5-972c-2a88aef8b004.png)

**Comment by ultrasaurus** [comment]
Maybe we should just change the text to "Opportunities Completed So Far" ?

**Comment by LisaLNelson** [comment]
I agree with that but the number doesn't jive with the number of opportunities created as shown in the dashboard either.

**Comment by kbwagner** [comment]
Closing - landing page will be updated.
