### ISSUE TITLE
As a user, supervisor, or agency rep I would like to see the benefits for each on the platform.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1053]
As a user, supervisor or agencies rep I would like to see the benefits of Open Opps outlined clearly on the platform.

Agencies/supervisors
Help agencies gain interagency insights and 
Professional development - Meaningful development of employees without the costs of travel or training.
Create and support a network of innovators who hone skills and gain interagency experience.

Employees
Make new contacts and become part of a community of innovators
Break out of the routine and learn what other government agencies are doing
Advance your career by developing new skills and experience
Do interesting work that cuts across the silos of government

**Comment by humancompanion** [comment]
Moved to here: https://github.com/USAJOBS/openopps-help/issues/1
