### ISSUE TITLE
As an admin I would like Kaitlin Devine to get notification of 18F tasks when they are submitted for review.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1064]
Kaitlin Devine is going to start reviewing new 18F tasks to make sure they are clear and have all the information that is important to a potential task taker. To do that she needs to get notification whenever an 18F task is submitted for review.  I told her I would ask you to make that happen.

I think it makes sense for this to be something that can easily be changed to someone else if Kaitlin leaves or goes on vacation.

**Comment by ultrasaurus** [comment]
Let's think of how this works generally.   From my thinking, it wouldn't always happen along organizational lines.  For example, we might have someone who is an experienced writer/editor review all guest blog post tasks (which is a common kind of task).  

One idea would be to have specific tags cause notifications to someone for review.  Might be complicated to have multiple people get notified, but maybe that is ok too... but maybe we need an in-review state or something.

cc @GailSwanson

**Comment by GailSwanson** [comment]
With multiple admins, how do you envision each admin determining which submitted opportunities are intended for which admin to review? i.e. How does the 18F admin (Kaitlin) tell her review queue from the OCSIT (Lisa) queue of opportunities?

**Comment by ultrasaurus** [comment]
One idea is to have a new role where community members act as editor mentors.  Making Kaitlin an admin was a hack, since we didn't have a way for her to review and give feedback on draft opportunities any other way.

**Comment by LisaLNelson** [comment]
This is being closed and rolled into #1580 Add agency admin role.
