### ISSUE TITLE
Fails Sometimes: As a task taker I should be able to click on the I'm in button and sign up for a task 

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1070]
Tim Lowden in my office tried to express interest in a task by clicking the I'm in button and he couldn't do it.  The screen that asks people for their location and agency kept popping up. Tim's location and agency had been added to his profile previously.

**Comment by ultrasaurus** [comment]
This happened to me today on staging -- @dhcole and @jeremiak can one of you browse through the code and see if you can see anything that would cause this?  or there's a server error in the logs?  (happened around 11a EST Oct 16, 2015)

**Comment by kbwagner** [comment]
@LisaLNelson @bmcorum I believe this one can be closed.
