### ISSUE TITLE
openopps.digitalgov.gov should have "official website of the US Government" banner

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1082]
![image](https://cloud.githubusercontent.com/assets/41906/10620071/03c60068-772e-11e5-906c-a6ed8524461f.png)

https://everykidinapark.gov/

**Comment by dhcole** [comment]
Why? Isn't the .gov enough?

**Comment by LisaLNelson** [comment]
@humancompanion is this something we need to add to Open Opps?

**Comment by humancompanion** [comment]
Yes, we should. However, I'm going to create the entire new header & navigation (which Ky shared) soon. That will include the revised logo, etc. It will be here with the other top navigation we have: http://usajobs.github.io/design-system/navigation/

**Comment by kbwagner** [comment]
no longer an issue
