### ISSUE TITLE
Conduct user research

### ISSUE THREAD

**Issue by vz3** [openopps/openopps-platform#1084]
# Research Plan
## Background

The purpose of this user research is to provide foundational research to the product team that can be used by non-designers and designers alike. The focus will be on two primary users: task creators and participants. 

The synthesis of this research will be delivered in the form of [personas ](https://methods.18f.gov/personas/). Personas  are useful in grounding product decisions in real-word user needs and behaviors. Any new features, design, and development should be tested against the user personas.
## Subjects

(In tentative interview order)
- **Current task creators**
  Federal employees who have created tasks on OpenOpps.
- **Potential task creators**
  Federal employees who might create an OpenOpps task.
- **Current participants**
  Federal employees who are participating or have participated in an OpenOpps tasks.
- **Potential participants**
  Federal employees who might be interested in participating in an OpenOpps task.
- **Program staff**
  Federal employees who are responsible for increasing participation in OpenOpps or similar platforms.
## Deliverables
- [Interview summaries](https://methods.18f.gov/stakeholder-and-user-interviews/)
- [Personas](https://methods.18f.gov/personas/)

**Comment by vz3** [comment]
@ultrasaurus it looks like I need to be added as a collaborator so I can move this to the backlog

**Comment by ultrasaurus** [comment]
@vz3 done!

**Comment by ultrasaurus** [comment]
@vz3 can you put the user research plan in the description at the top of this issue or link to a wiki page if you prefer

**Comment by vz3** [comment]
first swing at plan posted, we may need to break this epic down into more discrete tasks.
