### ISSUE TITLE
Revisit front-end testing

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#1099]
Let's set aside some time to revisit our approach to front-end testing. Right now we depend on Casper integration tests. These work pretty well but are really tricky to get right with modals. We do not do any unit testing on front-end code, nor do we have automated cross-browser tests.

Without good test coverage of front-end code we are more likely to see regressions as we development. We'd like to patch regressions with tests to make sure they don't come back; however, without a clear and consistent approach, it takes a lot of time more time to add these tests than it does to just fix the issue.

**Comment by kbwagner** [comment]
We have a test approach in place.
