### ISSUE TITLE
you should not be able to delete your email address

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1119]
It appears that you can delete your email address after signing up.  You shouldn't be able to do that.  (Seems to not allow it for MyUSA accounts)

Here's an example:
https://openopps.digitalgov.gov/profile/1460

![image](https://cloud.githubusercontent.com/assets/41906/10999009/64f308e0-844e-11e5-9317-8dba3717e605.png)

**Comment by kbwagner** [comment]
no longer an issue.
