### ISSUE TITLE
As a task creator, I want to be able to easily see what step of the process my opportunity is in.

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1120]
Acceptance Criteria: This ticket will create a progress bar that will work with the toggle to continue to accept/not accept new participants.
- Create a progress bar at the top of the task creator page. 
- The progress states will be Assigning, In Progress, and Complete
- The progress bar will be in the assigning state as soon as the opportunity is open.  The progress bar will light up and say "assigning"
- When a task is "Assigning", that status in the progress bar will be highlighted green
- The progress bar will be in the In Progress state when the task creator clicks the "Next" button under Assigned participants.
- When a task is "In Progress", that status in the progress bar will be highlighted yellow  and Assigned will continue to be green
- The progress bar will be in the Complete state when the task creator has selected the "Task Completed" link on at least one participant and then selected the "Complete opportunity" button.  If a participant doesn’t do their work and the task creator wants to mark the whole opportunity as completed, there will be a modal saying ‘this person is not marked as ‘task completed’ so he won’t get a credit, are you sure you want to close this opportunity.’ If the task creator clicks okay and returns to the posting posting- then the ‘completed’ icon in the progress bar will have the blue color.
- When a task is "Complete", that status in the progress bar will be highlighted color #02bfe7 (primary-alt) blue.
- There will be a toggle to continue to accept applicants that is covered by Github ticket 964.

Related Tickets: 
- 1703 - Task Taker Progress Bar
- 964 - toggle to accept applicants
- 1656 - Assign applicants
- 1168 - complete process

Mocks: 
Task Creator Progress: https://projects.invisionapp.com/d/main#/console/12657410/275759596/preview
Task Creator: https://projects.invisionapp.com/d/main#/console/12657410/275759596/preview
Full Desktop- https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
Full Mobile- https://projects.invisionapp.com/d/main#/projects/prototypes/12656859

Screen Shot:

![screen shot 2018-02-21 at 9 42 42 am](https://user-images.githubusercontent.com/18709918/36499131-4da36a22-170e-11e8-953c-888724812b63.png)

Original Entry: 
As a task creator, if more people than I need sign up for my task, I need to put it on hold while I select people
This happens with some of the more high profile tasks, so they don't get more people to sign up, since they have enough people who have expressed interest already.

The workaround that task creators are doing is to put it in "archived" state while they talk to people, then move it to assigned.  That feels weird.  We should probably do something better.

related to the general worflow around opportunity states, which also affects https://github.com/18F/midas/issues/964

**Comment by rogeruiz** [comment]
Is the need to put it in an "archived" state to prevent additional people from signing up for the same card while the task logistics are being worked out?

**Comment by ultrasaurus** [comment]
@rogeruiz yep!

**Comment by kbwagner** [comment]
Test comment for Kat M.

**Comment by kbwagner** [comment]
2/21/18 - Katrina Wagner updated:
- Changed the progress bar title from "Assign" to "Assigning" per Min and Brice discussion
- Changed the progress bar title from "Completed" to "Complete" per Min and Brice discussion

**Comment by KatMullens-work** [comment]
Updating: Bullet point 7 is handled by #1672

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
LHammond In Testing 3-2-18
