### ISSUE TITLE
as an admin, when I try to disable a user, I get an 502 "Bad Gateway" error

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1124]
as an admin, when I try to disable a user (1356) on https://openopps.digitalgov.gov/admin/user
the user interface shows a spinner
![image](https://cloud.githubusercontent.com/assets/41906/11035939/4ce8fd3c-86aa-11e5-879f-0bb8d63def65.png)

in JavaScript console, I can see the error:
![image](https://cloud.githubusercontent.com/assets/41906/11035964/633d0bb4-86aa-11e5-9c73-54ddbb82616a.png)

**Comment by kbwagner** [comment]
No longer an issue
