### ISSUE TITLE
Developers would like automatic migrations to avoid errors during deployment

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#1126]
Since moving to Cloud Foundry, our migration process is the only non-automatic step in deployment. Because deployments take place in a controlled environment (CF applications) that do not have `psql` installed, we use the `cf-ssh` extension to run migrations. This approach works but is error-prone do the the number of manual steps.

Another approach is to use `sails-db-migrate` to run the migrations through JS. Doing this eliminates external dependancies and allows us to continuously run migrations on deployment, such as by hooking into the `npm install` process: https://github.com/18F/federalist/blob/master/package.json#L84

This task is to attempt to implement automatic migrations, to update previous migration scripts to use the new approach, and to set up automatic migrations to run on each deployment.

**Comment by adelevie** [comment]
This might be difficult for someone outside of 18F's Cloud Foundry instance to work on.

**Comment by ultrasaurus** [comment]
created separate dependent task that is just for the Javascript migration:  https://github.com/18F/openopps-platform/issues/1248

**Comment by kbwagner** [comment]
runs migration during application start process
