### ISSUE TITLE
When I edit an opportunity, I would like to specify how often the work is done

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1127]
We have an end-date, but I thought we would alternatively have a duration.  This used to be a feature:

![image](https://cloud.githubusercontent.com/assets/41906/11045877/e781f400-86de-11e5-84c7-a21f35af57cb.png)

related to:  https://github.com/18F/open-opportunities-theme/issues/35

When you create the task, you can say how often:

![image](https://cloud.githubusercontent.com/assets/41906/11047641/781ea1e4-86e8-11e5-8d1c-f4f7b2889c32.png)

but then when it is edited, that doesn't appear:

![image](https://cloud.githubusercontent.com/assets/41906/11047674/a0587b08-86e8-11e5-82eb-51d12e9512a6.png)

**Comment by kbwagner** [comment]
Closing - Lisa will put in an enhancement
