### ISSUE TITLE
Add ethn.io to the site

### ISSUE THREAD

**Issue by vz3** [openopps/openopps-platform#1157]
Setting up ethn.io for identifying users for interviews

**Comment by vz3** [comment]
Code snippet:
```<!-- Ethnio Activation Code -->
<script type="text/javascript" language="javascript" src="//ethn.io/14930.js" async="true" charset="utf-8"></script>```

**Comment by humancompanion** [comment]
@LisaLNelson - Is/was ethn.io an option? apps.gov is down right now or I'd check.

**Comment by LisaLNelson** [comment]
@humancompanion not sure if you mean was it an option.  We had a designer who wanted us to add it.
