### ISSUE TITLE
show people's names on logged in home page with their acheivements

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1161]
![image](https://cloud.githubusercontent.com/assets/41906/11475292/68486292-9731-11e5-9d38-478760386496.png)

We can combine names & icons to be...

![image](https://cloud.githubusercontent.com/assets/41906/11485635/34f9a1a2-9769-11e5-8626-af99bb3ba20a.png)
![image](https://cloud.githubusercontent.com/assets/41906/11475283/5e4d02ac-9731-11e5-884a-2799cf4ea840.png)

**Comment by kbwagner** [comment]
Closing - redesigning home page.
