### ISSUE TITLE
Task Creator: reminder to fill out their profiles.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1167]
User Story:: As a task creator and admin I would like to see a reminder to task takers to fill out their profiles.

Acceptance Criteria: 
When someone signs up for a task who has not filled out their profile as admin & task creator I would like to see a screen pop up that says "You have not completed your profile.  Please go back to your profile and fill it out.
-From March 2018 backlog review meeting: adjust AC to make sure when an creator wants to post, they have an agency and location on their profile prior to posting.  How much needs to be complete as a task taker prior to applying.  How much should be required for an opportunity creator prior to posting.  Prompt.

**Comment by LisaLNelson** [comment]
So this is covered by #464 @kbwagner ?

**Comment by kbwagner** [comment]
Closed 464 as dupliate of this: We want to require photo and agency, and something about them (narrative bio and/or skills / interests)

**Comment by Piglady64** [comment]
With "one talent profile" the user has to go into their USAJOBS profile and add information making this not relevant. Closing
