### ISSUE TITLE
As a task creator, I need a clear process for marking assigned participants as having completed their task.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1168]
Acceptance Criteria: 

Marking Assigned Participants as Task Completed and Completing the opportunity:
- From the task creator view, once a participant has been assigned, the task creator can click "Next" and the status changes to "In Progress".
- Once the status is "In progress" a closing task message displays.  The message reads, "Mark this as Task completed when participant is finished with their assigned task"
- Each Assigned participant will have a "Task completed" link under their name.
- Once the participant has manually emailed the task creator to indicate they have completed the task, the task creator can select the assigned participant as "Task completed"
- The "Complete" button is grayed out until at least one assigned participant has been selected as "Task completed"
- When you click on "Task completed" the assigned participant will be marked with a green checkbox and task completed link. Cancel returns the task creator to the In progress page. 
- Confirm returns the user to the page. The assigned participant is now marked with a green checkbox and task completed link
- There is an "Undo" link under the Task Completed link. clicking the link will actually undo the task completed and leave them as assigned. 

Link to Prototype: 
Task Complete: https://projects.invisionapp.com/d/main#/console/12657410/268504231/preview
Desktop- https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
Mobile- https://projects.invisionapp.com/d/main#/projects/prototypes/12656859

Related Ticket: 
- 1656 - Assigning Applicants

Original Issue: 
As a task creator I may not remember to remove someone from the task who may have expressed interest but did not work on it.  Then when I close the task people get credit for completing the task when they did not work on it.

**Comment by minchung12** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update design issues tickets on Github](https://trello.com/c/nBrI4FHL/38-update-design-issues-tickets-on-github)

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
3-2-18 LHammond In Testing
for item 5 of the AC, no confirmation with buttons popped when the Task completed link under the participant name was clicked.  There was a message popped when the Complete Task button was selected, but no options to abort or complete the process was there.
