### ISSUE TITLE
when my account is disabled, I can't sign up and I don't get an error

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1169]
it lets me go through the first screen of registration, but then I can't submit this form:
![image](https://cloud.githubusercontent.com/assets/41906/11539363/8139317c-98db-11e5-8fac-f7433efa821d.png)

In Javascript console, I can a 403 Forbidden error

**Comment by kbwagner** [comment]
No longer an issue.  Message displays email already in use.
