### ISSUE TITLE
As a admin I want people who create tasks to get their badges when they create a new task not later in the process.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1181]
Bev Godwin created a task (https://openopps.digitalgov.gov/tasks/424) in late October and received notification of her first badge yesterday (December 3) when she removed a person who expressed interest in the task from the list. Bev should have received her first badge when the history was moved over. Timing was not right.

![image](https://cloud.githubusercontent.com/assets/9039852/11599626/f5b5095c-9a95-11e5-9c06-2d85a04f5a3c.png)

**Comment by ultrasaurus** [comment]
We should take a look at production database and see if there are any task creators who don't have badges....   but let's not do anything that would cause new notifications w/o checking with Lisa
