### ISSUE TITLE
Creator badges seem to be not assigned to all creators

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1183]
I closed a task out today for Tim Lowden (https://openopps.digitalgov.gov/profile/191) and I got notification that he got a badge today for being a task creator. (TC). I went to his profile page and saw he has two badges one as a TC (Instigator) and one as a TT (Newcomer).  The problem is that both the tasks appear under participated. The Analytics Trainng Coordinator badge should be listed under created.

![image](https://cloud.githubusercontent.com/assets/9039852/11655826/d0629e12-9d7e-11e5-9e55-97b0a66938c5.png)

**Comment by rogeruiz** [comment]
Is Tim the original creator of the task? Looking at [the *Analytics Training Coordinator* task](https://openopps.digitalgov.gov/tasks/421) it seems like he isn't the **Requestor** but rather the **Participant**. I don't think he should have received a creator badge or a notification for that task being completed. Are my assumptions correct?? Still seems like a bug, but may be different.

**Comment by LisaLNelson** [comment]
Your right he is the participant of that task.
<https://openopps.digitalgov.gov/tasks/421> Right now the tasks on his
account are correct.

This badge does not make sense at all then.

[image: Inline image 1]

I was thinking the badge came from another task
<https://openopps.digitalgov.gov/tasks/391> Define Federal Gov Website
Categories <https://openopps.digitalgov.gov/tasks/391> that was actually
created by Marina Fox who left the agency and assigned Tim to be TC.  That
is what I thought he got the badge for. Tim did not actually create the
task he took it over.


Lisa Nelson, GSA

Open Opportunities Program Manager

Digital Government Division

202-779-0262

**Comment by rogeruiz** [comment]
Okay thanks for following up. I'll rename the issue according to this new info. thanks again1

**Comment by ultrasaurus** [comment]
I think the main question now is, why is this https://openopps.digitalgov.gov/profile/191 not in Tim's "Created" list on his profile

**Comment by LisaLNelson** [comment]
Marco Segreto does not have a badge on his profile for the task he created.
Profile: https://openopps.digitalgov.gov/profile/1010
Task: https://openopps.digitalgov.gov/tasks/413

**Comment by LisaLNelson** [comment]
I followed up onthis today and now Tim doesn't have any tasks in the participated or created categories, BUT he has 2 badges.

![screen shot 2016-07-26 at 3 33 14 pm](https://cloud.githubusercontent.com/assets/9039852/17152611/90a42222-5346-11e6-863b-fa8f441a0bec.png)

**Comment by kbwagner** [comment]
Badges work as intended.
