### ISSUE TITLE
Tasks should have an agency

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1194]
so if a user changes their email address, the task would still be associated with their old agency (and we could update old tasks where people have moved)

Should be pre-populated with the task creator's agency.

add to Opportunity Edit screen right below the requestor
![image](https://cloud.githubusercontent.com/assets/41906/11795942/66b2ffd0-a26e-11e5-9249-f00fb62c2e91.png)

We can use same/similar UI as in Admin Tag Configuration.

**Comment by kbwagner** [comment]
Is this covered by the Admin ability to change the opportunity creator?

**Comment by LisaLNelson** [comment]
It is. Approved.
