### ISSUE TITLE
As a user, I would like to see "Draft" items in their own section on my profile.

### ISSUE THREAD

**Issue by rogeruiz** [openopps/openopps-platform#1212]
Currently the user profile **Opportunities** section contains only _Participated_ and _Created_ sections. There should be a _Draft_ section above these two to allow for _Drafts_ to be more prominent on the user profile page.

This fix would have to also filter out any drafts from the _Created_ section of the user profile.

**Comment by rogeruiz** [comment]
What it currently looks like as of this post.

<img width="797" alt="screen shot 2016-01-08 at 9 15 54 am" src="https://cloud.githubusercontent.com/assets/706004/12199730/7d6d4fc2-b5e8-11e5-8c08-dcf8e594b9b0.png">

**Comment by kbwagner** [comment]
This is resolved with Release 1.
