### ISSUE TITLE
As a task creator I need to get notification when a comment is placed on my task.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1215]
A comment was placed on the task "ISO Strategic Planning Facilitator Preference" today and the task creator did not get the notification.  Admin and the person who placed the comment got notification.

![image](https://cloud.githubusercontent.com/assets/9039852/12253280/ce03433a-b8ac-11e5-978a-1fedfe769d7e.png)

**Comment by LisaLNelson** [comment]
Another Instance of the task creator not being notified of a comment on their task. 

![image](https://cloud.githubusercontent.com/assets/9039852/12435106/3d54a404-bed9-11e5-8385-6f775afdf7c0.png)

**Comment by acolter** [comment]
See also https://github.com/openopps/openopps-platform/issues/1236

**Comment by LisaLNelson** [comment]
See #1236
