### ISSUE TITLE
As a task taker, task creator & admin I need to have a clear view of all Open Opportunities.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1218]
Here is a picture of the way the page is appearing.

![image](https://cloud.githubusercontent.com/assets/9039852/12332785/86bc55ca-babe-11e5-91b3-197fa620c97c.png)

**Comment by ultrasaurus** [comment]
Some, but not all have an elipses... and there doesn't need to be that gray line.  Like this:
![image](https://cloud.githubusercontent.com/assets/41906/14511625/960813fa-018d-11e6-9c10-cbaa3d4b4a7f.png)

**Comment by ultrasaurus** [comment]
We could also consider making them stretch vertically in a flowing layout.  @brendansudol might want to consider this when you are looking at the task list page

**Comment by LisaLNelson** [comment]
This no longer appears to be an issue.
