### ISSUE TITLE
As a program administrator, I should be able to see all of the users from my agency

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1224]
with a URL like:  /admin/user/:agencyId  (only show users with matching domain)

show a page like this (maybe with fewer columns to simplify the experience, but definitely need the ability to reset password and make someone else an admin for the agency), the total number of users and the export will also need to be filtered by the domain.

Note: I blocked out email addresses below, but they should link to the person's profile.

![image](https://cloud.githubusercontent.com/assets/41906/14511530/dc195ac6-018c-11e6-8a8a-c116a476b5f7.png)

**Comment by adelevie** [comment]
notes:

- if I am decent with node, but new to Sails, how can I find the code that renders `/admin/user/:agencyId` ?

**Comment by ultrasaurus** [comment]
fixed here:  https://github.com/openopps/openopps-platform/pull/1349
