### ISSUE TITLE
As an admin, I should be able to filter tasks by type

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1226]
As a classification reviewer, I need a way to review all detail opportunity postings before they are published so as to ensure they meet all classification criteria.  

For now we would make the classification reviewer a program administrator.  Even though is being driven by the need to show only Full-Time details, we should filter by any of the types, also On-Going and One Time.  The default should be "All" (similar to the function on the admin dashboard page)

Something like this to allow any admin to filter tasks by type, then the 
![image](https://cloud.githubusercontent.com/assets/41906/12621488/9f864c34-c4d5-11e5-82e0-93f3e0fb33f4.png)

**Comment by mtorres253** [comment]
If there are detail opportunities, there should be a type "Detail" that a user can use to filter this view.
