### ISSUE TITLE
As a program administrator, I want to be able to see all participants in my agency

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1228]
A list of every person with the Opportunity that they are signed up for (with state: completed, in-progress or open)

/admin/participants/:agencyId (if any participant or task creator has matching domain)

note related usability improvements: https://github.com/openopps/openopps-platform/issues/1022

**Comment by kbwagner** [comment]
This works for an agency admin role now.  The full admin will download a CSV.  Will create a new ticket for agency admin.
