### ISSUE TITLE
Confirmation message for full time details, and general confirmation message

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1231]
As an applicant for an opportunity, I want to understand my eligibility before I apply, so that I don't apply for opportunities I'm not eligible to work on.

- [ ] **Scenario: Applicant to full time detail sees appropriate eligibility message in confirmation box**
- Given I'm a registered user
- And there is a full time detail opportunity (see https://github.com/openopps/openopps-platform/issues/1317)
- When I've click on the "I'm In" button on the show page for that opportunity (https://openopps-staging.18f.gov/tasks/[id])
- Then an eligibility confirmation box should appear
- And the confirmation box should contain the following copy

> **Are you eligible to participate?**

> **Supervisor Approval**
> I have my supervisor's approval to apply to this opportunity. 

> **Position/ Performance**

> - I am a GSA employee serving under a permanent appointment and am at the full performance level of my position.
> - I have a performance rating of 3 or higher.
> - I have had no formal, documented disciplinary action within the past year (such as a written warning notice, reprimand, or suspension).
> -I am not participating in a different formal development program.

> **Location** 
> If this opportunity is for a specific location (i.e. it is not a virtual opportunity), I am located within the same commuting area.

> **Grade Level**
> If this opportunity is for a specific grade level (i.e. not to unclassified duties), I am at that grade level or higher. 

- [ ] **Scenario: Applicant applies to a non-full time detail opportunity and sees the correct eligibility message**
- Given I am a registered user
- And there is an opportunity that is NOT a full-time detail
- When I click on the "I'm in" button on the show page for that opportunity (https://openopps-staging.18f.gov/tasks/[id])
- Then I should see a confirmation box
- And that confirmation box should contain the following language

> **Are you eligible to participate?**

> - I have my supervisor's approval to apply to this opportunity.

> - I am a federal employee (not a contractor).

> - If this opportunity is for a specific location (i.e. it is not a virtual opportunity), I am located within the same commuting area.

## Notes
Right now there is just one message for all opportunities. This story is to create one for full-time detail opportunities and one for all other kinds.

Use the existing styles for both versions. The current confirmation box looks like this:
![screen shot 2016-09-07 at 2 21 41 pm](https://cloud.githubusercontent.com/assets/100149/18328997/7473ea60-7506-11e6-9d31-d11b7148c175.png)

**Comment by mtorres253** [comment]
Related to #1231 - hoping we can combine both stories and just have one pop-up.

**Comment by mtorres253** [comment]
Still may combine both messages in one pop-up. @LisaLNelson will work with Rachel to re-do this messaging to make sure it's updated.

**Comment by LisaLNelson** [comment]
Here is the messaging for Full time details.

**Are you eligible to participate?**

Supervisor Approval
I have my supervisor's approval to apply to this opportunity. 

**Position/ Performance**
I am a GSA employee serving under a permanent appointment and am at the full performance level of my position.
I have a performance rating of 3 or higher.
I have had no formal, documented disciplinary action within the past year (such as a written warning notice, reprimand, or suspension).
I am not participating in a different formal development program.
**Location** 
If this opportunity is for a specific location (i.e. it is not a virtual opportunity), I am located within the same commuting area.

Grade Level
If this opportunity is for a specific grade level (i.e. not to unclassified duties), I am at that grade level or higher.

**Comment by mtorres253** [comment]
Let's revisit this estimate @rogeruiz, as it looks like it will be somewhat simpler. One for full-time opportunities, and then the existing one for all other opportunities, correct @LisaLNelson?

**Comment by mtorres253** [comment]
Congratulations @dsummersl on winning this micro-purchase auction!

To get started, please create a pull request referencing this issue. Then enter the URL to your pull request on the auction page (in 18F's Micro-purchase platform) and click "start work".

**Comment by dsummersl** [comment]
Thanks so much @mtorres253 I'll make a PR soon.
