### ISSUE TITLE
As a participant, I want to communicate why I'm doing this...

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1233]
We believe that if the participant says what they want to get out of the project, then everyone will have a better experience (e.g. the task creator can be a better mentor).  This can also address a frequent request where prospective participants have asked for ways they can provide additional information that might lead them to be chosen in the event that multiple people sign up for limited spots.  While these are professional development opportunities, they often require that someone have some baseline skills.

Text: What do you hope to learn from the experience?  Feel free to add a personal note which will be included in your introduction to OpportunityOwnerName who posted this opportunity.

The second step includes the reason for signing up to this particular task.  

Engineering work:
- [ ] Add an input "Tell us about your interest, and what you can contribute" just above the "I'm interested" button. Let's add this to all opportunities (not just full-time details)
- [ ] This information will eventually be added to emails sent to the request approver

If we need to store this data:
- [ ] This data would be saved under the `Volunteer` table
- [ ] This change requires a database migration to the `Volunteer` table to store the intent of the participant.

**Comment by mtorres253** [comment]
@LisaLNelson and I will go over the desired UX and document. I will write acceptance criteria.

**Comment by mtorres253** [comment]
When this is done, we will need to update the notifications to the task creator for full-time and part-time details.

``` yaml 

Here is the applicant’s statement of interest:
<info here from text box on slide 20>

```

**Comment by mtorres253** [comment]
Discussed with @LisaLNelson Rachel and Wendy. We are going to add an input just above the "I'm interested" button so that people can add these comments if they like. The comments will be sent in the email to the approving admin. No need to store for now
