### ISSUE TITLE
update to language on the confirmation dialog when signing up for an opportunity

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1241]
When someone clicks "I'm in" on an opportunity detail page, they currently see a confirmation dialog box, that looks like this:
![image](https://cloud.githubusercontent.com/assets/41906/16492262/0e5f20e2-3e96-11e6-96bf-62ced1928b06.png)

The text needs to be updated to:

**Title**: Are you eligible to participate?

**Text**:

    I understand it is my responsibility to confirm supervisor approval prior to 
    applying to an opportunity.

    I am a federal employee (not a contractor).

    If this opportunity is for a specific location (i.e. it is not a virtual opportunity), I am 
    located within the same commuting area. 

Note: this text should be configured for Federal Open Opps, since general Open Opps doesn't require federal employee status.

**Comment by LisaLNelson** [comment]
Open Opportunities are intended as professional development for federal employees. As is the case is with any training opportunity, your supervisor should determine whether your participation fits into your development plan and follows your agency’s training policies.  

If you or your supervisor has questions about whether an opportunity is considered training, please consult your Office of General Counsel. Also, please contact us if you have any questions about how this works.

It is your responsibility to confirm supervisor approval prior to committing to an opportunity.

**Comment by LisaLNelson** [comment]
Language for platform as a whole.

Are you eligible to participate?
I understand it is my responsibility to confirm supervisor approval prior to applying to an opportunity.

I am a federal employee (not a contractor).

If this opportunity is for a specific location (i.e. it is not a virtual opportunity), I am located within the same commuting area.

**Comment by mtorres253** [comment]
Combining with #1231
