### ISSUE TITLE
as as admin, when I filter by month I see "undefined"

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1243]
To reproduce this, you will need to be logged in as an admin user (which you typically set up when you first install the app: https://github.com/18F/openopps-platform/blob/dev/INSTALL.md#setup-the-database)

Then go to:

https://openopps.digitalgov.gov/admin/dashboard

![image](https://cloud.githubusercontent.com/assets/41906/12990938/b8be5adc-d0c1-11e5-9bce-47a5e224281a.png)

and quarters show Q0 ... not sure if that is related:
![image](https://cloud.githubusercontent.com/assets/41906/12990953/d805a7e2-d0c1-11e5-83dd-841cd26244b1.png)

**Comment by baccigalupi** [comment]
I can grab this. There weren't any tests in this area, and I tried to backfill based on the code. 

What are the expected outputs instead of 'undefined'?

**Comment by ultrasaurus** [comment]
@baccigalupi I think it is just not successfully switching to month labels, since there should be many more columns, with month names or numbers -- I forget which.

Thank you!

**Comment by kbwagner** [comment]
@bmcorum @LisaLNelson this appears to be fixed
Month: 
![image](https://user-images.githubusercontent.com/18709918/37615261-37477050-2b83-11e8-9845-eec02a97f2ac.png)
 Quarter: 
![image](https://user-images.githubusercontent.com/18709918/37615277-4165f264-2b83-11e8-9d7b-d5a34a63c548.png)
