### ISSUE TITLE
As an admin I need to see the Terms of Use and the legal "disclaimer" on the Open Opportunities page.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1250]
Terms of Use:
http://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/open-opportunities-terms-of-use/

Disclaimer:
This site is operated and maintained by GSA's Office of Citizen Services and Innovative Technologies (OCSIT).  The Open Opportunities platform was created for the purpose of providing training and development opportunities for federal employees throughout the federal government.  As is the case with any training opportunity, your supervisor should determine whether your participation fits into your development plan and follows your agency’s training policies.  OCSIT _does not_ review opportunities to determine whether or not they are "official" training before posting on the site.  If you or your supervisor has questions about whether an opportunity is considered training, please consult your Office of General Counsel.

**Comment by ultrasaurus** [comment]
The background color should be the same, but was thinking that the placement should be something like this:  

![image](https://cloud.githubusercontent.com/assets/41906/16491110/7a65502c-3e91-11e6-8019-1feee19a67f4.png)

**Comment by LisaLNelson** [comment]
Here is the **_final language_** to be used:

This site is operated and maintained by GSA's Office of Citizen Services and Innovative Technologies (OCSIT).  The Open Opportunities platform was created for the purpose of providing training development opportunities for federal employees throughout the federal government.  OCSIT does not review opportunities before they are posted on the site.  Participating agencies and interested federal employees should work with their supervisors and servicing Office of General Counsel if they have questions about participating in an opportunity.

**Comment by mtorres253** [comment]
Per discussion with @LisaLNelson This can be closed as we are moving to OPM and language will change anyway
