### ISSUE TITLE
typo on 18F dashboard

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1258]
Found here: https://18f.gsa.gov/dashboard/project/openopps/

"Open Opportunities is creating a network of federal employees that will lead to a more effective, efficient, responsive government by sharing skills and collaborating on projects that support the mission of an agency or the government as a whole. Only 37% of federal employees surveyed believe that creativity & innovation are rewarded. From a total audience of 2.7 million federal employees, the initial target audience are motivate, mission-driven individuals who identify and solve problems for our nation."

I think where you have "motivate" you would want to change it to "motivated."

**Comment by ultrasaurus** [comment]
I sent a note to the 18F dashboard team to see how to get this live on: https://18f.gsa.gov/dashboard/project/openopps/

**Comment by acolter** [comment]
Sent a pull request to fix the typo.

**Comment by ultrasaurus** [comment]
@acolter so are about.yml files no longer a thing?

**Comment by ultrasaurus** [comment]
@acolter thanks, by the way!

**Comment by acolter** [comment]
@ultrasaurus My web development abilities haven't progressed much since about 2003, so it is entirely possible that there was a better way to do this. At any rate, the PR appears to be marked "in progress."
