### ISSUE TITLE
As a GSA employee I would like an easy way to find GSA Opportunities .

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1271]
As a GSA employee, I need a way for me to easily find and access a GSA section from the home page.  This would link to a page that can be shared that will take people to a “GSA Only” page (https://github.com/18F/openopps-platform/issues/1299)

Options:  
1. explore some kind of visual treatment / call-to-action on the logged in home page (member dashboard)
2. a specific URL that OHRM could send out to GSA employees that would take participants to GSA only rotation program only (maybe including GSA part-time projects too, maybe promote federal-wide in some way) https://github.com/18F/openopps-platform/issues/1299
3. Something on the opportunities page.

**Comment by ultrasaurus** [comment]
Here's an alternate logged in home page that could address this need:

![image](https://cloud.githubusercontent.com/assets/41906/14828654/cf9e4ed6-0b9c-11e6-99f9-e083b8e01293.png)

**Comment by ultrasaurus** [comment]
another idea:

![image](https://cloud.githubusercontent.com/assets/41906/14830879/e038740a-0ba7-11e6-912d-9ab58ebc2ac8.png)

**Comment by mtorres253** [comment]
Computed property on the opportunity. Every time it saves the opportunity, it checks who the requestor is and adds that requestor's agency. The migration would be to trigger a save in every opportunity. 

Any time the opportunity is edited, it changes the agency.
