### ISSUE TITLE
usability test for Full-Time detail creation experience

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1279]
Find some actual GSA employees, to find out whether they can use the new form and what kind of addition work is required (or nice to have):
 https://github.com/18F/openopps-platform/issues/1230

**Comment by ultrasaurus** [comment]
We should do this after updating the text:  https://github.com/18F/openopps-platform/issues/1274

**Comment by ultrasaurus** [comment]
assigning to @LisaLNelson since she had an idea for someone who might be able to help with this

**Comment by ultrasaurus** [comment]
Feedback: a little confusing to some with suggestion of changing section to say "Title" and/or descriptive text "Enter a title for your opportunity posting"  -- idea to test in some of the usability tests

**Comment by LisaLNelson** [comment]
Usability test completed.  Chart of issues: https://docs.google.com/document/d/1Bc-3JlQuSIw4IJEkUXtNbAJ86FFgYB9b41PDSWbqWEQ/edit
