### ISSUE TITLE
when someone is removed from a task after it is completed, should their badge go away?

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1280]
It appears that user 1931 has a badge for task 477, but has been removed from the task.... should their badge be removed too?

**Comment by ultrasaurus** [comment]
I believe this is the root cause of #1278

**Comment by ultrasaurus** [comment]
I think it would be weird for the badge to be removed, but would be good to understand the backstory here

**Comment by LisaLNelson** [comment]
A reason for this would be that someone did not actually participate.  Could have been a team and one person did not engage.

**Comment by kbwagner** [comment]
You can no longer remove a participant from an opportunity once it is completed.

**Comment by kbwagner** [comment]
the badge does not get assigned until the opportunity is marked completed and at that point you cannot make any additional changes thus non issue
