### ISSUE TITLE
as a developer, changes to the code should be easier (upgrade Node / Sails)

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1288]
To speed development (and position us to easily keep up with security patches and other routine library improvements), we want to be on a recent version of SailsJS and Node.
- Node 4.x  (use LTS version of Node)
- Sails 0.12.x 

Approach:
- start with sails new and move existing code into new app
- Work with existing database, at least till we have authentication working
- Move to USWeb Design Standards (at least start that way, see if we can clean up CSS along the way)
- i18n is now built into Sails, use that
- Remove (e.g. don't migrate) features we're not using
- Create an event log to replace waterline-postgresql soft-delete branch
- Consider moving to an Event Sourcing pattern, based on the event log

Don’t need to support
- SSPI authentication
- Projects aka Working Groups
- Events
- like
- UserSetting

Open questions
- should we just use Google Auth (and not implement MyUSA)?
- what runs the cron tasks? something in cloud foundry?

TO DO
- [x] basic authentication  
  - [x] user / passport models
  - [x] User model tests
  - [x] AuthController with tests 
    - [x] logout, login
    - [x] register: `https://openopps-test.18f.gov/api/auth/local/register name=Sarah+3+Gov&username=sarah.allen%2B3%40gsa.gov&password=XXX!&tags%5B%5D=837&tags%5B%5D=36&json=true`
- [x] backend test framework
- [x] Back-end for current registration workflow 
  - [x] check for username: `https://openopps-test.18f.gov/api/user/username/whatever@agency.gov`
  - [x] Tag models / controller with tests
    - [x] `https://openopps-test.18f.gov/api/ac/tag?type=agency&q=GS`
- [x] front-end basics
  - [x] not logged in homepage: backbone basics, underscore, jquery
  - [x] sign-up / log in UI
- [x] basic tasks
  - [x] tasks page displays data
  - [x] task model with tests
- [ ] admin
  - [x] pages render with no data
  - [x] user list displays
  - [x] task panel
    - [x] display tasks in each state
    - [x] task actions
  - [ ] participants panel displays data
  - [x] dashboard overview displays data
- [ ] file (profile image, store in S3)
  - [x] local file upload (for development)
  - [ ] s3 (for cloud foundry)
- [x] notifications
  - [x] model
  - [x] upgrade Node Mailer
  - [x] re-enable notifications for all events
  - [x] tests
- [x] complete authentication
  - [x] forgot password
- [ ] Temporarily disabled (site can be tested without these)
  - [x] comment
  - [ ] attachments
  - [x] admin export
  - [x] Google Auth or MyUSA
- [x] logged in dashboard
  - [x] There are NN open opportunities right now.
  - [  ] Latest acheivements
  - [x] welcome: list of recently joined users
- [ ] event log (replacing soft delete)
- [ ] demo data script
  - [x] users
  - [ ] tasks created (with badges for task creators)
  - [ ] users signed up for tasks 
  - [ ] users complete tasks (with badges)
  - [ ] users have locations

Clean up
- [ ] Review / polish across all pages
- [ ] Review test coverage, specifically around authorization
- [x] review TODO comments

Remove
- [ ] all references to:  ui.project.show

Refactors
- [ ] agency
- [ ] skills
- [ ] improved navigation for admin
- [ ] alternate approach to comments

**Comment by ultrasaurus** [comment]
starting work here:  https://github.com/18F/openopps-platform/tree/new

**Comment by bmcorum** [comment]
Outdated with the migration away from sails
