### ISSUE TITLE
As a federal employee, when I browse opportunities, I would like to see which are "virtual"

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1293]
Right now, we only display a location when a specific location is required.  Virtual opportunities should show as “virtual” because it might be confusing if only the specific location opportunities show a location.

In the image below, the opportunity on the right does not have a location requirement:

![image](https://cloud.githubusercontent.com/assets/41906/14510538/e652fb6a-0186-11e6-869a-913e53c59d8a.png)

Proposal that it appear like this:
![image](https://cloud.githubusercontent.com/assets/41906/14510661/55fc511e-0187-11e6-9429-8f8f80f7ca9d.png)

**Comment by LisaLNelson** [comment]
Completed
