### ISSUE TITLE
npm doesn't install dependencies (sometimes?)

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1297]
Sometimes I get this error when creating a fresh install...

```
Error: Cannot find module 'sails/node_modules/express'
```

I think [this article](http://krasimirtsonev.com/blog/article/Fun-playing-with-npm-dependencies-and-postinstall-script) explains why.

workaround:

```
cd node_modules/sails
npm install
```

reproduced with:  
- node 4.2.2, npm 3.8.6
- node 5.8.0, npm 3.7.3

**Comment by kbwagner** [comment]
Sails is no longer used.
