### ISSUE TITLE
As an admin I need to get notification when a new task has been submitted.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1302]
Daniel Yi submitted a task today (04/27/2016) and the system did not send me notification.  I would not have known the task was there if he had not sent me a separate email.

**Comment by LisaLNelson** [comment]
I think this may have been fixed

**Comment by acolter** [comment]
@LisaLNelson I saved a draft task yesterday and submitted it today. Did you get notifications for those? If yes, then we might be able to close this issue.

**Comment by LisaLNelson** [comment]
@acolter I did the the notification.
