### ISSUE TITLE
installation issues on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by mciolett** [openopps/openopps-platform#1304]
hello.  I am attempting to install this application on a UBUNTU openstack instance with the following hardware config:
 4GB RAM | 2 VCPU | 20.0GB Disk
using the install notes: 
https://github.com/18F/openopps-platform/blob/dev/INSTALL.md
debug file contents:
ubuntu@openopphost:~/openopps-platform$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'migrate' ]
2 info using npm@2.1.18
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'premigrate', 'migrate', 'postmigrate' ]
6 info premigrate openopps-platform@0.9.4
7 info migrate openopps-platform@0.9.4
8 verbose unsafe-perm in lifecycle true
9 info openopps-platform@0.9.4 Failed to exec migrate script
10 verbose stack Error: openopps-platform@0.9.4 migrate: `$npm_package_config_grunt db:migrate:up`
10 verbose stack Exit status 3
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:766:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
11 verbose pkgid openopps-platform@0.9.4
12 verbose cwd /home/ubuntu/openopps-platform
13 error Linux 3.2.0-75-virtual
14 error argv "node" "/usr/bin/npm" "run" "migrate"
15 error node v0.10.37
16 error npm  v2.1.18
17 error code ELIFECYCLE
18 error openopps-platform@0.9.4 migrate: `$npm_package_config_grunt db:migrate:up`
18 error Exit status 3
19 error Failed at the openopps-platform@0.9.4 migrate script '$npm_package_config_grunt db:migrate:up'.
19 error This is most likely a problem with the openopps-platform package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     $npm_package_config_grunt db:migrate:up
19 error You can get their info via:
19 error     npm owner ls openopps-platform
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

any direction or assistance would be greatly appreciated.

**Comment by ultrasaurus** [comment]
so, it looks like `npm run migrate` is failing, can you try to run just that command and paste in the output?

**Comment by mciolett** [comment]
thanks for the quick reply, sorry for the delay in response here is the log for running the 'npm run migrate'


ubuntu@openopp-wc-c01:~/openopps-platform$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'migrate' ]
2 info using npm@2.1.18
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'premigrate', 'migrate', 'postmigrate' ]
6 info premigrate openopps-platform@0.9.4
7 info migrate openopps-platform@0.9.4
8 verbose unsafe-perm in lifecycle true
9 info openopps-platform@0.9.4 Failed to exec migrate script
10 verbose stack Error: openopps-platform@0.9.4 migrate: `$npm_package_config_grunt db:migrate:up`
10 verbose stack Exit status 3
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:766:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
11 verbose pkgid openopps-platform@0.9.4
12 verbose cwd /home/ubuntu/openopps-platform
13 error Linux 3.2.0-75-virtual
14 error argv "node" "/usr/bin/npm" "run" "migrate"
15 error node v0.10.37
16 error npm  v2.1.18
17 error code ELIFECYCLE
18 error openopps-platform@0.9.4 migrate: `$npm_package_config_grunt db:migrate:up`
18 error Exit status 3
19 error Failed at the openopps-platform@0.9.4 migrate script '$npm_package_config_grunt db:migrate:up'.
19 error This is most likely a problem with the openopps-platform package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     $npm_package_config_grunt db:migrate:up
19 error You can get their info via:
19 error     npm owner ls openopps-platform
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by ultrasaurus** [comment]
@mciolett sorry to be un-responsive.  I have no idea...

Check out if you have grunt installed with sails.  I've sometimes run into an issue where things don't get installed quite the way you might figure they should be (see https://github.com/18F/openopps-platform/issues/1297):

`ls ./node_modules/sails/node_modules/.bin/`

You should see grunt there.  If not 

```
cd ./node_modules/sails
npm install
```

**Comment by mciolett** [comment]
@ultrasaurus I appreciate the response.  I did verify that grunt is installed.  The error during migration I keep getting is:
[ERROR] error: unrecognized configuration parameter "lock_timeout"
which appeared to not be an option in postgresql 9.2 but available in 9.3 and higher.  I tried upgrading to 9.3 and 9.4 but I continue to get that same error.

**Comment by ultrasaurus** [comment]
I'm running postgres 9.5.2 -- you could try that.

Alternately, you could try removing [this line](https://github.com/18F/openopps-platform/blob/dev/migrations/sqls/20160316223014-initial-schema-up.sql#L6) from the initial schema sql and see if that helps

**Comment by kbwagner** [comment]
Per Brice - That is a really old OS version and we should NOT support it (latest major version is 16)
