### ISSUE TITLE
As a task taker I need to be able to accurately tell how much time the task will take.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1310]
This comment was received on our annual survey:
"Hard to imagine how to dive in. For example, I just saw one opp listed that intrigued me: "Help document the new USAGov Platform API." I believe the phrase that caught my attention was "Technical Writer." I am a process oriented person with better than average writing skills. However, the description states 24-40 hours per week. To truly be able to micro-task, and build my own self-confidence as well as gain the support of my boss, I need to start with something that might take an hour or two, or even an hour a day for two to three days a week, perhaps for a couple of weeks max. If you can further lower the barriers to participation I believe you could truly strike gold!"

When I looked at the task again and talked to the task creator he wanted to denote the task would take between 24-40 hours total spread out over a few weeks but when he clicked the button for 16-24 hours it showed up on the task as 16-24 hours a week. 

![screen shot 2016-05-06 at 1 42 16 pm](https://cloud.githubusercontent.com/assets/9039852/15081310/63fd0d9c-1390-11e6-8edd-13138928eb5b.png)

![screen shot 2016-05-06 at 1 41 10 pm](https://cloud.githubusercontent.com/assets/9039852/15081329/7fe48800-1390-11e6-8428-970d8d164a9a.png)

**Comment by kbwagner** [comment]
Merging this into ticket 1644 and closing.
