### ISSUE TITLE
as a GSA employee, I would like to mark an opportunity as GSA-only

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1317]
![image](https://cloud.githubusercontent.com/assets/41906/15230653/9b39ea9a-184b-11e6-9100-3641ba16c722.png)

For full-time details the checkbox would always be checked (and disabled):
![image](https://cloud.githubusercontent.com/assets/41906/15230696/db12f4cc-184b-11e6-81cb-4db76aa023f5.png)

**Comment by rogeruiz** [comment]
Running into an issue here with the migration concerning what acronyms to use for which agency. Some have a `(XX)` acronym already in their name, and others do not. I will be migrating the `agency.data` for those agencies, but we'll need to do something about the remaining agencies eventually.

**Comment by rogeruiz** [comment]
being worked on in #1450

**Comment by mtorres253** [comment]
I think that's fine @rogeruiz for now

**Comment by rogeruiz** [comment]
We should be able to do this now on Production. This feature had already been developed and just needed a data migration to finalize it. I want to keep track of this feature while working on `Full Time Details` features and reopen if we need to fix any of the work previously done here.
