### ISSUE TITLE
an Opportunity requestor should be able to remove a participant

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1345]
this works for an administrator, but as an Opportunity creator I get prompted to login when I remove a participant and save

**Comment by brodydittemore** [comment]
Removing a participant, then clicking save, may be causing the site to crash.

**Comment by bmcorum** [comment]
Appears to be related to the CSRF Token issue. Not sure if the issue originates at the client or the server at his time.

- [ ] Check for CSRF Token validity
- [ ] Why prompt for user login on participant removal if already logged in? (i.e. can we be on this page if not logged in?)

**Comment by bmcorum** [comment]
To test you will need to create an opportunity if you have not already done so. Have someone apply (select "I'm interested" button), then you should be able to remove the participant without error and without being prompted to log in.
