### ISSUE TITLE
OpenOpps: Creator should be able to add participant 

### ISSUE THREAD

**Issue by JoanneMcGovern** [openopps/openopps-platform#1346]
As an opportunity creator, I should be able to add a participant
![screen shot 2016-05-18 at 9 27 53 am](https://cloud.githubusercontent.com/assets/19430796/15360515/dcc0be28-1cdb-11e6-8483-419fb6eff9b9.png)

**Comment by ultrasaurus** [comment]
It appears that it has always been that only admins can add participants... creators can assign or remove.  I do think this is a good idea.  

@LisaLNelson -- what do you think?

**Comment by mtorres253** [comment]
This may be a good candidate for micropurchase. @LisaLNelson will think about it and we can prioritize as indicated
