### ISSUE TITLE
Graphics should be hi-res (retina) compatible

### ISSUE THREAD

**Issue by dogweather** [openopps/openopps-platform#1354]
The assets have a fuzzy appearance on retina devices. E.g.:

<img width="292" alt="screen shot 2016-05-19 at 3 28 37 pm" src="https://cloud.githubusercontent.com/assets/150670/15411803/6749b42c-1dd7-11e6-9535-5d9f5d3869e4.png">

**Comment by LisaLNelson** [comment]
We need a high resolution file.

**Comment by kbwagner** [comment]
Resolved with the implementation of design standards.
