### ISSUE TITLE
need browser integration tests

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1363]
We used to have some tests that did full integration testing with PhantomJS.  When we upgraded everything on 0.10.0, I couldn't get them working again (Phantom would report "Parse Error" without a stack trace).  Work in progress in this brance:

https://github.com/openopps/openopps-platform/tree/test-browser

**Comment by Piglady64** [comment]
All browsers are being used in systems testing. No longer needed. Closing
