### ISSUE TITLE
as a developer, I would like "agencies" to be easier to work with

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1375]
The tagEntity model with its json data attribute was fine for prototyping, but now that the platform is working well, it would be easier to work with a separate model (and we'd like to call it something that is not specific to the government use case).

Proposal:
- Org model
  - name
  - abbr
  - allow_task_restriction
  - allow_full_time
- org_memberships model : userId, orgId, role
  - roles:  admin, member, (future: interested)

Users with Org Admin role would have admin rights for users/tasks belonging to the specific org:
- users (add admins, disable, edit profiles)
- tasks (publish, add/remove participants, edit tasks)

There would be a many-to-many relationship: `User` <--> `Org` (through the `org_memberships` table).  In the short term, the UI would only expose one-to-many:  Org has many Users

The current UI wouldn't change for the federal government use case.  When signing up, people choose their agency (which would be an associated "org" model, pre-populated with a script).  However, this would allow more flexibility in non-profit use case, where we believe individuals will volunteer for different orgs, and in the future, we could define different gov orgs that span agencies.  We anticipate that for the non-profit use case, we might want admin approval of org membership, which this model would support (potentially with a new role `interested` if someone has expressed an interest in an org, but is not yet an approved member).

Related:
- https://github.com/openopps/openopps-platform/issues/1194 Tasks should have an agency
- https://github.com/openopps/openopps-platform/issues/1232 As an admin or agency admin, I want to be able to modify agency configuration

**Comment by ultrasaurus** [comment]
Note that with [SailJS through associations](http://sailsjs.org/documentation/concepts/models-and-orm/associations/through-associations) we can't access additional attributes on the join table (although they could be queried directly).  Might be simple enough to have an isAdmin flag on the org_memberships table, then for any given user there would be one row per org, and we could manually query the org when we load the user, using Sails associations just for the user -> membership association.

**Comment by kbwagner** [comment]
Closing per backlog review 3/29/18
