### ISSUE TITLE
As a task creator I want to be able to see information on a task taker on the task.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1377]
Right now when I hover over the person's name who expressed interest in the task all I see is their name.
![screen shot 2016-06-13 at 5 56 24 pm](https://cloud.githubusercontent.com/assets/9039852/16024476/2ebf77c8-3190-11e6-8043-1bec61a8e84b.png)

**Comment by kbwagner** [comment]
Closing - this is no longer necessary.
