### ISSUE TITLE
As an admin I do not want to see the sails icon on the tab.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1378]
It will be confusing to the user to see the sail on the tab.
![screen shot 2016-06-13 at 5 58 40 pm](https://cloud.githubusercontent.com/assets/9039852/16024523/7c7a465a-3190-11e6-87d7-bb5e7005f3b3.png)

**Comment by acolter** [comment]
@LisaLNelson Is the problem that this is using the wrong icon or that there should be no icon on the tab at all?

**Comment by LisaLNelson** [comment]
We use the digitalgov icon.  No one knows what Sails is.  It is not the end of the world but it needs replaced.
