### ISSUE TITLE
Some tasks fail to render

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1380]
I have 2 assigned tasks in Open Opportunities and I tried to open one and I just get
![screen shot 2016-06-14 at 10 24 18 pm](https://cloud.githubusercontent.com/assets/9039852/16066136/c7d8c07e-327e-11e6-817b-1644e72598fd.png)
 a blank screen.

**Comment by ultrasaurus** [comment]
this happens when the task-length tag is missing

I can reproduce with:  https://openopps-staging.18f.gov/tasks/498
