### ISSUE TITLE
As a user I need an email address where I can contact someone that does not bounce back.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1384]
As user sent the following email: when i emailed the address listed at the bottom of the webpage (openopps-platform@googlegroups.com) I received a bounceback email stating the following:

"Hello maria.alberty@nasa.gov,

We're writing to let you know that the group you tried to contact (openopps-platform) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

* You might have spelled or formatted the group name incorrectly.
* The owner of the group may have removed this group.
* You may need to join the group before receiving permission to post.
* This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/.

Thanks,

Google Groups"

These are serious functionality issues with the website and as a digital.gov product, needs some retooling to be an effective product within the user community.

**Comment by ultrasaurus** [comment]
the google group requires that someone sign up for it before emailing.  I think we should make this configurable.
