### ISSUE TITLE
As a task creator I need to be able to add an opportunity to the platform.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1385]
When I click on the +Opportunity button it goes to another [URL ](https://openopps.digitalgov.gov/tasks/new) but the page does not open. 

![screen shot 2016-06-15 at 8 35 28 pm](https://cloud.githubusercontent.com/assets/9039852/16101958/fa89bdd8-3338-11e6-9723-88f7d1e62059.png)

**Comment by ultrasaurus** [comment]
strange... can't reproduce this now.  Will leave open and test more tomorrow
