### ISSUE TITLE
Work being done on ATO compliance on the 18F fork

### ISSUE THREAD

**Issue by rogeruiz** [openopps/openopps-platform#1391]
We are tracking a milestone from the 18F fork of `openopps-platform` which is a
**number 1** priority for the 18F team. You can use the following URL to track
it. Thanks!

https://github.com/18F/openopps-platform/milestones/ATO%20Compliance

**Comment by EricSchles** [comment]
The issue appears to be slightly unclear - @rogeruiz What should I be testing for / validating?  The link appears to be dead on the 18F side or possibly already closed?
