### ISSUE TITLE
As an admin and participant I would like to be able to see the people tab.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1396]
As an admin the people tab needs to be reactivated as it is important to showing potential customers the breadth and reach of Open Opportunities.  

As an admin and user the people tab is important for searching for people from specific agencies or with certain skills.

## Acceptance Criteria 
- [x] The People tab is accessible to Users 
- [x] The People tab is accessible to Admins 
- [x] The People tab is populated with a list of users 
  - [x] Name 
  - [x] Title 
  - [x] Agency 
  - [x] Location

**Comment by rogeruiz** [comment]
@mtorres253 will look into this one to see why this was disabled.

**Comment by mtorres253** [comment]
Looks like the People tab was disabled by @ultrasaurus (https://github.com/openopps/openopps-platform/commit/6eefde08a4feccfd4a60267497d9396fb3f79b8f) because there it wasn't working properly. There seems to be a lot of code for the Profiles page (People page) but can't tell what went wrong.

**Comment by ultrasaurus** [comment]
This was not upgraded.  I just turned it off so we could get the security fix deployed.  I assume there need to be a few code changes to work with the new version of JS libraries and some refactors of the Sails associations that we did, but I honest didn't even look at it.

**Comment by mtorres253** [comment]
Let's get on the same page with @LisaLNelson about what it means to have a functional people tab sot that we have a target to hit.

**Comment by rogeruiz** [comment]
This is now working on [Staging](https://openopps-staging.18f.gov/profiles). Please :eyes: take a look and verify the scope of work that is left to do here.

**Comment by rogeruiz** [comment]
@EricSchles will be bringing the map back 🙌

**Comment by brodydittemore** [comment]
The People Tab is currently being populated in Chrome and IE 11 as of 8/31/17.

![Screenshot](https://user-images.githubusercontent.com/4691642/29935653-7c061e86-8e4d-11e7-8945-c8142dde0158.png)

@LisaLNelson Is there additional Acceptance Criteria that needs to be delivered here?

**Comment by LisaLNelson** [comment]
@brodydittemore there is no more acceptance criteria.

**Comment by brodydittemore** [comment]
This AC, "The People tab populates within a reasonable amount of time" is being split and moved to #1503
