### ISSUE TITLE
As an admin I need to be able to disable registrants who are not federal employees.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1399]
There are a few people who have recently registered who are not federal employees and I am not able to disable them.  When I click on the green check mark t just spins and stays the green checkmark. In addition to the person in the image below I tried two others's 2765 ejtillman10@gmail.com and 2767 stephanie@winnermint.com
![screen shot 2016-07-05 at 5 30 23 pm](https://cloud.githubusercontent.com/assets/9039852/16600645/2fcd705a-42d6-11e6-82c8-1e9a7ce330e8.png)

**Comment by mtorres253** [comment]
This is a bug - the functionality to disable registrants should exist. If we fix this bug, then the disable functionality will be available for this use case

**Comment by LisaLNelson** [comment]
Done
