### ISSUE TITLE
As a task creator and admin I need to be able to see the template to add an opportunity.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1405]
Shannon Dahn is trying to post a couple time sensitive tasks and was not able to see the template when she clicked on plus opportunity.  Here is what she said.  "When I click on the “+Opportunity” button, nothing happens. I’ve tried two different browsers. I’m wondering, is this the right button to create a posting, and if so, am I doing something wrong? " The issue occurred for her in IE and Chrome.  I was not able to recreate but Ashley Wichman tried and had the same problem.  She said when she clicked +opportunity "the header and footer appear, but there is nothing in between."

![screen shot 2016-07-13 at 2 10 09 pm](https://cloud.githubusercontent.com/assets/9039852/16814862/a830fa46-4905-11e6-8b89-6d90278b5ae8.png)

**Comment by awichman** [comment]
I was having issues in Chrome (using the GSA network) about 25 minutes ago, but it is working now.

**Comment by rogeruiz** [comment]
:eyes: https://github.com/openopps/openopps-platform/issues/1404#issuecomment-232443456

**Comment by ultrasaurus** [comment]
When isolating the bug, I realized there is a work-around for this: if you reload the page after logging in, then it works.  I didn't test the other user cases interactively when I created the User class and refactored how agencies were defined.  Really need some front-end tests.

**Comment by rogeruiz** [comment]
@ultrasaurus yeah, I agree. I have some ideas based on what we talked about during our last pairing session about having a database with specific user types and opportunity types for better testing. I will add a page to the wiki with user types and opportunity types that should be tested whenever we release a new version. Maybe under [Releasing Midas](https://github.com/openopps/openopps-platform/wiki/Releasing-Midas), I'll add a `Manual Testing` checklist to try to catch cases like this one.
