### ISSUE TITLE
As a task creator (admin) I would like to be able to add links in the description when creating an opportunity.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1407]
This is something that worked but recently broke. The link button does not work in the opportunity description. When you highlight the section to be linked and click the link "icon" nothing happens except the link icon gets highlighted in blue.
![screen shot 2016-07-12 at 4 25 14 pm](https://cloud.githubusercontent.com/assets/9039852/16782363/406bc5e8-484d-11e6-8a6d-707f417f85c9.png)
 and nothing happens except the bold button gets highlighted in blue.

**Comment by acolter** [comment]
This looks like the same issue in #1406. None of the WYSIWYG controls are working for the description text box.
