### ISSUE TITLE
As an admin I would like to see all new task submissions on the on the recent activity section of the dashboard.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1408]
This something that recently broke.  It used to be that each new task submitted or posted was shown in the recent activity.   Now the only thing that shows is new people joining.
![screen shot 2016-07-12 at 6 29 49 pm](https://cloud.githubusercontent.com/assets/9039852/16785897/a572c764-485e-11e6-91ec-0f880a8ba187.png)

**Comment by mtorres253** [comment]
Per @LisaLNelson this is still an issue. It may not be a huge problem for now. Let's change it to P3 for now.

**Comment by kbwagner** [comment]
3/29/18 - This shows up now.
