### ISSUE TITLE
Remove or replace MyUSA authentication

### ISSUE THREAD

**Issue by yozlet** [openopps/openopps-platform#1414]
[MyUSA is going away](https://github.com/18F/myusa/issues/762#issuecomment-232811774) and should either be replaced with [an alternative authentication system](https://github.com/18F/myusa/issues/762#issuecomment-232811774) or just removed. While there's no current set date for MyUSA to be turned off, I strongly recommend completing this by September.

Whichever option you choose, however, be sure that users who previously logged in using MyUSA are still able to log into their existing OpenOpps accounts via alternative means.

For this task, we want to just notify users who ONLY have MyUSA authentication, that they need to also have a username and password. It may be the case that everyone already has a username and password, so we don't need to do anything but notify them that MyUSA is being discontinued. To discuss at the status meeting
- [ ] **Scenario: MyUSA is no longer an option on the log-in/register page**
- Given I am a new or returning user
- When I click on the sign-in link and I go to on the "Login or Register"
- Then I no longer see the section labeled "Login with MyUSA"
- And instead, I should see the following message

> MyUSA authentication is no longer available
> Please user your email and password to login. If you don't have a password, please click the "Forgot your password?" to get one via email.

**Comment by LisaLNelson** [comment]
Completed
