### ISSUE TITLE
If Reddis is down, error page is not ideal

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1419]
When reddis crashes, there is a sails.js error page. We need to fix this for ATO purposes and also to make the user experience better. 
1. Change error page to an open opps error page
2. Make sure alerts are in place for reddis outage

## Acceptance Criteria 
- [ ] Change error page to an open opps error page

**Comment by rogeruiz** [comment]
This is where the application fails when Redis is done. We're looking for a `500` error code to through here. https://github.com/openopps/openopps-platform/blob/dev/api/controllers/MainController.js#L10

**Comment by rogeruiz** [comment]
Assigning this to @jpang01

**Comment by mtorres253** [comment]
This may be taken care of. Let's discuss in meeting tomorrow.

**Comment by brodydittemore** [comment]
Split alerts part of the issue to #1534
