### ISSUE TITLE
Re-enable front-end tests

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1420]
Front end tests were disabled but need to be re-enabled so that we can start deploying to CI again.

**Comment by ultrasaurus** [comment]
Sadly, this is not as simple as turning them on.  The new Javascript fails to parse with Phantom: https://github.com/openopps/openopps-platform/issues/1363  -- it would be worth trying again with the latest version of Phantom, but if that issues persists, I would recommend that we try a completely different approach.   I was thinking of a set of front end unit tests for starters.

**Comment by rogeruiz** [comment]
Assigning this to @jfredrickson5

**Comment by rogeruiz** [comment]
This line contains the browser tests: 
https://github.com/openopps/openopps-platform/blob/test-browser/package.json#L118
This branch has the work associated with the Browser tests. The may not be in a working state. But, they should all exist on this branch. https://github.com/openopps/openopps-platform/tree/test-browser

Parse error is discussed in #1363

**Comment by jfredrickson5** [comment]
I got the app running in a local Docker environment. I'll take a look at the tests now.

**Comment by jfredrickson5** [comment]
@rogeruiz My original Docker env was having network problems for some reason (even after reloading docker-machine env settings) so I just recreated a fresh container. This time I am having trouble installing dependencies per https://github.com/openopps/openopps-platform/blob/dev/INSTALL.md#deploy-openopps-as-a-docker-container-from-the-docker-hub-mac-windows-linux.

Following the instructions, this is the part I am stuck on:

```
npm i -g npm@3
npm install -g node-gyp@3.3.1 grunt-cli@0.1.13
npm install
npm run init
npm start
```

Specifically, `npm install` is giving me errors when it attempts to install the strip-ansi dependency.

```
root@f9f07b38130d:/usr/src/app# npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN lifecycle sails@0.12.4~preinstall: cannot run in wd %s %s (wd=%s) sails@0.12.4 node ./lib/preinstall_npmcheck.js /usr/src/app/node_modules/.staging/sails-26b8711c
openopps-platform@0.11.0 /usr/src/app
`-- UNMET DEPENDENCY sails@^0.12.3

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.40
npm ERR! npm  v3.10.6
npm ERR! path /usr/src/app/node_modules/anchor/node_modules/geojsonhint/node_modules/jsonlint-lines/node_modules/nomnom/node_modules/chalk/node_modules/strip-ansi/cli.js
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chmod '/usr/src/app/node_modules/anchor/node_modules/geojsonhint/node_modules/jsonlint-lines/node_modules/nomnom/node_modules/chalk/node_modules/strip-ansi/cli.js'
npm ERR! enoent ENOENT, chmod '/usr/src/app/node_modules/anchor/node_modules/geojsonhint/node_modules/jsonlint-lines/node_modules/nomnom/node_modules/chalk/node_modules/strip-ansi/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
root@f9f07b38130d:/usr/src/app# 
```

Here's the log: [npm-debug.log.txt](https://github.com/openopps/openopps-platform/files/425959/npm-debug.log.txt)

Any clue what's going on?

**Comment by EricSchles** [comment]
Frontend tests re-enabled- 

Currently failing on:
```
1) LocationController api/location/suggest query location:
     AssertionError: expected {} to deeply equal [ Array(10) ]
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at containsSanLocations (test/integration/controllers/LocationController.test.js:18:14)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1548:8)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by EricSchles** [comment]
Front end tests re-enabled - passing locally and on CircleCI - above test is no longer relevant since we removed the map.  So we don't need the location controller.

**Comment by EricSchles** [comment]
How the fix happened:

I updated casperjs to "1.1.3", and added:
"webpack": "1.13.2", 
"babel-core": "6.14.0",
    "babel-loader": "6.2.5",
    "babel-preset-es2015": "6.14.0",
