### ISSUE TITLE
Start deploying from CI again

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1421]
We are not currently deploying from CI but we need to fix this so that future teams can more easily deploy changes and bug fixes. This story depends on #1420

### Acceptance Criteria
- [ ] Travis builds successfully

**Comment by rogeruiz** [comment]
The project currently fails on `CircleCI` because there is no Postgresql database.

**Comment by rogeruiz** [comment]
The deployment CI is `Travis` for the purpose of pushing to `cloud.gov`. The CI for `CircleCI` is just for the purpose of testing the project without a deployment set. #1436 covers the latter for now.

**Comment by ultrasaurus** [comment]
Note:  
* Travis configuration is here:  https://github.com/18F/openopps-platform/blob/dev/.travis.yml
* You can see the failing build here:  https://travis-ci.org/18F/openopps-platform  (also linked from the "badge" in the README
