### ISSUE TITLE
Apply to opportunity - change language on button

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1428]
As an applicant for an opportunity, I want it to be clear to me that I'm only applying for it, so that I don't think that it will automatically be assigned to me.

**Context**
- Given I am a registered user
- And there is an opportunity
- And I am qualified to apply for it

- [ ] **Scenario: Registered user sees "I'm interested" button on opportunity page**
- When I go the view page for that opportunity
- Then I should see a button labeled "I'm interested"

- [ ] **Scenario: Registered user expresses interest for an opportunity and sees that their application was received**
- And I'm on the view page for an opportunity
- When I click that button
- Then the system should record that I applied to that opportunity
- And the button should not be visible
- And I should see this message "Application received"
- And I should continue to see this message until the opportunity is assigned

This story is to replace the current "I'm In" language to make it clearer to applicants that they are not automatically assigned to the opportunity.

**Comment by mtorres253** [comment]
Micro-purchase auction started today

**Comment by sowmyakakkireni** [comment]
@mtorres253 - Please take a look at https://github.com/openopps/openopps-platform/pull/1470 and let us know if there are any questions/concerns. Thanks!
