### ISSUE TITLE
Admin can select one or more applicants to assign to an opportunity

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1429]
As an admin, in order to reduce confusion when I assign an opportunity, there should be an easy way for me to select one (or more) applicants to work on a task, and those applicants should be notified that they were selected, and all other applicants should be notified that they were not selected.
- [ ] **Scenario: Admin sees a way to assign an opportunity via the UI**
- [ ] **Scenario: Admin assigns one or more applicants to an opportunity via the UI**
- [ ] **Scenario: System sends emails to applicants that have been assigned an opportunity**
- [ ] **Scenario: System sends emails to applicants who have not been assigned**
## Notes

We want to make sure all the scenarios above are addressed, but we would need some help with the UX as this involves some workflow that hasn't been specified yet.

**Comment by mtorres253** [comment]
@LisaLNelson and I will meet to go through the UX and desired behavior. I will update acceptance criteria accordingly. Possible micropurchase?

**Comment by kbwagner** [comment]
Per March 2018 backlog review: Merging with 1878 and closing.
