### ISSUE TITLE
As an opportunity creator, I need a way to cancel my opportunity.

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1430]
Acceptance Criteria:
- For all job types, provide a cancel link.
- The link will appear under the list of applicants on the Task Creator view.
- The link will read, "Cancel this opportunity"
- when the creator clicks on this link, a message will appear that reads, "Are you sure you want to cancel this opportunity? If you cancel this opportunity, you and your participants will not receive any credit for work."  There will be a Cancel and Confirm pushbutton.  Cancel will take the user back to the previous page and not cancel. Confirm will cancel the opportunity.  Mock: https://projects.invisionapp.com/d/main#/console/12657410/269951242/preview

**To reopen a canceled opportunity:**
- The task creator can click on the canceled opportunity on their profile listing which will take them to opportunity where the pill will read Canceled.
- The progress bar will be grayed out
- The message under the progress bar will read, "Canceled on mm/dd/yyyy"
- applicants will stay as applicants in a canceled job
- assigned participants will stay as assigned participants in a canceled job
- Task completed participants will stay as task completed in a canceled job if marked as completed
- on the task creator page, the assigned participants, task completed, and applicants will display however, can't be modified.
- The Reopen link will appear where the Edit would be on an open job.  Reopen will open the job in edit mode and once Submit for Review is selected, the approval process will be initiated again.

Prototype: 
https://projects.invisionapp.com/d/main#/console/12657410/269951242/preview

Desktop- https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
Mobile- https://projects.invisionapp.com/d/main#/projects/prototypes/12656859

Screen Shot: 
![1430](https://user-images.githubusercontent.com/18709918/33968466-100d4d18-e036-11e7-96e0-b383b20a6a10.png)

Original Issue: 
As an opportunity creator, I need a way to close out an opportunity without assigning it to someone so that I have the option to not choose anyone at all and still close out my opportunity posting.
- This applies to part-time and full-time opportunities: 
- Temporarily want to archive an opportunity so that they can stop showing it to users and turn off notifications
- Is this locking or disabling an opportunity 
- Get aligned on first iteration of this feature

We could change opportunity state “archived” to “canceled”  --
never assigned & closed
No one was ever picked
No one ever signed up
Started but not finished

Needs definition

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
3-6-18 LHammond in test

**Comment by kbwagner** [comment]
3/6/18: Katrina updated AC as follows: Removed "-When cancel is selected, the task creator will go to their profile page where they can view the opportunity status list.  The status will now be "Canceled"" as it contradicted the previous bullet.
