### ISSUE TITLE
CSV report of open opps data

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1431]
As a program administrator, I need GSA-specific Dashboard view so I can easily view GSA-specific data only for report purposes. 
- I should be able to see an admin tasks page for my agency #1225
- I should be able to see all of the users from my agency #1224
- I would like to see overview metrics for participation from my agency #1256  (#1227 for making the page with basic stats we have now)
- I want to be able to see all participants in my agency #1228 

As a program administrator, I need to know how many applicants applied, even if they were not accepted (with the ability to export all applicant/opportunity actions). Right now the opportunity signups calculate only those that are actively listed on an opportunity- when a non-selectee is removed from a task, they are no longer considered an “opportunity signup” but we still need to count them as an applicant for report purposes. 

As a program administrator, I need all data fields under interactions and opportunities to have a filter for service/staff office, region, and location (either virtual or location specific - don’t need all various locations listed) so I can easily report out on where all opportunities and applicants are from. #1272 for Region & Service/Staff Office -- do we need a report based on location?

As a program administrator, I need an average calculated of part-time opportunity length for report purposes. 

This story is to create a .csv download with this data

We need to follow up with @rogeruiz to see how much of this we have, and then we need to add some acceptance criteria

**Comment by mtorres253** [comment]
Per @LisaLNelson we should generalize this for every agency rather than for GSA. I will write the acceptance criteria to describe the changes needed.

**Comment by mtorres253** [comment]
@rogeruiz According to this story, you were going to check into whether we already have this data. Can you let us know what you found out? Just add a note to this story.

**Comment by kbwagner** [comment]
3/29/18 - no longer doing GSA specific dashboard
