### ISSUE TITLE
Disabling user doesn't have the correct icon

### ISSUE THREAD

**Issue by rogeruiz** [openopps/openopps-platform#1434]
_This came up while working on #1399 / #1433_.

When disabling a user, the functionality works but the visual UI layer is missing a disabled icon.

The enabled icon and the loading icon are both there, but the disabled user is missing an icon in the square button.

<img width="417" alt="screen shot 2016-08-10 at 11 56 03 am" src="https://cloud.githubusercontent.com/assets/706004/17560818/74157802-5ef1-11e6-9108-e514a8e8dc8b.png">

**Comment by kbwagner** [comment]
Icon no longer exists.
