### ISSUE TITLE
Ombudsperson OpenOpps Link shows "Internal Error" message.

### ISSUE THREAD

**Issue by ShellSV** [openopps/openopps-platform#1435]
Link doesn't work and shows "internal server error" message:  https://openopps.digitalgov.gov/tasks/www.usda.gov/ombudsperson.  This hyperlink originates from https://openopps.digitalgov.gov/tasks/537 and shown as "www.usda.gov/ombudsperson".

**Comment by rogeruiz** [comment]
Thanks @ShellSV. This is an issue with the way the link was generated using markdown. I edited the opportunity and updated the syntax. Below is a `git diff` of the line changes highlighting the difference between what was in the opportunity and what I edited it to.

```diff
- [www.usda.gov/ombudsperson](www.usda.gov/ombudsperson)
+ [http://www.usda.gov/ombudsperson](http://www.usda.gov/ombudsperson)
```

You can preview markdown syntax you write when editing or creating an opportunity. When dealing with links or images, it's important to ensure that the protocol is in the URL.
