### ISSUE TITLE
Popovers don't close on back/forward

### ISSUE THREAD

**Issue by jmcarp** [openopps/openopps-platform#1444]
Steps:
- Hover over a user's name, triggering a popover
- Navigate back/forward using a keyboard shortcut
- Notice that the popover is still there

Also, user images don't seem to load.

![sacwicdb3d](https://cloud.githubusercontent.com/assets/1633460/18040329/96311300-6d7a-11e6-8a02-91a6a844d964.gif)

**Comment by kbwagner** [comment]
3/29/18 - no longer use popovers so non issue.
