### ISSUE TITLE
Unable to make a comment on an opportunity

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1445]
To duplicate
1. login as michael.torres@gsa.gov, Dolphin2!
2. Go to https://openopps.digitalgov.gov/tasks/542
3. Try to add a comment

Expected behavior: The comment is accepted

Actual behavior: Nothing happens

See attached screenshot - I appear to be getting a 400 error - bad request. id: missing?

![screen shot 2016-08-30 at 10 27 54 am](https://cloud.githubusercontent.com/assets/100149/18099697/983189c8-6e9c-11e6-89db-e9a72aefe457.png)

Related to #1236?

**Comment by adborden** [comment]
I just ran into this, the 400 response includes:
```
{"message":":id required."}
```

**Comment by brodydittemore** [comment]
Merging with #1505
