### ISSUE TITLE
Part-time opportunity - someone has applied - notification to creator

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1453]
When someone applies to a part time opportunity, this notification gets sent to the creator. "Part time" is a Agency-only (GSA-only for now) task that is not a full-time detail. This is a system notification for Agency-restricted opportunities. We want to do this in a way that can scale for other agencies.

This story contemplates creating custom notifications for Agency-restricted opportunities. And creating one for Agency-restricted opportunities that are not full-time details. Right now full-time details are hard-coded to be a GSA only opportunity type this needs to be generalized as well

Suggested implementation
- `api/notifications/task.create.draft/template.html` _default notification_
- `api/notifications/<AGENCY_ABBREVIATION/task.create.draft/template.html` _custom to an agency if it exists_

``` yaml

Part-Time Opportunity - Someone has just applied
Dear:

You have a new applicant for your opportunity. Their profile can be viewed here <insert link to profile>.

All applicants have self-certified that they meet eligibility requirements.  

Please follow the steps below:
Review all candidates and select your top pick(s).  If needed, reach out to those candidates to discuss the opportunity and ask any questions you may have about their profile or statement of interest. Once you are ready to make your selection, we encourage you to contact the selected applicant's supervisor to confirm that he/she is on board with the employee's participation.
Contact the selected candidate and discuss next steps for beginning the opportunity. You must also assign the opportunity in the system by doing the following:
Click to Edit your opportunity
Remove the non-selected participants from the opportunity under the “Participants” section
Change the opportunity state to “Assigned.”  This will send notifications to the candidates.

If you have any questions, feel free to reach out to us at gsarotationprogram@gsa.gov.

Thank you,
<signature>

```

**Comment by rogeruiz** [comment]
The PR #1467 is the start for this feature. The Notification behavior still needs to use this new directory and fallback if an agency directory does not exist.

**Comment by mtorres253** [comment]
Congratulations @dsiddy on winning this micro-purchase auction!

To get started, please create a pull request referencing this issue. Then enter the URL to your pull request on the auction page (in 18F's Micro-purchase platform) and click "start work".
