### ISSUE TITLE
Production Certificate Chain is Broken -- Certificate Error

### ISSUE THREAD

**Issue by msgn2007** [openopps/openopps-platform#1455]
> `(net::ERR_CERT_AUTHORITY_INVALID).`

I am receiving the above error on Google Chrome and cannot access site on IE 11.

**Comment by msgn2007** [comment]
here is the screen shot.
![image](https://cloud.githubusercontent.com/assets/21953167/18205423/df357b7c-70ef-11e6-881e-ce3bcbe6227c.png)

**Comment by rogeruiz** [comment]
Thanks for providing the screenshot @msgn2007! We will take a look at the certificate error to verify what the issue is there. Thanks again.

**Comment by lawrencek76** [comment]
If you are still seeing this issue please reopen this issue.
