### ISSUE TITLE
Agency table and list view

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1458]
To deal with various performance and scalability issues, we want to refactor the app so that we can more easily associate opportunities with agencies. 

The first step of this refactor is to create an agency table, populate with canonical data from data.gov, and show the list of agencies to a super-admin via the UI
- [x] **Create agency table**
- Name of agency
- ID of agency 
- Contact email 
- [x] **Seed agency table**
- Use data.gov as authoritative source of agency info OR this? https://github.com/usagov/Federal-Agency-Directory-API-Documentation
- Agency tags all have an id associated with them. The id is stored in a lookup table for users so let's use the value of this ID for the agency ID
## Feature:

Super admin user sees a list of agencies
## Context:
- Given I am an authenticated super-admin user (Lisa)
- [ ] **Scenario: Super admin navigates to "Agencies" list page"**
- When I go to [URL]
- Then I see a page titled "Agencies"
- And I should see all agencies in the Agency table listed
- And for each Agency I should see the Agency name, and contact email address
- And I should see a Button on the UI labeled "Update Agency Data"
- [ ] **Scenario: Super admin sees a tab labeled "Agencies" on superadmin homepage**
- When I go to the admin home page
- Then I should see a tab on the left labeled "Agencies"
- And clicking on that tab should take me to the "Agencies" page (see above)
- [ ] **Scenario: Superadmin user updates agency data by clicking on "Update Agency Data" button**
- And I am on the "Agencies" page
- When I click on the "Update Agency Data" button
- Then the agency data should be updated with data from data.gov
- And new agencies should be added
- And updates to existing agencies should be made
- And I should see a success message "All agencies have been updated"

**Comment by mtorres253** [comment]
@EricSchles Is this in progress?

**Comment by rogeruiz** [comment]
This was mentioned in #1459. The first steps of this comment are done. The dashboard view is not.
