### ISSUE TITLE
Refactoring app to use agencies in agency table instead of tags

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1459]
- [ ] Refactor the way that opportunities are created so they use this new agency data
- [ ] Check to see that old opportunities have the old data which is OK for now (not canonical data but still OK)
- [ ] Replacing what we’re doing now with a standard look up to get all opportunities associated with an agency.

**Comment by EricSchles** [comment]
Hey!

Sorry about the delay on this - all that's remaining is writing the tests.  All the functionality is there.  Currently in: https://github.com/openopps/openopps-agency

**Comment by rogeruiz** [comment]
We have the secondary application ready for more refactoring. We were only able to complete the second point in the opening comment for this issue.
