### ISSUE TITLE
As an admin I need to be able to download a complete CSV file from the users page.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1460]
When I download a CSV file from the Open Opportunities users page the excel spread sheet comes up blank. No info on it at all.  I tried it twice.

In addition, I tried to email Roger a copy of the spreadsheets and when I tried to attach it would not let me do it. Here is the messageI received.

![screen shot 2016-09-19 at 11 32 18 am](https://cloud.githubusercontent.com/assets/9039852/18638089/cdc9b888-7e5c-11e6-9990-4d5e20731fb6.png)

**Comment by rogeruiz** [comment]
Verified working in the latest release. :tada:
