### ISSUE TITLE
Update or remove outdated dependencies

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1461]
Per @NoahKunin we won't get ATO approval unless we take care of these outdated dependencies. So, let's discuss and come up with a POA

https://www.versioneye.com/user/projects/57297a80a0ca35004baf7d09?utm_medium=email&utm_source=project_notifications

**Comment by mtorres253** [comment]
We are going to create a doc in the repo that is linked from the README so that we explain why we can't update any of these dependencies, and we will update the rest. The dependencies will likely need to be refactored in the future.

**Comment by rogeruiz** [comment]
This was included in the latest release. We can close this. Read the :eyes: `DEPENDENCIES.md` found at the root of the repository.
