### ISSUE TITLE
Admin Dashboard: I want to be able to see an accurate number of tasks completed this year on the dashboard.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1462]
The dashboard page shows 307 tasks completed in FY16.  I am not sure where that number comes from but it is incorrect. The admin panel shows 76 tasks completed this year.

![screen shot 2016-09-21 at 9 23 52 am](https://cloud.githubusercontent.com/assets/9039852/18712604/40f7b568-7fdd-11e6-95f5-8423431ec475.png)

**Comment by LisaLNelson** [comment]
This is part of 1486

**Comment by LisaLNelson** [comment]
closing 1486 instead

**Comment by kbwagner** [comment]
3/29/18 - in the new design this has been removed.  Possibly close after release 2.

**Comment by Piglady64** [comment]
We have other tickets to update the dashboards. Closing this ticket
