### ISSUE TITLE
As a participant, I want to be able to update my profile in IE.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1479]
I was contacted by a user (Teri Easley) today who was trying to update their profile in IE and it wouldn't save.  I asked her to try Chrome and she was able to do it.

Yesterday I got an email from Kelvin Johnson that he could not update his profile. Below is the exchange we had on the issue.

![screen shot 2016-10-05 at 2 29 30 pm](https://cloud.githubusercontent.com/assets/9039852/19126305/59ab947c-8b08-11e6-8cd3-ce3a2c3f01b7.png)

**Comment by LisaLNelson** [comment]
I think this has been fixed.  @Brody can you try to see if this is replicable?

**Comment by kbwagner** [comment]
@LisaLNelson - this appears to be resolved. I tested in IE and it works for me.  Looks like this just recently was approved so want to make sure you didn't get another complaint.  If not, ok to close?

**Comment by LisaLNelson** [comment]
This is good.
