### ISSUE TITLE
As a task creator I need to be able to add people onto tasks.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1487]
Task creators need to be able to add people onto opportunities.  As an admin I am able to do that but task creators don't seem to be able to although thay were able to at one time.
![screen shot 2016-10-12 at 5 12 20 pm](https://cloud.githubusercontent.com/assets/9039852/19327869/204164b8-909f-11e6-8197-89dba0ad9748.png)

**Comment by mtorres253** [comment]
Can't duplicate

**Comment by kbwagner** [comment]
Closing.  This won't be necessary as long as we have the admin ability to add.  Ticket 1878
