### ISSUE TITLE
Consistent error messaging for 404 and other error pages.  

### ISSUE THREAD

**Issue by polastre** [openopps/openopps-platform#149]
Apply the Open Opportunities design system pages for 404 and other error pages.  
Design System Link: 

For project or opportunity ids that don't exist anymore, eg `/projects/foobarbaz`, we should show a 404 error page rather than a blank project/opportunity form (which will confuse users).

**Comment by afturner** [comment]
I'll work on this.

**Comment by Piglady64** [comment]
We want to show our own 404 page when a page doesn't exist. Consistent with USAJOBS.

**Comment by kbwagner** [comment]
1/8/20 - This has been completed
