### ISSUE TITLE
As a task creator I want to see my badges on the platform.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1492]
When Kelley Randazzo added her first task she was sent an email that she received her first badge but the badge did not appear on her profile.
![screen shot 2016-10-20 at 10 12 11 am](https://cloud.githubusercontent.com/assets/9039852/19563378/b40c6148-96ad-11e6-9aa1-f28d836e338d.png)

**Comment by bmcorum** [comment]
Lastest code from DEV branch displays the user's badges on his or her profile page.
@LisaLNelson can this be closed?

![screen shot 2017-09-12 at 7 33 34 am](https://user-images.githubusercontent.com/1165615/30323905-02ee946c-978d-11e7-92ec-443868df93dd.png)
