### ISSUE TITLE
As a potential user I would like to see a list of agencies who are using the platform.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1493]
Many people thinking about participating in the program for the first time would like to look and see if others in their agency have participated in the program. I suggest adding a drop down menu some where on the platform that lets you know the agencies who have participated.  

An example of this is the Virtual Student Foreign Service program.http://www.state.gov/vsfs/

**Comment by kbwagner** [comment]
Closing - can be added to landing page down the road if necessary.
