### ISSUE TITLE
As a task creator I want to be able to copy an already existing opportunity.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1500]
I tried to copy an `existing Open Opportunity (https://openopps.digitalgov.gov/tasks/25)` today and was not able to save it.  The "save as draft" button throws an error.

[Screenshot of console error when clicking "Save as Draft"](https://user-images.githubusercontent.com/4691642/29894950-4492a97c-8da5-11e7-8ee6-ec9a840b2215.png)

## Acceptance Criteria 
Users can save opportunities that have been copied from an existing Open Opportunity (their own, or if an Admin, another users opp):
- [ ] The "Save as Draft" button functions

**Comment by bmcorum** [comment]
@brodydittemore this appears to be a duplicate of #1529 and this issues has been corrected in staging. I would recommend maybe having someone review this in staging to verify it is still an issue.

**Comment by kbwagner** [comment]
@LisaLNelson @bmcorum I believe we can close this one?

**Comment by LisaLNelson** [comment]
Sprint 1.4
