### ISSUE TITLE
As an admin I would like to see the grammar Corrected on the dashboard page.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1501]
When someone completes an opportunity their name and info appears on the dashboard page.  The line that appears reads:
John Elliott earned the newcomer badge. have completed your first task. (See image)

It should read: John Elliott earned the newcomer badge! You have completed your first task.

![screen shot 2017-03-30 at 2 41 13 pm](https://cloud.githubusercontent.com/assets/9039852/24520603/05a3d81a-1557-11e7-96cd-5d518378ce23.png)

This same error appears when someone has completed multiple tasks. (See image)

![screen shot 2017-03-30 at 2 49 08 pm](https://cloud.githubusercontent.com/assets/9039852/24520896/14cbc914-1558-11e7-8283-5760f46a32e5.png)

## Acceptance Criteria 
- [x] The notification for when a user completes one or more opportunities should read: "[USERNAME] earned the newcomer badge! You ..."

**Comment by kbwagner** [comment]
Issue is resolved.
