### ISSUE TITLE
Drop heroku-buildpack-multi which is deprecated

### ISSUE THREAD

**Issue by adborden** [openopps/openopps-platform#1502]
The [upstream buildpack](https://github.com/ddollar/heroku-buildpack-multi) is deprecated, so unless we're maintaining our own, we should look at using the standard nodejs-buildpack.

Looks like the multi-buildpack exists to support [graphicsmagick](https://github.com/openopps/openopps-platform/blob/master/Aptfile), so we'll have to resolve that first.

**Comment by lawrencek76** [comment]
Resolved with #1537
