### ISSUE TITLE
As a participant I would like to see fewer entries per page when I use the People tab.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1503]
When searching on the people tab the loading time is very long because it is not paginated.  Suggest paginating with a maximum of 10-12 per page (desktop and mobile)

## Acceptance Criteria 
- [ ] The People Tab is paginated for a maximum of 25 results per page.

**Comment by Piglady64** [comment]
Will get this when we revisit new design for people search - closing
