### ISSUE TITLE
Ask a task taker I want to see my accomplishment on the on the dashboard when I have successfully completed a task.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1506]
Right now when a task is completed it does not appear on the dashboard. For example, Scott Nielsen just completed the opportunity [Conduct monthly interviews and draft lead-in for Open Opportunities newsletters](https://openopps.digitalgov.gov/tasks/498) and it does not appear on the [dashboard](https://openopps.digitalgov.gov/dashboard).

![screen shot 2017-08-30 at 12 12 57 pm](https://user-images.githubusercontent.com/9039852/29882957-a46aced4-8d7c-11e7-9fbe-fdd818a2a97a.png)

Another example of this is Joi Colman who just completed the task [Seeking WordPress Designers for Federal CIO Council Website](https://openopps.digitalgov.gov/tasks/529). Her accomplishment does not appear on the [dashboard](https://openopps.digitalgov.gov/dashboard).

**Comment by kbwagner** [comment]
@LisaLNelson - I believe this is fixed.  Ok to close? Screen shot of my completed task displaying in profile attached.
![image](https://user-images.githubusercontent.com/18709918/37615744-60a640ba-2b84-11e8-9f07-234b7907d3ab.png)
