### ISSUE TITLE
As an admin, I would like the dashboard page to accurately reflect the number of opportunities so far this year.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1507]
On the right side of the dashboard page there is a box that highlights the number of opportunities created so far this year.  That number is incorrect. The number should reflect the correct number of opportunities which as of today is 44 for this year. The number should also grow with each new task published.

![screen shot 2017-05-16 at 10 55 09 am](https://cloud.githubusercontent.com/assets/9039852/26114894/82457bfe-3a2c-11e7-837c-15794e6b5279.png)

**Comment by kbwagner** [comment]
closing - this number will be removed with the redesign of the landing page.
