### ISSUE TITLE
As a Security Engineer I want all elements of the infrastructure to be included in the SSP

### ISSUE THREAD

**Issue by thecapacity** [openopps/openopps-platform#1509]
Currently [the SSP](https://github.com/openopps/openopps-platform/blob/dev/system-security-plan.yml) mentions the tool leverages;

```
leveraged-authorizations:
- https://www.fedramp.gov/marketplace/compliant-systems/amazon-web-services-aws-eastwest-us-public-cloud/
```

However, since it's also built on cloud.gov it should also reference that platform's leverage as well.

**Comment by kbwagner** [comment]
3/29/18 - closing, this is outside of the application.  this would be worked outside of Github
