### ISSUE TITLE
As a task taker I would like to know what I am going to get out of an opportunity I am interested in.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1510]
Open Opportunities are developmental assignments and as such should let participants know in the task description what they will learn from participating.  To do that a section should be created in the task template (https://openopps.digitalgov.gov/tasks/new) where the task creator can add that information. 

The **_What you will learn_** box can be added as a new section under the Description box.

**Comment by kbwagner** [comment]
3/29/18 - This may be done with the FAI implementation after Release 2.

**Comment by kbwagner** [comment]
@LisaLNelson - we have a what you will learn box now.  Can this be closed?

**Comment by LisaLNelson** [comment]
Completed and approved.
