### ISSUE TITLE
As an open source participant I need to be able to find the code of conduct.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1515]
On the CONTRIBUTING.md the first paragraph refers to the 18F code of conduct.  The link is dead and should be removed with language added that indicates we are working to define a code of conduct.

**Comment by bmcorum** [comment]
@LisaLNelson the link on the first paragraph looks like it was updated to point at Code For America. Can this issue be closed?

**Comment by kbwagner** [comment]
3/29/18 - this is done.  Closing
