### ISSUE TITLE
Link to db-migrate scripts goes to a message 'sorry this page does not exist'

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1519]
On the CONTRIBUTING.md page under Creating New Migrations the link shows the following error.
![screen shot 2017-08-05 at 11 59 02 am](https://user-images.githubusercontent.com/9039852/28996847-81bc1e7a-79d5-11e7-8b28-b1820a090061.png)

**Comment by Piglady64** [comment]
Noted - Closing
