### ISSUE TITLE
Link to the Contribution Guide in GOVERNANCE.md goes to 404 message.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1521]
On the GOVERNANCE.md page under Contribution Process section the link to the Contribution Guide links to a 404 message.

**Comment by rogeruiz** [comment]
The reason for this is that the CoC is still under review and is part of a private repo at the moment. Would you like to have us link to a new CoC that we draft ourselves? GitHub offers a template we can start off as a draft.

**Comment by LisaLNelson** [comment]
That makes sense.  We will hold for that.

**Comment by ultrasaurus** [comment]
It's unfortunate that 18F decided to make the whole repo private with the consequence that there is effectively no code of conduct while it is undergoing revisions.  To address this, I'm going to switch to CfA code-of-conduct to govern participation in the interim,

@rogeruiz feel free to switch later if it is important for the gov work!

**Comment by bmcorum** [comment]
@LisaLNelson, @rogeruiz or @ultrasaurus can this issue be closed since there appears to be a code merge that was completed?

**Comment by Piglady64** [comment]
Noted Closing
