### ISSUE TITLE
As a task creator I want to be able to copy an already existing opportunity and not see the original creator's popover

### ISSUE THREAD

**Issue by brodydittemore** [openopps/openopps-platform#1530]
I tried to copy an `existing Open Opportunity (https://openopps.digitalgov.gov/tasks/25)` today and in the resulting edit page, the original task creators' popover (profile name and image) appears as and will not go away.

![screen shot 2017-03-22 at 3 43 39 pm](https://cloud.githubusercontent.com/assets/9039852/24217518/7d3447a8-0f16-11e7-967e-09ae89dc21cf.png)

## Acceptance Criteria 
- [ ] The original task creators' popover does not display on the edit page

**Comment by brodydittemore** [comment]
Split from #1500

**Comment by kbwagner** [comment]
@LisaLNelson - tested this today.  Copied Larry's opportunity, submitted, and my name displays.  Close?
