### ISSUE TITLE
Use cloud.gov recommended buildpack/deploy for the application

### ISSUE THREAD

**Issue by brodydittemore** [openopps/openopps-platform#1531]
_this ticket will be updated with more info_ 

Custom buildpack is being used. Contains obsolete dependencies and prevents cloud.gov updates from being applied to the application.

**Comment by lawrencek76** [comment]
Looks like part of the custom build pack is using graphicsmagick.  That is not included in the standard [cflinuxfs2](https://github.com/cloudfoundry/cflinuxfs2/blob/master/cflinuxfs2/cflinuxfs2_receipt) but imagemagick is.  We will need to verify that uploading a profile image still works after this change.  We are using an npm module gm that wraps graphicsmagick but it has support for [imagemagick](http://aheckmann.github.io/gm/docs.html#imagemagick)
