### ISSUE TITLE
Correct csrf server errors being thrown in app

### ISSUE THREAD

**Issue by brodydittemore** [openopps/openopps-platform#1532]
We can use the logs.fr.cloud.gov to find the more frequent errors. 

error id as an example  "_id": "AV5c3tERcqYYWKwNj5Lg",
@message": " ReferenceError: /home/vcap/app/views/main-layout.ejs:17",
next error in log at the same instant is _csrf is not defined

[For more logs at the same instant use this link](https://logs.fr.cloud.gov/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T00:00:00.000Z',mode:absolute,to:'2017-09-07T23:59:59.999Z'))&_a=(columns:!('@message'),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-app-*',key:'@timestamp',negate:!f,type:phrase,value:'September%207th%202017,%2015:04:19.309'),query:(match:('@timestamp':(query:1504796659309,type:phrase))))),index:'logs-app-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc)))

**Comment by lawrencek76** [comment]
Looks like we need to simply check for null in the main_layout.ejs template.  Also a little wider time span in [kibana](https://logs.fr.cloud.gov/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-07T15:04:10.000Z',mode:absolute,to:'2017-09-07T15:04:20.000Z'))&_a=(columns:!('@message'),filters:!(),index:'logs-app-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc),uiState:(spy:(mode:(fill:!f,name:!n))))) looks like the request was for HEAD /tasks/604 not certain but plausible that was the request with the error.

Can anyone get a repro locally on this one?

**Comment by bmcorum** [comment]
We also have some client javascript error handling expecting a JSON object with a message which fails on "CSRF Mismatch" errors.

- [ ] Add client error handling for "CSRF Mismatch"

**Comment by bmcorum** [comment]
@ultrasaurus, @rogeruiz, @lawrencek76, @Marchalk, @quadrinaquinn 

One issue that might be causing this issues are that we are trying to utilize both bootstrapping via the main view using locals and then trying to use a web socket via AJAX request from backbone. According to the [SailsJS CSRF documentation](http://sailsjs.com/documentation/concepts/security/csrf) we should you one or the other not both. So was there a particular reason why we are using both or was this just a simple oversight, in which case we need to pick which method to use.
