### ISSUE TITLE
Stress testing and profiling

### ISSUE THREAD

**Issue by brodydittemore** [openopps/openopps-platform#1533]
_This issue will be improved with more info_ 

Run load tests to find any potential bottlenecks that would affect performance.

**Comment by bmcorum** [comment]
[loadtest](https://www.npmjs.com/package/loadtest) might be a possible solution.

**Comment by kbwagner** [comment]
Closing.  Will enter a new technical enhancement/spike for researching what it will take to set up load testing for open opps.
