### ISSUE TITLE
As member, I would like to see where everyone is on a map. 

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1546]
There was a map on the profile page that showed on a map where everyone who has completed an Open Opportunities map is located. It was great for showing the breadth of the program.  That map no longer exists and  I would like to bring it back.  Here is a link to the Github task it cam from https://github.com/openopps/openopps-platform/issues/672.

Here is an old image of the map:
![screen shot 2017-09-12 at 3 54 14 pm](https://user-images.githubusercontent.com/9039852/30345323-ae57d594-97d2-11e7-9bb3-e56d0a8c5532.png)

**Comment by ultrasaurus** [comment]
FYI: in 2016 when I upgrade Node and SailsJS, I turned off the map so that I could reduce the scope of the upgrade.  So someone needs to go through and update the code in a few places to get it to work again.

**Comment by LisaLNelson** [comment]
See issue #1101

**Comment by Piglady64** [comment]
See #798

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41528&_a=edit
