### ISSUE TITLE
Mandrill Replacement Options

### ISSUE THREAD

**Issue by brodydittemore** [openopps/openopps-platform#1548]
GSA is mandating that systems replace Mandrill with an alternative notification system. 

Replacement options need the following functionality:
- OPM will own, lease, develop, etc. (not GSA)
- Able to send a minimum of 20 messages sent per day
  - This is expected to grow
- Able to pass any necessary OPM approvals
- Do this 
- Do that 

#1542 will capture the feature replacement work.

**Comment by brodydittemore** [comment]
We could, but there are a number of known issues with the USAJOBS notification system. Improving it is on our roadmap. It might be ideal to wait until we put a true CMS in place - but we may need a temporary solution in place fore this.

**Comment by quadrinaquinn** [comment]
@brodydittemore are you referring to bugs or future "refactor" work for CMS?

**Comment by brodydittemore** [comment]
@quadrinaquinn I'm referring back to issues that ATP experienced pre-12/2016 and which I understood as also effecting Core. I don't think I am in a place to call these bugs since the AC pre-dates me. Some of the issues/enhancements/maybe bugs that were discussed in 2016 were around reliability/spam, non-responsiveness, etc --> the reasons we've not integrated messaging back into ATP but are holding off until all of messaging can be refactored or a new CMS solution.

Of course, these may be issues that ATP was more limited by. I definitely defer to the you and the rest of the technical team here.

**Comment by quadrinaquinn** [comment]
We do have some technical tickets to refactor and modernize the process. I think we just need to be on the same page on the future of notifications in general :)

**Comment by LisaLNelson** [comment]
Yesterday I was notified that GSA will not discontinue Mandrill until the end of December. Cloud.gov will have another solution available by then.  There were so many parts of the organization that are using Mandrill and everyone was scrambling to find an alternative so they are giving everyone a few months to figure it out.

**Comment by brodydittemore** [comment]
@quadrinaquinn Agreed! I think a lot of different needs can be grouped into "notifications" - some might confuse the primary issue and direction forward. I don't want to imply that our current messaging feature can't do it (although @lawrencek76 may have hit that one for us!).

@LisaLNelson Great! +1 for more time on this issue!

**Comment by kbwagner** [comment]
Closing - merging with 1542
