### ISSUE TITLE
As an admin I need to be able to download a list of all users as a file ready import into excel.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1550]
This was something I was able to do until recently. I tried to download a CSV file tonight and the message I received is below.  I was also able to replicate receiving the same message.
![screen shot 2017-09-15 at 9 34 20 pm](https://user-images.githubusercontent.com/9039852/30508164-49bf6cc6-9a5e-11e7-99fe-9517b44013d8.png)

**Acceptance Criteria**

- [ ] When clicking on the download button I am able to download the CSV file into an excel spreadsheet.

**Comment by jhanson12** [comment]
@LisaLNelson @bmcorum could we close this ticket?  I believe we have this working now with the last release.

**Comment by kbwagner** [comment]
@LisaLNelson @bmcorum - I tested this and it's working correctly.  Ok to close?
