### ISSUE TITLE
As an admin I need a way to ensure that task creators remember to close out their open opportunities when completed.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1551]
Task creators frequently fail to update the platform when their task is completed. The tasks then inaccurately appear as open and participants don’t receive credit on their profile and get frustrated. We the designers to develop a process that ensures task creators close their tasks as soon as they are successfully completed. 

There are different ways this can happen:
Have the task creators dashboard show opened tasks or
Have them receive an email each week for each assigned task 

**Acceptance Criteria**
Not developed yet

**Comment by kbwagner** [comment]
Closing - replaced by tickdets 1689, 1690, and 1691
