### ISSUE TITLE
As a product owner or developer I want to know what percentage of the code is covered by automated tests.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1558]
My assumption is that there is little automated testing on the platform. It will be more efficient if we can run automated testing so results are checked automatically. Let's get a check on how much there is and where we want to go with it.

Ideas for tests:
1. Core functionality tests to alert us when the site has problems. Do automated regression tests to run on every code change makes sense?
2. The basics (smoke tests) to ensure manual testers aren't having their time wasted with obviously broken builds.
3. Anything fragile which is likely to break. This is hard to define for new code, but if you're working on some legacy code which you know to be bug prone then building tests around any changes you make is a good way to build towards being able to refactor more safely.
4. Things you the developers want to automate because it was easy to do. Sometimes it makes sense to add tests while you're building something.

**Comment by lawrencek76** [comment]
FYI Current Coverage

File                                                         |  % Stmts | % Branch |  % Funcs |  % Lines |
-------------------------------------------------------------|----------|----------|----------|----------|
All files                                                    |     39.4 |    24.12 |    38.08 |    42.51 |

**Comment by humancompanion** [comment]
@bmcorum - The current coverage looks a little underwhelming. Agree? What's your goal for coverage before you start swapping out SailsJS for Koa?

We should probably redefine the scope of this issue to be a repeatable code coverage test that can be run regularly and/or a definition of our "low bar". 

FWIW, the USWDS uses Istanbul for code coverage: https://www.npmjs.com/package/istanbul They also seem to keep it out of their test cycle/commands.

**Comment by kbwagner** [comment]
3/29/18- this is done now.  Can be reported on at anytime upon request.
