### ISSUE TITLE
update docker image on dockerhub with automated build

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1559]
The image on dockerhub was about a year old.  

I deleted the old one, and made a new one here: https://hub.docker.com/r/openopps/openopps-platform/

I set it up to build automatically but there's a build errr:

`Build failed: The command '/bin/sh -c apt-get update && apt-get install -y postgresql-client graphicsmagick' returned a non-zero code: 100`

**Comment by jhanson12** [comment]
Working with latest OPM baseline code.
