### ISSUE TITLE
Designing a template for the Open Opps newsletter.

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1562]
The Open Opps newsletter would benefit from a brand-reinforcing template.

**Comment by KatMullens-work** [comment]
content should mirror most of what we have today and include the same sections. We can send the assignee a copy of the current iteration.

**Comment by KatMullens-work** [comment]
Due date no later than when Lisa starts at OPM as we will lose access to the current tool at that time.

**Comment by kbwagner** [comment]
From 12/4/17 Branding Meeting Notes: 
- Assumption: New Emma email tool is ready by January branding release
- Update Emma newsletter tool with new Open Opps branding
- Update Emma newsletter tool with new Open Opps footer to include updated email, OPM address
- Create a simplified footer of "The Fine Print" – remove digital.gov social media links
- Newsletters should be sent from "OpenOpps@USAJOBS.gov

**Comment by kbwagner** [comment]
Kat completed email template in MyEmma and sent out first version 2/7/18
