### ISSUE TITLE
As an Open Opportunities user, I want to see a consistent color palette applied to the system. (Design System)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1563]
Acceptance Criteria:

Apply design system and CSS changes for Colors to all pages of Open Opportunities.  

Design System Link: http://usajobs.github.io/design-system/getting-started/
InVision Prototype Desktop: https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
InVision Prototype Mobile: https://projects.invisionapp.com/d/main#/projects/prototypes/12656859
List of Open Opps Pages: https://airtable.com/tblC0ddHd2X29xoa8

Related Tickets: 
•	1565 – Footer
•	1563 - Colors
•	1665 - Typography
•	1666 - Spacing
•	1667 - Shell of the page (breakpoints)
•	1668 - Buttons 
•	1669 - Form Elements
•	1670 - Logo – Powered by USAJOBS logo
•	1672 - Top Navigation
•	1660 – Autocomplete (later release)
•	1661 – Pagination (later release)

**Comment by kbwagner** [comment]
1/24/18 - KWagner - Moved autocomplete and pagination out of this ticket and into their own tickets as this involves new functionality.

**Comment by Kibrahacha67** [comment]
In Testing - 2-27-18 LHammond
