### ISSUE TITLE
As an unauthenticated user, I should be limited in what I can see.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1564]
Users that are not logged to the Open Opportunities platform should not be able to access the profiles of the task creator or the people who have signed up for the task.

**Comment by margaretdumas** [comment]
Tested by:  Margaret Dumas on 1/5/2018

**Comment by kbwagner** [comment]
Tested by Katrina Wagner in UAT 1/23/18

**Comment by LisaLNelson** [comment]
Tested by Lisa 1/24/2018.  My question is what are the limits?  If it is just signing up for an opportunity then yes.  In safari I could see opportunities, open an opportunity but when I clicked on I'm interested I got a log in screen.
