### ISSUE TITLE
As an Open Opportunities user, I want the site footer to be updated to reflect new OPM branding.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1565]
Acceptance Criteria:
The updated site footer should include:
- Change Contact Email: OpenOpps@USAJOBS.gov
- Terms and Conditions – should open in new window, will need to redirect to a Github repository (Matt to provide link)
- GeoNames –  Keep in footer
- Powered by Open Source

Note:
- There will be no social media icons in the footer for now.
- Release notes will no longer be in the footer.  They will be linked to elsewhere on the site and be housed in the Github repository.

Design System Link: http://usajobs.github.io/design-system/getting-started/
Footer Mock Up Link Desktop: https://projects.invisionapp.com/d/main#/console/12657410/268909834/preview
Footer Mock up link mobile: https://projects.invisionapp.com/d/main#/projects/prototypes/12656859

Related Tickets: 
•	1565 – Footer
•	1563 - Colors
•	1665 - Typography
•	1666 - Spacing
•	1667 - Shell of the page (breakpoints)
•	1668 - Buttons 
•	1669 - Form Elements
•	1670 - Logo – Powered by USAJOBS logo
•	1672 - Top Navigation
•	1660 – Autocomplete (later release)
•	1661 – Pagination (later release)

**Comment by Kibrahacha67** [comment]
Tested in Chrome, IE, Edge, FF and Safari and mobile. LHammond

**Comment by kbwagner** [comment]
2/21 - Tested ok in Chrome.  Unable to test in IE.
