### ISSUE TITLE
As an Open Opportunities user, I want system emails to have updated OPM branding applied.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1567]
Acceptance Criteria: 
o	Assumption:  new Amazon email tool is not in place by January and that we will continue using current Mandrill system email tool.
o	Open Opps has a base layout so branding is part of Open Opps and not dependent on tool (Mandrill or Amazon)

1) Apply new branding to Open Opps email templates. 
2) Ensure all links within email point to the new URL

Note: Email content and a standard email text footer will be part of a separate ticket 1583.

Invision Mock: https://projects.invisionapp.com/d/main#/projects/prototypes/12657410 scroll to the bottom "email" section.

Related Tickets:
1542 - Replace email tool with Amazon Web Servies
1583 - Update email content/footer

**Comment by Kibrahacha67** [comment]
Tested this and the image is too large across the page.  If I have it sent to my phone, it displays correctly, but if it is on normal email or enlarged to screen size the image displays across the page in large letters.  In that case it does not meet the criteria of the invision Mock up.

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
3-6-18 - LHammond In Testing
Passed Testing - LHammond 3-6-18
