### ISSUE TITLE
As an open opportunities user, I want the site URLS to reflect USAJOBS and to be redirected when I visit the old URLs.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1568]
Acceptance Criteria: 

Create new OPM/USAJOBS URLS for Open Opportunities: 
1) Production: https://openopps.usajobs.gov
2) Staging:  https://openopps.uat.usajobs.gov 
3) Dev: openopps.dev.app.cloud.gov 

For the production URL only, set up redirect from old pages for those that have bookmarks.
The redirects will last for (TBD) amount of time.

**Comment by margaretdumas** [comment]
Tested By: Margaret Dumas on 1/12/2018

Results:   I was able to verify Production and staging but I couldn't verify that the redirect has been set up for the DEV environment.

**Comment by kbwagner** [comment]
@margaretdumas - When I click on my old bookmark for stage: https://openopps-staging.app.cloud.gov/ I get a page not found instead of a redirect.  Not the end of the world since not a lot of people have access to Stage/UAT but can you confirm whether it should have worked?  Prod works fine.

**Comment by LisaLNelson** [comment]
1/24/2018 Redirect working great on production.
