### ISSUE TITLE
As an open opportunities seeker, I would like to have additional search filters to enhance my ability to find an opportunity.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1569]
From November 2017 Office Hours - add filters to be able to search for how many hours or days a task will take (i.e. show me tasks that are less than 10 hours total, or 1 hour a week).

**Comment by kbwagner** [comment]
@LisaLNelson - we now have the time commitment filter.  Can this be closed?

**Comment by LisaLNelson** [comment]
Approved.
