### ISSUE TITLE
As an Open Opportunities administrator, I would like for the newsletter tool to be integrated into Open Opps to relieve manual work.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1570]
Possibly integrate myEmma into OpenOpps in such as by adding new accounts into the contact/distribution list automatically.

**Comment by Piglady64** [comment]
Does MyEmma have an API that we can tap into?

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41585&_a=edit
