### ISSUE TITLE
As an open opportunities seeker, I would like to be able to have my badges display on USAJOBS job applications.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1574]
From November 2017 Open Opps Office Hours: Determine a way to make badges and hours from Open Opps show on job applications.

**Comment by bmcorum** [comment]
At best I would say we could create an authenticated GET request that would allow for external applications to allow users to access his/her Open Opportunities profile. USAJOBS could then have a feature addition to utilize said Open Opportunities feature to retrieve these details. I would NOT recommend allowing Open Opportunities to POST directly to USAJOBS.

**Comment by kbwagner** [comment]
Would badges then be sent to the TAS?

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41527&_a=edit
