### ISSUE TITLE
As an open opportunities participant, I want to be able to print a certificate that shows I have completed my task.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1579]
Provide the ability for Open Opportunities to print certificates of recognition for task takers.  
- Print certificate of completion of task
- Print certificate of receipt of badge.

**Comment by kbwagner** [comment]
@abudz19 do you think you could design a certificate of some sort that could be printed from Open Opps?  If so I can add this to the design task list.

**Comment by kbwagner** [comment]
1/8/2020:
- cloud.gov may limit our ability to do a .pdf
- would have to do an HTML version of the certificate and user would print browser page
- @abudz19 please add a design ticket to work on.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41584&_a=edit
