### ISSUE TITLE
Add agency admin role

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1580]
Agency admin role needs added to manage the Open Opportunities process in their agency including:

Publish tasks submitted by agency staff
Assign someone else to be an agency admin, same domain as their agency 
Access their agency’s dashboard
Unlock user accounts by resetting their password 
Review/publish new opportunities
Modify any profile or task for their agency, except for admin’s’
Delete a draft task for their agency
Edit an opportunity for their agency
Publish an agency task

**Comment by Kibrahacha67** [comment]
This item completed testing and can move to review.

**Comment by LisaLNelson** [comment]
Closing issue #1064 which is related.

**Comment by LisaLNelson** [comment]
1/25/2018 Lisa reviewed
