### ISSUE TITLE
As an open opportunities participant, I want the emails I receive to be clear, concise and consistent.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1583]
Shell ticket for:
1) Update current system email content
2) Create standard footer for all emails.
3) Create a text and HTML based version of each email - or make responsive?

Related Tickets: 
- 1567 - Apply branding to emails
- 1542 - Implement Amazon email system

**Comment by JodieYoung1** [comment]
test

**Comment by kbwagner** [comment]
Test comment for Jodie.

**Comment by kbwagner** [comment]
I just added a test comment.  I didn’t tag you but hoping you get it because you’re assigned.  Let me know.

Katrina Wagner
U.S. Office of Personnel Management
USAJOBS Program Office
Katrina.Wagner@opm.gov

**Comment by kbwagner** [comment]
Closing - all emails were entered as their own tickets
