### ISSUE TITLE
OPM & Akamai WAF

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#1589]
In order to on-board the openopps-platform at OPM, the application must be behind Akamai. The default configuration for WAF is to block all HTTP PUT and DELETE request. Need to update the openopps-platform to not use HTTP PUT and DELETE verbs. Recommend updating to use POST verb, and additional values in the request body to provide the same functional outcome of the equivalent PUT or DELETE.

**Comment by margaretdumas** [comment]
1/24/18 - Mdumas - Testing Artifact Added. If profile update works and if the comment can be deleted, testing is successful.

**Comment by LisaLNelson** [comment]
1/24/18 Lisa reviewed
