### ISSUE TITLE
dev branch, running locally, error after signing up

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1590]
on dev branch, running locally `commit 6de973141a78bed42cbc810fca2de203c77f028c`

When I sign up, and am redirected to http://localhost:3000/tasks, I don't see any opportunities and see an error in the console:
 ```
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

![image](https://user-images.githubusercontent.com/41906/34386017-5a16a576-eadb-11e7-9e9f-b9deb97820f3.png)

When I reload the page, I see an updated header with my name in top-right, then I don't get the 403 error, but still see this error in the console:

```
Uncaught TypeError: Cannot read property '0' of undefined
```

**Comment by ultrasaurus** [comment]
my guess is that this happens because I haven't confirmed my email address and it should instead display an error or some kind of helpful message

**Comment by bmcorum** [comment]
@ultrasaurus should not be related to email confirmation. Do you have opportunities in your local database?

**Comment by ultrasaurus** [comment]
@bmcorum yep, I ran `npm run demo` and when I wasn't logged in, I could press the big red "Get Started Today" button on the homepage and see opportunities.  (Also confirmed I can log out and then I see opportunities at: http://localhost:3000/tasks

**Comment by bmcorum** [comment]
@ultrasaurus so this only errors when logged in and with demo data. I have updated my system to using data we dumped from staging. So it might be an issue with some demo data that might be missing some values

**Comment by bmcorum** [comment]
@ultrasaurus we should be logging additional details to the terminal window. Can you see if we might be throwing a database query error?

**Comment by bmcorum** [comment]
@ultrasaurus I believe the issue is that the users.csv does not insert the agency tag for the users and the data query expects that all users have an agency since it is a required field. So we need to update the demo data process to create the required agency tags.

**Comment by ultrasaurus** [comment]
@bmcorum I created a new user -- though I did notice I had three entries for GSA in my agencies list.  I started from an old install which had no users or tasks in the database, but perhaps I had done `npm run init` before and maybe that script doesn't check for duplicates...  I'm going to test a fresh install to confirm.

**Comment by ultrasaurus** [comment]
Ok, that was a red herring.  I dropped my local db and setup all the demo data.  Then signed up as a new user, choosing GSA (where there was only one in the list) for my agency -- and just in case it makes a difference, I'm using my old gsa.gov address for local testing for now.

in  `user.js` it creates the class method `get` inside ` _createClass(User, [{...`

Setting a breakpoint in the Chrome debugger, at `     if (!agencyTag) {` 

I see that the `data` field is a string:

![image](https://user-images.githubusercontent.com/41906/34388597-62ed87a6-eae9-11e7-963a-2799e522628c.png)

later in the code, it expects for it to be an array

**Comment by bmcorum** [comment]
@ultrasaurus it is related to the init.js file. It creates the agency tag entities and inserts the data value as a string rather than JSON. We will need to update the init.js file to insert the data values as JSON and not as strings. That way when we pull the agency tag we get an object rather than a string.
