### ISSUE TITLE
Google Analytics deploy for Open Opps.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1602]
Deploy the Google Analytics 

Brody has set up a  Google Analytics “property” for OpenOpps under the USAJOBS GA account and can grant access to anyone we want.

Below are the tracking codes we’ll need to integrate into our pages. If the site moves from https://openopps.digitalgov.gov we may need to revise the codes:

Google Analytics Code:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94043649-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94043649-2');
</script>

Related ticket: 1654: Deploy DAP
Brody: I think this will be two separate issues, and we may need to work out where we can deploy DAP (i.e., not pages you have to be signed in to see). Our Terms of Service with DAP is for not deploying to non-public sites - this is why we don’t have DAP on ATP.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

I would say just navigate the site throughout the day and we will collect artifacts from Google Analytics to attach to this ticket.

**Comment by jhanson12** [comment]
[Analytics All Web Site Data Audience Overview 20180305-20180311.pdf](https://github.com/openopps/openopps-platform/files/1804438/Analytics.All.Web.Site.Data.Audience.Overview.20180305-20180311.pdf)

**Comment by jhanson12** [comment]
[Analytics All Web Site Data Users Flow 20180305-20180311.pdf](https://github.com/openopps/openopps-platform/files/1804448/Analytics.All.Web.Site.Data.Users.Flow.20180305-20180311.pdf)

**Comment by jhanson12** [comment]
[Analytics All Web Site Data Browser & OS 20180305-20180311.pdf](https://github.com/openopps/openopps-platform/files/1804450/Analytics.All.Web.Site.Data.Browser.OS.20180305-20180311.pdf)

**Comment by Kibrahacha67** [comment]
3-13-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas  and @Kibrahacha67 this can be moved to review. See attachment. Data is being tracked in Google Analytics account.

[Analytics All Web Site Data New vs Returning 20180224-20180325.pdf](https://github.com/openopps/openopps-platform/files/1848406/Analytics.All.Web.Site.Data.New.vs.Returning.20180224-20180325.pdf)

**Comment by kbwagner** [comment]
@brodydittemore - tagging  you to see if you want to take a look at this ticket and make sure it is ok by you.

**Comment by kbwagner** [comment]
@LisaLNelson - I think this is ok to move forward based on the artifacts.  You and I should get our accounts set up.  Brody sent me some instructions on how to create accounts.

**Comment by LisaLNelson** [comment]
Moved to ready to deploy.

**Comment by LisaLNelson** [comment]
Approved for closure LN
