### ISSUE TITLE
Admin - Password Reset Has No Validation on Confirm Field

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#1616]
Reset   Password - There is no validation around the confirm password. I was able to enter different text in the confirm field and was able to save it.
--

**Comment by Kibrahacha67** [comment]
Tested - Validated that there are controls in place to ensure that passwords match.  Functionality works as expected. Can be moved to review.

**Comment by kbwagner** [comment]
1/24/18: KWagner tested in UAT

**Comment by LisaLNelson** [comment]
1/24/2018 Lisa tested in UAT
