### ISSUE TITLE
Need a notification email when users comment on an op you've volunteered for

### ISSUE THREAD

**Issue by Chessen** [openopps/openopps-platform#162]
I know we said to hold off on enhancement requests, but this is higher priority. We need to activate notifications when there are comments on an opportunity a user volunteered for. Without this, a user who volunteers for an op has to keep checking back to see if there is new activity. 

We missed this one when developing the requirements. Not critical, but high priority next time we touch notifications.

@polastre I was going to revise the requirements doc at https://github.com/Innovation-Toolkit/midas/wiki/Notification-Business-Requirements and note what's been done and prioritize the remainder. Then we can turn this into a general enhancement for the next round of P1s. Sound good?

**Comment by dhcole** [comment]
Background on setting up notifications: https://github.com/18F/midas/wiki/Notifications

**Comment by LisaLNelson** [comment]
This issue has been completed and is now connected connected to: Unable to make a comment on an opportunity · Issue #1445 · openopps/openopps-platform
