### ISSUE TITLE
Images in IE and Edge Are Not Displaying

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#1628]
Images are not showing up in edge or IE11 (works in firefox, Chrome)

**Comment by Kibrahacha67** [comment]
LHammond - 1/22/18 - Tested and both IE and Edge are showing images.  This can move to review.

**Comment by kbwagner** [comment]
1/24/18 - Katrina tested in UAT/Stage

**Comment by LisaLNelson** [comment]
1/24/18 Lisa reviewed
