### ISSUE TITLE
Opportunity State Process

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#1629]
A non   admin user has the ability to approve/change the Opportunity State.  The problem here is that I can go in and   put in a new task, then log out and log in and change the state from draft to   Open without an admin review, which is the process today.

**Comment by bmcorum** [comment]
@Kibrahacha67 and @LisaLNelson I think we have a bigger issue here. It appears as though you can update a task from **submitted** to **open** using the change opportunities state link. Preforming said action updates the UI, however if you then refresh the page you will see the opportunity is still **submitted**. You can however, if an admin, from the admin panel covert submitted opportunities to open opportunities. I think we need to discuss how this should function and build out the necessary acceptance criteria.

Point to think about
- Should we even show the *change opportunity state* link to non-admins? (We don't show it if task is draft)
- Should we force admins to update **submitted** opportunities to **open** via the admin console or allow them to update it directly from the opportunity page?

**Comment by kbwagner** [comment]
@Kibrahacha67 - can this be closed since the new manage opportunity process has been created?

**Comment by Kibrahacha67** [comment]
3-21-18 Closed based on the new system of state changes.  LHammond
