### ISSUE TITLE
Check if cookie is invalidated / session ended

### ISSUE THREAD

**Issue by polastre** [openopps/openopps-platform#163]
Need a way for the frontend to check if a cookie has been invalidated and do a reload of the page from the server to be able to correctly show the user logged in or logged out.

**Comment by ultrasaurus** [comment]
I tried to figure out the negative consequence of this to effectively prioritize it... here are the steps I came up with:

1. log in the site
2. open a new window (notice that I'm logged in) and log out
3. go back to first window
4. go to a page that requires me to be logged in (choose Profile from user menu in top-right)

results: am prompted to log in

This seems reasonable.  If I'm missing something, feel free to re-open with use case and steps to reproduce.
