### ISSUE TITLE
Cookie Security: Persistent Cookie

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#1640]
During a WebInspect scan a medium vulnerability was detected. It was recommend that we look at using non-persistent (*session*) cookies versus persistent cookies.

![cookiesecurity](https://user-images.githubusercontent.com/1165615/34790362-9989fa16-f60f-11e7-8f08-ededf5ae9226.PNG)

**Comment by margaretdumas** [comment]
1/24/18 - Mdumas - Artifact Attached.
![artifact for 1640](https://user-images.githubusercontent.com/19936109/35354759-2346bbf4-0119-11e8-86af-cd9f3dbc3cb4.gif)

**Comment by LisaLNelson** [comment]
1/24/18 Lisa reviewed
