### ISSUE TITLE
As an Open Opportunities user, I would like to know how much total time is involved in my task.  

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1644]
Add Hours and Weeks to Tasks.
As an Open Opps user, I'd like to know how much time, for how long I'm volunteering to commit to a task. Tasks in Open Opps should include information on how many hours per week and how many weeks the task is expected to take. The task creator should enter in how many weeks the task will run, and how many hours per week are expected. The potential task taker should be able to see the hours per week and number of weeks. There should also be an estimated completion date for both ongoing and one-time tasks. 
From 1051 - We need to fix the Time Commitment so that it doesn't say per week for a one-time task. That should only show if it is an on-going task.

From Ticket 1310 (closed as duplicate):
This comment was received on our annual survey:
"Hard to imagine how to dive in. For example, I just saw one opp listed that intrigued me: "Help document the new USAGov Platform API." I believe the phrase that caught my attention was "Technical Writer." I am a process oriented person with better than average writing skills. However, the description states 24-40 hours per week. To truly be able to micro-task, and build my own self-confidence as well as gain the support of my boss, I need to start with something that might take an hour or two, or even an hour a day for two to three days a week, perhaps for a couple of weeks max. If you can further lower the barriers to participation I believe you could truly strike gold!"

When I looked at the task again and talked to the task creator he wanted to denote the task would take between 24-40 hours total spread out over a few weeks but when he clicked the button for 16-24 hours it showed up on the task as 16-24 hours a week.

screen shot 2016-05-06 at 1 42 16 pm

screen shot 2016-05-06 at 1 41 10 pm

**Comment by kbwagner** [comment]
Merged 1310 into this ticket since it was duplicate and closed 1310.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41576&_a=edit
