### ISSUE TITLE
Open Opps Timeout- Please Set to 30 Minutes

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1645]
As an Open Opps user, I'd like to know how much time is left on my session on Open Opps, and to have the timeout window match USAJOBS' at 30 minutes. 

Please set the timeout to 30 minutes, and have notifications at 10, 5, and 1 minutes that they are about to be logged out and how to stay logged in, if desired.

**Comment by bmcorum** [comment]
- [ ] Update TTL for Redis to 30 minutes (maybe 35 so we have a margin of error between client and server)
- [ ] Create inactivity modal to alert user of timeout resulting in forced logout
  - 1 button "Stay logged in"
  - 1 button "Log out"
- [ ] Create client timer for 30 minutes.
- [ ] Display inactivity modal at 10 minutes with countdown.
- [ ] Global event listener for client UI interaction to extend timer and Redis session

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 you may need to clear your local browser cache first before testing. After you log in and are inactive for about 27 minutes you should get a modal pop-up that you session is about to expire in 3 minutes. As long as you are navigating pages or typing in a form it should keep you session refreshed.

**Comment by Kibrahacha67** [comment]
This item was tested in IE, Edge and Chrome with no issues.  It is ready for review.  below is a screen shot of the time out message.

**Comment by bmcorum** [comment]
![sessiontimoutwarning](https://user-images.githubusercontent.com/1165615/35171868-4a2998ac-fd33-11e7-9498-74dbd1ece861.png)

**Comment by LisaLNelson** [comment]
1/26/2018 Lisa reviewed

**Comment by KatMullens-work** [comment]
Is this ticket still "open"?

**Comment by KatMullens-work** [comment]
Please hold off on this; USAJOBS and ATP are working on their policy. Please see ticket 32666.

Asked for clarification from Dan. Will report back findings!

**Comment by kbwagner** [comment]
@KatMullens-work this ticket has already been done.  It's in "ready for deployment" status and has already been tested.  If something changes with policy we'll have to enter another ticket to change the timeout.
