### ISSUE TITLE
Open Opps Login Email Should Not be Case Sensitive

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1646]
As an end user, I want to be able to log in without having to remember what capitalization was used when I set up my account. At present, the wrong case usage will make a log in fail. Please make log in email addresses not be case sensitive.

**Comment by bmcorum** [comment]
I think it would be best to just force all emails/usernames to lowercase.

- [ ] Force lowercase on email/username at account creation
- [ ] Force lowercase on email/username lookup
- [ ] Force lowercase on email/username at login
- [ ] Force lowercase on email/username change on profile edit
- [ ] Database migration to update existing email/username to lowercase

**Comment by Kibrahacha67** [comment]
LHammond - 1/23/18 - Tested in IF, Edge, Chrome and FireFox.  All tests good this can be moved to review.

**Comment by kbwagner** [comment]
1/24/18 - Katrina tested in UAT environment.  No issues.

**Comment by LisaLNelson** [comment]
1/24/18 Lisa tested in UAT

**Comment by bmcorum** [comment]
#1652

**Comment by bmcorum** [comment]
#1652

**Comment by KatMullens-work** [comment]
Should this issue still be "open"?

**Comment by kbwagner** [comment]
@KatMullens-work this one is also in ready to deploy and Brice will update them to "closed" with the 3/9 release.
