### ISSUE TITLE
As an admin I need to get notified when someone submits a new opportunity for publishing.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1648]
Closing - replaced by 1686.

Right now I do not know when a new opportunity is waiting in the que for me to approve and I may nt respond in a timely manner.

Here is an example of the email I used to get.
Dear Brice Corum,

Your opportunity, "____________________________" is now open.

You will receive a notification each time someone signs up to participate in this opportuntity.

Your opportunity will remain open for applications until either (1) you assign the opportunity to one or more applicants or (2) you archive the opportunity in the system.

Thanks! 
- The OpenOpportunities Development Team

**Comment by bmcorum** [comment]
@LisaLNelson this email is drafted in terms of speaking to the user who created the opportunity. I think it would be better and less confusing to send an email to admins with wording related to the fact that another user has submitted a task for review. Example.

Dear Admin(s),

Brice Corum has submitted the opportunity "_______________" for review.

[button to review the opportunity. Takes the admin to the dashboard and the submitted tab]

Thanks,
The OpenOpportunities Development Team
