### ISSUE TITLE
As a task creator, I want to be able to clearly identify which applicants have been assigned to my task.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1656]
Acceptance Criteria:
Part 1: Applicants vs Assigned Participants
- On the task creator page, applicants will be divided into Assigned participants and Applicants
- Prior to anyone being assigned, the Assigned participants section will have a "Click X to assign participants" message.  The "next" button will be grayed out.  The progress bar will show assigning.  If the job is still toggled to Open, a green "Open" pill will display on the top left.  
- When the task creator selects at least one of the applicants, they will be moved up to the Assigned participants section and the "Next" button will become active.  The progress bar will now reflect "In Progress?
- When the task creator selects "Next", a "Let's get started" message displays.  The message reads, "We've emailed the participants you've selected.  Now it's time for you to kick things off:
1.  Contact your participants and go over their tasks.
2. Email the participants you didn't select so they can look for other opportunities.
3. Turn the toggle back on if you want to keep accepting participants.
4. Keep in touch with your participants to track status.
5. Don't forget to mark this as complete when you're done!
- Existing users that are "selected" when the Next button is selected.  If someone is assigned after the assigned state, the "selected" email will be sent when the applicant is added as a selected participant.
- Email triggers are outlined in the email tickets 1695 and 1696

What to do with existing data: 
- if open then all applicants stay applicants, if assigned or closed all applicants become assigned participants.
- if open then accepting applicants is set to "on" if assigned or closed then accepting applicants is set to "off"

Link to Prototype: 
Assigning Applicants: https://projects.invisionapp.com/d/main#/console/12657410/269951246/preview
Desktop- https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
Mobile- https://projects.invisionapp.com/d/main#/projects/prototypes/12656859

Related Tickets: 
1168 - Marking Tasks completed.
1695 - Task Taker Assigned email
1696 - Task Taker not assigned email

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas, this is ready for testing.

**Comment by Kibrahacha67** [comment]
LHammond - In Testing 3-2-18
