### ISSUE TITLE
Categorize Opportunities by Audience (Product Owner)

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1657]
As a product owner, I would like the ability to categorize opportunities by audience (for example, by
Agency, special Program (PMF…), Occupation, Customer group (VSFS, etc.). This should be a repeatable process (cyber, PMF…DHS/SSA/FDA), searchable, and reportable in the admin space of Open Opps.

**Comment by humancompanion** [comment]
@minchung12 and I are working on defining how we do this. Folks can follow along here https://trello.com/c/suRTyrYS. I'll summarize where we land in this issue as well.

**Comment by kbwagner** [comment]
@KatMullens and @minchung12 -work would this be covered by the addition of the Career Field?  If so, we could close this ticket.

**Comment by kbwagner** [comment]
This should be covered by communities
