### ISSUE TITLE
As an administrator, I would like to be able to see metrics on task creators closing their tasks.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1662]
Acceptance Criteria:
- Create a query that identifies how many task creators complete/close their jobs on their own without Lisa's intervention.
-Track who the last person to update the task was. I.E. updatedBy
- How many opportunities are closed where the updatedBy is now equal to Lisa vs which ones are not.

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

Step for testing.

- update several opportunities (draft, submit, open, in progress, complete, cancel)
- Once complete I can see about getting a snapshot of database records to prove the data is being updated

**Comment by Kibrahacha67** [comment]
3-6-18 LHammond in testing
