### ISSUE TITLE
As an Open Opportunities User, I would like to have consistent spacing applied throughout the system to create a consistent user experience.  (Design System)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1666]
Acceptance Criteria:
Apply design system Spacing changes to all pages of Open Opportunities.

Apply the CSS from the design system to all pages and components in Open Opportunities

Design System Link: http://usajobs.github.io/design-system/getting-started/
InVision Prototype Desktop: https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
InVision Prototype Mobile: https://projects.invisionapp.com/d/main#/projects/prototypes/12656859
List of Open Opps Pages: https://airtable.com/tblC0ddHd2X29xoa8

Related Tickets: 
•	1565 – Footer
•	1563 - Colors
•	1665 - Typography
•	1666 - Spacing
•	1667 - Shell of the page (breakpoints)
•	1668 - Buttons 
•	1669 - Form Elements
•	1670 - Logo – Powered by USAJOBS logo
•	1672 - Top Navigation
•	1660 – Autocomplete (later release)
•	1661 – Pagination (later release)

**Comment by margaretdumas** [comment]
Mdumas - In testing

**Comment by margaretdumas** [comment]
02/27/2018 -Mdumas - All pages that are completed do not meet spacing requirements. 
- Tasks area(requested by)
- Filters area

**Comment by margaretdumas** [comment]
Mdumas - Inconsistent spacing. Create an opportunity page (tags).

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by margaretdumas** [comment]
03/06/2018 - Mdumas - Moving to review.
