### ISSUE TITLE
As an Open Opportunities user, I want to have standard page breakpoints and page shells in order to have a consistent user experience.  (Design System)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1667]
Acceptance Criteria:

Apply design system page shell/breakpoints changes to all pages of Open Opportunities.

Apply the CSS from the design system to all pages and components in Open Opportunities

Design System Link: http://usajobs.github.io/design-system/getting-started/
InVision Prototype Desktop: https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
InVision Prototype Mobile: https://projects.invisionapp.com/d/main#/projects/prototypes/12656859
List of Open Opps Pages: https://airtable.com/tblC0ddHd2X29xoa8

Related Tickets: 
•	1565 – Footer
•	1563 - Colors
•	1665 - Typography
•	1666 - Spacing
•	1667 - Shell of the page (breakpoints)
•	1668 - Buttons 
•	1669 - Form Elements
•	1670 - Logo – Powered by USAJOBS logo
•	1672 - Top Navigation
•	1660 – Autocomplete (later release)
•	1661 – Pagination (later release)

**Comment by margaretdumas** [comment]
In Testing - Mdumas

**Comment by margaretdumas** [comment]
02/23/2018 - Mdumas - Pending Code push to UAT for testing

**Comment by margaretdumas** [comment]
02/26/2018 - Mdumas - Mobile does not render properly.

**Comment by margaretdumas** [comment]
03/01/2018- Mdumas - Also text on edit profile page is going beyond page area when at certain breakpoints.

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by margaretdumas** [comment]
03/05/2018 - Mdumas - I am moving this one back to development for mobile . It is not responsive in mobile.

**Comment by margaretdumas** [comment]
Mdumas - Page shell is good.  We have tickets for mobile.  Moving through testing.
