### ISSUE TITLE
As an Open Opportunities user, I want to have standard buttons used throughout the system so I can have a consistent user experience.  (Design System)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1668]
Acceptance Criteria:

Apply design system changes for buttons to all pages of Open Opportunities.  

Apply the CSS from the design system for buttons to all pages and components in Open Opportunities.

Design System Link: http://usajobs.github.io/design-system/getting-started/
InVision Prototype Desktop: https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
InVision Prototype Mobile: https://projects.invisionapp.com/d/main#/projects/prototypes/12656859
List of Open Opps Pages: https://airtable.com/tblC0ddHd2X29xoa8

Related Tickets: 
•	1565 – Footer
•	1563 - Colors
•	1665 - Typography
•	1666 - Spacing
•	1667 - Shell of the page (breakpoints)
•	1668 - Buttons 
•	1669 - Form Elements
•	1670 - Logo – Powered by USAJOBS logo
•	1672 - Top Navigation
•	1660 – Autocomplete (later release)
•	1661 – Pagination (later release)

**Comment by margaretdumas** [comment]
02/26/2018- Mdumas - Secondary buttons do not have focus on tab as per design system.  Moving back to development.

**Comment by margaretdumas** [comment]
02/28/2018 - Mdumas - Secondary buttons still do not gain focus on tab. 
-Sign in page
-Create account page
-Edit profile page
-Create opportunity page
-Edit opportunity page
-Session expire page

**Comment by margaretdumas** [comment]
03/06/2018 - Mdumas - Moving to review
