### ISSUE TITLE
Migrate from underscore to lodash for node.js/sails

### ISSUE THREAD

**Issue by polastre** [openopps/openopps-platform#167]
lodash is a lot more useful to us on the backend than underscore, plus it is faster and has more functionality.  We should migrate all instances of underscore to lodash.

This came to light in #166

**Comment by dhcole** [comment]
Lodash is included with an globally available through Sails. So we just need to remove underscore as a server-side dependency wherever it's `require`d and test that the application works correctly. There are a few inconsistencies to watch out for, particularly that `_(foo).method()` and `_.method(foo)` are handled differently. In underscore, these are the same, but in Lodash, the first format automatically `chain`s the methods (`like _.chain(foo).method()`), so it needs to end in a `.value()`.

**Comment by kbwagner** [comment]
Closing per backlog review
