### ISSUE TITLE
As an Open Opportunities user, I want to have a consistent powered by USAJOBS logo applied to all pages of the system so that I can have a consistent user experience. (Design System) 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1670]
Acceptance Criteria:

Apply design system and CSS changes for Logo to all pages of Open Opportunities.  The new logo will reflect that Open Opportunities is now powered by USAJOBS.  

Design System Link: http://usajobs.github.io/design-system/getting-started/
InVision Prototype Desktop: https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
InVision Prototype Mobile: https://projects.invisionapp.com/d/main#/projects/prototypes/12656859
List of Open Opps Pages: https://airtable.com/tblC0ddHd2X29xoa8

Related Tickets: 
•	1565 – Footer
•	1563 - Colors
•	1665 - Typography
•	1666 - Spacing
•	1667 - Shell of the page (breakpoints)
•	1668 - Buttons 
•	1669 - Form Elements
•	1670 - Logo – Powered by USAJOBS logo
•	1672 - Top Navigation
•	1660 – Autocomplete (later release)
•	1661 – Pagination (later release)

**Comment by Kibrahacha67** [comment]
Tested in Chrome, IE, Edge, FF and Safari and mobile.  LHammond

**Comment by kbwagner** [comment]
Tested ok in Chrome 2/21.  Unable to test in IE.
