### ISSUE TITLE
As a task creator, I need a clear way to close my opportunity so that I will be encouraged to finish and close out my work.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1672]
Acceptance Criteria: 

- The complete opportunity button will turn blue and enabled once at least least one assigned participant is marked as "Task Completed"
- If complete opportunity is selected but not all participants are marked as Task Completed, a message displays https://projects.invisionapp.com/d/main#/console/12657410/271046225/preview that reads, "This participant hasn't completed their task and will not get credit.  Do you still want to complete the opportunity?".  There is a confirm and cancel button.  Cancel will return the user to the previous page.  confirm will complete the opportunity.
- When Complete opportunity is selected, a "Congratulations You've successfully completed <name of opportunity.>  We updated your profile with your achievement.  Don't forget to thank your participants for a job well done."  There is a Done button.  Done will close the message.
- A message will display under the progress bar that reads "Completed mm/dd/yyyy"
- Send completed emails at this point.

Prototype:
Complete: https://projects.invisionapp.com/d/main#/console/12657410/268504230/preview
 https://projects.invisionapp.com/d/main#/console/12657410/275766415/preview

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
Lhammond 3-5-18 In Testing
