### ISSUE TITLE
Update Search Box on Open Opps To Delete Search Button and Add Small Magnifying Glass

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1678]
As an Open Opps user, I want to use the dynamic filtering capabilities of the existing search technology while still seeing a visual indicator that it's a search box. 

This design helps accomplish both.

![image](https://user-images.githubusercontent.com/25315047/35828980-6376b2b8-0a8f-11e8-9113-a2bce8542b07.png)

**Comment by kbwagner** [comment]
@KatMullens-work can you please retest.  Believe this is resolved.

**Comment by KatMullens-work** [comment]
This is resolved and the issue can be closed.
