### ISSUE TITLE
Update OpenOpps.USAJOBS.gov Screen Shot Under "How does it work?"

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1680]
![katrina](https://user-images.githubusercontent.com/25315047/35829098-c60af84e-0a8f-11e8-8b34-95b05db0c701.png)

As a user, on the front page of OpenOpps.USAJOBS.gov, I should see a screen shot of the current product. Under the section  “How does it work?”  the screenshot image of the open-opps is the old version. Attached is the old image. Please update to a new image.

**Comment by KatMullens-work** [comment]
New screen shot from Min is attached.
![landing-how-image](https://user-images.githubusercontent.com/25315047/36158065-62477ae2-10a9-11e8-8d0c-936fd70bac37.png)

**Comment by Kibrahacha67** [comment]
Tested on UAT and the new image is not showing on the landing page. LHammond 2-22-18

**Comment by margaretdumas** [comment]
Mdumas - Moving to review
