### ISSUE TITLE
Open Opps System Email <Forgot password>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1683]
As an Open Opps Admin and/or User, I would like to receive the following emails at the following points in the Open Opps process: 

Current Message Name: Forgot Password
Desired Message Name: Forgot Password
Message Type: 	Email
Header/Subject Copy:	Reset your password on Open Opportunities
Desired Text Copy:
Hi [[GivenName]],
Forgot your password? Click the link below or copy and paste it into your browser to reset your password.

<insert link>

Didn't request a new password? Don't worry, you can just delete this email and your password will remain the same.

Thanks,
The Open Opportunities Team

Trigger: Sign in page > User clicks 'Forgot your password?' and enters email address to system.

**Acceptance Criteria:**
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger: Sign in page > User clicks 'Forgot your password?' and enters email address to system.

Desired Text Copy:
Hi [[GivenName]],
Forgot your password? Click the link below or copy and paste it into your browser to reset your password.

<insert link>

Didn't request a new password? Don't worry, you can just delete this email and your password will remain the same.

Thanks,
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by margaretdumas** [comment]
Mdumas - in tesing

**Comment by margaretdumas** [comment]
02/28/2018 - Mdumas - Does not meet AC.  Moving Back to development.

**Comment by margaretdumas** [comment]
02/28/2018 - Mdumas - Please correct wording. 

" Forget" in first sentence should be "Forgot"

**Comment by margaretdumas** [comment]
Mdumas - Testing completed

**Comment by kbwagner** [comment]
3/1: moved back to development per Margaret

**Comment by bmcorum** [comment]
@margaretdumas and @kbwagner, sorry this got corrected with the new code push to UAT just about an hour or so ago. Sorry for the confusion.

**Comment by margaretdumas** [comment]
Mdumas - Email is correct.  Reset Password Button - functionality of button doesn't work. I will add separate bug for functionality.
