### ISSUE TITLE
Open Opps System Email <New user>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1684]
As an Open Opps Admin and/or User, I would like to receive the following email at the following point in the Open Opps process: 

Current Message Name: New user
Desired Message Name: New user
Message Type: Email
Header/Subject Copy: Welcome to Open Opportunities!
Desired Text Copy:
Hi [[GivenName]],
Welcome to Open Opportunities! We’re happy you want to get involved. As a member of this community, you’ll collaborate with people across different agencies and work on projects that interest you.

Before you start applying to opportunities, follow the steps below to complete your profile:
• Write your bio: share a bit of your background to help other members get to know you.
• Add a photo: upload a profile picture to help other members put a face to your name.
• List skills and interests: tell us about your skills and career interests. This will help task creators match you with the right opportunities.

Thanks,
The Open Opportunities Team

Trigger: When user completes registration for Open Opportunities. 

**Acceptance Criteria:**
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger: When user completes registration for Open Opportunities. 

Desired Text Copy:
Hi [[GivenName]],
Welcome to Open Opportunities! We’re happy you want to get involved. As a member of this community, you’ll collaborate with people across different agencies and work on projects that interest you.

Before you start applying to Opportunities, please follow the steps below to complete your profile:
• Write your bio: share a bit of your background to help other members get to know you.
• Add a photo: upload a profile picture to help other members put a face to your name.
• List skills and interests: tell us about your skills and career interests. This will help Opportunity Creators match you with the right Opportunities.

Thanks,
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by bmcorum** [comment]
@margaretdumas and @lawrencek76 this is ready for testing

**Comment by KatMullens-work** [comment]
Hi team:

I thought we were going to change all "task" to "opportunities"? Please change in this email if possible: 

Desired Text Copy:
Hi [[GivenName]],
Welcome to Open Opportunities! We’re happy you want to get involved. As a member of this community, you’ll collaborate with people across different agencies and work on projects that interest you.

Before you start applying to opportunities, follow the steps below to complete your profile:
• Write your bio: share a bit of your background to help other members get to know you.
• Add a photo: upload a profile picture to help other members put a face to your name.
• List skills and interests: tell us about your skills and career interests. This will help task creators match you with the right opportunities.

Thanks,
The Open Opportunities Team

ALSO: the copy I got has different sized fonts. Is this a display issue or how the email is going out? It should be the same font size.

Also, the font on this one appears different than others. Is that a display or a configuration issue? Thanks! kat

**Comment by Kibrahacha67** [comment]
4/4/18 LHammond in testing

**Comment by KatMullens-work** [comment]
This ticket passes. Thanks, team! :)

**Comment by LisaLNelson** [comment]
Approved
