### ISSUE TITLE
Open Opps System Email <Opportunity - submitted- email to Task Creator>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1685]
As an Open Opps Admin and/or User, I would like to receive the following email at the following point in the Open Opps process. 

Current Message Name: Opportunity - submitted
Desired Message Name: Opportunity - submitted- email to Task Creator
Message Type: Email
Header/Subject Copy: New opportunity submitted
Desired Text Copy: 
Hi [[GivenName]],

Thanks for submitting [[link to the opportunity that displays the opportunity name]] on Open Opportunities! We'll review your submission to make sure it has all the necessary information. We'll email you when it's approved or if we need more information.

Thanks, 
The Open Opportunities Team

Trigger: Task creator creates an opportunity > Clicks 'Submit for review' 

**Acceptance Criteria:**
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger: Task creator creates an opportunity > Clicks 'Submit for review' 

Desired Text Copy: 
Hi [[GivenName]],

Thanks for submitting [[link to the opportunity that displays the opportunity name]] on Open Opportunities! We'll review your submission to make sure it has all the necessary information. We'll email you when it's approved or if we need more information.

Thanks, 
The Open Opportunities Team

**Comment by kbwagner** [comment]
Test comment - Kat let me know if you get this.

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 This is ready for testing

**Comment by margaretdumas** [comment]
03/04-2018 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
Mdumas - Moving back to development.  Did not receive the email.

**Comment by raywilliams** [comment]
@margaretdumas Please check your spam folder. I tested again and received the email immediately.

**Comment by margaretdumas** [comment]
04/02/2018 - Mdumas - Testing completed for creator.

**Comment by KatMullens-work** [comment]
passed! Thank you!!

**Comment by LisaLNelson** [comment]
Approved for closure. LN
