### ISSUE TITLE
Open Opps System Email <Opportunity - submitted- email to Admin>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1686]
As an Open Opps Admin and/or User, I would like to receive the following email at the following point in the Open Opps process. THIS IS A NEW EMAIL.

Current Message Name:  This is a new email and does not have an existing message name
Desired Message Name: Opportunity - submitted- email to Admin
Header/Subject Copy: New opportunity submitted by a task creator
Desired Text Copy: 

Dear   [[Admin First Name]]:           

The message below was sent to an Opportunity Creator because they created a new task on Open Opportunities. Please review it and determine if it can be approved or needs additional information and process appropriately.          

Respectfully,      
Open Opportunities Platform     

------------------------------------------           
Hi [[GivenName]],     

Thanks for submitting [opportunity name](link) on Open Opportunities! We'll review your submission to make sure it has all the necessary information.   We'll email you when it's approved or if we need more information.         

Thanks,      
The Open Opportunities Team

Trigger:  Task   creator creates an opportunity > Clicks 'Submit for review'

**Acceptance Criteria:**
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger:  Task   creator creates an opportunity > Clicks 'Submit for review'

Desired Text Copy: 

Dear   [[Admin First Name]]:           

The message below was sent to an Opportunity Creator because they created a new Opportunity on Open Opportunities. Please review it and determine if it can be approved or needs additional information and process appropriately.          

Respectfully,      
Open Opportunities Platform     

------------------------------------------           
Hi [[GivenName]],     
Thanks for submitting [opportunity name](link) on Open Opportunities! We'll review your submission to make sure it has all the necessary information.   We'll email you when it's approved or if we need more information.         

Thanks,      
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by KatMullens-work** [comment]
Hi @jhanson12 : I got the notice that I created this opportunity and it had been submitted. I'm also an admin and I did not get the notice to go in and review the newly-submitted open opportunity.

**Comment by margaretdumas** [comment]
04/02/2018 - Mdumas - In testing

**Comment by margaretdumas** [comment]
04/02/2018 - Mdumas - Did not receive email, moving back to development....

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
04/03/2018 - Mdumas - Testing complete

**Comment by KatMullens-work** [comment]
Hi Team:

This doesn't look like the right copy. What am I missing?

thanks, 
kat

Hi Kat Mullens,
The message below was sent to a task creator because they created a new task on Open Opportunities. Please review it and determine if it can be approved or needs additional information and process appropriately.
Respectfully,
Open Opportunities Platform
------------------------------------------
Hi Kat Mullens,
Thanks for submitting Posting Opp to complete it for testing on Open Opportunities! We'll review your submission to make sure it has all the necessary information. We'll email you when it's approved or if we need more information.
Thanks,
The Open Opportunities Staging Team

**Comment by bmcorum** [comment]
@KatMullens-work you are an admin so you got two emails. One as the last creator and one as an admin. Moving back to review

**Comment by LisaLNelson** [comment]
Moved to Ready to deploy - LN

**Comment by LisaLNelson** [comment]
Approved for closure. LN
