### ISSUE TITLE
Open Opps System Email <Opportunity - approved - open>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1687]
As an Open Opps Admin and/or User, I would like to receive the following email at the following point in the Open Opps process:

Current Message Name: Opportunity - approved - open
Desired Message Name: Opportunity - approved - open
Header/Subject Copy: Your opportunity is approved and open
Desired Text Copy: 

"Hi [[GivenName]],
We approved your opportunity,[opportunity name - link] and it's now open and accepting applicants.

You'll get a notification each time someone signs up to participate in this opportunity.

What do you do now?
1. Start reviewing and assigning participants.
2. Cancel the opportunity if it's no longer needed.

Thanks, 
The Open Opportunities Team

Trigger:  Admin approves and changes the status of submitted opportunity from Submitted to Open

**Acceptance Criteria:**
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger:  Admin approves and changes the status of submitted opportunity from Submitted to Open

Desired Text Copy: 

"Hi [[GivenName]],
We approved your opportunity,[opportunity name - link] and it's now open and accepting applicants.

You'll get a notification each time someone signs up to participate in this opportunity.

What do you do now?
1. Start reviewing and assigning participants.
2. Cancel the opportunity if it's no longer needed.

Thanks, 
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 This is ready for testing

**Comment by Kibrahacha67** [comment]
4/3/18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 This is ready for testing

**Comment by Kibrahacha67** [comment]
4/5/18 LHammond in testing

**Comment by KatMullens-work** [comment]
This item passes testing. Thanks, team!

**Comment by LisaLNelson** [comment]
Good to go!
