### ISSUE TITLE
Open Opps System Email <Opportunity - not approved> *Needs tech/design spec to implement

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1688]
Needs a design:
- Ability for admin to reject an opportunity
- On the reject, a comment box will open to state the reason for rejection
- Reason for rejection will display on the below email
- Reason for rejection should display on the task creator view of the opportunity.
(should be split into two tickets - one for functionality and one for email)

As an Open Opps Admin and/or User, I would like to receive the following email at the following point in the Open Opps process but we need tech/design specs to implement.

Current Message Name:  Opportunity - not approved
Desired Message Name:  Opportunity - not approved
Header/Subject Copy: Please update your opportunity on Open Opportunities
Desired Text Copy: 
"**If it's missing information

Hi [[GivenName]], 

We reviewed your [opportunity name-link] and it's missing some information.

Please update it with the following information:
* [insert missing info 1]
* [insert missing info 2]
* [insert missing info 3]

Once you make the updates, please submit it and we'll review it again.  We'll email you when it's approved or if we need more information.

Thanks,
The Open Opportunities Team

** If it has all of the information, but needs more detail or a rewrite:

Hi [[GivenName]], 

We reviewed your [opportunity name-link] and it needs some updates.

* [insert update info 1]
* [insert update info 2]
* [insert update info 3]

Once you make the updates, please submit it and we'll review it again.  We'll email you when it's approved or if we need more information.

Thanks,
The Open Opportunities Team

Trigger:  Admin does not approve the opportunity. Status moves from submitted to TBD (ticket needed in Github to establish process/functionality @bmcorum -this ticket only covers the email content and trigger)

**Acceptance Criteria:**

The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.
Trigger:  Admin does not approve the opportunity. Status moves from submitted to TBD (ticket needed in Github to establish process/functionality @bmcorum -this ticket only covers the email content and trigger)

Desired Text Copy: 
"**If it's missing information

Hi [[GivenName]], 

We reviewed your [opportunity name-link] and it's missing some information.

Please update it with the following information:
* [insert missing info 1]
* [insert missing info 2]
* [insert missing info 3]

Once you make the updates, please submit it and we'll review it again.  We'll email you when it's approved or if we need more information.

Thanks,
The Open Opportunities Team

** If it has all of the information, but needs more detail or a rewrite:

Hi [[GivenName]], 

We reviewed your [opportunity name-link] and it needs some updates.

* [insert update info 1]
* [insert update info 2]
* [insert update info 3]

Once you make the updates, please submit it and we'll review it again.  We'll email you when it's approved or if we need more information.

Thanks,
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by nia-johnson** [comment]
Split and moved into TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41574&_a=edit, https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41575&_a=edit
