### ISSUE TITLE
Open Opps System Email <Task due - in 7 days - Task creator>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1689]
As an Open Opps Admin and/or User, I would like to receive the following email at the following point in the Open Opps process:
Current Message Name:  Task due - in 7 days - Task creator
Desired Message Name: Opportunity due - in 7 days - Opportunity creator
Header/Subject Copy: Your opportunity is due in 7 days
Desired Text Copy: 

Hi [[GivenName]], 
We noticed that [opportunity name - link] on Open Opportunities is due next week. 

When you're done, mark your opportunity as completed. Otherwise, you and your team will not get credit.

Need more time?  Update your due date and let your team know.

You can also cancel it if you no longer need the opportunity.

Thanks, 
The Open Opportunities Team

Trigger:  7 days before its Estimated completion date/due date, opportunity is not marked as completed, if a task has a due date (not all tasks have a due date).  

**Acceptance Criteria:**

The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger:  7 days before its due date, opportunity is not marked as completed, if a task has a due date (not all tasks have a due date).

Desired Text Copy: 

Hi [[GivenName]], 
We noticed that [opportunity name - link] on Open Opportunities is due next week. 

When you're done, mark your opportunity as completed. Otherwise, you and your team will not get credit.

Need more time?  Update your due date and let your team know.

You can also cancel it if you no longer need the opportunity.

Thanks, 
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41591&_a=edit
