### ISSUE TITLE
Open Opps System Email <Task due - today - Task creator>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1690]
As an Open Opps Admin and/or User, I would like to receive the following email at the following point in the Open Opps process:

Current Message Name:  Task due - today - Task creator
Desired Message Name:   Opportunity due - today - Opportunity creator
Header/Subject Copy:  Your opportunity is due today
Desired Text Copy: 

Hi [[GivenName]], 
We noticed that [opportunity name - link] on Open Opportunities is due today, but you haven’t marked it as completed. 

Are you done? Mark it as complete so you and your team will get credit.

Need more time?  Update your due date and let your team know.

Or cancel it if you no longer need the opportunity.

Thanks, 
The Open Opportunities Team

Trigger:  24 hours before its due date, opportunity is not marked as completed, if a task has a due date (not all tasks have a due date).

**Acceptance Criteria:**

When the Trigger happens, the email text is sent to the users with any applicable links/personalization embedded/active.

Trigger:  24 hours before its due date, opportunity is not marked as completed, if a task has a due date (not all tasks have a due date).

Desired Text Copy: 

Hi [[GivenName]], 
We noticed that [opportunity name - link] on Open Opportunities is due today, but you haven’t marked it as completed. 

Are you done? Mark it as complete so you and your team will get credit.

Need more time?  Update your due date and let your team know.

Or cancel it if you no longer need the opportunity.

Thanks, 
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41592&_a=edit
