### ISSUE TITLE
Open Opps System Email <Opportunity overdue -Opportunity creator>

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1691]
As an Open Opps Admin and/or User, I would like to receive the following emails at the following points in the Open Opps process: 

Current Message Name: Task due – 6 months- Task creator
Desired Message Name: Opportunity overdue – Opportunity creator

Message Type: Email

Header Type/Subject Copy: Still working on your opportunity?

Desired Text Copy: 
Hi [Opportunity creator],
We noticed you haven’t marked [opportunity name - link] as completed and wanted to check in to see how it's going.

Are you done? Mark it as completed so you and your team will get credit.

Need more time?  Update your due date and let your team know.

Or you can cancel it, if you no longer need the opportunity.

Thanks,
The Open Opportunities Team

Trigger: Opportunity status hasn't been changed to completed for 6 months after its due date  (estimated completion date).  If no estimated completion date is provided, no email should be sent.

Acceptance Criteria:
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

**Comment by nia-johnson** [comment]
Moving to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41590&_a=edit
