### ISSUE TITLE
Open Opps System Email <Opportunity overdue - Assigned participant>

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1692]
As an Open Opps Admin and/or User, I would like to receive the following emails at the following points in the Open Opps process: 

Current Message Name: Task due – 6 months -Task taker
Desired Message Name: Opportunity overdue – Opportunity taker
Message Type: Email
Header Type/Subject Copy: Still working on your opportunity?
Desired Text Copy: 

Hi [assigned participant name],

We noticed your opportunity [[display opportunity name that links to the opportunity listing on open opps]] isn’t marked as completed. 

Are you done with your task?  If so, let your opportunity creator know so they can mark you as completed and we'll update your profile.

Let the opportunity creator know if you're still working or if you need more time.

Thanks, 
The Open Opportunities Team

Trigger: Opportunity status hasn't been changed to completed for 6 months after its due date  (estimated completion date) and Task completed hasn't been selected by the assigned participant.  If no estimated completion date is provided, no email can be sent.

Acceptance Criteria:
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

**Comment by nia-johnson** [comment]
Moving to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41589&_a=edit
