### ISSUE TITLE
Open Opps System Email <Opportunity - Complete- Applicant>

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1693]
As an Open Opps applicant, I would like to receive the following email at the following point in the Open Opps process: 

Current Message Name: Opportunity - Complete
Desired Message Name: Opportunity - Complete - Applicant
Message Type: Email
Header Type/Subject Copy: Your opportunity is complete - thank you!
Desired Text Copy: 
Hi [[GivenName]],

Congrats! Your have completed your task on Open Opportunities! Click here to review it: [link to task- display task name] . We updated your profile to note your achievement. Thanks for your hard work and we hope you developed some great skills and contacts while completing the task!

Please take a moment to complete this quick survey - your feedback will help us to improve Open Opportunities.

[insert link to applicant survey monkey- Open Opportunities' Opportunity Applicant Survey v.1
https://www.surveymonkey.com/r/D3M8KBR ]

Thanks,
The Open Opportunities Team

Trigger: 
1. (to assigned participants) Opportunity creator clicks 'Task completed' and then from the confirmation modal, opportunity creator clicks 'confirm' 

Acceptance Criteria:
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger: 
1. (to assigned participants) Opportunity creator clicks 'Task completed' and then from the confirmation modal, opportunity creator clicks 'confirm' 

Desired Text Copy: 
Hi [[GivenName]],

Congrats! Your have completed your task on Open Opportunities! Click here to review it: [link to task- display task name] . We updated your profile to note your achievement. Thanks for your hard work and we hope you developed some great skills and contacts while completing the task!

Please take a moment to complete this quick survey - your feedback will help us to improve Open Opportunities.

[insert link to applicant survey monkey- Open Opportunities' Opportunity Applicant Survey v.1
https://www.surveymonkey.com/r/D3M8KBR ]

Thanks,
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
removed second trigger per direction during sprint planning on 2/8. Second trigger was 

2. (to task creator) Task creator clicks 'Complete opportunity'

**Comment by kbwagner** [comment]
Test for Jodie...let me know if you get an email for this.

**Comment by KatMullens-work** [comment]
Added link to Open Opportunities' Opportunity Taker Survey v.1
https://www.surveymonkey.com/r/D3M8KBR

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
03/28/2018 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
03/28/2018- Mdumas - Moving back to development  to change the last word of the first paragraph to be "task" as in AC rather than "opportunity"

**Comment by JodieYoung1** [comment]
Testing is complete

**Comment by LisaLNelson** [comment]
Testing complete.  Moved to ready to deploy.

**Comment by LisaLNelson** [comment]
Approved for closure. LN
