### ISSUE TITLE
Open Opps System Email <Applicants - Interested>

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1694]
As an Open Opps Admin and/or Member, I would like to receive the following emails at the following points in the Open Opps process: 

Current Message Name: Applicants - Interested
Desired Message Name: Applicants - Interested
Message Type: Email
Header Type/Subject Copy: Thanks for your interest in Open Opportunities
Desired Text Copy: 
Hi [[GivenName]],
We received your request to work on [opportunity name - link]. Thanks for your interest in this opportunity – we’re glad you want to help!

During the next few days, we’ll review your profile (and may get in touch with you) to make sure you’re a good fit. If your skills and interests match what we’re looking for, we’ll assign you to the opportunity and send you a confirmation email.

If you’re not selected for this opportunity we'll let you know. Keep checking the site as we frequently add new opportunities.

Thanks,
The Open Opportunities Team

Trigger: Opportunity page > Clicks 'I'm interested'

Acceptance Criteria:
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger: Opportunity page > Clicks 'I'm interested'

Desired Text Copy: 
Hi [[GivenName]],
We received your request to work on [opportunity name - link]. Thanks for your interest in this opportunity – we’re glad you want to help!

During the next few days, we’ll review your profile (and may get in touch with you) to make sure you’re a good fit. If your skills and interests match what we’re looking for, we’ll assign you to the opportunity and send you a confirmation email.

If you’re not selected for this opportunity we'll let you know. Keep checking the site as we frequently add new opportunities.

Thanks,
The Open Opportunities Team

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 This is ready for testing

**Comment by Kibrahacha67** [comment]
4/3/18 LHammond in testing

**Comment by JodieYoung1** [comment]
My name appears under 'Applicants' but I did not receive an email notification after applying for the opportunity.

**Comment by LisaLNelson** [comment]
My name appears under applicants and I did not get an email.  Moving back.

**Comment by Kibrahacha67** [comment]
4/4/18 LHammond in testing

**Comment by KatMullens-work** [comment]
I applied for an opportunity and got the AC email. I applied as a regular user, not using my admin account. This ticket passes testing.

**Comment by LisaLNelson** [comment]
Approved.
