### ISSUE TITLE
Open Opps System Email <Applicants - Assigned>

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1695]
As an Open Opps Admin and/or User, I would like to receive the following emails at the following points in the Open Opps process: 

Current Message Name: Applicants - Assigned
Desired Message Name: Applicants - Assigned
Message Type: Email
Header Type/Subject Copy: You’ve been selected for an opportunity!
Desired Text Copy: 
Hi [[GivenName]],
Great news-you’ve been selected to participate in [opportunity name - link]!

What happens next?
The person who created the opportunity will reach out to you soon to get you started.  In the meantime, read the opportunity details:
http://openopps.digitalgov.gov/tasks/12

Thanks,
The Open Opportunities Team

Trigger: 
Trigger 1: If opportunity is open, after selecting volunteers and clicking the button “Next Steps” we will email participants to notify them of his/her selection or non-selection.

Trigger 2: On an opportunity with volunteers already assigned, a new applicant is selected, plus icon is clicked and a pop-up modal is engaged to ask the user to confirm assigning the new applicant. Upon confirmation the participant is added to the assigned section and an email is sent to the participant to notify him/her of selection.

Acceptance Criteria: 
The desired text, including personalizations/links is emailed to the appropriate user when the Trigger happens.

Trigger: 
Trigger 1: If opportunity is open, after selecting volunteers and clicking the button “Next Steps” we will email participants to notify them of his/her selection or non-selection.

Trigger 2: On an opportunity with volunteers already assigned, a new applicant is selected, plus icon is clicked and a pop-up modal is engaged to ask the user to confirm assigning the new applicant. Upon confirmation the participant is added to the assigned section and an email is sent to the participant to notify him/her of selection.

Desired Text Copy: 
Hi [[GivenName]],
Great news-you’ve been selected to participate in [opportunity name - link]!

What happens next?
The person who created the opportunity will reach out to you soon to get you started.  In the meantime, read the opportunity details:
http://openopps.digitalgov.gov/tasks/12

Thanks,
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Updated triggers (thanks @bmcorum :) !! ) to:

Trigger 1: If opportunity is open, after selecting volunteers and clicking the button “Next Steps” we will email participants to notify them of his/her selection or non-selection.

Trigger 2: On an opportunity with volunteers already assigned, a new applicant is selected, plus icon is clicked and a pop-up modal is engaged to ask the user to confirm assigning the new applicant. Upon confirmation the participant is added to the assigned section and an email is sent to the participant to notify him/her of selection.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-11-18 LHammond in testing

**Comment by KatMullens-work** [comment]
Did not get selection email once I was selected for the task. Test failed.

**Comment by KatMullens-work** [comment]
Passed test. Thanks, team! :)
