### ISSUE TITLE
Open Opps System Email <Discussion - new comment>

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1697]
As a task creator, the desired text, including personalizations/links is emailed to the the TASK CREATOR when the Trigger happens.

Current Message Name: Discussion –new comment
Desired Message Name: Discussion –new comment
Message Type: Email
Header Type/Subject Copy: There's a new comment on "[opportunity name]" 
Desired Text Copy:
 Hi [[GivenName]], 

There's a new comment in your opportunity.  [Name] said:

"comment"

[Take a moment to reply](link/button).

Thanks,
The Open Opportunities Team

Trigger: When a user posts new comment

Acceptance Criteria:
The desired text, including personalizations/links is emailed to the the TASK CREATOR when the Trigger happens.

Trigger: When a user posts new comment

Desired Text Copy:
 Hi [[GivenName]], 
There's a new comment in your opportunity.  [Name] said:

"comment"

[Take a moment to reply](link/button).

Thanks,
The Open Opportunities Team

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
4/3/18 LHammond in testing

**Comment by LisaLNelson** [comment]
Moving to ready to deploy LN

**Comment by LisaLNelson** [comment]
Approval for closure. LN
