### ISSUE TITLE
As a task taker, I want to be able to easily see what step of the process my opportunity is in.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1703]
When a task taker opens an opportunity that they haven't yet applied for, they will see a right rail that includes a progress bar, and a blank assigned participants screen.
Progress Bar:
The progress bar for a task taker will have Assigning, In Progress, and Complete as options.
-as soon as the opportunity is OPEN, the progress bar will light up and it’ll say ‘Assigning’
- Once applicants have been assigned to the task and the task creator has selected next, the status for the task taker will change to "In progress" (1656)
- Once the task taker has completed and closed the task, the status will change to "complete" (1672)

View of applicants:
- once a job is closed and assigned, task taker will no longer see applicants.  Only those assigned to the task.

Task Taker Progress Bar: https://projects.invisionapp.com/d/main#/console/12657410/269952624/preview

Related Ticket:
1120 - Task Creator progress bar
1672 - Task creator complete opportunity
1656 - Task creator assign applicants

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
LHammond 3-5-18 In Testing
