### ISSUE TITLE
Open Opps System Email <Standard Footer>

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1704]
As an Open Opps User, I would like to receive the following email footer displayed after email content:

**Open Opportunities Email Footer:**
Every email will close with:
Thanks,
The Open Opportunities Team

**The email footer that displays after the email content will read:**
You received this email because you signed up for Open Opportunities.

Have questions or comments?  Check out our help center  <insert help link> or email us at OpenOpps@usajobs.gov.

To make sure you get Open Opportunities emails to your inbox (and not your spam) add 'OpenOpps@usajobs.gov to your address book.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
03/28/2018 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
03/28/2018 -Mdumas - moving ticket back to development.  Will ask Jodie Y to update AC for removing "a" from footer text.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
03/29/2018 - Mdumas - Testing has been completed.  AC should be updated to remove "at"on the Have questions line and to update the address book address to the noreply one.

**Comment by LisaLNelson** [comment]
Complete. Moved to ready to deploy.

**Comment by LisaLNelson** [comment]
Approved for closure LN
