### ISSUE TITLE
Open Opps System Email <Opportunity - Complete - Task Creator>

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1706]
As an Open Opps task creator, I would like to receive the following email at the following point in the Open Opps process. This ticket creates a message to the task creator that is a copy of the message sent to the task taker.

Current Message Name: Opportunity - Complete
Desired Message Name: Opportunity - Complete - Task Creator
Message Type: Email
Header Type/Subject Copy: Your Open Opportunity is Complete - Thank You!
Desired Text Copy:

Dear [[Task Creator Name]]:
Congratulations on the completion of [opportunity title & link]. We have also emailed your Open Opportunities participants today to let them know that your Open Opportunity was marked as completed and to ask them to complete a survey about their experience.

We'd also love to know about your experiences with Open Opportunities. Please go here and complete this short survey so we can continue to improve our service to you: < link to: https://www.surveymonkey.com/r/D39SH3M>

Thanks for leveraging Open Opportunities to help achieve your mission while developing the federal workforce!

Thanks,
The Open Opportunities Team

Acceptance Criteria:

When a task creator marks an opportunity as complete, their participants are emailed their notification and the notification below is emailed to the task creator:

Dear [[Task Creator Name]]:
Congratulations on the completion of [opportunity title & link]. We have also emailed your Open Opportunities participants today to let them know that your Open Opportunity was marked as completed and to ask them to complete a survey about their experience.

We'd also love to know about your experiences with Open Opportunities. Please go here and complete this short survey so we can continue to improve our service to you: < link to: https://www.surveymonkey.com/r/D39SH3M>

Thanks for leveraging Open Opportunities to help achieve your mission while developing the federal workforce!

Thanks,
The Open Opportunities Team

**Comment by KatMullens-work** [comment]
Link to Airtable with updated emails from Min and Deb: https://airtable.com/tblzvuEsjxmNuyr3g/viw2axasCD2yUZHJv

**Comment by KatMullens-work** [comment]
Added link to survey monkey survey Open Opportunities' Opportunity Creator Survey v.1
https://www.surveymonkey.com/r/D39SH3M

**Comment by KatMullens-work** [comment]
After discussions with @bmcorum , we have modified this ticket. Now, when a task creator closes a task, the participants get their notification email and the following email will go to the task creator: 

Dear [[Task Creator Name]]:
Congratulations on the completion of [opportunity title & link]. We have also emailed your Open Opportunities participants today to let them know that your Open Opportunity was marked as completed and to ask them to complete a survey about their experience.

Thanks for leveraging Open Opportunities to help achieve your mission while developing the federal workforce!

Thanks,
The Open Opportunities Team

**Acceptance Criteria:**

When a task creator marks an opportunity as complete, their participants are emailed their notification and the notification below is emailed to the task creator:

Dear [[Task Creator Name]]:
Congratulations on the completion of [opportunity title & link]. We have also emailed your Open Opportunities participants today to let them know that your Open Opportunity was marked as completed and to ask them to complete a survey about their experience.

Thanks for leveraging Open Opportunities to help achieve your mission while developing the federal workforce!

Thanks,
The Open Opportunities Team

**Comment by Kibrahacha67** [comment]
2/28/18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
4/3/18 LHammond in testing

**Comment by KatMullens-work** [comment]
passed! Thank you!!
