### ISSUE TITLE
Standardization of Skill and Interest Lists

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1711]
As a user, I want to have a single list of interests and a single list of skills to choose from when I am creating my account. If my interest/skill is not present, I want to be able to add it. 

example: more than one listing for "usability test"
![image](https://user-images.githubusercontent.com/25315047/36054773-29988550-0dc6-11e8-9a5a-27549a171813.png)

example: should still be able to add new interest or skill
![image](https://user-images.githubusercontent.com/25315047/36054842-85ac6172-0dc6-11e8-8ac5-d4a1dbad5a17.png)

example: more than one listing for "travel"
![image](https://user-images.githubusercontent.com/25315047/36054866-9c89369a-0dc6-11e8-87d9-9cb9f9b86601.png)

**Comment by bmcorum** [comment]
@KatMullens-work, @LisaLNelson, @minchung12

So here we have a couple issues.

**Easiest to solve**
1. Travel, travel, trAveL should all be treated as Travel (i.e. we ignore case)
2. There is always the option to "click to create a new tag" (We will need to double check against database for matching/duplicate record before actually creating the new record)

**Harder to solve**
1. Travel, Traveller, I love to travel (these are different yet mean the same thing)
2. Misspellings

**Comment by kbwagner** [comment]
On hold until we implement Skills Engine

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41572&_a=edit
