### ISSUE TITLE
Skills and Interests Should be Displayed in Separate Boxes on Open Opps Profile

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1712]
As an open opps users, my skills and interests in my profile should be displayed in separate boxes in the completed profile; presently they display in a single, combined box.

example of present display in my open opps profile: 

![image](https://user-images.githubusercontent.com/25315047/36054938-203f4a4c-0dc7-11e8-8b49-28291dc12faf.png)

**Comment by kbwagner** [comment]
Closing - duplicate of 1561.  Copying notes from this ticket into 1561.
