### ISSUE TITLE
As an open opportunities user, I want to have consistent validation applied throughout the system.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1715]
Apply the USAJOBS design system validation to all parts of the open opportunities system.

**Comment by margaretdumas** [comment]
In testing - Mdumas

**Comment by margaretdumas** [comment]
02/23/2018 - Pending code push to UAT for testing - Mdumas

**Comment by margaretdumas** [comment]
02/26/2018 - Mdumas - Does not meet validation rules.  
- Able to sign in without entering correct confirm email.
- Able to sign in without accepting agreement
- Headline allows for more than 60 characters

**Comment by margaretdumas** [comment]
Mdumas - 2/26/2018- Correction, does not stop at 100 characters.

**Comment by margaretdumas** [comment]
03/5/2018 - Mdumas - In Retesting

**Comment by margaretdumas** [comment]
03/5/2018 - Mdumas - Sign in page missing validation

**Comment by margaretdumas** [comment]
03/05/2018 - Mdumas - Issues ...Moving back to development
- Sign in page missing validation when password is missing
- Required fields are not marked as per design system. Create an opportunity page

**Comment by margaretdumas** [comment]
Mdumas - Testing complete
