### ISSUE TITLE
As an open opportunities task taker, I would like to get an email to notify me if the opportunity I am working on has been canceled.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1716]
Subject of Email: Open Opportunity Canceled

Email Content: 

“Hello [name]

The opportunity you were working on, [name of opportunity], has been canceled. Please contact the person who created the opportunity if you have any questions.

Even though this opportunity is canceled, we frequently update the site with new opportunities. 

<See other opportunities>”

Trigger:
Who Gets the email: 
- if the opportunity status is Open, everyone who has applied or been assigned will get the email.
- If the opportunity status is "in Progress", only Assigned participants will get the email.

Related Tickets:
- 1430 - Cancel Opportunity

**Comment by jhanson12** [comment]
What should the Subject line be?  Maybe 'Opportunity has been cancelled'?  Also, I noticed some emails say "Hi" and others say "Hello" and some "Dear"...can we pick one for consistency?  At least use only "Hi" or "Hello"?

**Comment by kbwagner** [comment]
@jhanson12 - I emailed Debbie on the salutation since she's our content and consistency guru.  Good catch.  On the subject, how about "Open Opportunity Canceled" (we are using one "l" in canceled as a consistent decision too).  Thanks!

**Comment by Kibrahacha67** [comment]
3-30-18 LHammond in testing

**Comment by kbwagner** [comment]
4/3/18 - Canceled a job where one person was an applicant, one had applied, and the job status was "In progress".  Only the person who was assigned received the email.
- Tested second job where only had applicants and status was "open".  Canceled and the applicant received the email.
@LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
Reviewed and moved to ready for deployment
