### ISSUE TITLE
As an Open Opps user, I'd like to know what agency and bureau a requestor works for

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1719]
As an Open Opps user, I'd like to know what agency and bureau a requestor is working for as well as the career area that the opportunity resides in to help me better choose tasks that interest me and serve my career goals. At present, it's only the person's name and photo and not all opportunities include identifying information. Example attached:
![image](https://user-images.githubusercontent.com/25315047/36123504-e129b8d2-101a-11e8-9f92-47a6e5476386.png)

**Comment by minchung12** [comment]
@KatMullens-work You can click on the person's name to view their profile

**Comment by KatMullens-work** [comment]
Not all of our users have Agencies associated with their accounts:
user_id

name

username

title

agency

1

initialize@midascrowd.com



2

Dave Best

david.best@gsa.gov

Innovation Specialist

3

Sarah Allen

sarah.allen@gsa.gov

18F,  Midas / Open Opportunities

General Services Administration (GSA)

4

Gray Brooks

richard.g.brooks@gsa.gov

Sr. API Strategist

5

Jamie Albrecht

jamie.l.albrecht@gmail.com



6

Brandt Heisey

brandt.heisey@gmail.com



7

Aaron Snow - XI

aaron.snow@gsa.gov

Acting Executive Director (Deputy Assoc. Administrator), 18F

General Services Administration (GSA)

8

Amos Stone

amos@gsa.gov

General Services Administration (GSA)

10

Read Holman

read.holman@gmail.com



11

Diego Lapiduz

diego.lapiduz@gsa.gov



12

kristin nienhuis

kristin@dahlabs.com



13

Michelle Hood

michelle.m.hood@gmail.com



14

Natalie Shaw

natalie.shaw@digital.cabinet-office.gov.uk



15

Gregory Boone - XIS

gregory.boone@gsa.gov

Innovation Specialist



21

Kristin Nienhuis - XIS

kristin.nienhuis@gsa.gov




It looks like it was made a required field about 2/3 of the way through the registrations.

kat

**Comment by kbwagner** [comment]
This is part of Min's FAI design
