### ISSUE TITLE
As an open opportunities user, I would like for the login page to have consistent branding and language. 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1724]
[1724.docx](https://github.com/openopps/openopps-platform/files/1721588/1724.docx)
As an open opportunities user, I would like for the login page to have consistent branding and language. 

Acceptance Criteria: 
Apply the design system to the login page, forgot password page, and create account page.  In addition, the following changes should be made: 
Login page:
-	Change from modal to page
-	Change header from Login or Register to “Sign in”
-	Change all labels to be sentence case including “Official government email address”
-	Change the language from “Need an account?  Sign up now” to “Don’t have an Open Opportunities account?” Instead of a link, there will now be a “Create a new account” button. 
Forgot Password:
-	Change from a modal to page
-	Remove page heading of Login or Register
-	Change title of the page from Reset Your Password to Forgot password
-	Change the field label of email to be consistent “Official government email address”
-	Change the Cancel and Reset buttons to be a “Send email” button
Create Account:
-	Change form a modal to a page
-	Remove the page heading of Login or Register
-	Change title of the Page to “Create account”
-	Make all field labels sentence case
-	Add fields for Agency and Location
-	The buttons on the page will now be Cancel and Create account
-	Cancel takes the user back to the sign in page
-	Create account signs the user in and takes them to the landing page

**Comment by Kibrahacha67** [comment]
All tests pass except for:
•	Remove the “I am a federal employee” checkbox FAIL.

**Comment by jhanson12** [comment]
Please note that the "Remove the 'I am a federal employee" checkbox required has been removed.  It is a required field.

**Comment by Kibrahacha67** [comment]
All tests pass LHammond 2/22/18
