### ISSUE TITLE
Change Open Opportunities Timeout to 15 Minutes

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1733]
As a user, the Open Opportunities site should time out after 15 minutes to help keep my information more secure.

I would also like to get a user warning of the impending session termination before it happens.

**Comment by ultrasaurus** [comment]
What is the motivation for this change?  In two years of working with Open Opportunities users in government, including leading substantial user research projects, I never heard this from users.  I would guess this is coming from a security review -- if so, it would be very helpful to frame the actual need that is driving this.

**Comment by bmcorum** [comment]
@ultrasaurus this is an OPM security policy requirement.

**Comment by Kibrahacha67** [comment]
2-28-18 LHammond - in Testing

**Comment by kbwagner** [comment]
@LisaLNelson were you able to get this succesfully to work? Min and I both have the issue where the timeout message flashes very fast.  so it times out but you don't have time to read the message as to why.

**Comment by Kibrahacha67** [comment]
I had it work in chrome, ie, edge and fire fox.  I never went away quickly for me it stayed open until I clicked what I wanted to do.  I have had it work this afternoon as I was testing.
