### ISSUE TITLE
as a developer, how do I run migrate:up with different config?

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1737]
I don't see how our database config in `/db/index.js` is expected to be used by migrate:up for running on dev/staging/prod servers.  

Running on remote dev server, the errors below illustrate that, as expected, the migrate tool uses local db config:
```
npm run migrate:up

> openopps-platform@0.15.0 migrate:up /home/openopps/app
> node ./node_modules/db-migrate/bin/db-migrate up

assert.js:669
assert.ifError = function ifError(err) { if (err) throw err; };
                                                  ^

Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

The [db-migrate module](https://www.npmjs.com/package/db-migrate) which we are using offers reasonable [config options](https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/) that we could consider storing  in the same formate

**Comment by bmcorum** [comment]
https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/#configuration

Specifically,

You can pass the -e or --env option to db-migrate to select the environment you want to run migrations against. The --config option can be used to specify the path to your database.json file if it's not in the current working directory.

db-migrate up --config config/database.json -e prod

The above will run all migrations that haven't yet been run in the prod environment, grabbing the settings from config/database.json.

**Comment by kbwagner** [comment]
@ultrasaurus - Brice has provided comments.  Can this be closed.

**Comment by ultrasaurus** [comment]
In coversation with @bmcorum came up with following plan

- Make sure we have consistent configuration where DATABASE_URL is always used first, with fallback to database.json (consider moving to `config/database.json` with .db-migraterc config file)
- update CONFIG.md with changes
