### ISSUE TITLE
when signing up as a new user, I should not see an error before I have typed in my email

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1741]
1. From the home page, click "Sign In"
2. Click "Create new account"
3. Type name
4. hit TAB

Result:
![image](https://user-images.githubusercontent.com/41906/36358250-1e0d6628-14c0-11e8-9163-94618e3c622b.png)

**Comment by bmcorum** [comment]
@ultrasaurus, we have a ticket that covers this and include acceptance criteria that would handle this. #1715

Closing issue.
