### ISSUE TITLE
as a developer, my local dev dependencies should match deployments 

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1742]
package-lock.json should be checked in to the source repository, currently prevented when it was added to .gitignore file in [recent commit](https://github.com/openopps/openopps-platform/commit/7ae206ff879defcd2f0920b7fe3cdf79b67db49c)

For context, see [npm docs](https://docs.npmjs.com/files/package-lock.json):

> It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

> This file is intended to be committed into source repositories.

**Comment by ultrasaurus** [comment]
comment from @bmcorum via https://github.com/openopps/openopps-platform/pull/1743 I understand the usefulness of the package-lock.json, however this little thing can cause a merging nightmare. I removed it from source control recently and added it to the git ignore file. I would hope that for deployments we would run a final install, build and run locally on the machine that will initiate the deploy thus building the newest package-lock.json. Thoughts? Or experience in dealing with the package-lock.json and possible merge conflicts.

I think it is helpful for developers to be aware that their local environment differs in some way from the production environment (and other developers on the team as well).  Usually, I notice that package-lock.json has changed in some minor way, but before I commit, I'll `git checkout package-lock.json`

It is notable that npm has waffled a bit on its definition of how it generates and uses `package-lock.json`.  I just read up on the details in https://github.com/npm/npm/issues/17979 and https://github.com/npm/npm/issues/18286 

The current behavior *should* be:

> The lock file is used by default. It's just that if you modify dependencies in package.json those changes will get installed instead, and the lock file will be updated. Assuming you commit the lock file you should notice it changing and can revert those changes if necessary.  
-- https://github.com/npm/npm/issues/18286#issuecomment-365233383

We could also consider using [yarn](https://yarnpkg.com/en/), which has had a lock file feature in use much longer and is very reliable.  Then we could .gitignore `package-lock.json` and then check in `yarn.lock` -- then ci can install with `yarn install --frozen-lockfile` which ensures that we're not getting some random new version of a dependency which can (rarely) produce a hard-to-track down error.

Developers can choose to use `yarn install` or `yarn install --frozen-lockfile` depending on whether they want to track changes in dependencies.  Anyone who checks in `yarn.lock` is taking responsibility for having tested the app and reviewed the updated dependencies to watch out for potential incompatibilities (and usually I also like to check in the lock file in its own commit to make it easy to see whether a change in behavior is due to an updated dependency or a code change.

**Comment by kbwagner** [comment]
Per Brice, this is done.
