### ISSUE TITLE
as a developer, I would like separate install and build

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1744]
npm install is meant for installing dependencies, by including the app build step in the post install, we remove a typical separation of concerns that leads to a few challenges:

1. debugging npm install is challenging, since errors are often obscured by npm
2. deploying is slow -- when using docker, each RUN command creates a new layer. Running 'npm install' needs to download a lot of modules, and ideally all of the npm module dependencies could be fetched and installed *only* when we actually change the package.json (references: [efficient docker](https://medium.com/arthur-design-engineering/efficient-docker-with-the-new-yarn-package-manager-native-packages-like-bcrypt-for-node-js-apps-5b36c9930e2d), [optimizing caching](https://www.aptible.com/documentation/enclave/tutorials/faq/dockerfile-caching/npm-dockerfile-caching.html))

**Comment by kbwagner** [comment]
Per Brice, this is done.
