### ISSUE TITLE
As a task taker, I want to be able to cancel my application without having to contact the administrator.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1751]
Acceptance Criteria:
As a task taker, once I have applied I will get a message under the progress bar that reads, "Thanks for applying We'll email you with next steps.  You can also check your profile for status updates"  
- At the bottom of this message there will be a link that reads "Cancel your application" link.
- When the link is selected, a confirmation modal should display that reads, "Your application has been withdrawn.
- Thanks for applying would change to the "Apply" button
- The task taker profile will show as if the applicant had never applied.

Prototype: https://projects.invisionapp.com/d/main#/console/12657410/269952623/preview

Related Ticket: 1847 - email confirmation of application cancellation.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
3-15-18 LHammond In Testing

**Comment by kbwagner** [comment]
3/20/18 - Katrina tested in Chrome.  Looks good.  @LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
Tested. Good to go.

**Comment by LisaLNelson** [comment]
Approved for closure. LN
