### ISSUE TITLE
As an administrator, I want the ability to have additional search filters not available to other users.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1753]
If a user is logged on as an administrator, the search filters displayed should be:
Draft
Submitted
Open
Not Open
In progress
Completed
Canceled

Prototype: https://projects.invisionapp.com/d/main#/console/12657410/270464538/preview

Related tickets: 
1754 - non admin search filters

**Comment by Kibrahacha67** [comment]
3-6-18 LHammond - In Testing
