### ISSUE TITLE
As a non administrator, I want the search filters I see to be useful in helping me find an opportunity.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1754]
For an open opportunities user who is not an administrator, the search filters displayed will be:
Open
In Progress
Completed
Canceled

"Open" will be defaulted as checked on.

Prototype: https://projects.invisionapp.com/d/main#/console/12657410/265272109/preview

Related Ticket: 
1753 - Admin search filters

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
LHammond 3-5-18 In Testing
