### ISSUE TITLE
As a task taker, I want to have a clear way to apply for an open opportunity.  

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1755]
As a task taker, once I have viewed an opportunity:
- The existing "I'm interested" will now be "Apply"
- When Apply is selected, the messsage "Do you want to participate?" displays with the checklist of questions: https://projects.invisionapp.com/d/main#/console/12657410/275050822/preview
- At the bottom of the message, a button will read," Yes, submit my name"
- Once Yes is selected, a "Thanks for applying" message displays.  The message reads, "We'll email you with next steps.  You can also check your profile for status updates."  https://projects.invisionapp.com/d/main#/console/12657410/269952623/preview
- Cancel is handled by ticket 1751

Prototype:
https://projects.invisionapp.com/d/main#/console/12657410/269952624/preview

**Comment by kbwagner** [comment]
@bmcorum @LisaLNelson this one is still in the backlog but has been done.  we can close or move it to ready to deploy.  Tested 3/19/18

**Comment by LisaLNelson** [comment]
Sprint 1.4
