### ISSUE TITLE
As a task taker, I would like to be able to know in Open Opportunities when I have been assigned to a task.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1756]
Congrats your assigned: 
When a task taker enter has been assigned to an open opportunity, they will now have a message on their task taker opportunity view that reads, "Congratulations, you're assigned! Let the opportunity creator know when you've completed your task." 
 https://projects.invisionapp.com/d/main#/console/12657410/269952622/preview
- This message is also accessible from a link in the applicants assigned email (1695)

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
Lhammond 3-5-18 In Testing
