### ISSUE TITLE
Cannot get to site in IE

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#1769]
IE does not load site.

**Comment by margaretdumas** [comment]
03/01/2018 -  Mdumas - IE pages are not displayed properly.  CSS issues on pages.
- Tasks

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67, you should be able to load the site in IE now.

**Comment by Kibrahacha67** [comment]
LHammond - Tested and passed 3-5-18
