### ISSUE TITLE
Reset Password Page Does not Have Padding

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#1792]
There is no padding on the reset password page causing the text to be right up against the page left border.

Steps to reproduce:
1.  Navigate to site
2.  Select "Reset password
3.  Sign into email account
4.  Open reset password email

Results:  Text, text boxes and button are all against left edge of page.

**Comment by KatMullens-work** [comment]
I don't see an issue in production so this must be fixed.
