### ISSUE TITLE
Correct Error Styling Has Not Been Added to Password Reset Page

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#1794]
02/28/2018 - Mdumas - 
Error styling has not been added to the Password Reset Page. 
- Vertical line does not display on page.  
- Confirm password displays two messages.
- As soon as I start typing the confirm message (You must confirm your password and Your password does not match the password entered above both display)

**Comment by jhanson12** [comment]
Note: Current Open Opps and all new confirm password fields display two messages.

**Comment by margaretdumas** [comment]
03/02/2018 - Mdumas - Passed Testing
