### ISSUE TITLE
As an open opportunities user, I would like the landing page text to match the screen shot.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1800]
1) On the landing page, the text on the page doesn't match the new screen shot (ticket 1680)

Current Text:
- Browse opportunities on the site to find the one that is right for you.
- Then just click "Participate" to get started.
- Post a discussion topic if you have questions.

New Text: 
- Browse opportunities on the site to find the one that is right for you.
- Then just click "Apply" to get started.
- Post a discussion topic if you have questions.

2) Also, please revisit the mock to ensure the button is moved to the right place: https://projects.invisionapp.com/d/main#/console/12657410/268909834/preview

3) Change both red buttons to say "Find opportunities" so they are consistent.

**Comment by Kibrahacha67** [comment]
3-13-18 LHammond in Testing
Completed Testing

**Comment by margaretdumas** [comment]
Mdumas - I accidently moved this one to ready while dragging over another ticket.

**Comment by kbwagner** [comment]
3/18/18 - Katrina tested in Chrome and mobile Safari.  Looks good.
@LisaLNelson - ready for you to test.

**Comment by LisaLNelson** [comment]
Good to go

**Comment by LisaLNelson** [comment]
Approved for closure. LN

**Comment by LisaLNelson** [comment]
Approved for closure. LN
