### ISSUE TITLE
As an open opportunities Administrator, I want to be able to use the back button on my browser to return to the opportunities listings

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1803]
Browser: Chrome
Database: UAT

Steps to reproduce:
1) Log in as an administrator
2) Click on your name and then Administration
3) Click the back button
- The administrator stays on the Admin section rather than returning to the previous page

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
LHammond 3-2-18 In Testing
LHammond 3-2-18 Test completed Passed

**Comment by LisaLNelson** [comment]
This does not send me back to the Opportunities listing.  It sends me to the landing page. Lisa

**Comment by kbwagner** [comment]
@LisaLNelson - great it's in ready to review status so looks like it's been fixed.  Since you tested it you can move to ready to deploy.
