### ISSUE TITLE
As an agency admin, if I duplicate a opportunity, the owner of the new opportunity is still the owner of the old task.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#1809]

**Comment by LisaLNelson** [comment]
Hmmm.  I duplicated an opportunity that was not mine and it put me on as the task owner.
Originally it was  https://openopps.uat.usajobs.gov/tasks/597 (Amy Gay was the task creator)  and this is after it was copied https://openopps.uat.usajobs.gov/tasks/648 (I removed the word copy to test editing).

**Comment by bmcorum** [comment]
@LisaLNelson, I believe that would be the correct functionality. If you duplicate should you not become the owner?

**Comment by bmcorum** [comment]
**Confirmed**

It affect any user that is not an Administrator. Only administrators would be able to copy an opportunity. Fixing now.

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
3-6-18 - LHammond In Testing
