### ISSUE TITLE
As an open opportunities user, I want to remain on the opportunity page when I am requested to log in.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1823]
Browser: Chrome
Environment: UAT

Steps to reproduce:
1) go to UAT as a not signed in user
2) Click on Browse Opportunities
3) Open an opportunity
3) Select Apply
4) Sign in page displays
5) Enter sign in information
- User is taken to the signed in landing page instead of the task apply page.  They have to search again for the opportunity and then select sign in again.

**Comment by kbwagner** [comment]
@bmcorum - this issue is fixed without ever making it on the sprint log.  Should i close it or do you want to move it to testing?

**Comment by LisaLNelson** [comment]
Sprint 1.4
