### ISSUE TITLE
As an administrator, I should only be able to action against submitted opportunities.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1830]
Browser: Chrome
Environment: UAT

Steps to reproduce:
1) Administration
2) Tasks 
Issue: Only submitted opportunities should have ‘Actions’ section

Invision Mock: https://projects.invisionapp.com/d/main#/console/12657410/269124531/preview

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
3-6-18 LHammond in testing
