### ISSUE TITLE
Admin - Update confirmation modal to meet design system standards

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1843]
As an Open Opportunities administrator, I want to the admin site to meet design system standards for confirmation modals.

Steps to Reproduce:
1) Navigate to admin --> tasks
2) Click on the red X in the action column
- The modal to confirm deletion does not match the design system modal style. The confirmation modal for the check mark does match.

Entered from bug bash 3/6/18

**Comment by kbwagner** [comment]
6/4/18 - KWagner - Tested and still an issue.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-18 LHammond in testing

**Comment by kbwagner** [comment]
6/20/18 - KWagner tested in Chrome and mobile Safari
Ready for final review

@Kibrahacha67 - we double checked with Min and the generic modal is correct (for now...may change down the road). Thanks!

**Comment by tlorrison** [comment]
Approved
