### ISSUE TITLE
As an administrator, I want the People search to be weighted to better allow searching on multiple fields.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1844]
People search searches on name, title, agency, and location.  Upgrade to work better for multiple search fields.  Determine appropriate weighting if multiple search options are entered (and search vs or?)

Entered per 3/6/18 bug bash

**Comment by bmcorum** [comment]
@kbwagner I not sure this is a bug as much as it is an enhancement to current funtionality. The search works we just want to adjust how we rank/return matches.

**Comment by kbwagner** [comment]
People search now uses elastic search.  Closing.
