### ISSUE TITLE
As an Open opportunities creator, I want to receive a confirmation when an applicant who has applied to my opportunity withdraws their application.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1847]
Email Trigger: When someone who is a an applicant (not assigned participant) on an opportunity selects the "Cancel Application" link, the email above will be sent to the Opportunity Creator's email.

Subject: Application withdrawn

Email Content:
Dear [task creator],

One of the participants, [participant name], for your Open Opportunity, <a href="url">[task title]</a>, has decided to withdraw his or her application.

Thanks,
The Open Opportunities Team

Related Ticket: 1751 - Task taker cancel application

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
03/15/2018 - Mdumas - In Testing....

**Comment by margaretdumas** [comment]
03/15/2018 - Mdumas - Email verbiage is good.  There is a small issue in the yahoo email where the text wrapping isn't handled that great.  Example:  Open is cut off right after the "O'.

**Comment by margaretdumas** [comment]
03/16/2018 -mdumas - Testing completed

**Comment by LisaLNelson** [comment]
Tested. Good to go.

**Comment by LisaLNelson** [comment]
approved for closure. LN
