### ISSUE TITLE
Change "Task" to "Opportunity"

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1848]
Example: Assigned participant link says "Task completed" instead of "Opportunity completed".  Look throughout the site for other references to task

![image](https://user-images.githubusercontent.com/18709918/71001515-70ab6a80-20ab-11ea-83e6-1c787927904f.png)

From the 3/6/18 bug bash.

**Comment by Piglady64** [comment]
Change from Task Completed to Completed.
