### ISSUE TITLE
Require a federal email address in order to create a new account in the system.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1849]
User Story: As an Open Opportunities user, I should be required to enter a federal email address in order to create a new account in the system.

Acceptance Criteria: 
Only users with a federal email address should be allowed to create an account
- determine how to account for all federal email addresses (i.e. .gov, .mil, etc.)
- error message for failure should say more than "Registration failed".  "You must use a government email account for this system."  New messaging should read, "The email address provided is not a valid government email address or is already in use."

### Update account creation page
- Remove password and confirm password fields
- Add additional email address validation to include "You must use a government email account for this system"
- Update the new account email to include a complete registration link

### Complete Registration Page
- Form contains a password and confirm password
- Top of form reads "Please set a password to complete your account registration."
- Button at bottom reads "Complete registration"

At this time, no changes will be made for existing accounts that do not have a federal email address.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-6-18 LHammond in testing

**Comment by Kibrahacha67** [comment]
6-7-18 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67, oops! Looks like I forgot to hide the error message after your first failed attempt.

**Comment by Kibrahacha67** [comment]
6-7-18 LHammond in testing

**Comment by kbwagner** [comment]
@Kibrahacha67 - I am able to test the error messaging on this one...but how can I get the email for a new user that is a .gov since I won't be able to access the emails on any fake account.  Or, can you attach that email to this as an artifact?

**Comment by Kibrahacha67** [comment]
@kbwagner - i'm checking into this one with Brice to see if we can pull the request from the server and add it as a artifact.

**Comment by Kibrahacha67** [comment]
@kbwagner - Below is a screen shot of the email from me creating a government email account.  please let me knwo if that is good.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c593bb28-4ac1-466d-9f52-2cb6c29cda56)

**Comment by Kibrahacha67** [comment]
@kbwagner - to duplicate this test, go into uat and sign in your government email.  go to profile, and edit your gov email and place hold on the last part of the address and save.  now you can go out and create a new account with your gov email.  once you are done with the test.  change the email account on your new record to hold.  log in with a admin account and change your original email (delete the hold) and you are back to normal with the test complete...let me know if you have questions.

**Comment by kbwagner** [comment]
6/12/18 - KWagner tested in Chrome.  
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved.
