### ISSUE TITLE
Don't allow past dates for estimated completion date

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1850]
Who: Opportunity creators
What: Don't allow past dates to be entered as estimated completion date
Why: Because it doesn't make sense

Acceptance Criteria:
- For Create or Edit an opportunity – Estimated completion date can be in the past. Should only be able to save a date of today or the future.
- make month only accept 2 digits and day only accept 2 and year only 4

From 3/6/18 bug bash. and 5/10/18 bug bash

**Comment by jhanson12** [comment]
Ready for testing @Kibrahacha67

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond in testing

**Comment by kbwagner** [comment]
1/6/2020 - KWagner tested in Test/Chrome
Ready for final review.
