### ISSUE TITLE
Photo upload: Issues with upload process

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1852]
Issue: Click on “Upload” from edit profile, tried a .jpg or a .png and nothing appears to happen and no indication of success.  Photo does actually appear once the page is refreshed.  
From 1625: Picture upload to profile goes into perpetual upload mode (see image)  Pic uploaded but never got success from the application.  Did open it in another browser and pic was there.
From 1545: When I upload an image, I can't see it until I refresh the page.

Steps to reproduce:
1. Click on your name, then "Profile"
2. Click "Edit Profile" link on the top right corner
3. Click the camera to upload a photo
4. Watch the network requests
5. Choose a photo
6. Note the progress bar display, but the photo is not displayed
7. Note the network request shows the photo is uploaded and retrieved, yet it is not displayed (perhaps something is wrong with the api?)
8. Manually refresh the page (Cmd + R)
9. Note only the small profile image on top of the right corner is changed
10. Manually refresh the page again (Cmd + R)
11. Note the big profile picture is changed

Resolution: Photo should automatically appear once uploaded.  Should not require a page refresh.

**Comment by kbwagner** [comment]
Per March 2018 backlog review, merging 1627 and 1625 into this ticket and closing the others.

**Comment by kbwagner** [comment]
6/4/18 -KWagner - tested in UAT - still an issue.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-19-18 LHammond in testing
Testing completed in ie, edge, chrome and safari, moving to review.

**Comment by kbwagner** [comment]
@bmcorum - probably not related but when I try to upload a photo from my phone (iPhone/Safari), I select to either take a photo or use one from my photo library...every time the photo is turned to the left and I am unable to rotate it.  Is that something we can control?  Anything uploaded from my desktop works fine. (if we can control it I can create a new ticket - just wondering)

**Comment by kbwagner** [comment]
6/20/18 - KWagner tested in Chrome and mobile, Safari. Issue in this particular ticket is resolved.

**Comment by tlorrison** [comment]
Tested in Chrome, had to refresh to see my uploaded photo

**Comment by tlorrison** [comment]
approved
