### ISSUE TITLE
Bug: Opportunity create date and target date display yesterday's date.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1854]
Updated date on profile --> Created displays as yesterday's date.
Target date on opportunity also displays yesterday's date.

- Brice indicated the database may be using a different time zone.  All dates should be current date of the person who entered the opportunity or EST.

From 3/6/18 bug bash

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
3-15-18 LHammond In Testing

**Comment by kbwagner** [comment]
3/19/18 - Katrina Tested in Chrome.  All ok.
@LisaLNelson - Ready for your review

**Comment by LisaLNelson** [comment]
Tested. Ready to go.

**Comment by LisaLNelson** [comment]
Approved for closure. LN
