### ISSUE TITLE
As an opportunity creator, I only want to see the posted date displayed on my opportunity once is has been approved.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1857]
Who: Opportunity Creators
What: Don't display posted date field until posted
Why: To avoid confusion

Acceptance Criteria: 
Once an opportunity is saved and in Submitted status, the "posted by name mm/dd/yyyy" under the creator photo displays as -/-/- instead of displaying the date.  
- Current functionality is that this would display only once posted.  Hide the -/-/- until posted to avoid confusion

![image](https://user-images.githubusercontent.com/18709918/37113428-5a1df9d8-2213-11e8-9626-f0cc0686d282.png)

Entered from 3/6/18 bug bash (Michelle Earley)

**Comment by kbwagner** [comment]
Tested 3/20/18 - still an issue.

**Comment by raywilliams** [comment]
![image](https://user-images.githubusercontent.com/340340/71625310-19ca8880-2bb5-11ea-883a-d627a753eab7.png)
The design has changed slightly since this ticket was written. I will hide "Posted on -/-/-".

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/2/20 - Kwagner tested in Chrome/Test
Ready for final review
