### ISSUE TITLE
Bug: Mobile - Unable to create account

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1858]
Steps to reproduce: 
1) clicked Create new account and it flashed up and took me right back to sign in.  
- Happened over and over.  
- Mobile users on Chrome and Safari had the same issue.

Entered from 3/6/18 bug bash.

**Comment by jhanson12** [comment]
Margaret and I are unable to reproduce this issue.  Katrina is retesting.

**Comment by kbwagner** [comment]
Appears to be resolved by all testers.  Closing
