### ISSUE TITLE
Bug: Scroll to top on error messages - Create Account Page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1860]
Issue: On the Create account page, if the user error is at the top of the page the focus is not taken to the top so they don't see the error.

Steps to Reproduce: 
1) Enter an existing email address on the create account page and click Create account
- the screen position did not change. I had to scroll up to see the error message. It would be helpful to repoint the screen to the error message.

Entered 3/6/18 bug bash (Michelle)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-18 LHammond in testing
Testing completed in ie, chrome and edge.  Moving to review.

**Comment by kbwagner** [comment]
6/20/18 - Kwagner tested in Chrome and mobile Safari
Ready for final review.

**Comment by tlorrison** [comment]
approved
