### ISSUE TITLE
Bug: Number of people in create/edit does not match what is posted in opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1861]
Steps to recreate: 
1) Create/Edit an opportunity.  For How many people are needed, select "1 Person"
2) Post the job

Number of people in edit 
![image](https://user-images.githubusercontent.com/18709918/37114426-53276bca-2216-11e8-975e-1791f44df16f.png)

 Does not match was is displayed in announcement 
![image](https://user-images.githubusercontent.com/18709918/37114450-6162a39e-2216-11e8-8f03-ef8c22d7fa07.png)

From Bug Bash 3/6/18 (John Still)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
3-13-18 LHammond In Testing

**Comment by LisaLNelson** [comment]
Moving back to development because I can't change it from 1 person to any of the other options.

**Comment by Kibrahacha67** [comment]
Hi Lisa, I just tested it again to make sure, what browser are you using?

Larry

**Comment by Kibrahacha67** [comment]
3-19-18 LHammond In Testing

**Comment by JodieYoung1** [comment]
Tested successfully. Displayed the number of personnel needed and was able to edit/change the number of personnel needed.

**Comment by LisaLNelson** [comment]
Tested. Good to go.

**Comment by LisaLNelson** [comment]
Approved for closure. LN
