### ISSUE TITLE
Bug: Non admin users flip toggle off and are no longer able to get to their "not open" opportunity.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1863]
Steps to Reproduce: 
1) Post an opportunity
2) As a non admin user,  change "Continue accepting applicant" to Off
- Profile doesn't display non open opportunities
- non admin don't see not open in their filtesr
- unable to get back to job.  Profile should display not open jobs.

Bug bash 3/6/18

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-14-18 LHammond In Testing

**Comment by kbwagner** [comment]
3/20/18-Katrina Wagner tested in Chrome. Not open job now displays in profile.
@LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
Tested. Good to go

**Comment by LisaLNelson** [comment]
Approved for closure LN
