### ISSUE TITLE
Spike: In progress and toggle on pill and status bar values

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1866]
When an opportunity is under ‘In progress’ and the toggle is on, the left pill should be ‘Open’ while the progress bar stays  ‘In progress’.   Dev to research this more.
![image](https://user-images.githubusercontent.com/18709918/37114885-9505a722-2217-11e8-9c66-0ec275416f7a.png)

From bug bash 3/6/18

**Comment by bmcorum** [comment]
@minchung12, I wonder if it would be better to add differentiate the two in progress states like:

"In progress"
"In progress - accepting applicants"

We wont have to update a pill just simply add the "In progress - accepting applicants" to the search filters and then maybe create a pill "accepting applicants" that will display along side the in progress pill on the opportunity details page.

**Comment by bmcorum** [comment]
After discussions with @minchung12, @kbwagner, Debbie, we have decided to add the additional functionality and logic.

### Opportunity details page (view)
- Opportunities that are **_In progress_** with the **_continue accepting applicants_** toggled **on** will show the **Open** pill but still show **_In progress_** on the progress bar
- Opportunities that are **_In progress_** with the **_continue accepting applicants_** toggled **off** will show the **In progress** pill and show **_In progress_** on the progress bar

### Opportunity search page (list/card)
- Selecting **Open** from filters will display **_Open_** and **_In progress_** with the **_continue accepting applicants_** toggled **on** (each will have the **Open** pill)
- Selecting **In progess** from filters will display **_In progress_** with the **_continue accepting applicants_** toggled **off** (each will have the **In progress** pill)

**Comment by JodieYoung1** [comment]
Research is complete. Closing out #1886 Spike: In Progress and toggle on pill and status bar values. 
Reference: Ticket #1972: In Progress/Open toggle.
