### ISSUE TITLE
Spike: Research how to use markup

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1868]
Issue 1: 
From the bug bash: The bullets (rich text) is automatically populating 3 bullets.  Also the bullets don't display in number order.    
Resolution: This is working as designed.  When you are in edit mode it looks weird but in preview mode it looks fine. 
![image](https://user-images.githubusercontent.com/18709918/37115065-1b9c5560-2218-11e8-9c2c-2608c2080399.png)

Issue 2: Per Lisa users don't understand how to use the mark up editor.

Spike: Research how the markup works and how we can best share/teach our users how to use it.

From bug bash 3/6/18

Related tickets: 
1166
1922

**Comment by Piglady64** [comment]
See if we can look at the purpose of the button and make it work more effectively.
