### ISSUE TITLE
Bug: Remove Congratulations message from Assigned participants

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1869]
Steps to reproduce: 
1) Open a Completed opportunity
2) Assigned participants shouldn’t see ‘Congratulations’ box after the opportunity has been completed
![image](https://user-images.githubusercontent.com/18709918/37115276-adcf9bcc-2218-11e8-8733-1bf2ae0f90d4.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. Message should no longer show once the opportunity is marked completed.

**Comment by margaretdumas** [comment]
Mdumas - Testing

**Comment by kbwagner** [comment]
3/19/18 - Katrina Wagner tested in Chrome.  Looks ok.
@LisaLNelson - ready for you to test.

**Comment by LisaLNelson** [comment]
Tested on my MAC and the message showed up.  Moving back to In development.
![screen shot 2018-03-20 at 10 07 30 pm](https://user-images.githubusercontent.com/9039852/37691873-51d50500-2c8b-11e8-955b-e40d92071137.png)

**Comment by bmcorum** [comment]
@LisaLNelson the photo you attached is NOT a completed opportunity and thus the message shows. The acceptance criteria clearly states **Assigned participants shouldn’t see ‘Congratulations’ box after the opportunity has been COMPLETED**

**Comment by LisaLNelson** [comment]
Tested.  Good to go.

**Comment by LisaLNelson** [comment]
Approved for closure LN
