### ISSUE TITLE
As an open opportunities member, I do not want to see duplicate badges in my profile.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1872]
Create script to do a database cleanup to remove duplicate badges.

![image](https://user-images.githubusercontent.com/18709918/37115680-d528d9ee-2219-11e8-9dcc-61e349a9e8ad.png)

from bug bash 3/6/18

**Comment by bmcorum** [comment]
Users with duplicated badges in TEST

![image](https://user-images.githubusercontent.com/1165615/72088638-973e7900-32d8-11ea-9476-1e9ed6a14b44.png)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-9-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/9/20 - Verified against artifact in Test
Ready for final review
