### ISSUE TITLE
Spike: Outlook won't display apostrophes in email subjects

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1877]
![image](https://user-images.githubusercontent.com/18709918/37120665-05710f36-2229-11e8-897b-8e2e3280ac50.png)

Email displays odd text in the subject instead of apostrophe.  Might just be my Outlook.  Is there anything we can do for this?  

From bug bash 3/6/18

**Comment by kbwagner** [comment]
1/15/20 - FAI notified us they see this issue in the comment email and they use Google email so not limited to Outlook.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
01/27/2020 - Mdumas - The issue was tested and has been corrected.  Moving on to review.

**Comment by nia-johnson** [comment]
Passed in Test. Moving to final review.

**Comment by kbwagner** [comment]
Reviewed in Test/Chrome - it works!
Closing
