### ISSUE TITLE
Admin: Ability to manually add applicants to an opportunity.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1878]
User Story: As an administrator, I need the ability to manually add applicants to an opportunity. 
 
Acceptance Criteria: 
- System Administrators need the ability to manually add an applicant to an opportunity (functionality was removed with redesign).  At this time, the agency admin does not need this ability.
- The system should track who added the applicant, what applicant was added, and the date.

Design Option (Can be modified):
- On the Admin --> Task page, add an icon under "Action" for any Open or In Progress jobs
- The icon will be an add applicant icon: https://fontawesome.com/icons/user-plus?style=solid
- when selected, a modal will display where the admin can search by existing active users
- Once a user is selected, they will be added as an applicant on the opportunity.
- The applicant will receive the standard email that states that their application was submitted.

Related Ticket: 
2205 - Metrics: Need to track how many times an agency person does not enter an applicant themself but has Lisa/Admin do it for them.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-1-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum two things and you can tell me if you want a new ticket:
1) It allows me to add disabled user as an applicant and it should not.  Yes, I realize I didn't spell that one out but thought of it based on our conversation yesterday.  
2) The pop up modal uses the term "Participant" in the header, search box, and button...but that really isn't the correct term.  
- Header: Add applicant to this opportunity
- Search for a User or Search people
- Add applicant (button)

![image](https://user-images.githubusercontent.com/18709918/40976807-3a34e890-689d-11e8-854a-476eb66fcb50.png)

Let me know  if I should send this back or write new tickets.  Thanks!

**Comment by bmcorum** [comment]
AC does use the term "applicant" I will update to use the applicant term

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
6/7/18 - KWagner tested in Chrome and mobile Safari
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved
