### ISSUE TITLE
Bug: Mobile: Tasks created on mobile don't send email to admin

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1880]
Task created on mobile devices do not send an email to let me/Lisa know they are there to be opened.

Bug Bash 3/6/18

**Comment by bmcorum** [comment]
Upon further inspection and research it has been discovered that emailing administrators in any capacity has never been implemented. This will need to be closed as a non issue, and features/enhancement tickets created for each email that needs to be created and sent to application administrators.

**Comment by bmcorum** [comment]
@margaretdumas see comment above. Does this need to just be moved through or closed altogether?
