### ISSUE TITLE
Bug: Mobile - Unable to load profile message

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1881]
User received the following error on their mobile device
![image](https://user-images.githubusercontent.com/18709918/37121574-8d48df90-222b-11e8-8e34-a0691df1edaf.png)

per brice: is trying to view a profile page without being signed in. We could look at directing him to login, but then until we update login to return users to previously requested page it won’t be of much help

**Comment by jhanson12** [comment]
Brice and I have tested this bug in development/UAT and looks like it has been fixed.  The fix may also be in production.  Please test.

**Comment by Kibrahacha67** [comment]
3-15-18 LHammond In Testing

**Comment by LisaLNelson** [comment]
Tested.  Good to go.

**Comment by LisaLNelson** [comment]
Approved for closure LN
