### ISSUE TITLE
Bug: Mobile - Find opportunities page won't load

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1882]
When I click on Find Yours the Find Opportunities page header and footer loads, but the ‘Loading…’ circle just keeps spinning for minutes but does not complete. I tried it multiple times with same results.

**Comment by jhanson12** [comment]
This bug needs to be retested.  Margaret and I were unable to reproduce on the iPhone 7 plus and Samsung.

**Comment by kbwagner** [comment]
No longer able to reproduce.  Closing.
