### ISSUE TITLE
Bug: Mobile - Unable to click on opportunity created from profile page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1883]
I am unable to click on the opportunity I created from my profile page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
3-15-18 LHammond In Testing

**Comment by LisaLNelson** [comment]
Tested and not working on my Samsung Galaxy. Returned to In Development.

**Comment by margaretdumas** [comment]
Mdumas - Cannot reproduce.  Please clear cache.

**Comment by KatMullens-work** [comment]
I was able to click on a Submitted Opportunity and an Open Opportunity from my profile page. 

I created the opportunity from the button on the /tasks page, not from the profile page. I don't see an "add opportunity", etc. button on the profile page, though, so I think this passed the test! :)

**Comment by LisaLNelson** [comment]
Approved for closure LN
