### ISSUE TITLE
Bug: Create account page spacing issue

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1885]
Create Account page, need space between label and field

![image](https://user-images.githubusercontent.com/18709918/37160731-e57147dc-22be-11e8-9ae4-1804074ac46b.png)

(Matt Dingee/Bug Bash Testing)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
03/28/2018 - Mdumas - In testing...

**Comment by margaretdumas** [comment]
Mdumas - Please add space between cancel and create account buttons for mobile on create account page.

**Comment by margaretdumas** [comment]
03/29/2018 - Mdumas - Testing complete

**Comment by LisaLNelson** [comment]
Moved to deploy - LN

**Comment by LisaLNelson** [comment]
Approved for closure
