### ISSUE TITLE
Bug: Load icon does not match design system/core.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1886]
The load icon should match what is in the design system and Core.

![image](https://user-images.githubusercontent.com/18709918/37160791-08b1e472-22bf-11e8-8133-36eb0e07038c.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
03/28/2018 - Mdumas - In testing...

**Comment by margaretdumas** [comment]
Mdumas - Loading icon is displaying correctly. Testing completed...

**Comment by LisaLNelson** [comment]
moving to ready to deploy LN

**Comment by LisaLNelson** [comment]
Approved for closure
