### ISSUE TITLE
Opportunity Card: Ignore HTML

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1887]
Who: Open Opportunities Users
What: Opportunity Card display should ignore markup
Why: In order to have a consistent look

Acceptance Criteria: 
The opportunity card should match the design system and ignore any HTML/markup entered by a user.  HTML/markup can display when the full opportunity is displayed.

![image](https://user-images.githubusercontent.com/18709918/37160918-4eb95f7c-22bf-11e8-913a-0a6e7f952c1f.png)

Source: Design request - Min Chung

**Comment by Piglady64** [comment]
Needs further research

**Comment by kbwagner** [comment]
users are using markdown - we would have to strip out markdown and just pull content for cards.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1+28-20 LHammond in testing
Testing completed.  moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/21f4630a-0fee-42a7-ab04-29d1f7c64150)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c32b4d9f-4a3a-44e9-bfe2-fea8f2ec2e95)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/29638fd4-7659-43d9-8430-d918b11e3b1e)

**Comment by kbwagner** [comment]
KWagner reviewed - closing
