### ISSUE TITLE
Bug: Mobile - Boxes shouldn't be card style on all pages.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1891]
For mobile, boxes shouldn’t be card style on all pages (same as USAJOBS) 

https://projects.invisionapp.com/d/main#/console/12656859/266166955/preview

https://projects.invisionapp.com/d/main#/console/12656859/271056409/preview
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/ad415be4-a97e-458c-88fc-af5dd260ba28)

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/5ff9e846-6d64-473a-825b-bc1331c33921)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
3-13-18 LHammond in testing

**Comment by LisaLNelson** [comment]
Approved for closure LN
