### ISSUE TITLE
Bug - Mobile: Signed Out Landing page display issues

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1892]
The following display issues when a user goes to the open opportunities landing page as a signed out user:
1)  Landing page text not aligned:
![image](https://user-images.githubusercontent.com/18709918/37166418-faf68910-22cc-11e8-9aed-053801f78632.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
Mdumas - 03/12/2018 - In testing....

**Comment by margaretdumas** [comment]
03/12/2018 - Moving back to development for text alignment.  This is the text that is next to the image file.

**Comment by jhanson12** [comment]
This issue has been fixed with bug #1800

**Comment by margaretdumas** [comment]
Testing completed. Mdumas

**Comment by kbwagner** [comment]
3/19/18 - Katrina tested on mobile
@LisaLNelson - ready for you to test.

**Comment by LisaLNelson** [comment]
Tested. Good to go

**Comment by LisaLNelson** [comment]
Approved for closure LN
