### ISSUE TITLE
Bug - Mobile: Signed in landing page display issues

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1893]
The following display issues are occurring on the sign in landing page: 
1) Logged in landing page - find opportunities button sizing off

![image](https://user-images.githubusercontent.com/18709918/37167519-23fa58de-22d0-11e8-9877-03f537432c7f.png)

2) Photos displaying huge - may be resolved.

3) Username does not appear at the top with user icon; also people icon does not appear at the top of the screen (between user icon and search) in the same way it does for desktop users.  Chrome mobile experience via Android (Samsung S7 Edge
![image](https://user-images.githubusercontent.com/18709918/37178005-2f50a7f0-22ef-11e8-9212-84bc7afb0749.png)

**Comment by margaretdumas** [comment]
03/12/2018 -Mdumas - Moving back to development.  #3 . People icon still does not display on menu.  
Issues 1 & 2 are resolved.

**Comment by margaretdumas** [comment]
03/13/2018 - Mdumas - Testing

**Comment by margaretdumas** [comment]
Mdumas - Testing completed

**Comment by kbwagner** [comment]
3/19/18 - Katrina tested on iPhone/Safari.  People icon displays under Search dropdown.  Looks ok
@LisaLNelson - ready for you to test.

**Comment by LisaLNelson** [comment]
Tested. Good to go

**Comment by LisaLNelson** [comment]
Approved for closure LN
