### ISSUE TITLE
Bug - Mobile: Admin page display issues

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1895]
The following display issues are happening for the admin pages in mobile: 

1) Agency Admin
https://projects.invisionapp.com/d/main#/console/12656859/267500884/preview
- Should have a plus sign rather than send menu to two lines
![image](https://user-images.githubusercontent.com/18709918/37167669-8f93ac12-22d0-11e8-9948-0640a7edb981.png)

2) Admin Dashboard - sort dropdowns don't align
![image](https://user-images.githubusercontent.com/18709918/37167913-383d6880-22d1-11e8-8a50-5a4c50f8ed3a.png)

3) Admin > Tasks - filters don't align
![image](https://user-images.githubusercontent.com/18709918/37167947-523c56e2-22d1-11e8-8960-61d8158b4207.png)

4) Admin - Tasks don't wrap and display fully
![image](https://user-images.githubusercontent.com/18709918/37167965-6254dcf2-22d1-11e8-8b4a-bbf4efcbbffe.png)

5) Agency Admin page - tag doesn't line up
![image](https://user-images.githubusercontent.com/18709918/37167577-4d1bf998-22d0-11e8-87f1-e4e8d7c21edc.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
Mdumas - moving this one back for : 
1. Fields are not left justified (Type and period)
2. Cannot click the "Dashboard"option and go to that page. When clicking it from tasks, I am taken to "Agency Dashboard"

**Comment by margaretdumas** [comment]
03/30/2018 - Mdumas - Testing complete

**Comment by LisaLNelson** [comment]
Ready to deploy. - LN

**Comment by LisaLNelson** [comment]
Approved for closure. LN
