### ISSUE TITLE
Bug - Mobile: Profile display issues

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1896]
The following display issues occur on the mobile version of the profile: 
1) Profile Page not lining up;
![image](https://user-images.githubusercontent.com/18709918/37167640-77495f26-22d0-11e8-9e88-06c48a79cfce.png)

2) Full title of the opportunity doesn't display in profile dashboard.
![image](https://user-images.githubusercontent.com/18709918/37177505-a2def200-22ed-11e8-860e-0097e0ae0f4a.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
3-15-18 LHammond In Testing

**Comment by margaretdumas** [comment]
Mdumas - In testing

**Comment by margaretdumas** [comment]
Sorry, ticket is already in testing by Larry.

**Comment by kbwagner** [comment]
3/19/18 - Katrina Reviewed on mobile Safari.  Looks good.
@LisaLNelson - ready for your review.

**Comment by LisaLNelson** [comment]
Tested. Not displaying properly on my Samsung Galaxy. Sending back to In Development.

**Comment by LisaLNelson** [comment]
Approved for closure LN
