### ISSUE TITLE
Bug: Opportunity cards display in one column in IE

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1898]
Issue: Opportunity cards should all be the same size but display differently in Internet Explorer.  
Resolution: Should display 2 cards per row.

![image](https://user-images.githubusercontent.com/18709918/41248379-dcd5e12c-6d7e-11e8-962f-6402da7a4856.png)

**Comment by jhanson12** [comment]
@raywilliams did this get fixed?  If so, could we move to testing?

**Comment by kbwagner** [comment]
@raywilliams @jhanson12 @bmcorum I just tested this in IE and the boxes are the same size but mostly appear all in one column. 
![image](https://user-images.githubusercontent.com/18709918/37671595-720a9ba8-2c42-11e8-850d-a1d06ac7e869.png)

**Comment by kbwagner** [comment]
Confirmed still an issue 4/9/18 - cards are the same size but display all in one column.

**Comment by kbwagner** [comment]
6/4/18 - KWagner confirmed still an issue.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-15-18 LHammond in testing

**Comment by kbwagner** [comment]
6/17/18 - KWagner tested in IE
@LisaLNelson ready for final review.

**Comment by tlorrison** [comment]
approved
