### ISSUE TITLE
Bug - Mobile: Opportunity Search page display issues

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1900]
The following display issues occur on mobile when the user is on the search/opportunity listing page: 
1) Browse Opportunity page displays poorly
![image](https://user-images.githubusercontent.com/18709918/37120186-acfb6096-2227-11e8-8772-d424261792ae.png)
- could not click on the open buttons.

2) Search bar cut off:
![image](https://user-images.githubusercontent.com/18709918/37166431-032b20be-22cd-11e8-8cef-122020c7fc1b.png)

3) Search page error not showing up (font awesome)
![image](https://user-images.githubusercontent.com/18709918/37166455-114a2be0-22cd-11e8-91fa-d83bb9f6488b.png)

4) : On mobile, image of requestor overlays text, making it hard to see content surrounding the image. 
![image](https://user-images.githubusercontent.com/18709918/37177777-6fdece7e-22ee-11e8-9410-ba393385659a.png)

5) : Icon overlays text on specific task / opportunity pages. Chrome mobile experience via Android (Samsung S7 Edge):
![image](https://user-images.githubusercontent.com/18709918/37177902-d6335aa0-22ee-11e8-8713-1019d8b78a1c.png)

**Comment by margaretdumas** [comment]
03/12/18/ Mdumas - In Testing....

**Comment by margaretdumas** [comment]
Mdumas - Testing completed.  #1 mentions cannot click on open button.  These are not links the website does not allow for clicking on them as well.

**Comment by LisaLNelson** [comment]
Tested. Ready to go.

**Comment by LisaLNelson** [comment]
Approved for closure. LN
