### ISSUE TITLE
Bug - Mobile: Display issues on view Opportunity page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1901]
The following display issues occur on the view opportunity page:
1) Alignment

![image](https://user-images.githubusercontent.com/18709918/37177584-ea39e326-22ed-11e8-8834-1b7197bff172.png)

2) keywords should align under the circular icon - Chrome mobile experience via Android (Samsung S7 Edge
![image](https://user-images.githubusercontent.com/18709918/37177941-fc0164d4-22ee-11e8-93d3-ee05f4594144.png)

Prototype: https://projects.invisionapp.com/d/main#/console/12656859/271064124/preview

**Comment by Kibrahacha67** [comment]
3-19-18 LHammond In Testing

**Comment by kbwagner** [comment]
3/20/18 - Katrina Wagner tested mobile Safari.  Alignment looks good.  Skill boxes are displaying as green in mobile.  Checking with @minchung12 and will test further.

**Comment by LisaLNelson** [comment]
03/20/18 Looks good! LN

**Comment by LisaLNelson** [comment]
Approved for closure. LN
