### ISSUE TITLE
Bug: Back button from opportunity doesn't work right when coming from profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1902]
Steps to reproduce: 
1) Open an opportunity from the profile page listings
2) Post a comment on the opportunity
3) Click the back buttom
Issue: After posting a comment on this task page, I hit the back button and it goes to
homepage instead of back to my profile page.
** The back button does work if I access the task page from Profile, and don’t post.

**Comment by bmcorum** [comment]
@kbwagner I tested in UAT following the above outlined steps and was unable to reproduce. Can you please test as well to verify if this is still an issue?

**Comment by kbwagner** [comment]
@bmcorum - Agreed.  Tested in UAT and no longer appears to be an issue.  I will close.
