### ISSUE TITLE
New Account - Failed

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1906]
As a new account holder of Open Opportunities, add the reason(s) why registration failed.
Create a New Account with a non-Government Email Address
•	Visit homepage (log out if logged in)
•	Click on Sign in
•	Select Create a new account
•	Enter a non government email address (i.e. gmail)
•	You should see a Registration failed alert message.

**Comment by bmcorum** [comment]
@JodieYoung1 I think the entire account creation needs to be revisited. My recommendation is as follows:

1. Select 'Create new account'
2. Enter name
3. Select agency
4. Enter agency email address
5. Click 'Create account'
6. Validate that the domain for the email address entered matches
selected agency (ie OPM = opm.gov, GSA = gsa.gov)
7. If not valid, return registration failure message
8. If valid, send email with a 'Complete registration' link that allows the user to create a password

**Comment by Piglady64** [comment]
Been redesigned closing
