### ISSUE TITLE
Landing Page Redesign

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1907]
Landing page and logged in landing page should be redesigned.
1) After signing in the landing page list latest achievements and above the latest achievements is "There are 14 open opportunities right now." and the "Find yours" button. There should be a clearer message to find open opportunities and to create opportunities.
-Remove the latest achievements from this page and relocate to another 
-Change "Find yours" to "Find opportunity" or "Find opportunities" OR display/list  the opportunities on this page
2) Creating an opportunity should be on the Top Nav of the landing page. Clicking search doesn’t really make sense to create an opportunity.
-Put "Create an opportunity" feature on the landing page

**Comment by kbwagner** [comment]
5/17/18 - KWagner - Closing this. Landing page redesigned with release 2
