### ISSUE TITLE
Footer URL focus

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1909]
As a user, should be able to click on the URL and click back to the bottom/footer.

Notes: Footer URLs: when you click on a URL and then click the back button you are taken to the top of the page.  In USAJOBS if you click on the URL and click back your focus is taken to the bottom/footer of the page.  

Low priority

**Comment by kbwagner** [comment]
4/9/18 - confirmed still an issue.

**Comment by Piglady64** [comment]
Our links open in same window. Closing
