### ISSUE TITLE
Remove Open Source Link in Footer

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1911]
### Who
Open Opps users 

### What
The open source link is no longer visible or present in the footer of the Open Opps site 

### Why
The content the link contains is outdated and the presence of the link itself is not compulsory. 

### Acceptance Criteria
- The open source link is no longer visible or present in the footer of the Open Opps website, including the State sub-page
- The Help Cite and Open Opps email links (the State email for the State subpage) are moved up in the footer. 

### Related Tickets 
None

### Mocks
n/a

**Comment by Piglady64** [comment]
Can we take the "powered by open source" out of the footer?

**Comment by kbwagner** [comment]
@nia-johnson can you get this one ready for sprint planning tomorrow?  It's an easy one to add in.  Thanks!

**Comment by kbwagner** [comment]
1/8/20 - Team decided to remove link and move the Help center and email address up to be in line with bottom line of links.

![image](https://user-images.githubusercontent.com/18709918/72000384-313aee80-3211-11ea-989c-fa5937d052be.png)

2) Also need to remove from State footer

**Comment by bmcorum** [comment]
Ready for testing

**Comment by nia-johnson** [comment]
@kbwagner Ready for final review

**Comment by Kibrahacha67** [comment]
1-7-20 LHammond Testing completed

**Comment by kbwagner** [comment]
@raywilliams we may need to leave the help desk info on another line as it makes the usa.gov go to a new line when it's moved up.

![image](https://user-images.githubusercontent.com/18709918/72733793-945c4780-3b66-11ea-9844-363ce11794b3.png)

@abudz19 thoughts on this?   I definitely don't think usa.gov should be hanging on it's own line.  If there isn't enough room for help center and the email to be on the same line do we still keep it on it's own line on the right?  Or left justify it?

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-22-20 LHammond in testing

**Comment by kbwagner** [comment]
1/22/20 - KWagner reviewed in test/Chrome
Ready for final review

Created new ticket to work on spacing.
