### ISSUE TITLE
Save a draft

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1915]
As a creator, would like instructions on how to go back to submit an opportunity.

Note: Save as draft is confusing – add instructions on  how to go back to submit

**Comment by kbwagner** [comment]
look into updating modal

@abudz19 to look at this save draft experience.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41525&_a=edit
