### ISSUE TITLE
Edit Opportunity - Headline to Title

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1917]
### Who
Open Opps users

### What
Changing "Headline" to "Title" on the Open Opps site. 

### Why
Changing the terminology for clarity was at the suggestion of Open Ops users. 

### Acceptance Criteria
"Headline" should be changed to "Title" in the following places: 
- Create/Edit Opportunity page 

There is a separate design ticket to update the help center pages affected: 
- [Sample Opportunities page](https://usajobs.github.io/openopps-help/opportunity/sample-opportunities/)  

### Related Tickets 
None

### Mocks
None

**Comment by kbwagner** [comment]
@nia-johnson please look through help center, 10 tips, screen shots on help and see if there is anywhere we need to update with this change.
- Also verify edit message will likely need to change

**Comment by nia-johnson** [comment]
@kbwagner 

1. I only found Headline used on the Sample Opps page in the Help Center
2. I didn't find any screenshots in the Help Center 
3. The edit message doesn't need to change, but the headline above it does (see below) 
<img width="479" alt="Headline" src="https://user-images.githubusercontent.com/57805715/72012662-4c662800-322a-11ea-858d-02c6f64b09cd.PNG">

**Comment by kbwagner** [comment]
@nia-johnson thanks...for the second bullet above for sample opportunity - that's a change Debbie will have to make in the help center.  Can you just note it here (not acceptance criteria but an FYI note at the bottom and then enter a design team ticket and assign to Debbie?  I can put this in the next sprint so ask her to complete by 2/6 for release on 2/7.  Thanks!

**Comment by nia-johnson** [comment]
The "Sample Opportunities" page is being handled by the design team. A [ticket ](https://github.com/USAJOBS/team-design/issues/148)has been created in their backlog.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by nia-johnson** [comment]
@kbwagner Ready for final review

**Comment by Kibrahacha67** [comment]
1-17-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/20/20 - KWagner tested in Chrome/Test
Closing
