### ISSUE TITLE
As an administrator I need a way to delete drafts.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1928]
User Story: As an Open Opportunities administrator, I need the ability to delete draft opportunities to prevent a long list of drafts.

Acceptance Criteria:
- Users with the Open Opportunities Administrator role, should have the ability to delete opportunities in draft status.
- In the Admin Dashboard --> Tasks section, add a delete option beside all opportunities in draft status

Note from Lisa:  In the old system I was able to delete drafts.  I need to have that functionality restored or we will end up with a long list of drafts to sort through.

**Comment by LisaLNelson** [comment]
Consolidated into issue # 1976.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-6-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum two questions:
1) The delete uses the old style modal - there is an existing ticket to change admin modals to the new design system modal.  Should I pass this and make that that ticket is updated to include this modal?  Or is it an easy fix?
2) When I click Ok on the confirmation, the page refreshes and I loose my drafts.  It goes back to the default search of "Submitted".  Is there a way to keep it on the page where I was?

**Comment by bmcorum** [comment]
@kbwagner each of those questions will need to be new tickets. Number 1 I think has a ticket

**Comment by kbwagner** [comment]
@bmcorum   -that's fine. Yes #1 is a ticket so I'll add this modal to it.  #2 will be a new ticket.  Thanks

**Comment by kbwagner** [comment]
5/18/18 KWagner tested in Chrome. 
- Confirmation modal style is current ticket 1843
- Will create a new ticket to not refresh the page when the confirmation is selected.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
