### ISSUE TITLE
Help Center location - landing page and footer

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1934]
As an Open Opportunities user, I want to be able to click on the Help Center link under "How does it work?" on the landing page as well as on the footer that reads Visit our Help Center

![Screen Shot 2018-03-12 at 10.59.28 AM.png](https://images.zenhubusercontent.com/59fb63728a75884b9085d569/dbe0f4de-ed48-40a8-b1df-b91eb1591ae0)

**Comment by margaretdumas** [comment]
03/15/2018 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
Mdumas 03/16/2018 - Footer link different than mock.  Moving back to development.

**Comment by margaretdumas** [comment]
Mdumas - Testing complete.  Needed to refresh the page.

**Comment by JodieYoung1** [comment]
Tested successfully. Was able to click on the Help Center link from both the Landing Page and the Footer.

**Comment by kbwagner** [comment]
Reopening since this was accidentally closed.

**Comment by LisaLNelson** [comment]
Approved for closure LN
