### ISSUE TITLE
 New Task - Unable to use date picker to add Estimated completion date (Windows Edge)

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#1945]
If I create a new task and try to add an estimated completion date, the date picker displays but does not allow for selecting a date.  A date cannot be added via the keyboard either. 

Steps to reproduce:
1.  Sign into Openopps
2.  Select Post opportunity
3.  Navigate down to the Estimated completion date field (which is optional)
4.  Click into the field
Results:  Date picker displays and does not allow for selecting a date.

**Comment by jhanson12** [comment]
@minchung12 would you like us to use the design system calendar solution?  It is used in USAJOBS and would also solve this issue.

**Comment by minchung12** [comment]
@jhanson12 Yes, please use the same calendar we use in USAJOBS.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. Be sure to clear cache as it includes CSS changes.

**Comment by margaretdumas** [comment]
Mdumas -Testing complete.  Moving to review.

**Comment by LisaLNelson** [comment]
Approved for closure LN
