### ISSUE TITLE
Display new registrants on the landing page by user id rather than time.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1959]
Filter registrant by ID rather than create date due to time zones.

Steps to Reproduce: 
1) Create a new open opportunities account
2) Log out
3) Log back in - the new account name should display on the logged in landing page as a new registrant.

**Comment by bmcorum** [comment]
Tested in UAT and was not able to reproduce. See images below. Also, inspected data in PROD and it appears that it was related to a "time drift/difference" between the two virtual instances we have establish for the production environment at Cloud.gov and the fact that 20+ user all registered for new account around March 13 at about 5:30PM which I believe was shortly after we release the news letter about the newest release/updates to Open Opportunities, which would account for the increased signup rate which made the time difference on the virtual instances appear.

![1959-1_of_3](https://user-images.githubusercontent.com/1165615/37612546-db9c3d14-2b7b-11e8-897f-fed4545e51aa.PNG)
![1959-2_of_3](https://user-images.githubusercontent.com/1165615/37612548-ddf1c886-2b7b-11e8-8b53-e75d3c1a8243.PNG)
![1959-3_of_3](https://user-images.githubusercontent.com/1165615/37612552-e0178088-2b7b-11e8-8b47-2e8c97c7504e.PNG)

**Comment by kbwagner** [comment]
We will want to do this by user id vs time.

**Comment by Piglady64** [comment]
This page is gone. closing
