### ISSUE TITLE
Display 10 opportunities per page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1960]
User Story: As an Open Opportunities seeker, I would like to have a standard number of cards display in my search results.

Acceptance Criteria:
For both mobile and desktop, 10 opportunities should display per page.

**Comment by Kibrahacha67** [comment]
6-5-18 LHammond In Testing

**Comment by kbwagner** [comment]
6/6/18 - KWagner tested in Chrome, IE, and mobile Safari.
IE still only displays one column of opportunity cards but there is a separate bug ticket for that.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved.
