### ISSUE TITLE
Admin ability to reassign an opportunity to a new creator

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1964]
User Story: As an agency admin or product admin, I want to be able to reassign an opportunity in case the original creator leaves my agency.

Acceptance Criteria:
- Allow agency admin to reassign an opportunity from one person to another in case the one person leaves the agency. 
- The product administrator should also have this ability to reassign an opportunity to another person.
- The system should track who made the assignment change, what change was made (from person x to person y), and the date of the change.

Design Option: (can be modified by Macon)
- Where user role is agency admin or admin
- On the administration --> Tasks page
- for any opportunities in open and in progress status
- Add an icon to the Actions column to change owner: https://fontawesome.com/icons/user-cog?style=solid
- When this icon is selected, a modal will display with a people search by name.
- The people list will be restricted to the people in the same agency as the current opportunity owner.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

Will attach an artifact at a later date to show we are logging the changes in an AuditLog table.

**Comment by margaretdumas** [comment]
05-31-2018 - Mdumas - In testing....

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
06/04/2018 - Mdumas - Retesting...

**Comment by bmcorum** [comment]
Screenshot of audit_log table recording the change owner action.

![image.png](https://images.zenhubusercontent.com/59e8ff8ea468affe6df75add/da432dd9-7e31-43c3-ab01-9cc8a21e7554)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-6-18 LHammond in testing

**Comment by kbwagner** [comment]
6/7/18 - KWagned tested in Chrome, IE, and mobile safari as an admin and agency admin.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved.

**Comment by LisaLNelson** [comment]
approved
