### ISSUE TITLE
Spike: Research archiving 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1968]
research whether or not we want to bring back an "archiving" functionality and if not do we want to do some data research to determine which OLD archived tasks are really "canceled" vs "archived"

**Comment by kbwagner** [comment]
User research

**Comment by nia-johnson** [comment]
Moving to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41586&_a=edit
