### ISSUE TITLE
As an administrator, I want to generate metrics on how opportunity creators are creating their opportunities.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1969]
Acceptance Criteria: 
- Create a new report area on Administration --> Dashboard to generate metrics on completing opportunities
- Under "Completed" display rows for "Completed by Admin" and "Completed by Opportunity Creator" 
- Completed by Admin will display the number of opportunities for the selected time period that were completed by someone other than the Opportunity Creator
- Completed by Opportunity Creator will display the number of opportunities for the selected timer period where the same person that created the opportunity actually completed the process.

Current Admin Dashboard:
![image](https://user-images.githubusercontent.com/18709918/37724285-c6ae2336-2d06-11e8-9769-315572be2e2e.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
4/4/18 LHammond in testing

**Comment by kbwagner** [comment]
@LisaLNelson look good - ready for your review.

**Comment by LisaLNelson** [comment]
Approved for closure. LN
