### ISSUE TITLE
Users, admins and  agency administrators need to be able to delete comments.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1970]
As an agency administrator, task creator, or Open Opps user, I should be able to delete comments placed on a task's Discussion area.

Specifically:

As an Open Opps user, I should be able to delete my own comments.
As a task creator, I should be able to delete any comments posted to the Discussion area of only tasks I created.
As an admin, I should be able to delete any comments by any users.
As an Agency Admin (if we are still using this role), I should be able to delete any comments on tasks posted by people at my agency.
Acceptance Criteria:

As an Open Opps user, I can delete my own comments, but only my own comments.
As a task creator, I can delete any comments posted to the Discussion area of only tasks I created, but not tasks I did not create.
As an admin, I should be able to delete any comments by any users.
As an Agency Admin (if we are still using this role), I should be able to delete any comments on tasks posted by people at my agency, but not delete any comments on tasks that are not posted by my agency. If I want to delete a task posted anywhere else, I can email the Admins.

**Comment by LisaLNelson** [comment]
That is a good question @bmcorum I think we should allow for a user to delete their own comment as well.  So it would be for agency admins, admins and users.  Will update.

**Comment by KatMullens-work** [comment]
As an agency administrator, task creator, or Open Opps user, I should be able to delete comments placed on a task's Discussion area.

Specifically:
1. As an Open Opps user, I should be able to delete my own comments.
2. As a task creator, I should be able to delete any comments posted to the Discussion area of only tasks I created.
3. As an admin, I should be able to delete any comments by any users.
4. As an Agency Admin (if we are still using this role), I should be able to delete any comments on tasks posted by people at my agency.

**Acceptance Criteria:**
1. As an Open Opps user, I can delete my own comments, but only my own comments.
2. As a task creator, I can delete any comments posted to the Discussion area of only tasks I created, but not tasks I did not create.
3. As an admin, I should be able to delete any comments by any users.
4. As an Agency Admin (if we are still using this role), I should be able to delete any comments on tasks posted by people at my agency, but not delete any comments on tasks that are not posted by my agency. If I want to delete a task posted anywhere else, I can email the Admins.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
4/3/18 LHammond in testing

**Comment by Kibrahacha67** [comment]
4/4/18 LHammond in testing

**Comment by KatMullens-work** [comment]
Hi @Kibrahacha67 or @margaretdumas : Please post comments to discussions so that I can test them as an admin and a non-admin.

I can delete comments I make to a discussion as a regular user.

I can delete comments I make to a discussion as an admin.

Need more discussions to be able to complete testing.

**Comment by LisaLNelson** [comment]
I can delete my own comment

**Comment by LisaLNelson** [comment]
Approved for closure LN
