### ISSUE TITLE
In Progress/Open toggle

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1972]
As an Open Opportunity User; by

Opportunity search page (list/card)
- Selecting Open from filters will display Open and In progress with the continue accepting applicants toggled on (each will have the Open pill)
- Selecting In progress from filters will display In progress with the continue accepting applicants toggled off (each will have the In progress pill)

Opportunity details page (view)
- Opportunities that are In progress with the continue accepting applicants toggled on will show the Open pill but still show In progress on the progress bar
- Opportunities that are In progress with the continue accepting applicants toggled off will show the In progress pill and show In progress on the progress bar

NOTE: Reference #1866 Spike: In progress and toggle on pill and status bar values

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
3-28-18 LHammond in testing

**Comment by JodieYoung1** [comment]
1) By selecting 'Open' only displayed opportunities that are open. By selecting 'In progress' displayed opportunities that were both open and in progress.
2) I don't see the toggle

**Comment by LisaLNelson** [comment]
Moving to ready to deploy - LN

**Comment by LisaLNelson** [comment]
Approved for closure. LN
