### ISSUE TITLE
Bug: Mobile - People page does not render properly

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1973]
The People page does not render properly on mobile.  
-  Can scroll from side to side and it’s all over the place.  

![1973](https://user-images.githubusercontent.com/18709918/37722880-6e02251e-2d03-11e8-8033-bb80eda6ef61.jpg)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
Mdumas - 03/28/2018 - In Testing....

**Comment by margaretdumas** [comment]
Testing completed..Mdumas

**Comment by LisaLNelson** [comment]
Ready to deploy LN

**Comment by LisaLNelson** [comment]
Approved for closure. LN
