### ISSUE TITLE
Post/Create Opportunity Needs "Cancel" Option

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1977]
Once you click to post an opportunity, you can save as a draft or submit, but not cancel it. There should be a cancel option in case you didn't mean to click that button/just wanted to see what was involved in setting up an open opp.

![image](https://user-images.githubusercontent.com/25315047/37729983-d9456140-2d14-11e8-960d-12b43df6631c.png)

Acceptance Criteria
Create/Post an Open Opportunity page has a "cancel" button.

**Comment by KatMullens-work** [comment]
Hi @jhanson12 : I don't see a cancel button/option. Where should I look? 

Thanks!
kat

**Comment by jhanson12** [comment]
It wasn't in test env yet...we needed to make sure that the admins were cleaned up first for the email tickets I worked on.

**Comment by Kibrahacha67** [comment]
4/3/18 LHammond in testing

**Comment by LisaLNelson** [comment]
Approved for closure LN
