### ISSUE TITLE
Landing Page (signed in): New page shell

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1992]
**User Story:** As a signed in Open Opportunities user, I want to see useful information on the landing page once I sign in.

**Acceptance Criteria:** 

**Page Structure:**

Heading:
Under the top navigation, there will be a bar that goes across full page and reads, "Participate in opportunities to gain experience, contribute your expertise and work with others across the Federal Government."  
- Under there will be a button to "Search opportunities" and "Create opportunity"

The new page structure will have 4 sections:
- Announcement
- Search opportunities by
- See other people like you
- Latest achievements

Each of the new sections listed above will be handled in its own ticket.  This ticket will create the new page shell/structure.

**Invision Mock**: https://invis.io/7MGOG75P3DK#/288669012_FAI1-Home

**Related Tickets**: 
- 2011: Landing page: announcement
- 2012: Landing page: search opportunities
- 2013: Landing page: See other people like you
- Latest achievements

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - In Testing...

**Comment by margaretdumas** [comment]
04/27/2018 - Mdumas - Passed testing...

**Comment by kbwagner** [comment]
4/30/18: KWagner - tested in IE, Chrome, and mobile Safari
@LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
Approved.
