### ISSUE TITLE
Opportunity Page updates 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1994]
**User Story**: As an opportunity creator, I want to view my opportunity in a clear manner.

**Acceptance Criteria**: 
The following changes will be made to the view opportunity page for the Opportunity Creator. The applicant's right side bar will remain the same and the left will reflect the new field names listed below.

Header:
- Change “Posted by Name” to “Name Posted on ##/##/##” to match the information on search results card
- Add a label of "Desired skills" above the skills tags that display in the header

Opportunity Body: 
The labels for the sections will now read: 
- Introduction
- What you'll do
- What you'll learn
- Who we are
- Related keywords 
-  If a field has no values entered, suppress the field label.

The following changes should be made to the blue information box within the opportunity:
- Target date will now be labeled "Due Date"
- Duty location will now be labeled "Location"
- Display Career field and Series in the blue box.  Suppress if not provided.
- No icons will display in the blue box

The following changes should be made to the right sidebar:
- Add a Search people button under the applicant section.  Selecting this button will take the user to the People page.

The profile avatar at the top should work as follows:
o	Display photo if available
o	If no photo, display initials
o	Initial color, will pick from one of the 5 colors until future  ticket 2134 is implemented
o	Will change with future ticket 2134

**Invision Mock**: Opportunity Page: https://invis.io/HJGOHLCA2X9#/288642426_FAI1-Opportunity

Related Tickets:
- 1995 - Create Opportunity page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
04/27/2018 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
04/27/2018 - Mdumas - Does not meet any new AC.  Please check to see if code was checked in. Moving back to development.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__NOTE:__ You may to to edit an existing opportunity or create a new one with all the data filled out as some parts of the page will __NOT__ display if the data does not exist. __Example:__ We will not show the section for "What you will learn" if this section was not filled in.

**Comment by margaretdumas** [comment]
05/07/2018 - Mdumas - In testing, moving back to development.
Does not meet all AC.  

- Search people is a link rather than a button (does not meet AC or mock)
- Due date format (does not meet 00/00/00 format in mock)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-8-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__Note:__ New AC in comment above

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing

**Comment by kbwagner** [comment]
5/14/18 - KWagner - Tested in Chrome ok.
Note: I missed writing add default text of "Leave comments here" so will add a new ticket for later.  Displayed in mock but not in AC.

@LisaLNelson ok to test.

**Comment by LisaLNelson** [comment]
approved
