### ISSUE TITLE
Opportunity Create/Submit updates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1995]
**User Story:** As a signed in Open Opportunities user, I want to be able to create a new opportunity with the following changes from the existing create opportunities page.

**Acceptance Criteria:**
Page Structure: two steps/sections
•	Step 1 (same as current design)
•	Step 2 (New with this design): Describe the opportunity

New order of the inputs under Step 1 should be as follows:

Bold Text for Sub-section: Who

Order and content of questions under the “Who” section:
First question: How many people do you need?
Response: Single select list with displayed option of –Select-. Other options are the same as the existing single select list for this question.

Add radio button: 
Label: Are you looking for someone in a specific career field?
Radio button options: Yes No (No is default)
If yes, an auto complete text field of career fields appears and allow the user to start typing then select a career field.  (Please see example: https://projects.invisionapp.com/share/K7GOVW12J9N#/screens/288883130_FAI1-Create-Selected )
If someone selects Career field “yes” and then selects “Acquisition” it will be an opportunity that displays on the Acquisition search page.

Add text box: 
Label: What skills are you looking for?
Text box: uses autocomplete for skills that users type

Bold Text for Sub-section: When

Add line of text: What is the time commitment?
Add three option buttons: One time, Ongoing, and Full time detail; button design for these can be found in the design.

When One time is selected:
-italicized text appears under the three buttons which reads: A one time task with a defined timeline 
-a checkbox with this text appears: Limit participation to (agency) employees
-Text: How many hours do you need? 
-Response: Single select list with displayed option of –Select-. Other options are the same as the existing single select list for this question.
-Text: What is the estimated due date?
-Response: A multi-select box with the -Select- option displayed that lets the opportunity creator select a date. 

When Ongoing is selected:
-Italicized text appears under the three buttons which reads: Requires up to 20% of a participant's work time until goal is reached 
-A checkbox with this text appears: Limit participation to (agency) employees
-Text: How many hours do you need? 
-Response: Single select list with displayed option of –Select-. Other options are the same as the existing single select list for the time needed question. Please ensure options are in order of smallest to largest numbers.
-Text: For how many weeks do you need this time?
-Response: Text box that allows user to put in number of hours in numbers only and that allows calculation to made based on that box (number of hours per week * number of weeks).

When Full time detail is selected:
-Italicized text appears under the three buttons which reads: Restricted to opportunity creator's agency. --A radio button appears which is selected and is labeled: Limit participation to (agency name) employees
-Text: How many hours do you need? 
-Response: Single select list with displayed option of –Select-. Other options are the same as the existing single select list for the time needed question. Please ensure options are in order of smallest to largest numbers.

Bold Text for Sub-section: Where
Add text and buttons: 
Label: Where can participants be located?
Buttons: Virtual, In person; button design for these can be found in the design.

_end of Step 1 section_

Order of the inputs under Step 2 should be as follows:
Label for section: Step 2- Describe the opportunity

Text in bold: Headline
Add text: Write a catchy, but descriptive title. Include a specific skill or outcome to entice participants to click on the opportunity.
Add text box with 100 character capacity.
Add text: Maximum of 100 characters

Text in bold: Introduction
Add text: Describe the opportunity. Include how their work will make an impact. Recommend 100 words or less.
Add text box with advanced editing capability (including formatting and links).

Text in bold: What you’ll do
Add text: List specific tasks the participant will work on. Be concise, but offer enough details so that the participant knows what’s involved
Add text box with advanced editing capability (including formatting and links).

Add three links with green plus sign icons in front of each:
See style in design. 
Text: Add What you’ll learn (optional)
Text: List the types of skills the participant will learn and other benefits.
Add text box with advanced editing capability (including formatting and links).

Text: Add Who we are (optional)
Text: Briefly describe your team, department or agency.
Add text box with advanced editing capability (including formatting and links).

Text: Add Related keywords (optional)
Text: List the keywords to help describe an opportunity.
Add autocomplete keywords box.

Three buttons at the bottom of page
Three buttons at the bottom of page
On non-preview (form) - left to right
Cancel (cancels the opportunity and deletes the contents) -> Save for later (saves the progress of the opportunity and goes back to the openopps.usajobs.gov/tasks page) -> Preview (previews the open opportunity on the next page. Does not save progress or generate an email)

On preview page (step 3) - left to right
Make changes (goes back to the edit page to allow the creator to edit the open opp) -> Save for later (saves the progress of the opportunity and goes back to the openopps.usajobs.gov/tasks page)  -> Submit (submits the open opp for consideration of admins and triggers email to creator regarding submitted open opp).

**InVision Mocks:** 

-https://invis.io/VEGOVW38NGU#/288404688_FAI1-Create (unselected view)
-https://invis.io/K7GOVW12J9N#/288883130_FAI1-Create-Selected (selected view)
-https://invis.io/6QGQ2CMKVE9#/289711427_FAI1-Create-Selected2 (full time detail selected view)

**Related Tickets:**
•	2034: Preview Page while Creating an Opportunity

**Comment by KatMullens-work** [comment]
Made these edits per discussion on 4/18: Create/Edit Opportunity  (Ticket 1995)
- Kat update ticket 
- Remove Acquisition question
- If someone selects Career field “yes” and then selects “Acquisition” it will be an opportunity that displays on the Acquisition search page

**Comment by bmcorum** [comment]
The 3rd button (Save & Preview (blue button)- Saves the work so far and goes to preview screen.) will submit the task for review until 2034 is completed.

@KatMullens-work will you approve this change?

**Comment by KatMullens-work** [comment]
Hi @bmcorum : as long as it all goes out in the same release and can be tested together, that's fine with me and approved. I'll test 1995 once 2034 is also complete. Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-26-18 LHammond in testing

**Comment by KatMullens-work** [comment]
Please see Slack conversation on 2034. Updates to bottom three buttons:

Three buttons at the bottom of page
On non-preview (form) - left to right
Cancel (cancels the opportunity and deletes the contents) -> Save for later (saves the progress of the opportunity and goes back to the openopps.usajobs.gov/tasks page) -> Preview (previews the open opportunity on the next page. Does not save progress or generate an email)

On preview page (step 3) - left to right
Make changes (goes back to the edit page to allow the creator to edit the open opp) -> Save for later (saves the progress of the opportunity and goes back to the openopps.usajobs.gov/tasks page)  -> Submit (submits the open opp for consideration of admins and triggers email to creator regarding submitted open opp).

**Comment by bmcorum** [comment]
- All drop down boxes missing the default "-Select-"
  ___Fixed___


- Career field auto complete doesn't work
  ___Only a single option so no autocomplete___


- Question - When I selected Acquisitions from the career field box, should the acquisitions page have loaded?
  ___No we do not currently ask any other Acquisition related questions___


- When the full time detail button is clicked, a grayed out "selected check box appeared for "Limit participation to employees". But when I selected another button, the Limit participation to employees" check box turned green and selected.
  ___Full time details are forced to "Limit participation". Other two options can be but do not require "Limited participation"___


- The "Limit participation to (agency) employees" is missing the agency.
  ___Fixed___

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

See comment above

**Comment by Kibrahacha67** [comment]
5-2-18 LHammond in testing

**Comment by kbwagner** [comment]
@KatMullens-work here is a comment on this ticket from @minchung12 What I had for my mockup vs. UAT are different. ‘Is this an Acquisition opportuinty’ is removed, which I like - but we should move Series below career field

**Comment by kbwagner** [comment]
@KatMullens-work another issue that should be addressed when this ticket is sent back is the following: Steps to Reproduce:
1) Create an opportunity
2) click on the Full Time Detail option under When
3) Click on One time or ongoing and now the Limit participation box is automatically checked. 
- Only happens once you have clicked on full time detail
- Also, the disabled checkbox should be a radio button and that’s what says in the ticket.
I created a bug but I can close it since this ticket hasn't been finalized yet.

**Comment by KatMullens-work** [comment]
Full time detail will not let me click on the Preview button to preview the opportunity in Chrome. Test failed. Please also see comments from Katrina and Min above. Expect we'll keep working on this one for the next few days!

**Comment by Kibrahacha67** [comment]
5-15-18 LHammond in testing

**Comment by bmcorum** [comment]
![image.png](https://images.zenhubusercontent.com/59e8ff8ea468affe6df75add/5b47d76e-7816-4389-a171-70654ccc5005)

**Comment by Kibrahacha67** [comment]
5-16-18 LHammond in testing

**Comment by KatMullens-work** [comment]
Failed in Chrome on Related Keyword (see 2034)

Passed in Safari for iPhone. Passed in IE.

**Comment by bmcorum** [comment]
@KatMullens-work see comment on #2034 this is NOT a failure in the application but a graceful error handling to a network connectivity issue.

**Comment by KatMullens-work** [comment]
In that case, this passes. Thanks @bmcorum and team! :)
