### ISSUE TITLE
People Page Revamp

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1996]
User Story: As an Open Opportunities user, I would like to have an updated people page to help me network.

Acceptance criteria:
The following changes should be made to the People page: NOTE: THIS WILL NEED TO BE BROKEN INTO SMALLER TICKETS

Header/Search:
- The header will appear in a blue bar
- The wording under the header will now read, "Find people who share similar skills or interests."
- The search bar will now have a title of "Keyword" with the magnifying glass.  The text inside of this box will read, "Find people by name, skill, agency, or location"
- There will be a search button beside the keyword field
- Pills will display for any keyword entered.  Each pill will have an "X" to remove
- A remove all link will display under the pills

Pagination for the People page is handled with ticket 2018.

Sort by: likely a new ticket.  Will need to determine the sort by values, default, and any type of formula if relevance is used.

People Page Card Display:
- <MIN - how many cards to display per page; we have said 25 but they are 3 across in this design.>
- Cards will display 3 across.
- The person's profile avatar will display.  A picture if available and initials otherwise.
- The person's name will display to the right of the avatar
- The person's title will display 
- <min - what is the next field that reads "Design"?>
- The person's agency will display
- The person's location will display
- The person's skills will display.  Up to 6 will display.  If there are more than 6 a "+#" will display (i.e. +4)

Invite to opportunity: 
- Within each card, there will be an Invite to Opportunity Link with an envelope icon. This will be handled by ticket 1998.

Filters: 
- On the right bar of the People page, the user will be able to filter on people by Skill, Agency, and Location.
- Skill - the filter bar will read, "Start typing to select a skill"
- Agency - the filter bar will read, "Start typing to select an agency"
- Location - the filter bar will read, "Start typing to select a location"
As any filter is added, a pill will be added under the search bar
Filters will work similar to the main search.  (Ticket X)

MIN - Things that were mentioned during design review but I'm not sure I see...were these for later?
o	Save a person
o	People you might be interested in based on your profile

Invision Mock: People Page: https://projects.invisionapp.com/d/main#/console/13386795/288408606/preview
New: 
https://opm.invisionapp.com/d/main#/console/13386795/286741743/preview

Related tickets: 
- Search filters

**Comment by abudz19** [comment]
@kbwagner There is a corresponding design ticket in OpenOppsTasks - https://github.com/openopps/OpenOppsTasks/issues/55

Do you want it closed, or will there be any additional work iterating on this page?

**Comment by Piglady64** [comment]
@abudz19  We will be working on People soon so I would leave the Task ticket as well if that is where you track what you need to do.

**Comment by kbwagner** [comment]
Look at what has been completed and hasn't been completed

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41523&_a=edit

**Comment by abudz19** [comment]
@eponsonby Since we are working this area right now, I went through and checked off everything I think we've already done. 

Possibility to discuss at next PBI grooming session:
- do we have tickets in TFS related to filters for people? do we still want filtering for people?
- shell ticket for invite to opportunity
- display of skills (do we want the functionality above, or keep it as is? how will this get impacted by the use of skills engine?)

**Comment by kbwagner** [comment]
7/13/20 - decided filters aren't needed
- have a separate ticket for invite to opportunity.
Closing
