### ISSUE TITLE
Profile: Invite to Opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1998]
User Story: As a <type of user>, ...

Acceptance Criteria: 
- - These changes will be made sitewide, not just for FAI
- will possibly open a modal - consider whether this will be a new ticket.

Invision mock: Profile Invite to Opportunity: https://projects.invisionapp.com/d/main#/console/13386795/287878182/preview

Related Tickets:

**Comment by kbwagner** [comment]
@abudz19 is there a mock that exists for this? The link no longer works.

**Comment by abudz19** [comment]
@kbwagner I've found the right prototype and looked through the sketch files, but I can't find a screen that matches the description. I do see several screens that have an "Invite to Opportunity" link on them, but none that show a modal design she was considering. Do you want me to make this a design ticket?

**Comment by kbwagner** [comment]
@abudz19 yes please go ahead and enter a design ticket but I'd say low priority.  But I do think this was part of the north star vision so good to figure out at some point

**Comment by nia-johnson** [comment]
Mock is not active and there are no requirements. Not moving to TFS.
