### ISSUE TITLE
Search: Keyword search bar

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2000]
**User Story:** As an Open Opportunities user, I would like to have enhanced search functionality in order to help me find what I'm looking for.

**Acceptance Criteria:**
- The following changes will be made to the Open Opps search page

A blue search bar will be added to the top of the page.  This bar will display for any search result with the exception of when "Acquisition" has been selected in which case the Acquisition search bar will display (ticket 2002)
- The blue bar header will read, "Search for opportunities"
- The next line will read, "Gain experience with hands-on training, share your expertise and work with others across the government."
- The next line will read, "Learn more about Open Opportunities" and an icon will display.  when selected, the Open Opportunities help will display in a new tab.
- The search bar will be titled Keywords and have a magnifying glass icon.  There will be no default text in the search bar.
- A search button will display to the right.

As long as at least one pill is displayed, a "Remove all filters" link will display.  When selected, all pills will be removed and all filters will be unchecked.

Keyword search will autocomplete (Ticket 2021)
Any word entered and selected via tab or search, will become a pill.  Filters will also become a pill.  Filters are covered by ticket 2022

Invision Mock: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
- 2022 - Search filters
-2021 - Search autocomplete
- 2002 - Acquisition specific search bar.

![graphic_search.svg](https://images.zenhubusercontent.com/59fb63728a75884b9085d569/0dcee056-d539-4ad2-ad6b-a318fd5af0c5)

**Comment by margaretdumas** [comment]
04/09/2018 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
04/10/2018 - Mdumas - Moving back to development.  Does not meet AC:

As long as at least one pill is displayed, a "Remove all filters" link will display. When selected, all pills will be removed and all filters will be unchecked.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-26-18 LHammond in testing

**Comment by kbwagner** [comment]
5/1/18: Moving back to development.
1) there should be no default text in the keyword field for now per AC
2) I'm checking with Min on the text discrepancy between the AC and the Mock and will let you know if that is something that needs to be modified (can be a new ticket if needed).  Might have changed after the ticket was writte.

**Comment by kbwagner** [comment]
5/3/18 - updated the AC to have the wording match the mock per above.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-8-18 LHammond in testing

**Comment by kbwagner** [comment]
5/8/18 - KWagner tested in Chrome and Mobile.  Ok.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
