### ISSUE TITLE
Acquisition specific search bar

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2002]
**User Story**: As an Open Opportunity participant searching for an Acquisition related opportunity, I want to be able to clearly identify that I am looking at a results page for acquisitions.

**Acceptance Criteria**:
Open Opportunities users will receive a special search bar when any of the following situations occur: 
o	They type in "Acquisition" in the keyword search 
o	They type in "Acquisition" in the career field 

The Acquisition search bar will display as follows:
- A blue bar ($color-primary-alt-darkest) will display with the header of Acquisition Open Opportunities
- The second line of text will read, "You're now viewing Acquisition opportunities only."
- The third line will read, "Gain experience with hands-on training, share your expertise and work with others across government."
- The next line reads, "Learn more about Open Opportunities" which will display an icon.  When selected, help will open in a new tab
- The search bar will have a header of Keywords with the magnifying glass icon
- There will be no placeholder text in the keyword field at this time.
- There will be a Search button.  
- There will be  "Remove all filters to see all opportunities" link below pills
- If "Remove all filters to see all opportunities" is clicked, the user will also be returned to the regular search page without the Acquisition header.

Pills:
- The "Acquisition" pill will display if the requirements to enter the Acquisition search page have been met.

This page should be responsive for mobile.

**Invision mock**: https://invis.io/WTGOIMWB6UZ#/288639696_FAI1_-_Search_Acq

Related tickets: 
- Tickets with FAI listed as the label.
- 2000 - Search updates

**Comment by kbwagner** [comment]
Moved the following two bullets to the Landing Page ticket:
o	They click "View opportunities" in the Acquisition teaser
o	Or they click on the Acquisition link from the landing page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by jhanson12** [comment]
"Remove all filters"  was added by another ticket.  Will the verbiage change just because it is an Acquisition? @kbwagner @Kibrahacha67 @minchung12

**Comment by kbwagner** [comment]
@jhanson12 Yes, for just the Acquisition search the link will say "Remove all filters to see all opportunities" which does match the mock and the AC.  It will work differently for the regular, non acquisition search.  (@minchung12 )
- But I do notice one issue in the AC, we decided we wouldn't do any default text in the keyword field for now.  Can you remove the "find opportunities by" default text?  If so, I can update the AC.  The mock is already updated.

**Comment by jhanson12** [comment]
Thank you!  Please update the AC to match the mock to remove the "find opportunities by" default text.

**Comment by kbwagner** [comment]
5/1/18 - KWagner - updated AC to remove:
- Placeholder inside the search text box will read “Find opportunities by ”
- Placeholder text will change as new filters are added.

Added: there will be no placeholder text at this time.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

See above comment for AC changes

**Comment by Kibrahacha67** [comment]
5-1-18 LHammond in testing

**Comment by kbwagner** [comment]
5/2/18 - Was able to test successfully in IE, Mobile, and Chrome.
@LisaLNelson ready for final approval

**Comment by LisaLNelson** [comment]
Approved.
