### ISSUE TITLE
Restrict view of Limit participation to agency opportunities.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2004]
User Story:
As an open opportunities seeker, if an opportunity is restricted to an agency I should only see the opportunity if I work in that agency.

Acceptance Criteria:
Limit participation should not display to people outside their agency

If an opportunity is restricted to an agency because the checkbox on Create an opportunity for "Limit participation to <agency> is checked on, only that agency or admins should be able to view those opportunities.  Note: If detail is selected, the checkbox is defaulted to "on".

Scenario 1: If the user is not logged in and an opportunity has the limit checkbox selected as on, opportunity will not show for anyone.  

Scenario 2: If the user is logged in, determine what agency the logged in user is with, if it matches the agency of the limited opportunity, then that opportunity will display in the search.  If the agency does not match, the opportunity will not display.  

Administrators (logged in) can see all opportunities regardless of agency.

************
Original Issue - This ticket has been repurposed for the view of full time detail.
Issue:
I created a new opportunity in UAT and checked the button before full-time detail-restricted to requestor's agency. I logged out and logged back in as a different agency and the detail showed in an agency different than the one I created it in which was a USDA account.  

![screen shot 2018-03-28 at 5 13 36 pm](https://user-images.githubusercontent.com/9039852/38056764-689df1ea-32ab-11e8-8faa-cc0522629f36.png)

Resolution:
1)  update the data to create child parent relationship between agency records
2_ Create rules for how and when to show "Full Time Details": 
Option 1 (easiest):  never show FTD (Full Time Details) if not logged in since we won't know your agency
Option 2 (Harder): - if logged in do we automatically show FTDs for your agency or only show when you set that filter?

**Comment by LisaLNelson** [comment]
I created the opportunity as lisa.clark@gsa.gov logged out and created an account under lisa.oyler@usda.gov and was able to see the opportunity and apply for it.

**Comment by LisaLNelson** [comment]
The Opportunity Detail: Manage the Popular USDA Farmers Market (USDA employees only) https://openopps.usajobs.gov/tasks/712 shows on my list of opportunities even though it is marked as Full-time detail - Restricted to requestor's agency.  Not sure if this is because I am viewing as an admin.

**Comment by bmcorum** [comment]
FTD - Full Time Detail

Questions to answer to build acceptance criteria
1. If not logged in do we hide FTDs since we won't know your agency? (Recommend only show if logged in)
2. If logged in do we automatically show FTDs for your agency or parent agency, or do we require you to apply the filter "Full Time Detail"?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-18 LHammond in testing

**Comment by kbwagner** [comment]
5/30/18 - KWagner tested in Chrome.  
- On my non admin account, changed my agency from OPM and could no longer see the OPM only opportunity
- On my admin account, changed my agency from OPM and could still see the OPM only opportunity (correct)
- Logged out, not able to see the OPM only opportunity

@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved
