### ISSUE TITLE
Landing Page (signed in): Announcement section

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2011]
**User Story:** As an Open Opportunities user, I would like to see announcements related to the product when I sign on.

**Acceptance Criteria:**
The signed in landing page will have a new section called "Announcements".  The shell of this page was created with ticket 1992.
- Content will be dynamic based on the information entered into the Announcement section on the Admin Dashboard.
- Limit the number of maximum characters to 700 for now. 
Note: If 2031 can't be done with this release, we can consider hard coding some text that will stay for the 8 week release.

Ticket 2031 adds the ability to create/edit/delete announcements to display via the admin dashboard.

**Invision Mock:** https://invis.io/7MGOG75P3DK#/288669012_FAI1-Home

**Related Tickets**: 
- 2031 - Admin Dashboard Announcement Section

**Comment by jhanson12** [comment]
We will need text for the first announcement.  Please add to AC.

**Comment by kbwagner** [comment]
@jhanson12 wouldn't we add the text to the admin ticket 2031 or would you want it here?  We'll work on language ASAP.  Thanks!

**Comment by jhanson12** [comment]
700 character limit as suggestion should work well.

**Comment by LisaLNelson** [comment]
OPM’s USAJOBS is proud to announce the launch of Acquisition Open Opportunities. Through a partnership with the Office of Federal Procurement Policy (OFPP), the existing Open Opportunities site will now include a portal for acquisition specific opportunities. Through skill sharing opportunities, acquisition personnel can learn new capabilities through hands-on/experiential training. Just search for opportunities by clicking on the “Acquisition” link under the “Career Field” label to get started today! 
 
Check out this video from Leslie Field, Acting Director of OFPP to learn more: https://youtu.be/H9TWk_Rn61E
 
Questions or feedback at: OpenOpps@usajobs.gov.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing
testing complete, in IE, Edge, Safari, and Chrome.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
5/9/18 - KWagner tested Chrome and mobile.  
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved
