### ISSUE TITLE
Landing Page (signed in): Search opportunities by

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2012]
**User story**:  As an Open Opportunities user, I would like to be able to search for opportunities by career field, skill, and location once I have signed into the system.

**Acceptance Criteria**:
- Ticket 1992 creates the shell for the new signed in landing page.
- In the new “Search opportunities by” section, the user will be able to search for opportunities by Career field, Skill, Location

Career field: 
 - Career field will always have one link underneath: Acquisition.  Acquisition will always display first.
- Additional links can display - up to 4 in total.  These fields will be displayed based on the Career Tag field for any opportunity with a status of "Open".  Tags can be randomly chosen with higher quantity tags displaying higher than lower quantity tags.
 - When one of the links is selected, the Open Opps search results page will display with any opportunity that has been tagged with the selected career field.
 - If the Acquisition link is selected, the Acquisition specific search header (blue) will display (Ticket #2002) and the acquisition pill will display.
 - The selected career field tag will display as a pill on the search results and will be displayed in the right hand filters.

Skill:
 - The skill section will display links up to 4 in total. These fields will be displayed based on the Skill Tag field for any opportunity with a status of "Open". 
 - These tags can be randomly selected based on the highest used tag displaying first and so on.  In case of a tie, randomly select any skill from an opportunity that is Open.
 - When one of the links is selected, the Open Opps search results page will display with any opportunity that has been tagged with the selected skill.
 - The selected skill tag will display as a pill on the search results and will be displayed in the right hand filters.

Location: 
 - The location section will display links up to 4 in total. These fields will be displayed based on the Location Tag field for any opportunity with a status of "Open". 
 - Virtual will always display first.
 -  The most popular location based on Open jobs will display first, followed by the second, etc.  In case of a tie, randomly select locations for any opportunity that is Open
 - When one of the links is selected, the Open Opps search results page will display with any opportunity that has been tagged with the selected location.
 - The selected tag will display as a pill on the search results and will be displayed in the right hand filters.

The search results page that is displayed when any of the links selected, will show the appropriate pills and appropriate filters checked based on the link.

At the bottom of the search by section, a button will display to "View all opportunities".  When selected, the search results page will display.

**Invision Mock**: https://invis.io/7MGOG75P3DK#/288669012_FAI1-Home

**Related Tickets**: 
- 2011: Landing page: announcement
- 2012: Landing page: search opportunities
- 2013: Landing page: See other people like you
- 1992: Landing page: shell

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing
Testing completed.  all worked execpt when the acquisition link on the home page was clicked, the application navigated to the search page, displayed the pill for Acquisitions, and the pill for open, but didn't display the search header for Acquisitions.  Below is a screen shot of the display.  Moving back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/29b01d91-242d-4d12-884e-0ce84975d83d)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing
passed testing moving to review.

**Comment by kbwagner** [comment]
5/14/18 - Kwagner - 
1) AC states that the location of Virtual should always display first and it does not
2) Career fields should display in order of use.  Initially it did display in order of user but then I added another career field for Architecture which was displaying 4th.  It still displays 4th even though it now has one more that production.  Logged out and logged back in, cleared cache, closed browser.  Still displays that way.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-15-18 LHammond in testing

**Comment by kbwagner** [comment]
5/15/18 - Looks good but minor thing.  Locations should only have 4 total...so Virtual and up to 3 other locations.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-16-18 LHammond in testing

**Comment by kbwagner** [comment]
5/16/18 - KWagner tested in Chrome.
Ready for final review.

**Comment by LisaLNelson** [comment]
approved
