### ISSUE TITLE
Landing Page (signed in): See other people like you

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2013]
**User Story**: As an Open Opportunities user, once I sign in I would like to see other people who share similar job title or agency in order to network.

**Acceptance Criteria**:
- Ticket 1992 creates the shell for the signed in landing page.
- Display up to 4 people: 2 people matching based on user’s title, and 2 people matching based on user’s agency
- For each person that is matched display:
    ⁃    Profile picture if available, initials if no picture
    ⁃    Name
    ⁃    Job title
    ⁃    Agency
- If there are less than 2 people to match for either job title or agency, suppress the last line.
- If there is no match a column, display “No match found. Update your profile or search manually” in the column. When ‘profile’ link is selected, the user will be taken to the Profile page. When ‘search manually’ link is selected, the user will be taken to the People page.
- If there is no match for either column, display the no match text in each column.

At the bottom of this section, there will be a "View all people" button.  When selected, the user will be taken to the People page.  

**Invision Mock**: https://invis.io/7MGOG75P3DK#/288669012_FAI1-Home

Screen Shot: 
![image](https://user-images.githubusercontent.com/18709918/38329795-dc03b0cc-381c-11e8-9222-7426028cd884.png)

**Related Tickets**: 
- 2011: Landing page: announcement
- 2012: Landing page: search opportunities
- 2013: Landing page: See other people like you
- 1992: Landing page: Shell

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-8-18 LHammond in testing...

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing
Testing Completed. Tested in Chrome, IE, Edge, Safari.  Screen shots below for different views:
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/fd213dc8-f139-4ba7-b8e9-ac1c40256013)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/938e9045-f110-4a85-abe1-596a24a269d9)

**Comment by kbwagner** [comment]
@jhanson12 - For this one Dywane Boyd showed up in my "Based on agency" match with a title of "Rascal".  I updated my job title to match "Rascal" and went back but he doesn't show up on my job title search.  I logged out and logged back in.  I would assume this search would bring him back if we have the same job title?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-14-18 LHammond in testing

**Comment by kbwagner** [comment]
5/15/18 - KWagner - Tested in Chrome and mobile Safari.  
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved.
