### ISSUE TITLE
Landing page (signed in): Suggested opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2014]
**User Story**: As an Open Opportunities user, I would like to see suggested opportunities to look at when I log into the site.

**Acceptance Criteria:** 
- Display 4 opportunities at the bottom based on the following criteria: Status = Open, 
- The card will display: Opportunity Headline, the first x characters of the description, and the keywords for the opportunity.
- What displays if there is less than 4 Opportunities open?

**Invision Mock:** https://projects.invisionapp.com/d/main#/console/13386795/288669012/preview

**Related Tickets**: 
- 2011: Landing page: announcement
- 2012: Landing page: search opportunities
- 2013: Landing page: See other people like you
- 2014: Landing page: Suggested opportunities
- 1992: Landing page: Shell

**Comment by kbwagner** [comment]
In order to match opportunities to your profile, you need to have skills.  Currently you need to have skills and interests together.  Opportunities just add tags in one place.  So we can't specific skills and opportunities.  Once these are separated out we could do this.

**Comment by kbwagner** [comment]
Look at North Star

**Comment by nia-johnson** [comment]
Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41522&_a=edit
