### ISSUE TITLE
Search Results: Sort by

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2016]
### Who
Open Opportunities seekers 

### What
Sort opportunities search results based on user specified criteria 

### Why
To help Open Opps seekers to find the right opportunity.

### Acceptance Criteria
- Add a Sort by field on the opportunity search results page above the opportunity cards.
- Sort by will be a dropdown.
- The sort values will be (listed alphabetically)
Options: , Title, Agency, Posted date, Posted by, Status, Location, Duration (Highest to Lowest, Lowest to Highest), 
- For each value list ascending or descending
- Add default sort - default will be posted date newest to oldest
### Related Tickets 
n/a

### Mocks
https://projects.invisionapp.com/d/main#/console/13386795/288642168/preview

**Comment by kbwagner** [comment]
4/4/18 - Decision to remove this ticket from FAI release but keep open for future discussion.  Copying Slack conversations to document:  I'm working on the sort by ticket 2016.  We need to decide what items we want to allow to sort.  These should be limited to things that displayo on the opportunity card.  Here's a link to look at: https://projects.invisionapp.com/d/main#/console/13386795/288642168/preview   Options for Sort by: Relevance (we will have to come up with a calculation for this so I might suggest this one get put into it's own ticket for down the road), Headline, Location, Duration, Effort (i.e. one time, ongoing), posted by, agency, status.  For each of these we then determine ascending, descending.  Preferences on which values to allow to sort by?
For reference: USAJOBS sorts by Relevance (default - and there is an algorithm in the elastic search), close date, open date, agency, department, location, job title, and salary all which display on the search card.

Kat Mullens [3:06 PM]
We should sort by hours if possible :slightly_smiling_face:

Katrina Wagner [3:07 PM]
replied to a thread:
We should sort by hours if possible :slightly_smiling_face:
Hours is called "Duration" but that's one issue is using the true field title vs what really makes sense.  Then again I need to confirm what the true titles are in the new design.  Haven't gotten that far.

Kat Mullens [3:08 PM]
Something like "hours to complete opportunity"
so if i have a couple hours I can easily find them

Katrina Wagner [3:39 PM]
replied to a thread:
We should sort by hours if possible :slightly_smiling_face:
Actually that field is called Effort (ongoing, one time).  Two separate fields.

Katrina Wagner [3:39 PM]
replied to a thread:
We should sort by hours if possible :slightly_smiling_face:
But I will say that I'm not sure I would understand what "effort" was.

Katrina Wagner [3:55 PM]
uploaded and commented on this image: image.png 
Ok, trying a different approach.  Here's a screen shot of the new create page fields so you can see how they are labeled.  What is the time commitment (one time, ongoing)?  How many hours do you need?  How often do you need this time?

Katrina Wagner [3:56 PM]
uploaded this image: Here is a screen shot of the opportunity card 

Katrina Wagner [3:56 PM]
Things to keep in mind: Sort by is a very small field and we should stick to one word when possible i.e. location.  Second we want to try to not introduce brand new titles for anything.
So how about sorting on Location, Agency, Status, Time, Hours, Duration (would probably order the list alphabetically)?  We could always add a question mark help or something to explain the sorts?    It might be nice to sort on some sort of date - either date posted (so I could see the newest) or estimated completion date...but we don't display any of that on the card.

Lisa Nelson [4:08 PM]
I'm really confused
Want to talk it through
703-798-3515

Katrina Wagner [4:08 PM]
Hah...yes I'll call you.

Brice Corum [4:09 PM]
@kbwagner and @lisalnelson my 2 cents. I think you are over complicating sort by

Lisa Nelson [4:10 PM]
:+1:

Brice Corum [4:11 PM]
Why would I sort by Agency? should this just be a filter?
Why would I sort by Location? should this just be a filter?
To be honest I would sort by created date and maybe needs to be completed by

Katrina Wagner [4:36 PM]
Ok...here's what Lisa and I discussed...add created date and estimated completion date to the card (@min) and then sort by will be just those two fields.  The rest of the fields are covered by filters.  Thanks team!

Min Chung [4:47 PM]
Do we then want to make estimated completeion date a required field?

Lisa Nelson [4:47 PM]
No
Becasue most are dependent on when it gets assigned.

Min Chung [4:53 PM]
Then the opps with completion date will show first and then the rest. I don’t know how helpful that will be if most of the creators don’t put in the date. We also talked about instead of having users put in an exact date, we can have options like ‘2months after assigning’.

Min Chung [5:05 PM]
I’ll include those two dates in the design and we can talk about the options for ‘completion date’ later.

Katrina Wagner [5:46 PM]
@min @lisalnelson - With more conversation, 1) Posted date would be good to show on the card 2) Estimated completion date can show on the card if we want but if not being used and not required may not be a big win 3) Sort by - with so many filters available to narrow down, we are going to keep the sort by ticket open, I will note all of the discussions here, but we won't do it with this release.  If sort by was down to posted date and estimated completion date and estimated completion date isn't required/used often...then we are down to a sort on posted by which is what the sort is now.   Let me know if anyone disagrees with this.  May be readdressed later after we see how filters work out and once we get a lot more opps open. @brice.corum

**Comment by kbwagner** [comment]
From 1916 (closed as duplicate): As a user, would like to sort the opportunity listing page by the following: date posted, estimated completion date, agency, etc.

Note: Add a sort by option on opportunity listing page (i.e. date posted, estimated completion date, agency, etc.) (multiple users suggested)

**Comment by kbwagner** [comment]
@nia-johnson Comments on this one:
- Add default sort - the sentence is there but not finished - default sort should be posted date newest to oldest
- Change headline to title
- Probably remove the note if it's old.  If we need to do a spike on relevance than it should be removed as an option for now, a spike added, and then another ticket to add relevance in as an additional sort value once it's figured out.  
- Posted date should also be a sort (reading through the old comments)

**Comment by nia-johnson** [comment]
Moving to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Atlas/_backlogs?level=Backlog%20items&showParents=false&_a=backlog
