### ISSUE TITLE
People: Add pagination

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2018]
User Story: As an Open Opportunities user, I would like to see pagination on the People page so I can easily move between pages.

Acceptance Criteria:
- Apply the design system for pagination: http://usajobs.github.io/design-system/search/#pagination
- Apply pagination to the people pages
- Pagination should display for desktop and mobile.

Pagination changes should include:
- Above the people list, display, "Viewing 1-10 of <total number> people"
- 10 people cards should display per page 
- Pagination will display at the bottom of the people list.
--The current page number will always be highlighted in the pagination bar.
--As soon as the user moves past page one, a Previous link displays.
--When the user is on the last page of results, next no longer displays.
--When in the inside set of pages, the current page is highlighted and both a next and previous display.
Mobile consideration: for the smaller screen size, Next and Previous will display (Note: Even on phone when turned sideways page numbers still display).

Invision Mock for pagination only: https://invis.io/KPGOERW46JB#/268475911_People

Related Tickets:
- 1661 - apply pagination to search page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19LHammond in testing

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Chrome/Test
Ready for final review.
