### ISSUE TITLE
Top Navigation: Include help

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2020]
**User Story**: As an Open Opportunities user, I would like to be able to access help from the menu bar.

**Acceptance Criteria**: 
The top navigation will be modified as follows: 
- The top navigation should be across the full page (doesn't display that way in Invision)
- The top navigation will now have the following menu items:  Signed in name, Help, and Search
- Help will open the help center in a new tab.  
- People and Create Opportunity will also display in the Menu under name. The order will be: Profile, People, Create Opportunity, Administration, Sign Out (Note: Create Opportunity is not reflected in the mock up.

Invision Mock: https://projects.invisionapp.com/share/7MGOG75P3DK#/screens/288669012_FAI1-Home

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-18 LHammond in testing

**Comment by kbwagner** [comment]
@jhanson12 the blue box goes slightly into the help column..is that to be expected?  
![image](https://user-images.githubusercontent.com/18709918/39309088-2a38deec-4935-11e8-8a09-71c35c11f851.png)

**Comment by kbwagner** [comment]
Sending back to development to fix issue in comment above for IE and Chrome.

**Comment by kbwagner** [comment]
On mobile - remove People from the Search navigation menu.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
(https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ac82a772-9e55-40f0-bb3f-d8dbef10eead)

**Comment by jhanson12** [comment]
Could you please verify the issue? If it is on the comment/screenshot added by @kbwagner, that is not an issue.

**Comment by kbwagner** [comment]
5/1/18 - Min confirmed that the header is displaying correctly per the design system: https://designsystem.digital.gov/components/headers/basic/

**Comment by Kibrahacha67** [comment]
Testing complete moving to review 5-1-18

**Comment by kbwagner** [comment]
5/1/18 - KWagner tested in IE, Chrome, Mobile.  Ok
@LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
Approved
