### ISSUE TITLE
Keyword autocomplete

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2021]
**User Story:** As an Open Opportunities user, I would like to have the system autocomplete my keywords to help me find matching opportunities.

**Acceptance Criteria:** 
- Keyword autocomplete will work on both the Acquisition and general searches
- When any Headline/Title, Agency, Skill, Topic or Description is entered, the system will start autocompleting in a dropdown for the user to select options.
- Autocomplete will start after the user types in 3 letters.
- The autocomplete dropdown willl display titles for each category (i.e. agency, skill) and will display up to 5 results for each category..
- If an autocomplete relates to a filter of Skill, Career field, Series, Time commitment, or  Location, the associated filter will be checked.
- Once a selection is made from the autocomplete, the item will be entered as a pill under the keywords box.  Each pill will have an "x" to remove the pill.
- As long as there is one pill active, there will be a "Remove all pills" link.
- removing a pill related to a filter will also uncheck the filter and refresh the search

Invision Mock: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets: 
- 2000 - Search keyword bar
- 2022- Filter

Related core tickets for reference: 
TFS 30977 -Title autocomplete
TFS 29817 - Keyword autocomplete

**Comment by kbwagner** [comment]
Should work like it does in USAJOBS and sort keywords by area.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41579&_a=edit
