### ISSUE TITLE
Search filters help

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2022]
User Story: As an Open Opportunities user, I would like to have the ability to view help information to help me understand the new filters.

Acceptance Criteria: 
Add a question mark to the Filters section of the search results page.
Once selected, the help will take the user to a new page.  URL is: https://usajobs.github.io/openopps-help/opportunity/search/

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skills Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing, however the link on the help center does not yet exist.

**Comment by Kibrahacha67** [comment]
On hold for testing until the link is ready.  Rest of the AC meets requirements.

**Comment by LisaLNelson** [comment]
approved
