### ISSUE TITLE
Mobile: Search page updates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2023]
**User Story:** As a mobile user, I want to be able to search for opportunities successfully via my mobile device.

**Acceptance Criteria:**
•	Search pages (general and Acquisition) need a sticky tab for Filters (Similar to Core)

**Invision Mock:** https://invis.io/3TGRST0X7HG#/290223221_FAI2-Search-Mobile

Note: Removed Sort option since Sort by isn't going through right now.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-18 LHammond in Testing

**Comment by kbwagner** [comment]
4/25/18 - moving back to development per Margaret.

**Comment by margaretdumas** [comment]
Mdumas - Cannot view opportunities on mobile when applying filters even when it shows that there are 59 opportunities.  

Steps to repro:
1.  Open filter automatically added
2.  Add "virtual "  Shows 2 filters but when I select "View Results
There are 52 opportunities found but they are not displayed

Moving back to development

**Comment by jhanson12** [comment]
This is a data issue with initials and not code.  Initials are used on the cards and is not part of this ticket. Moving back to testing.

**Comment by margaretdumas** [comment]
05/02/2018 - Mdumas- Meets AC...Moving to review.

**Comment by kbwagner** [comment]
5/3/18 - KWagner - Filter number isn't updated correctly.  I have a filter of Open, Acquisition (Career field), Time commitment of Full time detail, and location of Virtual and In person so I should have 5.  I click view results and the filter number shows 2.  
- Also, for some reason I almost always have to click "View Results" twice.  Sometimes I have to click filter two or three times after I've scrolled around a bit to get that page to open.  I'm on my iPhone.  Seems to work if I don't scroll before I click.

@jhanson12 Is the filter count issue possibly because some of the filters are still being worked?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-8-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing

**Comment by kbwagner** [comment]
@jhanson12 and @bmcorum Question
- When I select the checkbox for Restrict to OPM, it does not update the filter count.  I would assume it should?
- I'm still having the issue where sometimes after I scroll on the page, I have to click "Filter" 2 or 3 times to get it to engage.  Has also happened sometimes on View results.  I'll have someone else test this tomorrow to compare.

**Comment by jhanson12** [comment]
I tested issue number 2, scrolling issue on iphone.  Because the Filter button is at the bottom of the page, you will notice that browser goes from full page view, to seeing the controls, ie back and forward, add a page, etc.  This is a touch point on the iphone which we cannot control...and would not want to.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-15-18 LHammond in testing

**Comment by kbwagner** [comment]
5/15/18 - KWagner - tested in mobile Safari.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
