### ISSUE TITLE
Profile Page: Add Career Field

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2026]
**User Story:** As an Open Opportunities user, I would like to add my career field to my profile in order to help me find opportunity matches in my field.  

**Acceptance Criteria:** 
- Add career field to profile and edit profile
- Career field will display under the job title in the current design
- Display "-Career field-" for existing users until they update their profile. 
- Remove icon for title and career field

**Invision Mocks:** https://invis.io/ZNGOOM7WBMJ#/289256724_FAI1-Profile_Career

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-1-18 LHammond in testing

**Comment by kbwagner** [comment]
5/2/18 - Unable to save profile right now in Chrome.  I have cleared cache.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
05/07/2018 - Mdumas - Retesting...

**Comment by margaretdumas** [comment]
Mdumas - Testing good...moving to review

**Comment by kbwagner** [comment]
5/7/18 - Kwagner tested in Chrome and mobile.  
@LisaLNelson  ready for final review.

**Comment by LisaLNelson** [comment]
Why do we show carrier field on the profile if someone hasn't added it?
![screen shot 2018-05-07 at 8 27 01 pm](https://user-images.githubusercontent.com/9039852/39731380-55f6e1ce-5235-11e8-8b90-c607d28c554e.png)

**Comment by jhanson12** [comment]
The AC states "Display "-Career field-" for existing users until they update their profile."  which was approved on April 4th.  An approved AC needs to go through the planning/development/testing cycle.  If it needs to be changed, then a new ticket will need to be created with the new requirements and go through the cycle again for refactor.

**Comment by LisaLNelson** [comment]
Ok.  I somehow spaced on this.  I will add it as a new issue and approve it for now.

**Comment by kbwagner** [comment]
2121 has been added to remove the default career field label from profile.
