### ISSUE TITLE
Password Reset Form Can Be Submitted Multiple Times 

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2028]
The password reset form can be submitted many times causing emails to be sent each time.  

Recommend only allowing the form to be submitted once.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

If the form returns an error you should see the error an be able to resubmit the form. If the form submits successfully it should disappear and not allow you to submit again without reloading that page and clicking the "forgot password" link.

**Comment by kbwagner** [comment]
Steps to reproduce:
Katrina testing 4/9/18: 
1) From sign in, select forgot password link
2) Enter email address and click send email button.  (for some reason I have to select the send  email button twice)  Button is grayed out.  After a delay, I get an alert.  I can't actually get into my email right now so will try that in a  bit.  But I can click sign in again and start the process all over.

**Comment by LisaLNelson** [comment]
Approved
