### ISSUE TITLE
Landing Page (Signed in): Latest Achievements

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2029]
**User Story:** As an Open Opportunities user, I want to be able to see the latest achievements when I sign into the system.

**Acceptance Criteria:**
The following changes should be made to the Latest Achievements section of the signed in landing page:
- Limit 6 achievements to display
- Achievements will now display on the right bar of the page
- Badges will no longer display in the list
- Separating lines will display between each achievement.
- Profile icons:
o	Display photo if available
o	If no photo, display initials
o	Initial color, will pick from one of the 5 colors until future ticket 2134 is implemented
o	Will change with future ticket 2132
- Alternating color palate: 
will be alternating colors: Bg $color-secondary-lightest (#f9dede)
Text $color-secondary-darkest (#981b1e)

Bg $color-cool-blue-lightest (#dce4ef)
Text $color-cool-blue (#205493)

Bg $color-green-lightest (#e7f4e4)
Text $color-gray (#5b616b)

Bg $color-primary-alt-lightest (#e1f3f8)
Text $color-primary-alt-darkest (#046b99)

Bg $color-gold-lightest (#fff1d2)
Text $color-gray (#5b616b) 

Screen Shot 2018-04-23 at 2.18.01 PM.png 
![image](https://user-images.githubusercontent.com/18709918/39130339-d14e5390-46da-11e8-99d2-0d8a87bf4972.png)

**Invision Mock:**https://invis.io/7MGOG75P3DK#/288669012_FAI1-Home

**Comment by Kibrahacha67** [comment]
5-8-18 LHammond in testing

**Comment by kbwagner** [comment]
5/8/18 - KWagner tested in chrome and IE.
Icons are not alternating in color.

**Comment by jhanson12** [comment]
![randominitialsie](https://user-images.githubusercontent.com/15199629/39780659-ff04d316-52da-11e8-89d7-cb9cd1d8b08b.png)

The icons are random, but sometimes the random does not look random.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
5/9/18 KWagner - Clarification on AC from discussions on Profile Picture/Initials this morning: 
•	2029 – Landing page achievements
o	Display photo if available
o	If no photo, display initials
o	Initial color, will pick from one of the 5 colors until new ticket is implemented
o	Will change with future ticket

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing
Test completed in ie, edge, safari and chrome.

**Comment by LisaLNelson** [comment]
approved
