### ISSUE TITLE
Admin: Ability to manage Announcement text

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2031]
User Story: As an administrator, I want to be able to enter announcement information in my dashboard in order to be able to share updated news with users.

Acceptance Criteria: 
- Add a new section on the Admin Dashboard to update/add/delete the text that will display on the landing page. 
- This will allow content to be changed by the system administrator (not agency admin) outside of a release cycle.
- The field size for this should be <<insert field size >>  Dev - can you give us a recommendation on how long we can make this field based on the size on the page.
- For now, at a minimum we would want to add text, bold, and URLs to this field.  At this time, we don't need to add pictures, videos, etc. but may want to do this down the road.
Invision Mock: https://projects.invisionapp.com/d/main#/console/13386795/288669012/preview

Related Tickets:
- 2011 - Landing page - Announcement Section
- 1992- Landing Page - Shell

**Comment by bmcorum** [comment]
@kbwagner and @LisaLNelson 

1. Do you just want a single text area that allows you to enter what displays in that section?

OR

2. Do you want to be able to schedule announcements (start/end date)? (You could now display multiple announcements)

**Comment by kbwagner** [comment]
@bmcorum - for now we're going to go with option 1 and keep it simple.  Thanks.

**Comment by Kibrahacha67** [comment]
5-25-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. Agency admins __should not__ see the _Announcement_ tab in the admin dashboard.

**Comment by Kibrahacha67** [comment]
5-30-18 LHammond in testing

**Comment by kbwagner** [comment]
![annoucement](https://user-images.githubusercontent.com/18709918/40744761-936f6062-6423-11e8-86ca-e3e9087018d2.png)

Not moving back til I ask the questions to be sure...
@bmcorum 
Question on the admin announcement for mobile.  
1) The make and save buttons are on top of each other.  Can they be spaced out and 
2) Announcement title on mobile...is there a way to scroll right to get to the end of the field?  i can on desktop but not sure how to do that on mobile - if it's a trick I don't know or a field setting we need to put in?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

Title is now a textarea rather than a textbox

**Comment by Kibrahacha67** [comment]
6-1-18 LHammond in testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
6/7/18 - KWagner tested in Chrome and mobile Safari
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved.
