### ISSUE TITLE
Search: Find People Box

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2033]
**User story:**As an Open Opportunities user, I would like to have a clear way to create an opportunity and find people from the search page.

**Acceptance Criteria:**
- On the search page for Acquisitions and general, a light blue box will display to the right of the keyword search box.
- The title will be, "Find people to help you complete your next project."
- The next line will read, "Anyone can create an opportunity.  Learn how."  Learn how will be a link to the help center that will open in a new tab. https://usajobs.github.io/openopps-help/opportunity/
- There will be a Create Opportunity button that will take the user to the Create Opportunity screens
- Text will read, "Connect with people who share similar skills or invite someone to apply to your opportunity.".  This will be followed by the people icon and a "Search people" link.  This link will take the user to the People page.

**Invision Mock:** https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

**Related Tickets:**
2000 - Search keyword
2021 - Search autocomplete
2022 - Search Filters
2063 - This ticket will add the Create Opportunity button for logged out users.

**Comment by LisaLNelson** [comment]
![screen shot 2018-04-04 at 11 30 46 pm](https://user-images.githubusercontent.com/9039852/38346006-567113f2-3860-11e8-8a77-3cc5ac1b1759.png)

As I look at this box I think we may need to rearrange things.

**Comment by Kibrahacha67** [comment]
4/10/18 LHammond in testing

**Comment by raywilliams** [comment]
@kbwagner 

1. Was the button missing when you were logged in? The Create opportunity button is only there when you're logged in. I didn't change the current functionality.

1. That can be changed to take you to the People page once you're signed in.

**Comment by kbwagner** [comment]
@raywilliams - nope I wasn't logged and yes I do see it when I'm logged in.  But that brings up the question that if I'm not logged in should I really see the People link either?  Should they work the same?  I'm chatting with Lisa and Brice now. Stay tuned.

**Comment by kbwagner** [comment]
@raywilliams - I'm going to create a new ticket that will ask for Create Opportunity to display regardless of signed in or signed out.  If clicked when signed out, it will take you to login and then to create page.

Should I add the People navigation to that ticket? (#2 above)

**Comment by kbwagner** [comment]
@raywilliams  - I'll add the people navigation to the new ticket. 
@LisaLNelson - ready for you to review.

**Comment by LisaLNelson** [comment]
Good to close
