### ISSUE TITLE
Preview Page while Creating an Opportunity

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2034]
**User story:** As an Open Opps user, I want to preview my new Open Opportunity that I just created before submitting or saving it.

**Acceptance Criteria:**
The screen appears as follows:

Title of screen in blue bold: 
Create an opportunity

Blue box with the following elements/text:
 - Text: First time creating an opportunity? Read our 10 tips for creating an ideal opportunity.
 - Link: This text <10 tips for creating an ideal opportunity> links to this page: https://usajobs.github.io/openopps-help/getting-started/top-10-tips/

Subheading in blue:
 - Text: Step 3- Review draft and submit
 - Insert dividing line

Preview of the opportunity

Blue (medium blue) box
 - Six headings in this box are arranged in two columns and the box is below Related keywords and tags
Text: Personnel needed
<list selected value>

Text: Time commitment
<list selected value>

Text: Due date
<list selected value>

Text: Location
<list selected value>

Text: Series
<list selected value>

Text: Career field
<list selected value>

Behaviors for this box:
• Suppress if not provided
• Remove all icons for blue box

Blue box to the right of screen, next to Who/where/when display box:
Text: <Bold>What happens next?
Text: Once you submit your opportunity, we’ll review it. We’ll email you within <bold> two business days </bold> with recommended edits or approval.
Insert empty line
Text: Read our step-by-step process to learn more about creating an opportunity.
Link: This text < step-by-step process > links to this page: https://usajobs.github.io/openopps-help/opportunity/

Three buttons at the bottom of page
On non-preview (form) - left to right
Cancel (cancels the opportunity and deletes the contents) -> Save for later (saves the progress of the opportunity and goes back to the openopps.usajobs.gov/tasks page) -> Preview (previews the open opportunity on the next page. Does not save progress or generate an email)

On preview page (step 3) - left to right
Make changes (goes back to the edit page to allow the creator to edit the open opp) -> Save for later (saves the progress of the opportunity and goes back to the openopps.usajobs.gov/tasks page)  -> Submit (submits the open opp for consideration of admins and triggers email to creator regarding submitted open opp).

**InVision Mock:** https://invis.io/N8GOVJSJGZT#/288641544_FAI1-Create2

**Related tickets:**

- 1995: Opportunity Create/Submit updates

**Comment by KatMullens-work** [comment]
Updating based on this Slack: 
Brice Corum [4:19 PM]
I have a question/concern related to https://github.com/openopps/openopps-platform/issues/2034
KatMullens-work
#2034 Preview Page while Creating an Opportunity
*User story:* As an Open Opps user, I want to preview my new Open Opportunity that I just created before submitting or saving it.

*Acceptance Criteria:*  
The screen appears as follows:

Title of screen in blue bold:  
Create an opportunity

Blue box with the following elements/text:

• Text: First time creating an opportunity? Read our 10 tips for creating an ideal opportunity.
• Link: This text <10 tips for creating an ideal opportunity> links to this page: https://usajobs.github.io/openopps-help/getting-started/top-10-tips/

Subheading in blue:

• Text: Step 3- Review draft and submit
• Insert dividing line

Preview of the opportunity

Blue (medium blue) box

• Four headings in this box are arranged in two co… Show more
Assignees
bmcorum, KatMullens-work
Labels
Approved, FAI, Opportunity Create, Requirements Ready
openopps/openopps-platformApr 4thAdded by GitHub

I feel as though we are adding complexity and an additional step for no added value. I would prefer at best to change the "Save & Preview" button to just say "Preview" and not include any save functionality (edited)

Lisa Nelson [4:22 PM]
I agree.  That is fine.  We can always expand later if need be. Katrina any thoughts?

Brice Corum [4:24 PM]
@lisalnelson to change the button/functionality or to backlog this ticket and revisit it?

Lisa Nelson [4:24 PM]
I like the just preview.

Brice Corum [4:25 PM]
Okay just checking
It matches better with the user story anyways which reads, "As an Open Opps user, I want to preview my new Open Opportunity that I just created before submitting or saving it."

Lisa Nelson [4:25 PM]
I see no reaso to backlog the ticket.  Just if we hear from users that the save is desireable we can always revisit.

Brice Corum [4:25 PM]
note the "before submitting or saving it"
the "Save for later" button is next to the "Preview"
So you would have a save option

Lisa Nelson [4:28 PM]
So when someone is previewing their draft they then have to save as draft

Brice Corum [4:28 PM]
"Save for later" would save as draft, when previewing the last button would change to "Submit"
which would submit the opportunity for approval

Lisa Nelson [4:30 PM]
So you would have the same 2 buttons we currently and a preview?

Lisa Nelson [4:31 PM]
uploaded and commented on this image: Screen Shot 2018-04-26 at 4.30.42 PM.png 

Min's moc

Brice Corum [4:31 PM]
Yes-ish....

On non-preview (form) - left to right
Cancel -> Save for Later -> Preview

On preview page (step 3) - left to right
Edit -> Save for later -> Submit
May edit should say "Make changes"?
"Edit draft" could be misleading when I am editing my submitted task or even my open task

Lisa Nelson [4:34 PM]
where is preview going?

Brice Corum [4:35 PM]
Step 1 and 2 (Edit Mode) would show Preview where Submit is and on Step 3 (Preview Mode) it shows Submit

Brice Corum [4:35 PM]
uploaded and commented on this image: image.png 

Edit Mode

Brice Corum [4:36 PM]
Expect just say "Preview"

Lisa Nelson [4:36 PM]
Preview is fine

Brice Corum [4:36 PM]
uploaded and commented on this image: image.png 

Preview Mode
"Make Changes" instead of "Edit Draft"

Lisa Nelson [4:36 PM]
Isee what you're saying

Katrina Wagner [4:37 PM]
Ack I know Min had really specific reasons for wanting to have those buttons. But yes I see what you’re saying. I thought there was a reason it needed to save before it could be previewed? Maybe how it would display on profile or something. I’m trying to remember

Brice Corum [4:38 PM]
Issue is emails are tied to saving so if we save every time we preview we would end up sending emails otherwise we have to change the logic behind when to send the email
plus the form already would include all the data I need to render a preview no need to send a data request across the internet to preview the data I already have on the user's machine

Lisa Nelson [4:40 PM]
Makes sense to me

Katrina Wagner [4:40 PM]
I get it. It’s fine by me. @katmullens can you update that ticket please since it’s yours? Thanks!

Lisa Nelson [4:40 PM]
We definitely don't want all those emails going out! (edited)

Brice Corum [4:41 PM]
Probably need to update 1995 and 2034
1995 also talks about the 3 buttons

**Comment by KatMullens-work** [comment]
Changes made to ticket based on the above conversation:

Three buttons at the bottom of page
On non-preview (form) - left to right
Cancel -> Save for later -> Preview

On preview page (step 3) - left to right
Make changes -> Save for later -> Submit

Step 1 and 2 (Edit Mode) would show Preview where Submit is and on Step 3 (Preview Mode) it shows Submit

The information is not saved by preview and an email (based on the save) is not triggered by the preview page UNLESS the opportunity is submitted.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

See above comment for AC change related to buttons on bottom of page.

**Comment by Kibrahacha67** [comment]
5-1-18 LHammond in testing

**Comment by kbwagner** [comment]
@KatMullens-work - we'll need to add career field and series to the blue box on the preview page like we did the opportunity page itself (from Slack discussion this morning) Didn't catch it until now.  Leaving here so you can test and see if there is anything else in addition to the above.  Here are the changes we requested in 1994 for opportunity page that need to be applied here as well: Display career field and series in blue box
•    Suppress if not provided
•    Remove all icons for blue box

**Comment by KatMullens-work** [comment]
Updated original ticket to reflect:

Blue (medium blue) box
 - Six headings in this box are arranged in two columns and the box is below Related keywords and tags
Text: Personnel needed
<list selected value>

Text: Time commitment
<list selected value>

Text: Due date
<list selected value>

Text: Location
<list selected value>

Text: Series
<list selected value>

Text: Career field
<list selected value>

Behaviors for this box:
• Suppress if not provided
• Remove all icons for blue box

**Comment by KatMullens-work** [comment]
Due date is not suppressed on Chrome when there is not a value listed.

**Comment by bmcorum** [comment]
@Kibrahacha67 that is because the column next to it takes up more room. That spacing is accurate because it matching row partner takes up more height.

**Comment by Kibrahacha67** [comment]
Testing complete, moving to review.

**Comment by KatMullens-work** [comment]
Passes in IE.
Loading failed on keyword in Chrome.
![image](https://user-images.githubusercontent.com/25315047/40160972-51bebccc-597d-11e8-9dff-7ea0aaff46b1.png)

Should "team" be capitalized given our capitalization rules?

![image](https://user-images.githubusercontent.com/25315047/40161012-703760e6-597d-11e8-8e22-e0ad20df8677.png)

Passes on Safari on iPhone.

**Comment by bmcorum** [comment]
@KatMullens-work the loading failure message means you encountered a network connectivity issue. That error message means the application handled the network issue gracefully. As far as the capitalization that is in the database prior or OPM taking ownership of the application.

**Comment by KatMullens-work** [comment]
Then it passes :) Those were the errors I found. Thanks, team!
