### ISSUE TITLE
Opportunity Card

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2035]
**User Story:** As an open opportunities seeker, I would like to see basic information about the opportunity on the search results page to gauge whether I want to read more.

**Acceptance Criteria:**
The following changes should be made to the Opportunity Card:
- Display the Headline 
- Display 4 lines of the opportunity description
- In one line, display Location, Hours, and Time committment (one time/ongoing)
- Display pills associated to skills 
- Display Career field – will work like related keywords and if clicked will create a new search with career field as a filter
- Display Series - will work like related keywords and if clicked will create a new search with series field as a filter
- Display related keyword: x, y, z.  These will be links.  When selected, they will change the search to a search for that keyword.
- At the bottom of the card, the Avatar associated to the Opportunity creator will display.  If no photo is available, their initials will display.
o	Display photo if available
o	If no photo, display initials
o	Initial color, will pick from one of the 5 colors below until a future ticket 2134 is implemented

-  To the right of the avatar, the creator's name will display with their agency in parenthesis after the name
- Underneath the creator's name, display "Posted on 00/00/00"

- On the bottom right, the status pill will display
- Screen shot below 

Colors for the initial icons (will change with a future ticket 2134):
- Initial icons for the opportunity creator should be alternating colors: Bg $color-secondary-lightest (#f9dede)
Text $color-secondary-darkest (#981b1e)

Bg $color-cool-blue-lightest (#dce4ef)
Text $color-cool-blue (#205493)

Bg $color-green-lightest (#e7f4e4)
Text $color-gray (#5b616b)

Bg $color-primary-alt-lightest (#e1f3f8)
Text $color-primary-alt-darkest (#046b99)

Bg $color-gold-lightest (#fff1d2)
Text $color-gray (#5b616b) 

**InVision Mock:**  https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search  NOTE: This mock does not include the display of career field and series.  See attached screen shot for the display of those two fields.

**Related Tickets:**
- 2000 -  Search Page
- 2021 - Keyword Autocomplete
- 2022 - Filters

![image](https://user-images.githubusercontent.com/18709918/39130261-a3530198-46da-11e8-9186-1b5e1dc51366.png)

**Comment by jhanson12** [comment]
I have fixed the color for the initials while working on the Landing page Achievement section ticket. (Not yet in testing.)

**Comment by Kibrahacha67** [comment]
5-8-18 LHammond in testing

**Comment by kbwagner** [comment]
5/9/18 - Updating the AC per conversation with Brice, Min, Katrina and approval to send back to dev per Brice.  Changes made due to issues with related keywords.

•	If career and series are supplied display, suppress if not supplied
•	Order of display: 
o	Career field – will work like related keywords and if clicked will create a new search with career field as a filter
o	Series - will work like related keywords and if clicked will create a new search with career field as a filter
o	Related - will work like related keywords and if clicked will create a new search with career field as a filter
•	No icons for these three fields on the card
•	Profile Avatar: 
o	Display photo if available
o	If no photo, display initials
o	Initial color, will pick from one of the 5 colors until a future ticket is implemented
o	Will change with future ticket

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 I finally gotcha! HAHA! You are in an agency that we do not have an abbreviation for.

**Comment by Kibrahacha67** [comment]
Testing complete. moving to review...

**Comment by kbwagner** [comment]
@bmcorum @raywilliams 5/9/18 - KWagner testing - Chrome - UAT, for some reason I can't click on the series or career field links in the second column of search results.  In the screen shot I can click on career field and series for the Industry day opp but not the Do you want to... opportunity.  The second column doesn't give me the hover over finger pointer either.  
- Same issue occurs in mobile.  
- I opened the opportunity and saved it again but didn't change.  

- Also, notice the second opportunity also has location, hours and duration on two lines..assuming it's just going to go to two lines for longer locations based on screen size?  

![image](https://user-images.githubusercontent.com/18709918/39844124-6c732dd0-53bc-11e8-98c7-e719b3ac2720.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-14-18 LHammond in testing

**Comment by kbwagner** [comment]
5/15/18 - KWagner - tested in Chrome and mobile.  Ok.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
