### ISSUE TITLE
Acquisition Teaser: Explore opportunities in acquisition box (on Open Opps Search Results page)

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2036]
**User story:** As an Open Opportunities user, I want to be reminded that there are acquisitions opportunities to explore on the platform.

**Acceptance Criteria:**
the following elements appear under the following conditions:

When does this appear?
- When a user searches for terms that are related to Acquisitions.
- When a user visits the page for the first time.

When does it NOT appear?
-When there are zero Acquisitions Open Opps.

What appears?
http://usajobs.github.io/design-system/search/#teasers
Box in roughly the middle section of the FIRST search results page, but not subsequent ones. 
Only shows if there are acquisition opportunities that are accepting applicants.
Text: Explore opportunities in acquisition. "View opportunities" button
Add white-bordered button.
Text: View opportunities

Add graphic on the right-hand side of the box (see in mockup).

When a user selects this teaser link, they will be taken to the search page for acquisitions and the acquisition pill will display.

**InVision Mock:**  https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related tickets: 

![graphic_teaser.svg](https://images.zenhubusercontent.com/59fb63728a75884b9085d569/499a3bae-d448-4519-ae23-04674994396f)

**Comment by kbwagner** [comment]
@kbwagner to check with Lisa to see if this is still needed

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41578&_a=edit
