### ISSUE TITLE
Green Open button 

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2037]
The green Open button on each opportunity card should open the full opportunity when someone clicks on it.  It is intuitive.

**Comment by kbwagner** [comment]
@LisaLNelson - it won't always be a Green open though.  It might be a red cancel, or a Draft, or a Completed.

**Comment by jhanson12** [comment]
@LisaLNelson  - the green/red/yellow/grey/navy/blue which represents the open/canceled/in progress/draft/submitted/completed are status pills, not buttons per the design system requirements.

**Comment by LisaLNelson** [comment]
Approved for closure. LN
