### ISSUE TITLE
Keyword Filters Needed

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2046]
**User Story:** As a user, I'd like to refine my Open Opportunities search by keywords and other information that opportunity creators have entered.

**Acceptance Criteria:**
Overall notes on filters in this ticket (search filters are the filters created based on keywords that the user enters in the keyword box at the top of the page after the user clicks the Search button):
• These will be applied across the site not just for FAI

Keyword filters:
As a keyword is entered and autocompleted, it an item is entered/selected, will add a pill to the top center of the page beneath Keywords and be removed from the Keywords box

Link to InVision mockup: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skills Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__NOTE:__ Only related keywords that have been entered up opportunity creators are available for keyword autocomplete with this ticket. There is another ticket on the backlog for additional autocomplete options.

**Comment by Kibrahacha67** [comment]
5-30-18 LHammond in testing

**Comment by kbwagner** [comment]
5/30/18 - KWagner tested in chrome and mobile Safari.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
