### ISSUE TITLE
Status Filter Needed

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2047]
**User Story:** As a user, I'd like to refine my Open Opportunities search by keywords and other information that opportunity creators have entered.

**Acceptance Criteria:**
Notes on Status filters, displayed on the right-hand side of the screen under the word "Status"
• Filters displayed are for general users. Admins will still see additional values.
• Filters will now have a question mark help that will link to the help center
• These will be applied across the site not just for FAI

Filter name/Text: Status
o Help icon/word link to Status filter help content. *****Content team Needs to create help content to link to (put Trello card in to request Help Center content for Status filters)
o Remove Canceled filter for general users only. Admin will still see Canceled filter.
o General users see these statuses only: Open, In Progress, Completed. Admins see all currently existing filters.
o This filter has a select all option which selects all options. Once "select all" is chosen, a "deselect all" option become visible to allow the user to deselect all of the options.

Link to InVision mockup: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skills Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by Kibrahacha67** [comment]
4-25-18 LHammond in testing
passed testing

**Comment by KatMullens-work** [comment]
Can't open OpenOpps.UAT.usajobs.gov in IE to test this ticket.  Is there an additional step?

**Comment by KatMullens-work** [comment]
Passed admin testing in Chrome. Need to do regular user testing in IE.

**Comment by KatMullens-work** [comment]
Passed user testing in mobile (iPhone) and IE on laptop. @LisaLNelson : this ticket passes testing.

**Comment by KatMullens-work** [comment]
Thanks, Team! :)
