### ISSUE TITLE
Skill Filter Needed

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2048]
**User Story:** As a user, I'd like to refine my Open Opportunities search by keywords and other information that opportunity creators have entered.

**Acceptance Criteria:**

Filter name/Text: Skill
o Entries are generated by user typing and Open Opps using Autocomplete function
o As an item is selected, will add a pill to the top center of the page beneath Keywords search box and remain in the skill box
o More than one item can be entered and selected, and the maximum number of selection will be 5
o An item can be removed by clicking the ‘x’ icon on the tag, or by clicking the link "X Remove all"
o When the maximum number of items is reached, there will be an error message "The maximum number of skills is 5" beneath the skill box

Link to InVision mockup: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skill Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by KatMullens-work** [comment]
I was able to add six skills in Chrome with no error. Test failed.

**Comment by KatMullens-work** [comment]
I was not able to test in IE.

**Comment by KatMullens-work** [comment]
Tested in IE. I was able to add six skills; should only be able to add five or fewer. Test failed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-3-18 LHammond in testing

**Comment by KatMullens-work** [comment]
It now works great with the limiting to five items in IE but now it  isn't rendering properly in IE: 
![image](https://user-images.githubusercontent.com/25315047/39610519-fdef1834-4f1e-11e8-8066-32240cc995d2.png)

![image](https://user-images.githubusercontent.com/25315047/39610554-37486392-4f1f-11e8-95c4-a38ee74f9d38.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__NOTE:__ _CANNOT_ meet AC "The maximum number of skills is 5" as this is a limitation of the Select2 form control which does not supply on option for text to display when limiting the amount of selection so the current text shows as "You can only select 5 items"

**Comment by margaretdumas** [comment]
05/07/2018 - Mdumas....moving to review

**Comment by KatMullens-work** [comment]
On mobile, you can't scroll right to see/edit the filters under keyword that you've set up to see if they are there/to edit them. (Testing on safari on iPhone x). I think the filters should display in the window or be scrollable. How is it supposed to work, @bmcorum ?

**Comment by bmcorum** [comment]
Tested on iPhone and I am able to scroll left to right.

![Image uploaded from iOS.jpg](https://images.zenhubusercontent.com/59e8ff8ea468affe6df75add/82ee6e7c-b927-427f-9ec6-8ed685b2a39f)

**Comment by KatMullens-work** [comment]
It lets me scroll if I touch the filters, but the screen itself does not scroll. Test passed.
