### ISSUE TITLE
Career Field Filter Needed

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2049]
**User Story:** As a user, I'd like to refine my Open Opportunities search by keywords and other information that opportunity creators have entered.

**Acceptance Criteria:**
Filter name/text: Career field
o “Acquisition” will be only option for now along with a value for "Other".  Other will pull back anything other than acquisition related jobs..
o Will be a dropdown for now
o As an item is selected, will add a pill to the top center of the page beneath Keywords search box and remain in the career field box

Link to InVision mockup: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skills Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by LisaLNelson** [comment]
We are working with FAI to get a list of key words together buy 4/13/18.

**Comment by KatMullens-work** [comment]
Made the following updates per notes from conversation on 4/18: Career field (Ticket 2049)
-      (Kat)update AC on the ticket the Career field filter ticket that “Acquisition” will be only option for now
-      Will be a dropdown for now

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
04/27/2018 - Mdumas - This is in testing....

**Comment by margaretdumas** [comment]
04/30/2018 - Mdumas - Passess AC moving on to review.

**Comment by KatMullens-work** [comment]
This item passed testing in Chrome. I was not able to test in IE.

**Comment by bmcorum** [comment]
@KatMullens-work can you please try again. If you are still having an issue please send us what version of IE you are using. I was unable to replicate the issue.

![image](https://user-images.githubusercontent.com/1165615/39577698-064f7a10-4eb0-11e8-9433-dbc98234ecfd.png)

**Comment by KatMullens-work** [comment]
Hi @bmcorum : Same results. Screen shot below. 

![image](https://user-images.githubusercontent.com/25315047/39641111-133ba118-4f9b-11e8-8479-0a8abb151551.png)

Version of IE: 
![image](https://user-images.githubusercontent.com/25315047/39641139-2ab14726-4f9b-11e8-8ed2-0be1576ef4f3.png)

**Comment by KatMullens-work** [comment]
@LisaLNelson : please advise how to proceed. This ticket does not pass our acceptance criteria testing in that, once you add a career field, you cannot delete individual options under the keyword box. The problem is with Font Awesome, but it impacts this ticket.

@bmcorum : there are now multiple career fields in the career field box. I thought it was just going to be Acquisitions in the list but maybe I missed a conversation?

![image](https://user-images.githubusercontent.com/25315047/39714676-d49b0a74-51f8-11e8-8d53-a4f7162fd090.png)

**Comment by KatMullens-work** [comment]
Per group discussion this morning (scrum), the new career fields come from an additional ticket and are expected. The Font Awesome issue can't be resolved by Macon. Therefore, the ticket passes testing for IE.

On mobile, you can't scroll right to see/edit the filters under keyword that you've set up. (Testing on safari on iPhone x). I think the filters should display in the window or be scrollable. How is it supposed to work, @bmcorum ?

**Comment by bmcorum** [comment]
@KatMullens-work I tested on an iPhone an I can scroll pills left to right.

**Comment by KatMullens-work** [comment]
Ah! you have to click on the filters themselves to scroll them, not the screen to scroll IT. Test passed.
