### ISSUE TITLE
Occupation Filter Needed

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2051]
**User Story:** As a user, I'd like to refine my Open Opportunities search by keywords and other information that opportunity creators have entered.

**Acceptance Criteria:**
Filter name/text: Occupation
o Entries are generated by user typing and Open Opps using Autocomplete
o As an item is selected, will add a pill to the top center of the page beneath Keywords search box and remain in the occupation box

Link to InVision mockup: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skills Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by kbwagner** [comment]
@kbwagner to discuss with Lisa on whether this is still needed

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41577&_a=edit
