### ISSUE TITLE
Time Commitment Filter Needed

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2052]
**User Story:** As a user, I'd like to refine my Open Opportunities search by keywords and other information that opportunity creators have entered.

**Acceptance Criteria:**
Filter name/text: Time commitment
o Entries are generated by user selecting one time or ongoing checkboxes
o As an item is selected, will add a pill to the top center of the page beneath Keywords search box and remain selected.
o This filter has a select all option which selects all options. Once "select all" is chosen, a "deselect all" option become visible to allow the user to deselect all of the options.

Link to InVision mockup: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skills Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-18 LHammond in testing

**Comment by KatMullens-work** [comment]
This item passed testing in Chrome. I was not able to test in IE.

**Comment by KatMullens-work** [comment]
This item passed testing in IE and on mobile (iPhone). Thanks, team! :+1:

**Comment by KatMullens-work** [comment]
@LisaLNelson : This passed my testing.
