### ISSUE TITLE
Location Filter Needed

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2053]
**User Story:** As a user, I'd like to refine my Open Opportunities search by keywords and other information that opportunity creators have entered.

**Acceptance Criteria:**
Filter name/text: Location
o Entries are generated by user selecting Virtual or In person.
o If they select "In person", the user will type then select a specific location using an autocomplete box.
o As an item is selected, will add a pill to the top center of the page beneath Keywords search box. The checkbox remains selected and the autocomplete entry remains in the box.
o This filter has a select all option which selects all options. Once "select all" is chosen, a "deselect all" option become visible to allow the user to deselect all of the options.
o Checkbox for in person should be what toggles the location autocomplete on/off
o If checked "turn on" filtering by location and display location filter autocomplete, if unchecked "turn off" filtering by location, remove filter autocomplete, and remove all location pills

Link to InVision mockup: https://invis.io/4XGODQP3VW7#/288642168_FAI1_-_Search

Related Tickets:
Keyword Filters Needed #2046
Status Filter Needed #2047
Skills Filter Needed #2048
Career Field Filter Needed #2049
Series Filter Needed #2050
Occupation Filter Needed #2051
Time Commitment Filter Needed #2052
Location Filter Needed #2053

**Comment by KatMullens-work** [comment]
Updating based on conversation with @bmcorum today:

So if it is going to be a checkbox for in person then it should be what toggles the location autocomplete on/off
if checked "turn on" filtering by location and display location filter autocomplete, if unchecked "turn off" filtering by location, remove filter autocomplete, and remove all location pills

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-18 LHammond in testing

**Comment by KatMullens-work** [comment]
Passes in Chrome. Was unable to test in IE.

**Comment by KatMullens-work** [comment]
Passes in IE. Passes on mobile (iPhone). Thanks, team! :)

**Comment by KatMullens-work** [comment]
@LisaLNelson : this passed my testing.
