### ISSUE TITLE
Email content update: Opportunity Submitted email to admin

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2061]
User Story: As an admin, I want the verbiage in all emails to be consistent and not use the word task.

Acceptance Criteria: 
The following text changes should be made to the email that is sent to the Admin when a new opportunity is completed:
- Change subject to "New opportunity submitted by an opportunity creator"
- Change first sentence from "The message below was sent to a task creator because they created a new task on Open Opportunities." to "The message below was sent to an opportunity creator because they submitted a new opportunity on the Open Opportunities platform."
- Change the sign off from "Respectfully" to "Thanks" to be consistent with other emails.

Related Ticket: 
- 1686 was the original ticket for this email.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond in testing.
Testing completed moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/30150d63-a01e-4e87-a12d-c091582c08ba)

**Comment by kbwagner** [comment]
1/2/20 - KWagner reviewed artifact
Ready for final review
