### ISSUE TITLE
People Bar: Add Create Opportunity button regardless of sign in status

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2063]
User Story: 
As a user, I want to see the Create opportunity button whether I am signed in or signed out.

Acceptance Criteria:
- Add the Create Opportunity button to the blue people bar even if the user is logged out.
- If the button is selected and the user is logged out, take the user to the log in page.  Once they are logged in, direct them to the Create Opportunity page.
- Modify the People link - if I'm logged out, click on the link, direct me to login (all currently working), and once logged in take me directly to the People page (currently takes me to landing page).

Related Ticket: 
- 2033 - Creates blue people bar 

![image](https://user-images.githubusercontent.com/18709918/38688652-a00a91f4-3e47-11e8-8e39-41a871ba0c0f.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-2-18 LHammond in testing

**Comment by kbwagner** [comment]
5/2/18- KWagner tested in Chrome, IE, and mobile Safari.  
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved
