### ISSUE TITLE
Admin: Ability to remove applicants

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2066]
User Story: As an admin, I need the ability to remove an applicant from an opportunity in the event they are found not to be a federal employee.

Acceptance Criteria: For non student internships only at this time
1) Provide admin with the ability to remove anyone from an opportunity that has applied (in either applied or assigned state)
2) If a user is disabled by an admin, automatically remove the user from any opportunity for which they have applied or been assigned.
3) The system should track what applicant/participant was removed, by whom, the date, and a reason 

Use Case: Applicant who is not a federal employee applied for many opportunities

Note:
- Admin or opportunity creators can remove someone as a participant currently by clicking on their name to drop them down as an applicant

Design Option: 
Design Option: (can be modified by Macon)

Where user role is agency admin or admin
- On the administration --> Tasks page
- for any opportunities in open and in progress status
- Add an icon to the Actions column to delete applicant/participant
- When this icon is selected, a modal will display with a all of the participants and applicants for this opportunity
- Once a name is selected, a confirmation message will display to the admin to ensure they want to remove this applicant/participant
- Once confirmed, the applicant/participant will no longer display on the opportunity
- No emails will be sent to the opportunity creator or the applicant at this time.
- If possible, we should track who deleted the applicant and on what date.  
- If possible, add an option to provide a reason as to why the applicant/participant was removed.  Can be free form or we can identify a list of values such as not a federal employee, requested to withdraw, etc.

Related ticket: 
1878 - Admin ability to add an applicant to an opportunity

**Comment by kbwagner** [comment]
5/16/18 - Kwagner - removing this ticket per @LisaLNelson Lisa Nelson's approval.  
- This is no longer necessary.  Anyone can remove a participant and make them only an applicant.  An applicant can just stay an applicant.  Removal is not necessary.

**Comment by tanichacko** [comment]
@kbwagner ready for testing

**Comment by tanichacko** [comment]
@Kibrahacha67 ready for testing

**Comment by tanichacko** [comment]
![atrifact volunteer.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/cad27e64-0c64-4b95-ab75-5898a495b320)

**Comment by Kibrahacha67** [comment]
12-23-19 LHammond in testing
#2 of AC says if a Sitewide admin disables a user then they should be removed from all opportunities.  I disabled a user and they were not removed from opportunities (images below) moving back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/f7ad7767-f0ca-41a6-bfeb-a79b57d9b033)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/683de0f3-f897-4488-9bb3-abaaa1496056)

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-26-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
12-26-19 This ticket actually works as requested, the BIC issue is a bug and I will create a new ticket.  Moving to review.

**Comment by kbwagner** [comment]
12/30/19 - KWagner tested in Chrome/Test
Ready for final review
