### ISSUE TITLE
Opportunity card sort order

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2076]
User Story: As an Open Opportunities member, I want to see the opportunities display in a known sort order each time.

Current sort order: Create Date

Acceptance Criteria:
Opportunity cards should be sorted as follows:
- Approval Date - newest to oldest (PublishedAT date - this gets set when the opportunity is approved)

Note: There is a ticket for a Sort By dropdown that may be done at a later date.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-17-19 LHammond in testing

**Comment by kbwagner** [comment]
7/17/19 - Kwagner tested Chrome/Test
Ready for final review.
