### ISSUE TITLE
IE does not render properly on Search Page

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2084]
IE does not render page properly.  
Search Page
- Filter checkboxes are cutoff
- Images stretched on opportunity cards
- Text overlapps for opportunities

Create Opportunity Page
- Missing "+" sign next to new options (What you'll learn, who we are, related keyword)

![IE does not render properly.gif](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/854f4989-4818-4f5a-b2d2-3f54172fe27e)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
05/07/2018 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
Images stretched on the dashboard. 
![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/edacb750-7d59-4539-b3b3-2162bbbcc708)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
5/8/18 - Kwagner - Tested in IE and these issues are resolved.  In my IE I only see a single column of opportunity cards with the occasional second column.  Not related to this issue so passing and will do a full review of IE in the future.
@LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
approved
