### ISSUE TITLE
Page Count is not accurate when multiple filters are used and one default filter is removed

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2086]
If a second filter is added and the first filter is removed, (open which is default) the page count does not display accurately.  

Steps to reproduce:
1.  Perform a search only with default filter
2.  Add second filter of "submitted"
3.  Remove the "open" filter

Results:  two pages are displayed.  When page 2 is clicked there's nothing on that page.

**Comment by bmcorum** [comment]
@margaretdumas this should also be fixed now. It was an error with trying to render initials

**Comment by margaretdumas** [comment]
05/03/2018 - Mdumas - Retesting passed. Moving to review.

**Comment by kbwagner** [comment]
5/7/18 - KWagner tested in Chrome.  Ok
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
