### ISSUE TITLE
Add text to no search results page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2090]
User Story: As an open opportunities user, I want tips to display when I have no search results.

Acceptance Criteria: 
If a user removes all filters (including the default of open), add a third bullet to the No search results page that indicates that you must have at least one status filter applied to receive results.  

![image](https://user-images.githubusercontent.com/18709918/39486433-168f9624-4d4a-11e8-9d5f-12427f643ddf.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
05/05/2018 - Mdumas - In Testing...

**Comment by margaretdumas** [comment]
Mdumas - Moving back to development.  There is a third bullet which is not mentioned in the AC. 

" You must have at least one status filter applied to receive results"

**Comment by raywilliams** [comment]
The image does not reflect the correct AC. The third bullet is mentioned right above the image.

**Comment by jhanson12** [comment]
The image was not intended as the final result, but as a reference to what needed to be updated.

**Comment by kbwagner** [comment]
5/17/18 - KWagner tested in Chrome and mobile
@LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
Approved.
