### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2091]
On the task creation page, under section 4 when I click on How to create an opportunity it takes me to we can't find the page you're looking for.
![screen shot 2018-05-01 at 10 18 10 pm](https://user-images.githubusercontent.com/9039852/39502338-b46e1d1e-4d8d-11e8-9495-324502f10709.png)

![screen shot 2018-05-01 at 10 11 39 pm](https://user-images.githubusercontent.com/9039852/39502450-52baca12-4d8e-11e8-8d3e-331bde0975be.png)

**Comment by kbwagner** [comment]
5/31/18 - KWagner closing per sprint planning.  This is no longer an issue as the process for create was redone with release 2.
