### ISSUE TITLE
Default text for keyword search fields

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2094]
User Story: As an open opportunities user, I would like to have help information to indicate what I can enter into a keyword search field.

Acceptance Criteria: 
- Add default text to the keyword field that reads, "Find opportunities by topic, skill, career field, agency or series"
- This should display for both the regular search and acquisition search pages'
- In mobile, if the text is too long add a "...."

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-5-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum If the verbiage doesn't  fit on mobile, then we should probably truncate it to make it fit.  That doesn't look right and @minchung12 agrees.  If we shorten it to "Topic, skill, career field, agency or series" (removing Find opportunity by" will it all fit on the mobile size?  I realize it's an AC change but it also doesn't work well on mobile.

**Comment by raywilliams** [comment]
I used Chrome's developer tools to see how the shorter placeholder looks and the placeholder still gets cuts off when using an iPhone 5. Even if you get the phrase short enough to fit on an iPhone 5, there's no way to control if it gets cut off. My MIL has the text size much larger on her iPhone and a shorter placeholder would still get cut off.

USAJOBS' keywords search placeholder gets cut off.

**Comment by kbwagner** [comment]
Thanks @raywilliams sorry I don't know why I tagged Brice earlier.  Let me just chat it over with Min and it sound like it is what it is.

**Comment by raywilliams** [comment]
I found that I can add an ellipsis to the end if the text is too long. Will this work?
![image.png](https://images.zenhubusercontent.com/5a6f64004b5806bc2bc4be2c/9209da19-0de2-4c54-8167-63e0189e32be)

**Comment by kbwagner** [comment]
I think that looks better...fine by me..

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-6-18 LHammond in testing

**Comment by kbwagner** [comment]
6/7/18 - KWagner - tested in Chrome and mobile Safari

**Comment by LisaLNelson** [comment]
Approved.
