### ISSUE TITLE
Find ways to get Opportunity Creators to be more responsive to applicants

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2097]
There is a problem getting Opportunity Creators to respond in a timely manner to people who apply for their opportunity. We need to brainstorm solutions. We should:

- Consider a rating system thumbs up for people who provide an excellent experience.

- Work with CORE as they have though about rating the job announcement to encourage people to spend some time writing better.

**Comment by nia-johnson** [comment]
Moved to TFS as a task. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41521&_a=edit
