### ISSUE TITLE
A film is overlapping the page when the  15 minute timeout warning notification is displayed

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2106]
When the system is in the  15 min time out process a film overlaps the page prohibiting the user from selecting either button.  

Steps to reproduce:
1.  Allow site to be idle for 12 min
2.  When the warning is displayed the timeout message is displayed but the page has a film which prevents the user from selecting "Stay signed in" or either option.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
05/07/2018 - Mdumas - in testing....

**Comment by margaretdumas** [comment]
05/7/2018- Mdumas - film has been removed. Moving on to review

**Comment by kbwagner** [comment]
5/7/18 - KWagner tested in Chrome.
@LisaLNelson ready for your review.

**Comment by LisaLNelson** [comment]
Approved.
