### ISSUE TITLE
Research issues with IE and font awesome

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2107]
IE does not properly render x on pills along with many other issues. 
![image 3](https://user-images.githubusercontent.com/18709918/39607019-954aeaa0-4f06-11e8-8f1b-49ee1b367fd3.png)
![image 2](https://user-images.githubusercontent.com/18709918/39607020-956fd630-4f06-11e8-8606-35d81f16a00d.png)

**Comment by humancompanion** [comment]
fontawesome.com had been blocked entirely on our network. Do we believe it is now properly unblocked? Or are you accessing off of our network and VPN? Also, what version of IE are you using? The "issues" are not really well defined here. Sounds like some icons are not appearing. Are any icons appearing?

**Comment by bmcorum** [comment]
@humancompanion the error occurs in IE 11 and only occurs randomly during the rendering process in which FontAwesome throws a syntax error. \<a\> tags are never converted to svgs

**Comment by bmcorum** [comment]
This is a recorded known issue with FontAwesome and IE11. See details here https://github.com/FortAwesome/Font-Awesome/issues/12471

**Comment by bmcorum** [comment]
@kbwagner I believe this ticket can be closed.
