### ISSUE TITLE
Add fade out to opportunity card

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2116]
The opportunity cards on desktop are cutting off text.  Display a total of 4 lines.  Begin fade after second line. 

This should occur on desktop and mobile.

**Comment by bmcorum** [comment]
__NOTE__ because we support markdown we __CANNOT__ guarantee that it will display exactly 4 lines and begin fading exactly after second line because each line might be different heights.

**Comment by kbwagner** [comment]
This appears to be completed - closing.
