### ISSUE TITLE
Series Values- 1102 Contracting to 1102 Contracting/Acquisition

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2122]
User Story: As an end user, I should see the the 1102 series listed as Contracting/Acquisition, not just Contracting, to support the FAI deployment.

Acceptance Criteria: 
Modify the display text for the series field to read 1102 Contracting/Acquisition (adding the /Acquisition).

**Comment by KatMullens-work** [comment]
Jobs is changing the label on parts of the site to contracting/acquisition to support FAI. We are not changing it across government (yet).

**Comment by bmcorum** [comment]
But we are because if I change it now it changes for everyone

**Comment by KatMullens-work** [comment]
Actually, the wording on the second page really could stay the same, and we can just change the title and get away with it unless anyone notices and asks us about it. I’ve added the story to TFS.

Product Backlog Item 33247:Update Explore Opportunities

On the Explore Opportunities page (https://www.usajobs.gov/?c=opportunities) under the Business, Industry, and Programs section, change "Contracting" to "Contracting/Acquisition"

On the Contracting page (https://www.usajobs.gov/Search/ExploreOpportunities/?Series=1102), change the title of "Contracting" to "Contracting/Acquisition"

Dan Thibodeau, USAJOBS Deputy Program Manager
U.S. Office of Personnel Management
Office:  202-606-1563          Cell:  202-534-8006

**Comment by KatMullens-work** [comment]
We have the cosmic power to change it for everyone?

**Comment by bmcorum** [comment]
See as everyone who would use OpenOpps would see the title for the series as Contracting/Acquisition so when the next agency/client comes along and finds out we changed titles because FAI wanted it they are going ask if they too can change the title of a series

**Comment by KatMullens-work** [comment]
I'll defer to Lisa but in cases like these, as long as it includes the Contracting title as well, doesn't seem like a problem to me if the universe it impacts is Open Opps. Open Opps isn't a career job, just a detail. @LisaLNelson @bmcorum @kbwagner

**Comment by bmcorum** [comment]
Either way I am fine I just want to make sure what is truly being asked for has been thought out. So we don't keep going back and forth, and I also don't want to get into huge conditionals where pages display differently for 100s of different situations. Whatever changes we make in the future should be across the board and not just for single agencies/use cases.

**Comment by KatMullens-work** [comment]
I agree. We could also start working with the official keepers of the series to see if wholesale title updates are appropriate or not. As always, I'll defer to @LisaLNelson for a decision on this.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
6/11/18 - KWagner tested in Chrome
@tlorrison ready for final review.

**Comment by LisaLNelson** [comment]
Approved.
