### ISSUE TITLE
Update Navigation

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2124]
User Story: As an open opportunities user, I want the navigation bar to be straightforward and concise.

Acceptance Criteria:
The following updates will be made to the navigation for open opps:
- Remove "Create Opportunity" from the menu (mobile and desktop).  It is not necessary to be in the menu since it is available on most pages already.
- Move People under Search menu
- Update with the new design system changes.
- Help should display even when not logged on.  Help in the top navigation should open in the same window (not a new)
- Mobile - Help should display under search
- The Open Opps logo should also be redone to include the trademark symbol on the USAJOBS logo
- Sign out will display on the menu to the right of Administration for Admin users or to the right of Profile for non admin users.  It will not display on the profile page at this time.

Please follow the design system and attached mock.

Design System: http://usajobs.github.io/design-system/navigation/    
![Screen Shot 2018-06-01 at 4.01.30 PM.png](https://images.zenhubusercontent.com/59fb63728a75884b9085d569/42c79b50-18a6-4f7c-9db6-49b7ff90c4be)

Logo screen shot: 
[openopps_logo.svg.zip](https://github.com/openopps/openopps-platform/files/2059949/openopps_logo.svg.zip)

**Comment by kbwagner** [comment]
@jhanson12 FYI I'm working on some help stuff and one of the notes is that help in the top navigation should always open in the same window vs new.  I added that in the AC above.

**Comment by kbwagner** [comment]
@jhanson12 I added the sign out link on the profile to this ticket per your conversation with @minchung12

**Comment by kbwagner** [comment]
@jhanson12 - Min and Lisa spoke and here is the final update for the sign out link (for now).  I updated the AC above: Sign out will display on the menu to the right of Administration for Admin users or to the right of Profile for non admin users.  It will not display on the profile page at this time.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-11-18 LHammond in testing

**Comment by kbwagner** [comment]
6/12/18 - KWagner per @minchung12 the Bar under the name should have same color as the bottom bar ($color-cool-blue)
![screen shot 2018-06-13 at 12 25 13 pm](https://user-images.githubusercontent.com/18709918/41366564-7f091e00-6f0a-11e8-832d-33da388ddf63.png)
@jhanson12 sending back to you.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-13-18 LHammond in testing

**Comment by LisaLNelson** [comment]
Approved.
