### ISSUE TITLE
Career Field requirements and add Other

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2125]
User Story: As an open opportunities user, I want the career field information to be as useful as possible.

Acceptance Criteria:
- Users must select one career field when creating an Open Opportunity (required field)
- Add a value of "Other" to the Career Field data values so if there isn't a good selection to make the creator can select "Other"

**Comment by bmcorum** [comment]
How do we handle old opportunities if this field becomes required?

What happens if I don't like any of the options for career field or none of them match my particular opportunity?

**Comment by kbwagner** [comment]
Communities will meet this requirement
