### ISSUE TITLE
Scroll bar displaying for Filters in IE and Edge

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2130]
There is a scrollbar displayed next to the filters for IE and Edge.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-18 LHammond in testing

**Comment by kbwagner** [comment]
5/9/18 - Tested in IE and no scroll bar displays.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
