### ISSUE TITLE
Profile - Update Photo/Initial coloring

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2134]
On the profile edit, make the following changes to the default photo:
- If photo is added by a user, display the photo
- If no photo is added by a user, display their initials with coloring as follows:
1) For existing users, run a process to assign a color
2) For new users, as they save their profile without adding a photo, assign a color to their initial icon

The following areas should be updated to now display the photo or colored icon from the profile instead of randomized coloring: (separate into new tickets prior to sprint where this will be done)
1) Landing Page - Latest Achievements
2) Opportunity Card
3) Opportunity

Colors are:
Colors for the initial icons (will change with a future ticket):
- Initial icons for the opportunity creator should be alternating colors: Bg $color-secondary-lightest (#f9dede)
Text $color-secondary-darkest (#981b1e)

Bg $color-cool-blue-lightest (#dce4ef)
Text $color-cool-blue (#205493)

Bg $color-green-lightest (#e7f4e4)
Text $color-gray (#5b616b)

Bg $color-primary-alt-lightest (#e1f3f8)
Text $color-primary-alt-darkest (#046b99)

Bg $color-gold-lightest (#fff1d2)
Text $color-gray (#5b616b) 

![image](https://user-images.githubusercontent.com/18709918/39130261-a3530198-46da-11e8-9186-1b5e1dc51366.png)

**Comment by bmcorum** [comment]
Initial coloring is based on Math.mod algorithm using the user's primary key from within the database. This will cause coloring to be distributed evenly among all users.

**Comment by kbwagner** [comment]
Closing per Brice's comment above.
