### ISSUE TITLE
Search filters should only show career fields for which we have opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2135]
Search filters should only show career fields for which we have opportunities
- Design recommendation
- Will need to be done as part of a full search overhaul
- Show options with zero link

**Comment by kbwagner** [comment]
Consider making search filters not dropdowns but a list like USAJOBS

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41519&_a=edit
