### ISSUE TITLE
Need tests for database deletions

### ISSUE THREAD

**Issue by polastre** [openopps/openopps-platform#214]
When objects are deleted from the database, they can cause adverse effects when pages are rendered.  For example, if a user creates a task, then that user is manually deleted from the database, the browse task page will fail to render because the user cannot be retreived from the database.

Note: deleting from the database OR setting the `deletedAt` column have the same effect to the application.

Tests needed, deleting a:
- [ ] user
- [ ] project
- [ ] opportunity
- [ ] event
- [ ] tag
- [ ] tagentity
- [ ] comment

And then testing that the server can render:
- [ ] browse projects
- [ ] browse opportunities
- [ ] a particular project (in the case of deleting an event, opportunity, user)
- [ ] a particular opportunity (same as above)
- [ ] a profile (that uses the tagentity or tag, for example)

**Comment by ultrasaurus** [comment]
now that we have the ability to delete in the admin panel, we don't manually delete anymore, so I think we don't need to do this specifically.  If there are problems discovered, we should then fix and write tests.
