### ISSUE TITLE
Create Opportunity: Limit number of skills and related keywords 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2140]
User Story: As an opportunity creator, I would like to limit the number of skills and related keywords allowed in order to keep my opportunity meaningful to seekers.

Acceptance Criteria: 
- On the create opportunity page, there should be a limit to 5 skills and 5 related keywords that can be entered.  This will alleviate display issues on the opportunity card.
- For existing opportunity cards where there are more than 5 skills and/or related keywords, display the first 5 and then a +# (i.e. +3) to indicate there are more keywords that will display when the card is opened.  
- There will be no limit to skills allowed on the profile (no change).

For existing opportunities:
- Keep the number of skills and related keywords they currently have
- If they go to edit, do not force an error on the save but do not allow them to add more.

Duplicate:
- If the opportunity is duplicated, they can save it as is with the existing number of skills or keywords.  However, if an edit is made after the duplicate and save, it will work like any other opportunity would.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-25-18 LHammond in testing

**Comment by kbwagner** [comment]
5/30/18 - KWagner tested in Chrome and mobile Safari. 
Will enter separate bug on the mobile related keyword field for odd display not related to this ticket.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Tested in Chrome. Approved.
