### ISSUE TITLE
Mobile: Footer should display on all pages

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2147]
The footer is not displaying on any mobile pages.  

AC: 
- Footer should display on all mobile pages except for the filter page when the filters are showing because it is more of an overlay page
Mock: https://projects.invisionapp.com/d/main#/console/13760177/290222734/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-15-18 LHammond in testing

**Comment by kbwagner** [comment]
5/15/18 - KWagner tested in mobile Safari
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
