### ISSUE TITLE
Opportunity page default text for comment box

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2154]
User Story:
As an open opportunities user, I would like to know that I can enter comments and discussions on an opportunity.

Acceptance Criteria:
On the opportunity viewing page, add default text of “Leave comments here” in discussion box (requirement not added in AC for 1994)

Mock:
https://projects.invisionapp.com/share/HJGOHLCA2X9#/screens/288642426_FAI1-Opportunity

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond in testing
Testing completed moving to review.

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/2/20 - KWagner tested in Chrome/Test
Ready for final review
