### ISSUE TITLE
Create Account - data lost when click on Terms and Conditions link

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2156]
Steps to Reproduce:
1) Click on Create account
2) Enter name, password, email, etc.
3) Click on Terms and conditions link by checkbox.  Terms and Conditions opens in the same window
4) Click the back button on the internet browser (Chrome) as that is the only way to get back.  All data entered on the create account page is now lost.  User is returned to sign in page.

**Comment by bmcorum** [comment]
This is technically correct as you left the site and therefore any session has been terminated and any data related to that session is no longer valid.

This would be more of an issue where the Terms and conditions link should open a new window/tab.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-16-18 LHammond in testing

**Comment by kbwagner** [comment]
5/16/18 - KWagner - tested in Chrome and mobile Safari.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
