### ISSUE TITLE
Loading icon issues

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2157]
Steps to Reproduce:
Loading icon is in odd locations on the page

1) Select an opportunity to open
- no loading icon displays just the header and footer
- mobile and desktop

**Comment by kbwagner** [comment]
6/4/18 - KWagner confirmed still an issue.  I need to make a list of all of the places where the issue exists.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-19-18 LHammond in testing

**Comment by kbwagner** [comment]
6/20/18 - KWagner - Tested in Chrome and mobile safari
- Ready for final review.

**Comment by tlorrison** [comment]
Approved
