### ISSUE TITLE
Delete comment bug

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2161]
Steps to Reproduce: 
1) Non Admin user creates an opportunity and saves as draft (Dywane),
2) Larry (admin) posts a comment to the draft opportunity
3) Dywane goes in to delete comment and it just goes to the signed in landing page.    
- As an admin, Katrina went in, deleted comment, successfully deleted, and it stayed on the opportunity page.  
- Issue occurs whether non admin opportunity is in submitted or open status.
- The original issue was a non admin couldn't delete a comment posted by an admin but it is now a creator can't delete any comments posted by any user on their opportunity.
Release 2 Bug Bash

Current functionality appears to be:
1) Admin can always delete comments (correct)
2) Non admin can't delete on any opportunity they didn't create (correct)
3) A user can always delete their own comment (correct)
4) **A non admin opportunity creator will see the "x" to delete from all comments that display on their opportunity, however, the delete does not work and takes the user off the page.  
- Opportunity creators should be able to delete a comment for the opportunity they created.  Make the "X" to delete work properly
5) No user should be able to post comments to drafts or submitted opportunities.
6) Agency admin should be able to delete a comment for any opportunity that is within their agency. 

![image](https://user-images.githubusercontent.com/18709918/41253329-f64a6c2c-6d8d-11e8-8b9f-8f487c0a5583.png)

**Comment by bmcorum** [comment]
Not sure we should be able to create comments on drafts or submitted. I believe the comment section is only supposed to be usable when in the state of 'Open' or 'In progress'.

**Comment by kbwagner** [comment]
That's fine too...to disable adding comments unless it's open or in progress.

**Comment by bmcorum** [comment]
Might be why Dywane had issues trying to delete. If the server returns a 403 (forbidden - you tried to do something that you are not supposed to do) it redirects you to the landing page, and I need to double check, but I believe we have a check in place that looks at the state of an opportunity and won't allow for deletion unless you own the comment, the opportunity is open or in progress or you are an admin

**Comment by kbwagner** [comment]
I validated this one with him...the issue is that the comment delete option is disabled for him.  But again I think if we don't allow comments on draft opps it's not an issue.  This one is really low priority but always want to track all the issues.

**Comment by kbwagner** [comment]
6/4/18 - KWagner - tested in UAT still an issue.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-21-18 LHammond in testing

**Comment by kbwagner** [comment]
6/25/18 - KWagner tested in Chrome.
- Tested as an admin I can delete all comments
- Tested as a non admin I can delete my own comment
- Tested as a non admin Opportunity creator, I can delete comments on the opportunity I created.
ready for final review

**Comment by tlorrison** [comment]
Approved
