### ISSUE TITLE
Regular search page displays which Acquisition search page is loading

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2162]
Steps to Reproduce: 
1) From the signed in landing page, select Acquisition from the Search for opportunities by Career field
2) The page goes to the regular search page while loading and then flips to acquisition.  
- Acquisition users should not see the regular search page here or only the loading icon.  

Release 2 Bug Bash

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-17-18 LHammond in testing

**Comment by kbwagner** [comment]
5/17/18 - KWagner tested in Chrome and mobile Safari
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
