### ISSUE TITLE
Selecting the "Yes" option on the Career Field without selecting a Value from the drop down list is causing a back-end error.

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2163]
When a career field is set to "Yes" and no selection is made from the drop down an error is thrown on the back-end rather than an error message being displayed on the screen.

We need a message to let the user know if they select one, they will need to select an option from the dropdown.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - 05/15/2018 - In testing

**Comment by margaretdumas** [comment]
05/15/2018 - Mdumas - Retesting was good moving to review.

**Comment by kbwagner** [comment]
5/15/18 - KWagner tested in Chrome and ok
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
