### ISSUE TITLE
Remove help from mark down editor

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2164]
Steps to Reproduce:
1) Create an Opportunity
2) in the Introduction, What you'll do, what you'll learn and who we are fields, there is a Help button.  That button does not work and should be removed.

Ticket 1992 provides further change requests to the mark down editor and there is also a spike to research better options for the future

**Comment by kbwagner** [comment]
5/16/18 - Kwagner tested in Chrome. 
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
