### ISSUE TITLE
Open Opportunities Communities

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2169]
![image](https://user-images.githubusercontent.com/1165615/40054429-ce9f980e-5812-11e8-8433-190ab354e3f0.png)

![image from ios](https://user-images.githubusercontent.com/1165615/45433707-c01a1400-b67a-11e8-97a9-0e97f84e1e97.jpg)

## What is a community?
1. A community is a group of Open Opportunity users who may belong to different agencies, but have a common goal. ___Example___: Federal Acquisitions Institute (FAI)
2. A community has two types of users.
    - __Member__: user that can search, create, and apply to opportunities within the community
    - __Manager__: same abilities as a member plus
        - Add or remove new members
        - Add or remove new managers
        - Approve, edit and delete opportunities within the community

## How does a community differ from an agency?
1. A community may consist of people from different agencies (OPM, GSA, FAI, etc)
2. Opportunities created by an community can only be viewed by members of the community
    - Might have various _teasers_ to entice new users to join a community

## How does it work?
1. A community is created and a manager is assigned to it
2. Members are added or join
3. A logged in member sees an additional search menu option for search community opportunities. ___Example___: Search acquisition opportunities
4. A logged in member sees an additional create opportunity option. ___Example___: Create acquisition opportunity
5. Managers will see an new dashboard option which will allow them to view reports and approve new opportunities. ___Example___: Acquisition Dashboard

## Benefits
1. Community managers can be provided with a reporting dashboard
2. Communities will have their own search page
3. Communities can more easily have custom questions or requirements on opportunities
4. Easier to logically separate _special_ or _specific_ opportunity categories

**Comment by kbwagner** [comment]
This has been completed
