### ISSUE TITLE
Opportunity Create Page: Focus shift to error messages

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2172]
Steps to Reproduce:
1) Create an opportunity without all required fields
2) Click on the Preview (or save as draft) 
- Error messages occur but user's focus is left on the bottom of the page so they think they are stuck
Focus should scroll to the first error message on the page.

In addition:
- If you don't specify the number of hours, save/preview does not work.  Add an error message to the field
- If you select full time detail, it breaks.  Users will be unable to create or edit new opportunities if full time detail selected.
- Note: If possible (can be a new ticket) - error messages shouldn't display the second you enter a field - i.e. skills.
- 

Related Ticket:
1860 - Focus for error messages on create account

**Comment by bmcorum** [comment]
@kbwagner I just tested this scenario in UAT and it does scroll to the to the first error on the page.

**Comment by kbwagner** [comment]
This is now working - closing bug.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-15-18 LHammond in testing

**Comment by kbwagner** [comment]
5/15/18 - KWagner tested in Chrome and mobile Safari
@LisaLNelson ready for final review

**Comment by LisaLNelson** [comment]
approved.
