### ISSUE TITLE
Share Opportunity Email changes

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2173]
Modify the Share Opportunity email as follows:
1) I wanted to let you know about this great opportunity to help a colleague.  should be the first sentence of the email
2) Change the label of "Opportunity" to read "Opportunity title"
3) Change the label of "Description" to read "Introduction"
4) Add What you'll do and associated text to the email
5) The last sentence will be the Click on the link to find out more
6) The subject line should be sentence case

Current Screen Shot: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/b5e1f428-3c4f-4b90-bc05-9190ce2c519c)

**Comment by jhanson12** [comment]
Ready for testing @Kibrahacha67

**Comment by Kibrahacha67** [comment]
1-3-20 LHammond in testing
Testing completed moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/571eca18-0748-497a-91c6-522d03fd7e34)

**Comment by kbwagner** [comment]
1/6/20 - Kwagner tested in Chrome Test
Ready for final review.
