### ISSUE TITLE
Support Back button functionality

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2182]
User Story: As an applicant, I want to be able to click on the back button to return to my search results and maintain the filters I have selected in order to have a good search experience.

Acceptance Criteria: 
- When a user is viewing an opportunity, they should be able to click on the browser back button and maintain any filters, keywords, or pills that they previously added.

From Release 2 Bug bash:

In reference to browser back button, do we support this function within Open Ops (we support this button in Core)? If a user used the pagination at the bottom and selects to view an opportunity on a subsequent page the system is failing to recall where the user left off. Same thing with filters when I "select all" and the paginate, select to view an opportunity...the system fails to recall my selection and I have to start all over again. (edited)

Brice Corum [1:22 PM]
@dywane.boyd the major issue with "back" button support resides in the fact that Open Opps does NOT currently support true pagination
When the search page is loaded it contains ALL data for ALL opportunities in the system and is filtered clientside so you are not technically navigating anywhere and therefore the browser History object is not being updated

Also, If you accidentally click the back button on your browser while creating an announcement you lose all the information you typed

**Comment by kbwagner** [comment]
10/31/18 - Issue came up again testing a search with career field "Acquisition".  Returned 20 results.  Opened an opportunity, reviewed, clicked back.  Had to reenter the career field again each time.

**Comment by kbwagner** [comment]
TFS: 35583 https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35583&fullScreen=false&_a=edit

**Comment by Kibrahacha67** [comment]
12-19-18 LHammond in testing

**Comment by kbwagner** [comment]
1/3/19 - tested using the /search once logged in.
- tested all filters.

@kikaider05 one issue I do see which may have nothing to do with this ticket.  I have added the following filters:
- Status: draft, submitted, open
- Skill: accessibility testing
- Career Field: Computer and Information Technology
- Series: 2210
- Time Commitment: One Time

I get two search results.  Open an opportunity, click back button, and I get an "Oops, there are no search results."  The Time Committment filter seems to be the issue.  If I remove that filter, I get my results back.  I can add the filter and get results...it's just when I open an opp and click back button it gives me the no results.  Initially was using one time and ongoing filters and thought it was the ongoing but even the one time causes the issue.

If this is related to this ticket, I can move it back.  If it's another issue, let me know and I can put in a bug ticket.

**Comment by kbwagner** [comment]
Discussed with Brice - moving back to dev until code is pushed.
- I still need to test the restrict to agency checkbox filter but Brice said it's been removed when signed out and he needs to put in a new ticket:

**Comment by Kibrahacha67** [comment]
1-10-19 LHammond in testing

**Comment by KatMullens-work** [comment]
Jodie and I tested this and the back button is not saving search preferences when you click the back button from an opportunity or from the search page to the main page.

**Comment by Kibrahacha67** [comment]
@KatMullens-work - please give us more information.  what browser what type of user etc.  thanks

**Comment by jhanson12** [comment]
It will only work for the new search capabilities.

**Comment by KatMullens-work** [comment]
Steps to test: 

. I started on this page: 
https://openopps.test.usajobs.gov/tasks

I selected:

Open
Ongoing
In Person

I clicked on this task:
https://openopps.test.usajobs.gov/tasks/812

clicked the back button

and the Ongoing and In person filters were no longer selected. Open is still present.

**Comment by Kibrahacha67** [comment]
you are using the wrong search.  please try https://openopps.test.usajobs.gov/search.  there are two test pages so we can compare the results.

**Comment by KatMullens-work** [comment]
When will the main search page be /search and not /task?

Is there a ticket for it?

**Comment by KatMullens-work** [comment]
Is there a ticket to update the main search page to /search from /tasks?

**Comment by KatMullens-work** [comment]
Confirmed back button works in /search.

**Comment by KatMullens-work** [comment]
Confirmed back button works in /search.

When will main search page be updated from /tasks to search? Which ticket is it so we can link it here. Don't want to lose track of it. :)

**Comment by Kibrahacha67** [comment]
will be the same for ticket 2187.  once testing is completed @bmcorum will make the switch over.  There are a couple of other issues that are being worked for search right now.  Brice can give a better timing on when.

**Comment by KatMullens-work** [comment]
Awesome! Passes the test with /search I just want to make sure we don’t forget with everything else going on to make the switch ☺

**Comment by kbwagner** [comment]
Ticket 2822 will change the default search to /task with release 7.6 when we implement elastic.

**Comment by Kibrahacha67** [comment]
All good...team is making some adjustments on search and shouldn't be long.  We will make sure that they get deployed together and not lost.  again Brice will be able to give a better picture on when it will be completed... : )

**Comment by KatMullens-work** [comment]
Excellent! Updated github and TFS. TFS is in Ready for PO Approval status.


https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35583

**Comment by kbwagner** [comment]
1/15/19 - KWagner - tested all filters with the back button and it worked.  Chrome/Test environment
- The only filter that I didn't test is the restrict to agency because htere is a separate bug for this.

Unable to test search in mobile/safari at all (using /task or /search).  Will test in other environments and enter bug if necessary

Ready for final review.
