### ISSUE TITLE
Bug - Users Unable to Respond to Comment Sent to Them While on OPM Network 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2184]
### Context 
**Steps to Replicate** 
1. Get on the OPM network 
2. Click reply button under comment that was sent to you.  

**Expected Results**
User is able to draft and send response 

**Actual Results**
Can't draft and send response. Button is grayed out. 

Notes: User is able to respond to a comment send to them while off the OPM network

### Old Requirements
The following changes should be made to the comment section of the opportunity:
1) **No longer relevant, per https://github.com/openopps/openopps-platform/issues/2275** ~~Add ability to cancel out of comment once selected~~ 
![image](https://user-images.githubusercontent.com/18709918/40075205-bc575d30-5849-11e8-861d-a18c7124ec6c.png)
3) **Addressed in https://github.com/openopps/openopps-platform/issues/2275** ~~When you reply to a comment, we shouldn’t auto default the original text into the comment box.~~ 
4) **Addressed in https://github.com/openopps/openopps-platform/issues/2275** ~~When you delete a comment, we should have a call to action of “are you sure you want to delete”~~ 
5) **Addressed in https://github.com/openopps/openopps-platform/issues/2275**
~~Have to refresh page to view updates on comments.  Users replied immediately but didn’t realize they had to refresh.~~ 

Release 2 bug bash

Related tickets: 
783 - comment authors shouldn't get notified of their own comments

**Comment by kbwagner** [comment]
@nia-johnson can you test this and see if this is still an issue?  If not, please close

**Comment by nia-johnson** [comment]
Tested in UAT and it doesn't seem to be an issue. Closing
