### ISSUE TITLE
Add Back to results link for Opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2187]
User Story: As an applicant, I want to be able to maintain my search filters as I navigate through opportunities in order to have a successful search experience.

Acceptance Criteria: 
Currently, a user can only use the back button to return to their search results.  They then lose their filters and have to reenter.
- Add a "< Back to results" link to all opportunities.
- When selected the will return to the search results page and maintain all of their search filters/pills/keywords previously entered.

Mock: 
https://opm.invisionapp.com/share/UHNZS9XEYR8#/323746480_State_-_Opportunity3_-Desktop-

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35772&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
10/31/18 - this issue came up again testing acquisitions.  Entered career field of acquisition, received 20 results, clicked back and lost career field.  Had to reenter each time.

**Comment by Kibrahacha67** [comment]
12-19-18 LHammond in testing

**Comment by kbwagner** [comment]
1/3/19 - Tested in Chrome.

@kikaider05 - this has the same issue as the back button ticket with the Time commitment filter.  If I have one time as a filter, I get results, click back to results link and one time is still a filter but I get no results now.

**Comment by kbwagner** [comment]
Discussed with Brice - moving back to dev until code is pushed.
- I still need to test the restrict to agency checkbox filter but Brice said it's been removed when signed out and he needs to put in a new ticket:

**Comment by Kibrahacha67** [comment]
1-10-19 LHammond in testing

**Comment by kbwagner** [comment]
1/16/19 - This link was removed on deploy to production so unable to test.
Moving back to development so we can remember to add this back to search results link in test, UAT, Prod and retest and deploy.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-18-19 LHammond in testing.
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/24/19 - Kwagner tested in Chrome/Test environment.
Ready for final review.
