### ISSUE TITLE
Add numbers beside filters

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2189]
idea is to add the number of results for each of the filters like we show on Core...would be good to know when you are going to filter yourself out of results

![image](https://user-images.githubusercontent.com/18709918/40075796-391285f6-584b-11e8-97f1-6424af6dc8e0.png)

Release 2 bug bash

**Comment by bmcorum** [comment]
This is easier said then done. In Core these numbers are provided by Elasticsearch which we do not have in Open Opportunities. Generating all those counts ourselves could be costly and slow.

**Comment by bmcorum** [comment]
@kbwagner now that we are leveraging Elasticsearch this is something we can discuss, and is now more easily achievable.

**Comment by kbwagner** [comment]
1/30/2020 - With elastic this will be easier.  This would be a nice feature to add when we have time but low priority.

**Comment by nia-johnson** [comment]
Closed. Added to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41450&_a=edit
