### ISSUE TITLE
People: Add sort

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2191]
Who: Open Opportunities users
What: Sort people search by columns
Why: In order to narrow down my results

Acceptance criteria: 
- add a Sort by dropdown on the People Search results page
- The sort by would include:
Relevance (highest relevance to lowest)
Name (sort by last name A-Z)
Title (A-Z)
Agency (A-Z)
Location (A-Z) - location sort is state (A-Z) then city (A-Z)

Default sort is - highest relevance

Request Source: Release 2 bug bash

Mock: https://opm.invisionapp.com/d/main#/console/16603537/344286038/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-26-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
7/2/19 - Kwagner tested in Chrome/Test and worked
- Would like to test in mobile before passing but getting Akamai message.

**Comment by kbwagner** [comment]
7/8/19 - KWagner tested in mobile and looks good.
Ready for final review.
