### ISSUE TITLE
Add help question mark beside toggle

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2198]
User Story:
As an open opportunities creator, I would like to be able to read more information about how the toggle button on the opportunity works.

Acceptance Criteria: 
- Add a question mark above the toggle field on the View Opportunity page. 
- The question mark will link to the following help content: https://usajobs.github.io/openopps-help/opportunity/accept-applications/  Note: Content has not been pushed out to this link yet.

**Comment by raywilliams** [comment]
Can we change the AC to add the Help above the toggle box? I talked it over with Min, and she's okay with the look.

![image.png](https://images.zenhubusercontent.com/5a6f64004b5806bc2bc4be2c/d3801fd5-1775-4f3c-a001-c39c3463d5fb)

**Comment by kbwagner** [comment]
@raywilliams - AC updated.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
06/05/18 - Mdumas - In testing...

**Comment by kbwagner** [comment]
6/6/18 - KWagner tested in  Chrome and mobile Safari.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved

**Comment by LisaLNelson** [comment]
Approved.
