### ISSUE TITLE
Character Limit on Skills field

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2211]
User Story: As an open opportunities creator and applicant, I want skills to be reasonable, short, and concise.

Acceptance Criteria: 
- Modify the skills field on opportunity create to be no more than 35 characters
- For any existing skills, leave them as is, they do not need to be shortened.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
06/7/2018 - Mdumas - In testing...

**Comment by margaretdumas** [comment]
06/7/2018 - Mdumas

I am moving this back to development.  I am only allowed to enter 35 characters or less but I can choose a skill that is already in the list that contains more than 35 characters.

**Comment by kbwagner** [comment]
moving back to development per Margaret.

**Comment by margaretdumas** [comment]
Mdumas - Back to development. 

 The only way that I can save on a new opportunity when selected a skill from the list that currently contains more than 35 characters is by adding a second skill.  I think the first one throws a back end error.

**Comment by margaretdumas** [comment]
Mdumas - I could not reproduce the potential issue to show the developer.  Moving back to review.

**Comment by kbwagner** [comment]
6/11/18 - KWagner tested in Chrome and mobile. 
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved.
