### ISSUE TITLE
Make profile name hyperlink clickable

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2212]
When signed in, the profile picture or initials link should be clickable to take the user to the person's profile page.

This occurs on:
- Opportunity Page creator 
- Opportunity page applicants and assigned participants

**Comment by bmcorum** [comment]
@margaretdumas this is ready for testing.

**Comment by margaretdumas** [comment]
05/21/18 - Mdumas - In testing.

**Comment by margaretdumas** [comment]
Mdumas - Testing good, on to review.

**Comment by margaretdumas** [comment]
Mdumas - Moving back to development.  Link text overlaps in IE for participants.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-18 LHammond in testing

**Comment by kbwagner** [comment]
5/24/18 - Kwagner - tested in Chrome and mobile Safari
@LisaLNelson ready for final review

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-30-18 LHammond in testing

**Comment by kbwagner** [comment]
5/30/18 - Kwagner - tested in Chrome and mobile Safari.
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Tested inChrome. Approved
