### ISSUE TITLE
How many people do you need field - make icons instead of dropdown

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2213]
User Story: As an opportunity creator, I want to have a clear way to select how many people I need to help on my opportunity.

Acceptance Criteria: 
On the create opportunity page, modify the how many people do you need field
- It will no longer be a dropdown
- Remove team as a value for any new opportunities created.  
- Replace dropdown with 3 icons for the remaining values
- see attached screen shot

Existing Data:
- For any existing data with the value of "A Team" change to the 5 plus option

Screen Shot: 
![screen shot 2018-05-31 at 3 37 18 pm](https://user-images.githubusercontent.com/18709918/40806634-1ec335d6-64f0-11e8-8edd-4147eee67325.png)

**Comment by bmcorum** [comment]
We could remove the need for another tag entity type for number of people and just add a number of participants to task table. Should also increase database performance.

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-23-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/23/19 - KWagner tested in Chrome/Test
Ready for Final review
