### ISSUE TITLE
A trailing space after the user last name is causing only one initial to display for that user

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2215]
If the user name text field in the profile has a trailing space, it will cause  only one initial to be displayed.  The user can edit his profile and delete the trailing space to correct this on his own. 

Steps to reproduce:
1.  Edit profile and navigate to the name field
2.  Add a space at the end of the last name and save the profile
3.  Navigate back to search for the user 

Results:  Only one initial will be displayed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-18 LHammond in testing

**Comment by kbwagner** [comment]
5/24/18 - KWagner - tested in Chrome.  
@LisaLNelson ready for final review

**Comment by LisaLNelson** [comment]
Approved
