### ISSUE TITLE
Location field should always display in search filters.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2218]
### Who
Open Opportunities 

### What
Location filter functionality

### Why
Give users the ability to filter opportunities by location

### Acceptance Criteria
- On the search filters, the user should be able to do the following: 
   - View location field in search at all times and the the "In person" checkbox will be removed. The system will assume that an entry in the location field is a search for In Person opportunities 
   - Type an entry in the Location field and have matching locations appear in a dropdown 
   - Make a selection by hitting Enter 
   - While un-selected view placeholder text in the Location field

### Related Tickets 
None

### Mocks
None

**Comment by bmcorum** [comment]
@kbwagner I believe the location filter is set to only display when you are looking for "In Person" opportunities. If we are going to show the location field at all times then the "In Person" checkbox becomes redundant and should be removed.

**Comment by kbwagner** [comment]
@abudz  - potentially have banner go all the way across
@nia-johnson can you please enter a design ticket for filter on location in search

**Comment by kbwagner** [comment]
@nia-johnson can you do this one for the next sprint 2/6/2020
- In person become the label for the location filter instead of a checkbox
- placeholder start typing to select location

**Comment by kbwagner** [comment]
@nia-johnson I would add this info into the AC - the location filter exists now but doesn't always display.  We want it to always display but then it requires a change in the name of the filter to make sense

In person become the label for the location filter instead of a checkbox
placeholder start typing to select location

![image](https://user-images.githubusercontent.com/18709918/73694755-be555400-46a6-11ea-9451-71badd5d2998.png)

**Comment by nia-johnson** [comment]
@kbwagner Not sure how the label change affects business logic, so I'm guessing that the user will only be able to select a location when the "In Person" box is checked.

**Comment by kbwagner** [comment]
Currently the location box doesn't even display until the in person box is checked but we want it to always display.  If I recall, we said to remove the checkbox for In person and if they add a location it's basically going to assume they want in person and add that pill and search on that location.  So it's not really a label change as much as it's removing the checkbox for In Person, always displaying location, and what happens when you select location (pills for in person and location added).  Hope that makes sense...hard to explain.

**Comment by nia-johnson** [comment]
@kbwagner Changed

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41544&_a=edit
