### ISSUE TITLE
Privacy Link incorrect in footer

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2223]
The privacy link in the Open Opps footer links to a "fake" site: http://usajobs.github.io/Help/privacy/
The correct link is: https://usajobs.github.io/openopps-help/privacy/

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-31-18 LHammond in testing

**Comment by kbwagner** [comment]
6/4/18 - Kwagner tested in Chrome and mobile.  
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved
