### ISSUE TITLE
Email Opportunity creators when people sign up for their opportunity.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2231]
User Story: As an opportunity creator, I want to receive an email notification when someone applies to a position I created.

Issue; Currently opportunity creators are not notified when someone signs up for their opportunity. We need to send an email notifying them them someone new applies.

Acceptance Criteria: 
Create a new email that is sent to the opportunity creator when an applicant applies to their position.

Audience – Opportunity Creator

Trigger – When someone applies to an opportunity.

Email Subject  - Someone has applied to your opportunity

Email body -

Hi <insert Opportunity Creator Name>,

Good news! <Insert applicants name> has applied to your opportunity, <insert opportunity name>;( link
it to the opportunity detail page).

Take a moment to review their profile and call or email them to make sure they’re the right person for
the work.

Review <applicant’s name>'s profile. (link to the applicants profile).

Are they a fit? (formatted blue and bold - see attached)

Go to your opportunity and click + to assign the person to the opportunity—once done, click Next Step.
We’ll send an automatic email to the participant telling them they’re assigned.

Thanks,
The Open Opportunities Team

The standard Open Opps email footer will appear in the email. 

See attached 
[2231 Open-opportunities-email-content-for-new-applicant_20180529_v2.docx](https://github.com/openopps/openopps-platform/files/2052142/2231.Open-opportunities-email-content-for-new-applicant_20180529_v2.docx)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-11-18 LHammond in testing

**Comment by kbwagner** [comment]
6/12/18 - Kwagner tested
@LisaLNelson ready for final review

**Comment by LisaLNelson** [comment]
Approved.
