### ISSUE TITLE
Display Viewing Numbers at top of search results

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2235]
User Story: As an Open Opportunities user, I would like to know how many opportunities are displayed in my search results

Acceptance Criteria: 
- Display "Viewing 1-x of y opportunities" at the top of search results in both mobile and desktop
- X is the total number displayed on the page; ticket 1960 sets a limit of 10 per page
- Y is the total number of opportunities displayed per the search results and filters based on the user's search criteria

Related Tickets:
1960 - Display 10 Opportunity Cards per page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-6-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-7-18 LHammond in testing 
completed testing moving to review.

**Comment by kbwagner** [comment]
6/7/18 - KWagner tested in Chrome and mobile Safari
@LisaLNelson ready for final review

**Comment by LisaLNelson** [comment]
Approved.
