### ISSUE TITLE
Separate skills and interests on the profile page

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2246]
Issue: Skills and interests should be separate boxes on the profile page so it is clear what skills someone has vs what they want to learn more about.

Acceptance Criteria:
- On the profile page only, separate skills and interests
- The label on the Profile display page will change from Skills and interests to a main header of Skills and then two subheaders of "I have experience with" and "I want to develop"
- modify the field titles on the edit page as well.  Skills will change to "I have experience with" and Interests will display as "I want to develop"
- Separate the display of skills and interests on the profile display page to display under the new fields of "I have experience with" (skills) and "I want to develop" (interests)
- On the edit page, change the text in the blue instruction boxes:
I have experience with blue box text will read, "List your skills, specific knowledge and abilities."
I want to develop blue box text will read, "List the skills, specific knowledge and abilities you want to develop or get more experience doing."

Prototype:
https://opm.invisionapp.com/d/main/#/console/13386795/288408607/preview

**Comment by Kibrahacha67** [comment]
6-5-18 LHammond In Testing

**Comment by kbwagner** [comment]
6/6/18 - KWagner tested in Chrome and Mobile Safari.  
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved.
