### ISSUE TITLE
Mobile: Default text for series and skill filters cut off

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2247]
Default text for skill and series is cutting off in mobile (Safari)

Steps to Reproduce:
1)Click on Filter on mobile
2) View skill and series fields. Default text cuts off at "start typing to select a".  If you click off the field and onto another it will resolve correctly.

Low priority mobile display issue.

![cut off text](https://user-images.githubusercontent.com/18709918/41363813-eb585e66-6f02-11e8-8c98-c47eeab1b790.jpg)

**Comment by kbwagner** [comment]
6/4/18 - KWagner - verified still an issue

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-18 LHammond in testing

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-26-18 LHammond in testing

**Comment by kbwagner** [comment]
6/26/18 - KWagner tested in mobile Safari
Ready for final review.

**Comment by tlorrison** [comment]
approved
