### ISSUE TITLE
Mobile: Related Keyword display issues on create

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2248]
Issue: Create opportunity on mobile, slight display issues for related keyword
![related keywords 2](https://user-images.githubusercontent.com/18709918/40745286-09ea2014-6425-11e8-9046-8890504dd156.png)
![related keywords 1](https://user-images.githubusercontent.com/18709918/40745287-09f8b994-6425-11e8-8aad-6f15218cad92.png)

Steps to Reproduce: 
1) On mobile device, select create opportunity
2) Scroll down to related keywords:
- Enter keywords and go to a new field.  the bottom section of the field no longer displays
- If there are less than 5 keywords entered and I tap on the field, I do not see a cursor (do on other fields) so I don't realize I can still type to add more.  

Low Priority mobile display issue

Screen shots attached.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
6/21/18 - KWagner tested on mobile Safari
- ready for final review.

**Comment by tlorrison** [comment]
approved
