### ISSUE TITLE
Opportunity Applicants should have completed profile in order to apply.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2249]
If an applicant applies for an Open Opportunity but doesn't have a completed profile they  should not be allowed to apply.  

Suggestion: a pop up box that tells them they will not be considered for an opportunity unless they complete their profile.

**Comment by bmcorum** [comment]
@LisaLNelson we will need to define what a complete profile looks like. What data is required vs optional.

**Comment by LisaLNelson** [comment]
@bmcorum @tlorrison My thinking is in addition to what is currently required it should be skills and interests but that should probably be a larger conversation with others.

**Comment by kbwagner** [comment]
We now display a pop up when they apply with check marks and notify them if they have not completed their profile or skills.

**Comment by bmcorum** [comment]
Handled with #3960
