### ISSUE TITLE
Opportunity creators should be able to endorse people who complete their opportunity.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2250]
This provides opportunity creators with some info as to the skills level of an individual.

**Comment by kbwagner** [comment]
@nia-johnson Can be moved to TFS under customer experience
- add TFS link here and then close once entered

**Comment by nia-johnson** [comment]
Closed. Added to TFS. 
https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS-New/_workitems?id=41406&_a=edit
