### ISSUE TITLE
Mobile: Screen flashing after entering skills/filters

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2251]
Mobile screen flashes after entering filters

Steps to Reproduce: 
1) Login to mobile as an administrator
2) Select Search Opportunities and then Click filters
3) Enter 5 skills
4) Click on Career field
Screen starts flashing
- does not seem to happen when logged out.
- does not seem to happen with a non admin account.

**Comment by Kibrahacha67** [comment]
6-26-18 LHammond in testing

**Comment by jhanson12** [comment]
There is currently no solution to fix this issue for this version of select2 component.  Only option is to update to the latest version, 4.*.

**Comment by raywilliams** [comment]
The screen flashing does not appear to happen anymore, perhaps from iOS updates or Safari updates.

**Comment by Kibrahacha67** [comment]
11-27-19 LHammond in testing
Tested in UAT and Test on Safari iphone 11 and cannot duplicate this issue.  Moving to review.

**Comment by kbwagner** [comment]
12/2/19 - Tested and seems to be working now.
