### ISSUE TITLE
Change text on Search boxes

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2253]
User Story: As an open opportunities seeker, I want help links to be clear to help me find the right information.

Acceptance Criteria:
- For both the Acquisition and general Searches, change the following in the dark blue search header:
- Change "Learn more about Open Opportunities" to read "What is Open Opportunities?" 
- Open Opportunities will still be a link and the icon will still display at the end.

**Comment by Kibrahacha67** [comment]
6-5-18 LHammond In Testing

**Comment by kbwagner** [comment]
6/6/18 - KWagner tested in Chrome and mobile Safari

**Comment by LisaLNelson** [comment]
Approved.
