### ISSUE TITLE
Pills are not per the design system

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2256]
Issue: Status pills on the profile, opportunity card, and opportunity are not all the same size.  This is especially noticeable on the profile when they are stacked in a table format.

Resolution: Status pills on profile, opportunity card, and opportunity should all be the same size per the design system: http://usajobs.github.io/design-system/pill/

![image](https://user-images.githubusercontent.com/18709918/41360696-597ab324-6efb-11e8-9a45-09ce29e5f111.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-19-18 LHammond in testing
Tested in chrome, ie, edge and safari (iphone7), moving to review.

**Comment by tlorrison** [comment]
approved
