### ISSUE TITLE
Allow admins to manage skills and keyword data entered into system

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2263]
Issue: Duplicate and misspelled data is being entered into the skills and keywords fields.

Solution: allow for full admins (not agency admins) to manage skills and keywords data entered into our system by users

**Comment by kbwagner** [comment]
Skills Engine should resolve this.

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41506&_a=edit
