### ISSUE TITLE
New users cannot log in

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2265]
Some users when creating a new account are unable to log in even after preforming a password reset several times.

Environment: Production 
Steps to Reproduce:
1) Click sign in
2) Click "Create new account"
3) Enter requirement information
4) Click Create account
- Create account button doesn't seem to work.  If you click again you get "registration failed"
- Account is, however, created and emails are sent out
- Clicking forgot password does not work and Admin resetting password does not work

**Comment by bmcorum** [comment]
@margaretdumas this is ready to test.

**Comment by margaretdumas** [comment]
06/7/2018 - Mdumas - Passed testing.

1. Was able to Create a new account
2.  Was able to reset password for new account and sign back in
3.  Was able to sign into existing account
4.  Tried to create second account with current credential (this passed with error message)

Moving on to review...

**Comment by kbwagner** [comment]
6/12/18 - Kwagner - passed testing.

**Comment by LisaLNelson** [comment]
Approved.
