### ISSUE TITLE
Profile Photo enhancements

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2267]
### Who 
Open Opps Users 

### What
Make it easier for users to upload a complaint profile picture 

### Why
Optimize the usability of the Open Opps platform.

### Acceptance Criteria
The user should be able to do the following: 
- View what types of files are allowed.  
-- Open Opps allows the following file types png, jpg, jpeg, gif, and bmp
- View proper error messaging if the wrong type of file is uploaded.

### Mocks / Related Tickets
None

Release 1 and 2 bug bashes

**Comment by kbwagner** [comment]
@kbwagner test this to see if this is still happening

**Comment by kbwagner** [comment]
#1 above has been resolved - a remove link now exists
![image](https://user-images.githubusercontent.com/18709918/72952215-2d55b300-3d5f-11ea-8224-0b78d130eceb.png)

#2 - you now get an error message when uploading an invalid image type
![image](https://user-images.githubusercontent.com/18709918/72952301-68f07d00-3d5f-11ea-818f-d95e19307e43.png)

Discuss during backlog review:
1) need to photo rotator?
2) need to list out valid file types or update error message with valid file types?

**Comment by kbwagner** [comment]
1/30/2020 - 
Decision not to add rotator

Decision to yes update message with valid file types on error message
.png, jpg., jpeg, gif, and bmp 

@nia-johnson can you please update AC and get this ready for 2/6

**Comment by kbwagner** [comment]
@nia-johnson this one looks fine but can you do some research whether the values should be a. or not.  I.e. should it be .jpeg or jpeg?  We should probably either take all the dots off or leave all the dots on.  thanks!

**Comment by nia-johnson** [comment]
@kbwagner From my research, either way works. I'm leaving periods off.

**Comment by kbwagner** [comment]
@nia-johnson thanks...and I just went to see what we do in USAJOBS and no periods either so we're being consistent. Thanks for researching.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Atlas/_backlogs?level=Backlog%20items&showParents=false&_a=backlog
