### ISSUE TITLE
People page does not filter out disabled users

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2268]
Issue: The People page does not filter out disabled users

Steps to reproduce:
1) As an admin, disable a test user account through Admin --> Users
2) Go to People
3) Search for disabled user, they still show up.

Resolution: Change the People view so that only enabled users display.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-19-18 LHammond in testing

**Comment by kbwagner** [comment]
6/20/18 - Kwagner tested in Chrome.  Ready for final review.

**Comment by tlorrison** [comment]
approved
