### ISSUE TITLE
Badge: Change name of instigator badge to make more meaninful

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2272]
Change name of Instigator Badge to something like Originator or something else 
Release 1 and 2 bug bash

**Comment by kbwagner** [comment]
1/30/2020 - Would like to review all badges 
@nia-johnson this can be moved to TFS Customer Experience

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41505&_a=edit
