### ISSUE TITLE
Create Opportunity: Don't display errors until tab out or save/preview

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2274]
Create opportunity should not display error messages as soon as you click on the field.

This issue occurs on: 
- Skills
- Introduction

Steps to Reproduce:
1) Select Create Opportunity
2) click on the skills field - an error message immediately displays

Resolution:
Error messages should only display when the user tabs out of the field or saves

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-18 LHammond in testing

**Comment by kbwagner** [comment]
6/20/18 - KWagner tested in Chrome and mobile Safari
ready for final review.

**Comment by tlorrison** [comment]
Approved
