### ISSUE TITLE
Revamp Opportunity Comment Section 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2275]
### Who
Open Opps Users 

### What
The comment section for individual opportunities needs to be updated for clarity and user-friendliness. 

### Why
Enter the reason(s) why the user needs the feature or functionality.

### Acceptance Criteria
The user should be able to do the following: 
- View reply threads nestled under the original post (similar to Facebook) 
- View replies to replies on the same level as other replies in the thread. 
- View top two replies are shown initially with "show more" accordion button when page loads
-- Click "show more" button and view all comments under a thread
- View deleted top-level comments (non-replies) as a static box in it's place with text indicating the comment needs to be deleted. 
- View stationary comment box at bottom of the page and use comment box to post to the main comment section 
- Click reply under a comment, additional comment box appears under original comment, and post. 
- Click reply under a reply, comment box appears at appears at the bottom of the reply thread with a tag of the user being replied to. 
- Users should be able to delete and edit their comments (kebab menu, maybe?) 
- Click the delete button, an "are you sure" modum should appear 
- Click the refresh button to see comments posted after the page loaded. 

### Related Tickets 
https://github.com/USAJOBS/team-design/issues/164

### Mocks
Will update when mocks are available. 

**Original AC** 
When replying to a comment on an opportunity:
1) Don't include the original text in the comment
2) Next the comment reply under the original comment to keep them together.-

Release 2 Bug Bash

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/72374093-98581780-36d7-11ea-88d2-8ddbe72dd964.png)

**Comment by nia-johnson** [comment]
We will probably have to break this up into smaller stories. Will do so after I receive the mocks from Design.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41533&_a=edit
