### ISSUE TITLE
Fix modals in system to match design system

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2278]
Confirmation Modals do not match the design system.  
The header color is wrong and we should use smaller button

Design system link: http://usajobs.github.io/design-system/modals/

![screen shot 2018-06-04 at 2 21 58 pm](https://user-images.githubusercontent.com/18709918/40937813-ddc31d32-680d-11e8-8603-56aad2002c83.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-19-18 LHammond in testing

**Comment by kbwagner** [comment]
6/20/18 - KWagner tested in Chrome (submit opportunity modal, admin modal)
Ready for final review.

**Comment by tlorrison** [comment]
Approved
