### ISSUE TITLE
508 - Change Owner modal is not accessible by the Keyboard

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2280]
Interface component or function must be accessible by the Keyboard. The Change Owner modal does not allow keyboard interactions.  Make modal keyboard accessible to

**Comment by Kibrahacha67** [comment]
6-6-18 LHammond in testing
Testing completed in ie, edge and chrome.  moving to review.

**Comment by kbwagner** [comment]
6/7/18 - KWagner tested in Chrome with Margaret's tips on how to test
The easiest way would be to use your mouse to go to administration, tasks.  Once there start using your keyboard tab key to tab around the  page until you have an event that you can change owner.  Tab to the change owner icon, press the enter key or space bar to select.  That should open the modal.  Use the tab key to highlight the dropdown on the modal, then the down arrow to move to a person in the list

@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
Approved
