### ISSUE TITLE
Investigate upgrading select2 to latest version

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2295]
spike to investigate upgrade select2 to the latest version

For Safari and mobile, there is an issue with Select2 which is the underlying functionality that gives the drop down its abilities. It is a know bug and will have to be addressed by the dev team (upgrade of select2) at a future date. So for IPhone and Mobile devices this functionality will be problematic. Will probably need some discussion around this from a team perspective to decide how to move forward with this.

**Comment by kbwagner** [comment]
Should be done in sprint 6/7 Feb/March 2020 timeframe

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41588&_a=edit
