### ISSUE TITLE
Profile buttons out of line

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2316]
Steps to reproduce:
1) Go to profile
2) Click edit
- save and discard buttons are not lined up

![image 5](https://user-images.githubusercontent.com/18709918/41363935-324895d4-6f03-11e8-9045-2ba3b2b9a9d9.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-15-18 LHammond in testing

**Comment by kbwagner** [comment]
6/17/18 - KWagner tested in Chrome and IE
@LisaLNelson ready for final review.

**Comment by tlorrison** [comment]
approved
