### ISSUE TITLE
Update Leslie Field's title on the Landing Page

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2322]
Change: Lesley Field, Acting Director of OFPP to learn more.

 To: Lesley Field, Deputy Administrator for Federal Procurement Policy at U.S. Office of Management and Budget

**Comment by bmcorum** [comment]
Announcement text is managed by administrators via the admin dashboard with ticket

#2031 - Admin: Ability to manage Announcement text
