### ISSUE TITLE
All applicants for a task are appearing in Latest Achievements on the home page

### ISSUE THREAD

**Issue by tlorrison** [openopps/openopps-platform#2323]
Issue: When an opportunity is successfully completed, all opportunity applicants appear on the home page instead of just the selected participant(s) that successfully completed the task. Only selected participants who successfully complete a task should appear on the home page.

Steps to reproduce: In UAT, please see “Bean Counter was completed with the help of Debbie LeNard and Teresa Reefe.” on the home page. The opportunity was only completed by Teresa, but Debbie (an applicant) is also showing on the home page.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-18 LHammond in testing
completed testing moving to review.

**Comment by kbwagner** [comment]
6/20/18 - KWagner tested in Chrome.  Test test test has 3 participants but only Katrina Wagner completed and she is the only one that displays on the homepage.

**Comment by tlorrison** [comment]
approved.
