### ISSUE TITLE
npm reports vulnerabilities in modules

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#2329]
updating openopps, I upgraded to latest node v8.9.x and npm report vulnerabilities...

```
nvm use v8.9.4
npm install
npm i -g npm

audited 7552 packages in 13.812s
found 128 vulnerabilities (60 low, 49 moderate, 19 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by bmcorum** [comment]
We are looking into integrating Code Climate plugin [Node Security](https://nodesecurity.io/) to detect and report on vulnerabilities and upgrade recommendations.

**Comment by bmcorum** [comment]
This should always be an ongoing task to fix detected vulnerabilities.
