### ISSUE TITLE
Navigation Updates (again)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2334]
User Story: As an open opportunities user, I would like the navigation on the site to be consistent with the other USAJOBS products and design system.

Acceptance Criteria:
- Update the navigation styling and location of sign out - move to the right and make it smaller
- Mock: https://opm.invisionapp.com/d/main/#/console/13386795/300494469/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-18 LHammond in testing

**Comment by kbwagner** [comment]
6/20/18 - KWagner tested Chrome and mobile Safari
Ready for final review.

**Comment by tlorrison** [comment]
approved
