### ISSUE TITLE
OpenOpps - Create Community

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2349]
### Should only system administrators create communities?
If yes
- What information needs to be collected the first time?
    - Community name
    - Assign at least 1 community manager

### Can anyone create an community?
If yes
- Should it require approval from a system administrator like an opportunity? 
- What information needs to be collected the first time?
    - Community name
    - Community description

## Possible structure of a community
- Name
- Description/About
- Frequency (cyclical - requires a new cycle with date range to create opportunities, ad-hoc)
- Target audience (federal, student)
- Target type (program, career field, agency)
- Type (open - anyone can join, closed - invitation only)

![image from ios](https://user-images.githubusercontent.com/1165615/45433769-e2139680-b67a-11e8-8bee-b6b10e69b04d.jpg)

**Comment by kbwagner** [comment]
This has been completed
