### ISSUE TITLE
Spike: iPhone profile pictures load sideways

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2353]
Issue: Pictures loaded to profile on an iPhone are loaded rotated.

Steps to reproduce:
1) On iPhone Safari log in and go to profile
2) Click edit profile
3) Click upload
4) Select either Take Photo or Photo library
5) Select a photo or take a new photo
- Photo displays on the page rotated to the left and user is unable to change rotation.

![image-1](https://user-images.githubusercontent.com/18709918/41684457-7d3a04bc-74ab-11e8-9be0-1679704f02c5.jpg)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-6-19 LHammond in test
test 1 the photo was off center to the left
test 2 it did the same thing described above with the picture being turned to the left.  moving back to development.

**Comment by bmcorum** [comment]
@Kibrahacha67 can you validate whether or not newly captured photos upload oriented correctly?

If newly captured photos work we are getting the Exif data from the iPhone. If older photos from your library are not being properly oriented then iPhone is not sending us the proper Exif data.

@kbwagner we may need a new ticket to look at giving users the ability to rotate their photo after it has been uploaded.

**Comment by kbwagner** [comment]
@bmcorum there is already a ticket on the backlog to add rotate and delete to photos in the future.

**Comment by kbwagner** [comment]
It's 2267

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-6-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
9/9/19 - Uploaded new photos to Mary Poppins in Test - both vertical and horizontal and they loaded correctly.
Ready for final review
