### ISSUE TITLE
Admin Dashboard: Menu Items 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2362]
User Story: 
As an administrator, I want to have clear menu items in the dashboard to help me easily navigate.

Acceptance Criteria: 
- Update the Administration dashboard menu items to be:
1) Sitewide - this displays only for full admins
2) Agency - this displays for full admins and agency admins
3) Community - this displays for full admins and organization admins  (Note: This is different from the mock that currently says "Organization")

The main admin landing page will display as three columns: Users, Opportunities, and Interactions.  All will be handled by separate tickets.

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by kbwagner** [comment]
Changed organization to community based on sprint planning

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this ticket is reading for testing.

**Comment by Kibrahacha67** [comment]
7-10-18 LHammond in testing

**Comment by kbwagner** [comment]
7/12/18 - KWagner tested in Chrome as admin and agency admin.  

@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
