### ISSUE TITLE
Admin Dashboard: Section 1: Opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2364]
User Story: As an administrator, I want to be able to view and approve all opportunities by status.

Acceptance Criteria: 
On the Administration --> Sitewide page, Opportunities will display as the second column of information.
- There will be a Manage link 

1) Sitewide page --> Opportunities will display: 
- Total Created - Total created’ should be the total number of Opportunities sitewide for all statuses including cancelled but NOT including draft
- Submitted: Total number of opportunities sitewide that are currently in Submitted status
- Open: Open will include both open and in progress accepting applicants opportunities sitewide
- Not open; Total number of opportunities in not open status sitewide
- In progress: Will include only in progress not accepting applicants opportunties.  Omit in progress opportunities that are accepting applicants.  Sitewide
- Completed: Total number of sitewide opportunities in Completed status
- Canceled: Total number of sitewide opportunities in Canceled status
- No data on drafts will display at this time
InVision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

2) When the Manage link is selected beside Opportunities, the following will display
- Header will read "Opportunities"
- Status will display pills for each status with a radio button.  The number of opportunities in that status will display beside each pill
- Column headings will change depending on the status selected.  See mock. (no change)
- For submitted, The checkmark will approve the opportunity and provide a confirmation modal (no change)
- For submitted, The delete X will disapprove and provide a confirmation modal (no change)
- The default sort order for this page will be by date (most current to least current)
- At the bottom of the page, there will be a Download list.csv.  This will initiate the process to download opportunities (existing report).  
- Default sort order will be the filter and then created date (newest to oldest)

Notes: 
- Across the board all numbers over 3 digits should display with a comma.  All percentages should display a percent sign after.
- Data should not include legacy/archived data

Invision Mock for Manage Opportunities: https://opm.invisionapp.com/d/main#/console/13386795/300494464/preview
- Manage -  Opportunities in Open Status: includes change owner and add participant
https://opm.invisionapp.com/d/main#/console/13386795/300494463/preview
-  Manage - Opportunities in Not open status: includes change owner and add participant
https://opm.invisionapp.com/d/main#/console/13386795/301582958/preview
- Manage - Opportunities in In Progress Status: includes change owner and add participant https://opm.invisionapp.com/d/main#/console/13386795/300494461/preview
- Manage - Opportunities in Completed status includes Publish and Delete
https://opm.invisionapp.com/d/main#/console/13386795/300494462/preview
- Manage - Opportunities in Submitted status includes Publish and Delete https://opm.invisionapp.com/d/main#/console/13386795/300494462/preview

Related ticket: 
2389 - Sort by for opportunities list 
2392 - Changes to download opportunities report .csv.
2393 - Opportunities pagination (removed from 2364 7/10/18 per discussion with Katrina and Jodi)

**Comment by kbwagner** [comment]
7/10/18 - KWagner updated AC to remove - MOVING TO 2393 - Viewing x -y of z opportunities will display under the pills.

**Comment by jhanson12** [comment]
The mock does not show publish and complete for 'Completed' status.  Is the AC correct?

**Comment by kbwagner** [comment]
@jhanson12 follow the mock for that section.  I didn't spell it all out since it's existing functionality.  The only big changes on that section are really applying the pills and some design system changes

**Comment by jhanson12** [comment]
@margaretdumas this is ready for testing

**Comment by margaretdumas** [comment]
07/20/18 - Mdumas - In testing

**Comment by margaretdumas** [comment]
07/20/18 - Meets Acceptance Criteria. Moving to review

**Comment by kbwagner** [comment]
@jhanson12 @margaretdumas  - I was able to verify most of the data counts by downloading the .csv file. But I have two questions:
1) For Open - It should be open and in progress.  By my count that's 142 but the site says 108. Can you help me sort out the difference?  Maybe it's the toggle
2) In Progress - should only include those not accepting applicants.  I don't have access to that toggle data so is there an artifact that can show how many in progress jobs have the toggle turned on or off to accept/not accept applicants?  

Thanks!
Katrina

**Comment by kbwagner** [comment]
@jhanson12 - in addition to my questions to verify data above, I did find one issue.
- when you click on the manage link and view the opportunities, click on the completed filter, the publish and delete icons should not show up for this status.  Sending back to development.

**Comment by bmcorum** [comment]
See attached artifact below. **NOTE** *in progress* with *accepting_applicants* true is counted as *open* when displayed on Open Opportunities. Number might change if a opportunity is added, deleted or updated.

![image.png](https://images.zenhubusercontent.com/59e8ff8ea468affe6df75add/c98a08b8-8617-4314-bf40-8fe290768dfd)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-1-18 Moving to review LHammond

**Comment by kbwagner** [comment]
8/5/18 - KWagner tested.  @tlorrison ready for final review.

**Comment by tlorrison** [comment]
Approved
