### ISSUE TITLE
Admin Dashboard: Section 1: Interactions

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2365]
User Story: As an administrator, I want to be able to track metrics on user interactions with the system.

Acceptance Criteria:
On the Administration Sitewide tab, the third column of data will display Interactions
The following information will display in Interactions section: (Note: labels are different then mock - follow the AC).  All numbers will be for sitewide, no timeframe, and will not limit to unique applicants.
- Total applications - total number of everyone who has applied to an opportunity sitewide.  Not unique applicants.  This should anyone who has applied that is an applicant + assigned participant + task completed.  As an example, if I have applied to 4 opportunities, I will count as 4 applications.
- Total assigned  - Total number of applicants who were moved to assigned participants for all opportunities sitewide. Includes Task completed.  Not unique.
- Total completed: only those participants who have been marked as task completed.  Not unique participants.  
- Discussion posts: Total number of comments and reply to comments for all opportunities sitewide

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview
![screen shot 2018-07-02 at 1 55 57 pm](https://user-images.githubusercontent.com/18709918/42180027-babd05bc-7e03-11e8-8847-700c8fb63d97.png)

Notes: 
- Across the board all numbers over 3 digits should display with a comma.  All percentages should display a percent sign after.
- Data should not include data with an archived status.

**Comment by Kibrahacha67** [comment]
7-27-18 LHammond in testing

**Comment by bmcorum** [comment]
![screen shot 2018-08-08 at 1 47 41 pm](https://user-images.githubusercontent.com/1165615/43855456-a256925e-9b13-11e8-8232-7c2775e9962e.png)

**Comment by Kibrahacha67** [comment]
8-8-18 All complete moving to review. LHammond

**Comment by kbwagner** [comment]
8/8/18 - Tested in Chrome.  
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
