### ISSUE TITLE
Admin Dashboard: Section 2: Opportunities created

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2366]
Who: Sitewide administrator
What: View dashboard information on opportunity creators
Why: in order to see who is using the system

Acceptance Criteria: 
On the administrator, sitewide dashboard page, the following will display in the second section of the page under Top Contributors and then Creators section:

Heading: 
Top contributors FY## (current fiscal year)

Agency: Display top 5 by created number
- Agency - display the agency name of the creator.  Display all agency/subagency information provided (i.e. DHS/Customs)
- # of opportunities created - display the total number of opportunities created whether published or not. (does not include drafts) in the current fiscal year
- The default sort will be sorted by greatest to least number. 
- Display for agency should be agency/department when possible (e.g. NIH/HHS or FSIS/USDA) name so we can see who our biggest users are, as well as where we need more outreach)

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-16-19 @bmcorum - please attach artifact so I can complete testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-21-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-22-19 LHammond in testing

**Comment by kbwagner** [comment]
9/3/19 - Kwagner tested in Test/Chrome
Ready for final review
