### ISSUE TITLE
Admin Dashboard: Section 2: Participants

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2367]
Who: Sitewide administrators
What: metrics on what agencies have participated in opportunities
Why: in order to see who is using the system

Acceptance Criteria: 
Administration --> Sitewide --> Top contributors --> Participants

Title: Participating in opportunities

1) Agency
- List the agency and the # of opportunities participated (not applied but actually selected to participate)
- For agency, list the agency/department as possible to provide as much info for outreach
- -# will be the number of participants and task completed for opportunities for that agency
- Sort order will be by opportunity participated number

2) Top Contributors report
- At the bottom there will be a Download all contributors (.csv) which will be a separate ticket. 2368

Invision: 
https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-16-19 @bmcorum - please attach artifact so I can complete testing

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/63517702-7b6b3f80-c4bd-11e9-83c0-a8dcd087f6ed.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-22-19 LHammond in testing
