### ISSUE TITLE
Admin Dashboard: Section 2: Top contributors opportunities created .csv

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2368]
Who: Sitewide administrators
What: View top contributors
Why: in order to determine who is creating and applying for opportunities.

Acceptance Criteria: 
Administration --> Sitewide --> Top contributors --> Top Contributors report

At the bottom of the Top contributors Opportunities created section, there will be a Download full list (.csv) link.  When selected, the following will display in a downloaded .csv file: 
- The file name will be: TopContributors_FYXX_Created.csv
- Display rank number, agency name, total created
- All will display in the .csv file not just the top 5.

Mock: Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by kbwagner** [comment]
@jhanson12 @raywilliams @bmcorum - question on this report.  Min had envisioned a .csv file with 4 tabs one for each section of the top contributors.  Is that possible?  If we can only do one tab per .csv then might need to do a link under each section and have it be 4 .csv.  Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-5-19 LHammond in testing
In the .csv file there are top 12 not top 5 as AC requested.  moving back to development![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/41fe7ec7-027f-4b48-8244-5c8b25456510)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-6-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
9/10/19 - KWagner tested in Chrome/Test
Ready for final review
