### ISSUE TITLE
Admin Dashboard: Section 3: Completed Opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2369]
User Story: As an administrator, I would like to see metrics on completed opportunities.

Acceptance Criteria: 
Administration --> Sitewide --> Completed opportunities
- There will be a Period dropdown with values: Fiscal year, Quarter, Month (Important to keep the historical data year over year somewhere).  The default will be Fiscal year  
- There will be Radio buttons for  – All, Ongoing, One time  The default value will be All
- The column headings when fiscal year is selected will be the last fiscal year and the current fiscal year.  Additional years will be added and eventually up to 2 years will display.  Column headings for other display options will be the same as current but limited to FY18 and FY19 data.
- Target audience = student metrics will not be included in these metrics.  

The row titles will be: 
o   Carryover (Not completed)- this row will display data for any opportunities opened in a previous selected time period that have not yet been completed. Note: The subtitle of Not completed is not updated on the mock at this time.  Follow AC.
o   Published - opportunities published in the selected time period
o   Completed - opportunities completed during the selected time period by the opportunity creator
o   Completed by admin - opportunities completed during the selected time period by the administrator 
o   Percentage completed - of the number opened in the time period selected how many were closed
o   Percentage canceled - of the number opened in the selected time period, how many were canceled
o   Applicants - number of applicants to opportunities within the selected time period that applied to completed opportunities.

Where there is no data to display, display "n/a" or zeros as appropriate

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by kbwagner** [comment]
@tlorrison ready for you to review and approve.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/63944094-ef1dc700-ca3e-11e9-97e0-dd55d801131a.png)

**Comment by Kibrahacha67** [comment]
9-5-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-10-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
10/10/19 - KWagner tested in Test/Chrome
ready for final review
