### ISSUE TITLE
Admin Dashboard: Section 5: Edit announcement sitewide admins

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2370]
Who: System Administrators
What: Make changes to current announcement information 
Why:  to keep information current

Acceptance Criteria:
Administration --> Sitewide --> Announcement
At the bottom of the sitewide admin page, display the current announcement text. 
- There will be a Make changes button at the bottom
- When selected, the current announcement page will display.
- Once saved, any updates will display on this page as well as the signed in landing page.

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by Kibrahacha67** [comment]
9-3-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested Chrome/Test
Ready for final review
