### ISSUE TITLE
Admin Dashboard: Section 4 - Recent activity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2371]
Who: Sitewide Administrators
What: Ability to see recent activity
Why: To see what is going on in Open Opportunities

Acceptance Criteria: 
Administration --> Sitewide --> Recent activity
-  List 20 recent activity items with a scroll bar
- Recent activity should include When someone: joins, applies to an opportunity, posts comment, posts an opportunity regardless of whether it is agency of community specific
- names should always link to a profile
- Opportunity names should always be a link to the opportunity
- Target audience student should not display on the recent on Sitewide (i.e. added to a community or anything that occurs within the community.)

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8.22.19 LHammond in testing

**Comment by kbwagner** [comment]
@raywilliams I duplicated an opportunity and clicked cancel but it still shows up here.  I would think it would only show up once I have submitted but the verbiage says "posted".  How has this been working?  
Definitely shouldn't show something I canceled or moved away from.

**Comment by Kibrahacha67** [comment]
9-4-19 LHammond in testing

**Comment by kbwagner** [comment]
9/10/19 - KWagner tested in Chrome/Test
Ready for final review
