### ISSUE TITLE
Sitewide Admin Dashboard: User .csv file changes

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2377]
User Story: As a sitewide administrator, I want to be able to download a list of all users and display related information for each user.

Acceptance Criteria:
When the administrator clicks on Sitewide --> Users --> Manage, they have the ability to download a .csv file of all users.
- The Sitewide CSV should include all users 

The current columns for this report are:
- user_id (do we need this?)
- name
- username (this is email - so change to email?)
- title
- agency
- location
- bio
- admin (add agency admin and organization admin?)
- disabled (True/False)
- announcement - all are blank

New report fields should be: 
- name
- Student/Contractor/Federal identifier (or Hiring path if there are space issues)
- Login.gov email
- Official federal government email
- Last login date
- Account create date
- title
- agency
- location (include Country if not USA)
- bio
- admin (True/False)
- disabled (True/False)

The sort order should be account create date (newest to oldest)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-11-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-15-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-16-19 LHammond in testing

**Comment by kbwagner** [comment]
10/16/19 - KWagner tested in Chrome/Test 
Ready for final review
