### ISSUE TITLE
Acquisitions would like a URL for marketing.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2378]
The Acquisition Community would like a URL that can be used in marketing Acquisition Open Opportunities. The URL should be easy to remember and make it easy to find the acquisition specific page on Open Opps.

**Comment by bmcorum** [comment]
@LisaLNelson, the Acquisitions Community can use the following URL to load the acquisition specific page

https://openopps.usajobs.gov/tasks?career=Acquisition

**Comment by kbwagner** [comment]
Closing - duplicate ticket 4288 entered and is being worked for release 8.6
