### ISSUE TITLE
Admin: Data dictionary for dashboard

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2381]
Create a data dictionary for the Sitewide admin dashboard, Agency Admin Dashboard, and Community dashboard (3 tabs)
- For each section, list out the field, what section of the dashboard it is located on, and how the field value is calculated.

Note: 
- Need to determine where to store data dictionary.  Github possibly?  Or possibly help center?
- 7/19/18 - Katrina/Tracy/Brice meeting - Brice suggested possibly adding a question mark to the admin dashboard that opens a data dictionary in the help center.  Sean suggested doing hover text above fields that would further explain calculations.

**Comment by kbwagner** [comment]
@tlorrison ready for you to review and approve.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41582&_a=edit
