### ISSUE TITLE
Admin Dashboard: Add sort by to User list

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2388]
Who: All administrators 
What: Add sort by to users
Why: To allow administrator to find users easily

Acceptance Criteria:
- Add sort by to all Admin Dashboards for Users  --> Manage page
1) Sitewide
2) Agency
3) Community

**Sitewide Admin** 
Sort by options should be:
Name - A-Z by last name
Federal email - A-Z by the first letter of the email
login.gov email - A-Z by first letter of the email
Created - newest to oldest date
Last login - newest to oldest date
Enabled - Yes then No
Sitewide Admin - Yes then No

Default Sort is: 
Create date - newest to oldest

**Agency Admin:** 
Sort by options should be:
Name - A-Z by last name
Federal email - A-Z by the first letter of the email
Created - newest to oldest date
Enabled - Yes then No
Agency Admin - Yes then No
Default Sort - Created - newest to oldest

Community Admin: 
Sort by options should be:
Name - A-Z by last name
Federal email - A-Z by the first letter of the email
Agency - A-Z by first letter of agency
Joined Date - newest to oldest
Community Admin - Yes then no 
Default Sort - Joined date newest to oldest

Related Ticket: 2363
3781 removes user number from the user page

**Comment by Kibrahacha67** [comment]
9-3-19 LHammond in testing

**Comment by kbwagner** [comment]
9/10/19 - KWagner tested in Chrome/Test
Ready for final review:

Note: We may want to consider all of the blanks for federal email, login.gov email and last login date...they sort to the top.  Would be a separate ticket and can wait and see if we get complaints.
