### ISSUE TITLE
Sitewide Admin: Download opportunities .CSV file changes

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2392]
Who: Sitewide Administrators
What: Opportunities .csv
Why: In order to allow data filtering and mining on opportunities

Acceptance Criteria:
- Admin --> Sitewide --> Opportunities --> Manage
- When a user clicks on the "Download list" csv file, the following information should display
Task id
Title (previously name)
Description
Created date
Published date
Assigned date (note: is this the date someone is selected to participate?  most are blank)
Submitted date
Creator name
Applicants (formerly sign ups)
Selected participants (leave blank if none) - new
Completed participants (leave blank if none) - new
Task State
Agency name
Community name (if applicable)
Completion Date

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-4-19 LHammond in testing

**Comment by jhanson12** [comment]
The assignedAt date was not populate because we had not updated the state from 'assigned' to 'in progress' when we changed at an earlier date.

Fixed now.  This will be for all the CVS tickets with Assigned At data.
@Kibrahacha67

**Comment by kbwagner** [comment]
@raywilliams per sprint planning I added Community name to this file

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-8-19 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum @raywilliams added community name as a field per sprint planning on Friday (added it yesterday morning when it was still in development and tagged ray but I think he was out).  Can this still be added via this ticket or does it need to be a new ticket?

**Comment by kbwagner** [comment]
Confirmed with @bmcorum to send this back to development to have community added.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
10/10/19 - KWagner tested in Chrome/Test
Ready for final review
