### ISSUE TITLE
Admin: Opportunities pagination

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2393]
Who: Administrators
What: Pagination on Opportunities
Why: In order to allow better viewing of opportunities

Acceptance Criteria: 
On the view opportunities section of the admin dashboard, pagination should display.
1) Display 25 opportunities per page 
2) Under the filter pills, display Viewing x -y of z opportunities will display under the pills.  
3) Pagination should display for:
- System Admin
- Agency Admin
- Community Admin

**Comment by kbwagner** [comment]
@bmcorum do I need to separate this into 3 tickets for sitewide, agency and community?

**Comment by bmcorum** [comment]
- [ ] Sitewide admins
- [ ] Agency admins
- [ ] Community admins

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
8-13-19 LHammond in testing
Testing completed moving to review.

**Comment by Piglady64** [comment]
Julie Reviewed - moving to final approval
