### ISSUE TITLE
Admin: User page - add viewing pagination

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2394]
User Story:  As an administrator, I want to be able to see how many users I am viewing.

Acceptance Criteria: 
On the Admin --> Sitewide --> User Section --> Manage page, add Viewing x-y of <Insert total number of users> Total Users 
- X is how many opportunities are being displayed
- Y is the total on the page 
-Total users is both active and inactive
- I.e. Viewing 1-25 of 5200 Total users

Invision Mock: https://opm.invisionapp.com/d/main#/console/13386795/300494465/preview

Related Ticket: 2363 - Admin User section

**Comment by jhanson12** [comment]
I formatted the numbers on this ticket to match criteria from another ticket that requested format of '1,000'  site wide.

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
07/31/18 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
7/31/18 - Mdumas - Moving back to development. Viewing x-xx of xxxx users appear hard coded and doesn't display actual values.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
8/1/18 - KWagner tested
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Approved
