### ISSUE TITLE
Create agency table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2397]
User Story: As a developer, I need to have a separate agency table in order to continue future work with agencies.

Acceptance Criteria: 
- Create a new table for Agency
- Migrate the data from the Tag Entity table to the new Agency table.

**Comment by bmcorum** [comment]
@kbwagner and @tlorrison I think the final bullet point "Remove the agency data from Tag entity when the migration to the new agency table is complete." will need to be a new ticket to refactor the code base to utilize the new agency table as well as a way to pull a more complete agency list from USAJOBS database.

**Comment by bmcorum** [comment]
See attached artifact for new agency table.

![image](https://user-images.githubusercontent.com/1165615/43284912-5462aff6-90eb-11e8-86c8-d35f884c3e49.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-26-18 LHammond testing moving to review.  Artifact attached.

**Comment by kbwagner** [comment]
7/31/18 - @tlorrison ready for final review.

**Comment by tlorrison** [comment]
Approved. @kbwagner were you able to add the ticket Brice referenced into the backlog?

**Comment by kbwagner** [comment]
@tlorrison added 2445 for the refactoring and using USAJOBS. Good catch since I would have sworn I wrote that but can't find it so clearly didn't!
