### ISSUE TITLE
Modify location table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2400]
Acceptance Criteria: 
- Create a new table for Location
- Migrate the location data from the Tag Entity table to the new Location table.
- Remove the location data from Tag entity when the migration to the new location  table is complete.
- Change from a single location field to city, state, country

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35526&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
@bmcorum do we still need this ticket?

**Comment by kbwagner** [comment]
@bmcorum I think we can close this correct?

**Comment by kbwagner** [comment]
8/1/19 - Confirmed with Brice that Open Opps still uses the old location table
- we need to transition opportunities from a single location field to city, state, country

**Comment by kbwagner** [comment]
On opportunity create, they would have to pick a country, then a state, and then a city vs just a free form text box for location (we do this for State internships)

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41504&_a=edit
