### ISSUE TITLE
Login.gov: new user needs to create profile

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2401]
User Story: As a new user to Open Opportunities who has created a login.gov account, I need to create a profile in Open Opportunities.

Acceptance Criteria: This ticket covers what will happen when a user has created a login.gov account but does not have an existing Open Opps account.  From the Find your Open Opportunities profile page, they will click on the "Create a new account" button.

When the Create a new account button is selected, the user will have a new Open Opps account created with the information from their USAJOBS profile populated.  They will be taken to the Open Opps signed in home page.  

Invision Mock: 
- Click on Create Account: https://opm.invisionapp.com/d/main#/console/14696610/313413542/preview

**Comment by kbwagner** [comment]
@bmcorum do we still need this ticket?  Or is it covered elsewhere?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-19-18 LHammond in testing

**Comment by bmcorum** [comment]
The secondary nav is a bug. I just noticed this does not display in some instances when it should.

**Comment by Kibrahacha67** [comment]
11-20-18 Testing completed moving to review and creating a bug for the secondary nav issue...

**Comment by kbwagner** [comment]
11/27/18 - Tested in Chrome.  Ready for final review.
