### ISSUE TITLE
Create Opportunity - Target Audience

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2402]
**User Story:**
As a DOS state user I want to be able to create a student internship opportunity.

**Acceptance Criteria:**
- [ ] Click create opportunity displays a page where users selects target audience
    - Create an opportunity header
    - Who's your target audience?
    - Two selections
        - Federal employees (For development opportunities) - government icon blue
        - Students (For internship opportunities) - book icon yellow
    - Cancel (go back to previous page)
    - Continue
- [ ] On continue Federal employees create opportunity page for federal opportunities is shown
- [ ] On continue Students create opportunity page for internship opportunities is shown

**Reference materials:**
https://opm.invisionapp.com/d/main#/console/14593252/308019691/preview#project_console

**Comment by kbwagner** [comment]
duplicate ticket - closing
