### ISSUE TITLE
State: Create Opportunity (Unpaid Internship) - Target audience

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2403]
User Story:

Acceptance Criteria: 
How do they get to this page?  From the Create Opportunity page if logged in as a state department user?  
- Federal employees
- Students

Invision Mock: https://opm.invisionapp.com/d/main#/console/14696610/308026298/preview

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35525&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
Duplicate
