### ISSUE TITLE
State: Create Opportunity (Unpaid internship) - Student Opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2404]
User Story:

Acceptance Criteria: 
- If student is selected as target audience
- Changes to the create page...list out here.

Invision Mock: https://opm.invisionapp.com/d/main#/console/14696610/308026300/preview

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35524&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
Closing - duplicate
