### ISSUE TITLE
Admin Dashboard: Section 1 - Users - Manage Link

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2410]
User Story: As a sitewide administrator, I want to be able to view information on system users. 

Acceptance Criteria: 
  
On the admin dashboard, When the Manage link is selected for Users: 
- There will be a "<Back" that will navigate the user back to the previous page.
- The header will display "Users" (note: different the mock - follow AC)
- The search box will read, "Filter by name or agency" with a Search at the end
- The total number of active users will display under the search bar.  This number will include active and disabled users.
- The column headers will be: User #, Name, Email, Created (date account created), Account enabled, Reset password, and Admin
- Created will display mm/dd/yyyy hh:mm and then am/pm (displaying leading zeros when necessary so it will all line up)
- Account enabled will be a toggle
- Admin will have a link that reads Assign or Assigned
- When the Assign link is selected, a new page will open called "Assign administrator"
- At the bottom of this section, there will be a download link to "Download list (CSV).  (separate ticket to update this report - 2377). 

Note: 
1) Across the board display commas for any number over 3 digits and display percent signs for percentages. 
2) Do not include legacy/archive data in the counts.

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494465/preview

Related Tickets:
2388 - Sort by for User list
2392 - Add viewing 1-25 of 5200 Total Users to user display
2362 - Admin Dashboard - Section 1 - Users Sitewide navigation
2411 - Admin Dashboard - Section 1 - Users - Assign admin rights

**Comment by jhanson12** [comment]
The mock has the header as "Total users".  I am going by the AC which says to have the header as "Users".

**Comment by kbwagner** [comment]
@jhanson12 fine to go with the AC on this one.  Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
7-31-18 LHammond in testing

**Comment by jhanson12** [comment]
The AC states "The header will display "Users".  There is no design for "The total number of active users will display under the search bar.  This number will include active and disabled users."  This is displayed in the Dashboard summer section as well.

**Comment by Kibrahacha67** [comment]
8-1-18 LHammond Moving to review.

**Comment by tlorrison** [comment]
Approved.
