### ISSUE TITLE
Admin Dashboard: Sitewide -  Section 1 Users - Assign Administrator

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2411]
User Story: As a sitewide administrator, I want to be able to assign administrator roles to users.

Acceptance Criteria: 
- On the Sitewide Admin Users --> Manage page, there will be a column for Sitewide Admin.  The column will contain a toggle button.  If turned on, the user is a Sitewide Admin.  If off, they will not have sitewide admin privileges.  when the toggle is selected, a confirmation message will display.
- On the Agency Admin --> Users --> Manage page, there will be a column for Agency Admin.  The column will contain a toggle.  If toggled on, the user will be an agency admin for their specific agency.  If toggled off, they will not be an agency administrator.  When the toggle is selected, a confirmation message will display.  
- Community will be done at a later time.

Note: 
1) Across the board display commas for any number over 3 digits and display percent signs for percentages. 
2) Do not include legacy/archive data in the counts.

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494465/preview

Related Tickets:
2388 - Sort by for User list
2392 - Add viewing 1-25 of 5200 Total Users to user display
2410 - Admin Dashboard - Sitewide section 1 - Users -  Manage Users
2363 - Admin Dashboard - Sitewide section 1 - Users - Display

**Comment by jhanson12** [comment]
![image.png](https://images.zenhubusercontent.com/59fb64278a75884b9085d586/1a833641-a744-4757-8ea5-980096c0625b)

![image.png](https://images.zenhubusercontent.com/59fb64278a75884b9085d586/7ed23e33-1bac-483b-a7a2-c91c992f3c2a)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
@kbwagner and @bmcorum and @jhanson12 - I see that the AC and the development is different, so can someone change the AC to match the development or vice versa before I test so I am sure as to what is being tested?  as it stands now I understand the changes but have no line of site into what officially needs to be tested...AC is totally different from the development at this point.

**Comment by kbwagner** [comment]
@jhanson12 @bmcorum @Kibrahacha67 - I'm a little confused on this one.  The idea behind the checkbox was that someone could be assigned all three permissions.  It looks like with the toggle, I will only only be able to be a sitewide or an agency or a community admin?  Unless I go to all three tabs and find myself (which would assume I was part of the agency or community)?  
Want to make sure I understand before I update the AC.

thanks!

**Comment by bmcorum** [comment]
@kbwagner, a couple issue with the original idea.

1) Nothing says I would only be able to belong to a single community so how would you specify which community or communities I need to be an admin for.
2) Being a sitewide admin automatically gives your all permissions (you are treated like an agency admin for **ALL** agencies and **ALL** communities thus needing to be given agency or community admin permissions would do nothing it gets ignored)
3) To remove confusion we separated out the ability to assign agency and community admins to the relevant tabs.
   - If site admin needs to assign a user as an agency admin go to agency tab select appropriate agency, find user and toggle agency admin on/off
   - If agency admin assigning a new agency admin find user from agency tab and toggle agency on/off
   - **When Communities is finished**  
      - If site admin needs to assign a user as a community admin go to community tab select appropriate community, find user and toggle community admin on/off
      - If community admin assigning a new community admin, go to community tab select appropriate community (if more than one), find user and toggle community admin on/off

**Comment by kbwagner** [comment]
@bmcorum - got it.  Just needed it explained to me.
@minchung12 FYI on a design change although I don't think you need to update the mock.

I will update the AC but it will l likely be tomorrow.

**Comment by kbwagner** [comment]
Original AC for tracking: Acceptance Criteria: 
Sitewide Admin --> Users --> Manage --> Assign Administrator Page: 
- There will be three checkboxes: Sitewide, Agency, and Community (note: mock currently says organization)
- The Community checkbox will have a dropdown available once selected to select an organization 
- There will be Cancel and Assign pushbuttons.  
- Once Assign is selected, the user will be taken back to the main sitewide page and the link will change to "Assigned".  
- Once cancel is selected, the user will be taken to the main sitewide page and the Assign/Assigned link will remain as it was originally.

Note: 
1) Across the board display commas for any number over 3 digits and display percent signs for percentages. 
2) Do not include legacy/archive data in the counts.

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494465/preview

**Comment by kbwagner** [comment]
@Kibrahacha67 I think this is ready to go now with updated AC.

**Comment by Kibrahacha67** [comment]
8-10-18 LHammond in testing.

**Comment by kbwagner** [comment]
8/13/18 - KWagner tested in Chrome. 
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
