### ISSUE TITLE
Login.gov: Sign in yellow banner

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2418]
User Story: As an Open Opportunities user, I want to have knowledge that the login process is changing in order to understand why I am being taken to login.gov.

Acceptance criteria: 
- add a yellow banner to the left of Sign in that indicates a new way to log in is here
- The text on the banner will read, "A new way to sign in. Create a login.gov account to sign into Open Opportunities.  Learn more"  
- login.gov account is a link that will take the user to the login.gov sign in/create account page
- Learn more is a link to the following help page to provide further information on the login process: <Link TBD>
- banner only displays when not logged in.
Invision Mock: 
Mobile: https://opm.invisionapp.com/d/main#/console/14593252/310828323/preview
Desktop: https://opm.invisionapp.com/d/main#/console/14696610/310829911/preview
Design System Link: http://usajobs.github.io/design-system/navigation/

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
7-31-18 LHammond in testing

**Comment by kbwagner** [comment]
8/6/18 - KWagner tested in Chrome and mobile.  
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Approved
