### ISSUE TITLE
Login.gov: Find my Open Opps profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2422]
User Story: As an Open Opps user, I want to be able to find my existing Open Opps profile when I create a new account in login.gov.

Acceptance Criteria: 
-	Background: When a user select the "Find Open Opportunities profile" button from the USAJOBS/Login process, USAJOBS will try to match their USAJOBS and Open Opps accounts based on the government email address provided.  If the government email matches, the accounts will be linked. If the government email address does not match, the user will be taken to the Find my Open Opps profile page.  
- The page title will be, "Find your Open Opportunities profile"
- The instructional text will read, "Enter the email address that's associated with your Open Opportunities profile."
- There will be a text box to enter Email address.
- There will be a Cancel button.  Cancel will return the user to the USAJOBS profile page where they came from.  
- There will be a Send email button. This will initiate an email confirmation to the address they entered to make sure they have access to that user account before we link it to the USAJOBS profile.  The email will be covered by a separate ticket 2454.

Invision Mock: 
Mobile - https://opm.invisionapp.com/d/main#/console/14593252/311571044/preview
Desktop - https://opm.invisionapp.com/d/main#/console/14696610/313413542/preview

Related tickets:
2454 - Find my profile confirmation email

**Comment by Kibrahacha67** [comment]
8-21-18 LHammond in testing

**Comment by tlorrison** [comment]
Final approval
