### ISSUE TITLE
Login.gov: Email all users

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2425]
User Story: As an Open Opportunities user, I want to be notified that the way I log in will be changing.

Acceptance Criteria:
- Who: send email to all active users to let them know login.gov is coming
- When: Send email a few days before login.gov is deployed.

Part 1: Development list of users
- export a list of current user emails 

Part 2: Content (also attached for proper formatting)

From: 
Email Subject Line: Open Opportunities update - A new way to sign in.

Email body copy:

Hello [Guest Name],

In a few days, Open Opportunities is changing the way you’ll sign in, making it easier and more secure.

What do I need to do?
For now, sign into your Open Opportunities account to make sure it’s up-to-date. If everything looks okay, you don’t need to do anything else just yet. 

Once we make the change, we’ll walk you through the new process when you sign in.

Thanks, 

The Open Opportunities Team
U.S. Office of Personnel Management
1900 E Street NW. Washington, DC 20415

About this message
You received this email because you signed up for Open Opportunities.

Have questions or comments? Check out our help center or email us at OpenOpps@usajobs.gov.

To make sure you get Open Opportunities emails to your inbox (and not your spam) add 'noreply@openopps.uat.usajobs.gov' to your address book.

[Open-opportunities-login-gov-coming-soon-email_variationA_20180813_v2 (3).docx](https://github.com/openopps/openopps-platform/files/2792486/Open-opportunities-login-gov-coming-soon-email_variationA_20180813_v2.3.docx)

Part 2.5: 
- Include Google Analytics link from 2427 in this email

Part 3: 
- Enter a Footprints ticket to provide list of active users to USAJOBS 

Note: Add info to a newsletter before go live

**Comment by bmcorum** [comment]
Need content for email.

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35522&fullScreen=false&_a=edit

**Comment by KatMullens-work** [comment]
@kbwagner "Washington" is misspelled in the address.

**Comment by Piglady64** [comment]
I made the edit to "Washington".

**Comment by kbwagner** [comment]
@KatMullens-work - weren't we talking about making sure the existing Open Opps users go in and copy their biography over to their USAJOBS profile?  I think this email might be out of date.  This email was created in July of 2018 so think it's out of date?

**Comment by KatMullens-work** [comment]
Hi @kbwagner - Agree we'll want to make sure everything is current before we send it out :) Welcome back, by the way! :)

**Comment by kbwagner** [comment]
@KatMullens-work thanks.  If this ticket isn't ready we should pull it - it's in the sprint log to be done this sprint.  But we probably need it done this sprint.  Or, split it into two tickets - one for the prep work to get the email out and the second for the content which needs to be updated.  Are you still taking this one on?

**Comment by kbwagner** [comment]
Closing - this will be done through myEmma
