### ISSUE TITLE
Login.gov: Toggle to turn on and off

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2426]
Have the ability to toggle between Login.gov and local login.

**Comment by bmcorum** [comment]
Login is toggled **OFF** in the TEST environment. The login yellow banner should not display.

![image.png](https://images.zenhubusercontent.com/59e8ff8ea468affe6df75add/1da18ca3-0e70-4af9-8f3a-0d3e4c52599d)

Login is toggled **ON** in the UAT environment. The login yellow banner should display.

![image.png](https://images.zenhubusercontent.com/59e8ff8ea468affe6df75add/d7dd1fbe-9a3f-49d0-b4bc-6336a37b5420)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
07/31/18 - Mdumas - In testing. Artifact shows the ability to turn banner on/off through changing value. Meets AC. Moving to review.

**Comment by kbwagner** [comment]
8/1/18- KWagner reviewed artifact.  
Verified login banner turned off in test and on in UAT
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Approved
