### ISSUE TITLE
Login.gov: Tracking for emails in Google Analytics

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2427]
User Story: As a program office, I want to be able to track analytics on emails that are sent to users in order to provide information related to how many people read the email.

Acceptance Criteria: 
- The email that is sent out via Footprints to Open Opps users notifying them of the change to the login process will include the ability to track information through Google Analytics.
- Team PD will provide a tracking pixel to include in the email
- The tracking pixel will include the ability to track click rates

**Comment by kbwagner** [comment]
@sean-lewis - it looks like we will be prepping this email for the sprint that starts next week.  Can you add this to your list for maybe next week?  I believe it was just something you were going to provide to include in the email that goes out?

**Comment by sean-lewis** [comment]
@kbwagner below is the information you need to track the login notification email. I also provided a couple of the key values in the string for the technical folks. All that needs to be done is for this img tag to be loaded into the body of the email that gets sent. When the image loads, it pings the Google Analytics servers and lets us know the email was opened.

<img src="https://www.google-analytics.com/collect?v=1&tid=UA-94043649-2&cid=555&t=event&ec=email&ea=open&el=login_gov_notification_change">

1. collect - simply notifies GA to collect
2. tid - our unique id for our GA account for Open Opps
3. cid - the client id of the person who click on the email. It is currently set to be anonymous
4.  t - the type (event)
5. ec - event category (email)
6. ea - event action (open)
7. el - even label (login gov notification change)

**Comment by kbwagner** [comment]
@bmcorum does this go to you guys in dev now (move to sprint log) or does this go in the Footprints ticket?  Or  both?

**Comment by kbwagner** [comment]
@bmcorum yes content is waiting for final approval.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

Generate some emails and then I will log into our Google Analytics account and attach an artifact.

**Comment by Kibrahacha67** [comment]
9-18-18 LHammond in testing

**Comment by bmcorum** [comment]
Not a specific email but we just added the code to the TEST environment today. All new emails will include the google analytics tracking pixel.

**Comment by Kibrahacha67** [comment]
@bmcorum - ok I will generate some messages today to make sure they get tracked

**Comment by bmcorum** [comment]
@Kibrahacha67 see below

![image](https://user-images.githubusercontent.com/1165615/45772457-c3cb0f00-bc15-11e8-8937-1550b3810d34.png)

**Comment by Kibrahacha67** [comment]
9-19-18 Testing completed and artifact attached. moving to review.  LHammond

**Comment by kbwagner** [comment]
9/19/18 - Reviewed artifact
@tlorrison ready for final review.  I also have it on my list to set up a meeting for us and @sean-lewis to get us up to speed on Google Analytics.

**Comment by tlorrison** [comment]
final approval
