### ISSUE TITLE
Login.gov: Remove password reset from admin screens

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2429]
User Story: As an administrator, I should no longer have the ability to reset a password once Login.gov is turned on.

Acceptance Criteria: 
- On the administration page, Reset password - hide once login.gov is toggled on

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. Remember Login.gov is turned **ON** in UAT and **OFF** in TEST

**Comment by Kibrahacha67** [comment]
8-1-18 LHammond in testing

**Comment by kbwagner** [comment]
8/1/18 - KWagner tested in Chrome. 
Verify in TEST and UAT environments
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
