### ISSUE TITLE
Data: Configure AWS SNS & SES for System Email Reporting

### ISSUE THREAD

**Issue by sean-lewis** [openopps/openopps-platform#2442]
##### Per Brice's suggestion below:

What we want to track: 
- Complaints
- Bounces
- Deliveries
- Opens
- Clicks (edited)

Then we will need tickets to configure AWS SES and AWS SNS to report data. Right now DEV and UAT are set to report Complaints and Bounces via SNS back to an API endpoint in OpenOpps but we can report to any API endpoint we so choose.

Though we would still need complaints and bounces to report to OpenOpps so we can make sure the system does not continue to send emails to those addresses

@kbwagner is this something I need to manage and track in the backlog/on scrum calls or will you? I am  fine with anything!

**Comment by sean-lewis** [comment]
@bmcorum @kbwagner any update on this one?

**Comment by kbwagner** [comment]
I defer to @bmcorum on this one as I'm not aware of any updates.

**Comment by kbwagner** [comment]
@sean-lewis I am just seeing your original question on tracking this issue.  Do we have a timeline for wanting to implement this?  For it to truly get tracked and worked, we'll need to put it into a sprint.  So the question is when it will fit into a sprint with the state work.

**Comment by sean-lewis** [comment]
@kbwagner I'd say it is a priority but not a showstopping one. We just need to get the data ball rolling more quickly and this will help us with the overall strategic objective. Whenever the team has availability to start this, that would be great!

**Comment by kbwagner** [comment]
Google Analytics tracks some of this
closing and can be readdressed if data team requests
