### ISSUE TITLE
Login.gov: Learn More link in yellow banner

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2446]
User Story: As an Open Opportunities user, I want to be able to read information about the new login process from the home page in order to answer any questions I may have.

Acceptance Criteria: 
- Learn More link on yellow banner should go to Open Opps Help Center (currently goes to USAJOBS): /openopps-help/account/login-gov

Invision Mock:
Mobile: https://opm.invisionapp.com/d/main#/console/14593252/310828323/preview
Desktop: https://opm.invisionapp.com/d/main#/console/14696610/310829911/preview
Design System Link: http://usajobs.github.io/design-system/navigation/ 

Related Ticket: 
- 2418: Yellow banner for login.gov

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**NOTE:** The help center page is missing but the link should be correct. Validate URL is correct based on AC.

**Comment by margaretdumas** [comment]
Mdumas - Testing Complete...moving on to review

**Comment by tlorrison** [comment]
Final approval
