### ISSUE TITLE
Login.gov: Find my Open Opps profile confirmation email

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2454]
User Story: As an Open Opportunities user, I want to be able to confirm I have access to my government email address in order to successfully link my Open Opps and USAJOBS profiles.

Acceptance Criteria:
- When the user select the "Send email" button from the Find your Open Opportunities profile page, an email will be initiated:
To: Email address provided on the find profile page
From: OpenOpps@usajobs.gov
Subject:
Content:

Functionality:
- Once the user clicks on the link within the email, their Open Opps and USAJOBS profiles will be linked.
- Once the user is signed in they will be taken to the signed in landing page.
- If the email does not exist in the system, no email will be sent.
  
Invision Mock: 
https://opm.invisionapp.com/d/main#/console/14593252/311571044/preview#project_console

Related Ticket:
2422 - Find my Open Opps profile

**Comment by bmcorum** [comment]
Usually if the email does not exist in the system you don't send an email at all. Prevents people from using the form to spam email accounts.

**Comment by Kibrahacha67** [comment]
@bmcorum and @kbwagner - if the user puts in an email address that is not in the system, there will be no email sent, but will there be a error message on the screen?  something like "this email address is not in the system, please build a new account"?

**Comment by bmcorum** [comment]
@Kibrahacha67 this is a sticky area. For securities sake you "never" want to tell a user as part of a form submission that the email provided does not exist in your system. Doing so allows for an attacker to use said form to phish for email accounts.

**Comment by kbwagner** [comment]
@bmcorum I had the same question as Larry at one point.  So they will just click send email but will never get one?

**Comment by bmcorum** [comment]
Due to empty AC I have created my own subject and content for the email.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-24-18 LHammond in testing

**Comment by Kibrahacha67** [comment]
8-24-18This ticket is on hold pending update of email...

**Comment by bmcorum** [comment]
@Kibrahacha67 you should be able to test this now.

**Comment by Kibrahacha67** [comment]
8-28-18 LHammond in testing

**Comment by Kibrahacha67** [comment]
9-7-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum can you send me the content you put in for this email so I can send to Debbie and confirm (and round out the AC)?  I had it but must have deleted it since I wasn't testing this specific ticket.

**Comment by kbwagner** [comment]
@bmcorum - the content approved by Debbie is actually "You recently asked to find your Open Opportunities profile using this email address. Please click the link below to confirm this is your email address and verify you have an Open Opportunities profile."

Do you want this to be a new ticket in the next sprint or send it back with AC entered.

**Comment by kbwagner** [comment]
New ticket 2555 created to provide approved email content.
Moving to review.

**Comment by tlorrison** [comment]
Final approval
