### ISSUE TITLE
Login.gov: New Open Opps Home page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2455]
User Story: As an Open Opportunities user, I want to see relevant information on the home page once I have signed in with my new login.gov account.

Acceptance Criteria:
-When a user is brought to Open Opportunities after having their USAJOBS profile matched and having logged in through USAJOBS, they will go to the new home page.
-The header on the page will read "Welcome (First name)"
- There will be a sign out link (ticket 2456)
- The shell of the page will include Your opportunities, Search Opportunities by, and See other people like you.
** 2493 adds what's new and latest achievements

Your opportunities:
- There will be two sections under Your opportunities: Participated and Created

Participated:
- There will be a Sort by dropdown to allow to search by each of the field headers.  Suppress sort by if there is nothing to display.
- Viewing x of y of z Opportunities will display under the header.
- The Participated section will display the Status, Opportunity, and Last updated for any opportunities for which the user has applied to.  
- The Opportunity name will be a hyperlink.  When selected the opportunity will open.  
- Updated date will display the last time the status of the opportunity was updated or an edit was made to the opportunity.
- If there are more than 5 opportunities on mobile or 5 opportunities on the desktop, a "Show more" button will display.  The button will not display is there are less than 5.
- Selecting Show more displays all on the page
- If there are no opportunities participated, display a Search opportunities link: https://opm.invisionapp.com/d/main#/console/14696610/313606719/preview
- The default sort for this section will be Last updated newest to oldest.

Created:
- There will be a Sort by dropdown to allow to search by each of the field headers.  Suppress sort by if there is nothing to display.
- Viewing x of y of z Opportunities will display under the header.
- The created section will display Opportunity status, Opportunity, and Last updated.
- The Opportunity status field will display the pill for the current status of the opportunity
- The Opportunity field will display the title of the opportunity as a hyperlink.  When selected, the opportunity will open.
- The Updated date will display the last date the status of the opportunity was updated or an edit was made.
- If there are more than 5 opportunities on mobile or 5 opportunities on the desktop, a "Show more" button will display.  The button will not display if there are less than 5.
- Selecting Show more opens the full list on the page
- If there are no opportunities created, display a Create opportunity link: https://opm.invisionapp.com/d/#/console/14696610/313606719/preview
- The default sort for this section will be Last updated soonest to oldest

Search opportunities by: 
- The first section will be "Search opportunities by" and a View all opportunities link.  View all will take the user to the general search page with all "Open" opportunities displayed
- There will be a Search based on your profile button.  When selected, it will use the career field, skill, and location from the user's profile to run a search.
-   Career field will display next.  The requirements will be the same as they are on the current landing page.  Acquisitions will always display.  See ticket 2012 for existing requirements.  
- Skill will display next.  The requirements will be the same as they are on the current landing page. See ticket 2012 for existing requirements.
- Location will display next.  The requirements will be the same as they are on the current landing page.   See ticket 2012 for existing requirements.

See other people like you:
- There will be a View all people link that will take the user to the People page
- Based on your job title
- Based on your agency
- The requirements for the display of this section are the same as they currently are. See ticket 2013 for original requirements.

Additional Notes: 
- This page will be for federal employees only.  There will be a different sign in page for student users at a later date. Ticket 2459
- The participated and created sections will no longer appear on the user's profile.  Help content will be updated to reflect this change.
- The recent activity and announcement sections have been removed from the landing page for the time being.

Invision Mock:
Mobile: https://opm.invisionapp.com/d/main#/console/14593252/313383442/preview
Desktop: https://opm.invisionapp.com/d/#/console/14696610/313393134/preview

Related Tickets: 
- 2456: Move location of sign out navigation

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-24-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-28-18 LHammond in testing

**Comment by kbwagner** [comment]
9/4/18 - KWagner tested in TEST environment.
- updated the AC to include the shell page to include What's new and latest achievements

Unable to test due to limited login options:
- less than 5 to not display show more
- no opportunities participated or created to show "none" message.

Issues/Questions for Dev:
1) the mock and AC say to display First name but both first and last name are displayed
2) Sort by: should include all 3 of the fields displayed - Status is not currently included

**Comment by bmcorum** [comment]
@kbwagner OpenOpps does NOT distinguish between first and last name so until we complete One Profile we will have to show the full name as that is how it is stored. Please attach a screenshot of the options for sort by.

**Comment by kbwagner** [comment]
Sort options are now displaying.  Ray is working on a CSS issue to remove the bold.

I will add a new ticket for making the name only display first name once One Profile is implemented.

@tlorrison ready for your review.

**Comment by tlorrison** [comment]
Final approval
