### ISSUE TITLE
Navigation: Move location of sign out

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2456]
User Story: As an Open Opportunities user, I want to have a standard location to sign out of my account.

Acceptance Criteria:
- Move the location of the sign out link to the signed in landing page under the user's name.

Invision Mock: 
Mobile - https://opm.invisionapp.com/d/main#/console/14593252/313383442/preview
Desktop - https://opm.invisionapp.com/d/main#/console/14696610/313393134/preview

Related Ticket:
2455 - New signed in landing page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-20-18 LHammond in testing

**Comment by tlorrison** [comment]
Final Approval
