### ISSUE TITLE
Signed in Landing page: Ability to delete draft from Your opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2458]
User Story: As an opportunity creator, I would like to have the ability to delete a draft opportunity from my landing page.

Acceptance Criteria: 
- On the signed in landing page in the Your opportunities section, add a column for Delete
- If there are no drafts for the user, suppress the delete column
- If there is a draft for the user, display a red "X" only beside the opportunity with a status of draft. The red X should display at the end of the line 
- When I click on the Delete icon, a confirmation modal will appear 
- The confirmation modal will read, "Delete opportunity confirmation" and then "Are you sure you want to delete [insert opportunity name]? This cannot be undone."  Opportunity name and the last sentence should be in bold. 
- The buttons on the modal will be Cancel and Delete opportunity.
- Selecting Cancel will close the modal and not delete the draft.
- Selecting Delete will close the modal and remove the draft from the landing page.

Current landing page with a draft: 
![image](https://user-images.githubusercontent.com/18709918/64290969-21469180-cf35-11e9-9130-7993f4748ca0.png)

Sample delete modal confirmation: 
![image](https://user-images.githubusercontent.com/18709918/64291119-623ea600-cf35-11e9-9b10-cdc92138b2e3.png)

**Comment by kbwagner** [comment]
@dalenard21 do you want to review the confirmation modal verbiage here?  I also think we have standards on the buttons on these types of modals if you want to weigh in. Thanks!

**Comment by dalenard21** [comment]
Hi @kbwagner which screen do you want me to review? I went to the invision mock above but it's no longer there.

**Comment by kbwagner** [comment]
@dalenard21 the mock doesn't work - I asked Alex if she could locate it but not sure there is a mock for the modal anyway.  So if you can just review the AC that would be great.

**Comment by kbwagner** [comment]
@abudz19 and @dalenard21 I found some samples to go off of so if you have a chance take a look and let me know if you're ok with this.

Thanks!

**Comment by dalenard21** [comment]
@kbwagner I'm looking at this today and will get back to you.

**Comment by dalenard21** [comment]
@kbwagner suggested content change:

Header: Confirm delete opportunity.
Are you sure you want to delete [insert opportunity name]?  You can't undo this action.

I think the button options are fine.

**Comment by kbwagner** [comment]
@dalenard21 thanks - updates have been made to the AC.  No further action needed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-17-19 LHammond in testing

**Comment by jhanson12** [comment]
Discussed with Katrina that it is okay to leave 'Delete opportunity confirmation"...this stays consistent with the systems current design.  For example the delete cycle title says "Delete cycle confirmation".

@Kibrahacha67 this is ready for testing

**Comment by dalenard21** [comment]
@kbwagner @jhanson12 

I don't understand why the heading can't be changed?  What do you mean by 'delete cycle title' says "Delete cycle confirmation"?

Also, the message content still needs to be updated to:

Are you sure you want to delete [insert opportunity name]? You can't undo this action.

The screenshot above shows "This cannot be undone."

**Comment by jhanson12** [comment]
![image](https://user-images.githubusercontent.com/15199629/67024451-6e8c5600-f0d2-11e9-9fd8-37e09f4562bc.png)

'Delete **cycle** confirmation' is used as an example how the title is worded else where in the application.

I can change it either way, but I thought keeping it consistent would be best.
The message content is updated.  The content just happened to be 'type type type'.

**Comment by dalenard21** [comment]
Hi @jhanson12 can you add a screenshot of the Cycle delete?  I'm not sure what that is.

**Comment by kbwagner** [comment]
@dalenard21 here's cycle delete
<img width="943" alt="Screen Shot 2019-10-17 at 2 46 02 PM" src="https://user-images.githubusercontent.com/18709918/67038221-fda66780-f0ec-11e9-8328-b342e24d2819.png">

Here's opportunity delete from the admin side
https://opm.invisionapp.com/share/U8R4CAV3HXF#/388169635_Open_Opps_-_Add_Office_Or_Bureau_-_Delete_Success

I can't think of any other deletes we have currently.  Let me know how you want to proceed.  I can put in tickets to update any of them if you'd like.  I'm all about being consistent.

**Comment by Kibrahacha67** [comment]
10-18-19 LHammond Testing completed moving to review.

**Comment by dalenard21** [comment]
@kbwagner 

I went through some of our other 'phase' messaging in ATP.  For the primary and alternate phase messaging we do use the active voice of "Start primary phase", "Confirm start primary phase", "Confirm close cycle", so I'd like to stay consistent with this pattern.

Confirm delete opportunity
Confirm delete cycle

Our style is to use active voice, sometimes it won't work but I think in this case we can still use active voice.  Also "deletion" is something that has already been deleted or is in the act of deleting.  In this case, we're asking the user to confirm that they want to delete the opportunity.  

If we can get it updated in the next sprint that would be great.

**Comment by dalenard21** [comment]
@kbwagner I spoke with @bmcorum who had concerns about changing "This cannot be undone" to "You can't undo this action." because it infers that someone else might be able to undo it.  We looked at some delete messages in USAJOBS and there's inconsistency there too, but did find a better solution.

Heading: 
Confirm delete opportunity

Message:
Are you sure you want to delete [insert opportunity name]? 

**If you delete this opportunity, you can't get it back.**

Heading:
Confirm delete cycle

Message:
Are you sure you want to delete [insert cycle name]?

**If you delete this cycle, you can't get it back.**

Not sure if this needs to be a new ticket.

**Comment by kbwagner** [comment]
@dalenard21 - I will create a new ticket for each of the delete modals (delete opportunity draft and delete cycle).  Thanks.

10/21/19 - KWagner tested in Chrome/Test. Functionality is fine and will create new tickets to modify verbiage.
