### ISSUE TITLE
Landing Page: Student user signed in landing page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2459]
User Story: As a student, I want to have a dashboard/landing page that allows me to see information related to my applications.  

Acceptance Criteria: 
- If Target Audience = Student, then display this landing page
- When a student is signed in, Welcome <Name> will display
- Sign out will display beside the name
- Your internships will display: Applied, Viewing X of Y (covered in 2899/2900)
- Status, Internship application, and Last updated columns will display
- Internship application will be a link that allows you to view the application
- There will be a Sort by dropdown to allow you to sort by all columns (covered in 2899/2900)
- View should work like it does in production on how many display and when show more will display.  Initially only 3 applications are accepted so this may be a non issue.
Ticket 2899 will be the functionality testable ticket where view and sort can be tested.

Saved:
- Viewing x of Y of Z internships (covered in 2899/2900)
- The table header columns will be Internship status, Internship, and Last updated
- Internship status will display a pill
- There will be a Sort by that will allow to sort by each column heading (covered in 2899/2900)
- The first 5 saved will display and then a Show more. (can be tested with 2899/2900)
- Show more will display all on the page  (can be tested with 2899/2900)

Badges will display under saved on the left rail,  suppress heading if there are no badges
- Unpaid internship badge will be added with ticket 3001

Latest achievements will not display on this page (updated design coming)

Note: 
this ticket will build the shell of the page.  The functionality will be updated with the apply and save tickets.

Invision Mock: https://opm.invisionapp.com/d/main/#/console/15990896/331677019/preview

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35775&fullScreen=false&_a=edit

Related tickets: 
2899 - View applications on landing page testable ticket
2900 - Saved internship on landing page testable ticket.
3001 - unpaid internship badge

**Comment by humancompanion** [comment]
We decided on 1/10/19 to cut the Latest achievements from the Student home page because learning about others successfully getting or completing Internships is not pleasant. 

We could in future consider bringing in the "What's New" section in order to communicate to users what's going on with the communities they belong to and perhaps others they may be interested in.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-18-19 LHammond in testing

**Comment by abudz19** [comment]
- Still missing sort function
- column headers are not aligned

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**NOTE:** Updated AC. New tickets to cover future functionality.

**Comment by Kibrahacha67** [comment]
2-7-19 LHammond in testing.
moving to review.

**Comment by kbwagner** [comment]
@abudz19 this is in test if you'd like to review.

**Comment by kbwagner** [comment]
@raywilliams please line up the column headings status, internship, last updated like the mock.  Otherwise this shell page looks fine.

Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-14-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/19/19 - Mdumas - In testing....

**Comment by raywilliams** [comment]
@kbwagner  Will you please update the A/C to make the table headers for applied internship opportunities the same as #2899? #2899 has the table headers as Status, Internship applications, and Last updated.

**Comment by kbwagner** [comment]
@raywilliams thanks for the catch....this was an older one that didn't get updated.  It should be right now.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/20/19 - Mdumas - in testing...

**Comment by margaretdumas** [comment]
@abudz19  Per a conversation with Brice about the badges, this is his comment:  "The system currently has no badges that students can earn".

So, can you remove this from the AC to a different ticket so that the ticket passes AC?  
@abudz19 

AC:  Badges will display under saved on the left rail, suppress heading if there are no badges

**Comment by kbwagner** [comment]
@margaretdumas - there are badges coming - it's a backlog ticket. This one says to suppress if not available.  Do I need to pull even that or just the part where badges will display?  I can do that...but they will be done hopefully even next sprint

**Comment by margaretdumas** [comment]
@abudz19  Ok, thanks that works for me if we have a ticket on the backlog.

**Comment by kbwagner** [comment]
Ticket 3001 adds an unpaid internship badge: https://github.com/openopps/openopps-platform/issues/3001

**Comment by margaretdumas** [comment]
Mdumas - passes testing. Moving on to review

**Comment by kbwagner** [comment]
3/20/19: Kwagner tested in Chrome/Test
- Looks good with application data.
- Need to create another student account so I can see blank page

@bmcorum 
If only one internship displayed, can we make this say “Viewing 1 – 1 of 1 internship” singular? Then for anything above 1 display “internships”?
 
![image](https://user-images.githubusercontent.com/18709918/54706474-6573e000-4b15-11e9-9616-eb3f6a0bfb9b.png)

**Comment by kbwagner** [comment]
@raywilliams 
Same on this one - the columns when blank display incorrect titles.  Titles for blank should be the same: Status, Internship application, Last updated.  Currently displays: Status, Program, Last updated.

I will create a new ticket for the viewing 1 of 1 and requesting different text other than "No applied applications."

![image](https://user-images.githubusercontent.com/18709918/54713274-9c052700-4b24-11e9-88de-243bd02fd421.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-21-19 LHammond in testing

**Comment by kbwagner** [comment]
3/21/19 - Kwagner verified in Test/Chrome.
Columns for a blank landing page are correct.

Ready for final review.
