### ISSUE TITLE
Login.gov: Open Opportunities Profile Page shell changes

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2461]
User story: As an Open Opportunities user, I want to be able to update my profile information that has been sent from USAJOBS.  

Acceptance Criteria:
The profile page will now be structured as follows:
- A yellow bar will appear at the top of the page that reads, "You must add your work location before you can apply to an opportunity."  This message will go away once a work location is added. This can be done with ticket 2463.
- Photo and Upload or Update Photo link (separate ticket 2462)
- Name
- Type of user - "Administrator" will display if the users is either a Sitewide or Agency admin)
- An Edit link - Selecting Edit will take the user to their USAJOBS profile edit mode to make changes.  All changes except for work location, skills, and photo will be done on the USAJOBS side.
- Job title
- Career field
- Agency
- Work location (separate ticket) - VERIFY FIELD TITLE OF LOCATION OR WORK LOCATION
- Official government email address - when someone else is looking at a user's profile, This will be an email hyperlink that will initiate an email to the user's email address (current functionality).  When I"m looking at my own profile, the email will not be a link.
- Biography
- Share profile link (current functionality)
- Skills
- Badges

Notes: 
- All data will be populated by USAJOBS with the exception of work location, skills, and photo
- The only edits to the profile on the open opportunities side will be for work location, skills, and photo.
- If data exists on Open Opps already (i.e. biography), it will be overwritten by the new data from USAJOBS.  If there is no data in USAJOBS for a field, what is in Open Opps will remain.
- Adding work location, photo, and skills will be done in separate tickets.
- The created and participated sections will now display on the signed in landing page

Invision Mock:
Mobile - https://opm.invisionapp.com/d/main#/console/14593252/313648489/preview
Desktop - https://opm.invisionapp.com/d/main#/console/14696610/313411848/preview

Related Tickets: 
- 2461 - Profile Shell
- 2462 - Add photo
- 2464 - Add skills
- 2463 - Add work location

**Comment by Kibrahacha67** [comment]
8-24-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by tlorrison** [comment]
Final approval
