### ISSUE TITLE
Profile: Photo upload page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2462]
User Story: As an Open Opportunities user, I want to be able to add a picture to my profile in order to allow me to better connect with other people who use the platform.

Acceptance criteria: 
- If a photo exists, the link should read Update photo
- If no photo exists, the link should read Upload photo.  The user's initials should display and be color coded (current functionality)
- click the link select a file.
- If successfully uploaded update profile image
- if failed display error using design system error alert
- Only allow valid image types to be uploaded and display error messaging to alert user if invalid file type or issue with file.

InVision Mock
https://opm.invisionapp.com/d/main#/console/14696610/313411848/preview

Remove Photo: 
- Once a photo has been uploaded, display a "Remove" link under the Update.
- Selecting remove will remove the photo and display initials
- The Remove link will not display when initials are displayed.

Existing photo backlog items to consider: 
- 2267 - adding a delete option and limiting and displaying file limitations
- 2353 - profile picture loads sideways in iOS

Invision Mock
https://opm.invisionapp.com/d/main#/console/14696610/313411846/preview

Related Tickets:  
- 2461 - Profile Shell
- 2462 - Add photo
- 2464 - Add skills
- 2463 - Add work location

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
09/7/18 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
Mdumas - Fails AC: 
•	If a photo exists, the link should read Update photo ( Link still reads upload photo)
![image](https://user-images.githubusercontent.com/19936109/45228739-0691fc00-b292-11e8-928c-0234f5838041.png)

•	if failed display error using design system error alert - ( I attempted to upload a word doc and there was no error).

**Comment by Kibrahacha67** [comment]
9-11-18 LHammond in testing

**Comment by Kibrahacha67** [comment]
9-11-18 LHammond  in testing

**Comment by kbwagner** [comment]
9/12/18 - KWagner tested in Chrome and mobile Safari.  Works.
Note: iOS still uploads the photo sideways or upside down but there is a separate ticket to look into that at another time.

Ready for final review.

**Comment by tlorrison** [comment]
final approval
