### ISSUE TITLE
Profile: Add/Edit work location

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2463]
User Story: As an open opportunities user, I want to be able to add my current work location to my profile in order to show opportunity creators where I am located.

Acceptance Criteria: 

Display location: 
- Open Opportunities will display the city, state from the contact portion of the USAJOBS profile
- The label in Open Opportunities will continue to be "Location" and thus can be interpreted as work location, home location, etc.
- Location will display city, state

Add/Editing location:
- When edit is selected from the Open Opps profile, the user will be taken to the USAJOBS profile to made the edit

Related Tickets: 
- 2461 - Profile Shell
- 2462 - Add photo
- 2464 - Add skills
- 2463 - Add work location

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35521&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
@bmcorum Has this ticket effectively already been done?  If so we can close.

**Comment by kbwagner** [comment]
Closing - the location will be pulled from the USAJOBS contact and this has been completed

**Comment by bmcorum** [comment]
Location is updated from contact information from USAJOBS profile
