### ISSUE TITLE
Profile: Add skills

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2464]
User Story: As an Open Opportunities user, I want to be able to add skills to my profile so that Opportunity Creators can see what I have to offer.

Acceptance Criteria:
1)No skills
- At the bottom of the profile, there will be a Skills section.  The instructions will read, "List all of your relevant skills."
- When a user has not entered any skills, an "Add skills" button will appear.
- If a user has skills already in Open Opps, they should stay and not be removed when the USAJOBS profile is linked.  Skills information will not be sent over from USAJOBS.

Mobile - https://opm.invisionapp.com/d/main#/console/14593252/313648489/preview
Desktop - https://opm.invisionapp.com/d/main#/console/14696610/313411848/preview

2)Add Skills:
- When add skills is selected, the user will be taken to a new page
- The page title will be Skills
- The instructions will read List all of your relevant skills.
- There will be two boxes for I have experience with and I want to develop
- The default text in each field will be Start typing to select a skill.
- Once a user starts typing in a box, they will see a message that reads, "Please enter 2 or more characters"
- Once a skill is selected, it will display with an "X" beside the pill.  X will remove the skill.
- There will be a Cancel and return to Profile button.  This will take the user back to the previous Profile page without saving their skills.
- There will be a Save skills button that will save the skills and return the user to the profile page where the skills will display

Mobile - https://opm.invisionapp.com/d/main#/console/14593252/313648488/preview
Desktop - https://opm.invisionapp.com/d/main#/console/14696610/313609253/preview

3)Display Skills
- The skills will display as pills
- Once skills are displayed, there will be an Edit link. Selecting edit will take the user to the add/edit skills page to make changes.

Mobile - https://opm.invisionapp.com/d/main#/console/14593252/313648487/preview
Desktop - https://opm.invisionapp.com/d/main#/console/14696610/313411846/preview

Related Tickets: 
- 2461 - Profile Shell
- 2462 - Add photo
- 2464 - Add skills
- 2463 - Add work location

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-4-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-7-18 LHammond in testing

**Comment by kbwagner** [comment]
@raywilliams this looks good but I did notice that the skills displayed on the profile are underlined and kick off a search when selected.  This happens in prod too but they aren't underlined.

Can we remove the underline on the skills?  
![image](https://user-images.githubusercontent.com/18709918/45496913-73027480-b744-11e8-9464-fd9a98a28d6f.png)

**Comment by raywilliams** [comment]
@margaretdumas added the skills underlining to issue #2515. There are links throughout the site that are underlined now that were not originally. @jhanson12 is looking at that issue.

**Comment by tlorrison** [comment]
Final approval
