### ISSUE TITLE
Navigation: Open Opps logo will take user to signed in landing page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2465]
User Story: As an Open Opportunities user, I want to be able to access the landing page from the Open Opportunities logo in order to have easy navigation points.

Acceptance Criteria: 
Landing page: https://openopps.usajobs.gov/
Home page: https://opm.invisionapp.com/d/main#/console/14696610/313393134/preview
1) Signed in/signed out- if you click the Open Opps logo > landing page
- If you are signed in, you will remain signed in so name will display instead of sign in

2) Signed in - you click your name > home page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - In testing....

**Comment by tlorrison** [comment]
final approval
