### ISSUE TITLE
Add ability for Opp Creator to notate a decline for an applicant

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2468]
Enhancement request from user: 
Note: Further discussion - allow notes on applicant or some way to mark they were not selected during the process.

If we have interviewed someone who applied to our open opportunities announcement and do not intend to offer them the detail/opportunity, is there a way to decline/not assign them?  I only see instructions for clicking the “plus” sign to assign them.

Thanks for the help!
Polly 

Polly Hall | Strategy & Planning Lead
Procurement Innovation Lab | Office of the Chief Procurement Officer
Department of Homeland Security
polly.hall@hq.dhs.gov
202-447-5549 desk | 202-868-0562 cell

**Comment by kbwagner** [comment]
Move to customer experience tickets in TFS

**Comment by nia-johnson** [comment]
@kbwagner Wouldn't this be in ATP?

**Comment by kbwagner** [comment]
@nia-johnson nope this is for regular opportunities.  Creators want a way to notate that they have either found an applicant to not be eligible for whatever reason or they interviewed them and didn't like them.  Right now they are all in an "applicant" bucket and they can't differentiate.  So do we maybe add another bucket of not selected or something where they can be drug.  There is an email that goes out once "Continue" is selected to anyone that isn't an assigned participant to say they weren't selected so when we think of the flow we'll need to include what emails go out, to whom, and what the trigger is.

**Comment by nia-johnson** [comment]
Closed. Moved to TFS - https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS-New/_workitems?id=41404&_a=edit

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41562&_a=edit
