### ISSUE TITLE
Department of State: Application Process

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2483]
User Story: 

As a Student Open Opportunities user, I want to be able to apply for department of state internships.  This ticket will start the application process of applying for a department of state internship. 

Acceptance Criteria:
•	When you click apply to a Department of State internship you will be brought to this page. (future)
•	This is the summary page of the Application Process to the internship. 
•	The “Back to Results” link will take you back to the search results. (future)
•	Clicking “Continue” will take you to the first step in the application process. (future)
•	This ticket should follow the design standards. 
This ticket creates the shell of this page.  The functionality of it will be done in the future.

Invision Mock:
https://opm.invisionapp.com/d/main#/console/15360465/319289299/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-7-18 LHammond in testing

**Comment by humancompanion** [comment]
This is an unfortunate case where both the mock-up and design system are lagging behind some decisions I made in core in the new user flow. @bmcorum correctly used the slim variation of the button bar here. Min's mock-up lacked the line it should have. However, in core I decided that this treatment can sometimes look odd and likely violates Fitt's Law (essentially it's far from the user's focus and takes a relatively long time to move the mouse over there). Thus an update to the design system is forthcoming:

https://github.com/USAJOBS/design-system/issues/134

So, for this button please:

* Align the button to the left
* Use the ```.usa-button-big``` variation of button style.

This keeps the button in line with the numbers that draw the eye down the page and make it a big clickable/tappable target. Thanks.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. **NOTE** See Matt's comment above about new design requirement for button placement.

**Comment by Kibrahacha67** [comment]
9-21-18 LHammond In Testing

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35519&fullScreen=false&_a=edit
