### ISSUE TITLE
Department of State: Application: Confirmation Alert

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2490]
Who: Student
What: A modal to show the Student that their application has been submitted.
Why: The student would like a confirmation of their application submission

This ticket is the Application Confirmation Page the student gets when they submit their application for their internship. 

Acceptance Criteria:

- When the student clicks the "Submit" button from the "Review Application Page" A modal will 
         pop up
- Header on the Modal - Your application has been submitted
- The body of the Modal - 

Thank you for submitting your application to the Department of State
Unpaid Student Internship Program.         
                    
After the application period closes and the internships are assigned, we'll email you to  confirm whether or not you've been selected.

- Clicking the “okay” button, will bring the student to their personal landing page

Invision:

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35512&fullScreen=false&_a=edit

**Comment by Piglady64** [comment]
I rewrote this ticket when GitHub removed this one after they flagged me.
