### ISSUE TITLE
Department of State: Application Process Circle Flow Numbers 

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2491]
User Story:

This ticket will highlight the application flow circles below the top navigation.
Acceptance Criteria:
This ticket will create the process flow bubbles in the navigation.  See mock.  
- Ticket 2591 will develop the functionality behind the circles (future).

Invision Mock:
https://opm.invisionapp.com/d/main#/console/14696610/305592970/preview
Mobile: https://opm.invisionapp.com/d/main#/console/15359539/319510813/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-7-18 LHammond in testing

**Comment by kbwagner** [comment]
9/13/18 - Tested in Chrome and mobile Safari

@raywilliams in Mobile step 4 should be titled "Languages" and is currently titled "Skills"

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-18-18 LHammond in testing

**Comment by kbwagner** [comment]
9/18/18 - KWagner tested in mobile Safari and step 4 correct says Languages
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
