### ISSUE TITLE
Change Footer

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2492]
User Story:
This ticket will change the Footer.

Acceptance Criteria:
•	Remove Links. 
•	Please refer to Mock

Invision Mock:
https://opm.invisionapp.com/d/main#/console/14696610/314849247/preview

**Comment by bmcorum** [comment]
*only during application process

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-4-18 LHammond in testing.

**Comment by kbwagner** [comment]
9/5/18 - KWagner tested in Chrome in the TEST environment.
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
