### ISSUE TITLE
Department of State: Application: Database

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2501]
## Description
Create tables necessary to store Department of State internship application data. Data tables should be modeled as closely as possible to USAJOBS tables to increase ease of importing data during application starts.

## Tables:
- [ ] Application
- [ ] Experience
- [ ] Reference
- [ ] Education
- [ ] Language

**Comment by bmcorum** [comment]
Need a process to import base system data from [Open Data API](https://developer.usajobs.gov/API-Reference)
- [ ] Academic honors (HonorsID)
- [ ] Degree type code (DegreeLevelID)
- [ ] Language codes (LanguageID)

**Comment by jhanson12** [comment]
New tables highlighted below. 

**NOTE:** language_skill will hold the languages a student has. There will be a language table that holds the list of language options (pulled from USAJOBS).

![image.png](https://images.zenhubusercontent.com/59fb64278a75884b9085d586/b921c86c-2d31-4312-ba1f-aca5244dbc03)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-18-18 LHammond artifact attached moving to review.

**Comment by kbwagner** [comment]
9/18/18 - KWagner reviewed attached artifact. 
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
