### ISSUE TITLE
OpenOpps: application audit log table

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2511]
Update audit_log table so we cover the following minimum content logging requirements.

- [x] Severity (info, warn, alert)
- [X] User ID
- [x] Origin/Source (IP Address: true-client-ip)
- [X] Date and time of the event
- [X] Type of event
- [x] Status of event (i.e. successful, unsuccessful, blocked, etc)
- [X] Event Specifics/Related Info (Additional Info)

**Comment by bmcorum** [comment]
- Type of event is tracked by the action column
- Event specifics (additional info) is tracked in the data column

![image](https://user-images.githubusercontent.com/1165615/45684955-e413a480-bb15-11e8-8ac8-b212419afa2c.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-18-18 LHammond artifact attached moving to review.

**Comment by kbwagner** [comment]
9/18/18 - KWagner - reviewed attached artifact.  
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
