### ISSUE TITLE
OpenOpps: application audit log: account events

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2513]
Record account related events to audit log

- [x] Account creation
- [x] Account disabled and enable
- [x] Account edited
- [x] Unauthorized attempt to edit user account
- [x] Permission or role changes

**Comment by Kibrahacha67** [comment]
9-25-18 LHammond in testing

**Comment by bmcorum** [comment]
See attached artifact from UAT.

![image](https://user-images.githubusercontent.com/1165615/46689126-1ff9d100-cbcd-11e8-92f2-04752090a007.png)

**Comment by Kibrahacha67** [comment]
10-9-18 artifact completes testing, moving to review LHammond

**Comment by kbwagner** [comment]
10/9/18 - KWagner reviewed attached artifact.
Moving to final review.
