### ISSUE TITLE
The opportunities and details are displayed with underlining

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2515]
The opportunity card and details are displayed on the card with underlining. 

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/d30bf75a-4793-474e-a217-81816f0f6481)

**Comment by margaretdumas** [comment]
Mdumas - Adding other pages with underlining. Added the URLs.

1.	https://openopps.uat.usajobs.gov/admin/tasks (title, creator)
2.	https://openopps.uat.usajobs.gov/tasks/870  (related keywords, Names in discussion)
3.	Https://openopps.uat.usajobs.gov/profile/3759 (profile skills)

**Comment by Kibrahacha67** [comment]
6-11-19 LHammond this issue has been resolved on both regular opportunities and internships.  Moving to review.

**Comment by kbwagner** [comment]
6/12/19 - KWagner - no longer an issue
