### ISSUE TITLE
Admin ability to reassign an opportunity to a new creator who resides in a different agency or department.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#2523]
User Story: As an agency admin or product admin, I want to be able to reassign an opportunity in case the original creator leaves the agency or position. With many projects being government-wide it is critical that admins be able to assign to a different agency.

**Comment by bmcorum** [comment]
@LisaLNelson can you elaborate on this issue? I am confused. If I create an opportunity for some task needed by OPM and then leave the agency to go work for DOD why would you assign the opportunity to someone at a completely different agency and not to someone at OPM since the task was for a need at OPM?

**Comment by LisaLNelson** [comment]
@bmcorum  Yes it has happened on a number of occasions mostly on projects that cross multiple agencies . For example. The CIO Council had an opportunity posted and the person managing the opportunity for them left and they reassigned it to someone else from a different agency to oversee.

**Comment by bmcorum** [comment]
@LisaLNelson then this sounds like they need a community and should not be posting at a agency level. If the opportunity crosses agency boundaries this is a perfect fit for a community.

**Comment by LisaLNelson** [comment]
@bmcorum Under this scenario we would be asking a cross-agency council to do a lot more work than just post an opportunity. They'd need a community manager and this is something that they may not want to invest their first time, they want just want to pilot it.  As a potential scenario, a new cross-agency council posts their first opportunity. Would we tell them they need to create a community and appoint a community manager? Alternatively, if we post their opportunity and the TC leaves and they want to appoint someone else from another agency we tell them no until they create a community?

My thinking is that these are barriers to participation that could stunt out growth.

My suggestion is that we allow site manager to be able to make that change under the assumption if this were to happen a second time for the same organization we present them with our community solution.

**Comment by bmcorum** [comment]
@LisaLNelson cross-agency should be a community. Then all members of the cross-agency council become members when a member leave then the opportunity can quickly be assigned to another member of the council. Any time you have something that needs to be cross agency they will need to utilize the community feature. Posting at the agency level only permits management of the opportunity within the same agency. This process help to protect data integrity.

**Comment by kbwagner** [comment]
2/3/2020 - Consider a change agency function.

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41489&_a=edit
