### ISSUE TITLE
Import base system data from USAJOBS

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2533]
User Story: As an Open Opportunities user, I would like for the data in USAJOBS to be the same as the Open Opportunities data to be consistent.

Acceptance Criteria: 
- Need a process to import base system data from [Open Data API](https://developer.usajobs.gov/API-Reference)

The following tables should be imported: 

- [x] Academic honors
- [x] Degree type codes
- [x] Language proficiency
- [x] Reference type codes
- [x] Security clearance codes

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. See attached artifacts below.

## Base data in USAJOBS
![image](https://user-images.githubusercontent.com/1165615/46495957-ca947d00-c7e4-11e8-956f-1052cca9580f.png)

## Base data in OpenOpps after import
![image](https://user-images.githubusercontent.com/1165615/46496013-eb5cd280-c7e4-11e8-9a4b-08103c8b2715.png)

**Comment by Kibrahacha67** [comment]
10-9-18 LHammond - development artifact attached moving to review

**Comment by kbwagner** [comment]
10/9/18 - KWagner - reviewed attached artifact.  Moving to final review.
