### ISSUE TITLE
Invite user to Community

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2534]
User Story: As a community manager, I want to be able to add members to a community so that they can view the community opportunities.

Acceptance Criteria: 
-On the Community dashboard, allow for any active Open Opportunities member to be added to the community.
- Click invite button, modal with select user (search by name or email).

An email to notify invitees will be a separate ticket

Related ticket:
2670 - Email - you are invited to a community

**Comment by kbwagner** [comment]
Related TFS ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35532&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

### Audit log artifacts
![image](https://user-images.githubusercontent.com/1165615/48849122-b0eacd00-ed73-11e8-8ff6-5ffac867ff9b.png)

![image](https://user-images.githubusercontent.com/1165615/48849169-c7912400-ed73-11e8-809b-e3e453696cf8.png)

![image](https://user-images.githubusercontent.com/1165615/48849201-db3c8a80-ed73-11e8-92cf-71274c4d125b.png)

**Comment by Kibrahacha67** [comment]
11-21-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum - I don't see an actual invite button.  Is this just a behind the scenes thing for now based on the artifact?  If so I will update the AC.

**Comment by Kibrahacha67** [comment]
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/37efe412-90f6-4b84-96aa-531adf02a226)

**Comment by kbwagner** [comment]
Thanks @Kibrahacha67  - I didn't see it but cleared my cache and shut down this morning and it now appears.

**Comment by Kibrahacha67** [comment]
All good...

**Comment by kbwagner** [comment]
@bmcorum The button on the modal says "Add applicant". Can it say "Add member" please?

![image](https://user-images.githubusercontent.com/18709918/49083984-34953580-f21c-11e8-8c66-c64f6abf56c7.png)

**Comment by bmcorum** [comment]
@kbwagner, yes it can. Sorry can you send it back to development please?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
Wording updated.
Entered new ticket to change "Invite member" to "Add member" to make more sense.  Future.
Ready for final.
