### ISSUE TITLE
Usability Testing with Community Managers 

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2536]
We need to conduct some research with community managers, on how communities should function.

When will this happen?
When can we create a sketch to show community managers?
When should we update sketch after research is concluded.

**Comment by Piglady64** [comment]
I will need to know the following:
1) When do you want to test?
2) Do you want this to be a virtual test or an in-person test?
3) How long do you anticipate the test to take (depends on the tasks you asking participants to perform)?
4) Are these community managers in different agencies? 
5) How do  I find a "community manager" ? ( I need to know how to recruit them.)
