### ISSUE TITLE
Bug: UAT the time out error message does not pop

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2538]

**Comment by Kibrahacha67** [comment]
When testing time out, the page gets past the 15 minute time out and the error message does not pop up.  Once the user clicks something on the page they get the sign in page.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
10/9/18 - KWagner received timeout message at 12 minutes in saying would expire in 3 minutes
timed out at 15 minutes in UAT.
Ready for final review.
