### ISSUE TITLE
Search People Option Does Not Display Underline until the page is refreshed.

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2539]
When I click the search people link, the people page is displayed but "People" is not under lined until I hit the refresh option.  Opportunities is still underlined. This is all browsers. 

Steps to reproduce:
1.  Sign into the site
2.  Click "Search" option
3.  Click the "Search people" link on the right

Results:  The people page is displayed with the results but the Opportunities option is underlined. 

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/3444680d-6c46-47b3-9f45-1eb3113d6bcf)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
10/9/18 - KWagner tested in Safari.
Ready for final review.
