### ISSUE TITLE
Alert admin when they are making changes to someone else's opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2540]
### Who
Open Opps Admins 

### What
Notify Admin users when they are making changes to someone else's opportunity 

### Why
Admins need to be aware of when they are making changes that directly changes users existing opportunity information 

### Acceptance Criteria
The following should occur when a sitewide administrator edits an opportunity that isn't theirs: 
- When a site wide admin clicks edit on someone's opportunity, view a warning banner saying the following "You are an administrator. You are editing another user's opportunity."

### Related Tickets 
4459 - will make the profile banner that currently appears the same yellow design system warning banner.

### Mocks
None 

### Background Info 
Suggestion from Margaret during testing: suggestion for a future release.  Earlier I was signed in my admin account and was editing the skills in someone elses account.  I know we have the message at the top that you are signed in as an admin but it would be nice to have a confirmation before the actual save is made.

Audit - should we be auditing who makes changes and what they changed? 

Warning message displays on profile.

**Comment by kbwagner** [comment]
2/3/20 - We currently show a message when you are updating someone else's profile.
- Add a similar message when a sitewide admin is updating someone else's opportunity.  You are editing an opportunity that isn't yours - make a modal instead of a banner
- Audit is currently happening.  No additional requirements needed.
Currently on profile - but use yellow warning message instead:
![image](https://user-images.githubusercontent.com/18709918/73681775-0ebfb800-468d-11ea-83b8-2ad186a07f19.png)

@nia-johnson this is one you could get ready as there is time

**Comment by nia-johnson** [comment]
@kbwagner done

**Comment by kbwagner** [comment]
@nia-johnson  you can remove the piece on the profile since that works currently - or note it works currently.
For the one message on the opportunity, please give them the text for it.  You can use the profile message as an example.  And it's really not a modal if it's a warning message - sorry we talked about two different things earlier but landed on warning message which is part of the design system

**Comment by nia-johnson** [comment]
@kbwagner Took out the profile bit and made a note at the bottom of the ticket. For the text, should we loop in design to ensure the copy meets content standards?

**Comment by kbwagner** [comment]
@nia-johnson in most cases I say to loop in Debbie but since we have existing approved text that we can use we don't need to bother her.  I'd just have it say "You are an administrator.  You are editing another user's opportunity."
- Also, I don't think this message needs to display until the admin clicks "Edit" on an opportunity that isn't theirs.  If we display it when it's viewed it will get annoying.
- One more also, should probably put in a new ticket to have the profile banner be changed to the yellow warning banner to be consistent.

**Comment by nia-johnson** [comment]
@kbwagner Done.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Atlas/_backlogs?level=Backlog%20items&showParents=false&_a=backlog
