### ISSUE TITLE
Login.gov: Sign out page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2541]
User Story: As an Open Opportunities user, I want to be able to see Open Opportunities specific links when I log out.

Acceptance Criteria:
- When a user clicks on "Sign out" from Open Opportunities, they should be taken to an Open Opportunities specific sign out page.  (currently takes them to a USAJOBS)
- We need to build a sign out page per the design:
https://opm.invisionapp.com/d/main#/console/14696610/319806039/preview
- Sign in again will go to the main Open Opps sign in page
- Search for opportunities will go to the main search page (may need to determine if it goes to a student page down the road)
- help center will go to the Open Opportunities help center
- Head back to home will go to the signed out landing page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing in UAT.

__NOTE:__ This will not work in TEST as that environment is using OpenID Connect and we have separate ticket to implement the new connect/endsession endpoint that will redirect to our logout page.

**Comment by Kibrahacha67** [comment]
9-27-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-1-18 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 did you test this in TEST or UAT? TEST environment is using Login.gov and thus uses a different logout endpoint which we have a separate ticket for (#2563).

**Comment by Kibrahacha67** [comment]
10-2-18 LHammond in testing.

**Comment by kbwagner** [comment]
10/3/18: KWagner tested in UAT because it does not come up in TEST due to issues described above.  

@tanichacko question - is it possible to make Open Opportunities appear in one line like it does in the design?  Currently looks like this in UAT: 
![image](https://user-images.githubusercontent.com/18709918/46417744-4c5aac80-c6f8-11e8-81fd-fbe18c5378c4.png)

**Comment by tanichacko** [comment]
@kbwagner - Yes it is possible. I checked in  for that changes. It will be ready for testing in UAT once after  the build happens.

**Comment by tlorrison** [comment]
Final approval
