### ISSUE TITLE
IE cutting off United States government image

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2542]
See image below.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/a5250dcd-adec-4974-b319-1200a5ea9737)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-9-18 LHammond in testing
