### ISSUE TITLE
Regression: confirm modal for closing out opportunity button (not active)

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2546]
If the complete opportunity button is grayed out, it can still be clicked to product the modal which gives the  user the ability to close the opportunity.  Should not be able to click the grayed out button only the blue active button should be accessible to close the opportunity.  See images below.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/1bc1c522-591b-490a-bfec-1586aa7befb2)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/420889ba-3e7f-4cdd-a23a-c5db39706763)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/7c0b0dd8-3039-456b-9de9-b53e452c8e2a)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-16-18 LHammond in testing

**Comment by kbwagner** [comment]
10/21/18 - KWagner tested in UAT and Test environments.  This issue is resolved but the same issue occurs when the user clicks the "Next step" button.  Will create a new bug ticket.
- This ticket is ready for review.
