### ISSUE TITLE
Regression: Column headings in Participated & Created sections do not match the sort by drop down list

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2549]
On the home page, the column headings in the Participate section don't match sort by drop down. (Updated date <> Last updated) and Created section heading does not match sort by drop down,  (Opportunity status <> Status) (updated date <> Last updated)

Modify all to read Last updated

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-18-19 LHammond in testing

**Comment by kbwagner** [comment]
12/18/19 - KWagner tested in Chrome/Test
Ready for final review
