### ISSUE TITLE
Create Community Table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2550]
User Story: As an Open Opportunities Program Administrator, I need the ability to create a community.

Acceptance Criteria: 
- This ticket will create the database table for community attributes.  The user interface portion will be a future ticket.

The Community Attribute Table will contain the following values: 

All fields are required unless noted, there will be no field defaults unless noted in order to drive people to enter information
1. Community Name - Free form text, 100 characters or less
2. Agency - Dropdown/select list
3. Community Manager Contact Name
4. Community Manager Contact Email
5. Community Administrator (would be a pick list of existing open opps users)
6. Description (optional) - free form text; under 500 characters
7. Target Audience 
- Valid Values: Student or Federal employee
- Single pick
- No default value
- Future: If student, do not allow profiles to be displayed on opportunity
8. Closed Group Y/N.  No default
- Future -  Yes will be open to anyone; No/Closed will be invitation only/limited display
9. Community Type 
- Valid Values: Career field, Agency, Program
- Single select 
- No default
- If Career field selected, then career field dropdown displays (required)
- Agency should default to the agency selected earlier.
10. Community related skills - skills related to the community (optional)
11. Opportunity Duration: (future: will drive create opportunity template and application flow)
- Valid Values: Ad Hoc, Cyclical, Continual
- no default
12. Microsite URL
13. Support Contact (future: likely a group email that will display on footer, opportunity, etc.?)  

Table 2 (same ticket) Community User table
o	Join table
o	Role – manager or not

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/46308765-7ee59780-c588-11e8-9f51-eed1b9e0fa59.png)

![image](https://user-images.githubusercontent.com/1165615/46308809-96248500-c588-11e8-9f22-92ebad94bf7e.png)

![image](https://user-images.githubusercontent.com/1165615/46308826-a50b3780-c588-11e8-95e1-ae28911d69fa.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__Note:__ Artifacts attached above.

**Comment by Kibrahacha67** [comment]
10-1-18 LHammond Moving to review.

**Comment by tlorrison** [comment]
Final approval
