### ISSUE TITLE
Spike: Profile requirements to Polydeuces

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2551]
Provide a document to the Polydeuces data team to define what information needs to be included in the data API for One Profile: 
- what data do we need to access to the data team can build an API?
- Define what data we need for a federal user's profile
- Define what data we need for a student profile

**Comment by bmcorum** [comment]
@brodydittemore, @Marchalk, and @lawrencek76 here is what we will need from the profile api. If you find it better or easier to provide more data points I won't complain at all, but I need at least what is listed below. Thanks.

## Federal employee profile
- First name
- Last name
- Job Title
- Career Field
- Agency
    - Name
    - Acronym/Abbreviation
    - CPDFCode
- Government email address
- Biography


## Student profile
- First name
- Last name
- Email address
- Biography
- Work experience [List]
    - Employer name
    - Street address
    - Street address 2
    - Country (Code value from OpenData API)
    - Postal code
    - City
    - State (Code value from OpenData API)
    - Job title
    - Start date
    - End date
    - Is present
    - Duties, accomplishments, related skills
- References [List]
    - Name
    - Phone
    - Email
    - Type (Code value from OpenData API)
    - Can contact
- Education [list]
    - School name
    - Country (Code value from OpenData API)
    - Postal code
    - City
    - State (Code value from OpenData API)
    - Degree level (Code value from OpenData API)
    - Completion date
    - Major
    - Minor
    - GPA
    - Max GPA
    - Total credits earned
    - Credit type (Semester, Quarter, Continuing education)
    - Honors (Code value from OpenData API)
    - Relevant coursework
- Languages [List]
    - Language (Code value from OpenData API)
    - Spoken skill level (Code value from OpenData API)
    - Written skill level (Code value from OpenData API)
    - Read skill level (Code value from OpenData API)

**Comment by brodydittemore** [comment]
@bmcorum Just to be clear on the word "need", many of these fields are optional for completion by the job seeker. That's fine, right? Also, the Federal Email field is still pending 7.3 deployment. 

@Marchalk Let's try to schedule this for our next sprint - we'll get working on some tickets.

**Comment by bmcorum** [comment]
@brodydittemore sorry, "need" probably wasn't the best word choice. If these values are present we would like to receive them.

**Comment by brodydittemore** [comment]
@bmcorum Great! Because if these are present, we want to give them to you! We'll keep Atlas in the loop on scheduling.

**Comment by kbwagner** [comment]
@brodydittemore are you ok with this ticket then for me to move it on to "final" review?

**Comment by tlorrison** [comment]
@brodydittemore @bmcorum So do we need any other stories to actually get the data into Open Opps? there are so many similar stories, I just want to make sure i know where we stand. Thanks!
