### ISSUE TITLE
Spike: Redundant Database

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2552]
This spike will allow development to research how to do redundant database services.
- Determine plan
- a ticket will be created to proceed with the work at a later time when we have full database access granted.

**Comment by bmcorum** [comment]
### Relational databases (RDS)
The Open Opportunities application utilizes AWS RDS service for hosting a database instance. The current plan being used is the medium-psql service plan. We have two options, shown below in the plan table, to upgrade to a redundant database.

Plan Name | Description | Software Version | Price
-- | -- | -- | --
medium-psql | Dedicated medium RDS PostgreSQL DB instance | 9.6.3 | Will be paid per hour + storage
medium-psql-redundant | Dedicated redundant medium RDS PostgreSQL DB instance | 9.6.3 | Will be paid per hour + storage
large-psql | Dedicated large RDS PostgreSQL DB instance | 9.6.3 | Will be paid per hour + storage
large-psql-redundant | Dedicated redundant large RDS PostgreSQL DB instance | 9.6.3 | Will be paid per hour + storage

### How to initiate the service plan upgrade
After logging into desired Cloud.gov Open Opportunities environment, we can utilize the following service update command via the cloud foundry CLI.

`cf update-service SERVICE_NAME -p NEW_PLAN`

According to Cloud.gov documentation, dedicated RDS instance provisioning can take anywhere between **five (5) and sixty (60) minutes**. During instance provisioning, the results of `cf services` or `cf service SERVICE_NAME` will show status as created. This created status simply mean the API call has completed not the actual provisioning process. To determine if a database is ready to use, try to create a service key using

`cf create-service-key SERVICE_NAME SERVICE_KEY_NAME`

If the status returns FAILED the provisioning has not yet complete, however a status of OK then the provisioning has completed and the upgraded database service instance is ready to use.

**Comment by kbwagner** [comment]
@bmcorum do you need any tickets added to get this work done?

**Comment by tlorrison** [comment]
@bmcorum When we do this work will we need approval for additional funding? If so, please let me know if there's anything I need to do
