### ISSUE TITLE
Update language on blue unauthorized page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2553]
User Story: As an Open Opportunities user, I want to know specifically what fields I must enter into my USAJOBS profile in order to use Open Opportunities to apply or create an opportunity.

Acceptance Criteria: 
- On the unauthorized page, please update the text to be more specific to what the required fields are.
- URL: https://openopps.test.usajobs.gov/unauthorized (edited)
- New Text Should read: 
Open Opportunities is only for current federal employees and students who are looking for internships.
If you are a federal employee, make sure your USAJOBS profile says that you’re a federal employee and includes your current agency and a verified federal email address.
If you are a student looking for an internship, make sure your profile includes the student hiring path.
Update your USAJOBS profile.
Go back to USAJOBS.
Go to the Open Opportunities Help Center.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-1-18 LHammond in testing

**Comment by Lforeman22** [comment]
@margaretdumas Anyway you can send a screen shot for this? My account has already been verified, and I am not sure I can go back and change this in my USAJOBS profile.

**Comment by Kibrahacha67** [comment]
@Lforeman22 - Here you go
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/24eaeb5f-ab3f-499f-b09a-50630e4b592d)

**Comment by Kibrahacha67** [comment]
@Lforeman22 - Sorry for the miscommunication.  Took me a bit of wrangling but here is the correct screen shot...
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2e76bf61-2df1-4ff6-86bf-0f76ddd57667)

**Comment by tlorrison** [comment]
Final approval
