### ISSUE TITLE
Email Content: Find profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2555]
User Story:  As an Open Opportunities user, I want to be able to confirm I have access to my government email address in order to successfully link my Open Opps and USAJOBS profiles.

Acceptance Criteria: 
When the user select the "Send email" button from the Find your Open Opportunities profile page, an email will be initiated:

To: Email address provided on the find profile page

From: OpenOpps@usajobs.gov

Subject: Find my Open Opportunities Profile

Content:
You recently asked to find your Open Opportunities profile using this email address. Please click the link below to confirm this is your email address and verify you have an Open Opportunities profile.

Ticket 2454 created an email.  This ticket is updating the content of the email.

Functionality from 2454: 
Once the user clicks on the link within the email, their Open Opps and USAJOBS profiles will be linked.
Once the user is signed in they will be taken to the signed in landing page.
If the email does not exist in the system, no email will be sent.
Invision Mock:
https://opm.invisionapp.com/d/main#/console/14593252/311571044/preview#project_console

Related Ticket:
2422 - Find my Open Opps profile
2454 - Find profile email

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

I may need to reset the link on one of your accounts in TEST, if so please let me know which one you would like me to reset so you can initiate a find profile again.

**Comment by Kibrahacha67** [comment]
9-25-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum can you reset my katrina.wagner@opm.gov so I can try to receive this email?  Or, attach a copy?

Thanks!

**Comment by margaretdumas** [comment]
Mdumas - Will this work? 
![image](https://user-images.githubusercontent.com/19936109/46489333-1c340c00-c7d3-11e8-8170-706640456ca0.png)

**Comment by kbwagner** [comment]
Approved.  "Test" should not display in the subject or closing once it goes to production.
@tlorrison ready for final review.

**Comment by tlorrison** [comment]
Final approval
