### ISSUE TITLE
OpenID Connect new logout endpoint

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2563]
## Details ##
The post logout redirect functionality has been added for any client that uses OpenID Connect. In order to use this new functionality, we will need to call the “connect/endsession” endpoint instead of the logout endpoint. We will need to pass in the id_token we were provided during the login process. We will also need to provide the URL we would like to be redirected to post logout.

## Acceptance Criteria ##
- [x] Open Opportunities logout utilizes the new __connect/endsession__ endpoint
- [x] Successful logout will redirect Open Opportunities user to the Open Opportunities logout page (#2541)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-9-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum - I tested this in the TEST environment.  When I click sign out, I get the USAJOBS sign out for a couple of seconds and then it goes to the OPen Opps sign out.  Is there a way to make it so it doesn't blip the USAJOBS and goes right to Open Opps.

**Comment by Kibrahacha67** [comment]
@kbwagner - brought up the same issue and Brice told me that would need further development/tickets.  He is out till monday so he can chime in on that when he returns, but I wanted to relay the information as well.  On the Titan side there will also be more development needed and Margaret relayed that information to me as well...

**Comment by kbwagner** [comment]
Thanks @Kibrahacha67.  Good info.  I'll chat with Brice and see what other tickets we need since I think we really should make the change.  I'll leave this ticket in review for now so I don't forget.

**Comment by kbwagner** [comment]
10/15/18 - KWagner talked to Brice and the ticket needs to be done on the Titan side.  Messaged Dan who will discuss with their dev team and create the ticket.
- Will move this to final review with the note that it's not ideal until the Titan ticket is done.

**Comment by kbwagner** [comment]
10/17/18 - Titan has now fixed the USAJOBS page displaying on the logout.  Only Open Opps page displays.
- Now the yellow "new way to sign in" displays beside the sign out.  Checking with Brice.
