### ISSUE TITLE
Sort by Opportunity does not sort properly in TEST Environment.

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2571]
On the "Your Opportunities" Participated page, the Sort By "opportunity" option does not sort properly. 

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/edcca68f-f0af-4ff6-8429-d9ec10f637fd)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-16-18 LHammond in testing

**Comment by kbwagner** [comment]
10/17/18 - KWagner tested in Test environment in Chrome and mobile Safari.  Also tested in UAT Chrome.
Ready for final review.
