### ISSUE TITLE
Open Opps: footer formatting inconsistent in IE

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2573]
The footer display in IE is not consistent with other browsers (edge, chrome, safari).
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/73286c29-2701-4030-9020-6750c5fa25b1)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-9-18 LHammond in testing

**Comment by kbwagner** [comment]
10/10/18 - KWagner tested footers in UAT and Test.  Chrome and IE are consistent.
Ready for final review.
