### ISSUE TITLE
FAI Community Assignment

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2576]
User Story: As an Open Opportunities community manager, I want to have a role defined that will allow me to only view information related to my community.

Acceptance Criteria: 
-       Create the ability to assign a community manager
- Assign Anne at FAI as a community manager for the FAI community 
-	Run a Data migration script that goes into the system,
-	Insert a record in community table for FAI (separate ticket)
-	Find any opportunity that was posted for career field acquisitions
-	Attach them to the FAI community
-	Find all creators for those opportuntiies and attach them as members of the community

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 see attached artifacts.

__NOTE:__ Anne's account will have to be migrated manually once we deploy to production.

## Search results of Acquisitions
![image](https://user-images.githubusercontent.com/1165615/47222707-72817d00-d385-11e8-983c-75999ed97037.png)

## Converted opportunities
![image](https://user-images.githubusercontent.com/1165615/47222848-c5f3cb00-d385-11e8-97aa-d9f004891afa.png)

## User added as members to FAI community
![image](https://user-images.githubusercontent.com/1165615/47222963-110dde00-d386-11e8-843f-3cb045adcb09.png)

**Comment by Kibrahacha67** [comment]
10-19-18 LHammond in testing
