### ISSUE TITLE
Create FAI Community Attributes

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2577]
**User Story:** As an FAI user, I want to be able to be a part of a community in order to be able to better administrate my opportunities.

**Acceptance Criteria:** 
Create a community for FAI through the database (the UI is currently not available). 

The following information should be entered: 
- Community Name - 
-Agency -
-Community Manager Contact Name - 
-Community Manager Contact Email - 
-Community Administrator - 
-Description (optional) - 
-Target Audience - Federal employee
-Closed Group Y/N.
-Future - Yes will be open to anyone; No/Closed will be invitation only/limited display
-Community Type - Career field, Agency, Program
If Career field selected, then career field dropdown displays (required)
-Agency should default to the agency selected earlier.
-Community related skills - skills related to the community (optional)
-Opportunity Duration: (future: will drive create opportunity template and application flow)
-Valid Values: Ad Hoc, Cyclical, Continual
no default
-Microsite URL
-Support Contact (future: likely a group email that will display on footer, opportunity, etc.?)

Related Tickets: 
2566 Assign Community Admin Role

**Comment by tlorrison** [comment]
Federal Acquisition Professionals - Community attributes will be: 
Community Name -	Federal Acquisition Professionals
Agency -	GSA
Community Manager Contact Name -	Anne Reinhold
Community Manager Contact Email -	Anne.Reinhold@fai.gov 
Community Administrator -	OPM PMO
Description (optional) -	
Target Audience - Federal employee/student	Federal employee
Closed Group Y/N.	No, open to anyone
Community Type - Career field, Agency, Program:	Career Field - acquisition
Community related skills - skills related to the community (optional):	acquisition 
Opportunity Duration: Ad Hoc, Cyclical, Continual:	Ad Hoc
Microsite URL	TBD
Support Contact (future: likely a group email that will display on footer, opportunity, etc.?)	TBD - future

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 see attached artifact.

![image](https://user-images.githubusercontent.com/1165615/47179756-db68e680-d2ec-11e8-8db9-36b8191ba5bb.png)

**Comment by Kibrahacha67** [comment]
10-18-18 LHammond artifact attached moving this to review.
