### ISSUE TITLE
Import Base System Data From USAJOBS Country 

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2584]
User Story: As an Open Opportunities user, I would like for the data in USAJOBS to be the same as the Open Opportunities data to be consistent.

Acceptance Criteria:
Need a process to import base system data from Open Data API

The following tables should be imported:
- Countries
- Country subdivisions

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35511&fullScreen=false&_a=edit

**Comment by Kibrahacha67** [comment]
1-7-19 LHammond reviewed Artifacts moving to review.

**Comment by kbwagner** [comment]
1/8/19 - Reviewed artifact attached.
ready for final review.
