### ISSUE TITLE
Import Systems Data from USAJOBS -  Agency 

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2585]
User Story: As an Open Opportunities user, I would like for the data in USAJOBS to be the same as the Open Opportunities data to be consistent.

Acceptance Criteria: 
- Need a process to import base system data from [Open Data API](https://developer.usajobs.gov/API-Reference)

The following tables should be imported: 

- [ ] Agencies (Abbreviation/Acronym needs to be added to codelist API?)
- Work with Polydeuces on the ability to access acronym data

**Comment by brodydittemore** [comment]
This ticket has a dependency in TFS: 35028. Polydeuces is working on getting this brought into a coming sprint. This will need to be deployed during a release inorder for OO to utilize.

**Comment by Kibrahacha67** [comment]
@bmcorum this ticket needs artifact to get past testing.

**Comment by bmcorum** [comment]
## Agency list USAJOBS
![image](https://user-images.githubusercontent.com/1165615/47665839-7a58d280-db78-11e8-9964-5a709d28e95a.png)

## Agency list OpenOpps after import
![image](https://user-images.githubusercontent.com/1165615/47665892-978da100-db78-11e8-8282-9ebee6d567ce.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 see attached artifacts.

**Comment by Kibrahacha67** [comment]
10-30-18 Moving to review.

**Comment by kbwagner** [comment]
@bmcorum did we get a final decision on the acronyms?  Or is that the piece we can utilize when it's deployed.  Just checking if i need to add a new ticket to grab acronyms?

**Comment by bmcorum** [comment]
@kbwagner we will probably need a separate ticket.

**Comment by kbwagner** [comment]
Created 2636 to bring over agency acronyms. 
- Reviewed artifact.
Ready for final review.

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35510&fullScreen=false&_a=edit
