### ISSUE TITLE
Import System Data USAJOBS-  Language Code

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2586]
User Story: As an Open Opportunities user, I would like for the data in USAJOBS to be the same as the Open Opportunities data to be consistent.

Acceptance Criteria: 
- Need a process to import base system data from [Open Data API](https://developer.usajobs.gov/API-Reference)

The following tables should be imported: 
Language Code

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 see attached artifact. Left is data from source, right is data from destination.

![image](https://user-images.githubusercontent.com/1165615/47150562-e730ba80-d2a4-11e8-9ffd-d1ad22b72de8.png)

**Comment by Kibrahacha67** [comment]
10-18-18 LHammond moving to review.

**Comment by kbwagner** [comment]
10/18/18 - KWagner reviewed attached artifact
- Ready for final review.

**Comment by tlorrison** [comment]
Final approval
