### ISSUE TITLE
Leverage Profile API

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2587]
- [x] Pull profile data when a new USAJOBS user comes to OpenOpps and creates a new account
- [x] Update OpenOpps user profile when edits are made in USAJOBS

**Comment by bmcorum** [comment]
Utilize OpenData

- /api/profile/search
- /api/profile/my/summary

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__NOTE:__ Profile data in OpenOpps is now updated by your USAJOBS profile.

**Comment by Kibrahacha67** [comment]
11-19-18 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum Trying to test this one.  On one computer, when I clicked Edit at USAJOBS.gov I get a Whoops message over and over.  On the other computer, when I click Edit at USAJOBS.gov I am sent to login.gov even though I am in the test environment and am logged on already through login.gov

Any thoughts?

**Comment by Kibrahacha67** [comment]
Let me test and see if I can duplicate...

**Comment by kbwagner** [comment]
@Kibrahacha67 - I'm in Chrome for both computers (a Mac and a Dell).  I'll try again and yet again clear my cache and see what happens.

**Comment by Kibrahacha67** [comment]
@kbwagner - I get the error in edge, talking with Brice now

**Comment by kbwagner** [comment]
11/27/18 - Able to test.  Updated information in USAJOBS and correctly displays in Open Opps
Ready for final review.
