### ISSUE TITLE
Research upgrading NodeJS

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2588]
Research upgrading NodeJS 8 to NodeJS 10

**Comment by bmcorum** [comment]
## Upgrade to NodeJS 10.16.0
- Install node-sass 4.12.0 or newer **(required)**
- Upgrade bourbon-neat (optional)

The bourbon-neat library threw a warning during assets build. Did not appear to negatively affect the ability to build required assets (stylesheets and javascript). I believe the USAJOBS Design System has a hard dependency on bourbon-neat 1.9.0. @abudz19 can you verify if the design system still has this dependency, and if so what can we do to remove it or update it?

![image](https://user-images.githubusercontent.com/1165615/60267612-9b64f500-98b8-11e9-9d2c-947e1e4baee2.png)

**Comment by Kibrahacha67** [comment]
Moving to review

**Comment by kbwagner** [comment]
7/2/19 - Ready for final review.

**Comment by tlorrison** [comment]
@abudz19 adding you for Brice's comment: @abudz19 can you verify if the design system still has this dependency, and if so what can we do to remove it or update it?

**Comment by abudz19** [comment]
@tlorrison This is outside of my skillset, but I can reach out to the design system team at GSA to see if we can arrive at an answer?
