### ISSUE TITLE
Community Manager Role Requirements

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2590]
User Story: As a community manager, I would like to be able to manage my community of users and tasks.

Acceptance Criteria:

Community Manager Role:
- should be able to approve all opportunities within their community only 
- will have administrator access to the community dashboard, users, opportunities
- should be able to assign other members of the community to be community administrators (future)

Dashboard:
- Turn back on/unhide the community dashboard page
- Verify Dashboard numbers reflect only the selected community
- Program Office Administrators should be able to select a community from a dropdown in order to be able to see metrics for any community (can be a new ticket if needed)

Reference Ticket 2589

**Comment by Kibrahacha67** [comment]
10-19-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__NOTE:__ AC for "should be able to approve all opportunities within their community only" is covered with ticket #2612, Manage link for members is handled by ticket #2614.

**Comment by Kibrahacha67** [comment]
10-23-18 LHammond in testing

**Comment by kbwagner** [comment]
11/14/18 - KWagner - Community manager role is established and will be tested with Create Opportunity functionality.
Ready for review
