### ISSUE TITLE
Add agency logo/graphic for community attribute

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2592]
User Story: As a community leader, I want to be able to attach my community logo to my opportunity.

Acceptance Criteria: 
-  Add a field on the community attribute table that will allow for a community logo/icon/graphic to be attached to an opportunity.  
- Requirements for file type and size should be the same as the profile picture
- The logo will be displayed on the opportunity (separate ticket)

**Comment by kbwagner** [comment]
Related TFS ticket 35531 https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35531&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
See below screenshot of the new database schema. Community table can now reference a image file by id.

![image](https://user-images.githubusercontent.com/1165615/48848816-f1961680-ed72-11e8-8f2f-d38939743694.png)

**Comment by kbwagner** [comment]
11/26/18 - Ready for final review.
