### ISSUE TITLE
Open Opps Edit Does Not Navigate to Correct Profile Page

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2597]
When selecting Edit from Open Opps, the user is taken to USAJOBS Profile.  The page they are taken to is the page without the header and space between the cards.  The "/" is missing for the URL.  

![image](https://user-images.githubusercontent.com/19936109/46762860-3f186180-cca6-11e8-8535-ead8b08ba105.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - testing....

**Comment by kbwagner** [comment]
10/17/18 - KWagner tested in the Test environment and the URL now has the / at the end and the USAJOBS navigation displays.
- Ready for final review.
