### ISSUE TITLE
Bug: Able to click on grayed out Next Step button

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2610]
If the Next Step button on the Opportunity is grayed out, it can still be clicked to produce the "Let's get started" modal to go to the next step. Should not be able to click the grayed out button.

2546 fixed the same issue for the complete button.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-23-18 LHammond in testing

**Comment by kbwagner** [comment]
10/24/18 KWagner tested in TEST and works.
Ready for final review.
