### ISSUE TITLE
Bug: Yellow "new way to sign in" banner showing at log out

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2611]
Test Environment

Steps to reproduce: 
1) in Test, sign in
2) Click sign out
3) The yellow "new way to sign in" login.gov banner displays briefly before the signed out page and should not

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-19-18 LHammond in testing

**Comment by kbwagner** [comment]
10/22/18 - Kwagner tested in Chrome Test environment.
Ready for final review.
