### ISSUE TITLE
Community Dashboard: Opportunity .csv

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2613]
User Story: As a community manager, I would like to be able to download basic information related to the opportunities within my community in order to provide additional metrics.

Acceptance Criteria: 
- At the bottom of the community --> Opportunity --> Manage page, there will be a Download list.csv. This will initiate the process to download opportunities (existing report).
- When this report is run from the community page, it should only provide the data related to the community and not other sitewide opportunity information.
- Default sort order will be the filter and then created date (newest to oldest)
- When this report is run, the system should audit/log who ran the report and when.

Related Tickets: 
2601 - Community - Opportunity Metrics
2612 - Community - Manage Opportunties
2613 - Community - Opportunity .csv

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/58910909-b642b000-86e4-11e9-9e97-7d6c188ac54b.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-5-19 LHammond in testing
Sort order of the report should be newest to oldest but it is in the other direction.  Newest is at the bottom of the report.  sending back to development.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-6-19 LHammond in testing

**Comment by kbwagner** [comment]
6/6/19 - KWagner tested in Chrome/Test
Ready for final review.
