### ISSUE TITLE
Community: Manage Members

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2614]
User Story: As a community manager, I want to be able to view information related to my members

Acceptance Criteria: 
On the Community dashboard, When the Manage link is selected for Users:
- There will be a "<Back" that will navigate the user back to the previous page.
- The header will display "Active Members"
- The search box will read, "Filter by name or agency" with a Search at the end
- The total number of active members for the community will display under the search bar.
- Only active members will display.  At this time, disabled users for the community will not display.  To disable a community member for now, the manager will contact the site admin.
- The column headers will be: User #, Name, Email, Agency, Joined Date, and Community Opportunities (Created: # Participated: #), Community Admin
- Joined date will be the date that the user joined the community (which may be different from when they created their account on Open Opps)
- Joined will display mm/dd/yyyy hh:mm and then am/pm (displaying leading zeros when necessary so it will all line up)
- Community Admin (not in mock) will show a toggle button. This will work like it does for the agency admin page. If the toggle is on, the user is a community administrator. If off, they are not.

Invision Mock (note: not up to date - follow AC):
https://opm.invisionapp.com/d/main#/console/13386795/300497097/preview

Related Tickets: 
- 2600 - Community - User metrics
- 2614 - Community - Manage Users
- 2615 - Community - User .csv

**Comment by jhanson12** [comment]
The header will display "Active Members" - for Agency and Community will Display the name of the selected Agency/Community so that the user knows which one they are looking at instead of just "Active Members".

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-13-18 LHammond in testing

**Comment by jhanson12** [comment]
I can.  We did deviated from the Mock to include the Community Name as the header.  We use a template for for all three manage user sections....and the AC was not clear on which header to change.

To clarify, you would like "Users" to say "Active Members"?

**Comment by kbwagner** [comment]
@jhanson12 yes- the screen shot you attached is perfect...Users should say Active members

thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-19-18 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner I have a question on this one, Community is the only tab that has Active members, the other two have Users (Sitewide and Agency).  Did you mean to mix and match or did you want them all to say Active members?

**Comment by kbwagner** [comment]
@Kibrahacha67 I wish I could remember why we did this.  Maybe @bmcorum would remember?  I know it was a purposeful conversation based on the way it's written but can't frankly remember why it's different.

**Comment by kbwagner** [comment]
Ready for final review.

Per Brice: "I believe this was because site admins and agency admins can disable accounts, communities will only show "active" (non-disabled) user accounts"
