### ISSUE TITLE
Community Dashboard: Recent Activity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2617]
User Story: As a community manager, I would like to be able to view recent activity related to my community in order to determine system usage.

Acceptance Criteria: 
- Display recent activity on the Community Dashboard page for Community Managers.
- Should include who joined the community, who created internship/opportunities, but should not include who applied.
- Recent activity will display directly under the first section for members, opportunities, and interactions.
- At this time, the community dashboard page will display only the top line of user metrics and recent activity. Additional dashboard information will be added at a later date.
- Recent activity should only include data for community members and managers 

Invision Mock:  (Note: This is out of date, AC is correct, but gives UI idea)
https://opm.invisionapp.com/d/main#/console/13386795/300494466/preview

**Comment by bmcorum** [comment]
Student communities will not include application submission in recent activity.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-21-18 LHammond in testing

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested in Test/Chrome
Ready for final review
