### ISSUE TITLE
Create Opportunity: Select audience page creation

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2624]
User Story: As an opportunity creator, I want to select the audience who should see the opportunity I am creating in order to target and limit who sees it.

Acceptance Criteria: 
This ticket will create the page shell for the select audience page.  Ticket 2634 will create the functionality behind the page.  The mock is not fully up to date.  Where the mock deviates from the AC please follow the AC.
- When an opportunity creator selects "Create Opportunity" from anywhere within the site, they will get a new page to select target audience
- The page title will read "Create an opportunity"
- The subheading will read "Who's your target audience?"

There will be two boxes to select from eventually - only item #1 will be done with this ticket.: 
1) Federal employees For developmental opportunities (display the federal hiring path icon)
When Federal is selected:
- "Choose a community (optional)" displays a dropdown with any community with a target audience of federal (i.e. FAI).  Note: Mock says "Choose a program" but should be community.  Mock also shows radio buttons which are now a dropdown.
- Community will be optional
- No community will default.  Blank will be the default.  
- If no community is selected, the opportunity will be assigned, as it is now, to the agency for which the opportunity creator is connected to.  See ticket 2634.

2) SECTION 2 IS MOVED TO TICKET 2677 AS OF 11/20/18 - Students For internship opportunities (display the student hiring path icon)
When Students is selected:
- "Choose a community" displays with a dropdown
- The dropdown will include a list of all communities where the Target audience is "Student"
- There will be an option in the dropdown for "None" and none will be the default.  

There will be a Cancel and Continue buttons.
- Cancel will return the user to the previous page
- Continue will be disabled until an audience selection is made.
- Once a community is selected, Continue will be enabled
- Continue will then take the user to the correct Create Opportunity page (i.e. Federal, Unpaid Internship, VSFS) (This will be done with 2634)

Invision Mock: 
https://opm.invisionapp.com/d/main/#/console/15360465/319313488/preview
Public Link: https://opm.invisionapp.com/share/UHNZS9XEYR8#/319313488_Create_-Desktop-

Related Tickets: 
2624 - Select community for opportunity
2625 - Create opportunity
2627 - Create opportunity - Languages
2628 - Preview opportunity
2634 - Select audience functionality

**Comment by kbwagner** [comment]
@abudz19 @humancompanion with trying to keep our embedded design process going - does one of you want to take a look at this and see if it works for you?  I will have to split it into two tickets.  For now, we need to put this in place for FAI.  Then soon after we need to add in the student option for the State release.
- Min didn't have a design for what to display under federal so I used the same design as students but added the word "optional".  Would we want to add any text or help text to clarify that if you don't pick a federal "program" that it will default to your agency?
- Also, is the word "program" good here - I think the "Community" term came after she had done these mocks.

Thanks for any thoughts! (PS - since I don't have email I wont' get a notification on any comments so if you could slack me that there are some I'll go look).

**Comment by abudz19** [comment]
@kbwagner is this ticket also related to https://github.com/openopps/OpenOppsTasks/issues/108

**Comment by kbwagner** [comment]
@abudz19 Yes, this is 108 and I think that one can be closed as I think we are good.  Do you want to close it or should I?  

Also, this one has been updated if you want to do a design review.

**Comment by abudz19** [comment]
@kbwagner I closed 108 and I will review after the PMO meeting, thanks!

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35509&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

__Note:__ The system only has a community of target audience federal. We will need to reach out to the program office for guidance on testing student target audience. Possibly a future ticket.

**Comment by Kibrahacha67** [comment]
11-20-18 LHammond in testing

**Comment by kbwagner** [comment]
updated the AC to remove #2 and that has been moved to 2677

**Comment by kbwagner** [comment]
12/27/18 - Ready for final review.
