### ISSUE TITLE
Create Opportunity:  Unpaid Internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2625]
User Story: As an Unpaid Internship (DOS) Opportunity Creator, I want to be able to enter information into the template for my community in order to provide the specific information relevant to student programs

Acceptance Criteria: 
- When the opportunity creator has selected the audience of Student and Unpaid Internship, they will be taken to the unpaid internship Opportunity Create template

Page layout:
- Header: Create an internship opportunity
- Text: All fields required unless noted
Note: there will not be a blue instruction box
- Step 1: Define who, when, and where
- Who: Display a 2 digit numerical input box 
- When: When would the internship start and end?   Radio buttons for Fall, Spring, Summer.  An input box will display 4 characters numeric only to allow the user to enter the year.
- Where: Where is the internship located? Icons for Virtual and In Person.  When in Person is selected additional location fields will display to select Country, State, and City
- Step 2: Describe the internship (note used to say opportunity)
- Internship title - Write a catchy, but descriptive title to entice participants to click on the internship. 
- There will not be an introduction section as in the current federal opportunity template
- What you'll do - List specific tasks the participant will work on. Be concise, but offer enough details so the participant knows what's involved. (same as federal opportunity template) 
- What skills are you looking for? (limit to 5 allowed like in regular template)
- Foreign languages (optional) - Please list the desired languages and the level of 
- Who we are - Briefly describe your team, bureau, or office/post. 
- Bureau (dropdown - loaded via a separate ticket 2671)
- Office/post (Dropdown of offices related to bureau - loaded via a separate ticket 2671))
- Cancel, Save for later, Preview: 
Cancel will return the user to the previous page without saving changes.  
Save for later will save a draft as it does in production now without notifying the admin, 
Preview will display the selected information in preview form (new ticket 2628).

Invision Mock:
https://opm.invisionapp.com/share/UHNZS9XEYR8#/319309731_Create_-_Unpaid_-Desktop-

Related Tickets:
2624 - Select community for opportunity
2625 - Create opportunity
2627 - Create opportunity - Languages
2628 - Preview opportunity

**Comment by kbwagner** [comment]
@abudz19 this one is ready for you to look at. However, there are some known design changes likely coming based on the usability test review today.  So fine to hold off.  I'll be on the lookout for the changes and will make those changes when ready.

**Comment by tanichacko** [comment]
We need new ticket  for "Save for later" (mock up with what data needs to display ).

**Comment by kbwagner** [comment]
@raywilliams @tanichacko FYI the mock should be updated now.  One thing we took out is the blue instruction box.  That can always be a ticket down the road to remove but just letting you know in case it's an easy fix now.  We meet with State Thursday of this week to go over Create Opportunity specifically.  Thanks!

**Comment by kbwagner** [comment]
@tanichacko for your comment above on save for later I believe Brice said to leave it as part of this ticket.  Save for later will work as it does now for create opportunity and they will go to their signed in landing page/dashboard to see all of the opportunities they have created and this one will show there as draft.  Let me know if you need more info or think it needs to  be pulled separately.  Thanks!

**Comment by raywilliams** [comment]
@kbwagner We went ahead and removed the blue tips box.

**Comment by kbwagner** [comment]
For the Create Opportunity side, please make the label for languages read, "Foreign languages".  Mock is being updated.
- I can create a new ticket if this one is too far along.

**Comment by kbwagner** [comment]
@raywilliams @tanichacko - not specifically stated but looking at production and we should probably be consistent with the rule of only 5 skills allowed on a create.

**Comment by kbwagner** [comment]
@raywilliams @tanichacko - all comments have been included in the AC

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-19-18 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-8-19 LHammond in testing

**Comment by kbwagner** [comment]
@raywilliams one small thing is that the next under Who we are needs to read, "Briefly describe your team, bureau, or office/post."  The /post is missing. 
Testing the rest now but since it's a small change I have a hunch you'll make it before I finish testing the rest!

**Comment by kbwagner** [comment]
@raywilliams @bmcorum question on country, state, city. Since we always talk about Paris...I entered country of France...but both state and city are required....so do I enter Paris Paris?  
![image](https://user-images.githubusercontent.com/18709918/50976453-ff882e00-14bd-11e9-9fe9-812042939cb4.png)

**Comment by raywilliams** [comment]
@kbwagner I've made the text change and I'll get it checked in soon. As far as the state goes, I'll need to have a discussion with Brice to see if State isn't required if you don't choose United States. For now, I guess we can enter Paris Paris. Depending on what Brice thinks, we could get a bug ticket to change whether or not State is required if United States isn't chosen.

**Comment by bmcorum** [comment]
So in USAJOBS I think state is required if there are available options. Some countries will not have any options for state. In instances where there are no available options for state then we should remove the requirement and disable the field.

**Comment by kbwagner** [comment]
@bmcorum should I send this back to dev? Or you want a new bug ticket?

**Comment by kbwagner** [comment]
@bmcorum @raywilliams following up on this question - should I create a new ticket for the city/state issue above?  Or send this back to dev to fix with this ticket?

**Comment by raywilliams** [comment]
@kbwagner Will you please create a new ticket for the city/state issue?

**Comment by raywilliams** [comment]
@kbwagner Will you please create a new ticket for the city/state issue?

**Comment by kbwagner** [comment]
Created 2849 for the country/city/state issue

1/15/19 - This is ready for final review.
