### ISSUE TITLE
Create Opportunity - Unpaid Internship: Preview Page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2628]
User Story: As an unpaid internship opportunity creator, I want to preview my opportunity before submitting for approval in order to make sure I have entered everything correctly.

Acceptance Criteria:
When an unpaid internship opportunity creator selects "Preview" from the Create page, the preview page will display
- Header: Step 3 -Review draft and submit
- The Internship Opportunity Title will display without a label
- The community Logo will display from attribute table
- Desired skills will display with label
- Who we are displays with label
- What you'll do displays with label
- Foreign languages display with label Foreign languages Speaking language skill level, Writing language skill level and selection,and Reading language skill level and selection
The language section will be suppressed if no language was selected
- Any non required fields that are not entered will not display the label and will be suppressed

There will be a blue sidebar that displays additional information:
- Bureau
- Office/post
- Location (City, State)
- Country
- Time commitment
Display start and end dates for the selected cycle which will be created in ticket 2660
Display "32-40 hours per week" for all internships

- Number of interns: Display number selected

Button selections:
- Make Changes - selecting Make changes will return the creator to the Create Opportunity Edit mode
- Save for later - will save to the user's profile as a draft
- Submit - will save the internship and send an email to the community administrator to approve the opportunity (Separate ticket 2653)

Invision Mock:
https://opm.invisionapp.com/share/UHNZS9XEYR8#/319314059_Create-Review_-Desktop-

Related Tickets:
- 2624 - Select community for opportunity
- 2625 - Create opportunity
- 2627 - Create opportunity - Languages
- 2652 - Review/Apply Opportunity Page

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35506&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
@jhanson12 per the state department meeting there are a few changes to the preview. Do you want a new ticket or just modify here? 
1) Language will not say "required"
2) Blue bar language required yes/no will go away
3) Bureau/Office will now be Bureau/office/post as a label.
Happy to write a new ticket just wanted to check.  Alex has updated the mocks already

**Comment by kbwagner** [comment]
For languages on the intern view, please use the following: "Foreign Languages” and add help text under - These languages may be helpful in the internship." for the internship view.

**Comment by kbwagner** [comment]
@jhanson12 - The AC has been updated to reflect all of the decisions.

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-19-18 LHammond in testing

**Comment by kbwagner** [comment]
1/3/19 - KWagner tested in Chrome...Test environment.
1) Logo must say "U.S. Department of State" across the board. I can create a new ticket for that if need be since it's a newer requirement from them.
2) Time commitment currently displays "Fall 2018"  but should actually display the  time period associated.  @jhanson12 is this just displaying since we don't have the dates built in yet?  If so, i can create another ticket to update this once we have dates plugged in.  But let me know.

**Comment by kbwagner** [comment]
@jhanson12 did you see my question above?  The time commitment displays "Fall 2018"...is that just because we don't have cycle dates in?  Dates should appear here.
