### ISSUE TITLE
DHS: Create Community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2629]
User Story: As a DHS Joint Duty Program manager, I want to be able to have a community so that I can post detail opportunities specific to my program.

Acceptance Criteria:
The following information should be entered in the Community table in order to set up the DHS community:
- Community Name: DHS Joint Duty Program
- Agency: DHS
- Community Manager Contact Name: Kenneth Johnson
- Community Manager Contact Email: JointDutyProgramOffice@hq.dhs.gov
- Community Administrator: Kenneth Johnson
- Description: The Department of Homeland Security Joint Duty Program is an intra- and inter-departmental program that offers civilian personnel professional and developmental opportunities.  Joint duty assignments enhance operations and mission execution through unity of effort and collaboration.  The program covers Federal employees at the GS-13 through GS-15 grade levels and equivalent. 

- Target Audience: Federal
- Closed Group: No (it will be an open group)
- Community type: program
- Community Related skills: Blank
- Opportunity Duration: Ad Hoc (open until closed)
- Microsite URL: JointDutyProgramOffice
- Support Contact: JointDutyProgramOffice@hq.dhs.gov

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/48433326-dd379580-e744-11e8-8c1e-b07880971c89.png)
![image](https://user-images.githubusercontent.com/1165615/48433359-e9bbee00-e744-11e8-9d93-3aeb56a1fe28.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-13-18 Artifact attached. moving to review.

**Comment by kbwagner** [comment]
11/14/18 - KWagner - Reviewed attached artifact.  Ready for final review.
