### ISSUE TITLE
Create Opportunity: Select Audience functionality - part 1 federal

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2634]
User Story: As an opportunity creator, I want to select the audience who should see the opportunity I am creating in order to target and limit who sees it.

Acceptance Criteria:  
- The mocks are not updated so please follow the AC and when there is a discrepancy follow AC
- When Create Opportunity is selected, the system will look at the creator's information to determine what sections they should see on this page.

Scenarios: 
1) If the Opportunity Creator is not connected to any community, they will not see this page and will go directly into the Create Opportunity template as they do now.
2) If the Opportunity Creator is only connected to a community with a target audience of Federal
- Only display the federal option and related community dropdown
- The dropdown will only display federal communities for which the creator is assigned along with the "None" option
- The user is not required to select a federal community.  If no community is selected, the system will assume that this is an agency opportunity and will assign based on the agency from the user's profile as it does now.
Buttons: 
- Continue will then take the user to the correct Create Opportunity page (i.e. Federal, Unpaid Internship, VSFS) (This will be done with 2634)

Ticket 2628 will cover scenarios 3 and 4 for student
Invision Mock: 
https://opm.invisionapp.com/d/main/#/console/15360465/319313488/preview
Public Link: https://opm.invisionapp.com/share/UHNZS9XEYR8#/319313488_Create_-Desktop-

Related Tickets: 
2624 - Select community for opportunity
2625 - Create opportunity
2627 - Create opportunity - Languages
2628 - Preview opportunity
2634 - Select audience functionality

**Comment by Kibrahacha67** [comment]
@kbwagner In scenario #4 where "State" is mentioned did it mean Student?  As State Department would be part of Federal, I didn't want to get confused while testing...Thanks for clarification

**Comment by kbwagner** [comment]
@Kibrahacha67 yes sorry that would be Student.  I'll change it.

**Comment by Kibrahacha67** [comment]
@kbwagner thank you:)

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35505&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-20-28 LHammond in testing

**Comment by kbwagner** [comment]
11/20/18 - updated AC to pull student criteria and created 2628

**Comment by kbwagner** [comment]
11/27/18 - Tested.  REady for final review.
