### ISSUE TITLE
Import agency acronyms to agency table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2636]
Work with Polydeuces to pull over agency acronyms to the agency table when available.

Related to 2585

**Comment by kbwagner** [comment]
@bmcorum can you check whether this has been done?

If so, might add another ticket to allow us to search on agency acronyms.

**Comment by bmcorum** [comment]
We are now able to get acronyms if known from USAJOBS

![image](https://user-images.githubusercontent.com/1165615/73973438-8e00f600-48f0-11ea-947f-7262ae057f4f.png)

Will need to run a new data migration to re-import agency data from USAJOBS

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41580&_a=edit
