### ISSUE TITLE
Home page option "Based on your Agency" does not update when Profile>Agency option is changed

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2644]
When the profile is edited to change the agency, when I sign back into Open Opps account, I am expecting my home page option" Based on your agency" to change as well.  It does not.  It still shows the previous agency option.

Steps to reproduce:
1.	Sign into an OpenOpps account
2.	Edit profile to change agency
3.	Sign back into OpenOpps
4.	Navigate to home page
5.	Notice that “Based on your agency” does not reflect the new agency

**Comment by kbwagner** [comment]
@Kibrahacha67 - I still see this as an issue in test.  
- Current profile says I work for OPM
- On my Open Opps profile, clicked on Edit and USAJOBS
- Changed my agency to be Federal Acquisition Service, saved, returned to Open Opps
- My Open Opps profile says Federal Acquisition Service.
- Click on my name to get to the landing page.  Based on agency still says OPM

![image](https://user-images.githubusercontent.com/18709918/59351603-c6fab380-8cec-11e9-96b3-45bde28be291.png)


Moving this one back to development although not sure it started there so feel free to move to the appropriate place.  Would be good to get fixed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by kbwagner** [comment]
6/18/19 - KWagner tested Chrome/Test environment
Ready for final review
