### ISSUE TITLE
Create New Opportunity Opens and anchors at the bottom of the page. Edge

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2648]
Selecting creating a new opportunity anchors at the bottom of the page. 

Steps to reproduce:
1.  Navigate to OpenOpps
2.  Sign in
3.  Select "Create opportunity" option

Results:  New opportunity page is displayed but does not anchor at the top of the page

**Comment by Kibrahacha67** [comment]
6-12-19 Tested in Edge, IE, Chrome, FireFox, Safari moving to review.

**Comment by kbwagner** [comment]
6/12/19 - KWagner tested in Edge.  Issue is resolved.
