### ISSUE TITLE
Admin option for Community manage members does not flag admins

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2649]
Although admins are displayed on page, they are not flagged and the assign admin option does not seem to work. If selected this option only spins.  

Steps:
1. Navigate to site
2. Sign in
3. Navigate to Community>Manage Users page

Results:  None of the admins are flagged as admins and if you attempt to use the Assign option it spins and doesn't change anything.

**Comment by jhanson12** [comment]
This has been fixed and had not been merged with the code yet.
