### ISSUE TITLE
Add ability to request being added to the newsletter to home page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2650]
In order to bring more users to the newsletter for Open, Opportunities, add the ability for a user to click a link that initiates an email to newsletter administrator to request they be added to the newsletter distribution.
- Per conversation with Alex and Katrina 11/6/18 - possible have a button that initiates an email to administrator that includes user's email and request

Related Ticket:
- Link MyEmma and Open Opps so new users are automatically sent to MyEmma

**Comment by kbwagner** [comment]
@abudz19 - want to add this as a design ticket?

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41485&_a=edit
