### ISSUE TITLE
Create Opportunity: Unpaid internship View/Apply View of Opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2652]
User Story: As an unpaid internship applicant, I want to be able to view the full opportunity in order to decide if I want to apply.

Acceptance Criteria: 
- When an opportunity is selected by clicking on the Opportunity Card, the opportunity will display as follows: 
The same information displayed on the Opportunity Preview (ticket 2628) will display with exceptions noted below:
- The Step 3 header does not display
- There is a "Back to results link" that will be handled with ticket 2187
- The community attribute logo will link to the Unpaid Internship info page: https://careers.state.gov/intern/student-programs/
- Desired skills will display with label.  Each skill will be a link that will run a search using that skill as a filter 
- No opportunity status bar will display for unpaid internships
- Students will see a Share link 
- Save will be a future ticket and may not be part of MVP so should not be included (it is in mock)
- A community administrator for the opportunity who is logged in will have the ability to edit and duplicate.  Edit and duplicate will follow current production functionality.
Who we are displays with label
What you'll do displays with label
- "Foreign languages" will  display with subtext that reads, "These languages may be helpful in the internship." with labesl Language name, Spoken language skill level and selection, Written language skill level and selection, Read language skill level and selection
- The language section will be suppressed if no language was selected
- Any non required fields that are not entered will not display the label and will be suppressed

**There will be a blue sidebar that displays additional information:**
Bureau
Office/post
Note: Section will not display even if it's on the mocks.  
Location (City, State)
Country
NOTE: Language requirements will NO longer display in the blue bar
Time commitment
Display start and end dates for the selected cycle which will be created in ticket 2660
Display "32-40 hours per week" for all internships

Number of interns: Display number selected

**Apply Section:** 
To the right of the opportunity section, the apply box will display as follows:
Before you apply (header)
To apply to the unpaid Student Internship Program, you must: 
- Be a U.S. citizen
- Be a current student
- Have at least a 3.0 GPA on a 4-point scale
- Be able to receive and maintain a security clearance

For more information
Visit U.S. Department of Unpaid Student Internship website
- this will be a link to https://careers.state.gov/intern/student-programs/ (confirm link with DOS)

There will be an Apply button which will kick off the Apply Process. This will be handled by a separate ticket 2484.

**Invision Mock:** 
https://opm.invisionapp.com/share/UHNZS9XEYR8#/320303454_State_-_Opportunity_-Desktop-

Related Tickets: 
2628 - Opportunity Preview

**Comment by kbwagner** [comment]
Related TFS ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35533&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
@raywilliams @tanichacko I have a slight update to this ticket based on our meeting with State last week.  Do you want me to create a new ticket?  Or would you rather update here?  
1) Bureau/Office should now be Bureau/office/post (if that doesn't fit then we'll stick with bureau/office)
2) We should remove the piece in the blue bar that says "Language required" yes/no
3) Languages should not say "Languages Required"...I can't get into the mock right now but I think it was going to say Language preferences (Invision is doing an upgrade)
Happy to put this in a new ticket but let me know your preference

**Comment by raywilliams** [comment]
I think we can go ahead and update this without a new ticket.

**Comment by kbwagner** [comment]
thanks Ray.  Once invision comes back up, the mocks should be up to date.  Invision is down for maintenance right now ughh.

**Comment by kbwagner** [comment]
State department has requested the following label change for Language requirements (invision mock in the process of being updated):  For the intern view:
Make title "Foreign Languages” and add help text under - These languages may be helpful in the internship.
- I'm happy to write a new ticket.  Just let me know.  I think this is the last change on Create.

**Comment by kbwagner** [comment]
@raywilliams @tanichacko AC has been updated to reflect all of the comments.

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-9-19 LHammond in testing
In the description section of the card, the What you'll do section is before the Who we are section.  The AC and Design have it in the other order.  See screen shot below.  sending back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/22e84312-d419-4238-9abe-4b78b25827de)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-10-19 LHammond in testing

**Comment by tanichacko** [comment]
@kbwagner- Made the change for the issue "U.S. Department of State Internships to open in a new window". It will be in  test once new build happens.

**Comment by kbwagner** [comment]
@tanichacko @raywilliams The only other thing I see is in the blue bar Office should be "Office/post".  The AC is correct but the mock isn't updated.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-16-19 LHammond in testing

**Comment by kbwagner** [comment]
1/16/19 - 
- Help opens in new window
- Text now reads Office/post (although with a capital P instead of lower/sentence case but it's fine)
ready for final review.
