### ISSUE TITLE
Create Opportunity Approval Email for Communities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2653]
User Story: As a community manager, I want to receive an email to notify me there is an opportunity to review and approve.

Acceptance Criteria: 
- If the opportunity that has been submitted is related to a community, once submitted an email should go to the community managers to indicate that there is an opportunity to approve.  

There are 4 emails related to Creating/Approving Opportunities.  
1) Save draft opportunity - goes to the creator
2) Opportunity submitted confirmation - goes to the creator
3) Admin needs to approve opportunity - goes to the community manager
4) Admin has approved opportunity - goes to the creator

Future Action:  Will create a new ticket for how this email should work with students.
- Verify email content whether it can stay the same or should change.
- Question - will this be necessary for Unpaid internships since they will all go in at the same time?  VSFS might use though?  FAI definitely needs

**Comment by kbwagner** [comment]
Related TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35534&fullScreen=false&_a=edit

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - AC Question, Is the 4 emails described in the AC expected in this ticket or is that a statement to ensure what we have currently?

**There are 4 emails related to Creating/Approving Opportunities.
  --Save draft opportunity - goes to the creator
  --Opportunity submitted confirmation - goes to the creator
  --Admin needs to approve opportunity - goes to the community manager
  --Admin has approved opportunity - goes to the creator

**Comment by kbwagner** [comment]
@Kibrahacha67 no sorry that is confusing...just the one email is involved and it's the one for the community manager approval

**Comment by Kibrahacha67** [comment]
Great, thank you

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-8-19 LHammond in testing

**Comment by kbwagner** [comment]
1/8/19 - KWagner tested in Chrome/Test environment.
- received the email to my community manager email account
- my sitewide admin account did not receive the email which is correct.
Ready for final review.
