### ISSUE TITLE
Cycle Time Functionality - when to post an internship for applying

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2654]
User Story: As a community administrator, I want to use the start and end dates for my community application cycles to determine when the opportunity displays in search in order to use the applicant cycle times of my program.

Acceptance Criteria: 

Post/Unpost Internship/Opportunity:
- If the opportunity has been assigned to a community and the opportunity has been approved by the community admin then use the community application dates from the community dashboard page (ticket 2660) to determine when the internship should be posted and unposted:
- The opportunity should not display on the appropriate search until the start date of the opportunity as 12:01 AM EST
- The opportunity should no longer display on any search once the end date of the opportunity has been reached at 11:59PM EST.

**Comment by kbwagner** [comment]
Related TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35535&fullScreen=false&_a=edit

**Comment by Kibrahacha67** [comment]
@kbwagner - question is this ticket approved?  Im not sure the AC is complete so just checking...thank you

**Comment by Piglady64** [comment]
@Kibrahacha67 Katrina is off today so I am not sure she will respond today.

**Comment by Kibrahacha67** [comment]
@Piglady64 thanks for letting me know...can wait till she returns for answers...

**Comment by kbwagner** [comment]
@Kibrahacha67 yes it's done - not sure why the requirements ready tag fell off but I added it back.  @tlorrison will need to approve it but the AC is done unless you see something missing

**Comment by Kibrahacha67** [comment]
@kbwagner Thanks just trying to make sure before test cases are written...thank you for responding to both tickets.

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
2-7-19 LHammond in testing

**Comment by kbwagner** [comment]
@Kibrahacha67 trying to figure out how to best test this.  I wanted to go create a cycle that started today and ends tomorrow but I can't do that since it overlaps with an existing cycle date.  Were you able to test that it posted and was pulled off based on the apply dates of the cycle?  I can see that they post but not that they are pulled down.

**Comment by kbwagner** [comment]
2/18/19 - Placing hold tag.  Unable to test until we can view the UI for cycle or add a one day cycle.

**Comment by kbwagner** [comment]
5/7/19 - KWagner tested in Test environment.
Ready for final review.
