### ISSUE TITLE
Community: Who can Create an Opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2655]
User Story: As an unpaid internship community, I want to restrict who can create an opportunity to community administrators so that students are not able to create opportunities.

Acceptance Criteria: 
- Anyone who is logged out on a Search for Target Audience of Student will never see the "Create Opportunity" button
- Any student who is logged in but is not a member or administrator of the community will never see the "Create Opportunity" button

The Create Opportunity button will display for student community members and administrators only in the following locations: 
- On the search page in the search banner (mock: https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-  
- On the signed in landing page for community admin/members

Additional Scenarios: 
•	FAI - open community - anyone can post, anyone in target audience can apply. On first post, opportunity creator automatically gets add as a community member if not already one.
•	DHS - open community? - anyone can post, anyone in target audience can apply. On first post, opportunity creator automatically gets add as a community member if not already one.
•	DOS Unpaid - closed community - anyone in target audience can apply, only members can post.
•	DOS VSFS - - closed community - anyone in target audience can apply, only members can post.

**Comment by kbwagner** [comment]
Related TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35536&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by jhanson12** [comment]
![image](https://user-images.githubusercontent.com/15199629/51764637-a87c7e80-20a3-11e9-9c0c-06dd19ed548d.png)
You have to click next to see it in the mocks.

**Comment by Kibrahacha67** [comment]
1-25-19 LHammond in testing

for admins Button can be seen on both home and search
for community members it can be see on home but not search
for students the button cannot be see on either home or search

Tested in chrome, ie, edge and safari, moving to review.

**Comment by kbwagner** [comment]
1/30/19 - KWagner Chrome/Test
- Tested as admin I can see Create
- Tested signed out, I can't see create for internship page
- Tested signed in as student, can't see create
Ready for final review.
