### ISSUE TITLE
Community Table: Cycle Table 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2660]
User Story: As a community administrator, I want to be able to select the start and end dates for each of my cycles on a yearly basis so that I can control when my internships are displayed for applicants.

Acceptance Criteria: 
Create a table for cycle data that will include:
1) Cycle Dates mm/dd/yyyy
Unpaid internships will have 3 cycles:
- Spring
- Summer
- Fall
For each cycle and each year, the community administrator will need to be able to set a start and end date every year. Month/Day/Year

2) Apply dates start and end mm/dd/yyyy
- Apply dates will control when an internship is posted and pulled off in related ticket 2654

Additional fields as listed below:
![image](https://user-images.githubusercontent.com/18709918/49195172-f9961d80-f353-11e8-846a-3cc66efbef1c.png)

**Comment by kbwagner** [comment]
Related TFS ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35544&fullScreen=false&_a=edit

**Comment by Kibrahacha67** [comment]
12-21-18 LHammond - Artifact attached, moving to review.

**Comment by kbwagner** [comment]
1/3/109 - Reviewed artifact. 
ready for final review.
