### ISSUE TITLE
Create Opportunity:  Language Selection display

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2665]
User Story: As an opportunity creator, I want to be able to add language requirements to my internships in order to display the requirements to an applicant.

Acceptance Criteria:
On the Create Opportunity page, once a language has been added it will display as follows on the main create page: 
Mock: https://opm.invisionapp.com/share/UHNZS9XEYR8#/319318712_Create_-_Unpaid_-_Language_-Desktop-
NOTE: The mock is not up to date - please follow the AC.

- Language
- Speaking language skill level - display creator selection
- Writing language skill level - display creator selection
- Reading language skill level - display creator selection
- There will be a delete link under each language added.  When selected, the language will be removed from the opportunity
- Multiple language selections will be separated by a line.

Related Tickets:
2624 - Select community for opportunity
2625 - Create opportunity
2627 - Create opportunity - Languages
2665 - Add languages display
2628 - Preview opportunity

**Comment by kbwagner** [comment]
Associated TFS Ticket 3558: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35558&fullScreen=false&_a=edit

**Comment by kbwagner** [comment]
@tanichacko - all changes are noted in the AC above.  Let me know if you have any questions.  The mocks are in the process of being updated.

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
12/20/18 - Mdumas - Moving back to development.
- Languages are not loading
- radio buttons to select levels are not displayed

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
12/21/18 - Mdumas - testing...

**Comment by margaretdumas** [comment]
Questions?   

- When a language is added, should the skill set go back to the default?  
- AC calls for "Language name" but if "Language" ok?

**Comment by kbwagner** [comment]
@margaretdumas 
- Yes, when a language is added the default should go back to "skill".  Confirmed that's how core works.
- Updated AC to say "Language" instead of "Language name"

**Comment by margaretdumas** [comment]
1/3/19 - Mdumas - Moving back to Development.  When a language is added the skill level does not go back to "None" instead it remains on the last selections.

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - tested and moving over to review.

**Comment by kbwagner** [comment]
1/8/19 - Tested and moving to final review.
will verify all language text once it is moved to test.
