### ISSUE TITLE
Elastic: Implement new elastic search service/API

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2669]
User Story: As a user, I want to be able to have a search tool which will allow me to search more efficiently for opportunities.

Acceptance Criteria: Implement the new elastic search service/API on Open Opportunities

**Comment by kbwagner** [comment]
Related TFS 35582: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35582&fullScreen=false&_a=edit

**Comment by Kibrahacha67** [comment]
1-4-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-16-19 LHammond in testing

**Comment by kbwagner** [comment]
1/16/19 - KWagner tested in Chrome/Test environment.  
Ready for final review.
