### ISSUE TITLE
Email to notify a user they are invited to a community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2670]
User Story: As a community manager, I want an email to be sent when I invite a new member to a community in order to notify them that they have been added.

Acceptance Criteria: 
When a user is added to a community through the community dashboard, the following email will be sent:

Email: Community Member Invite

Trigger: A community admin adds a user (clicks invite member) to their community.

Audience: A new member of an Open Opps community

Email subject: Welcome to the <insert community name> 

Hi <insert Open Opps user name>,
<Insert Open Opps Community Admin Name> has added you as a member of the <Insert Open Opps Community Name> Community. As a community member you can connect with other members who share similar interests, and apply to or post opportunities specific to the community.
Thanks,
The Open Opportunities Team 

Note on Open Opps Community Name: For example, if the community name is “Unpaid Internship”, the message should say “…member of the Unpaid Internship Community.”

[Open-opportunities-email-community-invite_20181206_v2 (1).docx](https://github.com/openopps/openopps-platform/files/2667897/Open-opportunities-email-community-invite_20181206_v2.1.docx)

Related ticket 2534: Invite users to a community

**Comment by kbwagner** [comment]
TFS 35585: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35585&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-8-19 LHammond in testing

**Comment by kbwagner** [comment]
1/8/19 - KWagner added Tracy as a member of the unpaid internship community and she received the email.  Email content is correct.
Ready for final review.
