### ISSUE TITLE
Load DOS bureau/office

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2671]
User Story: As an Unpaid Internship community member, I want to be able to create opportunities using my bureau and office data in order to allow interns to search for opportunities using this information.

Acceptance Criteria: 
- Add new columns to the current task table (where opps are stored) for bureau and office. 
- Data will be hierarchical - with offices relating to a bureau
- DOS to provide the data

Need data

**Comment by kbwagner** [comment]
TFS 35590: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35590&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. You can now select from a list of bureaus and once a bureau is selected you will get a list a related offices within that bureau if any exist.

**Comment by margaretdumas** [comment]
02/06/2019 - Mdumas - In testing..

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
@kbwagner @sabushanab This ticket is only for verifying that we have data loaded in the Bureau and Office/post fields  correct? I asked because I believe we are still ironing out those cases where there are no data for the office per the conversation this morning and I didn't want to fail it for that reason.

Thanks

**Comment by kbwagner** [comment]
@margaretdumas yes we are still waiting for the actual data from DoS so we don't know for sure if there will be instances where there is no office data.  I have a note to write a new ticket for that scenario as well.
- So yes - it's just that there is data loaded for now.

**Comment by sabushanab** [comment]
![bureau_data_load](https://user-images.githubusercontent.com/979314/52369115-f38c7f00-2a1d-11e9-9bc6-5eb8277dd4c0.PNG)
![office_data_load](https://user-images.githubusercontent.com/979314/52369116-f38c7f00-2a1d-11e9-91f9-dfee8ffa4076.PNG)

**Comment by sabushanab** [comment]
image showing task table has a link to the new bureau and office data
![task_data_load](https://user-images.githubusercontent.com/979314/52369325-76add500-2a1e-11e9-87cb-6600ab2220ca.PNG)

**Comment by margaretdumas** [comment]
Mdumas - Artifact added and verified Bureau/office can be added.  Moving on to review.

**Comment by kbwagner** [comment]
2/6/19 - KWagner reviewed artifact
- We will write a new ticket when we receive the actual data from DoS.
- Ready for final review.
