### ISSUE TITLE
Create Opportunity: Select Audience creation part 2 - Student

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2677]
User Story: As an opportunity creator, I want to select the audience who should see the opportunity I am creating in order to target and limit who sees it.

Acceptance Criteria: 
This ticket will create the page shell for the select audience page.  Ticket 2634 will create the functionality behind the page.  The mock is not fully up to date.  Where the mock deviates from the AC please follow the AC.

There will be two boxes to select from: 
1) PART 1 WAS COMPLETED WITH 2624 AND IS HERE FOR REFERENCE ONLY - SEE PART 2
Federal employees For developmental opportunities (display the federal hiring path icon)
When Federal is selected:
- "Choose a community (optional)" displays a dropdown with any community with a target audience of federal (i.e. FAI).  Note: Mock says "Choose a program" but should be community.  Mock also shows radio buttons which are now a dropdown.
- No community will default.  
- If no community is selected, the opportunity will be assigned, as it is now, to the agency for which the opportunity creator is connected to.  See ticket 2634.

2)Students For internship opportunities (display the student hiring path icon)
When Students is selected:
- "Choose a community" displays with a dropdown
- The dropdown will include a list of all communities where the Target audience is "Student"
- There will be no default 
2624 HANDLED THE BUTTONS FOR THIS PAGE BUT FOR REFERENCE AND REGRESSION TESTING:
There will be a Cancel and Continue buttons.
- Cancel will return the user to the previous page
- Continue will be disabled until an audience selection is made.
- Once a community is selected, Continue will be enabled
- Continue will then take the user to the correct Create Opportunity page (i.e. Federal, Unpaid Internship, VSFS) (This will be done with 2634)

Invision Mock: 
https://opm.invisionapp.com/d/main/#/console/15360465/319313488/preview
Public Link: https://opm.invisionapp.com/share/#/319313488_Create_-Desktop-

Related Tickets: 
2624 - Select community for opportunity
2625 - Create opportunity
2627 - Create opportunity - Languages
2628 - Preview opportunity
2634 - Select audience functionality

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35773&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
12/5/18 - Ready for final review
