### ISSUE TITLE
Select Target Audience part 2-  Student communities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2678]
User Story: As an opportunity creator, I want to select the audience who should see the opportunity I am creating in order to target and limit who sees it.

Acceptance Criteria:  
- The mocks are not updated so please follow the AC and when there is a discrepancy follow AC
- When Create Opportunity is selected, the system will look at the creator's information to determine what sections they should see on this page.

Ticket 2634 did the first two scenarios. This ticket will cover the additional two for students.
1) If the Opportunity Creator is connected to a community with a target audience of Student
- Display the federal option but with no community dropdown.  If this option is selected, the opportunity will be assigned to the creators agency and the standard opportunity template will be used
- Display the student option with a dropdown that only displays the communities that the creator is associated with.  
- The user must either select federal or a student community
2) If the Opportunity Creator is connected to multiple communities with both target audiences of federal and student
- Display the federal option with the community dropdown that displays any communities the user is associated with that have a target audience of federal.  The user can select a federal community or none.  
- If none is selected, the opportunity will be associated with the agency for the creator
- If a federal community is selected, the opportunity template for that federal community will be used and the opportunity will be associated to that federal community.
- Also display the student option with the community dropdown that displays any communities that the creator is associated with 
- If the student button is selected, a student community must be selected.
- In this scenario, either the federal or student option must be selected

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35774&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-29-18 LHammond in testing

**Comment by kbwagner** [comment]
12/5/18 - Tested in Chrome.  Ready for final review.
