### ISSUE TITLE
Secondary Navigation bar disappears during account creation and on different pages

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2679]
Secondary nav disappears during set up of accounts (below)  if the user refreshes page or signs out and comes back into page then it reappears (second image below).  Related to ticket 2401.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ccdd2365-ab8b-4c2f-b49b-06b4cc6b5479)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/45a91077-ddcb-41a3-8c91-08a79028c5ba)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
11/27/18 - Test in Chrome - ready for final review.
