### ISSUE TITLE
Search: Student Shell page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2701]
User Story: As a student intern, I want to be able to see a search page that is specific to my internship community.

Acceptance Criteria:
The shell of the unpaid internship page will display:

Yellow banner:
- Yellow banner that reads, "Student internship"
- The community logo will display in the yellow banner 
- The yellow banner will include keyword and location search
- Keyword search will have default text as follows, "Skill, language, bureau, office/post, etc."
- Location search will have default text as follows, "City, state, or country"

Blue instruction box:
- A blue instruction box will display based on the program selected.  (covered in a new ticket)
- This ticket will include the space for the blue box in the shell of the page

Filter display: 
- The right rail will display filters for Program, Skill, Language, Agency, Bureau, Office/post.  
- Functionality behind these filters will be done in separate tickets
- There will be a question mark for help text.  The help will take the user to "https://usajobs.github.io/openopps-help/opportunity/search/" in a new window

Opportunity Cards:
 - The main section of the page will display opportunity cards in two rows as currently in production
- Standard pagination will be used 10 per page for desktop

Footer: 
- The footer for the student search page will be the standard Open Opps footer but will not include the link to the Help Center or the email OpenOpps@usajobs.gov.
- Visit our Help Center will be replaced by Visit https://careers.state.gov/ (link)

Mock: 
https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

Associated TFS Ticket https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35761&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-23-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-25-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - Question when I'm logged in as an admin there is a "+Create internship" button after the "Student internship" header.  Is that correct, not in AC.

**Comment by kbwagner** [comment]
That’s fine as long as it’s only admin. A student should never see it. That’s part of another ticket.

**Comment by kbwagner** [comment]
@tanichacko please update the default text that appears in the keywords box to match the mock.  It should not include Major since that is no longer a filter.  Should say Skill, language, bureau, office/post, etc.

**Comment by kbwagner** [comment]
@abudz19 the shell of the student search page is in test if you'd like to take a look.

**Comment by tanichacko** [comment]
@kbwagner-  I checked in the default text change. It will be in test once the build happens.. Also I want to mention we don't get alerts/notifications when you update mock so can you please update the acceptance criteria.?

**Comment by kbwagner** [comment]
I don’t always see them either and normally I’d write a new ticket if it changed - not sure when it did. But since we don’t have major as a field it needed to be fixed. I’ll chat with design and make sure we can communicate on any mock changes. Thanks!

**Comment by kbwagner** [comment]
@tanichacko it doesn't look like the footer change was  made here to not include the open opps email but instead direct them to the state link.  
- I also see the help link was still marked TBD in the AC sorry - I need to verify which link that should be and will get back to you ASAP.

**Comment by abudz19** [comment]
@kbwagner @tanichacko I will do a better job of making sure updates to the mock are communicated to the right people. 
After reviewing I found the following typos:
- There is a missing period on U.S. Department of State Student Internship Program (Unpaid) radio button, on the filter pill when it appears, and in the cycle notification alert. 
- The acronym of (VSFS) is missing on the radio button and on the filter pill. Should read Virtual Student Federal Service (VSFS)

**Comment by Kibrahacha67** [comment]
1-31-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner - as it stands, the Agency search filter only displays if the "Virtual Student Federal Service (VSFS)" radio button is selected, but that is not in the AC.  If that is the functionality that should be displayed please amend the AC if not please let me know so that I can send this ticket back to dev.  thank you...

**Comment by kbwagner** [comment]
@Kibrahacha67 that's correct and is listed out on the agency ticket 2708.

**Comment by kbwagner** [comment]
1/6/18 - KWagner tested in Chrome/Test environment.
- Default text missing from Bureau and Office/post filters.  I will make a note in those individual tickets to make sure it is added.
- Ready for final review.
