### ISSUE TITLE
Search: Student Opportunity Card Display

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2702]
User Story: As a student, I want to see a quick view of the internship to determine if I want to view more.

Acceptance Criteria:
On the Student internship search view, the following will display on the Opportunity card:
- Internship opportunity title
- The first 4 lines of "What You'll do" will display  (Note: mock doesn't match - follow AC)
- The bureau/Office or post name will display next 
- The city, state and country will displayed.  If country is US, country does not need to display.
- Languages will not display on the card but will display in the full Internship opportunity
- Skills will display as green pills as they do in production.  Only 5 skills can display on the Opportunity card.
- The community logo will display along with the Agency name and Community name

The entire card will be clickable like they are in production.

Note: Where the mock doesn't match the AC, follow the AC

Mock: 
https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35762&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
@kbwagner Question one of the requirements for location is City, State and Country.  Are  you expecting US to show?

**Comment by kbwagner** [comment]
@Kibrahacha67 no, if US is the country it can be blank.  I can update the AC.

**Comment by kbwagner** [comment]
@raywilliams - 
1) The country isn't showing.  I selected France and it doesn't display, just the city and state.  If I select a country other than the US, the country should display.
2) The location icon is different then the one that is used in the mock and USAJOBS.  According to Brice it's the one that is used in the system so I will need to create an enhancement request to have it changed across the board which I can do.  Just noting it here.

Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-31-19 LHammond in testing

**Comment by kbwagner** [comment]
@abudz19 for your review (location icon has been updated)

**Comment by kbwagner** [comment]
2/6/19 - KWagner tested in Test/Chrome
- Ready for final review
