### ISSUE TITLE
Search Filter: Program

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2704]
User Story: As a student, I want to be able to search for internships for VSFS or Unpaid using my search filters.

Acceptance Criteria:
- The Program filter will display both student programs as radio buttons. Student internship program (unpaid) and Virtual Student Federal Service (VSFS)
- Default the radio button based on where the student comes in from.  This will be a later ticket 3010
- Selecting the Unpaid button will add it as a pill and return search results for internships associated with that community.
- Selecting the VSFS button will add it as a pill and return search results for internships associated with that community.
- One can be selected

Mock:
https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

Related Ticket:

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35764&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@kbwagner I have placed this on hold because it contains conflicting AC. It states each program should be a checkbox, but everywhere else including the design mock up they are referred to as radio buttons. Can we get the AC to reflect radio buttons for the first bullet point?

**Comment by kbwagner** [comment]
AC has been updated to reflect radio buttons

**Comment by kbwagner** [comment]
@sabushanab I know this one is still being worked on but @abudz19 noticed that the radio button for unpaid is missing a period.  Should be U.S. Department of State...

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
1-30-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@bmcorum could you take the hold button off this one...thanks

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
2-8-19 LHammond in testing

**Comment by kbwagner** [comment]
2/13/19 - Tested in Test environment/Chrome
- Will create a new ticket to default the program based on where the student comes in from (can be done later)
- Ready for final review.
