### ISSUE TITLE
Student Search Filter: Skill

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2706]
User Story: As a student, I want to be able to search for internships based on skills associated to the internship opportunity.

Acceptance Criteria:
- The skill box will display default text of, "Start typing to select a skill"
- The skill search will work as it does in production for the Open Opps search.  Selected skills will show as a pill in the skill box and under the header.
- Pills in the skill box can be removed by selecting the X
- Pills listed as search filters at the top can be removed by selecting the X
- There will be a limit to 5 skills to use as filters (as in production)
- Search results will return internships that have listed the selected skill on the Create internship opportunity. 

Mock:
https://opm.invisionapp.com/d/main#/console/15360465/323156811/preview

Related Ticket:

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35766&fullScreen=false&_a=edit

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
1-23-19 LHammond in testing

**Comment by kbwagner** [comment]
1/24/19 - Kwagner tested in Chrome/Test environment
Ready for final review.
