### ISSUE TITLE
Student Search Filter: Language

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2707]
User Story: As a student intern, I want to be able to search for internships that might need a language I speak.

Acceptance Criteria:
- The Foreign language filter will have default text of "Start typing to select a language"
- Selections will display in the language box and as a pill at the top of the page
- Both the language box pill and filter pill at the top of the page can be removed by selecting the X
- There will be no limit on the number of languages that can be entered as filters
- Search results will display internships based on Create internships that have the same languages selected

Mock:
https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35767&fullScreen=false&_a=edit

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
1-24-19 LHammond in testing

**Comment by kbwagner** [comment]
1/24/19 - KWagner tested in Chrome in Test environment.
ready for final review.
