### ISSUE TITLE
Student Search: Agency Filter

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2708]
User Story: As an intern, I want to be able to select an agency to view opportunities related to a specific agency.  

Acceptance Criteria:
- Agency will be a dropdown that displays options from the agency table
- If the Unpaid internship checkbox is selected as a Program, the Agency should default to "Dept of State" and can't be changed (disable/gray out)
- If the VSFS radio button is selected as the Program, the Agency will not default and this filter will display
- The agency selected should display as a pill.  This pill can be removed by selecting the "X"
- Only one agency can be selected
- When the agency is selected as a pill, the search results will only return internships associated with that agency

Mock:
https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35768&fullScreen=false&_a=edit

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
1-30-19 LHammond in testing

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
2-8-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
2/12/19 - Kwagner tested in Chrome/Test environment
