### ISSUE TITLE
Student Search: Bureau filter

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2709]
User Story: As a student, I want to be able to search on bureaus in order to help me narrow my search based on who I want to work for.

Acceptance Criteria:
- Bureau will only display if the Agency selected is Department of State.  Otherwise, bureau will be disabled.  Bureau and Office/post will only display when the Program of Student Internship Program (unpaid) is selected.
- Bureau will be a dropdown based on the bureau table
- Default text of - Select a bureau- will display in the blank field
- Once the agency of DOS is selected, the bureaus related to that agency will be displayed. (currently only DOS)
- Only one bureau can be selected (Question - is it possible to allow more than one?  if so we should allow)
- Once the bureau is selected, it will become a pill.  The pill can be removed by clicking on the X
- The search results will return based on internships that have the selected bureau listed on the create internship opportunity
Mock:
https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35769&fullScreen=false&_a=edit

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
02/6/2019 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
02/6/2019 - Mdumas - Tested Bureau filter - moving on to review.

**Comment by kbwagner** [comment]
@sabushanab question on bureau showing up after I select agency.
- Unpaid is fine since agency is defaulted to DoS
- VSFS, I try to enter Department of State as the agency (Department of State - Agency Wide although there is also a Department of State hiring fair).  Neither of them gives me the bureau drop down.
Let me know if I'm missing a step.

**Comment by kbwagner** [comment]
Created a separate ticket for  VSFS

2/12/19 - KWagner tested in Chrome/Test.  Ready for final review.
