### ISSUE TITLE
Student Search Filters: Office/post

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2711]
User Story: As a student, I want to be able to search for internship opportunities for a specific office/post so that I can narrow my search based on location.

Acceptance Criteria:
- Office post will only display when Unpaid Internships are selected and/or Department of State is selected as the agency
- Default text of - Select an office/post- will appear in the blank filter field
- Office/post will be a dropdown based on the Office/post data table
- The office/post will be based on the Agency (only DOS) and Bureau selected
- Office/post will not become enabled until a bureau is selected

Question: 
- Can they select more than one office/post?  If so, we should allow it.  If not, that's ok

Mock:
https://opm.invisionapp.com/d/main#/console/15360465/323156811/preview

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35770&fullScreen=false&_a=edit

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by margaretdumas** [comment]
02/6/2019 - Mdumas - In testing....

**Comment by margaretdumas** [comment]
@sabushanab - Moving back to development for AC * Select an office/post. Currently reads "Select an office"

**Comment by sabushanab** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
2-8-29 LHammond in testing

**Comment by kbwagner** [comment]
2/12/19 - KWagner tested in Chrome/Test environment. Ready for final review.
