### ISSUE TITLE
Community: UI for adding cycle data on community dashboard

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2713]
User Story: As a community administrator, I want to be able to add cycle information to my community that will be used to control cycle display and apply dates.

Acceptance criteria:
- Update the user interface on the Community Admin page to allow for the administrator of the community to add cycle start and end dates and apply start and end dates.
On communities with a cyclical type
-	Add button to manage opportunities page to "Create new cycle"
-	Function to create new cycle
o	Name/description (ex. Fall 2019, Spring 2020, Summer 2020)
o	First day to create opportunities (ex. May 1, 2019)
o	Last day to create opportunities (ex. June 1, 2019)
o	Date to start accepting applications
o	Date to stop accepting applications
o	Start date of internship (ex. August 15, 2019)
o	End date of internship (ex. December 10, 2019)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
01/9/19 - Mdumas - in testing....

**Comment by margaretdumas** [comment]
1/9/19 - Mdumas - Moving on to review.  Meets requirements requested fields.  Field Names are not exact but the page did not have a mock .

**Comment by kbwagner** [comment]
@bmcorum @jhanson12 Question on this - how will this connect to what's on Create Opportunity which asks for year and season fall/spring/summer?  

@abudz19 this is one that we discussed yesterday that the Macon team would use the design system and build the page but tagging you for review.

**Comment by jhanson12** [comment]
The data entered is saved to the database.  In another ticket, we will pull the data and display in the UI.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
1/11/2019 - Mdumas - testing for functionality...

**Comment by margaretdumas** [comment]
01/14/2019 - Mdumas - moving to review

**Comment by kbwagner** [comment]
1/15/19 - KWagner tested in Test/Chrome.  
Ready for final review.
