### ISSUE TITLE
Display cycle dates on the Opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2716]
User Story: As a community internship creator, I want to be able to display the community cycle times I have set on the internship in order for the interns to see when the dates they will be working.

Acceptance Criteria: 
- Based on the cycle dates set on the community admin table and the cycle selected on create opportunity, display the cycle start and end date on the Opportunity:
- Will display on the preview of the create opportunity and the apply view of the opportunity in the blue side bar

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-18-19 LHammond in testing
cannot test as no student opportunities will open on the site (see error listing below).  Tried to open from both home page and search, moving back to development.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/8710e4f8-c353-4087-8cf8-29134e59b9c3)

**Comment by bmcorum** [comment]
@Kibrahacha67 I was unable to replicate the error locally or in the TEST environment. Can you please retest or provide additional details?

**Comment by Kibrahacha67** [comment]
1-23-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 attached is a visual of the cycle data currently in the TEST environment.

![image](https://user-images.githubusercontent.com/1165615/51762493-e1b1f000-209d-11e9-90b4-fdec78b8d3bd.png)

**Comment by kbwagner** [comment]
@jhanson12 Not sure the AC was clear enough on this one.
1) The blue side bar on the opportunity preview/apply/view should not show the cycle name but the cycle start and cycle end (when they will actually be working on the internship)
2) on the create opportunity, beside Fall 2019 it displays (2/28/2019 thru 3/30/2019).  Looking at the artifact, these aren't correct.  It should again display the cycle start and cycle end date which in this case would be 3/1/19 to 3/31/19

Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
2-6-19 LHammond in testing

**Comment by kbwagner** [comment]
@jhanson12 on the dates that display on create page - where are these coming from?  
![image](https://user-images.githubusercontent.com/18709918/52733333-78cce200-2f90-11e9-90c7-b69da1aa4753.png)
If I look at the artifact for cycle date for internship, 5/31 to 7/1 are not listed.

**Comment by Kibrahacha67** [comment]
@kbwagner - actually the only dates that matter in this test are the current cycle.  any other date will not make the system react.  So if you use say the "5/31/2000 07/01/2000 dates the system will not react.  If you use dates in 2020 the system will not react as they are in the future (negative test).  But if you us the current dates March 2018 - March 2020 the system will display the message.

**Comment by jhanson12** [comment]
They are the cycle dates for the internship – displayed is cycle_start_date thru cycle_end_date.  But when you create an internship, the cycle that is displayed is based on the posting start date – posting_start_date.

**Comment by kbwagner** [comment]
@jhanson12 so maybe the artifact I'm looking at is old. I don't have Saleim's cycle but for the Cycle test I see posting start date of 1/1/2000

**Comment by Kibrahacha67** [comment]
@kbwagner - Please think of today's date and try to input a cycle that uses that date and you will see the error message

**Comment by kbwagner** [comment]
@Kibrahacha67 I tested the error message ticket fine.  This is the display of the cycle dates and I'm not sure where the dates are coming from that display in parenthesis beside the cycle name in Create internship.  They don't match the artifact attached to this ticket.

**Comment by kbwagner** [comment]
@Kibrahacha67 @jhanson12  In this screen shot...where does the 5/31/2000 to 7/1/2000 come from?  Those dates don't match the artifact attached for cycle test.
![image 11](https://user-images.githubusercontent.com/18709918/52734459-4d97c200-2f93-11e9-8d16-2dfcd0e48c79.png)

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - we need an updated artifact as the one above does not show Saleim's cycle and most of the tickets in the environment have that date.  Katrina is trying to complete review on this one..

**Comment by Kibrahacha67** [comment]
@kbwagner - this is the one i used to confirm...it is the fall 2019 first line of the artifact

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/d31d5bfb-8ef5-4c23-8325-06aaa485d336)

**Comment by Kibrahacha67** [comment]
@kbwagner - the artifact that is attached is prior to elastic, the dates now are different so Brice will need to attach new table to get clear dates so you won't have questions, but for my test the cycle start and end dates were where this was pulled.  So I think that there was some calculation with the start date to make the internship start in 2/19 as the apply dates were actually from 2/1 to 2/28 and the cycle dates are 3/1 to 3/31...Salem changed the cycle dates and currently in the system his dates show.  So again will need a new artifact to actually see the dates that are in the system now.  Sorry this changed from the time I tested to the time you are testing...

**Comment by kbwagner** [comment]
2/18/19 - Placing on hold until an artifact can be attached so we can test.

**Comment by kbwagner** [comment]
3/25/19 - Kwagner tested in UAT.  Setup a new cycle and verified the month and year display correctly.
Ready for final review.
