### ISSUE TITLE
If no open cycle, display an error

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2717]
User Story: As a student internship creator, I should not be able to create an opportunity for a cycle time where no dates have been set.

Acceptance Criteria:
- if community is a student and someone tries to create an opportunity but no cycle date is set on the admin table, throw an error to indicate that a cycle for this time period has not been created and must be created by the community administrator prior to being able to create an opportunity.
- The error message should read, "There are no current cycle dates set.  Please contact your administrator to request the cycle times be added." (open for suggestion on text)

**Comment by Kibrahacha67** [comment]
@kbwagner - is this meant to be in the create opportunity (internship) flow? or is this still being flushed out.  writing the test cases for this and just need to confirm.  thank  you

**Comment by kbwagner** [comment]
@Kibrahacha67 yes, this is the create opportunity flow (or create internship opportunity technically)
Not still being flushed out just got added late.

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - is this a valid ticket?  currently we have start and end dates on creating an internship as radio buttons that have to be selected.  So there is no way to have a cycle date that is not fed by the table.  as such this message would never be seen from a creator.  they message they would get is "Please select internship start and end date" currently.  unless you meant this to be a trigger for the admins if no dates for a specific fy have not been set...

**Comment by kbwagner** [comment]
@Kibrahacha67 this shows when they click on Create Opportunity...so they will never get to see the radio buttons on the create page.

**Comment by bmcorum** [comment]
Artifacts for error message when there are no open cycles available based on posting date range.

![image](https://user-images.githubusercontent.com/1165615/51930609-f5749380-23c8-11e9-93fe-4c12d56c0248.png)

![image](https://user-images.githubusercontent.com/1165615/51930620-fb6a7480-23c8-11e9-9009-384ca4937dab.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 see attached artifacts above.

**Comment by Kibrahacha67** [comment]
1-29-19 LHammond Moving to review.

**Comment by kbwagner** [comment]
1/30/19 - KWagner reviewed artifact.
Ready for final review.
