### ISSUE TITLE
Bug: Draft submitted email has incorrect link

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2720]
After release 7.3, the link on the draft submitted was not updated to reflect the correct place to find drafts.

Steps to Reproduce:
1) Create Opportunity
2) Save as Draft, receive email
3) Email reads, "Your draft can be found in your profile under Drafts" with a link to the profile.

Update email content as follows:
Your draft can be found on your dashboard.  (dashboard is a link to the signed in landing page where created opportunities are displayed)

**Comment by jhanson12** [comment]
@kbwagner the sentence "Your draft can be found in on your dashboard.", I think we need to pick one and not both  "in on".  Your preference?

**Comment by kbwagner** [comment]
@jhanson12 good catch on a typo!  I'd go with "on"

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-07-19 LHammond in testing
