### ISSUE TITLE
Update DHS Joint Duty Program Office Community to be Closed

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2726]
The DHS Joint Duty program office community should be a closed community.  Update the community attribute table for DHS to show community is closed.

A closed community will not show up in the Select a target audience dropdown on Create Opportunity.

This needs to go out with the 7.4 release.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing in UAT. DHS should no longer be a selection for community unless you are a member of the DHS Joint Duty Program Office.

**Comment by Kibrahacha67** [comment]
12-11-18 LHammond in testing...
testing completed in uat...moving to review.

**Comment by kbwagner** [comment]
@bmcorum - in TEST I still see the Joint Duty program office in the dropdown when I go to Create an Opportunity.  I'm not a member of that community.  But I am an administrator (I haven't set up all of my non admin accounts with login.gov).  Do I see it because I'm an admin?

**Comment by kbwagner** [comment]
Brice confirmed it is only in UAT right now.
- Confirmed that if I am not a member of the closed community, that I don't see it in the dropdown.
- Ready for final review.
