### ISSUE TITLE
Change label "Invite user" to "Add user" for communities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2729]
Who: Community Admin
What: Invite members button
Why: to avoid confusion

Acceptance Criteria:
- On the Community admin dashboard --> Members, change the label on the button from "Invite members" to "Add members".  

Reason: In communication planning, it was realized that invite makes it seem like they need to do something to accept which is not the case.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-4-19 LHammond in testing

**Comment by kbwagner** [comment]
1/8/19 - KWagner  tested in Chrome and mobile safari
- ready for final review.

Will create a new ticket to also change the title of the page when you click on the button from invite to add
