### ISSUE TITLE
Add a period to the sign out screen

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2730]
To be consistent with other sign out pages, please add a period to the end of the sentences "You are now signed out." and "Thanks for using Open Opportunities."

To be consistent with USAJOBS, add a period behind each of the link options at the bottom as well:
Sign in again.
Search for opportunities.
Go to our help center.
Head back to home.

Bug Bash 12/4/18![Snag_59790d5.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/7151efb9-6793-4bc9-8f42-a019a110b224)

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-10-19 LHammond in testing.
Testing completed moving to review.

**Comment by kbwagner** [comment]
7/10/19 - KWagner reviewed in Test
Ready for final review
