### ISSUE TITLE
Admin: when changing a owner, modal does not close and page does not update...even though the change took place

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2739]
Steps to reproduce, In Test, follow these steps
--sign in as a Administrator
--click Administration link
--click agency
--select OPM as Agency to utilize
--click on Manage Opportunities
--click Open radio button 
--select a particular opportunity to change owner
--click the change owner icon on the right hand side of the screen
--search for new owner via drop down
--click the change owner

**Comment by Kibrahacha67** [comment]
6-28-19 LHammond in testing.

**Comment by kbwagner** [comment]
7/9/19 - KWagner tested in Test/Chrome
Ready for final review.
