### ISSUE TITLE
Location Autocomplete

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2747]
User Story: As a student, I want to be able to search for internships based on location to help me narrow my search results.

Acceptance Criteria:
- Implement location autocomplete
- Search can be based on city, state, or country.
- Data that is returned is based on city/state/country that have been entered in an Opportunity/internship
- Autocomplete should work similar to USAJOBS.  
- After the user types 2 letters,a list of matching values will display separated into city, state, and country.
- Once a location is selected, the user must select search for the location to become a filter and pill
- Once the first set of search results is selected, the user can add additional locations as pills by selecting from the autocomplete
- The search results displayed will be based on internship opportunties that have that city/state/country selected.

Mock: https://opm.invisionapp.com/share/UHNZS9XEYR8#/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
1-24-19 LHammond in testing

**Comment by kbwagner** [comment]
1/30/19 - KWagner tested in Chrome, Test environment as an Admin.  Location autocomplete works correctly.
