### ISSUE TITLE
State: Student Profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2749]
User Story: As a student, I need to have a profile that displays relevant information about me.

Acceptance Criteria: 
The student profile will display:
- No photo will display, just initials
- Name
- Location (from USAJOBS)
- email (from USAJOBS)
- Skills

- Students will not part of People Search for federal employees.

The Student profile will NOT show:
- Badges
- Job title
- User type
- Photo
- Agency
- Biography 

Student Data:
- Look for student hiring path from USAJOBS to determine whether the applicant is a student and then pull over appropriate information.

**Comment by kbwagner** [comment]
@bmcorum that is fine - I'll update.  Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Recommendation:** Create a new USAJOBS account and select student hiring path. Then log into OpenOpps with this new account.

**Comment by Kibrahacha67** [comment]
1-17-19 LHammond  in testing

**Comment by Kibrahacha67** [comment]
@kbwagner - question since there is a requirement in the AC that the student search is not part of the open opps people search, is that functionality part of another ticket? or is that expected to be accomplished as part of this ticket? or is that a note?  TY

**Comment by kbwagner** [comment]
@Kibrahacha67 good question. I don't have it as part of another ticket but probably should create one so we can test that they don't show up.

**Comment by kbwagner** [comment]
2867 was created to remove People from the subnav when logged in as a student

**Comment by kbwagner** [comment]
@abudz19 this is one we didn't have a design for but you can review for design standards.

**Comment by kbwagner** [comment]
1/30/19- KWagner tested in test environment and Chrome.
- Profile for my student account looks good
- my student account does not show up in People Search.
