### ISSUE TITLE
Page displays after adding an internship opportunity with only header, footer and return to top link

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2772]
When an opportunity is added and save, a page is displayed without content.  It only displays a "return to top" link, header and footer.

Steps to reproduce:
1.  Add a new internship opportunity
2.  Save it

Result: It appears to save but doesn't navigate to any particular page.

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/dee9dc57-521a-485e-95ce-6dfcbb5b29be)

**Comment by margaretdumas** [comment]
01/4/19 - Mdumas - Tested...Moving on to review

**Comment by kbwagner** [comment]
1/8/19 - Tested in Chrome.  I still get the page described for about 5 seconds but it then does to go a saved page.
- ready for final review.
