### ISSUE TITLE
Department of State - Next Steps Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2784]
Who: Student Applicant
What: Next Steps page with a list of things they will need to do to apply
Why: As a student applicant I would like to know what to expect before I start my application so I can be prepared.

A/C 
- This will be the first page presented to **eligible applicants** when they click "Apply"
- There will be a header "Next Steps" at the top with an explanation
- There will be a smaller header "Complete your profile" with an explanation
- There will be a numbered list 
  - Select internship opportunities - with explanation
  - Review your experience and references - with explanation
  - Review your education and transcript - with an explanation
  - Review your languages and skills - with explanation
  - Include a statement of interest - with explanation
- There will be a "Continue" button at the bottom of the page that will take the user to the "Select Internship Opportunities" Page

InVision Link: https://opm.invisionapp.com/d/main/#/console/15360465/319289299/preview

**Comment by Kibrahacha67** [comment]
2-8-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
2-21-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@Piglady64 - In the AC when it says "with explanation" does that mean that the written text should match the design or will you provide the wording?  I'm testing this and need to know which text is correct.  ty Larry

**Comment by Piglady64** [comment]
@Kibrahacha67 Use the text in the design.

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/53116507-d922cd00-3516-11e9-80f9-e944679f3c72.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

@Piglady64 was there a specific reason why the word save was capitalized at the end of a sentence. This might be a question for design or Debbie.

**Comment by dalenard21** [comment]
@bmcorum it's capitalized because it's the button label.  It should also be 'bold'.  When we give instructions for clicking on specific buttons and links, we bold the button/link label name.  Sorry I missed this in the invision mock up.

**Comment by bmcorum** [comment]
@dalenard21 thank you for the clarification. @Kibrahacha67 I will make the necessary updates please standby.

**Comment by margaretdumas** [comment]
02/25/19 - Mdumas - Moving back to development for the following reasons:

1.  Does not meet Requirement - **Select internship opportunities**(We are displaying as "Select Internships)
2.  Fails -  The "Continue" button at the bottom of the page will take the user to the "Select Internship Opportunities" page.  I get an importing data modal then An unexpected error occured modal with the word error spelled as **errror.** 
![image](https://user-images.githubusercontent.com/19936109/53343384-4d29f000-38de-11e9-89c8-a21fe864b56d.png)

**Comment by margaretdumas** [comment]
2/27/19 - Mdumas - moving back to development.  The "Continue" button still throws an error. "An unexpected error occured"

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/1/19 - Mdumas - Moving this one back to development for the following reason:  
1.  It still fails this step in the AC:  
AC:  
-  Continue" button at the bottom of the page that will take the user to the "Select Internship Opportunities" Page.  Note:  (This  fails because it takes me to a modal - "An unexpected error occured")

From the modal there is a button  "Continue with application".  Once I click this button, I am taken to the "Select internship opportunities" page. The AC does not have this condition or extra step.

**Comment by bmcorum** [comment]
@margaretdumas I understand, but there are instances where an error might occur due to background processes happening and I had to do something to handle the error gracefully and to notify the user that in the next several steps there might be missing or incomplete information during the USAJOBS profile import.

**Comment by margaretdumas** [comment]
@Piglady64 @bmcorum . Once I go past this page in the process and move on to step 1,  should I bypass this page the next time I sign in? Same question for other steps in the process.

**Comment by margaretdumas** [comment]
@bmcorum, @Piglady64  Moving this one back to development for several reasons.  

1.  I still get the error modal to display with the continue button.  Brice I spoke with Julie and she do not want this modal to display. 
2.  When I sign out of an incomplete application, I was able to get back to the next step page by clicking on step one in the process and clicking back.  I'm not sure if this is correct for the flow.  Question asked prior should answer this.

**Comment by bmcorum** [comment]
@margaretdumas fixed it!

**Comment by margaretdumas** [comment]
Mdumas - passed testing. moving on to review.

**Comment by Piglady64** [comment]
3/11/19 Passed Review moving to final approval
