### ISSUE TITLE
Department of State - Select internship opportunities from search results

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2785]
Who: Student Applicant
What: Select 3 internships
Why: The student is required to apply to 3 internships

A/C 
- Header - Select internship opportunities - with explanation
- 3 placeholders for internships
  - 1st choice
  - 2nd choice
  - 3rd choice
- When the placeholder is empty it will have a dashed box around it with "Search for 2nd choice or Search or 3rd choice" in the center of the box" 
- The "Search for ..." will be a link back to search so the student applicant can continue to search for their second and 3rd choice.
- When the user selects an internship opportunity it will fill the next available choice. 
- Once all three slots are filled the user will be able to reorder them by using an up and down arrow. 
  - Choice 1 will only have a down arrow so the user can move that selection down
  - Choice 2 will have an up and down arrow so the user can move the selection to choice 1 or choice 3
  - Choice 3 will only have an up arrow so the user can move that selection up
- Clicking the "Back" button will take them to the "Next steps" page and the circle around the 1 in the progress bar will be white.
- There will be a red X "Delete" button in the upper right corner of each card once it is in the list.
- The user can remove an internship opportunity from their choices by clicking the delete button.

InVision Mock:  https://opm.invisionapp.com/d/main/#/console/15360465/319289308/preview

Related ticket: 2862 - Select internship from saved search

**Comment by bmcorum** [comment]
Need to update AC around dragging and dropping.

**Comment by Piglady64** [comment]
@abudz19 this is the ticket that we discussed during sprint planning. The drag and drop functionality is not 508 compliant according to Brice. We will need a new design that is 508 compliant. An up and down arrow was discussed during the meeting.

**Comment by Kibrahacha67** [comment]
@Piglady64 - Hi Question on the header, is the explanation in the design correct? or will you be adding an explanation to the AC?  ty

**Comment by Piglady64** [comment]
@Kibrahacha67 
1) The explanation under "Select internship opportunities" in the mock is correct
2) When they hit "Apply" on an internship opportunity they come here to start their application
3) At the center of each choice there is a "Search for your 2nd choice" Search for your 3rd choice" link
![image](https://user-images.githubusercontent.com/15252970/51936121-79cd1380-23d5-11e9-872f-5aa7cd97e4d3.png)
4) The "back to results" link in the upper left hand side should take the user back to the search results. The user will have 2 ways to get back to search, the link in the center of the 2nd and 3rd choice boxes and the "back to results" link.
5) The first box will look like it does in the mock. When the user clicks apply on one of the internship opportunities that internship opportunity will automatically be placed in the first space. As discussed in Sprint Planning there will be a down arrow for the user to move that selection once all 3 slots are filled.

I hope I answered all of your questions, if not just let me know.

**Comment by Kibrahacha67** [comment]
@Piglady64

**Comment by Kibrahacha67** [comment]
2-8-19 LHammond in testing
-Delete link didn't work.  page didn't respond until I searched for my second choice
-added two of my three choices, but when I added my third choice, the first two choices were deleted and my third choice showed as my first choice.
-the select program choice was not highlighted during the process
-intermittently the next steps page showed.  it showed when I first clicked the apply button, then once when I selected an internship but other times it didn't.
moving back to development.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
2/27/19 - Mdumas - testing...

**Comment by margaretdumas** [comment]
2/27/19 - Mdumas
1.  Selections cannot be moved up and down in Edge
2.  I have two opportunities.  When I add the 3rd one, they are different than what I originally had displayed on page. Tried this in two different accounts.

**Comment by bmcorum** [comment]
@margaretdumas maybe it will work this time!

**Comment by margaretdumas** [comment]
Mdumas - The up and down arrows does not seem to work in any browser but Chrome. IE, Edge and Mobile does not work with arrows.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
03/8/2019 - Mdumas - In testing.....

**Comment by margaretdumas** [comment]
Mdumas - Still cannot move the opportunities up and down using the arrows in browser other than Chrome.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 maybe I got it right this time!

**Comment by margaretdumas** [comment]
Mdumas - Can move opportunities up and down in all browsers.  Passes AC. Moving on to review.

**Comment by Piglady64** [comment]
3/11/19  Moved to final approval
