### ISSUE TITLE
Department of State - Saved Internship Opportunities on "Select internship opportunities" page (Right Rail)

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2788]
Who: Student Applicant
What: List of saved internship opportunities
Why: As a student applicant I would like to see a list of internship opportunities that I have previously saved so I don't have to look for them again.

A/C
- In the right rail of the "Select internship opportunities" page there will be a box titled "Saved internship opportunities"
- A list of the internship opportunities the student saved will be displayed
- This will be a scrollable list to accommodate all of their saved searches 
- There will be a blue check mark and "Select" in the upper right corner of each internship opportunity card.
- When the user selects an internship opportunity from this list there will be a green check mark and - "Selected" to indicate that the user has selected the internship opportunity.

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/319289308/preview

Related ticket 2862

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-2-19 LHammond in testing.
Testing completed.  moving to review.
Even though there are saved searches for this cycle, no saved internships show on this user (images below).  moving back to review.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/07310aff-c371-4682-99a7-b5cdf5b8c9cd)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/e4f9f12d-5b6f-4f87-aacb-67c7d77c6266)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-3-19 LHammond in testing

**Comment by Piglady64** [comment]
4/8/19 Julie Reviewed - returning to development - Saved search is missing the check mark next to "Select"
![image](https://user-images.githubusercontent.com/15252970/55748154-eb47c480-5a0b-11e9-9e6b-a309bd23facc.png)

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

Right rail issue is fixed.  We were approved to leave the select as is with no check mark by Julie and Matt.

**Comment by Kibrahacha67** [comment]
4-15-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed, moving to final approval
