### ISSUE TITLE
Add member to community: Change page title from invite to add

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2791]
User Story:
Who: Community Admin
What: Page title change
Why: To be consistent and avoid confusion.

Acceptance Criteria:
- Administration --> Community --> Members --> Manage --> Add members
- Change the page title from Invite member to community to "Add member to community" to be consistent

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-19 LHammond in testing

**Comment by kbwagner** [comment]
5/23/19 - KWagner tested in Test/Chrome
Ready for final review,
