### ISSUE TITLE
Update Unpaid Internship community name

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2798]
User Story:
Who: Unpaid internship community
What: Rename community 
Why: They would like consistent branding

Acceptance Criteria: 
Update the community name from Student Internship (unpaid) to 
U.S. Department of State Student Internship Program (Unpaid)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-23-19 LHammond in testing

**Comment by kbwagner** [comment]
1/23/19 - KWagner tested in Chrome in Test environment
Ready for final review.

**Comment by kbwagner** [comment]
@tanichacko sorry I missed this but the community name should be U.S. (period after both)...it's missing the second period right now.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-31-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
2-7-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
2/7/19 - Reviewed in Chrome/Test and this has been updated
- Ready for final review
