### ISSUE TITLE
Bug: Paging issue in elastic search

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2813]
During a search, I can click on page 5, select a opportunity to view, click the back to search link and the page count will be 1, ... 4, 5, 51 (see image below).

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/f8219a1c-d230-49a7-9910-b63cf7323511)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-10-19 LHammond in testing.
testing completed moving to review.

**Comment by kbwagner** [comment]
1/10/19 - Katrina tested in Test environment, using /search, in Chrome.
Ready for final review.
