### ISSUE TITLE
Modify search link to implement elastic search

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2822]
User Story:
Who: All Open Opps users
What: Modify search default link
Why: In order to implement elastic search

Acceptance Criteria:
- Modify the default search URL from /task to /search in order have all users using elastic search
- This MUST be done with the Department of State release which should be release 7.6
- Update link in Test, UAT, and Production

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-16-19 LHammond in testing

**Comment by kbwagner** [comment]
1/16/19 - Tested in Test in Chrome and default search is now /search
Ready for final review.
