### ISSUE TITLE
Enhance Search for limit participation to agency or department

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2824]
Environments: All

Steps to recreate:
1) Create an opportunity
2) Select the detail option to limit participation to your agency
3) Use the search filter for Agency and check the box "Participation limited to <agency> employees"
- No search results will be found

Need two checkboxes on create opportunity and search filtering:
- Limit to [insert agency of creator]
- Limit to [insert department of creator]

Example 1:
Agency: Bureau of Engraving and Printing
Department: Department of Treasury - Agency Wide

Two limiting options

Limit participation to Bureau of Engraving and Printing
Limit participation to Department of Treasury - Agency Wide
Example 2
Agency: Naval Reserve Force
Department: U.S. Navy - Agency Wide
Department: Department of Defense - Agency Wide

Three limiting options
Limit participation to Naval Reserve Force
Limit participation to U.S. Navy - Agency Wide
Limit participation to Department of Defense - Agency Wide

On filtering we would filter exactly on the limitation. So if I apply the filter 'Limited to Naval Reserve Force' it would show those specifically limited to Naval Reserve Service. If an opportunity is limited to U.S. Navy - Agency Wide I would not see it if I selected either of the two other limiting options.

**Comment by jhanson12** [comment]
@kbwagner and @bmcorum was a decision made if it should be parent department only or parent and child?

**Comment by kbwagner** [comment]
I defer to @bmcorum on this one.

**Comment by bmcorum** [comment]
@kbwagner and @jhanson12 this is a bigger issue and not ready to be worked. Moving back to backlog.

**Comment by kbwagner** [comment]
Discussion 1/2020 - limit to Dept/Agency

**Comment by bmcorum** [comment]
@kbwagner I think we should include all options.

### Example 1:
**Agency:** Bureau of Engraving and Printing
**Department:** Department of Treasury - Agency Wide

Two limiting options

1. Limit participation to Bureau of Engraving and Printing
2. Limit participation to Department of Treasury - Agency Wide

### Example 2
**Agency:** Naval Reserve Force
**Department:** U.S. Navy - Agency Wide
**Department:** Department of Defense - Agency Wide

Three limiting options
Limit participation to Naval Reserve Force
Limit participation to U.S. Navy - Agency Wide
Limit participation to Department of Defense - Agency Wide

##
On filtering we would filter exactly on the limitation. So if I apply the filter 'Limited to Naval Reserve Force' it would show those specifically limited to Naval Reserve Service. If an opportunity is limited to U.S. Navy - Agency Wide I would not see it if I selected either of the two other limiting options.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - Testing completed.

**Comment by kbwagner** [comment]
2/20/20 - KWagner tested in Chrome/Test
Closing
