### ISSUE TITLE
Isolate opportunities to only display on the correct search page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2825]
User Story:
Who: All Open Opps users
What: Display only the opportunities that are related to me
Why: To prevent the wrong people from applying to an opportunity

Acceptance criteria:
Opportunities should display on the correct search pages.

- Federal: opportunities with a target audience of "federal" and no other community selected should display on the standard Open Opps search results page
- Unpaid Internship: If target audience is Studenct and community is "Unpaid internship", it should display on the DoS student search results page only.
- FAI: Opportunities with a target audience of federal and a community of "FAI" should display on the Acquisition search page AND the standard Open Opps search page
- DHS Joint Duty: For now, if the target audience is federal and community is DHS, display on the main Open Opps search page.  This may change as they move forward with their implementation.

**Comment by bmcorum** [comment]
This was handle during the implementation of Elasticsearch for OpenOpps.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-29-19 LHammond testing
Logged in as a admin on the opportunity search page, typed internship in the search keyword and got three internships (below)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/7c7de044-6520-4611-9ece-7f9cf2534c89)

moving back to development.

**Comment by sabushanab** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
2-8-19 LHammond in testing.

**Comment by kbwagner** [comment]
2/13/19 - Tested in Chrome/Test environment. 
ready for final review.
