### ISSUE TITLE
Bug: Create opportunity button doesn't work in elastic

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2829]
Environments:

Test
UAT
Steps to reproduce:

in regular search/task click on Create opportunity - it works. Click back button
Change URL to end in "/search" which is elastic
click on "Create opportunity". Nothing happens
sometimes when I go back to /task it doesn't work but seems to be working now

**Comment by kbwagner** [comment]
@kikaider05 making sure you saw this one from last week.  Haven't tested it yet this week.

**Comment by kikaider05** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
1-16-19 LHammond in testing.
