### ISSUE TITLE
BUG: Opportunity restrict to agency

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2830]
When editing an existing opportunity the restrict to agency employees checkbox does not display.

**Comment by margaretdumas** [comment]
1/10/19 - Mdumas - Passed testing. Moving on to review.

**Comment by kbwagner** [comment]
1/15/19 - KWagner confirmed in Test/Chrome that if I edit an existing opportunity the restrict to agency checkbox does display
- Ready for final review.
