### ISSUE TITLE
View/Edit/Delete ability for Admin Cycle time table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2835]
User Story:
Who: Community Administrators
What: Ability to view existing cycle dates and update
Why: In order to empower the user to be able make changes themselves

Acceptance Criteria: 
- Update the Community Admin --> Manage Opportunities --> Create Cycle to also allow the user to view, delete, or edit existing cycle times.
- Should not be able to delete a cycle that the date for accepting applicants start date has passed

1/10/19 - Per discussion during release planning Dev will do this without a design but will use the design system.

**Comment by kbwagner** [comment]
@bmcorum Alex had some thoughts as she was reviewing on label consistency that make sense; I was  curious as to why for each date range entered there are different labels - "date range to create" uses first day/last day; "date range for accepting applications" uses start date/stop date; "date range of internship" uses start date/end date.  Probably all of them could just be labeled start date/end date.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-1-19 LHammond in testing.
testing completed moving to review.

**Comment by kbwagner** [comment]
@abudz for your review when you return.

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test

Future enhancement - when I go edit a cycle, the page name still says 'Create new cycle' but would be better labeled "Edit Cycle"

Ready for final review.
