### ISSUE TITLE
Ability to remove a member from a community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2836]
Who: Community Admin
What: ability to remove members from a community
Why: to maintain the integrity of the community

Acceptance Criteria: 
- Allow community managers to remove/disable members from a community.  
- Users will be removed/disabled from the community but not as an Open opps users

Closed communities: 
- Members can be disabled from a closed communities
- For closed communities, disabled users in that closed community should no longer be able to post for that community

Open communities:
- Members can be removed from Open communities
- For open communities it will just remove them from the list, but they still have the ability to post because it is an open community. 

Analytics should track who disabled and when but this information does not need to be displayed.

**Comment by Kibrahacha67** [comment]
@bmcorum - we will need an artifact for the last requirement of the AC.  Since there is no way for me to test if analytics are being tracked other then seeing a print out of the table...

**Comment by bmcorum** [comment]
Audit log artifact

![image](https://user-images.githubusercontent.com/1165615/58285716-501c6b80-7d7b-11e9-9933-32493f83600b.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

@Kibrahacha67 I left you a note on your desk for further information.

**Comment by Kibrahacha67** [comment]
5-24-19 LHammond in testing

**Comment by kbwagner** [comment]
5/28/19 - KWagner tested Chrome/Test environment
Ready for final review
