### ISSUE TITLE
User Interface for community attribute table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2837]
Who: Community managers
What: Ability to update the community attribute table
Why: So they can maintain their information

Acceptance Criteria:
- Create a user interface for the community attribute table so community administrators can view/edit the information on their own to maintain current data.  

1) Manage link
This should be accessible via the community admin tab and only can be updated by a system or community administrator.  There will be a "Manage community" link beside the community name dropdown/display Public link: https://opm.invisionapp.com/share/U8R4CAV3HXF#/353420497_Open_Opps_-_Community_Attributes_-_Change_Copy

2) Manage page: 
- This UI will only allow editing of all text fields not anything that defines how the community functions or has business logic around it such as type and target audience or agency.  Target audience and agency should be display only which differs from the mock...follow AC.
- The display should include what fields are optional vs required
-Please use the design system and design system mock below for the page
- See mock for field display and order:
- Mock: https://opm.invisionapp.com/share/U8R4CAV3HXF#/353420496_Open_Opps_-_Community_Attributes_-_Change_Copy_2

- There will be a Cancel and Save button.
- Cancel will return the user to the community admin page and no changes will be saved.
- Save - see item 3

3) Confirmation of save: 
- When Save is selected, the user will be returned to the community dashboard page and will receive a confirmation message that reads, "Community updated." and "You have successfully updated your community."  https://opm.invisionapp.com/share/U8R4CAV3HXF#/353555176_Open_Opps_-_Community_Attributes_-_Change_Successful
Note: The mock has the message in a different location - follow AC.  The success message should appear under the Administration title and submenu.

Invision Mock: https://opm.invisionapp.com/d/main#/console/17049184/353420497/preview
Public: https://opm.invisionapp.com/share/U8R4CAV3HXF#/353420497_Open_Opps_-_Community_Attributes_-_Change_Copy

Related ticket:
- 3530 allows for the ability for a system administrator to add a new community
- Original ticket to create community table: https://github.com/openopps/openopps-platform/issues/2550

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. 3rd time is the charm!

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing

**Comment by kbwagner** [comment]
@abudz19 this is in TEst if you'd like to review.
