### ISSUE TITLE
Ability to change the community assigned to opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2838]
Who: Opportunity creators
What: Modify the community assigned to an opportunity
Why: In case there was a mistake

Acceptance Criteria:
- Provide the ability for administrators to view and modify the community that was assigned to an opportunity/internship

Outcome from spike 3529:
- Only allow for changing communities within the same target audience. If wrong target audience was selected the entry will need to be deleted/closed and recreated using the correct target audience.
- Update target audience page to only allow selection of federal employees or students. Remove community selection from this page.
- On the opportunity form add a new section for community selection under the Who. 
-  On the internship opportunity - this field will not be necessary for a student as there is only one.show the student target audience button if you belong to DoS. No selection for community there would only be one. If no cycle show error, if cycle show internship form.
- Optional selection for federal target audience

Mock for Student Internship Create Page: https://opm.invisionapp.com/d/main#/console/15360465/319309731/preview
- The federal Open Opps create should place the drop down as the first selection below who as well. 

Related Ticket:
3529- Spike to research for this ticket

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-24-19 LHammond in testing.  
Testing completed, moving to review.

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Test/Chrome
Ready for final review

Need to discuss with the team whether if it's a new community if the status needs to be "submitted" and have to be approved again.  Would be a new ticket.
