### ISSUE TITLE
Do not require state when a country has none.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2849]
Steps to recreate:
1) Create an opportunity
2) Select a student target audience
3) Enter country of "France"
4) System requires both a city and a state

- If Country is not US, still require City, but do not require State if there are none in the database for that country

**Comment by jhanson12** [comment]
So I just tested this in production USAJOBS by editing my Profile.  Both the City and State are still required when selecting France.  However, when I selected French Quiana, only the City is required and the State is not.    The State is not required when there are no States available for that country.

I think the AC needs to be updated to still require City, but to not require State if there are none in the database for that country.  @kbwagner and @bmcorum

**Comment by kbwagner** [comment]
@jhanson12 updated - I'm fine with that.  I just don't want to be forced to enter something when I don't have something to enter.  

Will the location on the internship display automatically work?  Or do I need do a ticket to suppress if blank?

**Comment by jhanson12** [comment]
@kbwagner note it in this AC to test would work great.

**Comment by kbwagner** [comment]
@jhanson12 I updated the AC for this

**Comment by jhanson12** [comment]
@kbwagner and @bmcorum  we have one more issue to address.  We get the data for the locations from USAJOBS.  Currently, several of the countries have city names listed as states...like France.   To adjust for this, USAJOBS only requires City for United States.  Do you want Open Opps to do the same?

**Comment by kbwagner** [comment]
@jhanson12 Ack...I think that's how I had originally written it.  I think it makes sense to do it how USAJOBS does it although when I tested it in USAJOBS it required both city and state when I chose France.  I defer to you and @bmcorum I just don't want to be required to enter France, Paris, Paris.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
2-6-19 LHammond in testing

**Comment by kbwagner** [comment]
@jhanson12 @bmcorum I know we have talked about this a few times...but if I enter France, I enter a state of Paris and I'm still required to enter a city.
If I enter country of Germany and State of Berlin, I'm still required to enter a city.

Is this correct?   I know Brice mentioned once they could enter a province.  I'm just concerned we are requiring a city and a state when there may not be one.

**Comment by kbwagner** [comment]
Works the same as USAJOBS does so moving forward.  Hopefully USAJOBS and Open Opps can both address this in the future.

Ready for final review.
