### ISSUE TITLE
Bug: User should not have to log in to view an opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2850]
Environment: Test, UAT, and Prod

Steps to reproduce:
1) Click search, view opportunity search results
2) Click on card title to view opportunity
- All environments are taking the user to the login page before viewing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-17-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-18-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
found that the internship tickets on the opportunities search page are stalling, and they are not showing on the internship page.  when internships are selected from the internship page, they open with no issue.  issue is on safari, edge, ie, and chrome.  seems like there is an issue with internships showing on the opportunities page and not being able to open.  also the url is showing internship when the opportunity is selected on the Opportunity search page.  moving back to development

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-23-19 LHammond in testing

**Comment by kbwagner** [comment]
3/4/19 - KWagner tested in UAT/Chrome and worked
- Also tested in UAT/mobile/Safari
