### ISSUE TITLE
Sitewide: Help links don't open in new window

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2853]
As per the design system, all help links should open help in a new window.  Testing ticket 2822 showed that none of the links are opening in new window.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by kbwagner** [comment]
sorry this ticket really should have had a list of places before it went through.  

@tanichacko I noticed the help center link in the footer open in the same window.  Is that something we can add here to open in a new window?
![image](https://user-images.githubusercontent.com/18709918/60108457-a132cd00-9736-11e9-9caf-af98a92de613.png)

Looks good everywhere else.

**Comment by tanichacko** [comment]
@kbwagner I can make that change and I will check in shortly

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-26-19 LHammond in testing

**Comment by kbwagner** [comment]
6/26/19 - KWagner tested in IE/Test
Ready for final review.
