### ISSUE TITLE
Bug: Leading spaces in a skill causes elastic skills filter to not work

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2855]
Environment: Test

Steps to reproduce:
1) Search in Open Opps /search (elastic)
2) Select the skill " Open Data" with a leading space.  Nothing is returned but there is "Open Data" without a space.
- search ignores the space and searches on the word on its own
- correct all of the data to remove the erroneous spaces

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. We have run a data migration to remove leading and trailing spaces which was causing some skills filters to not work properly.

**Comment by Kibrahacha67** [comment]
1-06-19 LHammond in testing

**Comment by kbwagner** [comment]
1/17/19 - KWagner tested in Chrome/test environment.
Ready for final review.
