### ISSUE TITLE
Home: Search opportunities by links

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#2865]
All of the search links in this section of the home page need to be connected to the new elastic "Search"  they are still connected to the "task" search

**Comment by Kibrahacha67** [comment]
@bmcorum - fyi

**Comment by kbwagner** [comment]
Good catch.  We should probably check all of the emails and help center content as well.  I'll add it to my list

**Comment by Kibrahacha67** [comment]
@kbwagner  : )

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by kbwagner** [comment]
6/24/19  - KWagner tested IE/Test environment
Ready for final review.
