### ISSUE TITLE
Students should not have access to People search

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2867]
Who: Students
What: Remove ability to view People search
Why: At this time, students will not be part of a People search

Acceptance Criteria: 
- Remove "People" from the subnav on the search page when logged in as a student

**Comment by bmcorum** [comment]
This was completed as part of the process of integrating student profile between USAJOBS and OpenOpps.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-25-19 LHammond in testing
testing completed, moving to review.

**Comment by kbwagner** [comment]
1/30/19 - KWagner created a student account in USAJOBS.  
Tested in Test and Chrome.
People search does not display.
Ready for final review.
