### ISSUE TITLE
Add link to not selected email

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2869]
Who: Not selected users in Open Opps
What: link to search update
Why: So they can look for other opportunities

Acceptance Criteria:
- The email that is sent when a user is not selected should include a link to Open Opps search and that was missed.
- The link should be to /search to accommodate the new elastic search.
- Slight text updates are also included below

Subject: An update on <Opportunity Name>
Trigger: Once “Next steps” is selected, anyone who is not assigned will receive the email.
Audience: Applicants who are not assigned
Content: 
Hi,

Thanks again for your interest in [opportunity name link]. Unfortunately, you were not selected for this opportunity.

We frequently update the site, so keep checking for [other available opportunities](link to the open opps search page).

Thanks,
The Open Opportunities Team

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-30-19 LHammond in testing

**Comment by kbwagner** [comment]
7/30/19 - KWagner tested in Chrome/Test
Ready for final review.
