### ISSUE TITLE
Department of State: Ineligible GPA

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2874]
Who: Student
What: Notification of ineligibility due to GPA
Why: The student must have a GPA of 3.0 or higher to be eligible for the program

A/C
- There will be a header "You are ineligible"
- There will be an alert style box with the following content:
   - Your GPA is below 3.0 (Bold)
   - You're not eligible for this internship because your GPA doesn't meet the minimum requirement.   
      You must have a GPA of at least 3.0 or higher to be eligible for the U.S. Department of State 
       Internship Program (Unpaid)
- If a student does not have a 3.0 or higher GPA they will not be allowed to proceed with their application.
- Learn more about virtual internships will be a link that opens in a new window and takes the user to: https://vsfs.state.gov/
- Learn more about other student programs will be a link that opens in a new window and takes the user to: https://careers.state.gov/intern/other-programs/
- Learn more about the Pathways Program will be a link that opens in a new window and takes the user to: https://careers.state.gov/intern/pathways/

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/333437563/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
03/6/09 - Mdumas - In testing...

**Comment by margaretdumas** [comment]
Mdumas - Moving back to development for several reasons marked in the screen capture.

1.  Atleast - needs spacing
2.  Clearence - Spelling should be "clearance"
3.  Service - mock shows in lower case
4.  U.S.Department- needs spacing in two locations

![image](https://user-images.githubusercontent.com/19936109/53889042-b7841400-3ff3-11e9-80b5-6b7b59abf4a0.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - passed testing. Moving to review..

**Comment by Piglady64** [comment]
3/11/19 Moved to final approval

**Comment by abudz19** [comment]
@kbwagner color, spacing, and capitalization as noted below
<img width="938" alt="Open_Opportunities" src="https://user-images.githubusercontent.com/11526811/54391822-6bcd0c80-467c-11e9-91b7-58c671a630d7.png">
