### ISSUE TITLE
Department of State: Ineligible Citizenship

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2877]
Who: Student
What: Message of ineligibility due to Citizenship
Why: U.S. Citizenship is a requirement to apply to DoS Internship Program

A/C
- There will be a header: You are ineligible (Bold)
- There will be a warning message 
  - This message will be presented to the user when they click "apply" on any opportunity if they have indicated in their USAJOBS profile that they are not a U.S. citizen
   -You are not a U.S. citizen (Bold)
   - You're not eligible for this internship because you're profile says you're not a U.S. citizen. You must 
      be a U.S. citizen to be eligible for the U.S. Department of State Internship Program (Unpaid). Think 
      this is wrong? Edit Profile (this is a link to the users USAJOBS profile and will open in a new window)
- There will be content below alert box explaining the program.  
- The U.S. Department of State Student Internship Program (Unpaid) link will open in a new window and will take the user to the following website: https://careers.state.gov/intern/student-internships/
- Learn more about the U.S. Department of State exchange programs link will open in a new window and will take the user to the following website: https://exchanges.state.gov/

- If the student is not a U.S. Citizen they will not be allowed to proceed with their application

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/333432320/preview
  
Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by raywilliams** [comment]
@Piglady64  For the second warning message, will you please change "You're not eligible for this internship because *you're* profile says you're not a U.S. citizen." to "You're not eligible for this internship because *your* profile says you're not a U.S. citizen."?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
2-7-19 LHammond in testing

**Comment by raywilliams** [comment]
@Piglady64 Do you want the C in citizen from "You are not a U.S. Citizen (Bold)" uppercase or lowercase? It's a quick change so will you let me know which way you'd like it? Thanks!

**Comment by kbwagner** [comment]
@raywilliams C should be lower case...AC updated

**Comment by Piglady64** [comment]
@raywilliams Thank you for updating the A/C on this. Good Catch

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
03/6/19 - Mdumas - In testing...

**Comment by margaretdumas** [comment]
Mdumas - page content does not match AC starting with the first sentence below which should be below the message box. Moving back to development:

There will be content below alert box explaining the program.

The U.S. Department of State Student Internship Program (Unpaid) link will open in a new window and will take the user to the following website: https://careers.state.gov/intern/student-internships/

Learn more about the U.S. Department of State exchange programs link will open in a new window and will take the user to the following website: https://exchanges.state.gov/

If the student is not a U.S. Citizen they will not be allowed to proceed with their application

![image](https://user-images.githubusercontent.com/19936109/53884533-c665c900-3fe9-11e9-97e5-289ab9158757.png)

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - testing. ...
The 3 links are not working in the ticket. Moving back to development.

- Edit your profile
- U.S. Department of State Student Internship...
- Learn more about the U.S...

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - passed testing...Moving on to review.

**Comment by Piglady64** [comment]
3/11/19 moved to final approval

**Comment by abudz19** [comment]
<img width="1403" alt="Open_Opportunities" src="https://user-images.githubusercontent.com/11526811/54388904-3b35a480-4675-11e9-9f74-0a5eaa402e9d.png">
The margin on the bottom of this alert should be 30px
