### ISSUE TITLE
Department of State: Experience

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2878]
Who: Student Applicant
What: Experience and references page
Why: As a student applicant I want to provide my experience in my application

A/C
- The information will be populated from the users USAJOBS profile
- "All fields are required unless otherwise noted" (right margin)
- There will be a header: Experience & References (Bold)
- Header: Experience
- There will be a card for each experience entry with the following information:
   - There will be a + that will open the card to expose the information
   - Experience Title
   - The agency or company name (Bold)
   - The date range of the experience
- The "+Add experience" link will take the user to a blank Experience & Reference page
  - https://opm.invisionapp.com/d/main/#/console/15360465/319289332/preview
- When the user clicks the "save experience" button the user will return to the "Education & References" page and the new experience will be listed
- When the user clicks the "cancel and return" button the user will return to the "Education & References" page and any information they entered will be discarded
- Adding work experience in Open Opportunities during the application process will not update the user's USAJOBS profile with that work experience.

Invision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/319289315/preview

Public Link : https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Piglady64** [comment]
@bmcorum Here is the updated Experience ticket we discussed in sprint planning.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - moving this one back to development.  The text field for adding "duties, accomplishment and related skills" are missing the link below the text field.  Not listed in the AC but is in the mock? 

See below what is missing.
![image](https://user-images.githubusercontent.com/19936109/53911206-c84c7e00-4023-11e9-827b-0c683f143d64.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
03/8/19 - Mdumas - Please remove the "." and also check that the link is going to the correct place when clicked.  It is currently going to a unrelated place in the help center.

![image](https://user-images.githubusercontent.com/19936109/54039150-32823180-4190-11e9-8113-4cb4cffc6857.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-13-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-14-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-18-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in testing
