### ISSUE TITLE
Department of State: Education & Transcript

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2879]
Who: Student Applicant
What: Education and Transcript Information
Why: The student is required to provide education and transcript information

A/C
- There will be a header "Education & Transcripts" (Bold)
- "All fields are required" (In the right margin)
- There will be a header "Education" 
   - Under the header will be a statement- "Please tell us about your current academic standing and list any other education that you have completed to date."
- There will be 3 questions with Yes and No radio buttons
- All Questions will be blank (no default) 
   - Are you currently enrolled (part-time or full-time) or accepted for enrollment in an accredited college or university?
   - Will you be, at a minimum, a college or university junior (i.e. have completed 60 or more undergraduate semester credit hours or 90 or more undergraduate quarter credit hours) by the start of the intern session for which you are applying?
   - Will you continue your education after this internship has been completed?
- There will be a 4th question with a text box
   - What is your cumulative GPA on a 4.0 scale?
   - This box will only allow numbers up to a 4.0
   - If the user enters 0 to 2.99 they will be eliminated from the process and receive the ineligible due to GPA message #2874 
- There will be a card for each degree with the following information
   - A +sign that will expand the card to expose more information
   - The type of degree (Master's Degree, Bachelor's Degree) which will be a link to the user's USAJOBS profile 
   - The name of the college (Bold)
   - The date of the degree
- The "+ Add education" link will take the user to a blank "Education and Transctipt" page where the user can enter education information. 
    - https://opm.invisionapp.com/d/main/#/console/15360465/319289342/preview
    - "All fields are required unless otherwise noted" in the right margin
    - There will be a warning box in the right rail:
     - You must only list degrees from accredited schools or other education programs
     - Look up your school (this is a link) at the U.S. Department of Education. This link will open in a new window and link to: 
Note: Any new education added during the application process for Open Opps will only be stored on Open Opps and will not be udpated in the USAJOBS profile.

Invision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/319289334/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment]
@Piglady64 in the mock for this ticket under education there is a sentence that starts with "Please tell us about your..." will that be part of the page?  it is not in the AC.

**Comment by Piglady64** [comment]
@Kibrahacha67 I added the statement under the "Education" header to the A/C. That should be on the page as an explanation to the user.

**Comment by Kibrahacha67** [comment]
@Piglady64 thanks Julie...

**Comment by tanichacko** [comment]
@Piglady64 The mock says setting "YES" as default in all 3 question..but the acceptance criteria not mentioning default value..So do we need to set default as YES or let the user choose it? or in the database our default value is false  ..Can we set as default value as No?

**Comment by Piglady64** [comment]
@tanichacko I changed the A/C above to reflect that the questions should be blank and the user will have to choose the answer.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for tesing.

**NOTE:** this is for education only. Transcripts is handled by another ticket.

**Comment by margaretdumas** [comment]
3/1/19 - Mdumas - In testing...  Putting ticket on HOLD until I can get to this page.

**Comment by Piglady64** [comment]
Removed " Information will be pulled from the users USAJOBS profile" untestable due to data

**Comment by margaretdumas** [comment]
Mdumas - Removing the hold label and testing... The page can be accessed via a URL.  openopps.test.usajobs.gov/apply/x?step=x (whereas the 1st "x" is your application number and the 2nd "x" is the step number being reviewed.  In this case will be 3)


1.  I could not verify the link back to USAJOBS- 
* The type of degree (Master's Degree, Bachelor's Degree) which will be a link to the user's USAJOBS profile
2.  @Piglady64 - When the Degree completion date is added, it does display an per ticket.  This is not a required field so it may not be available. (We are good here)
3. GPA - field allows for any number below 4.0 (The validation will be done as part of 2874)

Moving on to review.

**Comment by Piglady64** [comment]
3/11/19 Moved to Final Approval
