### ISSUE TITLE
Department of State: Languages 

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2880]
Who: Student Applicant
What: Language and Skills Page
Why: As a student I would like to add my language and skills to my application

A/C
- There will be a header: "Languages & Skills" (Bold)
- "All fields are optional" (In the right margin)
- This information will be populated from the user's USAJOBS profile
- There will be a card for each language that will include the following:
   - A + sign that will expand the card
   - The Language 
- The + Add language link will take the user to a blank language page 
    - https://opm.invisionapp.com/d/main/#/console/15360465/319289346/preview
    - there will be a header "Language" with a drop down list of languages
      - There will be a header "Speaking language skill level" with 4 radio buttons
        - None
        - Novice
        - Intermediate
        - Advanced
     - There will be a header "Writing language skill level" with 4 radio buttons
        - None
        - Novice
        - Intermediate
        - Advanced
     - There will be a header "Reading language skill level with 4 radio buttons
         - None
        - Novice
        - Intermediate
        - Advanced
- There will be a link "What does novice, intermediate and advanced mean?" that will take the user to the Help Center in a new window to the following link: <need link>
- When the user clicks the "Cancel and return" button they will return to the "Language & Skills" page and the new information will be discarded
- When the user clicks the "Save language" button the will return to the "Language & Skills" page with the new information listed.

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/319289343/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment]
@Piglady64 @bmcorum Question for this ticket, Everything here for the add language page is the same as the original ticket that we did to add languages.  Will we be utilizing that page? if so is there a need to redo the testing other then regression?

**Comment by Piglady64** [comment]
@bmcorum Is Language one of the things that is only on Open Opps? Did the student have to add their language on Open Opps already so this page already exists?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
@Piglady64 @jhanson12 . The languages are not being populated from the USAJOB profile.  Do we want to remove this AC or was there a different decision on this function?

**Comment by kbwagner** [comment]
@margaretdumas - any idea why we aren't pulling languages from the profile @bmcorum?  If they are populated in the USAJOBS profile, we should pull them over to the application.  
- If we can pull them over but they aren't, then we may need a ticket to pull languages and a second ticket to populate the application @Piglady64 
- If we can't pull them over for some reason, then yes Julie the AC should be updated here.

**Comment by Kibrahacha67** [comment]
3-8-19 LHammond in testing

**Comment by Piglady64** [comment]
3/11/19 Moved to final approval
