### ISSUE TITLE
Department of State: Statement of Interest

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2881]
Who: Student Applicant
What: Statement of Interest Page
Why: Each student is required to provide a statement of information in their application

A/C
- There will be a header "Statement of interest" with description 
- There will be a text box "Paste or type your statement here"
   - The user has the ability to type their statement of interest in the box
   - The user has the ability to paste their statement from another document
   - There will be a 2500 character limit in the text box
- There will be "Help" content on the right rail
-  The "Back" button will take the user to the "Language & Skills" page
- The "Save and continue" button will save the information and  take the user to a "Review Application" page

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/319289352/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment]
@Piglady64 - Question for the AC, on the "Save and continue" button, will the application save the inputted data then move to the review page?  or once the review process is complete will the inputted data be saved on that page?  Also is the Help block on the page correct on the mock?  I need to include it in the test case if it is?  Thank you...

**Comment by Piglady64** [comment]
@Kibrahacha67 Once the user clicks the "Save and Continue" button the information will be saved and the user will go to the "Review" page.

The help content is correct in the mock.

**Comment by Kibrahacha67** [comment]
@Piglady64 thank you, can you update the AC to say save and send to the review page.  We have pages that do not save until the review is complete so I just want to make sure there is no confusion.  Ill update the test cases...

**Comment by Piglady64** [comment]
@Kibrahacha67 Done

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-7-19 LHammond in testing

**Comment by Piglady64** [comment]
Moved to Final Approval
