### ISSUE TITLE
Department of State: Review Application

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2882]
Who: Student Applicant
What: A Review Application page
Why: As a student I would like to see what I am submitting before it is sent to DoS

A/C
- There will be a header "Review Application" (Bold)
- The following sections will be presented
   - "Applying to these internship opportunities" 
   - There will be a card for each choice (1st choice, 2nd choice, 3rd choice) with the following information
      - The title of the internship
      - The Bureau/Office
   - "Experience"
   - "References"
   - "Education & Transcripts"
   - "Languages" 
   - "Skills"
   - Statement of Interest"
   - There will be a "Consent to share information" box 
      - There will be a Yes No radio button 
- The "Submit application" button will be disabled until the user answers the "consent to share information" question
- The user will be able to edit  each section on this page by clicking the "edit" button in the section they want to edit. (this will be done in the same window and will only update information in Open Opps)
-  When the user clicks the "Submit application" button they will be presented the "submission confirmation" modal #2927 

https://opm.invisionapp.com/d/main/#/console/15360465/319289355/preview

 
Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by margaretdumas** [comment]
@Piglady64 This page has a "submit application button".  Is this feature also a part of this ticket? If so, what happens when it is selected?  
Also, each section has an "edit" link.  Will these open in different tabs when selected?

Thanks

**Comment by Piglady64** [comment]
@margaretdumas I have updated the A/C to read "when the user clicks the "submit application" button the user will be presented with a modal and referenced the ticket for that modal.

Let me check with Katrina and see if when they edit it will open in a new tab.

**Comment by margaretdumas** [comment]
@Piglady64  One more question.  Will the submit button display with  focus or be grayed out until one of the radio buttons are selected?

**Comment by Piglady64** [comment]
@margaretdumas I updated the A/C with : The "Submit application" button will be disabled until the user answers the "consent to share information" question .

This is a question that the DoS required so I don't think we should allow submission without an answer

**Comment by Piglady64** [comment]
@margaretdumas  I have been having a discussion with Brice and if they are going to "edit" their application they will be doing that in Open Opps so it will NOT be in a new window.

**Comment by raywilliams** [comment]
@Piglady64 How many lines should show in the Statement of Interest area before the "Read more" link is clicked? I currently have five lines showing.

**Comment by Piglady64** [comment]
@raywilliams I am sorry, i am just getting to my emails and saw this. Use the same standards we use on USAJOBS for the number of lines that are displayed before the "read more" link is clicked.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in testing

**Comment by Piglady64** [comment]
Returning this to development:
1) I copied and pasted some help content into the box to validate the "read more" functionality 
2) then I held down the k and it stayed within the box on the actual page but looked like this on the "review " page 
![image](https://user-images.githubusercontent.com/15252970/54718425-dd033880-4b30-11e9-8d88-e527ccaeca07.png)
![image](https://user-images.githubusercontent.com/15252970/54718449-ec828180-4b30-11e9-9158-a42b1a6aa84d.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-21-19 LHammond in testing

**Comment by Piglady64** [comment]
Returning to development:
Security clearance type not displaying on review page
![image](https://user-images.githubusercontent.com/15252970/54776831-4ba2cd80-4be7-11e9-9a14-1360ffc5cd8a.png)

From Application

**Comment by Piglady64** [comment]
From Application:
Information ins in the application but not appearing on review page:
![image](https://user-images.githubusercontent.com/15252970/54777072-dedc0300-4be7-11e9-9de5-2c339682a767.png)

**Comment by Piglady64** [comment]
Content from text boxes under "other" are not displayed on the review page.
![image](https://user-images.githubusercontent.com/15252970/54777622-126b5d00-4be9-11e9-8a89-e2f63beff44a.png)

**Comment by Piglady64** [comment]
On Application:
![image](https://user-images.githubusercontent.com/15252970/54777704-4ba3cd00-4be9-11e9-9821-47b69f7c8a33.png)

**Comment by bmcorum** [comment]
@Piglady64 we will fix the type of security clearance. As for the Other text section and Length text section there was no acceptance criteria or anything on the mock up to cover this requirement. I am more than willing for us to add it but this is a missed requirement and needs to be a new ticket. It adds additional un-tracked complexity and requires our QA's to write additional test cases.

**Comment by bmcorum** [comment]
@Piglady64 if we can get a new ticket to cover new acceptance criteria for displaying the information provided in the Other section and the Length section, and get it approved we will move it into the current sprint.

**Comment by Piglady64** [comment]
Will Do

Julie Jackson
Usability Test Lead
USAJOBS

P: 202-606-5230 | M: 202-718-7608
Julie.Jackson@opm.gov<mailto:Julie.Jackson@opm.gov> | www.opm.gov/HRS<http://www.opm.gov/HRS>
[USAJOBS]<https://www.usajobs.gov/>
[usajobs-facebook-s]<https://www.facebook.com/USAJOBS>[usajobs-twitter-s]<https://twitter.com/usajobs> [usajobs-linkedin-s] <https://www.linkedin.com/company/usajobs>  [usajobs-youtube-s] <https://www.youtube.com/c/usajobs>

**Comment by Piglady64** [comment]
No problem. I will get it to you in a second. One question, we have a ticket to move the “length” box to be visible at all times not just when I click the “other” button. Do you want me to just include the Other text box in the new ticket?


Julie Jackson
Usability Test Lead
USAJOBS

P: 202-606-5230 | M: 202-718-7608
Julie.Jackson@opm.gov<mailto:Julie.Jackson@opm.gov> | www.opm.gov/HRS<http://www.opm.gov/HRS>
[USAJOBS]<https://www.usajobs.gov/>
[usajobs-facebook-s]<https://www.facebook.com/USAJOBS>[usajobs-twitter-s]<https://twitter.com/usajobs> [usajobs-linkedin-s] <https://www.linkedin.com/company/usajobs>  [usajobs-youtube-s] <https://www.youtube.com/c/usajobs>

**Comment by Kibrahacha67** [comment]
3-26-19 LHammond testing

**Comment by Piglady64** [comment]
3-18-19 Julie reviewed and the issue with the statement of interest box has been fixed along with the security clearance and overseas experience information being displayed. Moving to final approval
