### ISSUE TITLE
Search: Blue application deadline box for unpaid.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2897]
Who: Unpaid internship applicants
What: Display instruction box
Why: To provide application deadline information

Acceptance Criteria:
If the Program Filter is unpaid internship, then the following information should display in a blue instruction box under the pills, "U.S. Department of State Student Internship Program (unpaid) is now accepting applications for <insert cycle name>.  Application deadline: Month dd, yyyy."
- Cycle name will be the name of the cycle for unpaid that is currently posted
- Application deadline will be the application end date from the current cycle.

Invision mock: https://opm.invisionapp.com/share/UHNZS9XEYR8#/screens/323156811_Search_-_Students_-_Dept_Of_State_-Desktop-

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-25-19 LHammond in testing

**Comment by kbwagner** [comment]
@tanichacko can you please add a comma between the day and year per the AC and mock.   Thanks!

**Comment by kbwagner** [comment]
@abudz19 if you want to review.

**Comment by abudz19** [comment]
There is a missing period on U.S. Department of State Student Internship Program (Unpaid) radio button, on the filter pill when it appears, and in the cycle notification alert.

There is a missing space between the numbers in  February 28,2019.

**Comment by kbwagner** [comment]
@tanichacko 
Per Alex's note above:
1) Please add a period after the S in U.S. at the beginning of the sentence.  
2) Please add a space after the comma in the date so in this case it would be February 28, 2019
3) Can you provide me with an artifact that shows the cycle times for unpaid internships so I can make sure the right one is showing up?

Thanks!

**Comment by kbwagner** [comment]
Found an artifact on another ticket for cycle dates.  The Fall 2019 cycle date and application deadline of 2/28/19 are correct.  Attaching artifact.
![51762493-e1b1f000-209d-11e9-90b4-fdec78b8d3bd](https://user-images.githubusercontent.com/18709918/52005033-adbc3d80-2496-11e9-9983-d482cfa5ad4e.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
2-4-19 LHammond in testing.

**Comment by kbwagner** [comment]
2/5/19 - KWagner Tested in Chrome/Test environment
- ready for final review.
