### ISSUE TITLE
Student Landing Page: View applications

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2899]
User Story: As a student, I want to have a dashboard/landing page that allows me to see information related to my applications.

Acceptance Criteria:
For the student landing page, once we can apply to student internships in order to test, the following should be added to the existing shell page: 

Applications: 

- Your internships will display: Applied, Viewing X of Y
- Status, Internship application, and Last updated columns will display (note - does not match mock currently)
- Internship application will display the program name - cycle name (i.e. U.S. Department of State Student Internship Program (unpaid) - Spring 2020)
- Internship application will be a link that takes you to the application for the 3 internships you selected
- There will be a Sort by dropdown to allow you to sort by all columns.  
- The default sort will be last updated (most recent to least recent)
- View should work like it does in production on how many display and when show more will display. - Initially only 3 applications are accepted so this may be a non issue.

Invision Mock: https://opm.invisionapp.com/d/main/#/console/15990896/331677019/preview

Associated TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35775&fullScreen=false&_a=edit

Related ticket:
2459 - Shell landing page

**Comment by bmcorum** [comment]
@kbwagner I believe we had a discussion where this will display current applications not internships since students are technically applying to a cycle for a particular program (ie DoS or VSFS) and then selecting 3 preferred internships options. The middle column would display the cycle name for which the application is associated (ie Summer 2019), and it would be a link to the application.

**Comment by kbwagner** [comment]
@bmcorum yes it's on my list to update this ticket before Thursday.

**Comment by kbwagner** [comment]
@bmcorum this is updated

@abudz19 - please review the AC on this.  Brice suggested some changes when we met last week.  Since they are applying to 3 internships from one application, he suggested (rightfully so) that we display a link to the application vs each individual internship.  So that would mean changing the name of the column.  Also suggested the display for the link to the application would display the program name - cycle or at a minimum the cycle name.  
- let me know what you think and if you have any concerns.

**Comment by abudz19** [comment]
Just to make sure, we are talking about this [invision board](https://opm.invisionapp.com/d/main#/console/15360465/346381941/preview), not the one linked above? 
- so where it says internship, it will list the internship program name and cycle, instead of individual internship opportunities? That seems fine to me.

**Comment by kbwagner** [comment]
@abudz19 yes although the link above goes the right place for me - the same as your link above.  Hmmm.

- yes instead of the internship it will show the application.  Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-14-19 @abudz19 @kbwagner Please update the AC as to what is required for column headings and what the link should be.  I have already sent back 2459 as nothing matches, mock AC or page.  I'm putting this one on hold pending AC change.

**Comment by kbwagner** [comment]
@Kibrahacha67 @abudz19 this is one where I noted the mock will not match so you should be going by the AC.  Does that work or do you need the mock updated?

**Comment by Kibrahacha67** [comment]
@kbwagner column headings on the page are Status, Program, Action, and Last updated. Also the link is on Action not Program.  So that still does not match anything as far as AC.  Is that what you want?  if it is please update the AC.

**Comment by Kibrahacha67** [comment]
3-15-19 LHammond in testing,
Column headings don't match AC
extra heading for "Action" with link to opportunity when AC says the actual Internship should be a 
link to the opportunity.  moving back to development.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
@bmcorum @raywilliams I contacted Katrina via channel and she has said that the AC on this one is what is correct.  The heading "Program" is not correct and should be "Internship application"  Please change the heading and return to testing.  thank  you...

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in testing

**Comment by kbwagner** [comment]
3/20/19 - KWagner
Same issue as 2459 where column headings on the blank page are incorrect but will pass this one.

- Unable to test sort by on applications because I can only have one.  Same with show more and default sort.

Ready for final review..
