### ISSUE TITLE
Save internships

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2901]
Who: Student Applicant
What: Save a search
Why: As a student I would like to look through the available internships and save the ones I am interested in prior to moving to the "apply" process.

A/C
- On the expanded internship opportunity page, there will be a  star with a "Save" link
- When the user clicks the "Save" link the internship opportunity will be saved in the users "Student Dashboard: #2900 
- This will look as it does now in USAJOBS.  All saved jobs will have a filled in star.  non saved jobs will have the star outline.  Once saved, the star will stay filled in.
- If the user is not signed in they will be forced to sign in once they click the "save" button.

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/320303454/preview

**Comment by bmcorum** [comment]
- [ ] Create table to store saved opportunities (this can be for both students and feds)
- [ ] Create API route to save an opportunity
- [ ] Create API route to list saved opportunities
- [ ] Create API to removed saved opportunity

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum - question on this one - if I am not logged in, click on the save star, log in, is it possible to go ahead and populate the save star?  I checked to see how it works on Jobs...if I click on the save star, I sign in, and it automatically has saved it and takes me to the saved search page (which I don't think we should do)....but if we can save them from having to reclick the star once they log in that would be good.  Since we didn't clearly specify can always be a new ticket.  Let me know.  

@Piglady64 I was testing this as part of the save landing page so ended up testing this one too.  Everything looks good pending the one question above.

**Comment by kbwagner** [comment]
3/20/19 - Kwagner tested in Chrome/Test
Works
Will create an enhancement to see if we can make it work to no have to click the star again once logged out to be consistent with Jobs.  May not be able to because of login.gov interrace.

ready for final review.
