### ISSUE TITLE
Determine who can view internship search page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2904]
Who: Open Opps users
What:  determine who can view the internship search
Why: In order to limit who can view

Acceptance Criteria:
The following users will have the ability to view the internship search page as a link titled Internship under the Search navigation.
1) Non logged in users 
2) Logged in site administrators
3) Logged in federal employees that are members of DoS Unpaid Internship community
4) Logged in federal employees that are members of VSFS Internship community

**Comment by Kibrahacha67** [comment]
2-8-19 LHammond in testing

**Comment by kbwagner** [comment]
2/13/19 - KWagner 
tested in Test/Chrome
Ready for final review
