### ISSUE TITLE
Community - who can view applicants

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2905]
Who: Student internship users
What: ability to view applicants
Why: in order to limit who can see who has applied to the internship

Acceptance Criteria:
1) Applicants will not see who else has applied to an opportunity - hide right rail on internship opportunity

2) Bureau Internship coordinators will not be able to see who has applied to an opportunity nor move users forward to assigned on Internship Opportunity

3) Community administrators will have a view from the admin page where they can see who has applied for each opportunity.
- Community --> Opportunities --> Manage -- > Status of Open and beyond
- display a number of applicants i.e "78 applicants"
- the hyperlink will loads another page that then display the list of applicant first and last name

**Comment by Kibrahacha67** [comment]
@kbwagner - question, is Bureau Internship coordinators a new role?  What is there definition if so...ty Larry

**Comment by kbwagner** [comment]
@Kibrahacha67 bureau internship coordinators are the people that will create the opportunities so the same as an opportunity creator in the rest of the world.  They are community members of a student community and thus will have the ability to create.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
4/20/19 - Mdumas - Testing...

**Comment by margaretdumas** [comment]
Mdumas - @Piglady64 . Disregard my question above. I think what I was calling the right rail isn't what is being referred to in AC 1  so I verified that the applicant cannot view who else has applied to the opportunity .  This passes Moving on to review.

**Comment by Piglady64** [comment]
Julie Reviewed - I applied as Penny Coin- signed in as Kate Jones and didn't see anything in the Right Rail to indicate Penny Applied. Saw Penny Coin on the Administration page. Moving to final review
