### ISSUE TITLE
Unpaid Internship Cycle Dates: 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2906]
Who: Unpaid Internship community
What: cycle dates
Why: in order to determine when a cycle will occur and when applicants can apply

Please set the following cycle dates for the Unpaid Internship Community:  
State will begin use with their Spring  2020 cycle.

Spring 2020:
- Date range to create internship: April 12th, 2019 to April 23rd, 2019
- Date range for accepting applications: May 3rd, 2019 to June 3rd, 2019
- Date range of internship: January 6th, 2020 to April 30th, 2020 

Summer 2020: 
-  Date range to create internship: July 29th, 2019 to August 9th, 2019
-  Date range for accepting applications: August 30th, 2019 – September 27th, 2019
-  Date range of internship: May 11th, 2021 to September 30th, 2021

Fall 2020: 
         - Date range to create internship: December 13, 2019 to December 27, 2019
         - Date range for accepting applications:  January 10, 2020 to February 7, 2020
         - Date range of Internship: September 6, 2021 to December 31, 2021

**Comment by raywilliams** [comment]
@kbwagner  Should the date range of internship for Summer 2020 and Fall 2020 both be in 2020 instead of 2021? Or should the cycle names change to Summer 2021 and Fall 2021?

**Comment by kbwagner** [comment]
@raywilliams these are the dates they gave us and we even verified so although the names don't totally make sense to us I guess it does to them.  
- But with that said...I look forward to having a UI where they can update these dates on their own because I fully expect changes.  Thanks for checking!

**Comment by kbwagner** [comment]
Closing - it was determined that we can't add this through the system.  We will add manually once deployed.
