### ISSUE TITLE
Update help link on internship apply page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2910]
Who: Interns
What: Apply page help link
Why: Update to be consistent

Update the help link on the internship apply process right rail to read, "Visit U.S. Department of State Student Internship Program (unpaid)'s website" to follow the way State has asked for us to refer to their program.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/06d408b6-a747-4c9a-b39d-fbcb8786da6a)

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by margaretdumas** [comment]
1/30/19 Mdumas - In testing...

**Comment by margaretdumas** [comment]
Mdumas - testing is complete.  Moving on to review.
