### ISSUE TITLE
Department of State: Update Application After Submit from the Student Landing Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2912]
Who: Student Applicant
What: Ability to make changes to my application after submission from the student landing page
Why: As a student applicant I would like the ability to make changes to my application when I am on my student landing page

A/C
- When a student is on their landing page they will click the name of the internship cycle which is a link
- If the User has finished their application and clicks the link they will be sent to the "select internship opportunities" page of the application process
 - If the User has not finished their application and clicks the link they will be taken to page where they left off.
 - The user will be able to do the following once they are in the application process:
    - they can delete an internship opportunity from their list
   - They will be able to re-order their list
   - They will be able to add one or more internship opportunities once they delete one or more internship opportunities from their list
  - They will be able to navigate to other pages in the application process and make changes

Mock: https://opm.invisionapp.com/d/main#/console/15360465/346381941/preview

Public Link :https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Piglady64** [comment]
@abudz19 When I click on the link associated with this ticket is saying the page has been archived. Can you  point me to the mock up for this please.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-19-19 LHammond in testing

**Comment by Piglady64** [comment]
Returning to Development: There is no "update" button next to the Internship on the landing page
![image](https://user-images.githubusercontent.com/15252970/54718898-fbb5ff00-4b31-11e9-864a-9d514227a370.png)

**Comment by Piglady64** [comment]
changed A/C to match the design used to develop this and moving to final approval. 

Change: the name of the internship cycle is now a link - there is no longer an "update" link
