### ISSUE TITLE
Internship Opportunity Close out process

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2915]
Who: Internship coordinators
What: Close out opportunities
Why: In order to move opportunities forward

Acceptance Criteria:
- Created spike 3228 to do research on Open Opportunities automation. This ticket is dependent on completion of that spike.
- When the internship opportunity end date has passed, the selectee (from ATP) should be moved to (Task completed) automatically
- The opportunity status, should be moved to Completed automatically via an automated process

**Comment by Piglady64** [comment]
Julie added " When the automated closeout process runs,  the internship opportunities for the entire cycle will be set to "Completed"" to the A/C.
this was originally in ticket #3000, however, this ticket couldn't not be tested with this statement in the A/C.

**Comment by Piglady64** [comment]
On hold until we have the results of the Spike in #3228

**Comment by Piglady64** [comment]
This has been taken care of with new tickets. #3607 #3001 #3609   Closing this issue
