### ISSUE TITLE
Department of State: Transcripts

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2919]
Who: Student Applicant
What: Transcript page 
Why: The student is required to submit a transcript with their application.

- There will be a header "Transcripts"
- There will be a list of transcripts the user has stored in their USAJOBS profile
- The user can select the transcript they would like to submit with their application
- The "Upload transcript" link will take the user to their USAJOBS profile to upload a transcript (this will open in a new window)
- When the user returns to their application there will be a "refresh transcripts" button to update their application (this was discussed in our sprint planning meeting- because the transcripts are uploaded in USAJOBS we need to pull the new transcript into the application)
- When the user clicks the "view" button it will act the same as it does on USAJOBS (this was discussed during sprint planning- the view functioanlity will be dependent on the users browser)
- The "Back" Button will take the user to the "Experience & References" page
- The "Save and continue" button will take the user to the "Languages & Skills" page.
- New Transcripts are added and saved on USAJOBS.

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Piglady64** [comment]
@bmcorum here is the separate ticket for transcripts like we discussed in sprint planning.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
03/8/19 - Mdumas - Testing...

**Comment by margaretdumas** [comment]
Mdumas - Moving to review.

**Comment by Piglady64** [comment]
3/19/19 Moved to Final Approval
