### ISSUE TITLE
Department of State: References

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2921]
Who: Student Applicant
What: Reference Page
Why: As a student applicant I would like to add references to my application

A/C
There will be a header: References (optional)
- There will be a card for each reference that will include the following information
   - There will be a + that will open the card to expose the information
   - The name of the reference
   - The agency or company of the reference (Bold)
   - The "+Add reference" link will take the user to a blank reference page
    - https://opm.invisionapp.com/d/main/#/console/15360465/319289325/preview
   - There will be a header "References"
      - There will be a text box for the following information
         - Name
          - Phone
         - Email
   - There will be a header "Reference Type"
      - There will be a radio button for Professional and Personal
   - There will be a text box for Employer (optional)
   - There will be a text box for Title (optional
   - There will be a question "May we contact this person about you?" with a radio button for yes and no
   - When the user clicks the "Save references" button they will return to the "Experience and References" page with the new references displayed
   - The "Cancel and return" button will return the user to the "Experience and References" page and discard the information provided on this page.
- References added during the Open Opportunities application process will not be updated into the applicant's USAJOBS profile and will only be saved in Open Opps.

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment]
@Piglady64 - I have a question about the set up here.  In the AC seems like you go from the card directly to add references.  I don't see a requirement for opening the card and how the information is displayed.  so below I took images directly from jobs and how it is set up.  am I missing something or is this handled later in the process?  ty Larry  I just want to make sure we have proper test coverage as if I go directly to add references without testing opening the cards and editing information it skips some important testing...

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/30c4abc1-7d7e-4e59-96f6-27a6a8528465)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2b588c19-b28d-4e58-ab5c-8a005e4136d8)

**Comment by Piglady64** [comment]
@Kibrahacha67 The user should be able to "add a reference" without opening the card. If they want to delete a reference that is currently in their application they would need to open the card. The card design is in a different ticket https://github.com/openopps/openopps-platform/issues/2995.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
03/6/19 - Mdumas - passed testing.. Moving on to review.

**Comment by Piglady64** [comment]
3/6/19 - JJackson- Sent back to development for the following reasons:
1) the Title of the reference is showing on the card not the Employer (Agency or organization)
![image](https://user-images.githubusercontent.com/15252970/53911819-891f2c80-4025-11e9-89b4-a37e28278a6a.png)
![image](https://user-images.githubusercontent.com/15252970/53911845-9c31fc80-4025-11e9-81c0-6a56c19c4342.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/8/19 - Mdumas - In testing...

**Comment by margaretdumas** [comment]
Mdumas - Moving back to review. Verified the Employer is displayed.

**Comment by Piglady64** [comment]
3/11/19 Moving to Final Approval
