### ISSUE TITLE
Department of State: Skills

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2922]
Who: Student intern applicant 
What: Enter skills
Why: In order to show hiring managers the skills I can contribute to the internship

Acceptance Criteria:
- There will be a header "Skills" (Bold)
- There will be instructional text
- There will be an + Add skills blue banner that is the full width of the page
   - This link will take the user to a blank "skills" page 
     - https://opm.invisionapp.com/d/main/#/console/15360465/319289349/preview
     - "All fields are required" will be in the right margin
     - There will be a header "Skills"
     - There will be a text box for the user to type skills into the box
      - The skill will display as a pill
      - There will be a limit of 5 skills
      - The "cancel and return" button will return the user to the "Language & Skills" Page and discard any information provided.
      - The "Save skills" button will return the user to the "Language & Skills" page with the new skills displayed as pills (same as in Open Opportunities in production)

- Skills will only be added and saved on Open Opps and can be viewed on the applicant's profile. 
Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment]
@Piglady64 - question: is there a maximum number of pills that will be displayed in the skills box?  in Jobs the number is 5...ty Larry

**Comment by Piglady64** [comment]
@Kibrahacha67 Yes there is a limit of 5. I updated the A/C above

**Comment by jhanson12** [comment]
Skills is not required...so I removed the "All fields are required"  from the skills page.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Piglady64** [comment]
4/8/19 - Julie reviewed - "all fields are required" is missing

InVision Mock: 
![image](https://user-images.githubusercontent.com/15252970/55752733-ae34ff80-5a16-11e9-8e97-cc29bd7d4d91.png)

**Comment by Piglady64** [comment]
Julie - reviewed and moved to final approval
