### ISSUE TITLE
Department of State: Submission Confirmation

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2927]
Who: Student Application
What: Submission confirmation submission
Why: As a student applicant, I want to know that my application has been submitted and know what to expect now

A/C
- When the user clicks the "Submit application" they will see this page.
- There will be a green box at the top of the page "Congratulations! Your application has been submitted. Thanks for submitting your application to the U.S. Department of State Student Internship Program (Unpaid)" (see mock for formatting)
- There will be a white box aligned with the left margin
   - Header - What happens next?
   - The U.S. Department of State will:
      1. Review all applications after the application period closes.
      2. Set up interviews - you'll get another email if you're selected for an interview.
      3. Send offer emails - you'll get another email if you're selected for an internship.

- There will be a link "See the internship opportunities I've applied to. (this will take the user to their dashboard)

- There will be drawer "Learn more about the selection process" with +
- The +sign will expand the drawer 
- When the drawer is expanded:
   The U.S. Department of State will review your application to make sure you're eligible and meet the qualifications for the internship. If you meet the qualifications, a hiring manger will email you to set up an interview. Once they finish all interviews, they will let you know if you got the internship.

- There will be a second drawer "Learn more about the security clearance process with +
   - When the drawer is expanded.
      If you're selected for an internship, you must receive either a Secret or Top Secret security clearance. This process may take many months and will require you to complete:
      - An electronic security questionnaire.
      - Fingerprint cards.
      - An in-person interview with an investigator.

   We recommend you don't make any travel or housing plans until you receive your security clearance. Read our FAQs about the security clearance process (this is a link will go to https://careers.state.gov/intern/student-internships/selection-process/#expandfaq)

Related ticket # 2994

InVision Mock: https://opm.invisionapp.com/d/main#/console/15360465/344480823/preview

Public Link: Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Piglady64** [comment]
Alex Budz [2:26 PM]
Drawer text for "Learn how to save a job search"
You can save a search to help you look for jobs in your area of interest. When you save a search, we’ll automatically look for jobs that match the keywords and other criteria in your search.

Learn how to create a saved search and sign up for email notifications. (https://www.usajobs.gov/Help/how-to/search/save/) (edited)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-7-19 LHammond in testing

**Comment by Piglady64** [comment]
3/11/19 moved to final approval
