### ISSUE TITLE
Cannot sign into Account as student if federal hiring path was previously set

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#2928]
The Akamai page appears when attempting to sign into an account that previously used the federal hiring path.

Steps to reproduce.  
1.  Sign into USAJOBS and change hiring path to remove any of the federal selections - this includes the military service selections
2.  Select "Student" hiring path and save
3.  Navigate to Open Opportunities and attempt to sign into that now student account

Results:  Akamai page is displayed

**Comment by raywilliams** [comment]
Unable to replicate. Believe this may have been a issue related to a previous bug causing Akamai pages during log in and that this was just a side affect.

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 are you able to replicate this issue?

**Comment by Kibrahacha67** [comment]
@raywilliams @margaretdumas I just tried and it took me into open opps, but it didnt take me to the search page it took me to the home page for students...

**Comment by Kibrahacha67** [comment]
7-31-19 LHammond in testing

**Comment by kbwagner** [comment]
8/26/19 - Tested in Chrome/Test
Ready for final review
