### ISSUE TITLE
Update location icon to match design system

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2935]
The location icon used throughout Open Opps should be updated to match the location icon used in the design system and USAJOBS.  Update the font awesome icon used for location.

![image](https://user-images.githubusercontent.com/18709918/51913416-6ce3fc00-23a4-11e9-8583-78a2d9ca445d.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
2-1-19 LHammond in testing

**Comment by kbwagner** [comment]
2/5/19 - KWagner tested in Test/Chrome and icon has been updated.
Ready for final review.
