### ISSUE TITLE
Remove Status Filters from Search

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#2946]
### Who 
Open Opps Users

### What 
Remove draft, submitted, not open, cancelled status filters from search.

### Why
Currently only admins can see this filters, and there is a dedicated dashboard for this. This is redundant functionality and causes confusion.

### Acceptance Criteria

1. The following filters will be removed from search: 
- Draft 
- Submitted 
- Not Open 
- Cancelled 

2. Search status filters for federal opportunities will only include the following regardless of user permission roles
- Open
- In progress
- Completed

3. Admin users will be able to see drafts from the Admin dashboard

## Current Search Functionality for Sitewide Admins
- Can search for draft opportunities
- Can view draft opportunities from search
- Can search for submitted opportunities
- Can view submitted opportunities from search
- CANNOT approve submitted opportunities from search
- CANNOT delete submitted opportunities from search
- Can search for "not open" opportunities
- Can view "not open" opportunities from search
- Can search for canceled opportunities
- Can view canceled opportunities from search
- CANNOT approve canceled opportunities from search

## Current Functionality for Sitewide Admins from administration dashboard
- CANNOT see draft opportunities **This could easily be added**
- CANNOT view draft opportunities **This could easily be added**
- Can see full list of submitted opportunities
- Can view a submitted opportunity
- Can approve a submitted opportunity
- Can delete a submitted opportunity
- Can see a full list of "not open" opportunities
- Can view a "not open"opportunity
- Can see a full list of canceled opportunities
- Can view a canceled opportunity

**Comment by bmcorum** [comment]
@kbwagner and @tlorrison can we talk about this ticket at some point soon?

**Comment by kbwagner** [comment]
2/3/2020 - 
Update this ticket to add drafts to the admin section and in the same ticket  to update the search filters for any role to only show Open, In Progress, and Completed
@nia-johnson as you have time

**Comment by nia-johnson** [comment]
@kbwagner done

**Comment by nia-johnson** [comment]
https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41556&_a=edit
