### ISSUE TITLE
Data API: Application Preview

### ISSUE THREAD

**Issue by jonwoody** [openopps/openopps-platform#2965]
Who: Hiring Manager
What: Internship Application Data
Why: As a hiring manager I want to see details on the applicant's application.

A/C

* The following information will be SENT to ATP from OpenOpps:
    * Desired opportunities
        * Geographic location
        * Name of opportunity
    * Skills
    * GPA
    * Overseas experience
        * Experience name
        * Start/End dates
    * Security Clearance
        * Type of clearance
        * Issuing agency
    * Prior VSFS Experience
        * Name of experience
        * Start/End dates
    * References
        * Names
        * Reference Company
        * Reference Job Title
        * Reference Email
        * Reference Telephone
        * Okay to Contact Y/N
        * Type of Contact Personal/Professional
    *  Work Experience (All relevant fields)
    * Statement of Interest

Invision Design:
https://opm.invisionapp.com/share/Q8OESMCYS5P#/screens/338877567_Internship-Board-Applicant_Preview_Expanded

TFS Related Ticket:
https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Polydeuces/_workitems?id=36107&triage=true&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
Marked as ready for deployment on 4/24/2019
