### ISSUE TITLE
Data API: DoS Applicant Review Index

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2968]
Who: DoS Applicant Reviewer

What: Able to view necessary data on internship opportunities

Why: To understand the current status of the internship opportunities for management.

A/C

-An API will be created that will allow for Open Opps data to be pulled by ATP.
-Elements that will be available via the API include:
* Cycle Name (Source: Open Ops, Value of that element in this example is: Summer 2020)
* Internship location (Source: Open Opps; Value of that element in this example is: Paris, France)
* Internship Name (Source: Open Opps; Value of that element in this example is: Internship opportunity announcement Department of State Internship Program internship)
* Number of applicants (Count of the number of active applicants saved to the five columns/lists in that opportunity)
* Number of interns needed (This data element is entered by the user when they set up the opportunity)
*Internship closed date (Open Opps)

If in the course of development, the technical team has the liberty to designate more appropriate date sources.

Invision Design (from Drew on 2/6/19):
Active: https://opm.invisionapp.com/share/Q8OESMCYS5P
Archived: https://opm.invisionapp.com/share/Q8OESMCYS5P#/338360186_Internship-Index-Archived 

TFS Related Ticket:
https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Polydeuces/_workitems?id=36106

**Comment by KatMullens-work** [comment]
Old AC: DO NOT USE

  
The dark blue header of this page has:
Campaigns (static element, in orange on this example)
Applicant review as a title (static element, in white on this example)
 
The dark blue header also has:
***This is only intended to show activity on a Review Board. If no new activity on a board that the user has been assigned, then no blurb on the banner.***

Your last activity (static text)
(A link to the name of the last opportunity that the user viewed)
on (static text)
(date of the user’s last activity on that board)
 
Please note that this view has two tabs:
-One labeled “Active”
-One labeled “Archived”
*Each tab should include a count of the number of Active or Archived opportunities in that tab in parenthesis after the label. Example: "Active (10)" if there are ten Active opportunities.

This is the information for the "Active" tab: 
On each tab, there is a card for each opportunity and on each card are the following elements:
- Cycle Name (Source: Open Ops, Value of that element in this example is: Summer 2020)
- Internship location (Source: Open Opps; Value of that element in this example is: Paris, France)
- Internship Name (Source: Open Opps; Value of that element in this example is: Internship opportunity announcement Department of State Internship Program internship)
- Number of applicants (Count of the number of active applicants saved to the five columns/lists in that opportunity)
- Number of interns needed (This data element is entered by the user when they set up the opportunity )
- Last edited by (Source: ATP)

Each card also has a small paperclip icon and a hyperlink to the opportunity labeled as "View opportunity".

For the "Archived" tab:
There is a list of the archived opportunities with four column headers. Those column headers are:
-Opportunity
-Session
-Location
-Closed

If in the course of development, the technical team has the liberty to designate more appropriate date sources.

**Comment by KatMullens-work** [comment]
Added to AC: *Internship closed date (Open Opps)

**Comment by bmcorum** [comment]
TFS ticket was marked deployment ready on June 6th 2019
