### ISSUE TITLE
Data API: Applicant Review - Data - Review Board

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2969]
Who: DoS Applicant Reviewer

What: Able to view necessary data on internship opportunities

Why: To understand the current status of the internship opportunities for management.

A/C
This ticket pulls data and associates it with these UI elements on Applicant Review Index:
* The following information will be SENT to ATP from OpenOpps:

API returns information to be reviewed by logged in ATP user from Open Opps or other system as specified:

Top dark blue navigation bar for the Internship Review Board:
* Cycle Name (Source: Open Ops, Value of that element in this example is: Summer 2020)
* Internship Name (Source: Open Opps; Value of that element in this example is: Internship opportunity)
-Initials icons representing the individuals and number of people participating on this opportunity and with the functionality to add more people (<<< - functionality of this element to be described in a new ticket>>>)
-A Hyperlink to the opportunity in Open Opps that is labeled “View opportunity”.
-Number of seats pulled from Open Opps

****This ticket covers the top header bar of the screen. The body of the screen is covered by these related tickets:
TFS: 36835
GitHub: 2974

If in the course of development, the technical team has the liberty to designate more appropriate date sources.

Invision Design (confirmed with Drew on 2/6/19):
https://opm.invisionapp.com/share/Q8OESMCYS5P#/screens/335383918

There is also a screen showing the initial way a board will look, with just cards in the first list (in case that is helpful).
https://opm.invisionapp.com/share/Q8OESMCYS5P

TFS Related Ticket:
https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35877

**Comment by KatMullens-work** [comment]
Added this as AC:
API returns a list of internships opportunities to be reviewed by logged in ATP user from Open Opps or other system as specified:

Top dark blue navigation bar for the Internship Review Board:
Left side column:
-Campaign name (Source: ATP; Value of that element in this example: Campaign – Summer 2020) in orange
-Internship opportunity (Name of the internship opportunity pulled from ATP)
-Initials icons representing the individuals and number of people participating on this opportunity (per the design system functionality)
-Last edited by: (static text)  - followed by the name of the user (pulled from ATP) and time they edited the opportunity (pulled from ATP).
 
Right hand column:
-Small paperclip icon with (name of internship opportunity pulled from ATP) "," (static) (display number of internship seats from ATP; this is an entered, not calculated, value)
-A Hyperlink to the opportunity in Open Opps that is labeled “View opportunity”.

**Comment by KatMullens-work** [comment]
Deleted this from AC: Opportunity Name (source: Open Opps)
Opportunity Creator (source: Open Opps)
Number of applicants in opportunity pool (source: Open Opps)
Number of vacancies (source: Open Opps)
Last Edited date (source: ATP)
Card movement, messaging, etc
Users the board has been shared with (source: ATP)
Initially this will only display 1 user: the opportunity creator
Applicants by list (source: ATP)
Applicant name (source: Open Opps)
Applicant degree (source: Open Opps)
Applicant major (source: Open Opps)
Applicant GPA (source: Open Opps)
Applicant language(s) (source: Open Opps)
Applicant current location (source: Open Opps)
Applicant last contacted date (source: ATP)

**Comment by bmcorum** [comment]
### For blue header - API
- Internship title (Campaign Name)
- List of users that have access to review this internship
- Number of interns they are looking for (# of seats)
### For columns - Pending changes from design team
???

**Comment by KatMullens-work** [comment]
Former AC (corrected on 2/8) 
A/C
This ticket pulls data and associates it with these UI elements on Applicant Review Index:
* The following information will be SENT to ATP from OpenOpps:

API returns information to be reviewed by logged in ATP user from Open Opps or other system as specified:

Top dark blue navigation bar for the Internship Review Board:
Left side column:
-Campaign name (Source: ATP; Value of that element in this example: Summer 2020) in orange with static "Campaign - " label preceding it.
-Internship opportunity (Name of the internship opportunity pulled from ATP)
-Initials icons representing the individuals and number of people participating on this opportunity and with the functionality to add more people (per the design system functionality)
-Last edited by: (static text) - followed by the name of the user (pulled from ATP) and time they edited the opportunity (pulled from ATP).

Right hand column:
-Small paperclip icon with (name of internship opportunity pulled from ATP) "," (static) (display number of requested internship seats from ATP; this is an entered, not calculated, value)
-A Hyperlink to the opportunity in Open Opps that is labeled “View opportunity”.
**In this InVision mockup, there is a number 1 after the paperclip. This should NOT appear in the final; it is an error. 

****This ticket covers the top header bar of the screen. The body of the screen is covered by these related tickets:
TFS:
GitHub:

If in the course of development, the technical team has the liberty to designate more appropriate date sources.

Invision Design (confirmed with Drew on 2/6/19):
https://opm.invisionapp.com/share/Q8OESMCYS5P#/screens/335383918

There is also a screen showing the initial way a board will look, with just cards in the first list (in case that is helpful).
https://opm.invisionapp.com/share/Q8OESMCYS5P

**Comment by bmcorum** [comment]
Marked as ready for deployment on 5/6/2019
