### ISSUE TITLE
Data API: Agency Portal - Applicant Review - Data - Review Board- Bottom

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#2974]
User Story: As a DOS reviewer, I want to be able to view necessary data on internship opportunities to understand the current status of the internship opportunities for management.

AC

-Create an authenticated GET API route so that ATP can collect a list of internship candidates for review and processing.

This ticket refers to the body of the screen with the columns where users can sort and move applicants through.

On each "card" is listed:
-Applicant name (source: Open Opps)
-Applicant degree (source: Open Opps)
-Applicant GPA (source: Open Opps) 
-Applicant language(s) (source: Open Opps)

InVision Mocks: 
Invision Design (confirmed with Drew on 2/6/19):
https://opm.invisionapp.com/share/Q8OESMCYS5P#/screens/335383918

There is also a screen showing the initial way a board will look, with just cards in the first list (in case that is helpful).
https://opm.invisionapp.com/share/Q8OESMCYS5P

TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/36385

**Comment by KatMullens-work** [comment]
ORIGINAL INFORMATION FOR REFERENCE: User Story

AC

-Create an authenticated GET API route so that ATP can collect a list of internship candidates for review and processing.

This ticket refers to the body of the screen with the columns where users can sort and move applicants through.

There are five static columns; unlike in ATP, the columns cannot be renamed, added, or deleted. The five columns are:
-Assigned
-Interviewing
-Interviewed
-Offer out
-Accepted

-Each column is labeled with its respective name.
-Each column has the number of applicants in that column, which is a count of the number of people in that column followed by the static word "applicants".
--Each person is represented by an individual "card" in that column.

The column header also includes an ellipsis menu to allow other functionalities not described in this ticket.

On each "card" is listed:
-Applicant name (source: Open Opps)
-Applicant degree (source: Open Opps)
-Applicant GPA (source: Open Opps) with the label "GPA"
-Applicant language(s) (source: Open Opps)
-Applicant current location (source: Open Opps) preceeded by a small "location pin" icon
-Applicant last contacted date (source: ATP) with the label "Last contacted" before the date is in the lower right hand corner of the card.
-Each card also includes a small trashcan icon in the upper right hand corner to allow a user to delete the card from that opportunity (not delete from the database).
-Each card also includes a small envelope icon on the bottom left hand corner with a hyperlinked option to email the person described on the card; that hyperlink is labeled "Message".
-All elements should conform to the design system.

InVision Mocks:
Invision Design (confirmed with Drew on 2/6/19):
https://opm.invisionapp.com/share/Q8OESMCYS5P#/screens/335383918

There is also a screen showing the initial way a board will look, with just cards in the first list (in case that is helpful).
https://opm.invisionapp.com/share/Q8OESMCYS5P

TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/36385

**Comment by bmcorum** [comment]
Marked as ready for deployment on 5/6/2019
