### ISSUE TITLE
Prevent cycles within a community from overlapping

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2988]
Who: Admin
What: Prevent overlapping cycles
Why: to control what is displayed

A/C:
- Issue - if cycles overlap, two blue boxes will display and internships from the multiple cycles can be displayed for the student to apply to.

Resolution:
- We could add some logic during cycle creation that prevents users from creating overlapping apply cycles
- within the same community

I can see VSFS wanting overlapping cycles so maybe for now we just apply this to unpaid

**Comment by sabushanab** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing

**Comment by Kibrahacha67** [comment]
2-12-19 LHammond in testing

**Comment by kbwagner** [comment]
@sabushanab can I get an artifact that shows me all of the existing cycle dates so I can try to replicate this? Thanks!

**Comment by kbwagner** [comment]
![cycle times](https://user-images.githubusercontent.com/18709918/52721275-52e71380-2f77-11e9-81e3-0520980de9c1.png)

@sabushanab I found one in another ticket.  Attaching here for testing.

**Comment by kbwagner** [comment]
2/13/19 - KWagner tested in Test/Chrome
Screen shot of error attached
![image](https://user-images.githubusercontent.com/18709918/52721576-f89a8280-2f77-11e9-851f-13a529c908d1.png)

ready for final review.
