### ISSUE TITLE
Department of State: Right Rail of Submission Confirmation Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2994]
Who: Student
What: Notification that the user now has a USAJOBS profile and what they can do about it. 
Why: As a student I want to be informed that I now have a USAJOBS profile and information about federal hiring.

A/C
- There will be a box in the right rail "You now have a USAJOBS profile"
- There will be content under the header 
    With a USAJOBS profile, you can apply to jobs, upload a resume and make it searchable, save job searches and sign up for email notifications. 
- There will be 4 drawers with a + in the left margin that will open the drawer to expose content
    1) Find a job
      This will link the user to USAJOBS search 

   2) Learn how to make your resume searchable
       Making your resume searchable adds it to the USAJOBS Resume Mining collection. HR specialists and hiring managers from federal agencies use resume mining to look for people (with a searchable resume in their USAJOBS profile) to fill their job vacancies.

Plus, when your resume is searchable and you have completed your profile, your profile is searchable too. 
https://www.usajobs.gov/Help/how-to/account/profile/searchable/ (will open in a new window)

   3) Learn how to save a job search
     You can save a search to help you look for jobs in your area of interest. When you save a search, we’ll automatically look for jobs that match the keywords and other criteria in your search.
Learn how to create a saved search and sign up for email notifications. 
https://www.usajobs.gov/Help/how-to/search/save/) (will open in a new window) 

  4) Learn more about working in the government (this is the same as USAJOBS)
     - When the drawer is opened it will have 4 links: (these links will open in a new window)
     - How is finding a job in the government different that the private sector? (https://www.usajobs.gov/Help/working-in-government/appointments/difference-from-private-sector/) (will open in a new window)

      - How long does it take to get a federal job? (https://www.usajobs.gov/Help/faq/application/how-long/) (will open in a new window)

      - What's the difference between eligibility and qualifications? (https://www.usajobs.gov/Help/faq/application/eligibility/difference-from-qualifications/) (will open in a new window)

     - How does the application work? (https://www.usajobs.gov/Help/faq/application/process/) (will open in a new window)

Related Issue #2927 

InVision Mock: https://opm.invisionapp.com/d/main#/console/15360465/344480823/preview

Public Link: Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-7-19 LHammond in testing

**Comment by Piglady64** [comment]
3/11/19 Moved to final approval
