### ISSUE TITLE
Department of State Drawers

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2995]
Who: Student
What: ability to edit or delete information in Open Opps
Why: As a student applying for an internship I would like the ability to edit and delete information from my application

A/C
- The drawers throughout the application will follow the design system https://usajobs.github.io/design-system/drawer/
  - Each drawer will for References, Experience and Languages will have an edit button that will allow a user to edit the information in Open Opportunities only
  - Each drawer for References, Experience and Languages will have a delete button that will allow the user to delete the information in Open Opportunities only

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-8-19 LHammond in testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-14-19 LHammond in testing

**Comment by Piglady64** [comment]
3/15/19 Reviewed and moved to Final Approval
