### ISSUE TITLE
Open Opps - Applicant Status updates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2999]
Who: Student intern applicants
What: Status updates
Why: to show when an intern has applied or been selected

Acceptance Criteria:
Applicant status for unpaid internships will display on the landing page as follows:
- In progress - The applicant has started the application process and saved but not submitted
- Applied - The applicant has submitted their student intern application 
- Not selected - When the non select email has been sent from ATP, pull the information and mark those applicants as non selected.  
- Selected - when the selected email has been sent from ATP, pull the information and mark those applicants as selected. These are applicants in the primary column from ATP.
- Alternate - when someone is selected in the alternate column from ATP and has gotten the alternate email, they are marked alternate in Open Opps.

Completed status will be part of a new ticket - 3526

Related Ticket:
- 2915 - Close out process

**Comment by kbwagner** [comment]
@tlorrison Macon had this comment, "“Only concern is that “Not selected” would not show for months after a student was not selected. Maybe we add a “Selected” status as well based on Internship start date? Show “Selected/Not Selected” based on internship start date.”  

My comment - We had discussed this process with State and they said they consider someone official if they show up the day they are supposed to start (Date range of internship start date) and don’t really track if they finish or not.    They didn’t seem too concerned about the status in Open Opps..all of the selected and non selected emails go out from ATP  With the API, could we pull over “selected” from ATP on the start date of the internship and then possible show selected and not selected?  Then pull it again on the end date which would then do the complete process?   The only issue is if they don’t send out those non select emails but we’ve told them on Open Opps.

@tlorrison thoughts on this?  If we could show the "Selected"/Not selected earlier that would probably be good.  Or do we ask State?  @Piglady64

**Comment by Kibrahacha67** [comment]
@kbwagner Question is submitted the same as Applied?  in open opps now we have Applied on the home page but not submited

**Comment by kbwagner** [comment]
@Kibrahacha67 yes submitted is the same as applied. Didn't realize we had two different terms going.  Applied is fine - i just need to make sure the help page says the right thing too.

**Comment by Kibrahacha67** [comment]
@kbwagner thanks

**Comment by kbwagner** [comment]
updated AC...will message Debbie to update help content.

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing 
Testing completed, moving to review.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing
Testing completed moving to review.

**Comment by Piglady64** [comment]
My student "Penny Coin" only has 2 internships "completed" but she has a badge with a 3 on it. Returning to development.
![image](https://user-images.githubusercontent.com/15252970/64555822-2a0bde80-d30c-11e9-93ae-793777173c83.png)

![image](https://user-images.githubusercontent.com/15252970/64555871-41e36280-d30c-11e9-9ac7-3525f4ef47ab.png)

**Comment by Piglady64** [comment]
@kbwagner I completed the internships before I looked a the dashboard so I haven't confirmed the "selected" "not selected" status. I have verified "In progress", "applied" "alternate"

**Comment by kbwagner** [comment]
9/26/19 - KWagner tested UAT/Chrome the remaining statuses of Selected and not selected
Ready for final review
