### ISSUE TITLE
Open Opps - Internship status updates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3000]
Who: Bureau Internship coordinators 
What: Internship opportunity status updates
Why: in order to close out the internships

Acceptance Criteria:
The following internship statuses will be available for display both on the internship itself in a pill and on the landing page for applicants and creators
- Draft - The internship has been saved as a draft but not submitted
- Submitted - The internship has been submitted for approval to the community manager
- Approved - The internship has been approved by the community manager
- Open - the internship has been approved, the application start date for the selected cycle has passed, and the job has not yet been completed
- Completed - When the automated closeout process runs in ticket 2915, the internship opportunities for the entire cycle will be set to "Completed"

Related ticket:
- 2915 - closeout process
- 2999 -  applicant status update

**Comment by kbwagner** [comment]
@abudz19 @mchung07 for this ticket we have added a status of "Approved"...do we need a new pill color for this status?  It will go from draft to submitted to approved where it will sit until the open date hits.

**Comment by Kibrahacha67** [comment]
@kbwagner Question, will this also apply to the statuses on the Administration/Community/Opportunities (Manage) page?  As they don't line up now...or will that be another ticket?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
@Kibrahacha67 - correct there are more tickets to fix the admin dashboard.
- No, there isn't a pill no the opportunity although I may look into adding a future ticket for that.  It might be helpful...thanks!

**Comment by Kibrahacha67** [comment]
4-1-19 putting on hold as there are some issues with the close out  and I cannot confirm the "Completed" status.

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - as this ticket would be on hold until ticket 2915 is completed because of the last requirement in the AC, would it be possible to move that requirement to 2915 so that we can move this ticket through and handle all of the completed tasks in 2915?

**Comment by Piglady64** [comment]
Julie removed "- Completed - When the automated closeout process runs in ticket 2915, the internship opportunities for the entire cycle will be set to "Completed"" from the A/C and added it to #2915 so this ticket can be tested.

**Comment by Kibrahacha67** [comment]
4-11-19 LHammond taking the hold off this ticket and putting it back in testing.

**Comment by Piglady64** [comment]
Julie reviewed - moving to final approval
