### ISSUE TITLE
Internship Email: Branding

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3004]
Who: All student internships
What: Branding of emails
Why: In order to have consistent branding for both Open Opportunities and the Department of State

Acceptance Criteria:
For the U.S. Department of State Student Internship Program (unpaid) community, all emails that are sent from Open Opps should have the following branding applied:

Julie - can you check on whether we need to do anything specific with responsive design?    Might need to be a new ticket.

**HTML**
https://github.com/USAJOBS/responsive-emails/blob/98a047a31a064f21a9f76169232cb6fe999b91c8/dist/atp-dos-selected-for-interview.html

**TXT**
https://github.com/USAJOBS/responsive-emails/blob/98a047a31a064f21a9f76169232cb6fe999b91c8/dist/atp-dos-selected-for-interview.txt
      
**IMG**

![localhost_3000_atp-dos-selected-for-interview html](https://user-images.githubusercontent.com/13023132/53513260-c66a4400-3a92-11e9-9335-620c9df8eb08.png)

**Comment by bmcorum** [comment]
@kbwagner since this email will come from OpenOpps the section that state, "To make sure you get these emails.." should include the OpenOpps email account not DoS. That won't help make sure our emails get delivered.

**Comment by kbwagner** [comment]
@bmcorum thanks!  I thought we had discussed some sort of alias that could display.  Even if it days U.S. Department of State Student Internship Program (unpaid) OpenOpps@openopps.usajobs.gov or whatever the return email is?

**Comment by bmcorum** [comment]
@kbwagner yes we can set a reply to email, but this is for an email that is not meant to be replied to therefore it would come from OpenOpps and there is no reason why we should update or set email headers to make it look like it came from DoS.

**Comment by Piglady64** [comment]
Talked to Drew and because these emails are coming from OO the DoS branding is not necessary
