### ISSUE TITLE
Load final bureau/office/post data 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3005]
Who: DoS Unpaid Internship creators
What: Bureau/Office/post data
Why: to update the existing data to data approved by the unpaid program

The following updated list of bureau/office/post data should be added to the system and should replace the previous data.

[Bureaus and Offices Updated.xlsx](https://github.com/openopps/openopps-platform/files/2902447/Bureaus.and.Offices.Updated.xlsx)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. See attached spreadsheet in AC.

**Comment by Kibrahacha67** [comment]
3-19-19 LHammond in testing

**Comment by kbwagner** [comment]
3/19/19 - data appears to be correct.

Will put in an enhancement to make the office/post field alphabetical.  

Ready for final review.
