### ISSUE TITLE
Search: Default program based on where intern came from.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3010]
Who: Interns
What: Default the program radio button
Why: in order to keep the student in the program they originally researched online

Acceptance Criteria:
- Default the program filter based on where the user comes from
- Unpaid - if the user comes from <insert unpaid link>, the program radio button will default to Student Internship Program (unpaid)
- VSFS - if the user comes from <insert VSFS site link>, the program radio button will default to VSFS

Related ticket - 2704 Program Filter

**Comment by bmcorum** [comment]
@kbwagner this would be us simply providing each program with the proper search URL that would have the proper radio button selected. This would not require any new code.

**Comment by kbwagner** [comment]
@bmcorum - got it.  We already gave unpaid the /internships link.  

Can you provide us with the correct links for unpaid and VSFS? 

If I click on the unpaid link in test I get: https://openopps.test.usajobs.gov/search/internships?page=1&program=3

VSFS I get: https://openopps.test.usajobs.gov/search/internships?page=1&program=4

Are those what we should provide but remove "test"?

**Comment by kbwagner** [comment]
10/29/19 - Closing - VSFS has decided not to move forward with Open Opportunities.
