### ISSUE TITLE
Office should not be required if bureau doesn't have any offices under it

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3012]
Who: Internship creators
What: Office not required if bureau doesn't have any offices under it
Why: Not all bureaus have offices

Acceptance Criteria:
- On Create Opportunity, if a bureau is selected that does not have an office/post, make office/post not a required field.

**Comment by bmcorum** [comment]
- [ ] Need to provide a list of bureaus that do not have offices in our database to test for validity of functionality.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**NOTE:** Need to provide you with a list of bureaus from the database that do not have offices.

**Comment by Kibrahacha67** [comment]
3-14-19 LHammond in testing

**Comment by bmcorum** [comment]
[Bureaus.and.Offices.Updated.xlsx](https://github.com/openopps/openopps-platform/files/2902447/Bureaus.and.Offices.Updated.xlsx)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in review.

**Comment by kbwagner** [comment]
3/20/19 - Kwagner
Test/Chrome

Tested with international joint commission and it works.

Ready for final review.
