### ISSUE TITLE
Community Admins: Must be able to approve and delete 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3034]
Who: Community managers
What: Approve and delete
Why: to allow them to self serve and take burden off of site admin

Issue: Community managers receive a generic error message when they try to approve an opportunity from the Community Admin page.  
![error](https://user-images.githubusercontent.com/18709918/53128539-0f6e4580-3533-11e9-9d36-0ac94fa4e355.png)

Acceptance Criteria for fix: 
- Community managers should be able to approve opportunities that have been submitted for their community
- Community managers should be able to delete opportunities that have been submitted for their community
- The standard error messages used in Open Opps and the design system for approving/deleting opportunities should be used

Testing Note:
- Testing should be done with an account that is only a community administrator (not a system admin or agency admin)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
2/28/19- Mdumas ....in testing

**Comment by margaretdumas** [comment]
Mdumas - moving on to review.  Was able to successfully approve and delete opportunities as a community admin.

**Comment by kbwagner** [comment]
3/4/19 - Tested in UAT with an account that is only a community admin and not a sitewide admin.
- Approval process successful.
- Ready for final review. @tlorrison 

Entered bug 3105 because the opportunity doesn't show up unless logged in as an admin.
