### ISSUE TITLE
Agency Portal - Applicant Review - Messaging - 'Application Received' Template

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#3036]
Who: Hiring Manager

What: Ability to select default 'Application Received' message to a/an applicant(s)

Why: To send an email to a/an applicant(s) that their internship application has been received by DOS.

The template that should be used for the Applicant Received message is as follows:
HTML:
https://github.com/USAJOBS/responsive-emails/blob/master/dist/atp-dos-application-received.html

TXT:
https://github.com/USAJOBS/responsive-emails/blob/master/dist/atp-dos-application-received.txt

What triggers this email: Sent automatically when an applicant submits their application and we receive it.

Subject Line of email will be (without quotation marks): "U.S. Department of State Student Internship Program (Unpaid) - Thanks for your application"

Each email sent will have URL parameters attached:
Opportunity 1, 2, and 3 should all have url parameter links that redirect to the specific opportunity with identifiable information. e.g. usajobs.gov/opportunity1/DoS_Application_Email
There should be url parameters tying the Help Center page to this specific template. When reviewing the URL it should be clearly marked with identifiable information e.g. usajobs.gov/help_center/DoS_Application_Email (ultimately up to the technical team)
Each email sent during the Applicant Review phase will be embedded with the following, dynamic and static, string with pieces updated by the software (outlined below). GA refers to "Google Analytics":
<img src="https://www.google-analytics.com/collect?v=1&tid=UA-33523145-1&cid=555&t=event&ec=email&ea=open&el=Agency_Talent_Portal_[DYNAMIC_VALUE]">
These items below are elements of the URL above:
collect - simply notifies GA to collect (static)
tid - our unique id for our GA account for our Government wide account (static)
cid - the client id of the person who click on the email. It is currently set to be anonymous (static)
t - the type which is an event in this case (static)
ec - event category which is email in this case (static)
ea - event action which is open in this case (static)
el - event label which should be the corresponding step in the Applicant Review process with the prefix of Agency_Talent_Portal_(Static) Applicant Review Step(dynamic)

Replaces TFS ticket: [https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/36386]

**Comment by KatMullens-work** [comment]
Hey @Piglady64 - are you guys going to do this one still?

**Comment by Piglady64** [comment]
@KatMullens-work We have an email that is sent to the applicant from OO. It is going to be done this sprint. I am not sure why this ticket was created for ATP, the student doesn't go into ATP.

**Comment by KatMullens-work** [comment]
Hi @Piglady64 - I don't remember at this point why we put it here but there was a reason :/ I'll close this if it's covered!

**Comment by Piglady64** [comment]
We have this ticket in the next sprint and I think this is the same thing: https://github.com/openopps/openopps-platform/issues/3098

**Comment by KatMullens-work** [comment]
Excellent! Closing this ticket.
