### ISSUE TITLE
Apply to federal opportunity

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#3042]
There currently exist a typo in the apply functionality for federal opportunities preventing users from applying to opportunities.

**Comment by bmcorum** [comment]
@Kibrahacha67 can you please test the ability to apply to an opportunity in UAT?

**Comment by Kibrahacha67** [comment]
2-21-19 Lhammond in testing

**Comment by kbwagner** [comment]
2/21/19 - KWagner
- Tested as kbwagner non admin in UAT Chrome - applied successfully to two opportunities
- Tested as Katrina Wagner admin in UAT/Safari/mobile - applied successfully
- Tested as Katrina Wagner admin in UAT/IE - applied successfully

Ready for final review.
