### ISSUE TITLE
Add new fields for ATP to the Cycle date table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3048]
Who: Community managers
What: Additional information on cycle table
Why: in order to provide necessary data to ATP

Acceptance Criteria:
In order for ATP to be able to close opportunities, they would like for Open Opps to house additional dates for the community cycle:
- Hiring manager review start date and Hiring manager review end date (required)
- Secondary application link*: i.e., USAJOBS exclusive posting link (this will go here instead of the community attribute table since there will be a new exclusive posting every cycle) (optional)

Note: 
- ATP will pull this information over in their API process

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
@bmcorum please add a artifact for the table...ty

**Comment by Piglady64** [comment]
Julie reviewed - moving to final approval
