### ISSUE TITLE
Department of State: Add messaging when student edits application

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3049]
Who: Student
What: Provide a message when an application is changed after it is submitted.
Why: We need to make it clear that the student will need to "submit" the application again once it has been edited. 

A/C
- When the user clicks the "update" link associated with their application in  their dashboard they will see a modal with the following message

You are about to make edits to an application you have already submitted. Follow these steps to resubmit your application:
1. Go to the page you want to edit by using the progress bar at the top of the page or by clicking the **Save and Continue** button on each page.
2. Click **Save and Continue** once you make your change.
3; Click **Save and Continue** on all of the pages following the page you edited (you don't have to **Save and Continue** on any previous pages)
4.  Review your application and click **Submit application**.

- The modal will follow the design system
 
(no mock included)

**Comment by Piglady64** [comment]
Sent the following content to @dalenard21 for review.

You are about to make edits to an application you have previously submitted. After you make your changes, you will need to go to the “Statement of Interest” page and click the “Save and continue” button. You will then be sent to the “Review” page where you can review your application and click the “Submit application” button.

**Comment by dalenard21** [comment]
@Piglady64 

Do you think we should put these into steps?  Here's a revised message:

You are about to make edits to an application you have already submitted. After you make your edits, you need to follow these steps to resubmit your application:

1. Go to the **Statement of Interest** page.
2. Click **Save and Continue**—you will then go to the **Review** page.
2. Review your application and click **Submit application**.

**Comment by Piglady64** [comment]
@dalenard21 I was thinking the same thing this weekend. I am also having Devs add a step 6 on the progress bar so the student can skip to the review page to click submit and won't have to go to each page or to step 5 and then "Save and continue" to get to the button. I will update this message and get it back to you for review soon.

**Comment by Piglady64** [comment]
@dalenard21  I have modified this content to match the change I made to the progress bar. They are going to add a 6 (Review Application) so the user can go directly to the "Review" page. Let me know what you think. 

You are about to make edits to an application you have already submitted. Follow these steps to resubmit your application:

1)  Click **Save and Continue**— on each page where you have made changes.
2)  When you have made all of your changes click on the 6 (Review Application) in the progress bar at the top of the page.
3) Review your application and click **Submit application**.

**Comment by dalenard21** [comment]
@Piglady64 

I have a couple of suggestions  - For 1 - just remove the "-".  For 2 - I put the action first to keep parallel structure. I think it still makes sense.

1. Click **Save and Continue** on each page where you have made changes. (just remove the -)
2. Click **6 (Review Application)** at the top of the page, when you are done with your changes.
3. Review your application and click Submit application.

**Comment by Piglady64** [comment]
@dalenard21 Thanks I will add this language

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/14/19 - Mdumas - in testing...

**Comment by Piglady64** [comment]
I have returned this ticket to development because when we discussed the way the progress bar would work these instructions changed.  Sorry for the extra work.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-19-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@Piglady64 - Question, is the text in the AC correct or are we going by the text at the end of the string of comments with dalenard21?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/19/19 - Mdumas - In testing....

**Comment by Piglady64** [comment]
thank you for making this change so quickly. I have reviewed this and moving it to Final Approval
