### ISSUE TITLE
Remove Go to Saved from Create Internship Opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3058]
Who: Interns
What: Viewing internship - should not see Saved internships section
Why: Old design

Remove the Saved internships section from the Create internship opportunity view.  This was part of an old mock up and was removed.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/f0aacb1e-32af-4600-a317-1af28939cf31)

Mock:
https://opm.invisionapp.com/share/ZEPNZR09Q54#/320303454_State_-_Opportunity_-Desktop-

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-13-19 LHammond in testing

**Comment by kbwagner** [comment]
3/13/19 - Kwagner Chrome/Test
- Go to saved has been removed
@abudz19 this was one of yours if you want to take a look
