### ISSUE TITLE
Update Before you apply text on applicant view of internship opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3059]
Who: Interns
What: Viewing of the community name
Why: State has requested all references to their program be U.S. Department of State Unpaid Internship Program (Unpaid)

Acceptance Criteria:
On the applicant view of the internship, update the text in the Before you apply box to reflect the full program name
- Current text reads, "To apply to the unpaid internship student program..."
- Text should now read, "To apply to the U.S. Department of State Student Internship Program (Unpaid), you must...."

Mock: 
https://opm.invisionapp.com/share/ZEPNZR09Q54#/320303454_State_-_Opportunity_-Desktop-

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-12-19 LHammond in testing
Test completed moving to review.

**Comment by kbwagner** [comment]
3/20/10 - Kwagner tested Chrome/Test environment
Ready for final review
