### ISSUE TITLE
Internship Opportunity - update description under logo

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3060]
Who: Internship viewers
What: View U.S. in front of Dept of State
Why: State has requested we always display U.S. in front of their program name.

Acceptance Criteria:
The text under the logo on all views of the internship opportunity (creator view and applicant) should be updated to read, "U.S. Department of State"

Mock: 
https://opm.invisionapp.com/share/ZEPNZR09Q54#/320303454_State_-_Opportunity_-Desktop-

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-13-19 LHammond in testing
tested in chrome, ie and edge, moving to review.

**Comment by kbwagner** [comment]
3/13/19 - KWagner Test/Chrome
- Duplicated an opportunity and clicked Preview - the logo title doesn't include U.S.
- Moving back to development.


![image](https://user-images.githubusercontent.com/18709918/54306622-276c3e80-45a0-11e9-8f34-7c192be5c97b.png)

**Comment by Kibrahacha67** [comment]
@kbwagner good catch I am adding a test case for that one...

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-18-19 LHammond in testing.

**Comment by kbwagner** [comment]
3/18/19 - KWagner reviewed in Chrome/Test environment.
Ready for final review.
