### ISSUE TITLE
Align skills left under Desired Skills header

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3061]
Issue: The first skill that displays on the internship opportunity displays slightly indented from the Desired skills header
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/2ce1c248-0d9b-4fad-ae99-beaccbaa1f96)

Solution:
On all views of the internship opportunity, align the first displayed skill left to start with the header.  

Mock: 
https://opm.invisionapp.com/share/ZEPNZR09Q54#/320303454_State_-_Opportunity_-Desktop-

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/11/19 - Mdumas - testing...

**Comment by margaretdumas** [comment]
Passed testing, moving to review.

**Comment by kbwagner** [comment]
KWagner tested in Chrome/Test environment.  Ready for final review.

@abudz19 one for you to take a look - this is one of the issues you had found.

**Comment by abudz19** [comment]
@kbwagner Looks good.
