### ISSUE TITLE
Bug: unable to add skills on profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3066]
Environment: Test (works in UAT currently)

Issue:
When an Open Opps user does not have any skills attached to their profile, the Add button is not displaying

Screen shot of profile with no current skills: 
![image 13](https://user-images.githubusercontent.com/18709918/53509223-628f4d80-3a89-11e9-9bc5-7722ba11ebf0.png)

Resolution:
When there are no skills on a profile, an add button should display on the profile page
Mock: https://opm.invisionapp.com/share/MVNQNEQ89NR#/313411848_OO-Profile-Fed_-desktop-https://opm.invisionapp.com/share/MCP5BZ0P967#/340559304_v5_-_Explict_Separation

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/11/19- mdumas - testing....

**Comment by margaretdumas** [comment]
Mdumas - passed testing. Moving to review.

**Comment by kbwagner** [comment]
KWagner tested in Chrome/Test - ready for final review.

**Comment by abudz19** [comment]
@kbwagner I add skills but they won't save.
