### ISSUE TITLE
Prevent a student from being added to a student based community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3083]
Who: Students
What: student based communities
Why: In order to maintain the integrity of the system

Acceptance criteria:
- currently a student can be added to a student based community which would then allow them to create internships, etc.
- For a community that has a target audience of "Student", prevent accounts that have a hiring path of "student" from being assigned as a community member
- On the community admin --> Add members to a community piece, do not include student accounts in the search (note - my student account didn't show up when I typed in my name but did show up when I typed in my email).

**Comment by bmcorum** [comment]
@kbwagner I believe this may already be in effect now, however there is one question that remains.

1. I am currently a federal or contract employee
2. I join/added to a community
3. I change to a student only account

Should I automatically be removed from all communities?

**Comment by kbwagner** [comment]
2/4/2020 - KWagner tested this in the test environment and this is no longer an issue.  We have another ticket about allowing someone to be in multiple hiring paths so this can be closed.
