### ISSUE TITLE
Delete Confirmation Does not display in red as per Design System

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#3086]
The delete confirmation message box does not display in red as per the design system standards.  

Steps to reproduce:
1.  Sign into Open Opps with the delete permissions
2.  Navigate to opportunities 
3.  Select and opportunity that has been submitted
4.  Click the "Delete" option

Results:  A delete confirmation message is displayed.  See below.

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/0af330b7-9b43-4a75-adf3-76e15e190a00)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
6/18/19 - KWagner tested
moving to final review.
