### ISSUE TITLE
Allow for ability for an student to withdraw their application once completed

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3087]
Who: Intern Applicants
What: Ability to withdraw an application
Why: To allow applicants to withdraw their application from within Open Opportunities

Acceptance Criteria: 
- Students can withdraw an application only while the internship is open for applicants.  When the apply end date has passed, the withdraw option should not be available.
- From the landing page Applied section, when the intern clicks on the link in the Program column, they will be taken to the Submitted application page where they see the Submitted application section
- The header reads, "Submitted application"
- The text under the header reads, "You have submitted the following application to the community name for cycle name.
- There will be two buttons: Update and Withdraw
- Update will be handled with ticket 3231
- Withdraw is handled with ticket 3087

When the withdraw button is selected, a modal displays:
- Header: Withdraw application
- Subheader: Confirm withdrawal of this application
- Text:
Are you sure you want to withdraw from the community name for cycle name?  This action cannot be undone.

Want to keep your application, but choose another internship opportunity?
1. Close this window or choose **Cancel**.
2. Choose Update (bold).
3. Search for a new internship opportunity - you'll need to delete one of your selected internships to replace it with a new one.
4. Make sure to save and re-submit your application.

The modal will have Cancel and Withdraw buttons.
- Cancel will close the modal and return the applicant to the Submitted application page
- The "X" in the top right of the modal will act as a cancel
- Withdraw will close the modal and return the applicant to their signed in landing page.
- There will be an alert message at the top of the page that reads, "Application withdrawn  You have successfully withdrawn your application from the community name for cycle name."
- In the applied section, the application will no longer display
- The applicant will receive an email confirmation that their application has been withdrawn. This is covered in ticket 3100

Open Questions: 
- what if my application is in progress but not submitted?  Can I withdraw?
- what about other places I can update?

Design: 
https://opm.invisionapp.com/d/main#/console/15360465/352514658/preview
This includes updates to the Signed in landing page, a new view for students to update or withdraw, modals, and is wired up if you want to go through the experience.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-17-19 LHammond in testing

**Comment by Piglady64** [comment]
returning to development- # 3 has a content error. 
Search for a new internship opportunity &emdash; you'll need to delete one of your selected internships to replace it with a new one.

should be: Search for a new internship opportunity - you'll need to delete one of your selected internships to replace it with a new one.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - Ooops , I Added a comment to wrong ticket.  Removing comment and testing...

**Comment by margaretdumas** [comment]
4/22/19 Mdumas - moving to review

**Comment by Piglady64** [comment]
Julie reviewed and correction has been made - moving to final review
