### ISSUE TITLE
Bug: Create internship button runs off screen on mobile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3091]
Environment: Test
Mobile/iPhone/Safari

Steps to Recreate: 
1) Log on to openopps.test.usajobs.gov on a mobile device as a user who is a member of a student community who can create internships
2) The Create internship button displays off the screen

![IMG_5352 mobile bug.PNG](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/a00784fd-f609-43d8-a5ae-0f093248e622)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/5/19 - Mdumas - Tested button looks good on mobile. Tested on iphone. moving on to review.

**Comment by kbwagner** [comment]
3/6/19 - Kwagner - tested on iphone Safari and button is good.
Ready for final review.
