### ISSUE TITLE
Internship Emails: Turn off emails that don't apply

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3092]
Who: Anyone
What:
Why:

Note: There are only certain emails that need to be sent out for DoS. Example: The community manager and Hiring manager don't want an email every time a student applies to their opportunity.  There are only a few emails that they want sent.

**Comment by Piglady64** [comment]
@bmcorum Can I close this ticket? I thought we talked about this and decided we didn't need to identify which emails not to use as long as we had requirements for when to send the new ones for DoS.

**Comment by kbwagner** [comment]
@bmcorum following up on this - should we close this ticket?  Or do we need to spell out any emails to turn off?

**Comment by bmcorum** [comment]
@kbwagner their isn't really a **on** or **off**. Emails are sent based on a defined action so for students/internships if we have not defined an action then no email will get sent.

**Comment by kbwagner** [comment]
Ok so sounds like we can close this ticket @bmcorum @Piglady64
