### ISSUE TITLE
Internship Email: Draft internship opportunity created

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3093]
Who: Internship Opportunity Creator
What: Email to let them know they have created an internship
Why: As an internship opportunity creator I want to know that my draft has been saved and how to get back to it so I can finish it.

A/C

Title of Email**: Draft internship opportunity created
**Subject**: New internship opportunity draft created
**Trigger**: When the internship creator saves an internship as a draft
**Audience**: Internship opportunity creator

- Insert the following content into the U.S. Department of State Student Internship Program (Unpaid) community email template #3397

**Content**: 
Hello [Internship opportunity creator name],
Thank you for drafting an internship opportunity.
Your draft can be found on your [dashboard](link to creator’s dashboard). 
For your reference, here's a link to the internship opportunity: [insert opportunity name link] 
Reminder: You must submit this opportunity for approval by [insert create internship end date].
Thanks,
The Open Opportunities Team

-The email will come from no-reply@openopps.usajobs.gov 
- This email will be responsive
  - Design teams definition of responsive : Responsive, in any context, be it email or browser, does mean responding to the viewport size (which is roughly equivalent to screen size; it's the width of the browser or email reader). These particular emails can be responsive because they include HTML, with a fallback to text for email readers that don't support HTML.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-23-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed - Moving to Final Approval
