### ISSUE TITLE
Internship Emails: New Internship Opportunity submitted

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3094]
Who: Opportunity Creator
What: Submitted internship email
Why: As a internship opportunity creator I want to know that my internship opportunity has been submitted. 

A/C
**Subject**: New internship opportunity submitted
**Trigger**: When bureau internship coordinator submits internship for approval
**Audience:** Internship opportunity creator 

- Insert the following content into the U.S. Department of State Student Internship Program (Unpaid) community email template #3397 

**Content**: 
Hello [Internship opportunity creator name],
Thanks for submitting [Internship opportunity name link] with the U.S. Department of State Student Internship Program (Unpaid). The community manager will review your submission. You will receive an email when it’s approved or if they need additional information. 

Thanks,
The Open Opportunities Team

You have received this message because you have submitted an internship opportunity through Open Opportunities.

- The email will come from noreply@openopps.usajobs.gov 

- This email will be responsive
   - Design teams definition of responsive : Responsive, in any context, be it email or browser, does mean responding to the viewport size (which is roughly equivalent to screen size; it's the width of the browser or email reader). These particular emails can be responsive because they include HTML, with a fallback to text for email readers that don't support HTML.

**Comment by raywilliams** [comment]
@Piglady64 The email will come from noreply@openopps.usajobs.gov instead of no-reply@openopps.usajobs.gov. Will you please update the A/C? Thank you!

**Comment by Piglady64** [comment]
@raywilliams Done

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-23-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie- I received the email and it looks good - moving to final approval
