### ISSUE TITLE
Internship Email: Internship approved

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3095]
Who: Hiring Manger
What: Email to let me know my internship has been approved
Why: As a hiring manager I would like to be notified that my community manager has approved my internship

A/C: 
-The email will come from no-reply@openopps.usajobs.gov 

- This email will be responsive
  - Design teams definition of responsive : Responsive, in any context, be it email or browser, does mean responding to the viewport size (which is roughly equivalent to screen size; it's the width of the browser or email reader). These particular emails can be responsive because they include HTML, with a fallback to text for email readers that don't support HTML.

**Subject**: Your internship opportunity is approved 
**Trigger**: When community manager approves an internship
**Audience**: Internship opportunity creator

- Insert the following content into the U.S. Department of State Student Internship Program (Unpaid) community email template #3397

**Content**: 
Hello [Internship opportunity creator name],
Your internship opportunity has been approved, [Opportunity name link].  The internship will be posted for applicants to apply on [insert application start date]. 

Thanks,
The Open Opportunities Team

**Comment by Piglady64** [comment]
@kbwagner This looks like a duplicate

**Comment by kbwagner** [comment]
@piglady64 if there is another ticket for approved than yes this can be closed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-23-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed - Looks good - Moving to final approval
