### ISSUE TITLE
Internship Email: Internship submitted to community manager for approval

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3096]
Who: Community Manager
What: Email to let them know an internship has been submitted
Why: As a community manager I would like to be notified that an internship opportunity has been submitted for my approval.

A/C: 
-The email will come from noreply@openopps.usajobs.gov 

- This email will be responsive
  - Design teams definition of responsive : Responsive, in any context, be it email or browser, does mean responding to the viewport size (which is roughly equivalent to screen size; it's the width of the browser or email reader). These particular emails can be responsive because they include HTML, with a fallback to text for email readers that don't support HTML.

**Subject**: New internship opportunity submitted 
**Trigger**: When a hiring manager submits an internship opportunity for approval
**Audience**: Community manager 

- Insert the following content into the U.S. Department of State Student Internship Program (Unpaid) community email template #3397

**Content**: 
Hello [Community manager name],
[Internship Opportunity creator name] has submitted a new internship opportunity for your review: [Insert link to submitted internship opportunity]
Please review this and either approve or ask for more information if it’s needed. This internship opportunity will be available to applicants starting [insert application start date].

Thanks,
The Open Opportunities Team

**Comment by Piglady64** [comment]
@kbwagner I don't know what this is. I have created a ticket for "Internship Submitted" and one for "Share" this looks like a combination of both. Please give more details

**Comment by kbwagner** [comment]
@piglady64 this would be for just internship submitted and the text of the shell was just copied from a different ticket and should be ignored  But if you already created a ticket for internship submitted this can be closed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-23-19 LHammnond in testing

**Comment by kbwagner** [comment]
<img width="1440" alt="Screen Shot 2019-04-24 at 3 33 28 PM" src="https://user-images.githubusercontent.com/18709918/56688430-b479db80-66a6-11e9-8833-4101bc4fa45c.png">

@raywilliams - the email I got for this has an apply start date of 4/17 but the cycle says 4/16.  But...I know there were some questions on the time zones.  Thoughts?

**Comment by Piglady64** [comment]
Julie- The dates on my email are correct-
