### ISSUE TITLE
Student Account - Edit at USAJOBS button covers the username on mobile

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#3097]
The "Edit at USAJOBS" button covers the username on the profile page of a student account.

Steps to reproduce:
1.	Sign into a student account
2.	Navigate to profile

Results:  The username is covered up by the “Edit at USAJOBS” button.

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/edaa1854-c528-4829-a860-6c8f7870c026)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
06/17/19 - Mdumas - Passed testing, moving to review.

**Comment by kbwagner** [comment]
6/18/19 - KWagner tested mobile Safari test environment
Resolved and moving to final review.
