### ISSUE TITLE
Internship email: Application received

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3098]
Who: Student
What: Email to tell the student that their application has been received
Why: As a student I want to know that my application has been received

A/C
Subject:– Thank you for your application to the U.S. Department of State Student Internship Program (Unpaid)
Trigger: Student applies to an internship opportunity
Audience: Applicant/Student

- Insert the following content into the U.S. Department of State Student Internship Program (Unpaid) community email template #3397

Content: 
Hello [User name],
Thank you for submitting your application to the U.S. Department of State Student Internship Program (Unpaid) through Open Opportunities. You applied to the following internship opportunities:

[Insert internship opportunity 1] (Link to opportunity detail page)

[Insert internship opportunity 2] (Link to opportunity detail page)

[Insert internship opportunity 3] (Link to opportunity detail page)

View your application in your dashboard [insert link to student’s dashboard].

What happens next? (this is a header )
The U.S. Department of State Student Internship Program will:
1.	Review all applications. (bold)
They will begin to review applications after the application period closes on [insert application closing date].  
2.	Set up interviews. (bold)
They will contact you if you’re selected for an interview.  However, some offices don’t conduct interviews.
3.	Send offer emails. (bold)
They will send you an email with a conditional offer, if you’re selected for an internship.

What happens if I’m not selected? (this is a header)

 After all internships are filled, you will receive an email if you’re not selected. 
[Learn more about the U.S. Department of State Student Internship Program (Unpaid) selection process](https://careers.state.gov/intern/student-internships/selection-process/).

Thanks,
The Open Opportunities Team

-The email will come from noreply@openopps.usajobs.gov 
- This email will be responsive
  - Design teams definition of responsive : Responsive, in any context, be it email or browser, does mean responding to the viewport size (which is roughly equivalent to screen size; it's the width of the browser or email reader). These particular emails can be responsive because they include HTML, with a fallback to text for email readers that don't support HTML.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed - the last line should read 
Thanks, 
The Open Opportunities Team

Not the Open Opportunities Test Team

**Comment by Kibrahacha67** [comment]
@Piglady64 pretty sure that is the variable the identifies the test region.  So as it moves through it will be ok...but dev team can confirm as it is on all emails sent in test environment

**Comment by raywilliams** [comment]
@Piglady64 That's there from a variable used to identify the environment, in this case the Test environment. It will not be there in production.
@Kibrahacha67 I'll move this back to Review.

**Comment by Piglady64** [comment]
@Kibrahacha67 Ok I will move this to final approval
