### ISSUE TITLE
Internship email: Share internship opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3099]
Who: Student 
What: Email that someone has shared and internship with me
Why: As a student I would like to know if someone shares an internship opportunity with me.

A/C
- This email will work like the "share" in USAJOBS
   - We will send content to the users email client (I think this is the right term)

Trigger: User clicks on “Share” icon when viewing an opportunity
Audience: Anyone

Subject: Take a look at this internship opportunity

Content:
 I thought you might be interested in this internship opportunity.  Find out more: [link to the internship opportunity detail page].

 
.

**Comment by bmcorum** [comment]
@Piglady64 why would this not work the same way the share works for federal employees and federal opportunities where we use the default email client on the user's machine and we auto populate the subject and some basic message content? We basically just help the user get the email started and they send the email using their email provider.

**Comment by Piglady64** [comment]
@bmcorum Debbie gave me this content so I am not sure she knew how we currently did this. Can we customize the text  with the content above?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
04/22/19 - Mdumas - Tested...moving to review.

**Comment by Piglady64** [comment]
Julie shared an internship opportunity with herself using her gmail to send to hotmail. Everything worked and email looks good

moving to final approval
