### ISSUE TITLE
Internship email: Withdraw application confirmation

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3100]
Who: student
What: email to let me know that I have successfully withdrawn my application
Why: As an applicant I would like to be notified that I have successfully withdrawn my application

A/C
-The email will come from noreply@openopps.usajobs.gov 

- This email will be responsive
  - Design teams definition of responsive : Responsive, in any context, be it email or browser, does mean responding to the viewport size (which is roughly equivalent to screen size; it's the width of the browser or email reader). These particular emails can be responsive because they include HTML, with a fallback to text for email readers that don't support HTML.
-The header will be the current "Open Opportunities" branding

**Subject**: U.S. Department of State Student Internship Program (Unpaid) – Application withdrawn

**Trigger**: Applicant selects “Withdraw” on an opportunity they have applied for

**Audience**: Applicant/Student

- Insert the following content into the U.S. Department of State Student Internship Program (Unpaid) community email template #3397

**Content**:
Dear [Applicant Name],
You have successfully withdrawn your application with the U.S. Department of State Student Internship Program (Unpaid) for the following internships:
[Insert internship opportunity 1] (Link to opportunity detail page)
[Insert internship opportunity 2] (Link to opportunity detail page)
[Insert internship opportunity 3] (Link to opportunity detail page)

Thanks,
The Open Opportunities Team

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-26-19 LHammond in testing

**Comment by tanichacko** [comment]
@Piglady64  can you update the AC  in **content section** from U.S. Department of State Student Internship Program **(unpaid)** to U.S. Department of State Student Internship Program **(Unpaid)**?

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-26-19 LHammond in testing

**Comment by Piglady64** [comment]
Email is correct - Julie updated the capitalization error in the A/C- Moving to final approval
