### ISSUE TITLE
Remove unused statuses from Student Community Manager Dashboard

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3102]
Who: Community Administrators
What: Remove statuses not used for internships
Why: To avoid confusion

Acceptance Criteria: 
- The community manager page displays statuses that will not be used for Internships.  

For the unpaid internship community only, remove the following from Community Admin --> Opportunity --> Manage:
- In progress
- Canceled

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-1-19 LHammond in testing

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test
Ready for final review
