### ISSUE TITLE
Bug: Newly created community opportunities are not displaying in search

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3105]
Environment: UAT

Steps to recreate:
1) Created an account with community manager access for FAI (no sitewide or agency admin)
2) Created an opportunity with a sitewide admin account.
3) Logged in as community manager account and approved the opportunity
- Opportunity shows as open but does not display when signed out or signed in as the community admin.  Only displays when signed in as sitewide admin.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - passed testing. Moving to review.

**Comment by kbwagner** [comment]
3/6/19 - Chrome/UAT  created an FAI community opportunity.  Displayed on regular search, acquisition search and when logged out.

Moving to final review.
