### ISSUE TITLE
Bug: User .csv file times out

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3109]
Environment: Production

Steps to replicate:
1) Sign in as a system admin 
2) Go to Administration --> Users --> Manage run .csv
- File times out

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

Also here is an artifact showing the download of each user export and the time each took.
- All users took 346 milliseconds (0.346 seconds)
- OPM agency users took 142 milliseconds (0.142 seconds)
- FAI community took 153 milliseconds (0.153 seconds)

![image](https://user-images.githubusercontent.com/1165615/53828149-dd091300-3f4a-11e9-9285-40f3a89d0449.png)

**Comment by margaretdumas** [comment]
Mdumas - Tested all .csv file downloads.  Moving on to review.

**Comment by kbwagner** [comment]
3/6/19 - KWagner - tested .csv in UAT and reviewed artifacts.
Ready for final review.

**Comment by bmcorum** [comment]
Tested after production deployment. Download took 576 milliseconds

![image](https://user-images.githubusercontent.com/1165615/54027171-85e38800-416e-11e9-9713-edb53acd52bc.png)
