### ISSUE TITLE
Opportunity .csv 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3122]
The Opportunity .csv queries need to be rewritten to run efficiently and quickly.  
Bug 3109 resolved the issue for the user.csv

**Comment by bmcorum** [comment]
Export takes 1.02 seconds to compile and export.

![image](https://user-images.githubusercontent.com/1165615/60095427-85bac880-971c-11e9-94e0-b0b9f4ec7297.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19 LHammond in testing

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Test/Chrome. 
Ready for final review.
