### ISSUE TITLE
Remove password reset option for all admins with login.gov implementation

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3132]
Who: Administrators
What: Ability to reset passwords
Why: Will go away with login.gov

Acceptance Criteria:
- Remove the ability to reset a password on the Admin dashboard for both Sitewide and Agency administrators
Administration --> Sitewide/Agency --> Users --> Manager Users
- Remove "Reset Password"

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing
