### ISSUE TITLE
Search: Remove program area - default to Unpaid

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3138]
Who:Internship search page
What:  Default to unpaid
Why: VSFS will not likely go live until 2020

Until VSFS goes live, likely in 2020, we need to remove the Program Area section of the search filters and default to the U.S. Department of State Student internship program (unpaid) program.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-13-19 LHammond in testing

**Comment by kbwagner** [comment]
3/13/19 - KWagner tested Chrome/Test
- Ready for final review.
