### ISSUE TITLE
The top Nav is missing when you Edit/Add Skills to your Profile

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#3151]
Steps to reproduce:

1.  Sign into your account
2.  Click on profile
3.  Edit or Add skills

Results:  You are on the edit skills page but the top nav with your username etc is missing.  

Note*  This is in production and test environment.

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/cf1e9ecb-4c62-4c5e-b06c-afab0ec774cc)

**Comment by Kibrahacha67** [comment]
6-11-19 LHammond This has been fixed with another ticket, moving to review.

**Comment by kbwagner** [comment]
6/11/19 - KWagner tested in Chrome/Test - this is resolved
Ready for final review.
