### ISSUE TITLE
Department of State: Link in Submission Confirmation should open in a new window

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3153]
Who: Student
What: Link to FAQs about security clearance process link should open in a new window
Why: As a student I want to be able to easily get back to my application after reviewing the FAQs

A/C
When the user clicks the link in the message below for the FAQs it should open in a new window.

"We recommend you don't make any travel or housing plans until you receive your security clearance. Read our FAQs about the security clearance process (this is a link will go to https://careers.state.gov/intern/student-internships/selection-process/#expandfaq)"

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/14/19 - Mdumas - testing...

**Comment by Piglady64** [comment]
3/15/19 Passed Review moved to final approval
