### ISSUE TITLE
Bug: Duplicate process for internships doesn't copy over bureau or office/post

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3165]
Environment: Test

Steps to replicate:
1) As an System Admin or Community Admin, click on an internship opportunity
2) Select duplicate
- Bureau and then office/post do not copy over

Resolution:
- Bureau and office/post should be part of the duplicate process

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-18-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 safari had an issue or mobile safari?

**Comment by Kibrahacha67** [comment]
Mobile Safari

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-19-19 LHammond in testing.

**Comment by Kibrahacha67** [comment]
3-19-19 LHammond in testing

**Comment by kbwagner** [comment]
3/20/19 - KWagner tested in Chrome/Test environment
Ready for final review.
