### ISSUE TITLE
Department of State: Experience Questions- Add character limit 

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3177]
Who: Student
What:Character Account
Why: As an applicant I would like to know the character limit to a text box

A/C
- On the Experience & References Page Under the "Other" selection 
  - the "If you chose "other", please specify - provide a character limit (250 characters remaining)
  - Please indicate the total length of your overseas experience(s) provide a character limit (250 characters remaining)
- The character limit will change as the user types in the box and reflect the number of remaining characters.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
3/25/19 - Mdumas- Passed testing . Moving on to review

**Comment by Piglady64** [comment]
Julie reviewed, moving to final approval

**Comment by tlorrison** [comment]
Not approved - character count remaining is not updating as I type in the box (in Chrome)

**Comment by raywilliams** [comment]
@tlorrison  Will you please try again? I've tried in TEST and it updates, and had someone else try and it updated for them as well. If it still doesn't update for you, will you please let me know the steps you are taking so I can troubleshoot the issue?

**Comment by Piglady64** [comment]
@raywilliams @bmcorum @tlorrison  I am having the same problem in Chrome 

![image](https://user-images.githubusercontent.com/15252970/56431160-dd5d3380-6296-11e9-9667-27e6f85c29c2.png)
