### ISSUE TITLE
Bug: Firefox login takes you to USAJOBS (Test environment)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3180]
Environment: Test
Browser: Firefox

Issue: 
there seems to be a login issue in Firefox.  
1) Go to openopps.test.usajobs.gov, 
2) click on sign in, takes you to the https://login.test.usajobs.gov/Transition, 
3) when you click "sign in" it takes you directly to https://www.test.usajobs.gov/ and not to the login.gov sign in page
test.usajobs.gov
USAJOBS - The Federal Government's official employment site
Search and apply for federal jobs. Learn about unique hiring paths for veterans, students and graduates, individuals with a disability, and more.

Dan Thibodeau [11:47 AM]
@kbwagner looks like you guys are pointing the Continue and Sign in buttons to the old USAJOBS transition page, which we likely have a redirect set up since that page is no longer valid, so I'm assuming Firefox isn't doing the second redirect...but hopefully someone more technical can make that answer make more sense, or at least be valid :slightly_smiling_face:
actually, it looks like it just points to the same page since that doesn't have open opps in the URL, so not sure now

**Comment by bmcorum** [comment]
@kbwagner this is not something that can be fixed from the Open Opportunities code base. This is all configured and handled by the USAJOBS code base specifically the login project.

**Comment by kbwagner** [comment]
Closing as this is a USAJOBS issue

John Still [2:25 PM]
This is ticket 36778 Login issue in Firfox
