### ISSUE TITLE
Admin Dashboards: Display federal email 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3182]
Who: All administrators
What: Email view
Why: In order to alleviate confusion

Acceptance Criteria:
Currently we are displaying the user's login.gov account in the admin dashboards. Their profile, however, displays their official government email address from USAJOBS.  In addition, we are showing the federal email address in the add members to the community feature.  We should display consistently.

Solution: Display the federal government email address on the administrator dashboards

1) Sitewide Admin --> Users --> Manage
- Change current "Email" header to "Login.gov email" and display the email that currently displays that is connected to their login.gov account
- Add a new column to the left of Login.gov email for "Federal email" that displays their official government email address.
- It will be helpful to have this email for sitewide admin troubleshooting

2) Agency  Admin: users --> Manage
- Change current email header to "Federal email" and display their official government email address

3) Community Admin: Users --> Manage
- Change current email header to "Federal email" and display their official government email address
- The Add feature currently uses federal email address in the search.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-7-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
@margaretdumas @Kibrahacha67 I was peeking at this one since I was testing something else in admin and the agency and community tabs have the right header for federal email address but are showing gmails and other things - so what they are currently using for their Open Opps login vs the federal email address.  I could be missing something of course!

**Comment by Kibrahacha67** [comment]
@kbwagner you will see gmail as the test system will allow, but in production you should only see fed email address as it will NOT allow anything other then gov email.  Open opps originally allowed any email address so there will be some adjustment as that functionality goes out. So not sure how the program office is going to reign that in...

**Comment by Kibrahacha67** [comment]
5-9-19 LHammond in testing
Testing completed in uat as bot test and uat have the same code base.  moving to review.

**Comment by kbwagner** [comment]
5/9/19 - KWagner tested in Chrome/Test
- non federal email addresses show but according to notes above will not be an issue in production

Ready for final review.
