### ISSUE TITLE
Bug: Bureau/Office/Post filters no longer displaying

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3183]
Environment: Test
Browser: All

Issue: 
Bureau/Office/Post are not displaying for internship search

Steps to recreate:
Search --> Internships
Filters for Unpaid should display Bureau/Office/Post filters as originally intended for unpaid interns. 
-Office/post will not become enabled until a bureau is selected

Original Tickets: 
Office/Post filter: https://github.com/openopps/openopps-platform/issues/2711
Bureau filter: https://github.com/openopps/openopps-platform/issues/2710

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in testing

**Comment by kbwagner** [comment]
3/20/19 - KWagner tested Chrome (Test environment) and Mobile Safari.
- Filters appear again

Ready for final review.
