### ISSUE TITLE
Bug: Skills pills sometimes run into duplicate on Create Internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3186]
Environment: Test

Issue:
-  When viewing an opportunity as an applicant or in create mode, sometimes the skills pills will overlap into the duplicate link.

Resolution:
- Skills should wrap to not run into duplicate

Note: This does not occur all the time or on all computers.
Screen Shot 1: Reduced from full screen and skills overlapped into duplicate
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/792dc36a-0209-4c4f-8b45-8f57a8c6a400)

Screen shot 2: This one was on a full screen in Chrome.  One computer it was fine and the other displayed like this: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/aaa30a91-49c6-420d-b0db-03c59c7d515e)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in testing
