### ISSUE TITLE
Office/post field data should display in alpha order

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3204]
Who: Internship hiring managers
What: office post data should display in alpha order
Why: for ease of the manager finding the correct data

Acceptance Criteria:
On the Create internship opportunity, the Office/post data should display in alphabetical order.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
05/3/19 Mdumas - Testing...

**Comment by margaretdumas** [comment]
@kbwagner @tanichacko When we are doing the alphabetical ordering, are we going to over look words like "of the" or should they be included in the order.  If I'm not mistaken USAJOBS overlooks "of the" etc.

![image](https://user-images.githubusercontent.com/19936109/57153841-4d92ab80-6da5-11e9-92e6-2cdf8145158f.png)

**Comment by bmcorum** [comment]
@kbwagner and @margaretdumas that would require we build our own custom alphabetic comparison library rather than using what is already built into EVERY computer systems on the face of the planet. I checked USAJOBS and found an agency listing where words like 'the' and 'of' are NOT ignored.

![image](https://user-images.githubusercontent.com/1165615/57154356-b0387700-6da6-11e9-8aae-7356dc453867.png)

**Comment by margaretdumas** [comment]
Yes, I saw that after I posed the question.  I was mistaken

**Comment by margaretdumas** [comment]
@bmcorum @kbwagner What about this one?  What are the rules that we are to look for?  
![image](https://user-images.githubusercontent.com/19936109/57160528-01506700-6db7-11e9-900d-cbb72d590ac7.png)

**Comment by bmcorum** [comment]
Ah yes. @tanichacko we will need to overload the sortBy to compare the lowercase version of the strings. Capital letters are assumed to occur before lowercase letters when comparing strings.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-7-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
Added Bug 3501 for spelling error found.

**Comment by kbwagner** [comment]
5/7/19 - KWAgner tested in Chrome/Test
Ready for final review.
