### ISSUE TITLE
Update application process when viewing an internship already applied to

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3205]
Who: Student intern applicants
What: updating an application
Why: to be consistent across the system on how an application is updated.

Acceptance Criteria: 
When viewing an internship opportunity I have already applied to or have started an application for:
- Change the button from Apply to "Update application"

1) Scenario 1 - Update a submitted application
- When Update application is selected on a submitted application, the Update application modal will display that displays on the landing page when an application is being updated
![image (15)](https://user-images.githubusercontent.com/18709918/54635374-60058f80-4a5a-11e9-9942-218c51a5ed78.png)
- When the update button is clicked on the modal, the applicant is taken to the select internship screen of their existing application where they can edit. (same as landing page update application)

2) Scenario 2: Update an In progress application:
- when "Update application" is selected on an internship that has not been submitted but has been started (in progress), the application is loaded to the page where they left off.  No modal appears.

**Comment by Kibrahacha67** [comment]
@kbwagner Question, in the second scenario when you say "Update application is selected" do you mean when the user clicks on the application link?  As there is no button "Update application" unless the modal pops.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-28-19 LHammond in testing

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test
Ready for final review.
