### ISSUE TITLE
Create new pill for internship opportunity status of "Approved"

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3207]
Who: Internship community managers
What: ability to see approved opportunities before they are open for applicants
Why: in order to differentiate what opportunities have been approved vs submitted vs open

Pill Design:   
- Create a new pill for an internship opportunity status of "Approved"
Pill styling and color: 
<img width="130" alt="Open_Opps_-_Dept_of_State__master_-AB" src="https://user-images.githubusercontent.com/11526811/54639225-3e5cd600-4a63-11e9-89fc-9fdff3da1d8f.png">
design system color = #4c2c92

Pill Display:
- Add the pill to the community admin dashboard for communities with a target audience of student
- The pill should display to the right of the submitted pill
- All internships that have been approved will be sorted under the "Approved" pill

Pill Functionality: Covered in ticket 3000 but noted here 
- Once an internship opportunity is appoved, it will go to a status of approved instead of Open.
- Once the internship is open for applicants, the status will change to apply.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
4/22/19 - Mdumas - Tested, moving to review.

**Comment by kbwagner** [comment]
4/23/19 - Purple pill now appears on dashboard.
Ready for final review.
