### ISSUE TITLE
Internship duplication process: cycle is duplicated

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3216]
After duplication process, Step 1 page cycles are duplicated (see image).
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/0a98df3c-45b3-46b8-9c3a-95de3ad7e5cf)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-21-19 LHammond in testing
Testing completed. moving to review.

**Comment by kbwagner** [comment]
3/25/19 - KWagner - reviewed in test
Ready for final review.
