### ISSUE TITLE
Saved section of landing page improvements

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3218]
Who: Internship applicants
What: Saved on landing page
Why: Clarifications on view

1) When there are no internships saved yet, change the wording from existing "no opportunities" to "You have no saved internship opportunities."
2) When there is only one internship saved, it says "Viewing 1-1 of 1 internships".  Is it possible only for when it's 1 to have internship display singular as "Viewing 1-1 of 1 internship".  Anything above 1 would be "internships"?    
![image](https://user-images.githubusercontent.com/18709918/54704649-8d614480-4b11-11e9-91e9-089e09db9ec1.png)

**Comment by kbwagner** [comment]
@raywilliams put in the approved text from Debbie above.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-27-19 LHammond in testing
completed testing moving to review.

**Comment by kbwagner** [comment]
3/27/19 - KWagner verified with student account in Chrome/Test environment

Wording is updated

![image](https://user-images.githubusercontent.com/18709918/55109866-29102900-50ad-11e9-9e71-657f475ac1e8.png)

![image](https://user-images.githubusercontent.com/18709918/55109968-5a88f480-50ad-11e9-9fe0-c76b705752a7.png)


Ready for final review.
