### ISSUE TITLE
Student landing page application view updates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3223]
Who: Internship landing page 
What: Viewing application blank page
Why: To clean up

Acceptance Criteria:
1) On the student landing page, when there are no applications, please change the default text from "No applied applications" to "You have no applications." 
Current screen shot:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/4b5a14f5-b222-4e58-a6bc-0ef83f30b285)

2) If only one internship displayed, display “Viewing 1 – 1 of 1 internship” singular? Then for anything above 1 display “internships” plural.

Current Screen Shot
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/fb4ac2f5-0fc5-4ff7-a568-b2d17c6b189e)

**Comment by kbwagner** [comment]
@raywilliams - updated with approved text from Debbie

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-27-19 LHammond in testing
completed. moving to review.

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test
Ready for final review.
