### ISSUE TITLE
Save Star with login

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3225]
Who: Internship applicant - logged out
What: save internship
Why: to prevent duplicate clicks and to work like USAJOBS

In USAJOBS, if I am logged out but click "Save" on a job, once I log in, the job has been saved and takes me to my saved job page.

Currently in Test Open Opps, if I am not logged in and click the save star, I go through the login process, I'm taken back to the internship but the star is not selected so I have to click again.

If possible, the star should be selected already once logged in so the internship is saved.  This may not be possible with login.

Low priority but nice to have to be consist with USAJOBS.

**Comment by Piglady64** [comment]
@bmcorum is this estimate accurate? 13

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-31-19 LHammond in testing

**Comment by kbwagner** [comment]
6/2/19 - KWagner tested Chrome/Test
Ready for final review
