### ISSUE TITLE
Spike: Research automation in Open Opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3228]
Spike:
Research automation in Open Opportunities

For example, in 2915, we would like to receive selectee data from ATP, then automatically push selectees to "task completed", then automatically "Complete" the internship opportunity.

Related ticket: 2915

**Comment by bmcorum** [comment]
Have a few options for implementing some automation.

- [node-cron](https://www.npmjs.com/package/cron)
- [Node Schedule](https://www.npmjs.com/package/node-schedule)

**Comment by kbwagner** [comment]
5/14/19 - Reviewed spike info.  
- Will update 2915 once we hear more from ATP
- Ready for final review.
