### ISSUE TITLE
Landing Page: Update Applied Section

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3229]
Who: Student intern
What: Landing page application view
Why: In order to view application related information

Acceptance Criteria:
The following updates should be made to the student internship signed in landing page due to design updates: 

Current columns: Status, Internship application, and Last updated columns
New columns: Application status, Program, Cycle

- Application Status - no change
- Program - display community name (not cycle) as a link that will open their application
     - If the cycle apply end date has passed, the community name will display but not as a link
- All applications, regardless of status, can be viewed.  
- Cycle - Display name of cycle of the internship application

Invision Mock: https://opm.invisionapp.com/d/main#/console/15360465/352514658/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-1-19 LHammond in testing,
My test has one program that is a link and one that is closed, Both should be linked to their perspective applications per AC.  moving back to development.

**Comment by bmcorum** [comment]
@Kibrahacha67 completed status won't show until after the actual internship is over. This would be the internship end date has passed. The application end date will pass and you will no longer be able to update your application but it wont change to completed until later. Also, we have a ticket to mark applications completed that we have not worked yet.

**Comment by Kibrahacha67** [comment]
that's not the problem, the problem is that program should show as a link.  the first one does not.

**Comment by bmcorum** [comment]
Ah yeah looks like the AC never got updated. USAJOBS does **NOT** allow for viewing applications after the apply date has passed. @kbwagner can we get the AC updated to reflect it we want to display as a link even if apply date has passed, or do we want to keep in line with USAJOBS.

**Comment by kbwagner** [comment]
@bmcorum @Kibrahacha67 wasn't quite finished with that one but it's updated and I marked requirements ready with the requested note included.
@tlorrison please approve as well.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-5-19 LHammond in testing

**Comment by Piglady64** [comment]
4/8/19 - Reviewed by Julie - Moved to final approval
