### ISSUE TITLE
Add test for tag creation.

### ISSUE THREAD

**Issue by monfresh** [openopps/openopps-platform#323]
During yesterday's hack night, we discovered a bug where non-admins were not able to create tags due to [this policy](https://github.com/18F/midas/blob/0770dd4f8e696688f862add38ab49a722cd04261/config/policies.js#L82), which has now been [fixed](https://github.com/18F/midas/pull/320) to allow non-admins to create tags.

The fact that all tests passed before the fix means that tag creation is not properly tested, so I'm opening this issue to document the need for a tag creation test.

**Comment by dhcole** [comment]
We test logged in users creating tags here: https://github.com/18F/midas/blob/devel/test/api/sails/tag.test.js#L46 but we do not test logged out users attempting to create them.

**Comment by kbwagner** [comment]
no longer an issue
