### ISSUE TITLE
Landing page: Update Saved section

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3230]
Who: Internship applicants
What: Landing page saved section updates
Why: to display fields more relevant to the applicant

Acceptance Criteria: 
The following changes should be made to the saved section of the landing page:
Current column headings: Internship status, Internship, Last updated
New column headings: Location, Internship, Closing date 
Column headings should be the same when there are no saved internships or when it is populated
- Location should display city, state, country.  If country is US, no country needs to display just city, state
Adding 3/27/19 - If location is Virtual, display "Virtual"

Invision Mock: 
https://opm.invisionapp.com/d/main#/console/15360465/352514658/preview

**Comment by kbwagner** [comment]
@abudz19 - this ticket got pulled in.  Can you look at my comment on the mock: we had changed this to Internship status to be clear vs application status. We are also displaying the status pills here. The status in the example of "Applied" doesn't fit...because if you apply it should fall off of the save.
- If we can finalize this by 3/22 so they can work it next week that would be great.

**Comment by kbwagner** [comment]
@raywilliams confirmed with Alex the column headings and removed the note to check with her.  Letting you know since it's in development.

**Comment by kbwagner** [comment]
@raywilliams Alex and I were just discussing the fact that the internship status will always be Open since they will fall off save when they apply or the internship closes...so the status doesn't make much sense.  She's added location (city, state, country) instead.  Since you have already pulled this over, does this need to be a new ticket or if you haven't started can I update this one?  
![image](https://user-images.githubusercontent.com/18709918/54783986-1a32fd80-4bf9-11e9-8cb3-c1048e0fd614.png)

**Comment by raywilliams** [comment]
@kbwagner No, I haven't gotten that far on the ticket. I'll include the new changes you asked for.

**Comment by kbwagner** [comment]
@raywilliams AC has been updated.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-27-29 LHammond in testing

**Comment by kbwagner** [comment]
@abudz19 for your review - this includes the updates you made with the withdraw change.

**Comment by kbwagner** [comment]
3/27/19 - Kwagner tested as student in Test/Chrome. 
- Need to confirm display of United states on saved but got kicked out of test.

**Comment by kbwagner** [comment]
@raywilliams - if Virtual is selected only a comma displays.  Can we display the word Virtual for those situations?

![image](https://user-images.githubusercontent.com/18709918/55111024-ccfad400-50af-11e9-8ffe-e11a336ffd29.png)

**Comment by raywilliams** [comment]
@kbwagner  Yes, I can make that change.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-29-19 LHammond in testing

**Comment by kbwagner** [comment]
4/1/19 - KWagner tested TEst/Chrome
Ready for final review.
