### ISSUE TITLE
Update Process modifications

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3231]
Who: Student
What: Update application process
Why: As a student I want to be able to update my application 

Acceptance Criteria:
- When the user clicks the "update" button from the "submitted application" page they will get the "update modal" #3049 
<img width="700" alt="Open_Opps_-_Dept_of_State__master_-AB" src="https://user-images.githubusercontent.com/15252970/56161169-f021f080-5f96-11e9-989a-d521588be13d.png">

- from the modal the user will go to the "select internship opportunities" page (the first page in the application process)

Note: the modal is not in the InVision Mock below

Invision Mock: https://opm.invisionapp.com/d/main#/console/15360465/352514658/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-18-19 LHammond in testing

**Comment by Piglady64** [comment]
Modal comes up when I click Update- moving to final approval

**Comment by Piglady64** [comment]
Modal comes up when I click Update- moving to final approval
