### ISSUE TITLE
Community Admin: Remove add participant

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3233]
Who: Student community managers
What: remove ability to add participants
Why: students must submit a full application

Acceptance Criteria: 
- For a community with a target audience of student
- Community --> Opportunities --> Manage --> Status of Open
- Remove the "Add participant" column.  Internships require a full application not just a person being added.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
5/23/19 - KWagner tested in testing
Ready for final review
