### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3237]
Who: Open Opportunities Application (Technical)
What: Open Opportunities will need to request a new token for OpenData API access
Why: OpenData API tokens expire one hour after it is issued

OpenData API is leveraged for syncing a user's Open Opportunities profile with their USAJOBS profile. OpenData API is also leverage for auto-populating student internship applications.

**Acceptance Criteria**
- [ ] Federal users are still able to get profile updates after being logged into the system for longer than 1 hour
- [ ] Student users are still able to create a new application and have it auto-populated after being logged into the system for longer than 1 hour

**Comment by kbwagner** [comment]
@bmcorum can you fill this one in please?

**Comment by Piglady64** [comment]
Per Marshall on 4/17/19 this A/C is good. Please talk to him if you have any questions.

**Comment by Kibrahacha67** [comment]
@bmcorum - I'm assuming that the open opps time out is going to change for this ticket from 15 minutes to an hour?  can you confirm...

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-30-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-3-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed - moving to final approval
