### ISSUE TITLE
Bug: Apply - Education and Transcript page - lose data when refresh transcript selected

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3243]
Environment: Test
Browser: Chrome

Steps to reproduce:
1) Go to education & Transcript page on the application
2) Enter info into the first three questions and GPA
3) Click Upload transcript
4) upload a transcript on USAJOBS
5) on the education page, click Refresh
- Data on entered on the page is lost

Resolution:
- Find a way to keep data from being lost - temporary save of some sort?
- If not possible, we need to notify the user to save before they refresh.

**Comment by bmcorum** [comment]
@kbwagner are you using the "Refresh Transripts" button or the browser refresh?

**Comment by kbwagner** [comment]
@bmcorum - the Refresh transcripts button

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
I'm putting this ticket on hold as I cannot get to that part of the application due to cycle issues.  Dev team is looking into the issue.  Will resume testing when issue is complete.

**Comment by Kibrahacha67** [comment]
4-2-19 Lhammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test
Ready for final review.
