### ISSUE TITLE
Update text on Next Steps page of application

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3248]
Who: Internship applicants
What: Reviewing next steps
Why: To properly state what is required and not for their application

Acceptance criteria:

Issue: The next steps page indicates that references are required but they are actually not.  

Please update the next steps page Step 2 as follows: 
Tell us about your work, military or other experience. 
- Remove the subtext on reference data

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-19 LHammond in testing
completed testing moving to review.

**Comment by Piglady64** [comment]
@kbwagner The header was changed as per the A/C but the statement under this header still says 
![image](https://user-images.githubusercontent.com/15252970/56830224-cb016d80-6833-11e9-85e4-3bcad537e39d.png)
This still implies that references are required. Do you think we need to change this statement as well?

**Comment by kbwagner** [comment]
@Piglady64 yes that statement on references should be removed.  May not have been clear in the AC but that was the intent.

**Comment by kbwagner** [comment]
@raywilliams might not have been clear but the statement regarding references needs to be removed here.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
@Piglady64 @kbwagner - please update the AC to reflect the changes made to the page.  ty

**Comment by Kibrahacha67** [comment]
4-29-19 Testing hold

**Comment by kbwagner** [comment]
@Kibrahacha67 the AC is updated.  It really said it before but I guess wasn't clear so I added an additional sentence.

FYI, Julie created a new ticket to add some new subtext but since it was a change to the AC it's a new ticket that will come later.

**Comment by Kibrahacha67** [comment]
@kbwagner ty.
4-30-19 LHammond in testing

**Comment by kbwagner** [comment]
5/9/19 - KWagner tested in UAT/Chrome
Ready for final review,
