### ISSUE TITLE
Education section of apply is required

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3251]
Who: Internship applicant
What: Require at least one row of education
Why: required by state.

The education section of the application where the student can click on Education and add school name and info is required.  However, I can click save and continue without having to enter an education.

Before save and continue is selected, require at least one row of education data be entered by the applicant.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-2-19 LHammond in testing.

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Test/Chrome
Ready for final review.
