### ISSUE TITLE
Transcript - should be required

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3252]
Who: Internship applicants
What: required to provide a transcript
Why: required by State

Once I have uploaded a transcript, I still must go select the radio button to select this transcript.  If I do not select the radio button, I can click Save and continue without having selected a transcript.

Transcript should be required on Save and Continue.

Use Case 1: I have not uploaded any transcripts and select save and continue
Use Case 2: I have added a transcript but have not selected the radio button and select save and continue.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-2-19 LHammond in testing
testing completed moving to review.

**Comment by Piglady64** [comment]
4/8/19- Julie reviewed - moving to Final Approval
