### ISSUE TITLE
Apply Process: No references text on review page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3253]
Who: Internship applicants
What: Review their application
Why:  To avoid confusion

On the internship application review page, if no references are supplied (optional), the header appears but nothing else.  We can't suppress the header like USAJOBS because we need the edit.  

If no references are supplied, display the following text under the References header on the review page:
You haven't added any references.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-2-19 LHammond in testing

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test
Ready for final review.
