### ISSUE TITLE
Department of State: Display description of "Other" on the Review Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3255]
Who: Student
What: Display information provided under "other" on the review page
Why: as a student applicant I want to be able to review everything that is being submitted prior to submitting my application

A/C
- If the user has provided information on Experience & Reference page for the question "Do you have overseas experience?= Yes - Please indicate what type of overseas experience you possess. = Other - If you chose "other" please specify It should display on the Review Page
- The information will be listed in the "Experience" section on the "Review" page

![image.png](https://images.zenhubusercontent.com/5b59d12efee5ed0b01c00008/422152f2-148b-4e7a-b26f-96e1b59b2ac5)

**Comment by Piglady64** [comment]
Per Tani's request, I added "The information will be listed in the "Experience" section on the "Review" page" to the A/C to explain where this information will be presented on the this page.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-27-19 LHammond in testing.
testing completed moving to review.

**Comment by Piglady64** [comment]
3-28-19 Julie reviewed moving to final approval
