### ISSUE TITLE
Department of State: Display length of overseas experience on the review page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3256]
Who: Student
What: display the length of overseas experience information provided on my review page
Why: as a student applicant i want to see all of the information that will be submitted with my application

A/C
- If the student has provided information in the "please indicate the total length of your overseas experience(s)" on the Experience & References page it should display on the Review Page 

**Note** this is dependent on the completion of #3178

**Comment by tanichacko** [comment]
@Piglady64 : Can you confirm with what's the header needs to display in the Review page for this ticket, currently I am giving as '**Total length of overseas experience**' as header . If that's OK I can proceed if that's not OK, Can you add it in the ac?

**Comment by Piglady64** [comment]
@tanichacko "Total length of overseas experience" is what it should be. The text box this information comes from says "Please indicate the total length of your overseas experience(s)."

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-27-19 LHammond in testing
completed testing moving to review.

**Comment by Piglady64** [comment]
3-28-19 Julie tested in Chrome and it looks good. moving to final approval
