### ISSUE TITLE
Text runs together on the "Delete Languages and skills"  confirmation modal

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#3260]
The text runs together on the delete confirmation modal for Language and Skillls.

Steps to reproduce:
1.  Sign into a student account
2.  Navigate to the internship application
3.  Navigate to step 4 Language and skills
4.  Add a skill or attempt to remove one that exists (delete function)

Delete confirmation modal appears:  
![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/e8d003fd-1fb4-49a2-a2ca-f4f79e9e0100)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner Question for you, on this page you have the ability to delete languages and delete skills, should this modal pop for both deletes?  and is the current language for delete language what you want as it has changed from the original?
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c7a40915-20f8-432c-ad71-8700764d961c)

**Comment by kbwagner** [comment]
@Kibrahacha67 yes we should have a confirmation for both deleting a language and deleting a skill.  It was just one combined before which was ok although not ideal.  So if it's separated into two we definitely need two.
Language is fine on the delete language.

Thanks!

**Comment by Kibrahacha67** [comment]
Testing completed, the skills delete does not pop the modal as expected.  moving back to development.

**Comment by raywilliams** [comment]
@Kibrahacha67 There's only a modal for deleting languages on that page. We don't have a modal for deleting skills.

**Comment by kbwagner** [comment]
@raywilliams the original modal seemed to be for both skills and languages?  Do we need a new ticket to add a delete modal for skills?

**Comment by raywilliams** [comment]
@bmcorum can expand more if needed, but we don't have a modal for deleting skills because we don't actually delete skills until the user clicks save. The original modal header was using a variable name so I corrected that to say what was actually getting deleted.

**Comment by kbwagner** [comment]
Got it - I’m ok with that then. We don’t need a modal for skills. Thanks

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. See comment above from @kbwagner.

**Comment by Kibrahacha67** [comment]
6-20-19 LHammond testing completed moving to review.

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Test/Chrome
Ready for final review.
