### ISSUE TITLE
Bug: Create internship - countries with no state will not save

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3279]
Environment: UAT and Test
Browser: Edge and Chrome
steps to Reproduce:
1) Create an internship with a target audience of Student (unpaid)
2) Select a country that does not have a state such as United Kingdom
- State is grayed out
- Select Preview - nothing happens.
- Will not save unless country is changed to US or one where state is not grayed out
- No error message is thrown so the user does not know why there was an issue

Resolution:
- Fix issue with countries that don't have state
- If there is an error on the page, display an error message.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/0e5d117c-6933-47b0-aadc-0b42041a1191)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-29-19 LHammond in testing

**Comment by kbwagner** [comment]
4/1/19 - KWagner tested Test environment, chrome

Ready for final review.
