### ISSUE TITLE
Bug: Drafts won't submit

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3280]
Environment: UAT
Browser: All

Steps to reproduce:
1) Create an internship
2) Save as draft

Issue 1: If you edit a draft and save, no changes are saved
Issue 2: If you duplicate a draft, no changes are saved
Issue 3: If you submit a draft, you receive a message that it was submitted but it still says "draft" on landing page and the admin does not receive a submit email.  So it's not truly submitting

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/23189368-0911-44a4-b4e7-d633f67f8775)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. Please test with a general user account.

**Comment by Kibrahacha67** [comment]
3-27-19 LHammond in testing
1. Can create a ticket, but if you add to either "What you'll learn, Who we are or Related key works" It will preview but not save when you click Submit or Save for later
2. on a ticket that is in open status, Preview will not submit the page and it just sits no matter how many times you click the button
3. Same issue in progress, will let you edit, will show changes in preview, but once it is saved nothing saves...
moving back to development

**Comment by bmcorum** [comment]
This change only applies to UAT at the moment.

**Comment by Kibrahacha67** [comment]
3-27-19 Testing completed.  Moving to review.

**Comment by kbwagner** [comment]
@bmcorum I created two drafts in UAT and got them to submit.
- But...when I log in as my admin account and try to approve them they won't approve.

![image](https://user-images.githubusercontent.com/18709918/55102914-d3805000-509d-11e9-9e4f-9840dc5c4fb3.png)

**Comment by bmcorum** [comment]
@kbwagner,

@Kibrahacha67 and I were not able to replicate this issue. Can you provide more details on which dashboard you were trying to approve from (Site, Agency, Community)? Could you approve any of the submitted opportunities or only specific ones?

**Comment by kbwagner** [comment]
@bmcorum I was able to get this to work so we can move this to final review.  Not sure why they didn't work the first round but ok now.

**Comment by bmcorum** [comment]
- [X] **VERIFIED** fixed in version [v7.5.21](https://github.com/openopps/openopps-platform/tree/v7.5.22)

@kbwagner, I am moving this back to development so that we can have it merged into our 7.7.x version of code and tested in our TEST environment so we make sure to not reintroduce this bug.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**NOTE** Please test in the TEST environment.

**Comment by Kibrahacha67** [comment]
3-29-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
During continued testing it is doing this on all browsers and all roles.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
Testing completed moving to review.

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test
Ready for final review.
