### ISSUE TITLE
Update text on submit alert

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3281]
Who: Hiring managers
What: submit alert messaging update
Why: To make it more clear

Remove the "the" in the first sentence so it will read, "Thanks for submitting <internship name>."
Remove cancel button

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/a1dcc2c7-ef10-4b51-b101-424d0f3bdd72)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
@Piglady64 Question, what page is this alert on?

**Comment by kbwagner** [comment]
@kibrahacha67 -this is when an internship creator submits an internship for review...so create, preview, submit.

**Comment by margaretdumas** [comment]
04/9/19 - Mdumas- Testing but moving back to development.  The "the" did not get removed.  

![image](https://user-images.githubusercontent.com/19936109/55801399-fd754180-5aa3-11e9-8463-c8f81635c02c.png)

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-10-19 @Piglady64 I cannot open any of the images attached to this thread, can you validate the text for me so I can complete the test:

"Thanks for submitting your application to the U.S. Department of State Internship Program (Unpaid).

Is the "the" in front of "U.S." what you are trying to remove?

**Comment by Kibrahacha67** [comment]
Testing completed.  moving to review.

**Comment by Piglady64** [comment]
@Kibrahacha67 Sorry, I am just seeing this. The "the" that needs to be removed is in front of the name of the Internship.  this is the "submitted" modal

**Comment by Piglady64** [comment]
This is still not correct. The "the" before the internship opportunity name needs to be removed. This shows up when someone creates a new internship opportunity and gets the "submitted" modal.

**Comment by Kibrahacha67** [comment]
@Piglady64 May I make a suggestion, Maybe if you put the text in the AC that you want the confusion will be eliminated and you will get what you want...

**Comment by Piglady64** [comment]
@Kibrahacha67 I think the "the" was in the original A/C and then we noticed it and realized it sounded weird so Katrina submitted this ticket to correct the language. When I went back in it is correct. Not sure what happened but I am moving this to final approval.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
4/15 /19 - Mdumas - Passed testing. moving on to review.

**Comment by Piglady64** [comment]
Julie reviewed - the "the" has been removed. Moving to "final approval"
