### ISSUE TITLE
Bug: Application end date displays incorrectly

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3282]
Who: Intern applicants
What: Applicant end date display should be correct
Why: So I'll know the deadline to submit the application

Environment: UAT
Steps to reproduce:
1) Click on Search and then Internships
2) The blue information bar displays May 2, 2019 but I believe the application end date is May 3rd (please verify since I can't see the table)
- Will create a separate enhancement ticket to add 11:59 PM EST to the message

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/81ad2034-0341-4352-ae85-01f72be2a67b)

**Comment by tanichacko** [comment]
@kbwagner  Application end date we have 05/02/19 in database .I am  attaching the screenshot.
![cycle end date](https://user-images.githubusercontent.com/40576337/55355187-9cdb7880-5495-11e9-95cb-5773fb317302.PNG)

**Comment by kbwagner** [comment]
@tanichacko can you please check UAT?  I was fairly certain the end date was 5/3/19 but 5/2 displayed/  So it could be fine but otherwise Brice had some ideas on why it displayed funny due to time zone issues

**Comment by bmcorum** [comment]
@kbwagner and @tanichacko I would say we could try to edit and if we set it for 5/3 see if it saves and displays as 5/3 or 5/2. If it display correctly then I think we can just move this ticket forward.

**Comment by tanichacko** [comment]
@kbwagner  Yes the screenshot I took it from UAT.

**Comment by kbwagner** [comment]
Ok thanks.  Will close then.
