### ISSUE TITLE
Add text to the blue box on search page to indicate the closing time of the application

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3283]
Who: Internship applicants
What: Closing date  text 
Why: so I will understand exactly when the closing date of the internship occurs

Add text to the end of the blue bar so it will read: 
Application deadline: <Month, Day, YYYY> at 11:59 p.m. EST.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/64010894-2b7d-4006-8985-a3960d8de914)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
04/9/2019 - Mdumas - Passed testing....Moving to review

**Comment by Piglady64** [comment]
Julie reviewed - text has been added - moving to final approval
