### ISSUE TITLE
Change Opportunities to Internship opportunities on search page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3284]
Who: Student interns
What: change the word opportunities to Internship opportunities
Why: To have consistency in wording

On the search page, it reads, "Viewing 1 -1 of 1 opportunities" but should read "Internship opportunities" or just "Internships" if there is not enough space.

![image](https://user-images.githubusercontent.com/18709918/55032538-74600400-4fe7-11e9-9e5e-294621ff7969.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
4/9/19 - Mdumas - Passed Testing...

**Comment by Piglady64** [comment]
Julie reviewed - moved to final approval
