### ISSUE TITLE
Add fade to internship card

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3285]
Who: Internship applicants
What: viewing internship card display
Why: to get a quick peak

Add fade to internship opportunities like we did for regular opportunities so there isn't a sudden cutoff

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/a172d0d8-9288-41c6-82f9-39a9e2c7e5d1)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
05/3/19 - Mdumas - testing...

**Comment by kbwagner** [comment]
5/6/19 - KWagner - tested in Test/Chrome
Ready for final review.
