### ISSUE TITLE
Bug: Skills search not working

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3286]
Environment: UAT

Steps to reproduce:
1) On the internship search page, enter a skill of Coordination
2) no search results return but there are skills of Coordination in an internship

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/962d10b2-f4f3-4344-a16a-8a2299d2ac52)

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/690877b6-f9cb-4e05-b20a-eee94c9c2c03)

**Comment by raywilliams** [comment]
@kbwagner I tried adding the Coordination skill and was able to see the opportunity. I looked at your screenshot and saw that one of your search criteria is "United States". That opportunity is Virtual. That may be why it didn't show up when you searched by that skill.

**Comment by kbwagner** [comment]
@raywilliams this was in UAT and I can't see internships in UAT right now so will retest as soon as it's put back together.  This happened with a few people yesterday and I know when I did that screen shot I didn't purposefully select united states so I'll double check what's going on when UAT is back

**Comment by kbwagner** [comment]
@raywilliams UAT is back up so I tested "coordination" again and made sure there were no other pills and it  doesn't work for me still.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-17-19 LHammond in Testing

**Comment by Piglady64** [comment]
Julie Reviewed - used "cool stuff" returned  ~Hola, coma estas~! Used "Website design" - returned Become a techie in the intelligence community - moving to final approval
