### ISSUE TITLE
Bug: Internship skills should search against internship page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3287]
Environment: UAT

Steps to follow: 
1) When viewing an internship opportunity, click on desired skills
2) the search runs against regular opportunities.  Should run against internship opportunities only and should add a pill 
-  Clicked on Verbal and written communication, took me to regular search, no pill added 

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/d845c1f9-0070-4ea1-8a59-ea2bd8a130d2)

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/b478173c-af98-4a7b-be11-5482708c00c8)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-29-19 LHammond in testing

**Comment by kbwagner** [comment]
4/1/19 - KWagner tested in Test environment Chrome as Admin
Ready for final review.
