### ISSUE TITLE
Bug: Display State footer on internship opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3288]
Environment: UAT

Steps to reproduce:
1) On the internship search page, select an internship to view
2) Full internship has standard Open Opps footer instead of State footer. 
- Display State footer

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/8cb9e77d-5242-4055-9852-85228127020d)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-20-19 LHammond in testing

**Comment by kbwagner** [comment]
4/1/19 - KWagner tested in Chrome/Test environment as Admin

Ready for final review.
