### ISSUE TITLE
Bug; Number of interns toggle display in Firefox

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3289]
Environment: UAT
Browser: Firefox

In Firefox, this toggle is super tiny and kind of hard to use.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/61b2853d-74db-4af8-8eef-25400cc7dec1)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-29-19 LHammond in testing
tested in chrome and ff.  moving to reveiw.

**Comment by kbwagner** [comment]
4/1/19 - KWagner tested in Test/Firefox
Ready for final review
