### ISSUE TITLE
Bug: Lose navigation 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3290]
Environment: UAT
Chrome and Firefox

Steps to Reproduce:
1) Navigate around
2) Go to profile.  Profile randomly loses navigation

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/d6dca510-64ea-4000-b48d-55f479ddabb5)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-29-19 LHammond in testing
Tested in chrome and ff both working, moving to review.

**Comment by kbwagner** [comment]
4/2/19 - KWagner tested Chrome/Test
Ready for final review.
