### ISSUE TITLE
Bug: User search lose results after page 3

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3293]
Environment: Production and Test

Steps to Recreate:
1) In the Admin --> Users --> Manage search by agency "State" and multiple pages of results appear
2) on the pagination, select page 2, scroll through, then select page 3.
- On page 3, you lose all results

![image](https://user-images.githubusercontent.com/18709918/55089602-074e7c00-5084-11e9-9114-63455fb15897.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by kbwagner** [comment]
6/18/19 - KWagner tested in Chrome/Test environment
moving to final review.
