### ISSUE TITLE
Application: Limit GPA to a 4.xx scale

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3304]
Who: Internship applicants
What: GPA limitations
Why: In order for sorting to work properly

At the request of ATP:
- When a student enters their GPA on the education page, limit to X.XX characters
- Do not allow more than a 4 to be entered as a whole number
- Do not default GPA to 0.00.  It should be blank.  Otherwise, if I don't enter anything I get the GPA below 3.0 message instead and have to hit the back button to get back to the page.
- If I enter anything above a 4.0, throw an error message that says You must enter a GPA on a 4.0 scale.

**Comment by tanichacko** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-10-19 LHammond in testing
Testing completed moving to review.

**Comment by Piglady64** [comment]
Julie - Moved to final approval
