### ISSUE TITLE
Cycle date for internships passed but all of the Internship opportunities for that cycle still show in search.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3311]
Found during testing, all of the internships associated with Saleim's cycle are still on the internship search page.  All of the applications are greyed out but no other actions took place.

**Comment by Kibrahacha67** [comment]
6-11-19 LHammond this has been resolved moving to review.

**Comment by kbwagner** [comment]
6/11/19 - KWagner reviewed/tested
Ready for final review.
