### ISSUE TITLE
Bug: Create Opp UI bug in IE and Safari

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3318]
Environment: UAT

Browser: IE and Safari - Chrome was ok

Steps to reproduce:
1) Create an internship opportunity
2) Step 1- Define who, when, and where goes to two lines in some browsers and should ideall be on one

![image](https://user-images.githubusercontent.com/18709918/55340611-0ac27880-5473-11e9-9090-15a6c9d62962.png)

Found during 3/26/19 bug bash

**Comment by bmcorum** [comment]
@humancompanion, @abudz19 can this be closed as a non-issue? Seems to me that if there is not enough space the line should wrap. Also it would wrap for mobile or for smaller screens.

**Comment by humancompanion** [comment]
Yes, this is a non-issue. The Standards define a max-width for the form and we are complying with that. The headers could technically live outside the form, but that would be unnecessarily burdensome. Lines are going to wrap at different viewports. The fact that it looks a little awkward at desktop is the least of our worries.
