### ISSUE TITLE
Don't throw error on office/post until something has been entered on field

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3319]
Who: Internship creators
What: Error on office/post field
Why: I haven't entered anything yet so should not get an error

When creating an internship opportunity, I get an error message on the office/post field as soon as I enter the bureau information. do not display error message on office/post until I have tabbed past that field.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/e1ef1fc4-8ead-4229-b99f-4b81feadfb57)

From 3/26/19 bug bash

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-26-19 LHammond in testing

**Comment by Piglady64** [comment]
No longer throwing error before typing in Office box


Moving to final approval
