### ISSUE TITLE
Update two spelling errors on Bureau/Office/post data for State

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3320]
Who: DoS users
What: resolve spelling errors
Why: to have proper data in the dropdowns

In the bureau/office/post data, please update the following:
- Office of Brail and Southern Cone (WHA/BSC) to be Office of Brazil and Southern Cone (WHA/BSC)
- Update LaPaz to have a space La Paz

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/12b851a3-861c-4076-80a6-d90fbf282632)

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/9fb0d753-776d-4605-84aa-4bb8c7688816)

Found during 3/26/19 bug bash

**Comment by tanichacko** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
Mdumas - Testing....

**Comment by Piglady64** [comment]
Julie reviewed- corrections have been made - moved to final approval
