### ISSUE TITLE
Bug: Prevent student from having admin priveleges

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3321]
Environment: Test
Browser: Chrome

Steps to follow:
1) Create an account as a federal user
2) Change the account to be a student
- The landing page appears to be a student but the user can still create and see the admin tab
- When the account is converted, it is a student account with the isAdmin flag set to true
- Student accounts should not be admin

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-17-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed - When I go in and change my profile and remove the federal employee and make it a student I am no longer able to sign into OO. I get the Akamai page.

**Comment by kbwagner** [comment]
@jhanson12 @bmcorum Tested this in Firefox/Test
1) Took katrina_wagner@hotmail.com account with federal hiring path
2) Changed hiring path to student
3) Selected return to Open Opps.  
- I still have my full federal landing page and ADmin access
4) logged out and logged back in...still have my full federal landing page and admin access.
- it has not registered I am a student.

**Comment by bmcorum** [comment]
@kbwagner did you remove your federal service? Remember federal service trumps student hiring path. If you did not set your federal service to 'No' then you are still a federal employee.

**Comment by kbwagner** [comment]
@bcorum yes I removed federal and am just student. I’ll check again but double checked last night

**Comment by kbwagner** [comment]
@bmcorum today it's ok.  Who knows.

Ready for final review.
