### ISSUE TITLE
Allow user to have multiple hiring paths

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3326]
Landing page 

Concern over the fact that some federal employees can also be students.  If you have both, you are stopped
•	Michelle said we have to allow for federal to also have student
•	Should be a small population – must be a current junior and returning to school
•	We have very distinct personas with their own unique homepages student and federal

Hiring paths: Federal, student, contractor
- student can be a contractor
- fed can be a student

**Comment by bmcorum** [comment]
My recommendation would be to just allow everyone to apply to student internships.

**Comment by kbwagner** [comment]
2/3/2020 - Discuss with State in a future meeting - allow anyone to apply

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41581&_a=edit
