### ISSUE TITLE
Apply: Skills should pull over from my Open Opps profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3331]
Who: Internship applicants
What: application should include skills from Open Opps profile
Why: To allow my skills to be included for hiring managers to see

When I apply, the skills from my Open Opps profile should come into my application and allow for me to be changed.
- The application review page displays skills from my profile now...even though they don't display on my application page.

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-15-19 LHammond in testing

**Comment by Piglady64** [comment]
Skills moved over from my OO profile - moving to final approval
