### ISSUE TITLE
Bug: Lose education data when education added

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3334]
Environment: Test
Browser: Chrome

Steps to reproduce:
1) Answer the 3 education questions and GPA
2) Select Add Education (when you don't already have education)
3) Enter education and save
4) Questions and GPA are lost
- Once saved, I can edit the questions and follow the same path and the edits will save.  Appears to be an issue when blank and the page hasn't been saved.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-4-19 LHammond in testing.

**Comment by tanichacko** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-10-19 LHammond in testing.
Testing completed moving to review.

**Comment by Piglady64** [comment]
Julie - Reviewed in Chrome - Moved to final approval
