### ISSUE TITLE
Create: Add security clearance level

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3335]
Who: Internship hiring managers
What: Add Suggested security clearance level
Why: To aid the unpaid internship office in their hiring

Acceptance Criteria:
- Add a Suggested security clearance field to the Create internship where target audience is Student
- The field should appear in the "Step 2 - Describe the internship" section after the "Foreign language" section
   - Follow the current design (Font, Color etc)
   - Header: Suggested security clearance
- The values for the field should be:
    -	Low Risk Public Trust Domestic
    -	Low Risk Public Trust Overseas
    -	Interim Secret Domestic
    - 	Interim Secret Overseas
    - 	Full Secret Domestic
    - 	Full Secret Overseas
    - 	Interim Top Secret Domestic
    - 	Interim Top Secret Overseas
    - 	Full Top Secret Domestic
    - 	Full Top Secret Overseas
- The field should not display on the view for the internship applicants to view
- The field is required

Note; Currently security clearance values in USAJOBS are different than in Open Opps.  Question out to leadership on whether we should update in Open Opps.
From State...waiting for additional info:
Based upon a conversation with one of my team members, we realized that we require a suggested security clearance level for the various offices. This information is needed to initiate student security clearance applications. We typically break them up into about nine groups to enter the different security clearance types in groups (example: Full Secret Overseas, Full Secret Domestic, Interim Secret Overseas, etc.). Not having this information would hinder us from being able to take care of this task efficiently.
Is there a way for the opportunity creators to enter the suggested security clearance level gathered in Open Opportunities? 

Note: Currently the individual bureaus are sending this to Khadijah's office in a spreadsheet and she is manually putting this in REETA. This information is to inform the program office of which clearance the student needs so they can initiate the appropriate one.

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-26-29 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 API has already been established between ATP and OpenOpps. Any and all schema changes (new data columns) are immediately available to ATP.

**Comment by Piglady64** [comment]
Julie removed the comment: This field should be included in the API for ATP"  This was holding up the ticket and ATP doesn't currently pull nor display this new date point. All data is already consumable by the pre-established API. (per Brice) Julie will send a message to Brody and Yusuf so they can create a corresponding ticket to display this new data point.

**Comment by Kibrahacha67** [comment]
2-29-29 As per the comments above, hold removed, testing complete moving to review.

**Comment by Piglady64** [comment]
Julie reviewed- moving to final approval
