### ISSUE TITLE
Display loading icons on page loads

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3341]
Who: All system users
What: Display loading icon on all pages
Why: So the user knows the system is processing their request

The following pages should display a loading icon when the page is loading, otherwise the user only sees a header and footer but no indication that the page is loading:
- Create opportunity or internship after target audience is selected
- internship or opportunity saved for later

From bug bash 3/26/19 (Alesia)

**Comment by raywilliams** [comment]
For "internship or opportunity saved for later", which page are you referring to?

**Comment by kbwagner** [comment]
@raywilliams - on the create internship page, enter all of the info, then click "Save for later"
- Or, on the regular opportunity page (not internship), enter info and then "Save for later"

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-4-19 LHammond in testing
Issue: display loading icon stays up for over 5 min even though the page loaded in the back ground.
Steps to recreate:
in ie, click the "+Create opportunity" button from the home page
click on "Students" select "U.S. Department of State..."
Screen goes in to load mode even though the target page loads in back ground (see image below)  moving back to development.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c7604b42-4580-4efc-9e84-1ba7a41c2c5b)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-4-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
6/6/19 - KWagner tested in Test/Chrome
- Create opportunity doesn't have loading icon but is fairly fast.
- All the rest now have loading icon
- Ready for final review.
