### ISSUE TITLE
Bug: Save for later and preview buttons too close

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3343]
Browsers: Firefox and IE
Environment: Test and UAT

Save for Later and Preview buttons on Create internship are too close together

![image](https://user-images.githubusercontent.com/18709918/55433796-1d68aa80-5564-11e9-9b63-24c4b8a5167d.png)

Mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/319309731_Create_-_Unpaid_-Desktop-

From 3/26/19 bug bash

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-31-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed in Chrome and Edge. Spacing is correct. Was not able to test in FireFox due to a bug.  Moving to final approval
