### ISSUE TITLE
Display full name in community dropdown

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3344]
Who: hiring managers
what: Display full name of community in target audience dropdown
Why: In order to make sure the right one is selected

Creating an opportunity   - choose a community dropdown option does not fully display the community name.  Lengthen the display box to show the full name.
- This ticket is for desktop and we understand mobile can't be modified.

From bug bash 3/26/19

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
LHammond in testing

**Comment by kbwagner** [comment]
5/23/19 - KWagner tested in Test/Chrome.  The first time I went in the arrow for the dropdown was missing but can't reproduce now and looks ok.
Ready for final review.
