### ISSUE TITLE
Enhancement: Display field limits on Create for What you'll do, who we are, etc.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3345]
Who: Opportunity Creators
What: Display field size limits when creating opportunities 
Why: To assist with the creation process

Source: From bug bash 3/26/19

Acceptance Criteria: 
- For each large text field on the create opportunity page, display character countdown so users will know the maximum number of characters allowed as well as how many they have left.

- The following fields should display a character count/countdown:
Headline/Title - 100 character limit 
Introduction - 1500 character limit
What You'll Do - 5000 character limit
What You'll Learn -  5000 character limit
Who We Are -  5000 character limit

For the introduction field, remove the sentence "Recommend 100 words or less".

Note: Introduction currently has some opportunities that exceed 1000 characters.  These can be left.  However, if the opportunity is duplicated or edited the limit should be enforced

Regular Opportunity Screen Shot:
![image](https://user-images.githubusercontent.com/18709918/71821878-4ffa8300-3061-11ea-9017-3c64933ff644.png)

Countdown example:
![image](https://user-images.githubusercontent.com/18709918/71823847-3a3b8c80-3066-11ea-8fd7-78d0f8033ef6.png)

Related ticket:
- 4339 - Display field limits for Internship

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-17-20 LHammond in testing

**Comment by kbwagner** [comment]
1/20/20 - KWagner tested in Test/Chrome
Ready for final review
