### ISSUE TITLE
Update Icon on Transcript

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3348]
Who: Student
What: Icon on Transcript
Why: To make iconography consistent with USAJOBS

A/C
- Change the icon for the transcript on the Education & Transcripts to make it consistent with USAJBOS 
- Current icon:
![image](https://user-images.githubusercontent.com/15252970/58588839-94ea4b80-822e-11e9-91f1-85c1c0981954.png)

From USAJOBS:
![image](https://user-images.githubusercontent.com/15252970/58588933-cc58f800-822e-11e9-8749-e44c5f40b437.png)

Note: this came from one of our internal bug bashes

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-10-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@Piglady64 @kbwagner @raywilliams question for the PO.  are you asking for the small image on the side of the box to match (first image) or the whole image to match (second image)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/99ddb3c8-3885-4d81-8463-2ddf82c714d3)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/bb3e7a15-dd4c-4027-a492-803fab001b44)

**Comment by Piglady64** [comment]
@Kibrahacha67 

The small image (first one)
![image](https://user-images.githubusercontent.com/15252970/60974312-db37cd80-a2f7-11e9-9f08-f153c24dc26c.png)

**Comment by Kibrahacha67** [comment]
@Piglady64 - Ok just understand that icon changes depending on what type of document is uploaded.  So different for pdf, wrd, excel, etc...

**Comment by Kibrahacha67** [comment]
7-10-19 LHammond Testing
Testing completed moving to review

**Comment by Piglady64** [comment]
Julie Tested and the icon changes according to the file type. Moving to final approval.
![image](https://user-images.githubusercontent.com/15252970/61150206-e4b86580-a4b0-11e9-837f-06ab612e969f.png)
