### ISSUE TITLE
Change security clearance values to match USAJOBS

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3349]
Who: Internship applicants
What: Security clearance values
Why: To match USAJOBS

Modify the security clearance dropdown on the internship application to match the new values in USAJOBS.  These values will not match the values on the create internship that State has requested.

Order display should match the screen shot to display highest to lowest if possible.  More important is for all of the values to display regardless of order.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/3fe3beab-62da-44e5-b307-fa502e8960ee)

**Comment by Piglady64** [comment]
This ticket is no longer necessary. The Student Internship Program uses different security clearance levels for their interns. It is based off of location and if they are a primary or alternate. They requested we add a "suggested security clearance" field to the create process so they know which clearance to process for each internship opportunity. #3335 

closing this issue

**Comment by kbwagner** [comment]
Reopening - the student values on the apply process are different than the values State has requested in the create process.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-2-19 LHammond in testing
@Piglady64 @kbwagner @bmcorum Question, is the sort order an issue for this ticket?  The Order that is represented in Jobs is completely opposite from open opps.  All of the clearances are there just 180 out.

**Comment by kbwagner** [comment]
@Kibrahacha67 good question.  I just copied what was display in USAJOBS but that doesn't make much sense.  I would say at a minimum mimic what is in USJAOBS.  I would think a logical order would be lowest to highest but I can't even tell you what that is.  So I think for now just mimic jobs

**Comment by Kibrahacha67** [comment]
@kbwagner @Piglady64 @bmcorum - Ok thanks for the information I will have dev's put in order from jobs...

**Comment by bmcorum** [comment]
@kbwagner, @Piglady64 and @Kibrahacha67 USAJOBS does **NOT** provide a sort order for the security clearance codes. So there is nothing I can do to make the application know how to sort them. I can either sort then alphabetically or USAJOBS CodeList API will need to send us a defined sort order.

**Comment by kbwagner** [comment]
@bmcorum @Kibrahacha67 @Piglady64 Julie says the order displayed in the screen shot is correct if we go from highest to lowest.  So order should match screen shot

**Comment by bmcorum** [comment]
@kbwagner I understand as a human we know the level of the security clearances, however their is no data information provided that tells a computer that Top Secret is higher than Public Trust and therefore there is no code I can write that is going to make the list magically sort highest to lowest clearance unless we provided a data attribute that gives the computer a numeric value that it can compare greater than or less than. It is like asking which is greater and apple or an orange.

**Comment by kbwagner** [comment]
@bmcorum so is it a big ask to add a data value for the number?

**Comment by bmcorum** [comment]
@kbwagner that number has to come from USAJOBS. I did notice that at this moment if I sort by code value it will match for the time being. However code values DO NOT change so if we add a new security clearance at some point it will get the next code in sequence and if they security clearance is supposed to fall somewhere in the middle of the list then the order on OpenOpps will be wrong. My recommendation would be that the CodeList API via USAJOBS OpenData need to provide another data point for security clearances that provides the ranking or intended sorting.

**Comment by kbwagner** [comment]
@bmcorum - at this point we just care that the values are the same as USAJOBS.  If the order works for now, that's great.  Thanks

**Comment by bmcorum** [comment]
It might work for now as long as we USAJOBS does not change the current order or add any new clearances. As soon as that happens we will be broken.

**Comment by kbwagner** [comment]
5/2/19 - KWagner reviewed in Testing/Chrome
Values are in reverse order but team agreed this is ok as long as the values match USAJOBS.
Ready for final review.
