### ISSUE TITLE
Home page update - change punctuation

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3350]
Who: Open Opps Users
What: Home page punctuation
Why: So we look smart

From 3/26/19 bug bash:
On the landing page, for the sentence "Building a 21st century government together."
- Remove the comma after government and add a period at the end of the sentence.
![image](https://user-images.githubusercontent.com/18709918/60839304-dc9fb380-a19a-11e9-8a1e-caf155aeb586.png)

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-12-19 LHammond in testing
testing completed in ie, edge, chorme, ff, safari.  Moving to review.

**Comment by kbwagner** [comment]
7/15/19 - KWagner tested in Chrome/Test
Ready for final review.
