### ISSUE TITLE
Admin: unable to approve internships from an old cycle

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3357]
Issue: Currently if the cycle has passed, the delete button displays Need to determine what to do with an internship that is submitted but the apply dates has passed.  Approve doesn't do anything.  Delete acts weird.

Steps to recreate:
Admin --> Community --> DoS
- Clicking Delete gives a message that it can't be deleted but doesn't give any indication of why 
Note: as of 7/8 this seems inconsistent in Test/UAT/Prod and can't test in prod now since it was manually removed by a Footprints ticket.

Regardless of whether the cycle for the internship is current or past the following should be allowed:
1) Internships in Draft, Submitted or approved can be deleted.
- Currently in Test the delete icon does not display for draft and should
2) Internships Open or completed can't be deleted and the delete option should not display.

**Comment by jhanson12** [comment]
Currently, if an internship has a cycle and the current date is after the apply start date, the internship cannot be deleted.

Need to determine a more applicable business rule.  
Do you want to restrict when an internship can be deleted?
If yes, what are the criteria?
Also, to make sure all scenarios are covered, when do you want to allow/need to delete an internship?

**Comment by kbwagner** [comment]
@jhanson12 I think for this one admin should be able to delete until the job is open...after that they can't.  I would also hide the delete once it's open so there isn't any confusion.  So draft, submitted, approved can be deleted but not open or anything past that.
- definitely no deleting once it's live and has applicants.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-2-19 LHammond in testing

**Comment by kbwagner** [comment]
8/26/19 - KWagner tested in Test (and deleted some as requested in prod)
- ready for final review

Internships will stay in approved status until the open date hits.  Regular opportunities will not have approve.
Completed can now be tested
