### ISSUE TITLE
Enforce a 4 digit year in education fields

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3362]
Who: All users
What: Require 4 digit year in all date fields
Why: To stay consistent with USAJOBS

A/C
- Enforce a four digit year in all education date fields.

**note**: This should be the same way USAJOBS collects this information. No mock needed

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-1-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
worked out what the AC meant moving to review.

**Comment by kbwagner** [comment]
5/9/19 - KWagner tested in Chrome/UAT 
Ready for final review.
