### ISSUE TITLE
Bug: Experience data is cleared when I add a reference

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3367]
Actions to Recreate:
1) Select 3 internship opportunities
2) Click "Save and Continue"
3) Add Experience
4) Answer Experience Questions
5) Add references
6) Click "Save and Continue"

Experience stays but all of the questions are cleared

**Comment by tanichacko** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-10-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie - reviewed an moving to final approval
