### ISSUE TITLE
Department of State: Create an email template for the Student Internship Program (Unpaid) Community

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3397]
Who: All Users
What: Email Template
Why: To create a common template that can be used for all Student Internship Program (Unpaid) community emails

A/C
- Use the current Open Opportunities Header
- The footer will read as follows:
To make sure you get Open Opportunities emails to your inbox (and not your spam) add noreply@openopps.usajobs.gov to your address book.

Please do not reply to this message. Replies to this message go to an unmonitored mailbox.

If you doubt the authenticity of a USAJOBS or Open Opportunities email, please visit the USAJOBS site using your browser or read our Help Center article on this topic.

Have Questions or comments? Email the U.S. Department of State Student Internship Program (Unpaid) at StudentInternship@state.gov

**Comment by raywilliams** [comment]
@Piglady64 The email will come from noreply@openopps.usajobs.gov instead of no-reply@openopps.usajobs.gov. Will you please update the A/C? Thank you!

**Comment by Piglady64** [comment]
@raywilliams Done

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**NOTE:** This will work for each email for DoS as we complete the relevant email tickets (draft, submitted, approved, application recieved, etc)

**Comment by Kibrahacha67** [comment]
4-23-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@Piglady64 Question, In the AC the footer reads: 
To make sure you get Open Opportunities emails to your inbox (and not your spam) add noreply@openopps.usajobs.gov to your address book.
Is that correct or should it be 
To make sure you get U.S. Department of State Student Internship Program (Unpaid) emails to your inbox (and not your spam)...

**Comment by Piglady64** [comment]
@Kibrahacha67 all of these emails are coming from Open Opps so it should say "to make sure you get Open Opportunities emails..." All of the emails using this template will be coming from us. The one's in ATP are being sent on behalf of DoS so those have a different footer.

**Comment by Piglady64** [comment]
All of the email have this header and footer - moving to final approval
