### ISSUE TITLE
Joint Duty Program: Default logo as Picture for Community Members

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3398]
Who: Joint Duty Program Community Members
What: Add logo as Picture
Why: The JDP wants their logo to display on all of the opportunities they create within their community instead of their picture

A/C:
- Use the following logo in place of the opportunity creators picture for internships created by members of the community (default logo in place of picture)
![JDP Collateral_Final DHS JDP Logo](https://user-images.githubusercontent.com/15252970/56303742-95a9a100-610a-11e9-8e01-53c949c789a5.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-23-19 LHammond in testing

**Comment by kbwagner** [comment]
4/24/19 - KWagner tested Chrome/Test as System Admin account
- The logo appears correctly on the Opportunity itself but my picture still appears on the opportunity card.
- JDP logo should display on the opportunity card when the opportunity is created for the JDP community.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-25-19 LHammond in testing
completed testing in chrome, ie, edge, and safari.  moving to review

**Comment by Piglady64** [comment]
Julie - the logo is the photo space  
![image](https://user-images.githubusercontent.com/15252970/56831421-06ea0200-6837-11e9-9147-2e19ca98020d.png)

Moving to final approval
