### ISSUE TITLE
Joint Duty Program: Default email

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3399]
Who: Community members of JDP
What: Default email
Why: JDP wants their community email displayed instead of the email of the individual creator

A/C:
- Use the following email as the default for all opportunities created in the JDP community
jointdutyprogramoffice@hq.dhs.gov
- Place the following element in the top of the right rail
<img width="388" alt="Open_Opps_-_Dept_of_State__master_-AB" src="https://user-images.githubusercontent.com/11526811/56526881-dba3a200-651a-11e9-979a-c5893f903042.png">

**Comment by bmcorum** [comment]
Currently we do not have a defined place to display email/contact address on opportunity view pages. Need direction on where to display a support/contact email for community postings.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-24-19 LHammond in testing
@Piglady64 please update the AC to regular opportunity as this is not related to internships
@bmcorum can you give me the location of the link in the email?

**Comment by raywilliams** [comment]
@Kibrahacha67 You'll see the link above the right rail on https://openopps.test.usajobs.gov/tasks/1380. It only shows for DHS opportunities.

**Comment by Kibrahacha67** [comment]
@raywilliams Thanks Ray, it needs to be in the AC waiting for an update.  I see it on the page.

**Comment by Piglady64** [comment]
Julie Reviewed - JDP email is displayed in the right rail

![image](https://user-images.githubusercontent.com/15252970/56831512-46b0e980-6837-11e9-96f5-a8f8cce35bd3.png)


moving to final approval
