### ISSUE TITLE
Remove Duplicate from the Internship Opportunity for student

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3400]
Who: Student
What: Duplicate button on the internship opportunity
Why: Students do not have the ability to create an internship opportunity and therefore, don't need to be able to duplicate 

- Remove "Duplicate" from the internship opportunity for students
- Hiring managers should still be allowed to duplicate internships.

![image](https://user-images.githubusercontent.com/15252970/56317254-45dad200-612a-11e9-8aa1-6308c2826936.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-30-19 LHammond in testing

**Comment by kbwagner** [comment]
5/2/19 - KWagner tested in Chrome/Test
- Tested student account can't duplicate
- Admin can still duplicate

Ready for final review.
