### ISSUE TITLE
Content correction 

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3401]
Who: All users
What: Content change in the "Before you apply" box in the right rail of the internship opportunity
Why: Doesn't sound right he way it is currently written

- Add "the" after the work visit under "For more information"
- Remove the ' after (Unpaid)
  - Should read: Visit the U.S, Department of State Student Internship Program (Unpaid) webiste.

![image](https://user-images.githubusercontent.com/15252970/56317407-ab2ec300-612a-11e9-8178-45e9fcc9daa0.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-1-19 LHammond in testing

**Comment by kbwagner** [comment]
5/2/19 - Kwagner reviewed in test/Chrome
Ready for final review.
