### ISSUE TITLE
GPA should be limited to 2 decimal points on Review page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3402]
Who: Applicants
What: GPA display
Why: to be consistent with the input in application

A/C
- Only display the GPA on the Review page out to 2 decimal points
  - The input box in the application process is limited to 2 decimal points, it should display on the review page with the same requirements

![image](https://user-images.githubusercontent.com/15252970/56317895-e1b90d80-612b-11e9-853f-137da775a22d.png)

![image](https://user-images.githubusercontent.com/15252970/56317866-cf3ed400-612b-11e9-8bb2-91b3bb27c001.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-30-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
FYI, on the Education and Transcript tab, there are two places that GPA can be entered, one is on the form directly which this test apples and the other is in the addition of the degree.  in both cases the format is different and the numbers don't have to match, so there could be a degree that says that gpa is 2.5 and the front page of the application says 3.50.

**Comment by kbwagner** [comment]
@Kibrahacha67 yes we are aware.  We can't change the one on the Education section that comes from USAJOBS.  But the one on the Open Opps page is what goes to ATP and they needed it to be limited to two decimal places.  Not ideal to have differences I agree.

**Comment by kbwagner** [comment]
5/2/19 - KWagner tested in Chrome/Test
Ready for final review
