### ISSUE TITLE
Start Students on the Search Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3403]
Who: Students
What: Start on Search page
Why: As a student I want to start my experience on the Search page

A/C
- Students should go to the Search page upon entry into Open Opps
  - the current flow is for the student to go to their home page first
  - during testing several people couldn't figure out how to get to search
  - After discussing with Tracy and Brice the decision was made to break from USAJOBS and dump the student on the search page instead of their home page (dashboard page)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-30-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed - moving to final approval
