### ISSUE TITLE
Only display first name in navigation header

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3445]
Who: Open Opps users
What: Name display first name only
Why: to be consistent across products
From Bug bash 3/26/19:

Issue:
USAJOBS only displays first name in navigation header
Open Opps displays full name

Acceptance Criteria:
Modify desktop version to only display first name to be consistent with USAJOBS.
Mobile version should also be consistent in displaying initials (first and last)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-1-19 LHammond in testing

**Comment by kbwagner** [comment]
7/2/19 - KWagner tested in Chrome/Test and desktop is fine.
- Test in mobile Chrome and initials display correctly.
Ready for final review.

**Comment by kbwagner** [comment]
7/8/19 - Test mobile safari displays "KL" instead of 'KW".  L is the first letter of my middle name.  Should display first name initial and last name initial on mobile.
Sending back to development

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-10-19 LHammond in testing

**Comment by kbwagner** [comment]
7/11/19 - KWagner reviewed in mobile Safari
ready for final review.
