### ISSUE TITLE
Change wording on "What happens next?" page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3447]
Who: Student
What: link to student landing page on "What happens next?" page
Why: to make it more clear where this link goes - we no longer list the opportunities a student applied to but the internship cycle as a whole

A/C
Change the link from:
"See the internship opportunities I've applied to."

New content:
"See my applications"
![image.png](https://images.zenhubusercontent.com/5b59d12efee5ed0b01c00008/6ad157f1-b09c-4dc7-8425-4f5f654c9f64)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-1-19 LHammond in testing

**Comment by kbwagner** [comment]
5/2/19 - KWagner reviewed in testing/Chrome
Ready for final review.
