### ISSUE TITLE
Department of State: Correct spelling error on Bureau list

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3448]
Who: all users
What: Correct spelling error 
Why: to make listing accurate

A/C
- Change the Bureau name as follows:
Current spelling: ![image.png](https://images.zenhubusercontent.com/5b59d12efee5ed0b01c00008/022ed6e4-966b-48d2-9b4a-5fbc45a405c2)

Should read:
United States Mission to the UN (USUN)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-2-19 LHammond in testing
testing completed moving to review.

**Comment by Piglady64** [comment]
Julie reviewed - moving to final approval
![image](https://user-images.githubusercontent.com/15252970/57105475-d69fd900-6cf8-11e9-9555-574ac083b6c5.png)
