### ISSUE TITLE
Student intern application: GPA field not popping the error message when 201 is entered

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3450]
1. I could enter 201 in gpa field and error message was not showing up
2.If I paste  '2.999999 'it was not stripping to 2.99

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-29-19 LHammond in testing
testing completed moving to review.

**Comment by Piglady64** [comment]
Julie reviewed- issue has been resolved. I put in 3.99999 and it stripped to 3.99 I also put in 201 and it gave me the error message saying I needed to use a 4.0 scale. Moving to final review
