### ISSUE TITLE
Department of State: Change content on "Next Steps" page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3455]
Who: Student
What: Clarify that references are not required
Why: As a student I want to know what is required in my application

A/C
- Step #2 should read
   - Review your experience (this will be bold)
- Under this will be 
    - Tell us about your work, military, or other experience. 

Note: In the mock it says " Review your experience and references" however we need to remove the word "references" Included it for your reference.
https://opm.invisionapp.com/d/main/#/console/15360465/319289299/preview

Public Link:https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
05/3/19 - Mdumas - testing...

**Comment by margaretdumas** [comment]
Mdumas - Passed testing. Moving to review.

**Comment by kbwagner** [comment]
5/9/19 - Kwagner tested in Chrome/UAT
Ready for final review.
