### ISSUE TITLE
New User Flow - No profile page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3461]
Who: New users to both Open Opps and USAJOBS
What: No profile page
Why: To assist new users in determining the next steps to create their profile

Acceptance Criteria:
Issue: The blue "sorry" page is very confusing to users and makes them think they have an error.
- Remove the blue sorry page from the new user flow.
- When a user is new to Open Opps and also doesn't have a USAJOBS profile at all, they will be directed to a new page with requirements as follows:
- Header - no name nor "Guest" will display (This will be a new ticket)
- Other than the name the regular Open Opps header will appear with Logo, Help and search
- Instructional text will display in a teal box with text as follows, "Welcome to Open Opportunities!" and subtext of "Discover opportunities that will help you find new connections, advance your career, and make a difference across government."
- Under the header box there will be a section entitled, "Create your profile"
- Under the header there is additional text that reads, 'It looks like you don't have a USAJOBS profile.  To get started, select the group you belong to."
- Under the Create your profile header there the federal and student hiring paths will display with their associated logo and subtext.
- Federal employee subtext, "Current or former federal employees in the competitive or excepted service."
- Student subtext, "Current students enrolled in, or accepted at, accredited educational institutions from high school to graduate level.  Includes internships, pathways and other student programs.
- The new user must select one hiring path, by clicking on it, to continue.  When a hiring path is selected, it will display as a green box
- There will be a Continue button.  The button will be grayed out until one hiring path has been selected

Continue for a new user will take them to either the federal or student page in the process which are separate tickets.

Invision mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/358534511_Open_Opps_-_No_Profile

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-3-19 LHammond in testing

**Comment by kbwagner** [comment]
5/6/19 - KWagner updated based on new content.
There is now subtext appearing under the header.

@raywilliams - I need to get these updated so can't test right now.  Did you already add the subtext or do I need to send this back for you to add it?  You guys might have caught these in the mocks if you did them late last week.

**Comment by raywilliams** [comment]
@kbwagner The subtext is already under the header and under the header in each button.

**Comment by kbwagner** [comment]
@tlorrison this is ready to be approved.

**Comment by kbwagner** [comment]
@abudz19 - these are now in test if you want to take a look

**Comment by kbwagner** [comment]
@raywilliams this one is missing the text "It looks like you don't have a USAJOBS profile..."

Also, @abudz19 and @bmcorum met and decided to take out the "Guest" on these pages in the navigation.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-8-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
5-9-19 LHammond in testing
Testing completed in uat as test and uat have the same code base.  Moving to review.

**Comment by kbwagner** [comment]
@raywilliams @bmcorum this looks good but i thought we had decided to not display the "Guest' in the header?  

![image](https://user-images.githubusercontent.com/18709918/57739969-9559e280-7683-11e9-9418-6a33a5b9c8e3.png)

**Comment by kbwagner** [comment]
5/15/19 - Entering new ticket to remove Guest/Help/Search from new user from navigation

Moving to final review.
