### ISSUE TITLE
New user flow: Federal hiring path page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3462]
Who: New user who selects Federal hiring path
What: Federal hiring path requirements for Open Opps accounts will display
Why: To provide federal users more information about required fields for Open Opps

Acceptance Criteria:
- When a new user to both Open Opps and USAJOBS clicks on the Federal Hiring page and then Continue, they will be taken to the Federal Hiring page page.  Requirements for this page are:
- The header and green text box will be the same as the previous page (ticket 3461)
- The federal employee hiring path logo and a title of Federal Employee will display
- In bold, the following text will display, "To access Open Opportunities, you need to create a USAJOBS profile.  Make sure you: "
Four bullets will display:
- Choose Federal Employee as your hiring path. (Federal employee should be bold)
- Include your current agency in the Experience section. (Experience should be bold)
- Add your federal email address in the Experience section. (Experience should be bold even thought it's not in the mock)
- Confirm your federal email address - look for the confirmation email in your inbox.

Buttons on the page will be Back and Create your profile
- Back takes you takes you to the initial page where they can select Student or Federal again
- Create your profile takes you to the initial step in the USAJOBS profile creation process (hiring path selection?)

Invision Mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/358534509_Open_Opps_-_No_Profile_3_-_Federal_Friction

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-3-19 LHammond in testing

**Comment by kbwagner** [comment]
5/6/19 - KWagner updated with new content. The text before the bullets and the bullet text has changed.

@raywilliams - can you take a look and see if this needs to go back to development?  Thanks!

**Comment by kbwagner** [comment]
@tlorrison this is ready to be approved

**Comment by kbwagner** [comment]
Ray confirmed this needs to be updated so sending back to development per instructions from Brice.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-7-19 LHammond in testing

**Comment by kbwagner** [comment]
5/7/19 - KWagner tested in Chrome/Test
Ready for final review.
