### ISSUE TITLE
New user flow: Student hiring path

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3463]
Who: New user who selects Student hiring path
What: Student hiring path requirements for Open Opps accounts will display
Why: To provide student users more information about required fields for Open Opps

Acceptance Criteria:
- When a new user to both Open Opps and USAJOBS clicks on the Student Hiring path page and then Continue, they will be taken to the Student hiring path page.  Requirements for this page are:
- The header and green text box will be the same as the previous page (ticket 3461)
- The student hiring path logo and a title of Student will display
- In bold, the following text will display, "To access Open Opportunities, you need to create a USAJOBS profile.  Make sure you: "

Two bullets will display:
- Choose Student as one of your hiring paths. (Student is bold)
- Complete as much of your profile as possible.

- Under the bullet the following text will display, "A complete profile will save you time and effort later. 
 If you apply to an internship, we'll use this information to automatically populate your application(s)."

Buttons on the page will be Back and Create your profile
- Back takes you takes you to the initial page where they can select Student or Federal again
- Create your profile takes you to the initial step in the USAJOBS profile creation process (hiring path selection?)

Invision Mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/358534506_Open_Opps_-_No_Profile_3_-_Student_Friction

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
5/6/19 - kWagner udpated AC based on new content.  The following has changed - text above the bullets, bullets, text below bullets

@raywilliams please confirm whether this needs to go back to development.

**Comment by kbwagner** [comment]
@tlorrison this is ready to be approved

**Comment by kbwagner** [comment]
Ray confirmed this needs to be updated so sending back to development per instructions from Brice.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-7-19 LHammond in testing

**Comment by kbwagner** [comment]
@abudz19 this is in test if you'd like to review.

**Comment by kbwagner** [comment]
5/7/19 - KWagner reviewed in Chrome/Test
Ready for final review

Note: Guest should not display in the header here but I noted that in the original ticket that creates the navigation.
