### ISSUE TITLE
New User Flow: federal hiring path with Incomplete profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3464]
Who: New Open Opps user who has an existing USAJOBS profile with a federal hiring path but the profile is not complete
What: Display a friction page 
Why: To let them know their profile is missing information

Acceptance Criteria:
When a new user to Open Opps but has an existing profile on USAJOBS with a federal hiring path selected but a profile that is incomplete the following requirements apply:
- The header and green text box will be the same as the previous page (ticket 3461) and will display the user's name
- A warning icon will display along with a heading of, "Your profile is missing information."
- Subtext will read, "To access Open Opportunities, you need to update your USAJOBS profile to:"
- Three bullets will display: 
- Include your current agency in the Experience section.  (Experience is bold)
- Add your federal email address in the Experience section.  (Experience is bold)
- Confirm your federal email address - look for the confirmation email in your inbox.

The button on the page will read, "Edit your profile".  Clicking this button will take the user to their USAJOBS profile.

Invision mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/358534508_Open_Opps_-_Incomplete_Profile_-_Federal

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by abudz19** [comment]
This has had updated content since it was written - not sure if there is already a new ticket or not, but heads up that the AC as written will not match the mockup.

**Comment by kbwagner** [comment]
5/6/19 - KWagner updated AC to reflect new content
- Warning title, subtext, and bullet content has been updated

@raywilliams please confirm whether this needs go back to development.

**Comment by kbwagner** [comment]
Ray confirmed this needs to be updated so sending back to development per instructions from Brice.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-7-19 LHammond in testing

**Comment by kbwagner** [comment]
@abudz19 this is in test if you'd like to review.

**Comment by kbwagner** [comment]
@raywilliams for this one - I am using kbwvt+1@hotmail.com, I edited the account to add the federal hiring path in USAJOBS, click return to Open Opps but still get the page that says I don't have a hiring path selected instead of the page that says I'm a fed but missing information.  

Can you check on this?  It's hard to say for sure since I've messed with this account a bit.

**Comment by kbwagner** [comment]
5/7/19 0 KWagner tested in Test/Chrome
Ready for final review.
