### ISSUE TITLE
New user flow:no hiring path selected

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3466]
Who: New Open Opps user, USAJOBS profile exists but no hiring path selected
What: Display a friction page
Why: to provide more information on what information is needed

Acceptance criteria:
When a new Open Opps user that exists in USAJOBS however the system has detected that they haven't chosen a hiring path, the following requirements should be followed:
- The header and green text box will be the same as the previous page (ticket 3461) and will display the user's name
- A warning icon will display along with a heading of, "Your profile is missing information."
- Subtext will read:
Only students and federal employees can access Open Opportunities. Updates your USAJOBS profile to tell us if you're a student or federal employee."
If you're a student:
- Choose Student as one of your hiring paths.  (Student is bold)

If you are a federal employee trying to access Open Opportunities: 
- Choose Federal Employee as your hiring path. (Federal employee should be bold)
- Include your current agency in the Experience section. (Experience is bold)
- Add your federal email address in the Experience section.  (Experience is bold - not bold in mock but follow AC)
- Confirm your federal email address- look for the confirmation email in your inbox.

The button on the page will read, "Edit your profile". Clicking this button will take the user to their USAJOBS profile.

Invision mock: 
https://opm.invisionapp.com/share/ZEPNZR09Q54#/358534507_Open_Opps_-_Incomplete_Profile_-_Unclear

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
5/6/19 - Updated with new content - subtitle and bullet text.

@tlorrison ready to approve

@raywilliams let me know if this one needs to go back to development.

**Comment by kbwagner** [comment]
Ray confirmed this needs to be updated so sending back to development per instructions from Brice.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-7-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
@abudz19 this is in test if you'd like to review.

**Comment by kbwagner** [comment]
5/7/19 - KWagner tested - matches AC

The bullet If you're a federal employee has some extra text than the mock now but meets the AC. Checking with Alex and can write a new ticket to update if needed.

Ready for final review.
