### ISSUE TITLE
New user flow: new Open Opps user who does not have validated email in USAJOBS 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3467]
Who:New Open Opps user who has a USAJOBS account with federal hiring path but no validated email address
What: Display friction page
Why: In order to provide information to the user as to next steps

Acceptance Criteria: 
When a new Open Opps user that exists in USAJOBS with a federal hiring path but no validated email address, the following requirements should be followed:

- The header and green text box will be the same as the previous page (ticket 3461) and will display the user's name
- A warning icon will display along with a heading of, "Validate your email address."
- Subtext will read:
To complete your profile and access Open Opportunities you must validate your federal email address.
1) Check your federal email inbox.  You may need to check your spam folder.
2) Follow the instructions in the email to validate your email address.

The button on the page will read, "Resend validation email". Clicking this button will ? (can we send it from here?)

Invision Mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/359799282_Open_Opps_-_Validate_Email_-_Federal

**Comment by abudz19** [comment]
@kbwagner Closing this per @bmcorum we can't actually detect whether or not they have entered an email at all or just not validated it. Will have to show #3464 instead.
