### ISSUE TITLE
Add last login to the Admin user display

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3469]
Who: Administrators
What: Add last login to admin user display
Why: in order to help address login issues with users

Acceptance Criteria:
1) Add last login to the user table
2) Display last login date for Sitewide administrators
Sitewite --> Users --> Manage - Add a column for Last Login to display to the right of Created

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-7-19 LHammond in testing

**Comment by kbwagner** [comment]
5/8/19 - KWagner tested in Test/Chrome
Ready for final review.
