### ISSUE TITLE
Research usage of OpenID client state option

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#3478]
What: Spike to research usage of the state option for OpenID Connect
Why: Will allow for the application to reduce clicks by being able to return a user to their page or reevaluate the requested action after a login request triggered by navigation or click

Related tickets:
 - Save Star with login #3225

**Comment by kbwagner** [comment]
2/3/2020 - The spike is done.  We know how to use it. If we have issues in the future, new tickets to be written.
