### ISSUE TITLE
Bug: GPA doesn't come over from USAJOBS to Open Opps on Education row

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3481]
Environment: UAT

Steps to Reproduce: 
1) entered information into USAJOBS UAT profile including an education row with a GPA
2) Apply to an internship in Open Opportunities
- Education row comes in but the GPA is blank

<img width="1440" alt="Screen Shot 2019-05-02 at 1 32 42 PM" src="https://user-images.githubusercontent.com/18709918/57094757-4acd8300-6cdf-11e9-82db-31ef1fcb6c16.png">
<img width="1440" alt="Screen Shot 2019-05-02 at 1 31 17 PM" src="https://user-images.githubusercontent.com/18709918/57094763-4dc87380-6cdf-11e9-8da6-1907eebba580.png">

**Comment by kbwagner** [comment]
@bmcorum did you mean to close this?

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
@Kibrahacha67 those are two total different fields. Someone could have multiple education records. There is no place in USAJOBS to list a cumulative GPA. The GPA question in your screenshot is a field that *MUST* be answered by the user. This is *NOT* an auto populated field.

**Comment by bmcorum** [comment]
@Kibrahacha67 the field you have is a required field the user **MUST** fill out. This is **NOT** an auto populated field. There is also no such field in USAJOBS for cumulative GPA. The auto populated GPA fields are only those that are associated with each **individual** education record entry.

**Comment by kbwagner** [comment]
5/9/19 - KWagner tested in Chrome/UAT 
Ready for final review.
