### ISSUE TITLE
Bug: Wrong email displays in apply process footer

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3482]
Environment: UAT

Steps to Reproduce:
1) Apply to internship in UAT
2) Footer displays OpenOpps@usajobs.gov as the email in the footer but should display the 
Visit https://careers.state.gov/

<img width="1440" alt="Screen Shot 2019-05-02 at 1 42 29 PM" src="https://user-images.githubusercontent.com/18709918/57095308-89b00880-6ce0-11e9-9c23-8028f095420a.png">

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
@tanichacko - the open opps footer appears in the What happens next screen at the end of the process and it should also be the State footer.  

![image](https://user-images.githubusercontent.com/18709918/57382972-f3fef800-717b-11e9-8d2c-57219a1456dd.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-10-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed - Footer is correct- moving to final approval
