### ISSUE TITLE
Add a question to the Education Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3486]
Who: Student and DoS
What: Additional Education requirement
Why: DoS would like to screen out applicants based off this question

A/C
- Add the following question to the "Education and Transcripts" page under "Will you continue your education after this internship has been completed?" and before the GPA question
  -  If selected for an internship, will you be able to work between 32 and 40 hours a week for 10 consecutive weeks?
- There will be a Yes and No button
- This information will display on the "review page"
No Mock required

**NOTE** This was brought up when we were testing with DoS on Thursday 5/2/19. They forgot to add this question initially.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-19 LHammond in testing
Testing completed. moving to review

**Comment by kbwagner** [comment]
5/9/19  KWagner Tested in Chrome/Test
- Education question added
- question appears on review page

Julie to write a new ticket to specify new language on review page.

Ready for final review.
