### ISSUE TITLE
Stop Students if they answer "no" to education questions

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3489]
Who: Student and DoS
What: Don't allow students to continue their application if they answer "no" to education questions
Why: DoS doesn't want to see the application if student doesn't qualify due to education questions

A/C
- This is for functionality only there is another ticket for the actual page.
- If the student answers no to any of the following questions they will not be allowed to continue
- If the student answers no to any of the following questions they will be shown the "you are ineligible" page  #3490 
  - Are you currently enrolled (part-time or full-time) or accepted for enrollment in an accredited college or university?
  - Will you be, at a minimum, a college or university junior (i.e. have completed 60 or more undergraduate semester credit hours or 90 or more undergraduate quarter credit hours) by the start of the intern session for which you are applying?
  - Will you continue your education after this internship has been completed?
  - If you are selected for an internship, will you be able to work between 32 and 40 hours a week for 10 consecutive weeks? #3486

**Comment by Kibrahacha67** [comment]
5-9-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed. Moving to final approval
