### ISSUE TITLE
Page when a student answers "no" to education questions

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3490]
Who: Student
What: Modal 
Why: to alert the student that they don't qualify based off of their answers to the education questions.

A/C
Show this pagel when a student answers "no" to the following questions
  - Are you currently enrolled (part-time or full-time) or accepted for enrollment in an accredited college or university?
  - Will you be, at a minimum, a college or university junior (i.e. have completed 60 or more undergraduate semester credit hours or 90 or more undergraduate quarter credit hours) by the start of the intern session for which you are applying?
  - Will you continue your education after this internship has been completed?
  - If you are selected for an internship, will you be able to work between 32 and 40 hours a week for 10 consecutive weeks? #3486

-The page will follow the design of the "Your not eligible because of GPA or Citizenship" page
- The header will be **You are ineligible** 
- There will be a yellow warning box with the following content
  - **Your education status does not meet requirements.**
   - You're not eligible because your enrollment status, completed credits, intent to continue education after you complete your internship,or work availability does not meet the requirements.
- The following content will be in the main body of the page
  - To apply to the U.S. Department of State Student Internship Program (Unpaid), you must: 
    - Be a current student or be accepted for enrollment in an accredited college or university.
    - Be a college or university junior or a graduate student by the start of the intern session for which you are applying.
    - Continue your education after this internship has been completed.
    - Be able to work between 32 and 40 hours a week for 10 consecutive weeks. 

You might be eligible for these student programs: 

**Virtual Student Federal Service (VSFS)**
   Work remotely from your college or university campus through the largest virtual internship in the world. The U.S. Department of State partners virtual interns with more than 60 federal agencies and U.S. diplomatic posts overseas. Learn more about virtual internships. (This links to https://vsfs.state.gov/)

**Other U.S. Department of State student programs**
   The U.S. Department of State has several other student programs for current high school, college or graduate students. Learn about other student programs (This links to https://careers.state.gov/intern/other-programs/)

**Pathways Program**
  The Pathways Program offers federal internship and employment for current students, recent graduates and those with an advanced degree. Learn more about the Pathways Program. (This links to https://careers.state.gov/intern/pathways/ )

- All links will open in a new window

InVision Mock https://opm.invisionapp.com/d/main#/console/15360465/361505804/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-9-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed- moving to final approval
