### ISSUE TITLE
BUG: Spelling error in post/office

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3501]
Found spelling error on Post / office drop down.  
Office of Acacemic Programs (ECA/A)  See image
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/328aa983-bbb1-4310-ac32-6a5d412daeed)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/4f498e6c-c4e0-4802-9782-7f25c907d6f6)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
5/8/19 - KWagner tested Test/Chrome
Ready for final review.
