### ISSUE TITLE
New create account page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3505]
Who: Open Opps users with new login.gov accounts
What: Friction page to link accounts
Why: In order to prevent duplicate accounts from occurring

Acceptance Criteria:
When a user has created a login.gov account for the first time and comes to Open Opportunities, they will receive a friction page as follows:
- Top navigation; There will be no links in the navigation.  The Open Opps logo will appear.  The green Welcome to Open Opportunities bar will display.
- Bottom navigation: The standard Open Opps footer will display

**NOTE: Content on the mock has not been updated.  Follow the AC**
The page will be divided into two sections for New User and returning user.

**New User Section:**
- Header: New user?  Start here.
- magnifying glass icon: Search for new opportunities Search by skill, location, agency and more.

- gear icon: Add skills to your profile  Let people know your areas of expertise and what skills you want to develop.

- comment icon: Make new connections  Find colleagues with similar goals and interests--down the hall or across the country.

There will be a Start button.
- If the user is a student, clicking Start will take the user to the internship search page
- If the user is a federal user, clicking Start will take the user to the federal search page.

**Returning User Section:**
- Header: Returning user?  Link your profile.
- USAJOBS and Open Opportunities now share one profile.  To save your information and link your profile, enter the email address you use for Open Opportunities. You'll get a confirmation email with further instructions. 

Didn't get a confirmation email? Contact us at OpenOpps@usajobs.gov or start as a New user. (bold New user)

Field label: Open Opportunities email address (label might change)
Field: email address entry box
Button: Link profile button
- When Link profile button is selected, the existing process will kick off to link accounts, send an email, etc.

Invision Mock:
https://opm.invisionapp.com/share/ZEPNZR09Q54#/362009695_Open_Opps_-_Create_New_Account_Page_V3

mock with comments: https://opm.invisionapp.com/d/main#/console/15360465/362009695/comments

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-10-19 LHammond in testing
While the page meets the AC I have some questions on the functionality and need to get with Brice on Monday, so I'm putting this ticket on hold until that meeting.

**Comment by bmcorum** [comment]
I broke it. I shall fix it and send it back once I have corrected the issues.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-15-19 LHammond in testing
@bmcorum Question: I encountered the Whoops page (below) when clicking the link accounts button.  I was an account that was linked so I was expecting an error, but not sure if this is the right response.  the other button works as expected so let me know if that was the error screen that you wanted for this error and not a "this account is already linked" error...ty
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/b0607e75-3de1-46d6-b1d2-49d5d7b7b9e4)

**Comment by Kibrahacha67** [comment]
5-15-19 After talking to dev I am going to send this back to development.  When clicking the link button the page is throwing the "whoops" page and not sending email about what happened.  So with that we will move back.

**Comment by Kibrahacha67** [comment]
5-16-19 LHammond in testing
Testing completed moving to review with notes
To test this page the tester will need two new accounts (one student one fed user).
Test will not be valid with old accounts that have had profile changed.
For the first test, clicking the "Start" button will take the user to the first page in the process and will require the Second account be used for the find profile part of the test.
As the second part of the test will be to find profile, you should get email message for the email input to the page.  There is a bug for email confirmation link.  If there are questions please contact Larry or Brice.

**Comment by kbwagner** [comment]
5/29/19 - KWagner tested in UAT
Ready for final review.
