### ISSUE TITLE
Change language on Review Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3513]
Who: Student
What: Language on the ability to work 32 to 40 hours for 10 consecutive weeks
Why: As a student I want the review page to accurately reflect the questions on my application

A/C
- On the review page, the question "Able to work for 10 weeks?" needs to be changed to 
Able to work 32 to 40 hours per week for 10 consecutive weeks.

Note: the requirements is not just to work 10 weeks it is to be able to work 32 to 40 hours for 10 consecutive weeks. The review page should reflect the questions the student was asked in their application.

![image](https://user-images.githubusercontent.com/15252970/57484663-a23b9800-7277-11e9-822e-c3803676c859.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-19 LHammond in testing
Testing completed moving to review.

**Comment by Piglady64** [comment]
Julie reviewed - moving to final review
