### ISSUE TITLE
Internship apply: Remove "not required" as a value for security clearance

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3514]
Who: Student applicants
What: Security clearance value change
Why: To remove field that doesn't make sense

Acceptance Criteria:
- On the application process for internships, step 2 - Experiences and references, modify the values in the Type of Security Clearance field to remove "Not required" as it doesn't make sense to appear here.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-19 LHammond in testing
"Not Required" not removed in the security clearance field (see image below) moving back to development

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/4c1493f0-2172-4ea5-be7d-6c97a4905046)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
5/29/19 - KWagner tested Chrome/Test
Ready for final review
