### ISSUE TITLE
BUG: Administrator can add a Student to the Department of State Community

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3515]
I added Student Rand Paul to the DOS community via the community "manage users" page  This was found in UAT.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/a9790a93-7de3-4ee7-afbc-b9af83f0ab04)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/b9294289-e80e-4d00-ab6d-887f43c0cc60)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/5fede541-7c45-4b18-b781-e9cbcf632c6d)

**Comment by Kibrahacha67** [comment]
Steps to reproduce
Navigate to the administrative site
select Community -- Department of State 
Click + Invite Members
Search for "rand paul" 
Add to community "user 3892"
Rand Paul is a student associated with grapefieldbeach+4stud+5@gmail.com

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
05-15-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
5/15/19 - KWagner tested in Chrome/UAT
Ready for final review
