### ISSUE TITLE
Bug: Applicant able to select save and continue without having 3 selections

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3518]
Environment: UAT
Browser: Chrome

Issue: During the apply process where user selects 3 internships, Save and continue shouldn’t be active until 3 choices are selected AND if I only select 2 and click save and continue, I get a red bar on the 3rd selection but no error message.

Steps to Reproduce:
1) Select apply on an internship
2) Select a second internship to apply to but not a third
3) Select Save and continue
- Red bar displays with no error message

Resolution:
- Disable save & continue until 3 options are selected

Issue found during 5/9/19 bug bash with State

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing.

**Comment by kbwagner** [comment]
5/23/19 - KWagner tested in Chrome/Test
Ready for final review.
