### ISSUE TITLE
Add save star to Internship Card

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3519]
Who: Internship applicants
What: Ability to save from internship card
Why: to prevent having to click into internship

Acceptance Criteria:
- Add the ability for an intern to save an internship to their favorites from the card without having to click into the full internship to click save
- The saved star should appear in the upper right corner of the opportunity card.  The title will be coded so that we have the save star in the top right corner with a buffer of 15 px around it.
- To work like USAJOBS, the save star on the internship card will not appear unless logged in
- Once the star is selected, the star will be filled in and the internship will be saved to the saved section of the user's landing page
- When the star is unselected, it will be removed from the saved section of the landing page.

Requested during 5/9/19 bug bash with DoS

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-5-19 LHammond in testing.

**Comment by kbwagner** [comment]
6/5/19 - KWagner tested in Chrome/Test environment
- unable to test on mobile because internships won't show up - will discuss with dev.
