### ISSUE TITLE
Ability to view internship from saved right rail

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3520]
Who: Internship application
What: Apply for clicking on saved internships to view
Why: to allow interns to view saved internships prior to adding them to top 3

Acceptance criteria:
Background:
- When an applicant has saved internships and begins the application process, the internships display in the right rail of the selection page.
- State has requested the ability for the applicant to click on the internship that they have saved to view the internship again prior to applying.  

Changes:
If you click anywhere on the card besides Select, it takes you to the internship page and you can apply from there. Or you can click Select and it accomplishes the same thing.
- Clicking anywhere on the "Saved" card will open the internship in the same window
- To add the saved internship, the applicant will select the "Apply button" on the internship
- Selecting apply will add the internship to the next available spot and will display a Green check mark and "Selected" beside the saved internship in the right rail.
- If 3 internships have already been selected, clicking on the internship in the right rail during an update process will have the same button logic as the current system to display update, etc.
- mock does not reflect AC - follow AC

Mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/screens/372984499_State_-_Programs_-_Preview_Option_2

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-16-19 LHammond in testing

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested Chrome/Test ready for final review.

@abudz19 tagging you in case you want to take a look at this one.
