### ISSUE TITLE
Bug: Entering USA as a location shows no results

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3521]
Environment: UAT
Browser: Chrome

Issue: Selecting a location of "USA" does not bring back any results when there are internships in the United States

Steps to Reproduce: 
1) On the internship search page, entered USA in the location field and select USA from the autocomplete dropdown and search; "USA" is displayed as a pill
2) no results are found even though an internship from California displayed
- tested in USAJOBS and the pill that was added when "USA" selected from autocomplete was "United States".  Open Opps adds a pill of "USA"

Entered from 5/9/19 testing with DoS

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
5/23/19 - KWagner tested Chrome/Test
USA returns pill of United States
Ready for final review.
