### ISSUE TITLE
Modify security clearance values on Create to match REETA/eQIP

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3524]
Who: Internship creators
What: Security clearance values should match eQIP values
Why: For easy reporting purposes

Acceptance Criteria:

On the CREATE process for internships, modify the security clearance values to be:
None
Classified
Interim Secret
Interim Top Secret
Secret
Top Secret
Top Secret/SCI

They should appear in that order.

The security clearance values in the application should not change.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing.

**Comment by kbwagner** [comment]
5/23/19 - Kwagner tested in Chrome/Test
Ready for final review.
