### ISSUE TITLE
Remove navigation from New User flow

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3525]
Who: New users 
What: Should not be able to navigate away
Why: in order to make sure they complete the new user flow

Acceptance Criteria:
Remove the "Guest", Help and Search from the navigation of the new user flow

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-19 LHammond in testing

**Comment by kbwagner** [comment]
5/23/19 - KWagner tested in Chrome/Test environment
Ready for final review
