### ISSUE TITLE
Applicant Status: Completed

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3526]
Who: Student
What: Status on Dashboard
Why: As a student I would like to know what my status is as an applicant

Statuses:
**Not complete** - when a student is a primary selection and the Hiring Manger does not mark them complete before closing the internship.
**Completed** - when a student is an alternate or primary selection and the Hiring Manger marks them as completed before closing the internship.
**Alternate** - when a student is an alternate selection and the Hiring Manger does not mark them completed before closing the internship

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing
Testing completed moving to review.

**Comment by Piglady64** [comment]
Complete and Not Complete work. I didn't create one where I had more than one person apply so I could not complete the alternate to see the alternate status. Will have to set up another cycle and review this piece of the ticket

**Comment by Piglady64** [comment]
all statuses have been checked. moving to final approval
