### ISSUE TITLE
Bug: Font size for languages too small

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3527]
Internship display - Languages: Font size under description too small
- font size for the description under Foreign Language
![image](https://user-images.githubusercontent.com/18709918/55434221-15f5d100-5565-11e9-8479-19b1a7e33159.png)

From Design: The font size should be the same as the body text of the Opportunity, i.e. the same size as the text in the screenshot that says "for open source research." In the mockup, that would be 17.  So yes, it is too small.

entered from the bug bash on 3/26

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-22-19 LHammond in testing
