### ISSUE TITLE
Bug: Disable Apply Button for Inactive Internship Opportunities

### ISSUE THREAD

**Issue by jonwoody** [openopps/openopps-platform#3528]
![ViewOppLink](https://user-images.githubusercontent.com/19825016/57863731-99dbe380-77c8-11e9-9ad0-a8a4ed1a1ec1.PNG)

Issue: 
Users that have saved the URL for an internship will see the apply button (not logged in) on the internship after the application date has passed.
- Logged in admin users accessing the internship through the community admin page do not see the apply button and it works correctly for them.
 
Ask:
The "Apply" button in Open Opps should be disabled for all types of users in Open Opps when the user clicks on the internship link after the application cycle has closed. (based on the application cycle dates in manage cycle)

Woody's re-creation steps:
1. Logged into ATP UAT as a community member and went to "Video Game Development" review board.
2. Clicked on "view opportunity" on blue header. Link opens new tab and brings up the following URL:  (https://openopps.uat.usajobs.gov/tasks/1000)
3. Saved above URL
4. Create a new student via Login[dot]gov. (FName= Tester, LName= Student, email: testerstudent@aol[dot]gov)
5. Created profile within Login[dot]gov
6. Using the opportunity URL above (https://openopps.uat.usajobs.gov/tasks/1000) and loading it in a new tab, I am able to successfully click apply, log into Open Opps, and begin my application process.

**Comment by Piglady64** [comment]
I don't get the apply button when I use this url.

**Comment by Piglady64** [comment]
![image](https://user-images.githubusercontent.com/15252970/57871960-9cded000-77d8-11e9-9f4c-2d1ce4dbad67.png)

**Comment by kbwagner** [comment]
@piglady64 - it’s because you are logged in. Happens when logged out

**Comment by Piglady64** [comment]
@kbwagner I don't get the opportunity at all if I search for it by name

**Comment by kbwagner** [comment]
@Piglady64 - that's good!  The issue is if a hiring manager in ATP who is not logged into Open Opps but clicks on the internship link from within ATP or a student that might have saved the internship link as a bookmark and clicks on it - not logged in...they will get the internship with the apply button.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-23-19 LHammond in testing

**Comment by kbwagner** [comment]
5/27/19 - KWagner tested Chrome/Test environment
Ready for final review

@jonwoody FYI this issue is resolved.
