### ISSUE TITLE
Ability for System Administrator to Add new community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3530]
Who: System Administrators
What: Create a new community
Why: In order to add a community outside of the release cycle

Acceptance criteria:
Using the design system and design from 2837 (Edit communities), allow for system administrators to add a new community.
- Add an "Add" button and utilize existing form

Related tickets: 
2837 allows for the community member to Edit

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-11-19 LHammond in testing

**Comment by kbwagner** [comment]
7/11/19 - KWagner tested in Test/Chrome
- Didn't save so we didn't have a lot of test communities out there but reviewed other test communities that were saved.
Ready for final review
