### ISSUE TITLE
Create new account page: Linking account sends two confirmation emails

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3534]
When completing the link accounts part of the page, put in your email address and click the add button.  System sent two confirmation emails.  Both emails had different links and neither link worked to verify email.

**Comment by Kibrahacha67** [comment]
@kbwagner - not sure, will test sometime today and make sure.  We can close but want to make sure the back end process is not broken...

**Comment by bmcorum** [comment]
@kbwagner and @Kibrahacha67 I do not think this ticket is relevant anymore due to the removal of account linkage page. All account linkage happens automatically or a new account is created.

**Comment by Kibrahacha67** [comment]
@bmcorum @kbwagner --I would agree.

**Comment by kbwagner** [comment]
Closing - no longer relevant
