### ISSUE TITLE
Transcript: Default radio button if only one

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3537]
Who: Internship applicants
What: Default transcript selection if only one uploaded
Why: To avoid confusion

Acceptance Criteria:
- When an internship applicant selects to upload a transcript and then selects "Refresh", default the radio button to select the transcript IF there was only one uploaded.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-31-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed. Moving to final approval
