### ISSUE TITLE
Transcripts: Modify text on the Education & Transcript page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3538]
Who: Internship applicants
What:  Reading text on transcript page
Why: In order to provide more information on how to upload a transcript

Acceptance criteria:
- Modify the text under the **Transcript** header on the Education & Transcripts page
- Remove Please upload your current or most recent academic transcript. We accept unofficial transcripts
- Replace with:  Please select or upload your most recent academic transcript—this can be an unofficial transcript. If you’re selected for an internship, you’ll need to provide an official transcript before you start.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-31-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed, moving to final approval.
