### ISSUE TITLE
Transcript: Add instructional modal

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3539]
Who: Internship applicants
What: Display a new transcript modal
Why: To explain the upload process

Acceptance Criteria:
- When an internship applicant selects, "Upload transcript", a modal will appear.

- The text will read:

 To upload a transcript, first you need to add it to your USAJOBS profile.  Follow these steps:
 1. Click **Continue**—we’ll send you to your profile in USAJOBS. This will be a new tab in your browser.
  2. Click **Upload document**—you’ll get another pop-up window.
  3. Choose the transcript you want to upload and change the name if needed.
  4. Select **Transcript** as the document type.
  5. Click **Complete Upload**—you’ll see the new transcript in your USAJOB profile.
  6. Go back to the browser tab that says **Open Opportunities**.
  7. Go to the **Transcript** section and click **Refresh transcripts**—you will see the new transcript you uploaded.
  8. Select the transcript you want to include in your application.
  9. Click **Save and continue** to finish your application.

- There will be a **Continue** button on the modal that will take the user to their USAJOBS profile (This will open in a new window)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-31-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed in Chrome - moving to final approval
