### ISSUE TITLE
Remove GeoNames link from Open Opps footer

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3542]
Who: All Open Opps users
What: Remove GeoNames link from footer
Why: Locations are no longer provided by GeoNames

Acceptance Criteria:
- Remove the GeoNames link from the Open Opps footer.  Locations are no longer provided by GeoNames
- Ensure this link doesn't display in the standard or State Dept. Footer

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
5-31-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 we do not control the help center pages. That is handled by the design team.

**Comment by Kibrahacha67** [comment]
Testing completed...moving to review.

**Comment by Piglady64** [comment]
Julie tested in Chrome and Edge.  Moving to final approval
