### ISSUE TITLE
Internship submit - add button to "Create another internship"

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3552]
Who: Internship creator
What: Create another button on submit confirmation
Why: For easy navigation for hiring managers that often create 15-20 internships at a time.

Acceptance criteria:
- When a hiring manager has submitted an internship, they receive a Submitted confirmation modal
![image](https://user-images.githubusercontent.com/18709918/58178540-64297580-7c74-11e9-90ac-342010ecb49b.png)
- Remove the Cancel button as it is duplicative
- Replace the Cancel button with a white button that reads, "Create another internship"
- When the Create another internship button is selected, the Create process will kick off starting with the Who's your target audience page.
- This functionality is not a duplicate.  It is meant to save them steps in having to re-navigate to the create screens.

This was requested by State Department during testing.

**Comment by kbwagner** [comment]
Added ticket 3552

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-4-19 - LHammond in testing
Go the same modal with the cancel button (see image below) moving back to dev
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/8443e6e8-6510-43e4-906a-2ef26c27517a)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-5-19 LHammond in testing
Testing completed moving to review.

**Comment by Piglady64** [comment]
Julie reviewed in Chrome - moving to final approval.
