### ISSUE TITLE
Prevent disabled member of a closed community from duplicating

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3558]
Who: Disabled Community Member
What: Remove capability to duplicate opportunity
Why: When a member is disabled from a closed community they should not be allowed to duplicate an opportunity

A/C
When a member of a closed community is disabled they should no longer have the ability to duplicate an opportunity.

Note: this is an extension of #2836

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-30-19 LHammond in testing
Step 1 Disabled Larry Jammer in test for the DOS community
Step 2 Logged into open opps as Larry Jammer 
Step 3 Search and select internship and duplicated it 
Step 4 Submitted copy of French cooking explained for approval.

Sending back to development...
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/39e90729-b8b6-4809-953a-5bac7469ac7d)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/6bbd6063-3312-48cf-815b-70efe9bb46ed)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/f71147c0-f140-4142-af09-88496cbc4d44)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-1-19 LHammond in testing

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested Test/Chrome
Ready for final review
