### ISSUE TITLE
Department of State OOPs Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3561]
Who: Student applicant
What: OOPs Page
Why: As a student I would like to know why there are no internship opportunities listed.

A/C
- The design should follow the design system and current OOPs pages 
- The header will be **Sorry, there are no internships available right now.**
- The following text will appear under the header:

The U.S. Department of State Student Internship Program is not accepting applications at this time.  Our next available session will be [insert next internship session]. [Sign up for email updates to know when we’re accepting new applications](link to: https://public.govdelivery.com/accounts/USSTATE/subscriber/new).
Learn more about the [U.S. Department of State Student Internship Program] (link to:  https://careers.state.gov/intern/student-internships/)

- All links will open in a new window
- The following sentence is conditional "Our next available session will be [insert next internship session]."
   - If the next cycle has not been created by the CM this sentence will not be visible.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-5-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-5-19 LHammond in testing
Testing completed in safari, ie, edge, chrome, firefox.
moving to review.

**Comment by kbwagner** [comment]
Screen shot: 
![image](https://user-images.githubusercontent.com/18709918/58979721-aab2c000-879c-11e9-8972-4d7ba6021621.png)

**Comment by Piglady64** [comment]
Julie reviewed in Chrome - moving to final approval
