### ISSUE TITLE
People: Revamp Page shell

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3566]
Who: Open Opportunities Users
What: Search for People improvements
Why: to allow users to find People that match a need they might be looking for

Acceptance Criteria:
When a user navigates to the People search, they will see the following:
- Page Header: The page header will appear in a blue bar
- Header: People
- Text: Find people who share similar skills or interests.
- Keyword search default text: Name, skill, job title, career field or agency (keyword search will be a separate ticket). Note: Mock not updated - follow AC
- Location search default text: (not in mock – follow AC) City, state or country

Viewing 1-X of Y (pagination will be a new ticket - 2018)

Sort by: (sorting will be a new ticket 2191)

People Card: New ticket 3568

Right rail – this will be done at a later time

Invision mock: https://opm.invisionapp.com/d/main#/console/16603537/344286038/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner The user of the comma before the word "or" is not consistent in the design or the requirements.  Do  you want it to display this way?
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/b423f5dc-cebc-42dc-8a6c-99eceacafead)

**Comment by kbwagner** [comment]
@Kibrahacha67 remove the comma from the keyword field before "or agency".  The others are right.  

Also, the keyword field is truncated on my Chrome or was this morning but I can't currently get logged out of my student account to see it again.  It cut off and I couldn't see the whole thing.

**Comment by kbwagner** [comment]
@raywilliams FYI this is what I see on my Chrome for Keyword
![image](https://user-images.githubusercontent.com/18709918/60126517-32686a80-975c-11e9-9eb0-8822f2370f88.png)
 The text cuts off and I can't get into the box to see it.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-26-29 LHammond in testing.
Testing completed moving to review.

**Comment by kbwagner** [comment]
6/27/19 - KWagner tested in Chrome/Test environment
ready for final review
