### ISSUE TITLE
People: Keyword search and autocomplete

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3567]
Who: Open Opportunities users 
What: Search for People by keyword
Why: To find people with similar skills and interests

Acceptance criteria:
The keyword box will perform a regular search on the following 
- Name - will display and search against first and last name
- Job Title 

Autocomplete - the following fields can use autocomplete (because they are defined lists in the system) and should be separated into sections in the autocomplete results:
- Skill
- Career field
- Agency

Standard autocomplete rules will be in place:
- autocomplete will start when the user has entered at least 2 characters
- the matching portion of autocomplete will be in bold
- up to 5 results will display in each autocomplete section

- if what you type is matching a skill, career, or agency you get an autocomplete option. If you select something from autocomplete,  create the corresponding pill/filter and apply it
- If you just type and click search then do are just doing a basic relevancy text search on the entire user profile

Invision mock:  https://opm.invisionapp.com/d/main#/console/16603537/344286038/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19 LHammond in testing

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Chrome/Test
Ready for final review.
