### ISSUE TITLE
People: Profile card

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3568]
Who: Open Opportunities users 
What: Search for People and view their profile information
Why: To find people with similar skills and interests 

Acceptance criteria:
- People search results will now display in a card format
Top line of card:
- On the left of the card the person's photo or initials will display
- The person's name will display (preferably only first and last name not including middle but ok if we need to leave middle in for now because it's all one name field).
- Note: The mock has badges on the card but we will not be doing that at this time.  Follow AC.

Second line of card:
- Job title will display

Third line of card:
- Agency | Career Field | Location

Fourth line of card and beyond: 
- Display skills pills from the person's profile.

Note:
- Mock has a saved star - we will not be doing save at this time follow AC
Click anywhere on the card to open the person's full biography

Invision mock:  https://opm.invisionapp.com/d/main#/console/16603537/344286038/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-21-19 LHammond in testing
Testing completed moving to review
Note: confirmed with Brice that the first line in the card name may align with initials if there is no other information in the card.  If the card has other information the name will be a bit higher to allow for the other data.

**Comment by kbwagner** [comment]
@bmcorum i thought we wanted to display the person's photo on the card if possible.  But all are displaying as initials.  Was it determined that wasn't doable?

**Comment by raywilliams** [comment]
photoId wasn't being recorded in Elastic. I added photoId to the Elastic user query.

**Comment by kbwagner** [comment]
@raywilliams sorry not sure why I tagged Brice instead of you!

**Comment by kbwagner** [comment]
@raywilliams the rest of this ticket is good so just let me know when the photo is fixed and I'll check that.

6/25/19 - Katrina Tested in chrome/Test - all ok except for pictures.

**Comment by raywilliams** [comment]
@kbwagner The profile card has been updated.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-219 LHammond in testing

**Comment by Kibrahacha67** [comment]
6-28-19 LHammond in testing

**Comment by kbwagner** [comment]
7/2/19 - KWagner tested in Chrome/Test
Ready for final review
