### ISSUE TITLE
People: Implement elastic search

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3569]
Who: Open Opportunities users 
What: Search for People and view their profile information
Why: To find people with similar skills and interests 

Acceptance criteria:
Implement elastic search into the People search to improve performance and allow for auto complete.

Invision mock:  https://opm.invisionapp.com/d/main#/console/16603537/344286038/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-19 LHammond in Testing
When I type in Keywords search the Search is executed and the word being searched stays in the field.  It can be cleared by backspacing or deleting and search goes back to first search.  But in the Location search the word is wiped out and there is no way to get back to normal without first going to another page.  Question, should pills be displayed for each search executed (keyword, location)?  sending back to development.  
NOTE: I cannot access the design so I cannot verify page set up.
Pagnation ticket:
Search Card ticket: 3568

**Comment by bmcorum** [comment]
@Kibrahacha67 it appears there is a missing requirement for pills. I have added pills into the profile search so you should be able to remove location from your searches moving forward.

**Comment by Kibrahacha67** [comment]
6-20-19 LHammond in testing

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Chrome/Test environment 
Ready for final review.
