### ISSUE TITLE
People: location search and autocomplete

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3570]
Who: Open Opportunities users 
What: Search for People by location
Why: To find people with similar skills and interests

Acceptance criteria:
The keyword box will have autocomplete that will separate results in sections by:
- City
- State
- Country

Standard autocomplete rules will be in place:
- autocomplete will start when the user has entered at least 2 characters
- the matching portion of autocomplete will be in bold
- up to 5 results will display in each autocomplete section

Invision mock:  https://opm.invisionapp.com/d/main#/console/16603537/344286038/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum - for this one I have Paris, Paris, France as my location...but when I do a location search and select Paris, France, nothing is returned.

**Comment by kbwagner** [comment]
> @bmcorum - for this one I have Paris, Paris, France as my location...but when I do a location search and select Paris, France, nothing is returned.

Tracy's profile has Arlington, VA listed as a location. But if I select that from the location autocomplete, I get the oops page and no results.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-26-19 LHammond in testing

**Comment by kbwagner** [comment]
6/27/19 - KWagner tested in Chrome/Test
Ready for final review
