### ISSUE TITLE
Firefox: Create internship: Continue button not showing once Students chosen

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3577]
In Firefox, and creating a new internship or regular opportunity, once either is selected the Continue button is not showing. to reproduce
From home page, click +Create opportunity,
Select either Federal emaployees or Students 
The Continue button does not appear.
Error on page is below in image and if the user goes to the Search page and clicks +Create opportunity then the process works as normal...
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/cfe33962-016e-4176-a1b2-6ec8baf7540c)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-6-19 LHammond in testing

**Comment by kbwagner** [comment]
6/6/19 - KWagner - ready for final review
