### ISSUE TITLE
Handle foreign locations on Open Opps Profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3597]
Who: Open Opps users
What: Display foreign locations on profile
Why: They do not display at all right now

Issue: 
- US locations currently display city, state
- If a foreign location is entered in USAJOBS, nothing displays in the Open Opps Profile

Resolution: 
- If Country is US, do not display United States on the Open Opps profile.  No change.
- If Country is not US, display City, State, Country but suppress any blanks for fields not entered

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-24-19 LHammond in testing.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19 LHammond in testing

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Chrome/Test
Ready for final review.
