### ISSUE TITLE
Bug: New Skills will  not save

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3598]
Who: all OO users
What: New skills tags will not save
Why: As a user I want to add skills that aren't on the list 

Issue: When a user tries to add a new skill that isn't on the list, it will not save.

![image](https://user-images.githubusercontent.com/15252970/59046468-12761300-8850-11e9-9de5-1ee3c3aadbc8.png)

![image](https://user-images.githubusercontent.com/15252970/59046513-2b7ec400-8850-11e9-9032-08bb82e614e4.png)

![image](https://user-images.githubusercontent.com/15252970/59046565-3e919400-8850-11e9-8840-1a6b57555b47.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Chrome/Test
Ready for final review.
