### ISSUE TITLE
Student Application: add same language twice to application

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3603]
Steps to reproduce:
1. Select add language
2. Start typing "spanish"
3. Select Spanish from the list and add skill levels, then save language
4. Follow steps 1-3 again and save

Results: You have the same language added twice. Found in FireFox

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2741d0da-a4e6-41ec-8bc4-3804f8f79110)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-26-19 LHammond in testing.

**Comment by kbwagner** [comment]
6/26/19 - KWagner tested in IE/Test environment

![image](https://user-images.githubusercontent.com/18709918/60191181-ebcd4b80-9801-11e9-866d-f7c8bbda4822.png)

Ready for final review
