### ISSUE TITLE
DoS: Close out Page for Hiring Mangers (internship creator)

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3607]
Who: DoS Hiring Manager
What: Close out process
Why: We need the HM to tell us who completed their internship so we can award the student a badge

A/C
- the Hiring Manger (internship creator) and the community manager will be the only one that will see this page
- The "Before you apply" box will not be visible on this page
- There will be a box at the bottom of the page- between the internship opportunity and the footer
  - the header will read "Selected interns"
  - This information will come from the ATP API
 - All Students in "selected" status (both primary and alternate) will be listed
- There will be a circle with the initials of the selected student
- Under the circle will be the students name
- Under the students name will be a blue ? and the label "Internship complete"
- When the Hiring Manager clicks the label it will change to a green check mark with the label "Internship completed"
- In the bottom left hand column there will be a blue button labeled "Close internship"
  - This button will be inactive until at least one student has been changed to "completed"
  - When this button is clicked the internship will be closed and the status will be changed to "completed"
  - When this button is clicked the user will be presented with a modal #3609 

InVision LInk: https://opm.invisionapp.com/d/main#/console/15360465/367690184/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment]
@raywilliams fyi on this page the names overlap for the Applicants...
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/8310f01f-269d-4986-83a8-638c4741fa2e)

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie reviewed - moving to final approval

**Comment by Piglady64** [comment]
Julie Reviewed. Moving to "final approval"
