### ISSUE TITLE
DoS: Close out confirmation modal

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3609]
Who: DoS Hiring Manger
What: Close Internship Confirmation Modal
Why: We want to make sure that they have completed all of the interns before they close the internship opportunity

A/C
- When the user clicks the "close internship" button they will see a modal
  - Header: Are you sure you want to close this internship?
   - Text under the header: You haven’t marked these interns as completed. If you close the internship, they will not get credit. 
  - The circles with the initials and the names of the students that were not completed will appear under the above text

  - The text under the circles with initials and names will read: Do you still want to close this internship opportunity? Once you close it, you can’t re-open it.
   - There will be two buttons in the lower right hand corner: Cancel and Close

  

- No email will be sent to the student when the internship opportunity is closed. 

InVision link: https://opm.invisionapp.com/d/main#/console/15360465/368187817/preview
Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing

**Comment by Piglady64** [comment]
Talked to Debbie - The A/C says "re-open" but the modal has "reopen". She said this is fine. Moving to final approval.
