### ISSUE TITLE
Bug: Sign out does not always fully sign you out

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3612]
Environment: Test

Browser: Chrome

Steps to Reproduce: 
1) If a user selects Sign out, they receive the blue sign out page
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/51ab1067-8e6c-43bf-9e94-7fc9f8b5a728)

2) If I click "Sign in again", I am taken back into Open Opps and I'm still signed in

- Doesn't always happen

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 please create a new bug for session timeout not properly logging users out in Firefox and Edge please.

**Comment by kbwagner** [comment]
7/8/19 - Kwagner tested in mobile Safari and desktop Chrome.
Ready for final review.
