### ISSUE TITLE
Add question mark/help link on landing page for applicant status help

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3613]
Who: Open Opps users
What: View application status explanations
Why: In order to understand different status updates for my application

Acceptance Criteria:
- Add a "? Help" link on both the student and federal landing page. (see mock - ignore the help beside the applicant status header)  https://user-images.githubusercontent.com/11526811/59625620-c6588780-9107-11e9-93e5-e71ac655c9cd.png
- Help link should open in a new window
- The help content will explain each of the application statuses
- The link for the help content will be: This is the url to use:
https://usajobs.github.io/openopps-help/opportunity/application-status/
- Here's the page in the test 'federalist' site:
https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/application-status/

Related task: https://github.com/openopps/OpenOppsTasks/issues/194

**Comment by bmcorum** [comment]
**ON HOLD** Need to rebuild help center content

**Comment by bmcorum** [comment]
New build of Open Opportunities help center has been deployed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-2-19 LHammond in testing,
testing completed moving to review.

**Comment by kbwagner** [comment]
7/8/19 - Kwagner tested Student page mobile Safari and desktop Chrome; Federal Chrome desktop
Ready for final review.
