### ISSUE TITLE
Bug: Save Star displaying blue on internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3614]
Environment: Test
Browser: Chrome

Steps to reproduce:
1) Log in as a student
2) Click search
3) Select an internship to view in full
4) Click on save star - it turns blue

Follow the design system for saved stars - should be yellow.

Current:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/e2e2cdb1-aed0-41f1-91bc-c0d37faffca4)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-19 LHammond in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested in Chrome/Test environment.  
Ready for final review.
