### ISSUE TITLE
Add ? Help for Internship/Opportunity help content

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3615]
Who: Open Opportunities users
What: Ability to view help content on status
Why: to understand what each status means

- Add "? Help" links on the following pages for internship/opportunity content:
- Admin --> Opportunities  --> Manage
- Community --> Opportunities --> Manage in the upper right of the page
- Agency --> Opportunities --> Manage (upper right of the page)
- Federal landing page in the view opportunities I have participated in section.

- Help should be in the upper right corner like this mock (ignore help beside applicant status header) https://user-images.githubusercontent.com/11526811/59625620-c6588780-9107-11e9-93e5-e71ac655c9cd.png
- The link for the help content will be: Use this URL for production:
https://usajobs.github.io/openopps-help/opportunity/opportunity-status/
Here is the page in the test 'federalist' site:
https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/opportunity-status/

- The help link should open in a new window

Related task: https://github.com/openopps/OpenOppsTasks/issues/159

**Comment by bmcorum** [comment]
**ON HOLD** Need to rebuild help center content

**Comment by bmcorum** [comment]
New build of Open Opportunities help center has been deployed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
@kbwagner Question for you, the design is for the landing page, but the discription of this ticket takes me to both the sitewide and community administration pages for opportunities.  Are you expecting the help to be located by the logo for the community? (see screen shot below) ty
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/b912f941-e52b-4198-aa2a-8cee0a7b55f3)

**Comment by kbwagner** [comment]
@Kibrahacha67 on this screen it might look best maybe in line with the "Opportunities" word or to the right of the completed pill.  Sorry I wasn't more specific on this!

@abudz19 thoughts?

**Comment by raywilliams** [comment]
@kbwagner I thought I confirmed with you and Alex yesterday about the placement of the help link.

**Comment by kbwagner** [comment]
@Kibrahacha67 @raywilliams @abudz19 - sorry yes this is the page Ray checked on yesterday and where he put it is fine and at the top of the page on the right.  He did confirm so ok as is.  I can update the AC to be more clear.  Sorry i was thinking this was the other ticket.

**Comment by Kibrahacha67** [comment]
Ty please update the AC that would make it easy...

**Comment by Kibrahacha67** [comment]
Sorry one more question, What about Agency Admins?  on the community and Sitewide admin pages, doesn't matter which community page you are on the help is there, but on agency not there at all...

**Comment by kbwagner** [comment]
@Kibrahacha67 I had a blanket " in the upper right of the page" but also added the same sentence to the specific page in question.  Let me know if you need more detail.

**Comment by kbwagner** [comment]
@Kibrahacha67 yes it should be on agency admin as well...but I didn't spell that out so @raywilliams let me know if you need a new ticket?

**Comment by Kibrahacha67** [comment]
7-2-19 LHammond in testing,
Testing completed moving to review.

**Comment by raywilliams** [comment]
@kbwagner, I let @Kibrahacha67 know that I would just check in the changes to let the help link show on the agency manage opportunities page too. No need for another ticket.

**Comment by kbwagner** [comment]
thanks @raywilliams - I updated the AC.

**Comment by Kibrahacha67** [comment]
Testing completed moving to review.

**Comment by kbwagner** [comment]
@raywilliams on mobile the help link is just slightly cut off (Safari)...not a big deal but if it's easily fixable would be nice to fix.  Thanks!
![help link](https://user-images.githubusercontent.com/18709918/60844758-4c686b00-a1a8-11e9-94fd-23c438ce67c9.jpg)

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-10-19 LHammond in testing,
Tested in Safari, moving to review.

**Comment by kbwagner** [comment]
7/10/19 - KWagner tested in Safari mobile/Test
Ready for final review.
