### ISSUE TITLE
DoS: Update Student Profile Page with Badges

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3619]
Who: Student
What: A place to display their badges
Why: as a student I would like to see the badges I have earned.

A/C
- Add a box in the right rail of the student profile page
- The header in the box will be : Badges
- Show all badges the student has earned up to 3 (#3001)
- Use the same design currently in production for profile page

Note: No design needed

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing
Testing completed moving to review

**Comment by Piglady64** [comment]
@kbwagner This box is visible. Since this one isn't about the numbers here is a screenshot if you want to move this one 
![image](https://user-images.githubusercontent.com/15252970/64462434-605c1a80-d0ce-11e9-9b8a-979bb178cadf.png)

**Comment by Piglady64** [comment]
@kbwagner I have sent the other badge ticket back to development. This one is for the container in the right rail. It is there and has the badges. However, this tickets says "up to three" which I haven't tested. Should this be part of this ticket or does it go with #3001. If it does not go with this ticket we can move this to final approval.

**Comment by kbwagner** [comment]
@Piglady64 fine to move forward. Thanks!

**Comment by Piglady64** [comment]
The container in the right rail is correct. Moving to final approval.
