### ISSUE TITLE
Mobile: Adding filters not being counted in filter display

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3626]
If I add a filter, the pill displays but the filter count on the mobile browser does not increment.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19 LHammond in testing
Testing completed in safari (mobile), moving to review

**Comment by kbwagner** [comment]
6/25/19 - KWagner tested Chrome/Test environment 
Ready for final review
