### ISSUE TITLE
Bug: Prod: -	Enter all education information and save it. Education record not saving..

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3635]

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-20-19 LHammond in testing
When trying to add education data, the dropdown for Degree or level attained would not drop down and give selections.  Focus seemed to stay in the Country field.  moving back to development

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-24-19 LHammond in testing

**Comment by kbwagner** [comment]
6/20/19 - KWagner tested Chrome
Ready for final review.
