### ISSUE TITLE
Bug: Prod: On internship card, location didn’t show 

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3636]
Once the internship was opened then Location showed (London)  But from the search page user could not see the location was (undefined).

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing. **NOTE:** this fix is currently in TEST

**Comment by Kibrahacha67** [comment]
6-26-19 LHammond in testing

**Comment by kbwagner** [comment]
6/27/19 - KWagner tested in test environment.
Ready for final review.
