### ISSUE TITLE
Education page, on the transcript, blank square and small Word icon beside it (mobile)

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3643]
On the Education page, in the transcript, I’m seeing a blank square and then a smaller Word icon beside it. I’m looking at it on my iPhone.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-25-19 LHammond in testing

**Comment by Piglady64** [comment]
@abudz19 I think the first one with the report in the body of the messaging is better. 
The other one looks orphaned over there by itself. We already have the user reading down the page no need to ask them to look somewhere else (even though it is in the right rail) to find the rest of the information

**Comment by abudz19** [comment]
@Piglady64 Moving this comment to ticket DoS #101

**Comment by kbwagner** [comment]
6/25/19 - KWAgner tested mobile Safari Test 
Ready for final review
