### ISSUE TITLE
Bug: ignore casing on email addresses when linking USAJOBS and OpenOpps emails

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3652]
Who: any User
What: ignore case of email address
Why: So the user can quickly and easily link their OO profile to their login account 

A/C
- When a user is linking their OO and USAJOBS profile ignore the casing in their email.

Note: when a user types Julie.Jackson@gmail.com and the system has julie.jackson@gmail.com they are not getting the confirmation email because the system doesn't recognize these as the same.

**Comment by bmcorum** [comment]
## Before One Profile (accounts in USAJOBS and Open Opportunities **not** linked) 
### USAJOBS
![image](https://user-images.githubusercontent.com/1165615/60454108-fc663300-9c00-11e9-80a1-e7030dcb6837.png)

### Open Opportunities
![image](https://user-images.githubusercontent.com/1165615/60454203-3fc0a180-9c01-11e9-9968-6f9be59251db.png)

**NOTE:** Email addresses are different casing

## After One Profile (accounts in USAJOBS and Open Opportunities linked) 
![image](https://user-images.githubusercontent.com/1165615/60455315-148b8180-9c04-11e9-88cc-7a490632bf6f.png)

**NOTE:** The username was changed to the Login.gov email and the government uri was updated successfully and my account was linked without issue.

**Comment by Piglady64** [comment]
@bmcorum thanks for the artifacts. moving to review

**Comment by Piglady64** [comment]
This ticket is difficult to test without everyone resetting their accounts. Brice provided screen shots above to prove the fix worked. Moving to final approval.
