### ISSUE TITLE
Require new approval when community changed

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3659]
Who: Community users
What: Require a change in a community to be approved 
Why: to make sure the correct approver has reviewed the opportunity

Acceptance Criteria: 
- If the community of an opportunity in any status past submitted is changed, the status of that internship/opportunity should change back to submitted.  Must be approved again prior to being posted.  
- An email should be sent to the community manager to indicate that there is a submitted opportunity to approve. (same email as current)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-2-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
7-16-19 Talked to Brice and this is correct. moving to review.

**Comment by kbwagner** [comment]
7/21/19 - KWagner tested in Chrome/Test
Ready for final review.
