### ISSUE TITLE
Community Admin - change field label from Publish to Approve

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3663]
Who: Student communities
What: Admin language change from Publish to Approve
Why: In order to avoid confusion

Acceptance Criteria:
- Where target audience = Student
- On the Community Admin --> Opportunities --> Manage 
- Change the column title of "Publish" to "Approve"

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/533220c9-d00c-49a4-ae24-cf2356fb471d)

Related ticket: 3664 - change text on modal

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-1-19 Lhammond in testing

**Comment by kbwagner** [comment]
7/8/19 - KWagner tested in Test/Chrome
Ready for final approval.
