### ISSUE TITLE
Community Admin: Update approved modal to change Publish to Approve

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3664]
Who: Community Admin
What: Change the verbiage from Publish to Approve
Why: To avoid confusion

Acceptance Criteria:
- where community target audience is student
- Update the modal when the community member clicks the Publish (changing to Approve in ticket 3663) update the modal text to change Publish to Approve
- Title Confirm approval
- Are you sure you want to approve <title>?
- Buttons would be Cancel and Approve
- Non student communities will not change.

Current modal:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/44e94a75-97a7-4009-8e2b-bc0220a16f60)

Related tickets: 3663 - change admin from Publish to Approve

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-1-19 LHammond in testing

**Comment by kbwagner** [comment]
@raywilliams modal should be titled "Confirm approval" but currently says "Confirm approve"

![image](https://user-images.githubusercontent.com/18709918/60844117-630dc280-a1a6-11e9-8d22-cd8e0d183bfc.png)

Sending back to development.

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-11-19 LHammond in testing

**Comment by kbwagner** [comment]
7/11/19 - KWagner reviewed in Chrome/Test
Ready for final approval
