### ISSUE TITLE
Profile: If no federal email, show Open Opps email

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3666]
Who: Open Opportunities users
What: Display current Open Opps email address
Why: So they can be contacted

Issue:
- Open Opps users have applied to opportunities but have not yet logged in to link to login.gov/USAJOBS therefore their federal email address does not show on their profile
- Or, someone is searched and found in People search, but they have not logged into login.gov/USAJOBS their email address will not display on their profile

Acceptance Criteria:
- The following changes should be made to both the profile and the people display
- If no federal government email address is available, display the users's current Open Opps email address with a label of Email.
- Once they have logged on and linked their accounts, only show their official federal government email address.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-3-19 Talked to dev about the state of email addresses and how we need to test this ticket.  There is a transition of data on this ticket that will be supported by artifact.  As such there will be email addresses in the system that don't line up until the user logs in and inputs the new address associated with the .gov account that is verified by the system.

**Comment by bmcorum** [comment]
Below is sample of 20 users from the TEST database. The first 10 users are those who **have not** synced/logged in after the initial Login.gov release for whom we do not yet have a **verified** government email (government_uri). The last 10 users are those who **have** synced/logged in after the initial Login.gov release for whom we do have a **verified** government email.

![image](https://user-images.githubusercontent.com/1165615/60598724-34918100-9d7b-11e9-824e-2ebaae033222.png)

**Comment by Kibrahacha67** [comment]
7-3-19 LHammond in testing

**Comment by kbwagner** [comment]
7/8/19 - KWagner reviewed artifact.
Ready for final review.
