### ISSUE TITLE
Update application modal for non students to encourage them to add profile info

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3667]
Who: Open Opportunities applicants (non student)
What: Additional information on the submit application modal
Why: To encourage them to enter biography and skills 

Acceptance Criteria: 
- When someone applies to an opportunity that is not a student, display additional information on the confirmation modal to remind them to add a biography and skills.
- The text on the modal should now include another checkmark that reads, "I've updated my profile, including my biography and skills (optional, but recommended)."

Current modal:
![image](https://user-images.githubusercontent.com/18709918/60205077-4bd1eb00-981e-11e9-9a9b-3883160da2e9.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-1-19 LHammond in testing.
testing completed moving to review.

**Comment by kbwagner** [comment]
7/2/19 - KWagner tested in Chrome/Test
Ready for final review
