### ISSUE TITLE
DoS Footer: Visit DoS link should open in new window

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3669]
Who: DoS users
What: Open "Visit" link in new window
Why: So interns don't lose where they were

Acceptance Criteria:
- Wherever the State Department logo displays (internship search, internship apply) the Visit link should open in a new window

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/bf2ef519-3253-4483-833d-e3e50e3c675e)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-1-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
7/8/19 - KWagner tested Chrome/Test
Ready for final review.
