### ISSUE TITLE
Change all emails in Open Opps to go to the Official federal government email address

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3672]
Who: Open Opportunities users
What: All emails should go to federal government email address
Why: in order to ensure federal users are getting emails

Acceptance Criteria:
- Student emails should continue to go to the email the student uses for login.gov
- Any emails going to non students (Hiring managers, community managers, etc.) should go to the official government email address on the user's profile.  If no official federal government email is available, then and only then use the login.gov email address for emails.

**Comment by Piglady64** [comment]
@jhanson12 We just got a FP ticket about this. Just want to make sure this is something that you are still working on. It hasn't gone out yet.

**Comment by jhanson12** [comment]
@Piglady64  I just checked in the code updates.  Tough to test and took a bit to get through.  We have 27 email notifications and the data comes from different queries.  Testing will take a bit of time.  Thanks!

**Comment by jhanson12** [comment]
@Kibrahacha67  and @margaretdumas  this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-23-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-1-19 LHammond in testing
