### ISSUE TITLE
Modify email shown in add member to community dropdown to be federal email

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3673]
Who: Open Opps community admins
What: show federal email address when adding to a community
Why: for consistency and simplicity 

Acceptance Criteria:
- Admin --> Community --> Users --> Manage users --> Add members
- on the dropdown to add community members, only the federal email address should display for each user (not login.gov)

![image](https://user-images.githubusercontent.com/18709918/60298652-fa4a5e80-98f8-11e9-8452-31d27b8ba4b5.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-2-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
Attached is the artifact that Brice used for ticket 3666.  It is the same information needed to test this ticket.  Talked to Jodi and she agrees to use this artifact.  
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/3b4eedf3-5c50-4532-8b6e-d9266618a32d)

**Comment by Kibrahacha67** [comment]
7-8-19 LHammond in testing.
found that Sheldon Cooper had both gmail address and opm.gov address (image below) as per the AC should only have the opm.gov address in the drop down to add members...moving back to development.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ef959d31-acfa-4927-8ef8-68fdfdadd20b)

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-9-19 LHammond in testing

**Comment by kbwagner** [comment]
7/9/19 - KWagner tested Test/Chrome using artifact
Ready for final review.
