### ISSUE TITLE
Modify landing page/home page to only display first name 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3675]
Who: Open Opps users
What: Display only first name on landing page
Why: To be consistent across our platforms

Acceptance Criteria: 
- On the landing page for students and federal users, only display the user's first name to be consistent with USAJOBS.
- This should be consistent for mobile and desktop

![image (22).png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/53b27b1c-9c13-486d-9c64-89c3f0187bd8)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-1-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
7/2/19 - KWAgner tested landing page on Desktop
- Need to test mobile when Akamai white page issue is resolved.

**Comment by kbwagner** [comment]
7/8/19 - KWagner tested on Safari mobile 
Ready for final review.
