### ISSUE TITLE
Update profile to only display first and last name

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3676]
Who: Open opportunities users
What: Display only first and last name in Open Opps profile
Why: To be consistent across products

Acceptance Criteria:
- The USAJOBS profile only displays first and last name on the profile regardless of whether I have entered a middle name.
- The Open Opps profile currently displays first middle and last name on the profile
- Modify Open Opps to only display first and last name on the profile

USAJOBS Profile:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/88d4da49-c46f-4737-8765-ec0954ff2b1c)

Current Open Opps profile: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/073438e3-0c98-4384-91b9-082adebd2bb5)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-1-19 LHammond in testing

**Comment by kbwagner** [comment]
7/2/19 - Kwagner tested Chrome/Test
Ready for final review
