### ISSUE TITLE
on FF or EDGE, Application will let user directly in if the session times out

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3686]
If I let the application time out and I click "Sign in again", I am taken back into Open Opps and I'm still signed in In FF or Edge  See ticket 3612

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready to test.

**Comment by Kibrahacha67** [comment]
8-1-19 LHammond in testing
in Edge, the browser didn't let the user back in, but the Akami page was thrown (see below)
in ff after the page timed out and the sign in again link was clicked the application let the  user back into open opps.  moving back to development.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ef7feb7c-dd94-4d51-b8ef-02d9810b78a9)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready to test.

**Comment by Kibrahacha67** [comment]
8-2-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing
Testing completed in ie, edge, ff, chrome.  moving to review.

**Comment by abudz19** [comment]
@kbwagner these all worked fine for me except I don't have IE to test in.

**Comment by abudz19** [comment]
Okay to close?

**Comment by kbwagner** [comment]
@abudz19 for these you don't close - you just note that you tested and move to final review.  So just drag and drop to the final review column in Zenhub...then Tracy tests and closes. Thanks!!!
