### ISSUE TITLE
DoS: Email with Survey link for Applicants

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3702]
Who: Student
What: Survey Email
Why: The Internship program would like to send out an email with a survey monkey link to students after they complete their internship

A/C
- Use the OO email template
- This email will only go out to those students that have been marked "internship completed" during the close out process

**Subject**: U.S. Department of State Student Internship Program (Unpaid) - Thank you and please complete a survey

**Trigger**: When the Hiring Manager closes out the internship.
**Audience**: Student who completed the internship
**Content**:
Hello <Applicant/Student name>,
Congratulations on completing your internship with the U.S. Department of State Internship Program (Unpaid). Thank you for your hard work—we hope you gained valuable work experience and made connections while completing this internship.
Please take a moment to complete this quick survey–your feedback will help us improve the internship program.

[Start the Survey](https://www.surveymonkey.com/r/2P65W6Z)

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing,
Testing completed moving to review.

**Comment by Piglady64** [comment]
I received the email and it is correct. The link worked in the email Moving to final approval
