### ISSUE TITLE
DoS: Email with  survey link to Hiring Manager

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3703]
Who: Hiring Manager
What: Email with survey monkey link
Why: The Internship Program would like to send out an email with a survey monkey link to hiring managers at the end of the cycle.

A/C
- Use the OO email template
- this email will go out when the hiring manager closes the internship 

**Subject**: U.S. Department of State Student Internship Program (Unpaid) – Please complete a survey 
Trigger: When the Hiring Manger closes out the internship
**Audience**: Hiring manager who managed the internship selection process
**Content**:
Hello <Insert Hiring Manager name>,
Thank you for participating in the U.S. Department of State Student Internship Program (Unpaid). We appreciate you helping to review and select the interns.

Please take a moment to complete this quick survey about your experience–your feedback will help us improve the internship program.

[Start the Survey](https://www.surveymonkey.com/r/YYYB5ZS )

**Comment by Kibrahacha67** [comment]
8-6-19 LHammond in testing
Testing completed moving to review.

**Comment by abudz19** [comment]
Looks good, moving to final approval.
