### ISSUE TITLE
User data (federal email address) not populating on all pages

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3706]
Hermione Granger - if searched through People search brings back two different records.  Both have the same federal email address showing on the screen.  IF the records are opened the federal email address is the same only difference in the records is the skills.

If as an Administrator you navigate to the community - select DoS and then manage users the record for Hermione Granger shows once with no federal email address shown.  We know from the artifact attached to 3666 that this person has signed into the system so looks like federal email address is not populating through the system.  Images below
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/29da9b7f-5661-4c6a-b492-a85f71798f39)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/367eb107-1e37-42cd-ad4c-83110b298fc8)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/dbde9102-6d2e-4e41-aba5-8f08754f5d0b)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/e6fd397e-469a-4229-b466-e5e283d6b078)

**Comment by bmcorum** [comment]
@raywilliams if governmentUri show it. If not use username but change label to 'Contact email'

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-5-19 LHammond in testing
