### ISSUE TITLE
Filtering does work for - Admin Active Members

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#3732]
Filtering does not work from the admin section.

1. Navigate to Admin 
2. Navigate to Community > Department of State
3.  Select Manage members
4.  Type in either a name or agency to filter by

Results:  Filtering does not show anything

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-17-19 LHammond in testing

**Comment by kbwagner** [comment]
7/17/19 - KWagner tested Chrome/Test
Ready for final review.
