### ISSUE TITLE
Bug: Add skills button overhangs container on profile page

### ISSUE THREAD

**Issue by raywilliams** [openopps/openopps-platform#3736]
- Add skills button overhangs its container on the profile page
![image.png](https://images.zenhubusercontent.com/5a6f64004b5806bc2bc4be2c/347a1c5c-dde8-4c24-bae2-9da6e991d474)

- Edit skills button is out of place on the profile page
![image.png](https://images.zenhubusercontent.com/5a6f64004b5806bc2bc4be2c/9ed404e9-4652-460e-a586-68f767b43ebc)

- A border shows under the skills on mobile
![image.png](https://images.zenhubusercontent.com/5a6f64004b5806bc2bc4be2c/9daf89ef-f6e1-41cc-92c1-59ac72f62c22)

**Comment by raywilliams** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-26-19 Lhammond in testing
testing completed moving to review

**Comment by kbwagner** [comment]
7/26/19 - KWagner tested in Chrome/Test
Ready for final review.
