### ISSUE TITLE
Bug: Create new user doesn't take user to full landing page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3737]
environment: Production

Issue:
- Creating new user in new user flow shows them welcome page without top navigation

Steps to Recreate:
1) When a user gets to the new user page in Open Opps they can select to link their account or create new.  When they click create new they are taken to the welcome page.
- Welcome page doesn't have any top navigation
- Clicking the Open Opps logo takes them to the sign in page where they have to sign in again.
- Clicking refresh seemed to work for some users

See photo:

![Image from iOS (2)](https://user-images.githubusercontent.com/18709918/61245604-e71df800-a71a-11e9-8596-3634fccfbe58.jpg)

**Comment by bmcorum** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-1-19 LHammond in testing
