### ISSUE TITLE
Bug: Community Admin should not have the ability to add a new community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3738]
Environment: Production

Steps to reproduce:
1) Log in as someone who is ONLY a community administrator
- Add new community button is available

Only sitewide admniistrators should be able to add new communities.

Found during 7/15/19 State login party.bug

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
7-17-19 LHammond in testing

**Comment by kbwagner** [comment]
![image (24)](https://user-images.githubusercontent.com/18709918/61976187-10f7da00-afb9-11e9-9a16-a2ede591f4fb.png)
 
7/26/19 - KWagner tested in Test/Chrome (Julie's account)
Ready for final review.
