### ISSUE TITLE
Bug: Community Manager cannot click on "Manage community" link

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3743]
As a Community Manager, I click on the manage community link and it takes me to the manage community edit page for a sec and then takes me to my home page.  Found while testing ticket 3738.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing
