### ISSUE TITLE
Bug: Open Opps Profile: Location not displaying correctly

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3745]
Location name not displaying correctly, object displaying instead image below.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/134a3ceb-3a55-40e9-8efa-97c7d2267a43)

**Comment by bmcorum** [comment]
## Prior to code fix
### Profile
![image](https://user-images.githubusercontent.com/1165615/62068701-902d1e00-b204-11e9-81f5-25e3264b6863.png)
### Attempt to apply to an opportunity
![image](https://user-images.githubusercontent.com/1165615/62068759-b652be00-b204-11e9-989a-5561e6b14dd9.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is a hot fix to 7.8 and is ready for testing in UAT.

**Comment by Kibrahacha67** [comment]
7-30-19 LHammond in testing

**Comment by kbwagner** [comment]
7/30/19 - KWagner tested in Safari/mobile
- able to view location as a new user and apply for an opportunity.
@tlorrison ready for final review.
