### ISSUE TITLE
Open Opps modifications to allow contractors

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3754]
Who: Contractors
What: Allow entry into Open Opportunities
Why: because many contractors do work for the federal government that may require them to have access to Open Opps

Acceptance Criteria:
In some situations, contractors doing work for the federal government should be allowed access to Open Opportunities.

Contractors must have:
- federal government email address that has been confirmed
- they have not indicated they are a current federal employee
- they have indicated they are a contractor
- Users trying to gain entry into Open Opps will be allowed an flagged as contractors 

What can a contractor do?
- Create an internship/opportunity
- can be a community member or manager
- can be a system admin

What can a contractor not do?
- Apply for an opportunity or internship opportunity

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-3-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-4-19 LHammond in testing

**Comment by bmcorum** [comment]
@kbwagner and @tlorrison we currently do not have any way to have a single account with multiple types (I.E. I am either a fed, contractor, or student) I can only be one and not a combination. If this is a new requirement we will need a ticket to examine all the necessary changes to do such as the home page for feds, contractors and students are very different.

**Comment by kbwagner** [comment]
@bmcorum removed that sentence in the AC and added a note to a different ticket that allows for multiple hiring paths for users.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-6-19 Since the AC has been updated and the other tests for this requirement have passed moving this to review.

**Comment by kbwagner** [comment]
9/10/19 - KWagner tested in chrome/Test
Ready for final review.
