### ISSUE TITLE
Admin Dashboard Section 2: Top Contributors - Participating in Opportunities .csv download

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3756]
Who: System administrators
What: download top contributors for participating in opportunities
Why: So we can provide the report to others

Acceptance Criteria:

Acceptance Criteria:
Administration --> Sitewide --> Top contributors --> Top Contributors report

At the bottom of the Top contributors Opportunities created section, there will be a Download full list (.csv) link. When selected, the following will display in a downloaded .csv file:

- the report name will be: TopContributors_FYXX_Participated.csv 
- Display rank number, agency name, total number participated
- All will display in the file not just the top 5.  

Mock: Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-5-19 LHammond in testing

**Comment by kbwagner** [comment]
9/10/19 - KWagner tested in Chrome/Test
Ready for final review
