### ISSUE TITLE
Bug: Badges awarded for just applying for an opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3757]
Environment: Production
Browser: All
Issue: User Kevin Nooney kevin.nooney@dot.gov was recently awarded a "Game Changer" badge for "completing five tasks"; however, has only completed only two tasks. Applied to five tasks, but was selected for two.

Resolution: Game changer badge should only be awarded when applicant is selected as a participant for 5 opportunities
2) If possible, remove the game changer badge for Kevin and anyone else who should not have been awarded the badge.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

Completed opps badges
1 = Newcomer
3 = Maker
5 = Game Changer
10 = Disruptor
15 = Partner

**Comment by Kibrahacha67** [comment]
8-1-19 LHammond in testing

**Comment by kbwagner** [comment]
8/26/19 - KWagner tested test/Chrome
Ready for final review
