### ISSUE TITLE
Create the ability for Opp Creators to collect a list of all applicant email address. 

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#3760]
Who: Open Opportunities Creators
What: Ability to email multiple applicants
Why: To save time

Acceptance Criteria: 
Add the following links to the View opportunity page that will only be visible to the opportunity creator and sitewide administrators: 
- Email all applicants (link below the applicant header)
- Email all participants (link below the Assigned participant header)

Links should appear regardless of what status the opportunity is in (open or in progress)

Links will be mail to links (a link with an envelope icon beside it would be helpful) that opens up a blank email in the user's email program and will dump all emails from the selected category into the email to box.  The creator will manually then enter a subject and content and send.

Initial Request:
It can be very time-consuming for the opportunity creators to send individual emails to applicants.  It would be good to be able to send out one email at the same time.  

This has been a suggestion by multiple Opportunity creators.

**Comment by bmcorum** [comment]
@LisaLNelson I am a bit confused by this since we do not have any functionality in the system that lets opportunity creators email any applicants directly. They have to use their own email service (Outlook, Gmail, Yahoo, etc). The opportunity creator simply needs compose their single email as they do currently and include all intended recipient email addresses.

**Comment by LisaLNelson** [comment]
@bmcorum The issue comes from TC's who have selected a large group of people to work on their opportunity. They would like an easy way to pull the email addresses of the people selected so they can email them without have to go back and forth between multiple screens to collect the email address. If you have multiple people the TC has to click on each name copy the address, paste it in their email service, click back to the opportunity, click on the next person go into their profile, copy their address, paste in their email service and so on.  It's not about creating an email, it's about an easy way to collected the addresses. Make sense?

**Comment by bmcorum** [comment]
@LisaLNelson yes that is a clearer picture on the requirement. Sounds to me like the requirement would be to add a link that collects all applicant email address then. So maybe we reword this ticket to state, "Create the ability for Opp Creators to collect a list of all applicant email address". Is that a correct assessment?

**Comment by LisaLNelson** [comment]
Yes that's great. Appreciate the clarification.

**Comment by kbwagner** [comment]
2/3/2020 - Add link to "Email all" that is a mail to link that opens up a blank email, will dump all emails into the email to box.

Email all applicants
Email all participants
Possibly Email everyone

**Comment by kbwagner** [comment]
@nia-johnson I talked this through with Lisa.  I added more comments above...when you have time can you get this one ready please?

**Comment by kbwagner** [comment]
@nia-johnson  FYI  I had some time so went ahead and did this ticket.  Thanks.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41549&_a=edit
