### ISSUE TITLE
Separate the DoS intern opportunities from the federal opportunities on the sitewide admin panel.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#3766]
As an admin I find it confusing to see the intern opportunities mixed in with the federal ones. I have to read through them if the title does not contain the word intern to see who is responsible for publishing.  It would be great if there was a way to separate.

**Comment by kbwagner** [comment]
@LisaLNelson I have another ticket that will do this in the future.

**Comment by bmcorum** [comment]
@kbwagner can you comment with a link to the existing ticket and then close this one please.

@LisaLNelson I would recommend reaching out to any PMO Atlas member in the future to make sure we don't already have a ticket in place so that we can avoid future duplicates.

**Comment by kbwagner** [comment]
Duplicate - closing
