### ISSUE TITLE
Create internship: Remove value from suggested security clearance field

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3767]
Who: Student internship hiring managers
What: Modify values for the suggested security clearance field
Why: In order to line up with the DoS REETA system

Acceptance criteria:
- One the Create internship page for Student internship opportunities, remove the value of "Classified" from the Suggested security clearance field.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing

**Comment by abudz19** [comment]
Looks good, moving to final approval.
