### ISSUE TITLE
Create internship page: Add instructions above Suggested security clearance

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3768]
Who: Internship hiring managers
What: instructional text for security clearance
Why: In order to provide additional information on what to select for this required field

Acceptance criteria:
- For the create internship page, add the following instructional text between the field label for Suggested security clearance and the dropdown: "Please select the preferred security clearance level for this internship. If a Low Risk Public Trust is needed, please select “None.” Full clearances can only be granted for INR, USUN Nato, S-ES/S, and EUR/RPM. If outside of these offices, email studentinternship@state.gov with a justification cleared by your bureau/regional security officer."

Note:
- This was requested by State Department

**Comment by kbwagner** [comment]
@abudz19 tagging you so you'll be aware of an addition to the create internship page that State has requested.

**Comment by kbwagner** [comment]
@dalenard21 tagging you for review when you get back.  This language came from State.

**Comment by jhanson12** [comment]
We changed the placement of the text.  See images below:
![image](https://user-images.githubusercontent.com/15199629/62550605-81fc8480-b838-11e9-85a2-5954c6c3fc2a.png)
![image](https://user-images.githubusercontent.com/15199629/62550620-8aed5600-b838-11e9-9996-71facb75e6e4.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing

**Comment by abudz19** [comment]
Looks good, moving to final approval.

**Comment by dalenard21** [comment]
@kbwagner @abudz19 @jhanson12 If we're able to make a slight edit, I suggest this version of the content:

Please select the security clearance level for this internship.  Select "None" if it's a Low Risk Public Trust clearance. You can only select "Full clearance" if you're part of INR, USUN Nato, S-ES/S, and EUR/RPM. If you're outside of these offices, email studentinternship@state.gov with a justification cleared by your bureau or regional security officer."

**Comment by bmcorum** [comment]
@dalenard21 this content was specifically requested by Department of State. This is the exact text that they wanted.

**Comment by dalenard21** [comment]
@bmcorum I get that, and want to respect the stakeholders, but this is on our site. We should have some say in how instructions are worded, especially when trying to keep the tone consistent (in this case, active voice vs passive). We've made so much progress improving how we speak to and guide our users, I want to encourage our stakeholders to do the same.

I was out of the office when the request came through and maybe there were attempts to revise the language, so I understand if it's too late to go back to them with a suggestion and iterate. 

Thanks.
