### ISSUE TITLE
Community Managers unable to approve internships

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3772]
Environment: Prod and Test
Browser: Chrome

Issue: A user that is a community manager only (without sitewide admin access) does not see the "Approve" column for submitted internships.  Delete is also not aligned.

screen Shot: ![community manager.jpg](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/1b13197c-7ab3-4c99-9ab7-a16e5520e6fe)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing in the UAT environment. You will need to use an account that does not have sitewide admin privileges.

**Comment by Kibrahacha67** [comment]
7-30-19 LHammond in testing

**Comment by kbwagner** [comment]
7/30/19 - Kwagner tested in Chrome/UAT as a community manager only.
@tlorrison ready for final approval.
