### ISSUE TITLE
Bug; Internship submitted email content update

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3773]
Environment: Production

Issue: Internship submitted email has an extra "you" and currently reads, "You will receive an email you when it's approved..."

Resolution: Modify last sentence of email to read, "You will receive an email once the opportunity is approved or if additional information is needed."

Screen shot of current email: 
![submitted email](https://user-images.githubusercontent.com/18709918/62076932-e905b200-b216-11e9-965c-beaa8ebb9b45.jpg)

Original Ticket: https://github.com/openopps/openopps-platform/issues/3094

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing

**Comment by Piglady64** [comment]
Email is correct. Moving to final approval.

![image](https://user-images.githubusercontent.com/15252970/63286376-e03c5500-c285-11e9-94e5-7c461cff1d2c.png)
