### ISSUE TITLE
Allow for administrators via dashboard and all users via people search to view what a person has applied to or created

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3779]
Who: All users
What: View opportunities applied to and participated in for other users
Why: For help desk purposes and networking.

Issue: When we created a landing page for users that displays their applied to and created opportunities, we took away the ability for sitewide admins/help and users in the People Search to view this information.

Acceptance Criteria:
- Add the ability to see what a user has created in or participated in.
- If a user goes to People search to view a user, Add the Opportunities section from the user's landing page to the People Search (Participated in and Created).  This section will function like it does on the user's landing page where the Opportunity link allows them to view the opportunity. 
- Show more will also work on this page
- Sort by will be functional and the default sort will be the same as the landing page

If a sitewide administrator views a user's profile via the admin dashboard, the above requirements will be the same in this instance.
- If a user is a student, the student landing page section of Applied and Saved will appear.  

As with any view of a profile that is not your own, the "You are viewing another user's profile" messaging will appear (to include you are an administrator...you are viewing a contactor, etc.) which is all current functionality.

<img width="428" alt="Dept_of_State_-_Open_Opps_-_Search_Apply_Profile_-_AB_07292019 (1)" src="https://user-images.githubusercontent.com/18709918/62159825-9f819980-b2e0-11e9-95c5-e9667529de2e.png">

**Comment by bmcorum** [comment]
@kbwagner what if we just added  the following section to the bottom of the profile page? This would be only when viewing someone else's profile not my own.

### Posted Opportunities
- Includes all _Open_, _In Progress_ or _Completed_ opportunities
- It does **NOT** include _Draft_, _Submitted_ or _Canceled_ opportunities

### Completed Opportunities
- Display the opportunities I successfully completed (I.E. Show the world my success)
- **DO NOT** show opportunities I was not selected for or that I did not complete (I.E. Don't show the world my failures)

**Comment by abudz19** [comment]
So more similar to this mockup (ignore the irrelevant parts): https://opm.invisionapp.com/d/main/#/console/16603537/344286020/preview

**Comment by bmcorum** [comment]
@abudz19 yes. Though I am not sure I want to share the bad stuff like I didn't get selected or I didn't complete it but we can. Also probably don't want to show my drafts, submissions or canceled since those can't be search.

**Comment by abudz19** [comment]
Would an admin need to see those things to be able to help someone though? That was the impetus for this ticket right?

**Comment by abudz19** [comment]
Also, I don't think we should show the same information in two places. It kind of invalidates the need for a home/dashboard page?

**Comment by kbwagner** [comment]
Tracy and I discussed and we will use the link to the landing page design

**Comment by bmcorum** [comment]
@kbwagner so it this for admins only? I assume yes since the blue banner only displays for admins.

**Comment by kbwagner** [comment]
@bmcorum yeh that's confusing.  I actually wrote it for all users since that's how it used to be but only did a message for admins.  Can it be for all users and i'll write another message for normal users?

**Comment by kbwagner** [comment]
@bmcorum actually I already had this in there  Add a link to the existing "You are viewing another user's profile." that reads, "You are viewing another user’s profile. Please view their dashboard to view opportunities created / participated in."

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-9-19 LHammond in testing
as a sitewide admin while viewing a student record, if I click the sortby dropdown and select any of the other views, the page deletes all of the records and removes the sortby drop down.  images below.  moving back to dev
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/89dbfd6d-8862-41ab-aa4b-bf18c0f206d5)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/7ed11e40-9180-45bd-948a-5cf224d6c747)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-9-19 LHammond in testing

**Comment by kbwagner** [comment]
10/10/19 - @bmcorum katrina student wagner has a current application open and it's not displaying (Maglio's cycle)

**Comment by kbwagner** [comment]
10/10/19 - KWagner tested in Chrome/Test - ready for final review
