### ISSUE TITLE
Create indicator on admin dashboards to indicate whether a user is a student or federal or contractor

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3781]
Who: Sitewide Administrators
What: Icon to identify federal vs student users
Why: To avoid confusion and assist with help desk needs

Acceptance criteria:
On the sitewide administator dashboard, the following changes should occur:
1) Remove the User # column from the dashboard
2) To the right of the user's name, add a new column called "User type"
3) In the User type column display the icon associated with the user - Federal or student (contractor coming soon)
4) The icons will be the hiring path icons
5) If the administrator hovers on the icon, an Alt Tag should display to read Federal, Student, or Contractor (future ticket) for the appropriate icons.

Current Admin page Screen Shot:
![image (25)](https://user-images.githubusercontent.com/18709918/62153098-e025e680-b2d1-11e9-9857-944c7f75af98.png)

Suggested use of icon (ignore field labels):
![image](https://user-images.githubusercontent.com/18709918/62160409-ef149500-b2e1-11e9-93be-c2fcee33fbaa.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-3-19 LHammond in testing.

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested in Chrome/Test
Ready for final review
