### ISSUE TITLE
BUG: Sub nav not loading when canceling out of create opportunity

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3787]
SR
click the create button on the home page
select student internship click continue
scroll to bottom of page and click cancel
click cancel on select page
Home page will not have sub nav bar

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing
testing completed moving to review

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested
Ready for final review
