### ISSUE TITLE
BUG: When copying an internship, the security clearance level isn't getting copied over as well.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3798]
When the user tries to save the copied internship, they will get an error on page to add security clearance.  therefore it should be copied over during the procedure.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing

**Comment by kbwagner** [comment]
8/7/19 - KWagner tested in Chrome/Test
Ready for final review.
