### ISSUE TITLE
Bug: Secondary URL does not save on Cycle

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3808]
Environment: UAT

Steps to recreate:
1) Edit cycle
2) Enter secondary URL
3) Save
4) Go out of the cycle and go back in
- URL not saved.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
8/7/19 - KWagner tested in test/chrome
Ready for final review.
