### ISSUE TITLE
Bug: only community managers can see selectees 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3811]
Environment: Chrome

Steps to reproduce: 
1) log in as community member (not community manager)
2) open up your internship that was closed in atp
- no selectee info shows
- only community managers and sitewide admins can see

**Comment by bmcorum** [comment]
This was fixed during user acceptance testing done on 8/6/2019

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing

**Comment by kbwagner** [comment]
9/26/19 - KWagner tested in Chrome/UAT
Ready for final review
