### ISSUE TITLE
Bug: intern badge doesn’t display title 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3812]
Environment: UAT

Steps to reproduce: 
1) complete an internship in Open Opps
2) view the profile of the completed applicant 
3) internship badge displays but the title of the badge is generic
- the title of the badge should read "Intern"

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing,
completed testing moving to review.

**Comment by abudz19** [comment]
@kbwagner I can't close my internship to check this -- this is another bug, #3822

**Comment by abudz19** [comment]
Was able to close this morning.
