### ISSUE TITLE
Bug: internship owner change doesn’t get sent to atp 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3813]
Environment: uat

Steps to reproduce:
1) change the owner on an open internship
2) log into atp as the new owner once the review dates have hit
- new owner doesn’t see internship review boards
- Open Opps needs to send new owner info to atp

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum   I need a clarification here.  When I changed the owner in open opps from Larry Hammond to Jared H Tester, the information got sent to ATP, but now both have it on a board and the only difference in the board is that the circle with initials is wrong on the original owners board.  So I need to know if that is ok or should it only be on a board for the changed owner and the board for the original owner goes away?
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/d1d33e90-790c-4443-a529-f9bedcb07e0f)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/a0c7ef23-058b-4bbd-ae71-75f0ab6e369f)

**Comment by kbwagner** [comment]
@Kibrahacha67 change owner should fully change.  So only the NEW hiring manager should see the board to start with.  If they want to invite more people that's fine but they should be the only name listed on the board.  Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-9-19 LHammind in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
9/26/19 - KWagner tested in Open Opps and ATP test
Ready for final review
