### ISSUE TITLE
Close out: must be able to close out even if no selectees 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3814]
Who: hiring managers 
what: close out internships even if no selectees display 
Why: to keep clean data 

Acceptance criteria:
- current process: if an internship has no selectees, the complete button is disabled 
- new process: if an internship has no selectees or alternates after the close out process in atp, the complete button should be enabled so the internship can be closed.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-6-19 LHammond in testing

**Comment by kbwagner** [comment]
9/26/19 - KWagner tested in Chrome/UAT
Ready for final review
