### ISSUE TITLE
Do not display student internships on the Sitewide Administrator Dashboard

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3815]
Who: Sitewide Admins
What: Do not display student internships on the sitewide admin dashboard
Why: To avoid confusion

Acceptance Criteria:
- Where target audience is student, do not display internship opportunities on the sitewide dashboard

Note:
- If a sitewide admin needs to approve an internship on behalf of State, they can do so via the Community dashboard
- Metrics will be discussed at a later time

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-7-19 LHammond in testing

**Comment by Piglady64** [comment]
Julie Reviewed. No student internships on my Sitewide Administrator dashboard. Moving to final approval.
