### ISSUE TITLE
Internship creator (DoS hiring manager) cannot close internship

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#3822]
Used the wrong permission check to validate if user could close the internship

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
08-08-19 LHammond in testing
on hold for until 8-13-19 so that the other testing with that cycle can complete before we close out the cycle.

**Comment by abudz19** [comment]
Good to go, moving to final review.
