### ISSUE TITLE
Contractor: add indicator to admin dashboard

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3827]
Who: Sitewide Administrators
What: Icon to identify contractors 
Why: To avoid confusion and assist with help desk needs

Acceptance criteria:
On the sitewide administator dashboard, the following changes should occur:

In the User type column display the icon associated with contractor for contractors (see comment below with icon)
If the administrator hovers on the contractor icon, an Alt Tag should display Contractor

Related ticket 3781

**Comment by kbwagner** [comment]
@abudz19 can you please add the contractor icon to this ticket?

**Comment by abudz19** [comment]
[Contractor.svg.zip](https://github.com/openopps/openopps-platform/files/3486844/Contractor.svg.zip)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-3-19 LHammond in testing 
Testing completed moving to review.

**Comment by kbwagner** [comment]
9/3/19 - Kwagner tested in Chrome/Test
- Ready for final review
