### ISSUE TITLE
Federal Contractor  - Friction Page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3848]
Who: Federal Contractor
What: Inform Federal Contractors how to access OO
Why: Some users are federal contractors and we need a way to allow them to provide their federal email

A/C
- The user will see this page when they have selected "Contractor" on the "Create your profile"  
   page #3850 
- Use the Open Opportunities Header
- There will be a green banner with the following information:
   Welcome to Open Opportunities!
   Discover opportunities that will help you find new connections, advance your career, and make 
   difference across government.
- There will be an icon with the label, Federal Contractor 
![image](https://user-images.githubusercontent.com/15252970/63465746-e40bdb00-c42f-11e9-97db-d0a4071aec28.png)
- The following content will be below the label:
   If you're a federal contractor and need access to Open Opportunities, you need to create a 
   USAJOBS profile. Make sure you:
     - Choose the hiring path(s) that fit you.
     - Select **I am a current contractor working for the Federal Government** in the 
      **Experience-Federal service** section.
     - Include the agency you're currently working for.
     - Add your federal email address.
     - Confirm your federal email address - look for the confirmation email in your inbox.

- There will be a "Back" button in the left hand corner
   - When the user clicks this button they will go to the previous page - #3850 
- There will be a "Create your profile" button in the lower right hand corner
  - When the user clicks this button they will be taken to USAJOBS to create their profile.

InVision Mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/screens/376322884_Open_Opps_-_No_Profile_3_-_Federal_Friction_Copy

**Comment by kbwagner** [comment]
@raywilliams the mock and the AC both have the page title as "Federal Contractor" (unless something changed I don't know about).  Please update.  Everything else looks good.  Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-5-19 LHammond in testing
Moving to review.

**Comment by kbwagner** [comment]
9/10/19 - KWagner tested Chrome/Test
Ready for final review
