### ISSUE TITLE
Add contractor option to the "Create your profile" page

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3850]
Who: Contractor
What: provide a contractor option to the "Create your profile" page
Why: Federal Contractors should have access to OO

A/C
- Add a "Contractor" button under the "Student" button on the "Create your profile" page
![image.png](https://images.zenhubusercontent.com/5b59d12efee5ed0b01c00008/222e674e-c183-40d8-bd38-5a269c3bb0fa)
- When the user clicks this button they will go to the Federal Contractor Friction Page (#3848)

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested Test/Chrome
Ready for final review
