### ISSUE TITLE
Prevent students from applying to federal opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3854]
Environment: Production

Issue: Students are finding non student opportunities and are able to apply to them.

Resolution: Prevent students from being able to apply for non internships.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-5-19 LHammond in testing

**Comment by kbwagner** [comment]
9/10/19 - Kwagner tested Chrome/Test
Ready for final review.
