### ISSUE TITLE
Bug: Emails for community admin being sent to personal/login.gov email instead of federal

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3856]
Environment: Production

Issue: Emails to approve an internship are being sent to the community administrators personal email address instead of federal.   A previous fix resolved this issue for non community administrators.

Note: this issue is occurring for all communities not just DoS.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
9/3/19 - KWagner tested (as Jasmine) ready for final review
