### ISSUE TITLE
Bug: Duplicate needs to use duplicator's agency not owner's

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3858]
Environment: Production

Issue:
-  Copy needs to update the task with the users agency not the owners agency
- User didn't have agency associated so wouldn't show up on limit to agency participation section.  Duplicate wouldn't work because even though now he added his agency, it wouldn't update based on who he is now.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
9/10/19 - KWagner tested in Chrome/Test
Ready for final review
