### ISSUE TITLE
Profile: Add contractor label to admin view of profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3865]
Who: Open Opps users
What: Viewing another user's profile - indicate contractors
Why: To make sure users understand when they are viewing a contractor profile

Acceptance Criteria: 
When an Open Opps users views another user's profile either via
1) Admin dashboard - manage users
2) View of the profile via People search
3) By clicking on the user's name as part of an application
- the fact that the user is a contractor should be indicated.

The message should read, "You are a <type of user>.  You are viewing a contractor's profile."  
Screenshot of similar message for students: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/80ace6c1-8cb6-489c-a63d-9047031084ab)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
9/19/19 - Kwagner tested in Chrome/Test 
Ready for final review
