### ISSUE TITLE
Bug: Search field to add members to a community doesn't always return values

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3872]
Environment: Production
Browser: Chrome

Issue: 
The search field for adding members to a community doesn't return users in certain instances.  See examples below.

Examples: 
•	As for the search feature to find community members, I have entered a first name and last name but because there is a middle name, the person did not show up. Is there any possibility of this being fixed so that the first and last name will still render a community member? I have included screenshots below. 

![image](https://user-images.githubusercontent.com/18709918/63775263-f6ad6680-c8ac-11e9-9c35-f86d8b6cb779.png)
![image](https://user-images.githubusercontent.com/18709918/63775305-0cbb2700-c8ad-11e9-8e95-b3f44dc3b276.png)

•	I have included another example where I typed the first name and the first initial of last name but it did not render a user but when I typed the last name, it did. Same thing happened with community member Sharon Jones.

![image](https://user-images.githubusercontent.com/18709918/63775358-29575f00-c8ad-11e9-8756-2e3c8ac00440.png)
![image](https://user-images.githubusercontent.com/18709918/63775382-383e1180-c8ad-11e9-9d0f-8d23ed78e05f.png)

•	This is an instance where I typed the first name but it did not render a result so I decided to look through the users and found them on the second page.

 
![image](https://user-images.githubusercontent.com/18709918/63775436-4db33b80-c8ad-11e9-9893-dcb36a0dce9b.png)

![image](https://user-images.githubusercontent.com/18709918/63775467-5e63b180-c8ad-11e9-987a-d4b099efea83.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-25-19 LHammond in testing

**Comment by kbwagner** [comment]
9/25/19 - KWagner tested in Chrome/Test
Ready for final review
