### ISSUE TITLE
Agency Admin Dashboard: User .csv file

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3880]
User Story: As an agency administrator, I want to be able to download a list of all users and display related information for each user.

Acceptance Criteria:
When the administrator clicks on Admin --> Agency --> Users --> Manage, they have the ability to download a .csv file of all users.

Acceptance Criteria: 
- The agency report should ONLY display users associated with that agency.

- Report fields should be:
name
Student/Contractor/Federal identifier
Login.gov email
Official federal government email
Last login date
Account create date
title
agency
location (include Country if not USA)
bio
Agency admin (True/False)
disabled (True/False)
- The sort order should be account create date (newest to oldest)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-11-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 does excel not convert the time to your local timezone?

**Comment by Kibrahacha67** [comment]
no this is what it looks like![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/0e5077fd-d043-44d3-86c6-cca9a0513528)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-15-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
10-16-19 LHammond in testing

**Comment by kbwagner** [comment]
10/16/19 - KWagner tested in Chrome/Test
Ready for final review
