### ISSUE TITLE
Agency Admin: Opportunity .csv

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3887]
Who: Agency Administrators
What: Opportunities .csv
Why: In order to allow data filtering and mining on opportunities

Acceptance Criteria:

Admin --> Agency  --> Opportunities --> Manage
When a user clicks on the "Download list" csv file, the following information should display
Task id
Title (previously name)
Description
Created date
Published date
Assigned date (note: is this the date someone is selected to participate? most are blank)
Submitted date
Creator name
Applicants (formerly sign ups)
Selected participants (leave blank if none) - new
Completed participants (leave blank if none) - new
Task State
Agency name
Completion Date

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-4-19 LHammond in testing
Assigned date would not populate even though I took a ticket though the complete process. Moving back to development.

**Comment by jhanson12** [comment]
The assignedAt date was not populate because we had not updated the state from 'assigned' to 'in progress' when we changed at an earlier date.

Fixed now.  This will be for all the CVS tickets with Assigned At data.
@Kibrahacha67

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-8-19 lhammond in testing

**Comment by kbwagner** [comment]
10/9/19 - KWagner tested in Chrome/Test ready for final review 

Note: I had intended for selected and completed participants to be a count instead of a name but my fault for not being specific.  Will leave it for now and if we need to change it later can write a new ticket.
