### ISSUE TITLE
Community Admin: Opportunity .csv

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3888]
Who: Community Administrators
What: Opportunities .csv
Why: In order to allow data filtering and mining on opportunities

Acceptance Criteria:

Admin --> Community  --> Opportunities --> Manage
When a user clicks on the "Download list" csv file, the following information should display
Task id
Title (previously name)
Description
Created date
Published date
Assigned date (note: is this the date someone is selected to participate? most are blank)
Submitted date
Creator name
Applicants (formerly sign ups)
Selected participants (leave blank if none) - new
Completed participants (leave blank if none) - new
Task State
Agency name
Bureau (can this be for the State community only?)
Office/post (can this be for the State community only?)
Completion Date

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-8-19 LHammond in testing

**Comment by kbwagner** [comment]
@raywilliams - number of applicants isn't being populated on the state community .csv file. All are zero when there are in fact applicants.  
Returning to development

**Comment by bmcorum** [comment]
@kbwagner do you want selected participants for DoS would have to include both primary and alternate.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
@bmcorum sorry I missed this yesterday - yes would be ideal to have alternate and selectee

**Comment by kbwagner** [comment]
10/10/19 - KWagner tested in Chrome/Test 
ready for final review
