### ISSUE TITLE
Sitewide User: Add agency to manage users

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3890]
Who: Sitewide admin
What: Add Agency to manage users
Why: In order to facilitate user support

Acceptance Criteria:
Admin --> Sitewide --> Users --> Manage
- Add "Agency" after the Name field in manager users

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-25-19 LHammond in testing

**Comment by kbwagner** [comment]
9/25/19 - KWagner tested in Chrome/test
Ready for final review
