### ISSUE TITLE
Sitewide: Opportunity filter

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3891]
Who: Sitewide administrators
What: Ability to filter opportunities
Why: in order to allow admin to more easily find opportunities

Acceptance criteria:
Navigation: Admin --> Sitewide --> Opportunities --> Manage
Add a filter box similar to manage users
The default text in the box will read "Filter by Title or Creator"
A search box will be at the back of the field
The text entered will search against the Title field and Creator name fields to return search results

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-27-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner - question, originally this ticket was to search on title and creator, but it now has Agency in the search as well, are you good with that?

**Comment by kbwagner** [comment]
9/30/19 - KWagner tested in Chrome/Test
Ready for final review
