### ISSUE TITLE
Agency Admin: Add opportunity search filter

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3892]
Who: Agency administrators
What: Ability to filter opportunities
Why: in order to allow admin to more easily find opportunities

Acceptance criteria:
Navigation: Admin --> Agency --> Opportunities --> Manage
Add a filter box similar to manage users
The default text in the box will read "Filter by Title or Creator"
A search box will be at the back of the field
The text entered will search against the Title field and Creator name fields to return search results

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-1-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
@bmcorum can you please remove the comma in the default text?  Should just say "Filter by Title or Creator" but there is currently a comma after Title.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-1-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 Kwagner tested in Chrome/Test
Ready for final review
