### ISSUE TITLE
Community Admin: Add filter for opportunities (non DoS)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3893]
Who: Community administrators
What: Ability to filter opportunities
Why: in order to allow admin to more easily find opportunities

Acceptance criteria:  For all non DoS communities:
Navigation: Admin --> Community --> Opportunities --> Manage
Add a filter box similar to manage users
A search box will be at the back of the field
The box will auto filter as the user types
The text entered will search against the Title field and Creator name and Agency to return search results

The default text in the box will read "Filter by Title, Creator, or Agency"

Related Tickets: 
3911 is adding filter for DoS communities

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-20-19 LHammond in testing

**Comment by kbwagner** [comment]
@jhanson12 if I enter something that brings back no results The viewing shows "Viewing 1 of 0

![image](https://user-images.githubusercontent.com/18709918/65431452-82041400-dde7-11e9-8cc6-063451b45fc8.png)

Can this be fixed with this ticket or does it need to be a separate bug ticket?

**Comment by kbwagner** [comment]
Added bug 3969 for the above issue.

Moving this to review.
