### ISSUE TITLE
Remove contractors from People Search

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3894]
Who: Contractors
What: Do not include in People search
Why: To prevent issues

Acceptance Criteria:
Remove contractors from being searchable in People search. 
only federal employees will be part of the People search

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
9/19/19 - KWagner tested in Chrome/Test
Contractors no longer display in People search
Ready for final review
