### ISSUE TITLE
Sitewide: Add agency to manage opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3895]
Who: Sitewide administrators
What: Add agency to opportunity list
Why: To assist with help desk needs

Acceptance Criteria:
- Navigation: Admin --> Sitewide --> Opportunity --> Manage
- Add Agency as a display field after the creator name 
- Agency should be added for all of the pill filters Submitted, Open, Not open, In progress, completed, canceled

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
9/19/19 - Kwagner tested in Chrome/Test
Ready for final review
