### ISSUE TITLE
Community Admin: Add Agency to Opportunity view

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3896]
Who: Community Admins
What: Add agency to opportunity view
Why: So they can provide better support

Acceptance Criteria:
Navigation: Admin --> Community --> Opportunities --> Manage

For non state communities:
Add Agency after creator name

Related ticket 3963 - DoS

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-30-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 - KWagner tested in Chrome/Test
Ready for final review
