### ISSUE TITLE
Sitewide Admin: Add Agency to Opportunity sort by

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3897]
Who: Sitewide administrators
What: Add agency to opportunity sort by
Why: in order to more easily find opportunities

Acceptance Criteria:
Navigation: Admin --> Sitewide --> Opportunities --> Manage
- Add Agency as a value in the sort by drop down
- Drop down should appear in the same order as the fields in the grid

Related ticket: 
3895 - Add agency to opportunity admin view

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-25-19 LHammond in testing

**Comment by kbwagner** [comment]
9/25/19 - KWagner tested Chrome/Test
Ready for final review
