### ISSUE TITLE
Community Admin: Add Agency to opportunity sort by (non DoS)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3898]
Who: community admin
What: Add Agency to Sort by
Why: to help managers find the right opportunities

Acceptance Criteria:
Navigation: Admin --> Community --> Opportunity --> Manage

For non DoS communities:
- Add Agency to the sort by in the same order it appears in the grid

Related ticket:
- DoS 3964

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-1-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 - KWagner tested in Chrome/Test
