### ISSUE TITLE
Agency Admin: Interactions

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3900]
Who: Agency administrators
What: View interactions on dashboard
Why: In order to provide metrics

Acceptance Criteria:
On the agency admin, add the Interactions section to the right of opportunities

Interactions
Total applications
Total assigned
Total completed
Discussion posts

Calculations will be limited to the selected agency

**Comment by bmcorum** [comment]
- [ ] Data export for 3 - 5 agencies for validation

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
9/19/19 - Kwagner tested in Test/Chrome
ready for final review
