### ISSUE TITLE
Agency Admin: Dashboard Opportunity Data

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3901]
User Story: As an administrator, I would like to see metrics on completed opportunities.

Acceptance Criteria:
Administration --> Agency --> Opportunities

The opportunity section on the sitewide should be replicated for the agency section.  Data should be limited to the selected agency.

- There will be a Period dropdown with values: Fiscal year, Quarter, Month (Important to keep the historical data year over year somewhere). The default will be Fiscal year
- There will be Radio buttons for – All, Ongoing, One time The default value will be All
- The column headings when fiscal year is selected will be the last fiscal year and the current fiscal year. Additional years will be added and eventually up to 2 years will display. Column headings for other display options will be the same as current but limited to FY18 and FY19 data.
Target audience = student metrics will not be included in these metrics.
The row titles will be:
o Carryover (Not completed)- this row will display data for any opportunities opened in a previous selected time period that have not yet been completed. Note: The subtitle of Not completed is not updated on the mock at this time. Follow AC.
o Published - opportunities published in the selected time period
o Completed - opportunities completed during the selected time period by the opportunity creator
o Completed by admin - opportunities completed during the selected time period by the administrator
o Percentage completed - of the number opened in the time period selected how many were closed
o Percentage canceled - of the number opened in the selected time period, how many were canceled
o Applicants - number of applicants to opportunities within the selected time period that applied to completed opportunities.

Where there is no data to display, display "n/a" or zeros as appropriate

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by tanichacko** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-17-19 LHammond in testing

**Comment by kbwagner** [comment]
@tanichacko question on this one - 

Selected  Department of Veterans Affairs Agency Wide and then downloaded the opportunity csv file
- Count for published in FY16 matched .csv file
- Count for applicants is off - csv file has 3 applicants but metrics shows only 1.  But the other 2 are on an archived application.  Are we not including archived?  If not we should also not include it for published

**Comment by tanichacko** [comment]
@kbwagner we have some changes that pushed to test yesterday afternoon based on the ticket #4022. We only displaying current fiscal year and previous fiscal year in the metrics  and we are excluding archived state opportunities plus for count for applicants we are taking only completed opportunities that's why the count showed as 1 for Fy2016.

**Comment by kbwagner** [comment]
10/10/19 - KWagner tested in Chrome/Test
Ready for final review
