### ISSUE TITLE
Agency Admin: Top opportunities created .csv

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3903]
Who: Agency administrators
What: .csv of top creators
Why: in order to encourage system use

Acceptance Criteria:
In the Top Contributors section of the Agency dashboard, add a link that reads, "Download full list (.csv)"

All contributors for the agency will appear with a numerical ranking.

the .csv fields will be:
Display rank number, Creator name, total number created

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-16-19 LHammond in testing.

**Comment by kbwagner** [comment]
919/19 - KWagner tested in test/Chrome
- ready for final review

Note: The tied people show in different order than the screen but it's not really an issue.
