### ISSUE TITLE
Community admin: opportunity metrics for dashboard (Non Dos)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3905]
Who: Community Administrators
What: Add opportunity metrics to dashboard 
Why: for easy reporting

Acceptance Criteria:
Navigation:
Administration --> Community  --> Completed opportunities

- For communities, this section will display under the users/opportunities/interaction line
- Data should only display for the selected community
- Communities that use a cycle have an additional requirement in ticket 2910

The remaining requirements are the same as the sitewide:
There will be a Period dropdown with values: Fiscal year, Quarter, Month (Important to keep the historical data year over year somewhere). The default will be Fiscal year
There will be Radio buttons for – All, Ongoing, One time The default value will be All
The column headings when fiscal year is selected will be the last fiscal year and the current fiscal year. Additional years will be added and eventually up to 2 years will display. Column headings for other display options will be the same as current but limited to FY18 and FY19 data.
Target audience = student metrics will not be included in these metrics for non student communities
The row titles will be:
o Carryover (Not completed)- this row will display data for any opportunities opened in a previous selected time period that have not yet been completed. Note: The subtitle of Not completed is not updated on the mock at this time. Follow AC.
o Published - opportunities published in the selected time period
o Completed - opportunities completed during the selected time period by the opportunity creator
o Completed by admin - opportunities completed during the selected time period by the administrator
o Percentage completed - of the number opened in the time period selected how many were closed
o Percentage canceled - of the number opened in the selected time period, how many were canceled
o Applicants - number of applicants to opportunities within the selected time period that applied to completed opportunities.

Where there is no data to display, display "n/a" or zeroes as appropriate

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

**Comment by kbwagner** [comment]
@Kibrahacha67 for non DoS yes the dropdown should be there.  Sorry I think I wrote the DoS one first and copied it.  DoS won't have the dropdown because it's only cycles.  Non DoS should be the same as regular

**Comment by tanichacko** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-17-19 LHammond in testing

**Comment by kbwagner** [comment]
10/10/19 - Kwagner tested in Chrome/Test
Ready for final review
