### ISSUE TITLE
Community Admin: Opportunity metrics Cycle communities (DoS)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3910]
Who: Community Administrators
What: Add opportunity metrics to dashboard
Why: for easy reporting

Acceptance Criteria:
Navigation:
Administration --> Community --> Completed opportunities

For communities, this section will display under the users/opportunities/interaction line
Data should only display for the selected community
- For communities that use a cycle and have an audience of student, add a period of Cycle and if selected show data for the last two cycles

The remaining requirements are the same as the sitewide unless otherwise noted:
- The only period will be cycle for the time being - no dropdown needed
- Students only use ongoing so no radio buttons needed 
- Column heading will include cycle names

The row titles will be:
o Published - opportunities published in the selected time period
o Completed - opportunities completed during the selected time period by the opportunity creator
o Completed by admin - opportunities completed during the selected time period by the administrator
o Percentage completed - of the number opened in the time period selected how many were closed
o Percentage canceled - of the number opened in the selected time period, how many were canceled
o Applicants - number of applicants to opportunities within the selected time period that applied to completed opportunities.

Where there is no data to display, display "n/a" or zeroes as appropriate

Invision: https://opm.invisionapp.com/d/main#/console/13386795/300494469/preview

Note: Carryover will not be necessary for DoS

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-3-19 LHammond in testing

**Comment by kbwagner** [comment]
@tanichacko @Kibrahacha67 similar issues confirming applicant numbers on this one.  

If I use Julie Cycle 2, I count 20 applicants to the various internships which divided by 3 is 6.66666 people...but the metrics says I have 13 applicants.  am I counting wrong somehow?  Can you point me in the right direction for this calculation?

**Comment by Kibrahacha67** [comment]
@kbwagner @tanichacko devs will have to tell you the calc they used I used the numbers on the site to confirm.  may be out of bounds on that one as well as the other ticket

**Comment by kbwagner** [comment]
@bmcorum @tanichacko for the DoS metrics section:
- SC Cycle - says 12 applicants  in the metrics section but 4 applications submitted
- Julie cycle - says 13 applicants in the metrics section but 4 applications submitted

First - the numbers don't make sense.  it's not likely 12 applicants because we force applicants to apply to 3.  
Second - it doesn't really make sense to show the same piece of data side by side so do we just pull applicants off of the metrics section?

**Comment by bmcorum** [comment]
@kbwagner there are 3 cycles with corrupted data in test that I am reviewing to explain the number issues.

**Comment by bmcorum** [comment]
@kbwagner 
- **SC Cycle** has 4 submitted (completed) applications which would account for 12 total internships opportunities applied to (3 selections per application X 4 total submitted applications).
 - **Julie Cycle** has 5 submitted applications which would account for 15 total internship opportunities applied to (3 selections per application X 5 total submitted (completed) applications) **However,** Two internship opportunities for **Julie Cycle** got deleted (probably during a testing phase by accident) one of which had 2 applicants the other had 3 applicants which accounts for the 5 missing applicants not listed on the admin manage internships page because those two internships got deleted.

**Comment by kbwagner** [comment]
10/10/19 - Passing but will enter new ticket to hide this section as it's repetitive
