### ISSUE TITLE
Community: Add filter for opportunities (DoS)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3911]
Who: Community administrators
What: Ability to filter opportunities
Why: in order to allow admin to more easily find opportunities

Acceptance criteria: For DoS community:
Navigation: Admin --> Community --> Opportunities --> Manage
Add a filter box similar to manage users
A search box will be at the back of the field
The text entered will search against the Title field and Creator name and Bureau/Office/Post fields to return search results

State Department community:
The default text in the box will read "Filter by Title, Creator, or Bureau/Office post"

**Comment by jhanson12** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-26-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-30-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 - KWagner tested in Test/Chrome
Ready for final review

Note: Counts are off on viewing x of y of z but there is a separate bug for this
