### ISSUE TITLE
Applicant status for non submitted application

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3917]
Who: Applicant who has not submitted their application prior to the close of the apply cycle
What: Display status of Not submitted on landing page
Why: To show that their application was not sent forward

Acceptance Criteria:
- For Student target audience with a cycle, if application is not submitted prior to the application cycle close date, update the application status to "Not submitted" on the student landing page

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-25-19 LHammond in testing

**Comment by kbwagner** [comment]
9/26/19 - KWagner reviewed attached artifact (Thanks Larry)
ready for final review
