### ISSUE TITLE
Bug: Career field does not display in edit mode and does not duplicate

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3919]
Environment: Test

Issue: Career field selected does not display when you click edit on an opportunity.  In addition, career field does not duplicate.

Steps to reproduce:
1)  Find an opportunity that has a career field
2) Select "Edit"
- Career field does not display
OR 
2) Duplicate - Career field does not duplicate

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-26-19 LHammond in testing

**Comment by kbwagner** [comment]
9/26/19 - KWagner tested Chrome/test
Ready for final review
