### ISSUE TITLE
Bug: Mobile only one initial displaying in top navigation

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3921]
Environment: Test

Issue: Mobile is only displaying the first initial for the user

Steps to reproduce: 
1) Log in to openopps.test.usajobs.gov as a user that has a first and last name on their profile
- Only the first initial displays in the top navigation

![Image from iOS](https://user-images.githubusercontent.com/18709918/64643196-e1bcf100-d3dd-11e9-8a8f-3e6fe55ef94a.png)

Original ticket 3455

**Comment by raywilliams** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-17-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
9/19/19 - KWagner tested in Chrome/Test
Ready for final review
