### ISSUE TITLE
Bug: Save for later submits opportunity

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3936]
Environment: Production

Issue: Save for later actually submits opportunity

Steps to reproduce:
1) Create internship
2) Select save for later
- instead of saving as draft the opportunity is submitted

**Comment by tanichacko** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-16-19 LHammond in testing

**Comment by kbwagner** [comment]
9/19/19 - KWagner tested in test/ready for final review
