### ISSUE TITLE
Bug: Change title of modal if non student tries to apply

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3938]
Who: non students
What: Try to apply for an internship
Why: The modal title is confusing

I clicked apply on a student internship, logged in as a non student, received modal: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/0b81ebdb-6296-4b2b-93cc-2d6855e85546)

This modal title should be renamed to reflect that only Students can apply for these internships.  The subtext is fine.

This modal title, however, should stay for those that have already applied for 3 internships

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-1-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 - KWagner reviewed artifact
ready for final review
