### ISSUE TITLE
DoS Community: Interactions updates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3942]
Who: DoS community admins
What: View interaction activity
Why: In order to have metrics

Issue: Interactions is currently zero for DoS community

Acceptance Criteria:
Current State:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/f9c8e0cf-4ad1-4c10-b25a-0d6ed73a6300)

Interactions will now appear under a heading of cycle and the numbers will be based on the cycle selected.

Interactions should display:

Completed applications (Header)
Applications submitted: total number of applications completed; 1 per student who submits their application for 3 internships

Incomplete applications: (Header)
Applications on Next Steps: Total number of applications that have stopped on Next Steps 
Applications on step 1 - Select Internships: Total number of applications that have stopped on Select internships page
Applications on step 2 - Experiences & References: Total number of applications that have stopped on the Experience & References page
Applications on step 3 - Education & Transcript: Total number of applications that have stopped on Experiences & references
Applications on step 4 - Languages & Skills: Total number of applications that have stopped on step 4
Applications on step 5 - Statement of interest: Total number of applications that have stopped on step 5
Applications on step 6 - Review application: Total number of applications that have stopped on step 6

Completed internships: (header)
Total completed:  Number of interns who have been marked completed

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-8-19 LHammond in testing

**Comment by kbwagner** [comment]
@Kibrahacha67 I actually noticed the same thing yesterday (and in my dream the night before sadly) and have a ticket in to modify . Thanks!

**Comment by Kibrahacha67** [comment]
All Good :)

**Comment by kbwagner** [comment]
@tanichacko @Kibrahacha67  I'm having trouble verifying this data. Really all I can see if the number of applications...

Example 1: Integration cycle - says applications submitted is 7.
- click on internships and manage - I could 50 applicants which if I divide by 3 to get an application (1 student applies to 3 internships) I get 16.66 applications submitted.

Example 2;  Julie's cycle - says there are 5 applications submitted
- click on internships and manage I count 32 applicants which if I divide by 3 is 10.666 applications

Am I calculating these wrong?
