### ISSUE TITLE
DoS community: Update opportunity metric values

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3943]
Who: DoS community Admins
What: Update Opportunity Metrics
Why: to remove values that don't apply to State

Issue: Values don't match State Department Values:

Current
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/bfd10c3d-6a29-4a60-a503-2a6e79dd4d58)

Opportunity metrics will now be based on the cycle selected (ticket 3995)
- Opportunity will now be renamed to Internships (ticket 3995)

Values for the DoS community should be: 
Total created
Submitted
Approved
Open
Completed

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-4-19 LHammond in testing

**Comment by kbwagner** [comment]
10/8/19 - KWagner tested in chrome/Test
Ready for final review

Note: if I select a cycle, click on manage internships, then use the back link, I lose the cycle I selected.  Checking with Brice and can make a new ticket.
