### ISSUE TITLE
Dos(community) vs Dos(Agency) metrics mix up

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3945]
Some of the information for Internships is being counted against the Dos Agency metrics.
Top contributors for FY 19 show 23 total opportunities but in the opportunities management page there are only 3 total.  
If under manage opportunities for Dos Agency user exports the .csv file there will be 29 entries, 26 of them are internships only 3 are actual agency opportunities.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/5da0fc39-0b80-4e55-b64d-be7825df53ba)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ca2a4b7f-6184-411b-99f6-fb8a5ba7131a)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/b092a742-0e56-4158-bc99-4f719cb024e7)

**Comment by jhanson12** [comment]
@bmcorum @kbwagner @Kibrahacha67 this bug is out of date and no longer an issue.  The UI has changed and this CVS file no longer exists.   Please review and either update if the bug still exists with where (can not find) or we may just need to close.  Thanks!

**Comment by Kibrahacha67** [comment]
12-23-19 LHammond in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
12/23/19 - kWagner reviewed.
Closing
