### ISSUE TITLE
Bug: Production - Application Experience throws a limit of 100 characters on Duties Accomps and Related Skills

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3946]
Environment: Production

Issue: System throws an error on Duties, accomplishments and related skills that it should be limited to 100 characters however USAJOBS does not have that limit

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/97d8d388-8ef4-44e9-bbac-3d487fa0239a)

Resolution: Use the same limit that USAJOBS has

Steps to reproduce:
1) In USAJOBS create a work experience row with over 100 characters in the Duties accomplishments and related fields section.
2) apply to an internship in Open Opportunities, click edit on the work experience row from #1 above.  Try to save.
- Message throw that there is a limit to 100 characters.

**Comment by tanichacko** [comment]
@kbwagner  For this section in UsaJobs Maximum character count is 5000 and  not allowing to type more than 5000 characters and not showing error . Do we have to do same in open opps ? or Do we need to show an error if its exceeds 5000 characters? or we have to go with adding (5000 characters remaining)?

**Comment by kbwagner** [comment]
@tanichacko if I had my perfect world Open Opps would:
1) limit to 5000 characters like USAJOBS and not allow to type more
2) I don't think an error is necessary...just don't allow them to type
3) Show 5000 character max text on the field and a character remaining countdown.

However...that's my perfect world and I recognize some of this isn't doable now.  For now at a minimum mirror USAJOBS to stop allowing them to type.

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by kbwagner** [comment]
9/19/19 - KWagner tested in Chrome/Test
Ready for final review
