### ISSUE TITLE
Bug: character counter on the "Please indicate what type of overseas experience you possess" box does not count input

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3951]
Steps to recreate:
1. Create a new internship application
2. Add internships
3. go to Experience page
   -Indicate you have overseas experience by clicking on "yes" radio button
   -Add some text in box.  You will see the counter go along with your input
     --scroll up the page and click on "+add experience"
     --cancel out of the page
     --go back to the overseas experience text box
        ---You will see that the counter has reset to 250
        ---The counter will not register any new input

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-20-19 LHammond in testing

**Comment by kbwagner** [comment]
9/24/19 - Kwagner tested in Chrome/test
ready for final review
