### ISSUE TITLE
Bug: Experience dates display incorrectly on application review page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3954]
Environment: Production

Issue: Work experience start and end dates are displaying incorrectly on the application review page

Steps to reproduce:
Jot down work experience start and end dates in USAJOBS
Apply for an internship in Open Opps
Go to the review page of your application and the start and end dates display one month off

Related ticket: 3947

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready to test in UAT. This will be a hotfix for 7.9

**Comment by Kibrahacha67** [comment]
9-20-19 LHammond in testing

**Comment by kbwagner** [comment]
I have an end date of "Present" and on the review page it shows up as "undefined"

![image](https://user-images.githubusercontent.com/18709918/65433938-f345c600-ddeb-11e9-8523-f5d3cb5fbd70.png)

returning to development.

Also, work experience on the experience page and review page should display newest to oldest like USAJOBS - will create a new ticket

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready to test in UAT. This will be a hotfix for 7.9

**Comment by kbwagner** [comment]
9/24/19 - KWagner tested in Chrome/UAT looks good.
