### ISSUE TITLE
Tracking Data: Track who deleted an opportunity or internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3959]
Who: Sys Admin
What: Ability to show who deleted an internship/opportunity
Why: To help answer questions when asked

- we currently can track when an internship or opportunity is deleted and the IP address associated.  
- Add tracking data for the name and agency of the person who deleted the opportunity/internship as well as the task number, title, and creator of the deleted internship.  
Also track who edited an internship, when it was edited, and if possible what fields were edited.

Notes from Brice 10/2/19: We probably need to create a new audit type of ‘delete’ and any time we delete data we need to record the event to our audit log. What got deleted, when and by whom.  I have updated our network logs to include user ids on all requests.

**Comment by bmcorum** [comment]
@kbwagner can we move the following requirement to a new ticket?

- Also track who edited an internship, when it was edited, and if possible what fields were edited.

**Comment by bmcorum** [comment]
Testing artifact. We record the id of the task delete, the title, and the creator's id which we can use to look up additional details on the creator such as agency. UserId column is the id of the user who preformed the deletion and the source field is the IP address where the delete originated from.

![image](https://user-images.githubusercontent.com/1165615/67115119-73710880-f1ab-11e9-8c5a-42b1a472a094.png)

**Comment by bmcorum** [comment]
This is ready for testing.

**Comment by Kibrahacha67** [comment]
10-18-19 LHammond Artifact attached moving to review.

**Comment by kbwagner** [comment]
10/21/19 - Reviewed artifact
Ready for final review

**Comment by kbwagner** [comment]
Moved to 4077 per Brice request - Also track who edited an internship, when it was edited, and if possible what fields were edited.

**Comment by kbwagner** [comment]
Added edit back into this ticket and closed 4077.  Work was done with this ticket.
