### ISSUE TITLE
Updates to submit modal on opportunity application

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3960]
Who: opportunity applicants
What: let them know if they have not updated their biography or skills
Why: so more applicants will input biography data

Acceptance Criteria:

Current Screen Shot
![image (29)](https://user-images.githubusercontent.com/18709918/65353835-14c06b00-dbbc-11e9-86d8-bd6e6d0ef5d8.png)

For the last bullet that currently reads, "I've updated my profile, including my biography and skills (optional, but recommended).
1) The system should check against the USAJOBS biography field and the Open Opps skills and flag if either of them has not been completed (at least one skill)
2) If both are complete, display the green check
3) if either isn't complete, display a yellow warning triangle to indicate.  However, they can still submit as normal and this display will not prevent them from applying
4) modify the language to read, "I've updated my profile, including my biography and/or skills (optional, but recommended).

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-18-19 LHammond in testing
Although both the skills section and the Bureau sections are filled out on the profile of the person applying, the yellow triangle shows on the modal.  should be a green check mark instead.  Sending back to development

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/29c50170-ed46-44fe-beac-ef2f51e761c9)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c1e5b913-159d-4e57-ae18-ea5678b8f13d)

**Comment by Kibrahacha67** [comment]
12-20-19 LHammond in testing.
Testing completed moving to review.
Note: if testing this from start (yellow flag) you will have to clear you browser after completing update on bio and or skills.

**Comment by kbwagner** [comment]
12/23/19 - KWagner Tested Chrome/Test
Ready for final review

![image](https://user-images.githubusercontent.com/18709918/71366839-2fb2ca80-2571-11ea-9d0b-624cfa634d2d.png)


![image](https://user-images.githubusercontent.com/18709918/71366932-6f79b200-2571-11ea-8689-b548a9ef1ebf.png)
