### ISSUE TITLE
Community: Add bureau/office post to manage opportunities (DoS)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3963]
Who: Community Admins (DoS)
What: Add agency to opportunity view
Why: So they can provide better support

Acceptance Criteria:
Navigation: Admin --> Community --> Opportunities --> Manage

For State community:
Add Bureau and Office/post fields after creator name

Related ticket: 3896 - non DoS

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-26-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-30-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 - KWagner tested in Chrome/Test
Ready for final review
