### ISSUE TITLE
Community Admin: Add Bureau and Office/post to opportunity sort by (DoS)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3964]
Who: community admin (DoS)
What: Add Bureau and Office/post to Sort by
Why: to help managers find the right opportunities

Acceptance Criteria:
Navigation: Admin --> Community --> Opportunity --> Manage

For DoS communities:
- Add Bureau and Office/post to the sort by in the same order that they appear in the table/grid

Related ticket: 3898 (non DoS)

**Comment by Kibrahacha67** [comment]
@kbwagner Question, Since Bureau and Office/post are the new column names for this page, and Agency is not on the page is "Agency" the right add to the sort order here?

**Comment by kbwagner** [comment]
@Kibrahacha67 AC was correct but title was wrong.  Updated. Thanks!

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
9-30-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 - KWagner tested in Chrome/Test
Ready for final review
