### ISSUE TITLE
Bug: Filtering on opportunities - View displays count of 1 when should be zero

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3969]
Environment: Test
Issue: If i filter in manage opportunities and no results are returned, the view count is off and shows viewing 1 of 0 of 25

This issue occurs on sitewide, agency, and community

Screen Shot: 
https://user-images.githubusercontent.com/18709918/65431452-82041400-dde7-11e9-8cc6-063451b45fc8.png

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-4-19 LHammond in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
10/7/19 - KWagner tested in Chrome/Test
Ready for final review
