### ISSUE TITLE
Application review page: work experience should in order selected

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3970]
Who: applicants
What: reviewing their work experience should display in order selected
Why: to be in line with the resume and USAJOBS

Acceptance Criteria:
Student application - review page: When a student applies, the work experience on the experience page should display in the order selected in Open Opps.
- the default order will be the sorted order from USAJOBS however the order can be changed in Open Opps.  Whatever is saved in Open Opps is the order the review page should display
- the order saved should also be what is sent to ATP

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-25-19 hold till 3994 is complete.

**Comment by Kibrahacha67** [comment]
12-3-19 LHammond in testing

**Comment by kbwagner** [comment]
12/5/19 - KWagner tested in Chrome/Test
Ready for final review

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/70632791-8200fc80-1bfd-11ea-8d5e-49a2c1b057bf.png)

**Comment by kbwagner** [comment]
12/12/19- ready for final review
