### ISSUE TITLE
Sitewide Admin: Opportunities pills not working 

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3972]
Administration -->Opportunities --> Manage
Click on any of the Opportunities pills
Submitted
Open
Not open
In progress
Completed
Canceled
Page does not change and does not reflect the number of opportunities from that particular pill.
Environments: Test and UAT

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Needs to be tested in**
- [ ] Test - Release 8.1
- [ ] UAT - Release 8.0

**Comment by Kibrahacha67** [comment]
9-25-19 LHammond in testing for UAT and Test

**Comment by kbwagner** [comment]
9/25/19 - KWagner tested in Chrome/Test
Ready for final review
