### ISSUE TITLE
Display ATP board close date on cycle page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3985]
Who: Community managers
What: Display ATP board close date in Open Opps
Why: to have dates in one place

Acceptance Criteria:
Administration --> Community --> DoS (Unpaid)  --> Manage Cycles --> Edit
- Display the actual date that the cycle/board was closed in ATP on the manage cycle page at the bottom of the page 
- Non editable/read only
- This field does not need to display on the grid that shows the cycle dates of all cycles (main manage cycles page)

Source: request from ATP team

**Comment by jhanson12** [comment]
@kbwagner and @bmcorum below is a screen of what I came up with based on the info from AC.  I have two questions:
1) Is the label I have given the date sufficient?
2) If there is no date, how/what do you want to display?
![image](https://user-images.githubusercontent.com/15199629/67292535-16c66400-f4b1-11e9-8fb1-a22ae24eca0b.png)

**Comment by kbwagner** [comment]
@jhanson12 i think the label is fine.  If it has not closed yet maybe we just show N/A?

**Comment by jhanson12** [comment]
@kbwagner I am fine with 'N/A' - just was not sure if that was descriptive enough.

**Comment by kbwagner** [comment]
@jhanson12 I did toy with some wording like "The cycle is still open." but wasn't sure if that would look weird.

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-25-19 LHammond in testing

**Comment by jhanson12** [comment]
@Kibrahacha67 a ticket has to created for the field to be updated by ATP - it is a new field and that code does not existed.  Let me know if we need to manually update the field in Open Opps with a screenshot.

**Comment by Kibrahacha67** [comment]
@kbwagner do we know if there has been a ticket input to ATP for the data pull?

**Comment by kbwagner** [comment]
@Kibrahacha67 @jhanson12 wouldn't it just be the date that archive is selected in ATP?  I'm not aware of any new field created in ATP  but I can ask.  I thought it was an existing field that we need to pull from them.

**Comment by Kibrahacha67** [comment]
@kbwagner @jhanson12 - that could be true but question is that field available to open opps to pull or does the team need to make it available...that is more a question for Jodi...

**Comment by Kibrahacha67** [comment]
10-29-19 Putting this ticket on hold as the data portion that would allow the date to show is not completed.  Will need data from ATP to complete this ticket as the AC stands.

**Comment by kbwagner** [comment]
@Kibrahacha67 do we know if ATP has indeed written the ticket for this? and if so when it will be done?  If not I can check.

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - No I talked to Jodi yesterday and that was the sticking point.  That's why I asked the question.  When I test this only response on any page is N/A so there are no dates at all.  If there is a data pull needed to finish it will have to come from Titan otherwise this will never meet the AC.

**Comment by kbwagner** [comment]
Yep I get that...I'll ask Titan in Slack now if they have a ticket for this.

**Comment by Kibrahacha67** [comment]
@kbwagner Hey I just talked to Danny and here is the ticket number they have 39638.  Probably will be in next sprint, but you may want to let them know this ticket is on hold waiting for that work.

**Comment by Kibrahacha67** [comment]
11-12-19 LHammond in testing
Testing completed moving to review.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/41f390dc-357b-4989-84e1-6830f9c371a8)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/a479137b-fbd1-48f9-b88e-d93b70a1a107)

**Comment by kbwagner** [comment]
11/12/19 - KWagner tested in Chrome/test
ready for final review
