### ISSUE TITLE
Bug: Community Admin: Manage Members sort by drop down has Community capped "Admin" in the drop down when should be admin 

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3986]
Administration -->Community-->Members Manage -->Sort by 
Name
Federal email
Agency
Joined date
Community Admin
Environment: Test and UAT

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-1-19 LHammond in testing

**Comment by kbwagner** [comment]
10/1/19 - KWagner tested in Chrome/Test
Ready for final review
