### ISSUE TITLE
Bug: FAI Opportunities page pill for "In progress" showing 5 but the display only shows 3 and count is "viewing 1 - 3 of 5 opportunities"

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3990]
Administration --> Communities --> FAI --> Opportunities (manage)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/9fdc5330-7c27-43bc-836a-7473cecadc87)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-18-19 LHammond in testing
Testing completed moving to review. 
NOTE: I retested this one prior to development and the functionality is not now responding as it was when the ticket was written.  Tested in chrome, ie edge and ff.

**Comment by kbwagner** [comment]
10/21/19 - KWagner tested in Chrome/Test
Ready for final review
