### ISSUE TITLE
Bug: Community Admin: Manage Opportunities: If a filter search is added then the pills and paging is not being updated.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#3992]
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/84865d6e-476a-4fc2-9727-7c1c08a1ced7)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Note:** This needs to be tested in both TEST and UAT

**Comment by Kibrahacha67** [comment]
10-1-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 if at first you do not succeed...try, try again!

**Comment by margaretdumas** [comment]
10/2/2019 - Mdumas - This was re-tested in Test and UAT and all tests were good.  Moving on to review.

**Comment by kbwagner** [comment]
@bmcorum this isn't working how i would expect it to work.  
In Test for the FAI community, there are 11 in submitted status
If I type in Brice and click search, there is one returned
The count by the pill changes to 1 - I would think that would stay at 11
then the page is 1 of 1 of 1 - I would still think it would be 1 of 11?

I had submitted a similar bug on the viewing.  Maybe my mind if thinking of this wrong?

**Comment by bmcorum** [comment]
So without updating the pills the paging is wrong plus you could then select a new pill that has no results based on your applied filter

**Comment by kbwagner** [comment]
Ok...then works as designed.
Ready for final review.
