### ISSUE TITLE
DoS apply: Allow for sorting of work experience

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3994]
Who: Applicants 
What: Ability to sort work experience on an open opps student application
Why: in order to allow students to highlight which work experience should display first

Acceptance Criteria:
- Add the ability to sort work experience in Open Opps by using arrows 
- Work experience will be pulled over from USAJOBS with a USAJOBS assigned sort order
- work experience can be reordered in Open Opps and when saved, the sort in Open Opps should also be saved.

Screen shot of sorting on Work Experience in USAJOBS:
![image](https://user-images.githubusercontent.com/18709918/67790006-58c04e80-fa4b-11e9-816d-2b088ce18320.png)

F

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-02-19 LHammond in testing
tested in chrome, ie, edge and ff.  Could not sort using arrows, page flashed when arrows clicked but sort order didnt change.  this error captured in console.  Moving back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/28ffc2f4-74cc-4b30-8518-0c592f7b847e)

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-3-19 LHammond in testing

**Comment by kbwagner** [comment]
12/3/19 - Kwagner tested in Chrome/Test
Ready for final review
