### ISSUE TITLE
DoS Community Admin page restructure

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3995]
Who: DoS administrators
What: View metrics by cycle on the administration page
Why: In order to have easy access to data

Acceptance Criteria:

Restructure the DoS community admin page

Top Row:
- Users - no change
- Cycles - no change

Add a separator line

Add a line for Cycle with a dropdown where all cycles are listed.  Everything below will display numbers based on the cycle selected:

- Move the existing "Opportunities" section under the cycle selector and rename to "Internships"

- Interactions should be to the right of the Internships

Add a separator line at under this section and before recent activity to make it clear the remaining sections aren't controlled by the selected cycle timeline.

![IMG_3599](https://user-images.githubusercontent.com/18709918/65972095-514f5a80-e437-11e9-8618-78c22e4ffa08.jpg)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-4-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
@abudz19 tagging you on this in case you want to do a design review

**Comment by kbwagner** [comment]
10/7/19 - KWagner tested in Test/Chrome
Ready for final review

Note: The internships section I would think should only show the selected cycle and the last two I picked from the dropdown.  Might need to write a new ticket since this ticket was done before we had the selector for cycle.
