### ISSUE TITLE
DoS: Cycle download reports

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3998]
Who: DoS Administrators
What: Dowload report for cycle data
Why: In order to have easy access to cycle information

Acceptance criteria:
On the Admin --> Community --> DoS page add a Download list (.csv) link beside each section in the cycle selector

Internships: 
Cycle name (selected in dropdown)
Internships - all data displayed on the page for internships
Total created: 
Submitted: 
Approved: 
Open: 
Completed: 

Interactions: 
Cycle name
all data displayed on the page for interactions:
Completed applications
Applications submitted: 0
Incomplete applications
Applications on Next Steps: 0
Applications on step 1 - Select Internships: 
Applications on step 2 - Experiences & References: 
Applications on step 3 - Education & Transcript: 
Applications on step 4 - Languages & Skills: 
Applications on step 5 - Statement of interest: 
Applications on step 6 - Review application: 
Completed internships
Total completed:

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
@bmcorum should there be a link next to the cycle selector?  I thought I saw one last week...
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/b17d75fd-c7cb-4e4a-a051-091905550b54)

**Comment by kbwagner** [comment]
10/10/19 - KWagner tested in Chrome/Test
Ready for final review
