### ISSUE TITLE
DoS: Email to unfinished applicants 3 days prior to closing of apply cycle

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4001]
Who: Applicants
What: Reminder email to complete internship application
Why: to increase numbers and satisfaction

Acceptance Criteria:
Send an email to to applicants who have not completed their application.  The email should go out 3 days prior to the closing date of the apply cycle.

The text of the email will read:
Hello [student name],

The application period for the U.S. Department of State Student Internship Program (Unpaid) will close on [insert date] at 11:59 p.m. EST.

 It looks like you have started an application, but have not submitted it. If you’re still interested in applying to the internship program, click the link below to submit your application before the application period closes.

[Sign into Open Opportunities to submit your application](link to Open Opps).

Did you already submit your application? Great! You can check the status of your application on your [Open Opportunities dashboard](link to Open Opps dashboard). If you need to make an update, don't forget to submit your application again.

Thank you,
The Open Opportunities Team 
U.S. Office of Personnel Management 
1900 E Street NW. 
Washington, DC 20415

**Comment by bmcorum** [comment]
@kbwagner instead of trying to build a time based automated email could we add ability to send our the emails based on a button the community manager clicks on the dashboard? This would allow the community manager the flexibility to send at any point in time without the need to update functionality.

**Comment by kbwagner** [comment]
@bmcorum I discussed this with Michelle last week and she'd really like for it to be automated.  I know you have some concerns on this so we'll just have to work through the issues.

**Comment by bmcorum** [comment]
This will require work outside of the source code for monitoring and troubleshooting.

**Comment by Kibrahacha67** [comment]
2-4-20 LHammond in testing

**Comment by kbwagner** [comment]
@bmcorum @Kibrahacha67 looks like the AC didn't get updated from our decision that times should display as 11:59 p.m. ET.  Not worth holding the ticket up but if by chance it's a quick change : 0 ) I'll take it.  Otherwise can put in a ticket for later.

**Comment by bmcorum** [comment]
@kbwagner and @Kibrahacha67, I have changed EST to ET.

![image](https://user-images.githubusercontent.com/1165615/73848476-32524200-47f6-11ea-9918-51133d801e31.png)

**Comment by kbwagner** [comment]
@bmcorum thanks!  What release will you be assigning this to?

**Comment by bmcorum** [comment]
@kbwagner good catch. This will go out with 8.8

**Comment by kbwagner** [comment]
@nia-johnson this ticket is being added to the 8.8 release. Can you please update the release notes - this is one for State Department.  Thanks!

**Comment by kbwagner** [comment]
@bmcorum so for some reason the subject line didn't get put in the AC.  Should be U.S. Department of State Student Internship Program (Unpaid) – Application period is closing.
- Want a new ticket?  Or is it an easy change to just get this out?

**Comment by bmcorum** [comment]
@kbwagner subject line updated.

![image](https://user-images.githubusercontent.com/1165615/73859028-62eea780-4807-11ea-8804-8ce057bb4e7e.png)

**Comment by kbwagner** [comment]
2/5/20 - KWagner reviewed
Closing
