### ISSUE TITLE
DoS internship cancel process

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4007]
Who: State users
What: Ability to cancel their internships
Why: In order to cancel internships that should no longer be posted

Acceptance Criteria:
State would like for the ability to cancel an internship.

1) Add a "Cancel this internship" link on the internship page
Screen shot of cancel link for a regular opportunity: 
<img width="383" alt="Screen Shot 2019-10-17 at 10 24 09 AM" src="https://user-images.githubusercontent.com/18709918/67017815-4ac41280-f0c8-11e9-8b1a-4d324eadc956.png">

2) Only the creator of the internship, a community manager for the Student community, or a sitewide administrator will be able to view and click the link

3) when the Cancel link is selected, a confirmation modal will appear (screen shot is of current cancel modal for opportunities) 

<img width="946" alt="Screen Shot 2019-10-17 at 10 31 18 AM" src="https://user-images.githubusercontent.com/18709918/67018490-519f5500-f0c9-11e9-9d88-385f97662854.png">
The text on the modal should read, "Are you sure you want to cancel this internship?
The messaging should read, "If you cancel this internship, applicants will no longer be able to apply to it. You will also remove any applicants who have already applied for this internship."

4) An internship can be canceled in draft, submitted, or approved status.  
- Internships in Open status can be canceled if the apply cycle is still open and will send emails to applicants (via separate ticket).  
- Internship in Open status where the apply cycle has been closed can't be canceled
- Internships in Complete status can't be canceled

Note: 
-  Emails will be sent to applicants via separate tickets.
- Tracking data will be in a separate ticket

Related tickets: 
4007 - Internship Cancel process
4064 - Email if open and has applicants to apply again
4127- email if internship canceled, has applicants, apply is closed
4128 - Email - canceled with selectee after review cycle closed
4129 - Tracking data on cancel

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-6-19 LHammond in testing

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested in Chrome/Test
Ready for final review
