### ISSUE TITLE
Community administration dashboard access

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#4008]
Users who are only community admins can no longer access the administration dashboard.

Acceptance Criteria:
- Community managers should be able to access the community administration dashboard

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Note:** This will need to be tested in both TEST and UAT

**Comment by Kibrahacha67** [comment]
10-2-19 LHammond in testing

**Comment by kbwagner** [comment]
10/2/19 - KWagner tested in Chrome/Test
Ready for final review
