### ISSUE TITLE
DoS: Update text on next steps page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4009]
Who: Student applicants
What: Next steps page content
Why: In order to provide more information related to closing time, clicking submit, and pulling data from USAJOBS.

Acceptance Criteria:

Update the text.  
Add a 6th step that says:
6. Review and submit application
Double check your application and submit it before 11:59 p.m. EST on the closing date. Don't forget to click Submit.

Update the intro to say:
To save time, we'll import your information in your USAJOBS profile into your application. Review your USAJOBS profile to make sure all of your information is correct before you start the application.

If you update your USAJOBS profile after you start the application, you must come back to Open Opportunities and update your application as well.

If you make edits to your application, the information will not update in your USAJOBS profile.

Related Tickets:
4118 - Move USAJOBS data pull from apply button to next steps continue
4009 - update next steps text
4119 - Modal to say we're pulling from USAJOBS

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-08-19 LHammond In Testing

**Comment by kbwagner** [comment]
11/12/19 - KWagner tested in Chrome/Test
Ready for final review

**Comment by kbwagner** [comment]
@raywilliams - discussed this with @jhanson12  can you please make the p.m. lowercase with periods.  I just updated the AC.  Should say 11:59 p.m. EST.

Thanks!

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-12-19 LHammond in testing
Testing completed moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ff31330b-b4c4-4f0d-a12b-ac930aa9cafc)

**Comment by kbwagner** [comment]
11/13/19 - KWagner tested in Chrome/Test
Ready for final review
