### ISSUE TITLE
Two way application data between USAJOBS and Open Opps

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4011]
Applicants are not understanding that once they click apply, any updates on USAJOBS will no longer be pulled over.  Michelle has suggested two way updates.

Other options: 
Refresh button
modal on apply

**Comment by bmcorum** [comment]
@kbwagner and @tlorrison my only concern is we don't do two way updates in USAJOBS. This would be like adding two way updates to resumes in USAJOBS that are used for JOA applications. You run the risk of deleting or changing data in USAJOBS that a user never intended to do. In my mind USAJOBS profile is meant to be the foundation from which I start my application experience, and any changes I wish to make should be unique to that application experience and not affect my future applications.

**Comment by nia-johnson** [comment]
Plan is to retire profile in Open Opps and pull out Profile as a separate product. Closing.
