### ISSUE TITLE
Opportunities metrics at start of new fiscal year

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#4022]
When a new fiscal year start the opportunities metrics section on the administration dashboards is not being populated for the new fiscal year.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-8-19 LHammond in testing

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment]
10/10/19 - Mdumas - In testing...

**Comment by kbwagner** [comment]
10/10/19 - KWagner reviewed in test/Chrome
Ready for final review

NOTE: may want to consider in the future having current fiscal year display first and then sequentially down from there.
