### ISSUE TITLE
Track student application withdrawals

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4024]
Who: Students who withdraw their applications
What: Track data related to withdrawals
Why:  in order to provide metrics on how many withdrawals occured

Acceptance Criteria:
When a student application is withdrawn, track the following:
- That the application was withdrawn
- the date the application was withdrawn

**Comment by bmcorum** [comment]
Ready for testing.

![image](https://user-images.githubusercontent.com/1165615/70065634-6d978100-15b9-11ea-94de-cd2d0c5c8c63.png)

**Comment by Kibrahacha67** [comment]
12-3-19 Artifact attached moving to review.

**Comment by kbwagner** [comment]
12/3/19 - KWagner reviewed artifact. 
Ready for final review
