### ISSUE TITLE
Dos: Do not move approved internships back to submitted once edited

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4027]
Who: Internship creators
What: keep internship in approve status even if edited
Why: In order to prevent internships with student applicants from sitting in submit status and not receiving applications

Acceptance Criteria:
- If a student internship (unpaid) that is in approved  or open status has been edited and saved, do not move the internship back to submit status.  It should stay in approved/open.

Note: If an internship needs to be pulled back for any reason, it will have to be canceled following that new process. (separate ticket)

**Comment by bmcorum** [comment]
This is ready for testing.

**Comment by Kibrahacha67** [comment]
10-18-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
Created ticket 4077 with the edit per Brice request and updated AC

**Comment by kbwagner** [comment]
10/21/19 - KWagner tested in Chrome/Test
Ready for final review
