### ISSUE TITLE
Bug: Community member page displays open opps join date instead of community join date

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4028]
Environment: All

Issue:  community user page join date is open opportunities join date not community join date

Steps to reproduce:
- Admin --> Community --> Members --> Manage
- Joined date should display the date the user was added to the community

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-11-19 LHammond in testing

**Comment by kbwagner** [comment]
KWagner tested in Chrome/Test
Ready for final review
