### ISSUE TITLE
Update to DoS interactions

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4030]
Who: DoS Admins
What: View interactions data change
Why: to make more sense on the apge

DoS Interactions section (Admin --> Community --> DoS --> Interactions)
- Remove the bottom section called "Completed internships" 
- Replace with 
Student interns:
   Primary selections: x (number of student interns selected as a primary)
   Alternate selections: y (number of student interns selected as an alternate)
   Successfully completed: z (number of student interns marked as having completed an internship)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-18-19 LHammond in testing,
Testing completed.  moving to reveiw

**Comment by kbwagner** [comment]
10/21/19 - KWagner tested in Chrome/Test
Ready for final review
