### ISSUE TITLE
Bug: Manage user search doesn't search full name

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4033]
Environment; Test

Steps to reproduce:
1) Navigate to Sitewide Admin --> Users --> Manage
2) Enter Mary Poppins in the search filter - no results
3) Enter just Mary - Mary Poppins is returned
4) Enter just Poppins - Mary Poppins is returned
- Also occurs on the agency and community manager users search

I should be able to search on the full user name to narrow down the search.
If the user has a middle name, I should also be able to search using their middle name or initial (i.e. Barry B Goode in test)

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-18-19 LHammond in testing

**Comment by kbwagner** [comment]
10/21/19 - KWagner tested in Chrome/Test
