### ISSUE TITLE
Bug: DoS metrics doesn't save cycle when click back button

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4034]
Environment: test

Issue/Steps to follow:
1) On the DoS community dashboard, select a cycle such as Julie test
2) Click on manage beside Internship
3) View the data and click the back link on the page
- The cycle I selected has reverted back to the default.

Using the back link on the page or the back button on my browser should maintain the selected cycle.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-11-19 LHammond in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
10/16/19 - KWagner tested in Chrome/Test
Ready for final review
