### ISSUE TITLE
Bug: Manage Internships is displaying incorrect counts for applicants

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4035]
environment: Test

Steps to reproduce:
1) Navigate to Admin --> Community --> DoS Unpaid --> Opportunities --> Manage
2) View the number of applicants for each - applicants who have not submitted their application are being included in the count.

Only submitted applications should be displayed here.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

Number of submitted applications should be 3 times number of applicants

**Comment by Kibrahacha67** [comment]
10-9-19 LHammond in testing

**Comment by kbwagner** [comment]
10/15/19 - KWagner reviewed in test/Chrome
Ready for final review
