### ISSUE TITLE
DoS: Hide admin metrics section for DoS community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4043]
Who: State administrators
What: Hide metrics section on Admin for DoS community
Why: Because it contains repetitive information

Original Ticket 3910
- Remove the metrics section of the DoS unpaid admin dashboard as it is duplicative

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
10/10/19 - KWagner reviewed in Chrome/Test 
Ready for final review
