### ISSUE TITLE
DoS application: Track submit and update dates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4046]
Who: System Admin 
What: Log application data
Why: In order to supply data when requested

Acceptance Criteria:
Issue: students are submitted their applications, then making updates but not submitting again. Tracking data will help us support applicants that have questions.
- Log the date when an application is first submitted
- Log the date when an application is updated

**Comment by jhanson12** [comment]
[results.xlsx](https://github.com/openopps/openopps-platform/files/3821538/results.xlsx)

@Kibrahacha67 and @margaretdumas  this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-7-19 Artifact attached moving to review.

**Comment by kbwagner** [comment]
11/12/19 - KWagner reviewed artifact
Ready for final review
