### ISSUE TITLE
Bug: Community managers can't view applicants in production

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4048]
Environment: Production

Issue: community managers can’t view applicants in production. Sitewide admins can view.

Steps to reproduce: 
1) navigate to Admin --> Community --> DoS --> Internships --> Manage
- select a cycle that has applicants
- Select an internship that has applicants and click View link
- no applicants are displayed

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 I have reviewed the code and cannot see what would be causing this issue. Can you please verify if this is an issue in TEST or UAT. The current code in UAT is scheduled to be release to production on Monday.

**Comment by Kibrahacha67** [comment]
10-18-19  LHammond in testing
Tested this against Test and UAT.  With several different accounts related to the community admin and Sitewide admins.  Test conducted in ie, edge, chrome.  Several different cycles utilized and could not find a account/cycle combo for community admins where could not see applicants on internships.  Also did see where Internships were in progress so the total number of applicants vs interns in progress was different (as should be) but both accounts matched.  It looks like we  have fixed this problem with another ticket.  moving to review.

**Comment by kbwagner** [comment]
10/21/19 - Works in Test...but always did work in test.  Will have to retest in production once this moves.
KWagner/Test/Chrome
Ready for final review
