### ISSUE TITLE
View what applicants have applied to

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4049]
Who: Community managers and sitewide admins/help desk
What: ability to search for applicants and view what they applied for
Why: in order to assist applicants with questions and confirm applications

Acceptance Criteria: 
Issue: Need to implement a way to search and display what applicants have applied for.

- Add a link called "Search applications" under the Interactions heading for the state community
![image (30)](https://user-images.githubusercontent.com/18709918/67794868-c6707880-fa53-11e9-9402-a9fae9821fa6.png)

- When the link is selected, a table will display with the following information: 
Applicant name, email address, and applicant status and last update timestamp in EST
- When applicant status is anything other that in process or not completed, the status will be a link.
- only applicants for the selected cycle will display
- When selected, the link will open a new window to display the 3 internships that applicant applied to.  The page will be the same page as the internship selection page without the update or withdraw buttons.  The student name will appear at the top of the page as {Student Name's} application
![image](https://user-images.githubusercontent.com/18709918/67795444-a2f9fd80-fa54-11e9-88d2-8bc7e1ce6b94.png)

Related tickets: 
4049 - create applicant list
4130 - Filter on applicant list
4133 - Sort by on applicant list
4134 - .csv of applicants

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by tanichacko** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-19-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner - Question here.  On the page that is opened for the student application, if the applciation was not submitted what should the wording be?  currently it says "you have submitted the following...."  wording was not part of this AC, but seems out of wack. image below
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/997eac62-f0f8-4edc-9497-c0b54ea84ffe)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ded65667-6993-43fc-a9bb-88be6fb34d87)

**Comment by kbwagner** [comment]
@Kibrahacha67 the AC says it shouldn't be a link for in process or not completed so if the link is showing for those might need to go back

**Comment by Kibrahacha67** [comment]
@kbwagner ok but that does not cover not submitted...Sending back to development after talking to brice...

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-20-19 LHammond in testing

**Comment by kbwagner** [comment]
11/21/19 - KWagner tested in Chrome/test
@tanichacko can you confirm that the last update shows in Eastern time since I think the system time is General?  If so, I might create a new ticket to add (ET) beside the last update field label to avoid confusion.

Ready for final review

**Comment by bmcorum** [comment]
@kbwagner last updated is stored at UTC (GMT) time. When it gets displayed in the browser the user's machine will auto convert the time to the whatever timezone the logged in user is in.

**Comment by kbwagner** [comment]
@bmcorum thanks...I won't change the label then.  Just knew that the spreadsheet you gave me was in GMT so wanted to make sure we didn't see that.
