### ISSUE TITLE
Bug: View applicant display on mobile overlaps

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4050]
Environment: Production

Issue: When viewing applicants through the admin dashboard on a mobile phone, the names overlap

Tested with iPhone

Steps to reproduce:
1) On a mobile phone, navigate to Admin --> Community --> internships --> manage
- select an internship with applicants and select View
- applicant names overlap (see screen shot)

<img width="307" alt="Screen Shot 2019-10-15 at 1 44 38 PM" src="https://user-images.githubusercontent.com/18709918/66855840-fe56c680-ef51-11e9-92b6-3ee5d4388780.png">

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-27-19 LHammond in testing

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Safari
Ready for final review
