### ISSUE TITLE
Display current fiscal year first in metrics followed by previous fiscal years

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4052]
Who: Administrators
What: Ability to view current cycles first
Why: in order to view current data ahead of historic data

Acceptance Criteria: 
admin metrics should display current fiscal year first and then previous fiscal year in displays
- This should occur for sitewide, admin, and communities

<img width="1180" alt="Screen Shot 2019-10-15 at 2 21 32 PM" src="https://user-images.githubusercontent.com/18709918/66858365-23016d00-ef57-11e9-9221-a30453492fc6.png">

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-18-19 LHammond in testing

**Comment by kbwagner** [comment]
12/19/19 - KWagner tested in Test/Chrome
Ready for final review

Will write an additional ticket to make the quarter and month options work the same way.
