### ISSUE TITLE
Apply friction if creator isn't a member of the student community but tries to create internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4055]
Who: Internship creators
What: Apply friction for users who aren't members of the student community
Why: To prevent them from creating internships outside of the community

Acceptance criteria:
- When a creators goes to the Target audience page, always show Student as an option in addition to federal
- If the user clicks "Student" and they aren't a member of the student community display a message "You're not a member of a Student community. Please contact [insert email from community attribute table which should be StudentInternship@state.gov] and ask to be added to the community. Please do not create the internship until you receive confirmation that you're a member of a Student community."

**Comment by kbwagner** [comment]
@dalenard21 can you take a look at the wording for this message when you have a chance please?

**Comment by dalenard21** [comment]
Hi @kbwagner slight edit:

You're not a member of a Student community. Please contact [insert email from community attribute table which should be StudentInternship@state.gov] and ask to be added to the community. Please do not create the internship until you receive confirmation that you're a member of a Student community.

**Comment by kbwagner** [comment]
@dalenard21 that works thanks!

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-5-19 LHammond in testing

**Comment by kbwagner** [comment]
12/10/19 - KWagner tested in Chrome/Test
Ready for final review
