### ISSUE TITLE
Add bureau/office post to profile for State users

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4056]
Who: Department of State Users
What: Add bureau/office post to profile
Why: in order to be able to manage work better

Acceptance Criteria:
- For a user who is a member of the State community or whose agency is "Department of State" of any level, add Bureau and Office/post as optional fields to their Open Opportunities Profile.
- The data will be the same as currently used for these fields
- The functionality will work the same way as it does for the create internship where you must select a Bureau prior to an office/post
- The fields will not be required
- The fields should be a new section clearly separated from the Edit at USAJOBS.gov fields (add a separator line possibly)

Related Tickets:
4056 - Add bureau and office/post to state user's Open Opps profile
4060 - pop up message at  login for state users to add bureau and office/post to their profile
4061 - Add bureau/office post to state manage user dashboard
4062 - limit who gets the email to approve internship

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - Question will there be a save and cancel button here once the user has selected their Bureau and office?

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-23-19 LHammond in testing

**Comment by kbwagner** [comment]
10/28/19 - KWagner tested in Chrome/Test
Ready for final review
