### ISSUE TITLE
Update Department of State Unpaid Student Internship Program – Selected as an Alternate for Internship Email

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#4058]
Update the alternate selection email with the following content from the attached document file.

[Department-of-state-unpaid-student-internship-program-selected-for-alternate-internship-offer-email_v9_20191009 (1).docx](https://github.com/openopps/openopps-platform/files/3736147/Department-of-state-unpaid-student-internship-program-selected-for-alternate-internship-offer-email_v9_20191009.1.docx)

**NOTE:** The "Learn more about your internship placement and responsibilities" link should point to https://careers.state.gov/intern/student-internships/

**Comment by bmcorum** [comment]
[U.S. Department of State Student Internship Program (Unpaid)You have been selected as an alternate for an internship..zip](https://github.com/openopps/openopps-platform/files/3767585/U.S.Department.of.State.Student.Internship.Program.Unpaid.You.have.been.selected.as.an.alternate.for.an.internship.zip)

**Comment by bmcorum** [comment]
See attached zip file.

**Comment by Kibrahacha67** [comment]
10-24-19 LHammond Testing for the email in the artifact attached. moving to review.

**Comment by kbwagner** [comment]
@bmcorum 
1) please add a line break/blank line between the two paragraphs in "What does an alternate mean"
2) please add a line break/blank line for #2 before You must complete the security clearance process even as an alternate

**Comment by bmcorum** [comment]
[U.S. Department of State Student Internship Program (Unpaid)You have been selected as an alternate for an internship. (2).zip](https://github.com/openopps/openopps-platform/files/3779724/U.S.Department.of.State.Student.Internship.Program.Unpaid.You.have.been.selected.as.an.alternate.for.an.internship.2.zip)

**Comment by Kibrahacha67** [comment]
10-28-19 Artifact attached moving to review.

**Comment by kbwagner** [comment]
@bmcorum did you see my comments on here about line breaks?  I still don't see them.

**Comment by bmcorum** [comment]
[U.S. Department of State Student Internship Program (Unpaid)You have been selected as an alternate for an internship.(3).zip](https://github.com/openopps/openopps-platform/files/3784184/U.S.Department.of.State.Student.Internship.Program.Unpaid.You.have.been.selected.as.an.alternate.for.an.internship.3.zip)

**Comment by Kibrahacha67** [comment]
10-29-19 Artifact attached moving to review.

**Comment by kbwagner** [comment]
10/29/19 - KWagner reviewed artifact
Ready for final review
