### ISSUE TITLE
Update Department of State Unpaid Student Internship Program – Selected for Internship Email

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#4059]
Update the primary selection email with the following content from the attached document file.

[Department-of-state-unpaid-student-internship-program-selected-for-internship-offer-email_v9_20191008.docx](https://github.com/openopps/openopps-platform/files/3736151/Department-of-state-unpaid-student-internship-program-selected-for-internship-offer-email_v9_20191008.docx)

**NOTE:** The "Learn more about your internship placement and responsibilities" link should point to https://careers.state.gov/intern/student-internships/

**Comment by bmcorum** [comment]
[U.S. Department of State Student Internship Program (Unpaid)You have been selected for an internship..zip](https://github.com/openopps/openopps-platform/files/3767598/U.S.Department.of.State.Student.Internship.Program.Unpaid.You.have.been.selected.for.an.internship.zip)

**Comment by bmcorum** [comment]
See attached zip file

**Comment by Kibrahacha67** [comment]
10-24-19 LHammond Testing for the email in the artifact attached. moving to review.

**Comment by kbwagner** [comment]
10/28/19 - 
@bmcorum I see two issues with the primary selection email: 
I’ll send the ticket back momentarily – the word “alternate” should not appear here in number 1 because this is the selected email
1. Submit additional information
If you want to accept this internship as an alternate, you must answer a few more questions.
-	Also, Security clearance is blank but it’s a required field

**Comment by bmcorum** [comment]
[U.S. Department of State Student Internship Program (Unpaid)You have been selected for an internship. (2).zip](https://github.com/openopps/openopps-platform/files/3779722/U.S.Department.of.State.Student.Internship.Program.Unpaid.You.have.been.selected.for.an.internship.2.zip)

**Comment by Kibrahacha67** [comment]
10-28-19 Artifact attached moving to review

**Comment by kbwagner** [comment]
10/28/19 - KWagner reviewed artifact. 
Ready for final review
