### ISSUE TITLE
Tip to tell State users to update their profile 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4060]
Who: State users
What: Warning to let them know to add Bureau and Office/post to their profile
Why: in order to better manage their work

Acceptance Criteria:
- At login, if a user is associated to the Department of State (unpaid) community and they do not yet have a Bureau and Office/post on their Open Opps profile, provide them with a warning message that reads:
**Heading:** Update your profile
**Body content:** You need to add your **Bureau and Office/post** to your profile before you can create an internship.
**Button label:** Update profile

- The button on the warning message should read, "Update profile"
- "Update profile" will take the user to their Open Opportunities profile

System alert: use Warning with footer: https://usajobs.github.io/design-system/alerts/ or see Alex's comment below

Related Tickets:
4056 - Add bureau and office/post to state user's Open Opps profile
4060 - pop up message at  login for state users to add bureau and office/post to their profile
4061 - Add bureau/office post to state manage user dashboard
4062 - limit who gets the email to approve internship

**Comment by kbwagner** [comment]
@abudz19 can you take a look at this and make sure you're ok with the flow and buttons design wise?
@dalenard21 any recommendations for the language?

**Comment by abudz19** [comment]
<img width="571" alt="AttributeTable_sketch" src="https://user-images.githubusercontent.com/11526811/67024498-82d05300-f0d2-11e9-80d1-10d7de6c8a6d.png">


Do you have a preference between these? @dalenard21 Any updates to the text?

**Comment by kbwagner** [comment]
@abudz19 @dalenard21 all works for me. Thanks!

**Comment by kbwagner** [comment]
@dalenard21 one thought - do we need to say Open Opportunities profile to differentiate between USAJOBS?  But then again we're supposed to really only have one profile...and we are directing them to the right place with the button.

**Comment by dalenard21** [comment]
@kbwagner I think it's okay to leave out Open Opportunities and just keep it as "profile", especially if we're linking them to the open opps profile page.

Another thought - does it make sense to look into adding this to their USAJOBS profile at some point?  If a DOS employee selects "DOS" as their agency in their USAJOBS profile, could we display another field to capture their Bureau/Office post?

**Comment by bmcorum** [comment]
@dalenard21 bureau and office data is irrelevant to USAJOBS and also currently only exists in Open Opportunities. Also this data is in no way official or controlled.

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-25-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
10-25-19 LHammond in testing
Message pops even if the user already has the information on their profile, see images below.  Sending back to development

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/199e718e-644a-4854-a942-af1a0edc2bd0)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/1ba7dd78-5ef7-4ce2-a1b2-db04274acf10)

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-29-19 LHammond in testing
The functionality works, but the button has the wrong color scheme.  Currently it is Blue with Black text.  It should be Blue with white text as the the ticket has it.  Sending back to development.


![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/badb4b20-e79d-4b26-bd90-fc25f205eaf6)

**Comment by Kibrahacha67** [comment]
10-29-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
10/31/19 - KWagner tested Chrome/Test
Ready for final review
