### ISSUE TITLE
Add Bureau/Office post to State Manage user dashboard

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4061]
Who: State Administrators
What: Ability to view Bureau/Office post for community members
Why: To assist with their workload

Acceptance Criteria: 
Administration --> Community --> Users --> Manage
- Remove Agency 
- Add Bureau and Office/post columns to the Manage User page for the State (unpaid) community
- The fields should display after federal email

Related Tickets:
4056 - Add bureau and office/post to state user's Open Opps profile
4060 - pop up message at  login for state users to add bureau and office/post to their profile
4061 - Add bureau/office post to state manage user dashboard
4062 - limit who gets the email to approve internship

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-23-19 LHammond in testing

**Comment by kbwagner** [comment]
10/28/19 - KWagner tested in Test/Chrome
Ready for final review
