### ISSUE TITLE
Limit what can be edited on an internship once approved

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4063]
Who: State users
What: Limit what can be edited on an internship once approved
Why: To prevent substantial changes that change what an applicant is applying for

Acceptance Criteria:
Limit what can be edited on an internship once approved:

If the internship has been approved but is not yet open:
• Any fields can be changed

If internship is open for applicants:
• Cycle cannot be changed
• Any other field can be changed

Note: If location or bureau/office/post is changed, we will need to email applicants who have already applied.  Separate tickets.

**Comment by bmcorum** [comment]
@kbwagner so do we want to disable these fields?

**Comment by bmcorum** [comment]
@kbwagner and @tlorrison wonder if we should do something like...

If _approved_
- Changing bureau/office requires new approval
- Any other fields can be changed

If _open_
- Cycle cannot be changed
- Bureau/Office cannot be changed
- Location can only be changed by a manager
- Any other field can be changed

**Comment by Kibrahacha67** [comment]
10-23-19 @kbwagner @bmcorum - in order to write test cases the above questions need to be answered as the AC does not confirm which fields are not to be edited and which are and when...ty

**Comment by kbwagner** [comment]
@Kibrahacha67 yep this one isn't even requirements ready yet - working on it with state

**Comment by Kibrahacha67** [comment]
@kbwagner ok will let brice know...they are working it now.

**Comment by kbwagner** [comment]
@bmcorum I think this one is ready now after some back and forth with state. I have separate tickets for emails but they will have to go out later

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-31-19 LHammond in testing

**Comment by kbwagner** [comment]
11/5/19 KWagner tested 
Ready for final review
