### ISSUE TITLE
Internship cancel email - internship canceled but select another internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4064]
Who: Internship applicants
What: Notification of cancelation of an internship while application period is still open
Why: to allow them to update their application to select another

Acceptance Criteria:
- If an internship is canceled, has applicants, and the application deadline is still open, send the following email.
Email Subject - Department of State Student Internship Program (Unpaid) - One of your internship has been canceled.

Hello, [Username},
We want to let you know that the Department of State has canceled one of your internship opportunity selections.

You can select another internship to apply to, or you can continue with just the two internship you’ve already selected.

If you’d like to add another internship, click the link below to make your selection before the application period closes.

[Sign into Open Opportunities to select another internship](link to Open Opps).

If you don’t want to select another internship, you don’t need to do anything.

You can check the status of your application on your [Open Opportunities dashboard](link to Open Opps dashboard). If you need to make an update, don't forget to submit your application again.

Thank you,
The Open Opportunities Team 
U.S. Office of Personnel Management 
1900 E Street NW. 
Washington, DC 20415

Related tickets: 
4007 - Internship Cancel process
4064 - Email if open and has applicants to apply again
4127- email if internship canceled, has applicants, apply is closed
4128 - Email - canceled with selectee after review cycle closed
4129 - Tracking data on cancel

**Comment by tanichacko** [comment]
@Kibrahacha67 ready for testing

**Comment by Kibrahacha67** [comment]
12-10-19 LHammond in testing
The Link "Sign into Open Opportunities to select another internship" is in the wrong position.  It is before the "If you don't want to select another internship, you don't need to do anything."  It should follow that sentence, from the AC.  moving back to development 

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/15cc8863-e32d-4d6f-83b1-0b9117746036)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-11-19 LHammond in testing

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested in Chrome/Test
Ready for final review
