### ISSUE TITLE
Ability for Community Managers to update Office/Post information - Edit

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4065]
Who: State community managers
What: Ability to Edit Bureau/Office/post
Why: in order for them to self maintain their constantly changing organization structure

Acceptance Criteria:
As a community manager, I need the ability to update office/post information as it changes per cycle through the UI of Open Opportunities.
- State (unpaid) Community managers and sitewide administrators will have access to update the bureau/office/post information
- Navigation: Administration --> Community --> Department of State Student Internship Program (unpaid) --> Manage community
- At the bottom of the existing page add a section called "Bureau and Office/Post Information"
- There will be an "+ Add new" button
- There will be a grid that displays all of the Bureaus in bold with associated Office/post underneath.
- Each bureau and office/post will have an Edit and Delete icon to the right. Alt Tags should display for Edit and Delete

Acceptance Criteria:
Edit:
- If Edit is selected beside a Bureau/Office/Post, the following modal will appear https://opm.invisionapp.com/share/U8R4CAV3HXF#/388169634_Open_Opps_-_Add_Office_Or_Bureau_-_With_Modal_-_Edit_Step_1
- Header Edit Bureau or Office/post
- All fields are required.

- If a Bureau or Office/post is duplicative of an existing Bureau or office/post, notify the user that this already exists.  When checking for duplication, case should not matter.
- Tracking data should track who edited,  what was deleted, and the date/time.

- There will be Cancel and Save buttons.
- Cancel will close the modal and not save
- Save will save the edit and return the user to the manage community page and will display a success message at the top of the page.

Mocks: https://opm.invisionapp.com/share/U8R4CAV3HXF#/388169635_Open_Opps_-_Add_Office_Or_Bureau_-_Delete_Success

Related tickets:
3851 - add new
4065 - Edit
4066 - Delete

**Comment by bmcorum** [comment]
**Updated mock:** https://opm.invisionapp.com/share/U8R4CAV3HXF#/388169636_Open_Opps_-_Add_Office_Or_Bureau_V4

**Comment by kbwagner** [comment]
@raywilliams @lawrencek76 Alex has wired the mocks to help a bit on this.  I did see some duplicate stuff in the AC so I cleared that out. But the AC should match the mock.  Thanks!

**Comment by tanichacko** [comment]
![bureau_updated.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/8a153029-2caf-4c49-b69b-22f382b179ed)

**Comment by tanichacko** [comment]
![bureau data updated.png](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/be6e4750-4dba-4ba3-8d7c-08be781f63d6)

**Comment by tanichacko** [comment]
![office updated.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/d1dcac68-d38a-4df8-bc39-bb8e0d64ed87)![office data updated.png](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/aba0528b-e871-41a9-ae9c-96cda8f53ed6)

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas  this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-06-19 LHammond in testing

**Comment by kbwagner** [comment]
11/13/19 - KWagner tested in Chrome/Test
Ready for final review

**Comment by kbwagner** [comment]
@abudz19 the add/edit/delete office data tickets are available in test if you'd like to take a look.
