### ISSUE TITLE
Ability for Community Managers to update Office/Post information - Delete

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4066]
Who: State community managers
What: Ability to add/remove Bureau/Office/post
Why: in order for them to self maintain their constantly changing organization structure

Acceptance Criteria:
As a community manager, I need the ability to update office/post information as it changes per cycle through the UI of Open Opportunities.
- State (unpaid) Community managers and sitewide administrators will have access to update the bureau/office/post information
- Navigation: Administration --> Community --> Department of State Student Internship Program (unpaid) --> Manage community
- At the bottom of the existing page add a section called "Bureau and Office/Post Information"
- There will be an "+ Add new" button
- There will be a grid that displays all of the Bureaus in bold with associated Office/post underneath.
- Each bureau and office/post will have an Edit and Delete icon to the right. Alt Tags should display for Edit and Delete

Delete:
If the delete icon is selected beside the bureau or office/post, the following message will display 

https://opm.invisionapp.com/share/U8R4CAV3HXF

A red modal will appear to that reads, "Confirm delete bureau or office/post"
Then text that reads, "Are you sure you want to delete the [insert name here}from your community?  If you delete the bureau, you will also delete all of its offices and posts."
- There will be a Cancel button that will close the modal and not delete the selection.
- There will be a Delete button that will close the modal and remove the selection.  A confirmation will display on the Manage community page.  "Bureau deleted" and "You have successfully removed the {insert bureau name} from your community."
- The bureau or office/post will not be deleted but will be inactivated.  
- Deleting a bureau will also delete all of the offices/posts under it
- Tracking data should track who deleted, what was deleted, and the date/time.

Mocks: https://opm.invisionapp.com/share/U8R4CAV3HXF#/388169635_Open_Opps_-_Add_Office_Or_Bureau_-_Delete_Success

Related tickets:
3851 - add new
4065 - Edit
4066 - Delete

**Comment by abudz19** [comment]
@kbwagner Looks good.

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - Question as the Bureau's are parents to the office/post entries, if I delete a Bureau that is connected to several offices/posts, will they be inactivated as well?

**Comment by kbwagner** [comment]
@Kibrahacha67  good question yes they would have to be deleted or else they are orphans right @bmcorum 
we should update the messaging to reflect that on the delete confirmation (which Debbie might have already done there is a message waiting for me on some updates to content for this piece I need to look at)

**Comment by kbwagner** [comment]
10/29/19 - updated the AC to reflect a confirmation message after successful delete.

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas  this is ready for testing.

**Comment by tanichacko** [comment]
Bureau deleted
![Bureau deleted.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/7b48a4c8-5021-476e-accb-e34f1ec9598b)

Bureau deleted info with associated![bureau deleted information.png](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/2c6bca22-2a8b-4086-958d-fee5a0e4644f)
office deleted
![office deleted.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/73c3847f-6604-498a-a64b-cb1e89347e51)
office delete info 
offices![office deleted info.png](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/a77298f3-e4cc-4e3b-bf15-d247e6559109)

**Comment by Kibrahacha67** [comment]
11-08-19 LHammond in testing

**Comment by kbwagner** [comment]
11/13/19 - Kwagner tested in Chrome/Test
Ready for final review
