### ISSUE TITLE
Update DoS interactions CSV file

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4076]
Who: DoS Administrators
What: Updates to the CSV file
Why: To reflect system changes

Ticket 4030 updated the DoS interactions

Update the DoS csv file found under interactions on the community admin Dashboard as follows:
- Remove:  "Completed internships"
- Add: 
Primary selections: x (number of student interns selected as a primary)
Alternate selections: y (number of student interns selected as an alternate)
Successfully completed: z (number of student interns marked as having completed an internship)

**Comment by bmcorum** [comment]
This is ready for testing.

**Comment by Kibrahacha67** [comment]
10-23-19 LHammond in testing

**Comment by kbwagner** [comment]
10/28/19 - KWagner tested in Chrome/Test
Ready for final review
