### ISSUE TITLE
Delete draft confirmation modal - update text

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4078]
Who: Opportunity creators
What: Delete draft confirmation modal
Why: Update wording to not use passive voice

Acceptance Criteria:

Modify the text on the delete confirmation modal that displays when a user clicks to delete a draft internship from their landing page:

Heading:
Confirm delete opportunity

Message:
Are you sure you want to delete [insert opportunity name]?

If you delete this opportunity, you can't get it back.

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-06-19 LHammond in testing

**Comment by kbwagner** [comment]
11/7/19 - KWagner tested in Chrome/Test
Ready for final review
