### ISSUE TITLE
Delete cycle modal - update confirmation text

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4079]
Who: Community managers
What: Delete cycle modal update
Why: to not use passive voice

When a community manager for DoS tries to delete a cycle, update the text on the modal as follows:

Heading:
Confirm delete cycle

Message:
Are you sure you want to delete [insert cycle name]?

If you delete this cycle, you can't get it back.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-4-19 LHammond in testing
Heading for modal does not match the AC.  moving back to development

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/226d165d-3a55-4d25-86c5-84413956b49e)

**Comment by bmcorum** [comment]
@Kibrahacha67 according to [USAJOBS Design System](https://usajobs.github.io/design-system/modals/) delete modals have the lines "If you delete this _blank_, you can't get it back." in bold text.

![image](https://user-images.githubusercontent.com/1165615/70146426-1d2f2a80-1670-11ea-9b33-8492caf88f7c.png)

**Comment by Kibrahacha67** [comment]
@bmcorum - Ok does that apply to the Heading as well?  Does it have to be Delete cycle confirmation?  Or can it match the AC?

**Comment by bmcorum** [comment]
@Kibrahacha67 no, you were correct in notating that the header does not match the AC. A correction will be published shortly for retesting.

**Comment by Kibrahacha67** [comment]
12-4-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/4/19 - KWagner tested in chrome/test
ready for final review
