### ISSUE TITLE
Bug: Changing Agency Admin rights not functioning

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4083]
If a user tries to remove agency admin permissions then the system goes into wait mode.  Link to the Agency table broken

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/1ca88732-f8bc-4f6e-bd27-ad5e34300013)

**Comment by raywilliams** [comment]
Can no longer replicate bug. Please retest.

**Comment by Kibrahacha67** [comment]
11-26-19 LHammond Tested in UAT and Test.  Could not test in prod.
Tested in ie edge chrome and ff and could not duplicate.  moving to review.

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Chrome/Test
Ready for final review
