### ISSUE TITLE
Bug: Community managers can't change owners

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4085]
Environment: Production and Test

Issue: Community managers unable to change owners

Steps to reproduce:
1) log in as a community manager (not system administration)
2) to go admin --> community  select an internship and select change owner
3) Change the owner and save 
- owner doesn't save
works for system administrator

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
10-28-19 LHammond in testing.

Testing completed moving to review.

**Comment by kbwagner** [comment]
10/29/19 - KWagner tested in Chrome/Test
Ready for final review

Note: My student account showed up as an option in change owner.  I couldn't select it but ideally it wouldn't even show up.
