### ISSUE TITLE
Create ability for survey links to be updated by administrators 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4088]
Who: Sitewide administrators
What: Ability to update survey links for email 
Why: So emails don't have to be udpated every year

Acceptance Criteria:
- Provide the ability for sitewide administrators to update the survey links for both creator and participant surveys via the admin dashboard at any time.
-  - Update the creator and participant completor surveys to pull the link from the admin dashboard.

Links for FY2020
https://www.surveymonkey.com/results/SM-HDMN37TQ7/ (FY2020 Creator survey)
https://www.surveymonkey.com/results/SM-PXYV7DTQ7/ (FY2020 Participants survey)

Related ticket:
4088 - create links on admin dashboard
4113 - update participant creators email to pull survey link from admin dashboard
4114 - update creators email to pull survey link from admin dashboard

**Comment by bmcorum** [comment]
@kbwagner I think instead of having to update this link every fiscal year we should just add the ability for a sitewide administrator to add survey links via the admin console.

Opportunity participant survey link:
Opportunity creator survey link:
Any other survey links....?

**Comment by kbwagner** [comment]
@bmcorum I love that idea and think we have it on the backlog somewhere but wasn't sure what the quicker fix was.  But I like it - I'll write it up.

**Comment by bmcorum** [comment]
Ready for testing. Table of editable system variables is displayed in a table at the bottom of the sitewide administrator page below the announcement section.

**Comment by Kibrahacha67** [comment]
12-5-19 LHammond in testing
When each link was edited and saved it worked, but when edit button was selected the second time, the edited link was not opened in the modal, the original link without the edit was opened in the modal.  when saved then the original link was placed back in the field.  moving back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/6aa3fef8-170f-4895-99f2-6beea0308f0d)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-11-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested in Chrome/Test
Ready for final review
