### ISSUE TITLE
Update applicant status labels

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4093]
Who: State applicants
What: applicant status updates
Why: To be more clear and consistent with state language

Acceptance Criteria:
State has requested the following updates to application status:
Selected should be changed to Primary Select

Alternate should be changed to Alternate Select

The help center will be updated separately

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
10-08-19 on hold as there is an issue with cycles in open opps and atp to close cycles.  working with dev team to address the issue.

**Comment by Kibrahacha67** [comment]
11-12-19 LHammond in testing
Testing completed (see images below) moving to review
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/3822a6af-b8da-408d-bb46-ae42d74d619b)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/46e82900-8561-4c25-8594-9d7c89ce9812)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/cec1cfe8-bae1-4791-8ca2-d4d373544775)
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/e6bd9dfd-7656-43d6-b4be-7712b7e02c21)

**Comment by kbwagner** [comment]
11/12/19 - KWagner reviewed Larry's screen shots
@Kibrahacha67 thanks for the screen shots!!  

Ready for final review
