### ISSUE TITLE
Remove the option to create student internships as virtual

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4094]
Who: Student internship creators
What: remove the option to create a virtual internship
Why: because at this time all internships have a location

Acceptance Criteria:
- remove the option for a student internship to have a virtual location.  On the create template, hide the Virtual option

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-08-19 LHammond in testing
Testing completed, moving to review

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/19d59798-436f-48fa-8e57-3e85b07b28a4)

**Comment by kbwagner** [comment]
11/12/19 - KWagner tested in Chrome/test
Ready for final review
