### ISSUE TITLE
Update Manage Users .csv file for State

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4103]
who: State managers
What: Ability to view details on community members
Why: In order to adjust workload as needed

Acceptance Criteria:
For the DoS Unpaid community, Users --> Manage, adjust the .csv file as follows:
Remove Agency
Add Bureau and  Office/post
Update username title to be the actual title which I believe is login.gov email address
Add federal email address after username/federal email address

**Comment by kbwagner** [comment]
11/4/19 - Updated AC to include federal email address at request of state

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-08-19 LHammond in testing

**Comment by kbwagner** [comment]
11/12/19 - KWagner reviewed in TEst/Chrome
Ready for final review
