### ISSUE TITLE
Update student application submitted email to include info on updating

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4104]
Who: Applicants
What: submit email updates
Why: in order to provide more information on updating your application

Update the application submitted email to including information related to if you make an update please resubmit and also all changes must be submitted by 11:59 p.m. ET on the cycle close date.

**Email subject:** U.S. Department of State Student Internship Program (Unpaid) – Thank you for your application

**Email body:**
Hello [User name],

Thank you for submitting your application to the U.S. Department of State Student Internship Program (Unpaid) through Open Opportunities. You applied to the following internship opportunities:

[Insert internship opportunity 1] (Link to opportunity detail page)
[Insert internship opportunity 2] (Link to opportunity detail page)
[Insert internship opportunity 3] (Link to opportunity detail page)

View your application in your dashboard [insert link to student’s dashboard].

**What happens next?**
The U.S. Department of State Student Internship Program will:
1. **Review all applications**. They will begin to review applications after the application period closes on [insert application closing date].  
2. **Set up interviews**. They will contact you if you’re selected for an interview.  However, some offices don’t conduct interviews.
3. **Send offer emails**. They will send you an email with a conditional offer, if you’re selected for an internship.

**Can I update my application?**
Yes, you can update your application. You must make all updates before 11:59 p.m. ET on the closing date {insert closing date}. Don't forget to click submit.

**What happens if I’m not selected?**
After all internships are filled, you will receive an email if you’re not selected. 

(Learn more about the U.S. Department of State Student Internship Program (Unpaid) selection process)[https://careers.state.gov/intern/student-internships/selection-process/].

Thanks,
The Open Opportunities Team

**Comment by kbwagner** [comment]
@raywilliams updated the AC to reflect 11:59 p.m. EST (didn't have periods in the pm before)

**Comment by kbwagner** [comment]
@raywilliams since this is still in development can we change EST to ET on this email?

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-15-19 LHammond in testing

**Comment by kbwagner** [comment]
11/19/19 - KWagner tested in Test
Ready for final review
