### ISSUE TITLE
Change "Secondary application link" to be consistent with Agency Talent Portal

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#4107]
Agency Talent Portal  displays a message when the community manager clicks "Close cycle" indicating that a link must be added to the exclusive job announcement in the internship opportunity details.  

Update the secondary application link text to be consistent so that it is not confusing.   

Secondary application link text is changed to "Exclusive job announcement"

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-11-19 LHammond in testing
testing completed moving to review

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/902641f4-9f70-427b-8c5e-56850f7f5690)

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested in Chrome/Test
Ready for final review
