### ISSUE TITLE
Email to applicants of bureau/office/post or location change

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4112]
Who: Interns applicants
What: Email to notify of bureau/office/post change
Why: to allow them to update their application

Acceptance Criteria:
If an internship is open and has applicants in in progress or completed, and a bureau, office, or post changes or location change email applicants to notify them and allow them to update their application.

only email if the application cycle is still open for applicants.  

Content - see attached.
[Department-of-state-application-internship-location-changed-email_v4_20191112.docx](https://github.com/openopps/openopps-platform/files/3859009/Department-of-state-application-internship-location-changed-email_v4_20191112.docx)

https://github.com/USAJOBS/team-design/issues/47

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-11-19 LHammond In Testing

**Comment by kbwagner** [comment]
12/12/19 - KWagner 
testing completed
Ready for final review
