### ISSUE TITLE
Update creator completed survey link in email

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4114]
Who: Sitewide administrators
What: Update email sent to creators when opportunity is complete to provide updated survey link from admin dashboard
Why: In order to provide updated metrics each year

Acceptance Criteria:
Ticket 4088 will Provide the ability for sitewide administrators to update the survey links for both creator and participant surveys via the admin dashboard at any time.

With this ticket - Update the creator completor emails to pull the appropriate survey link from the admin dashboard as the email is being generated.

Links for FY2020
https://www.surveymonkey.com/results/SM-HDMN37TQ7/ (FY2020 Creator survey)
https://www.surveymonkey.com/results/SM-PXYV7DTQ7/ (FY2020 Participants survey)

Related ticket: 
4088 - create links on admin dashboard
4113 - update participant creators email to pull survey link from admin dashboard
4114 - update creators email to pull survey link from admin dashboard

**Comment by Kibrahacha67** [comment]
12-11-19 LHammond in testing
Testing completed moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/368231ae-474c-4bc6-8753-f07698cd10fb)

**Comment by kbwagner** [comment]
12/12/19 - KWagner reviewed artifact. Ready for final review
