### ISSUE TITLE
Bug: community allows for owner of internship to be changed to a student

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4115]
Environment: Test

Issue: In the student community, the change owner functionality allows you to select a student.  Does not seem to be an issue for sitewide
Students should not be allowed to be owners of internships

Steps to reproduce:
1) login as a community manager or sitewide
2) navigate to community --> DoS
3) Select a cycle and an internship and Change owner
4) search for Katrina Student Wagner - this is a student account and shows up and lets me select

**Comment by bmcorum** [comment]
This is ready for testing.

**Comment by Kibrahacha67** [comment]
10-30-19 LHammond in testing

**Comment by bmcorum** [comment]
I have removed all students users from the DoS community. Please retest.

**Comment by Kibrahacha67** [comment]
10-31-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
10/31/19 - KWagner tested in Test/Chrome
Ready for final review
