### ISSUE TITLE
Update What's next page to include content on updating application

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4116]
Who: Applicants
What: View information on what happens next
Why: In order to provide information about how to update and submit prior to closing

Acceptance Criteria:
Update the What's next page to include additional information related to updating the application, clicking submit, and all before 11:59 p.m. EST

New text: 

Can I update my application?

Yes, you can update your application by visiting your dashboard. You must make all updates before 11:59 p.m. EST on the closing date. Don't forget to click submit.

Design page with updated text and placement: https://opm.invisionapp.com/share/ZEPNZR09Q54#/344480824_State_-_Confirmation_-_Open_-Desktop-

Current Screen Shot: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/2ac98591-3ce9-4b9a-9fa6-3bb876889e58)

**Comment by kbwagner** [comment]
@tanichacko FYI - just updated the AC for this to be 11:59 p.m. EST  (original didn't have periods in the p.m.)

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-12-19 LHammond in testing
testing completed moving to review
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/6b726558-b5ed-41b6-8dbf-c724ca18adc9)

**Comment by kbwagner** [comment]
11/13/19 - KWagner tested in chrome/Test
Ready for final review
