### ISSUE TITLE
Add "We're pulling data" modal after Next Steps

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4119]
Who: Applicants
What: Provide modal to let them know we're pulling over USAJOBS data
Why: in order to let them know there may be a time lag and also make it clear we're pulling over the data

Acceptance:
When a user clicks "Continue" on next steps, display a modal that lets them know we are pulling data over from USAJOBS.

Title: Importing your information from USAJOBS
Message: "Please wait while we import your education, work experience, references, and languages from your USAJOBS profile."

No buttons and now "X" since you won't be able to stop this process

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas ready for testing.

**Comment by Kibrahacha67** [comment]
11-15-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
11-19-19 LHammond in testing.

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - There are a few questions that need to be answered in reference to the modal for this test.  I have talked to Brice and he is going to lead discussions as to how we move this ticket forward.  As such this will need to be put on hold until we have a clear path forward.

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
11-21-19 LHammond in testing

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Chrome/Test
- The screen still flashes so fast I can't fully read it but I get the idea so letting it go.
Ready for final review
