### ISSUE TITLE
Update delete bureau/office/post confirmation modal

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4120]
Who: Community managers
What: Deleting bureau or office/post - show numbers
Why: in order to let the user know how many will be removed

Acceptance Criteria: 
- Update the delete modal for removing a Bureau or Office/post to show metrics on how many internships are currently using this to deter deletion
- Update the modal to read, "[insert number] internships are currently using this bureau or office/post. Are you sure you want to remove [insert name here] from your community?"
- The number displayed should show all internships in any status that use that bureau or office/post in any cycle

Additional notes:
- For bureaus, thee last sentence will continue to say "If you delete the bureau, you will also delete all of its offices and posts." 
- For the office deletion modal. The last sentence will also say "This cannot be undone"?
- Because the modals are separate only show bureau for bureaus and only office/post for those

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-4-19 LHammond in testing
Testing completed moving to review

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/91b6dd0c-ac9f-46c1-9977-37ea473749b3)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/bec30cbb-3e94-4f96-bc40-5916c046fede)

**Comment by kbwagner** [comment]
12/4/19 - KWagner tested in Chrome/Test 
Ready for final review
