### ISSUE TITLE
Update modal - update the text to provide more information

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4122]
Who: Applicants
What: Update the update application modal
Why: in order to provide additional information

Acceptance Criteria: 

Update the update application modal to provide more information related to closing time EST and if you update make sure you submit

New content:
4. Review your application and click **Submit application**. You must submit changes before [insert closing date] at 11:59 p.m. EST.

Current Screen Shot:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/19e48d66-64db-4627-ad4e-6aea58e5f11a)

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-12-19 LHammond in testing

**Comment by kbwagner** [comment]
11/12/19 - Kwagner tested in Chrome/Test
Noticing inconsistently on how we do pm, p.m., PM - checking with  Debbie and can create new tickets to adjust.

**Comment by kbwagner** [comment]
@tanichacko just discussed this with @jhanson12 can you please update pm to be p.m. to meet design system standards?  Should say 11:59 p.m. EST (AC has been updated) Sorry I missed this!

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-12-19 LHammond in testing
Testing completed, moving to review

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/75670f98-b291-4a02-aef7-32d280fa4795)

**Comment by kbwagner** [comment]
11/13/19 - KWagner tested in chrome/test
Ready for final review
