### ISSUE TITLE
Bring work experience sort order over from USAJOBS

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4123]
Who: Student internship applicants 
What: default sort order for work experience
Why: in order to bring data over from USAJOBS in the same order

Acceptance Criteria:
USAJOBS now allows for the user to sort their work experience on One Profile.
- Pull the sort order from USAJOBS
- The work experience should default display in the same order as it comes over from USAJOBS 

Screen shot of USAJOBS one profile:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/200f4745-edaa-4c1b-8801-a1ba1e738b88)

Related Tickets:
10/29/19 - TFS 39119 is in production which adds the sort on USAJOBS but it's not available yet in the API. 39267 should add it to the API in the next release

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum - Question here, is this about the ability for users to move their work experience in the order they want?  As in JOBS the particular order is not set they can put it in any order they want and move it, does not have to be in date or even specific employer...

**Comment by kbwagner** [comment]
@Kibrahacha67 yes it's mirroring what they do in jobs.  So they can move a work experience to the top if it's more pertinent to the job they are applying for.

**Comment by Kibrahacha67** [comment]
@kbwagner - Thanks that makes the TC clear...

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-25-19 LHammond in testing

The top and bottom of the sort order should only have one arrow, either down for the top or up for the bottom as in jobs (see image in the AC).  Also the arrows do not allow the user to actually sort at this time.  moving back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/15512d61-8adf-4d76-9a97-52850e88a7da)

**Comment by Kibrahacha67** [comment]
11-25-19 LHammond in testing
Testing completed, moving to review.

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Chrome/Test
Ready for final review
