### ISSUE TITLE
Pull/Display the education sort order from USAJOBS One Profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4124]
Who: Applicants
What: Pull default education sorting from USAJOBS
Why: In order to truly have a one profile

Acceptance Criteria:
- Pull the sorted education data from USAJOBS One profile  including the sort preference
- Displayed the education data sorted in the USAJOBS sort order as the default on the Open Opps application

Screen shot of USAJOBS One profile education sorting: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/c7330240-1bec-4887-8920-c9cd8359d186)

Related Tickets:
10/29/19 - TFS 39119 is in production which adds the sort on USAJOBS but it's not available yet in the API. 39267 should add it to the API in the next release

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-3-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/4/19 - Kwagner tested in Chrome/Test
Ready for final review
