### ISSUE TITLE
Allow for sorting of education data in Open Opps application

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4125]
Who: Applicants
What: ability to sort education data
Why: in order to highlight specific education

Acceptance Criteria:
- Education data will be pulled from USAJOBS and displayed in the sort order that comes over.  Allow for applicants to sort that data in Open Opps.
- Add arrow sorting per design system.

Sample of USAJOBS education sort arrows:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/809494bb-ca89-4716-ac6a-0f951059edea)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-04-19 LHammond  in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
12/4/19 - KWagner tested in Chrome/Test
Ready for final review
