### ISSUE TITLE
Display education in sorted order on application review page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4126]
Who: Student applicants
What: Display education data by sort preference on the application review
Why: to allow applicants to review the application correctly

Acceptance Criteria:
- The education data will now have a sort order (either default from USAJOBS or resorted in open opps).  Display the education data in the correct sort order on the application review page

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-4-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/4/19 - KWagner tested in Chrome/Test
Ready for final review
