### ISSUE TITLE
Cancel email: When cycle is closed and canceled internship has applicants

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4127]
Who: Student applicants
What: Email to notify of cancellation after the cycle has closed
Why: in order to provide status

Acceptance Criteria:
- If an internship is canceled while in the selection process in ATP (apply cycle has closed), the following email should be sent to applicants with completed applications for that internship:

Here's the second email for when DOS cancels an internship during the selection process. I'm not sure about the (if you chose that option during the application process) - let me know if that's clear or if we need to say anything else.

Email Subject - Department of State Student Internship Program (Unpaid) - One of your internship selections has been canceled.

Hello, [Username}
We want to let you know that the Department of State has canceled one of your internship opportunity selections.

If the Department of State does not select for your other internship selection(s), they will consider you for any open internships that are available (if you chose that option during the application process).

You can check the status of your application on your [Open Opportunities dashboard](link to Open Opps dashboard). If you need to make an update, don't forget to submit your application again.

Thank you,

The Open Opportunities Team 
U.S. Office of Personnel Management 
1900 E Street NW. 
Washington, DC 20415

Related tickets: 
Related tickets: 
4007 - Internship Cancel process
4064 - Email if open and has applicants to apply again
4127- email if internship canceled, has applicants, apply is closed
4128 - Email - canceled with selectee after review cycle closed
4129 - Tracking data on cancel

**Comment by kbwagner** [comment]
This ticket is on hold.  this process will happen in ATP and we will not likely send out emails.  But will try the cancel process in ATP for a cycle and see if there is a need.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41530&_a=edit
