### ISSUE TITLE
Cancel email: Canceled after review cycle closed

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4128]
Who: Selectee or alternate on a canceled email
What: send an email to notify of cancelation
Why: to provide status update

Acceptance Criteria: 
If an internship is canceled, has a selectee or alternate, and was canceled after the review process in ATP was closed, the following email should be sent to selectee and/or alternate.

Email Subject - Department of State Student Internship Program (Unpaid) - Your internship has been canceled.

Hello [Username],

We want to let you know that the Department of State has canceled your internship opportunity.
If you have questions, please contact studentinternship@state.gov.

Thank you,

The Open Opportunities Team 
U.S. Office of Personnel Management 
1900 E Street NW. 
Washington, DC 20415

the studentinternship@state.gov should pop up an email.

Related tickets: 
Related tickets: 
4007 - Internship Cancel process
4064 - Email if open and has applicants to apply again
4127- email if internship canceled, has applicants, apply is closed
4128 - Email - canceled with selectee after review cycle closed
4129 - Tracking data on cancel

**Comment by kbwagner** [comment]
This ticket is on hold.  this process will happen in ATP and we will not likely send out emails.  But will try the cancel process in ATP for a cycle and see if there is a need.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41531&_a=edit
