### ISSUE TITLE
Cancel: Track metrics

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4129]
Who: Admins
What: ability to retrieve data on cancelations
Why: in order to prove who did what

Acceptance Criteria:
If an internship is canceled, the following metrics should be tracked for ad hoc reporting needs: 
Track metrics for who canceled the internship, the date time stamp of the cancel, and the task number, title and creator of the canceled internship

Related tickets: 
4007 - Internship Cancel process
4064 - Email if open and has applicants to apply again
4127- email if internship canceled, has applicants, apply is closed
4128 - Email - canceled with selectee after review cycle closed
4129 - Tracking data on cancel

**Comment by tanichacko** [comment]
[https://app.zenhub.com/files/11452644/b83ccbe1-c723-4596-97c9-d2e5807fcd90/download](https://app.zenhub.com/files/11452644/b83ccbe1-c723-4596-97c9-d2e5807fcd90/download)

Attaching data in excel

**Comment by bmcorum** [comment]
Ready for testing

**Comment by kbwagner** [comment]
12/9/19 - KWagner reviewed artifact.  Ready for final review
