### ISSUE TITLE
View application status - filter applicants

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4130]
Who: admins
What: ability to filter on applicant lists 
Why: in order to make searching for applicants easier

Acceptance Criteria: 
On the table where you can view applicants for a cycle, add a filter that allows to search by name, email, or application status.
- Default test for the filter box will be, "Filter by Name, email, or status"
- When information is entered in the filter and search is selected, the applicant list will be filtered by the data input.

Related tickets: 
4049 - create applicant list
4130 - Filter on applicant list
4133 - Sort by on applicant list
4134 - .csv of applicants

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-25-19 LHammond in testing 
testing completed moving to review.

**Comment by kbwagner** [comment]
12/3/19 - Kwagner tested in Chrome/test
ready for final review
