### ISSUE TITLE
Add location to the State internship .csv file

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4131]
Who: State  Community admins
What: add location to the .csv file 
Why: to help them build their exclusive posting

Acceptance Criteria:
- Add location to the internship .csv file for the State community
- The field can display after the bureau and office/post fields

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-06-19 LHammond in testing

**Comment by kbwagner** [comment]
11/7/19 - KWagner tested in Chrome/Test
Ready for final review
