### ISSUE TITLE
Add ability to edit DoS internships

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#4132]
Who: State Community admins
What: ability to edit internships without reverting to submitted state
Why: need ability to update incorrect information without needing to re-approve

Acceptance Criteria:

Allow for editing of internships that are open without them going back to submitted state

**Comment by bmcorum** [comment]
Ready for testing in UAT.

**Comment by kbwagner** [comment]
10/31/19 - KWagner tested 
Ready for final review
