### ISSUE TITLE
View applicant - sort by

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4133]
Who: Community and sitewide admins
What: ability to sort on applicant lists
Why: in order to 

Acceptance criteria:
- Add a sort by to the applicant listing
- Default sort will be by last name
- Sort by options will be for all fields on the table: Name, email, Status, and Last update

Related tickets: 
4049 - create applicant list
4130 - Filter on applicant list
4133 - Sort by on applicant list
4134 - .csv of applicants

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-25-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Chrome/Test
Ready for final review
