### ISSUE TITLE
Applicant list: csv download

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4134]
Who: Community and sitewide admin
What: Export list of applicants for a cycle
Why: in order to provide help and support

Acceptance Criteria:
- In the new applicant view section, add a "Download list (.csv)" link
- The export will include the following fields:
Name, email, application status, internship name, internship creator, internship bureau, internship office/post, internship location, and last updated in ET if possible
- Each submitted intern will end up having 3 rows of data and the rows should be sorted together
- All internship applications that have started will display in this .csv (in progress, not completed, submitted, completed, etc.)
- the export will only include applicants for the selected cycle

Related tickets: 
4049 - create applicant list
4130 - Filter on applicant list
4133 - Sort by on applicant list
4134 - .csv of applicants

**Comment by bmcorum** [comment]
Ready for testing.

**Comment by Kibrahacha67** [comment]
11-21-19 LHammond in testing
No link shows in the Applicnts page (image below) sending back to development
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2c012e4a-6d14-42f2-894d-e806531dd069)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-25-19 LHammond in testing

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Chrome/Test
Ready for final review
