### ISSUE TITLE
Admin - Agency Search display "Previous" and "Next" When There are No Results

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#4141]
When you perform a search from Admin>Agency> Department of State - Agency Wide and search for "Test", there are no results returned but the "Previous" and "Next" options are displayed on the page. If there are no results then these options are not needed.
Steps to repro:
1.  Navigate to Administration
2.  Select the "Agency" option
3.  Enter "Test" or anything that doesn't return results: 

Note: This is production:

Results:  There were no option found but the "Previous" and "Next" options are displayed on the page.  See screenshot:               ![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/d4ab5772-569b-483a-b59c-d5de429237c8)

**Comment by raywilliams** [comment]
Can no longer replicate bug. Please retest.

**Comment by Kibrahacha67** [comment]
11-26-19 LHammond - Tested in chrome, ie, edge and ff also in Test, UAT and Prod and could not duplicate.  Moving to review.

**Comment by kbwagner** [comment]
I am able to replicate this somewhat  - If I test in agencywide or community and follow the steps I get a "Next" option although no previous.  
![image](https://user-images.githubusercontent.com/18709918/70050743-ad506f80-159d-11ea-909d-639371ad136d.png)

**Comment by tanichacko** [comment]
@Kibrahacha67 ready for testing

**Comment by Kibrahacha67** [comment]
12-10-19 LHammond in testing
Testing completed moving to review.

**Comment by Kibrahacha67** [comment]
12-10-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested in Chrome/Test
Ready for final review
