### ISSUE TITLE
Bug: DoS recent activity not showing in order

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4150]
Environment: Production 

Steps to reproduce: 
1) Admin --> Community --> DoS
2) View recent activity 
- Displays in random order
- Resolution: Please make this appear most current to least current

Screen shot of issue: 
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/712ea26e-8039-4b7a-b5d7-c64c012accd2)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-25-19 LHammond in testing

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Chrome/Test
Ready for final review
