### ISSUE TITLE
Add number of positions to the State .csv file

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4158]
Who: State users
What: Add number of positions to the .csv
Why: in order to provide data State needs

Acceptance Criteria:
Add number of positions to the State internship .csv download (Admin --> Community --> State--> Internships --> Manage --> download list (.csv)
- This field can be added after the description field and will display the data from the How many interns to you need? field

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-19-19 LHammond in testing
Testing completed moving to reveiw

**Comment by kbwagner** [comment]
11/19/19 - KWagner tested in Chrome/Test
Ready for final review
