### ISSUE TITLE
As as user, I would like to explore the network of people in the community

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#416]
Ideas for exploring relationships through 
- shared skills
- opportunities that I have worked on
- working groups I'm part of
- shared topic interest
- cross agency relationshios

We would most likely want to show this on the user's profile page -- ideally with a way to prompt/inspire them to add skills.  Maybe also show on a task page (or task creation dialog?) to show who might be good for this task...

**Comment by ultrasaurus** [comment]
Another idea of exploring your network of people:
![image](https://cloud.githubusercontent.com/assets/41906/6135469/b488cfac-b11d-11e4-8307-25fd2772164d.png)

**Comment by kbwagner** [comment]
5/18/18 - Kwagner - @LisaLNelson can this one be closed since we now allow to search for people by skill, agency, career field?

**Comment by LisaLNelson** [comment]
This should be kept open and will relate to development work we will be doing on the profiles. @minchung12 should be aware.

**Comment by kbwagner** [comment]
Closing - this will be done with People search update
