### ISSUE TITLE
Change "Assigned' to "In progress" on opportunity .csv

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4165]
Who: Admin
What: Opportunity .csv shows misleading label
Why: to avoid confusion

Acceptance criteria:
- opportunity .csv for sitewide and agency have Assigned date.  Change heading to be "In progress date". The actual date is apparently correct to show the date the opportunity was moved to in progress but the heading wasn't changed.

This change should be made to:
- sitewide
- agency
- community not State
- community State

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-19-19 LHammond in testing 
Testing completed moving to review.

**Comment by kbwagner** [comment]
11/19/19 - KWagner tested in Chrome/Test
Ready for final review
