### ISSUE TITLE
Add "I do not have work experience" option on application

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4169]
Who: State applicants
What: Ability to select that they do not have work experience
Why: To allow state to understand if someone didn't fill out info on purpose

Issue:
State has noted that many students did not enter work experience and think it's because they missed the section.  They would like to make work experience required.

Acceptance criteria:
- Add a checkbox to allow the applicant to indicate "I do not wish to provide or do not have any work experience"
- The applicant must either have selected that checkbox or entered at least one row of work experience to continue.  (required) 
- Error messaging will indicate that work experience is required
- remove the (optional) beside work experience
- Update the intro sentence to read, "Please list your federal, military, professional, and volunteer experience here."

Placement:
- Add the checkbox under the "Add work experience" link
- If the box is selected, gray out the "Add work experience" link
- If at least one work experience row is added, do not display the checkbox

Work experience not entered yet (current screen shot):
![image](https://user-images.githubusercontent.com/18709918/68772050-21c76c80-05f7-11ea-86cf-7582e86a724f.png)

Work experience entered (current screen shot):
![image](https://user-images.githubusercontent.com/18709918/68772085-3146b580-05f7-11ea-8153-81bba8d8981d.png)

USAJOBS Resume Builder Checkbox:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/5f98bbab-2cf9-4d2d-9d44-eeb5874e98c6)

**Comment by jhanson12** [comment]
@kbwagner and @bmcorum  we can not grey out /disable a link.  I am changing the Add work experience to a button per the design system.

**Comment by kbwagner** [comment]
@jhanson12 so then can you  disable a button i assume?  That's all fine with me.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
11-28-19 LHammond in testing

**Comment by kbwagner** [comment]
12/3/19 - KWagner tested in Test/Chrome
Ready for final review
