### ISSUE TITLE
Update state internship metrics to include drafts

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4170]
Who: State administrators
What: View metrics for drafts
Why: For the metrics to make sense

Acceptance Criteria:
Admin --> Community --> State --> Internships
- Add Drafts under Total created 

Source: Request from state to make the numbers make sense

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/2d85dade
-aefc-4dfe-8139-61a3fb167122)

**Comment by Kibrahacha67** [comment]
11-15-19 LHammond in testing
Testing completed, moving to review.

**Comment by kbwagner** [comment]
11/19/19 - KWagner tested in Chrome/Test
Ready for final review
