### ISSUE TITLE
Bug: Metrics incorrect for State incomplete applications on Interactions

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4171]
Environment: Production

Steps to reproduce:
1) Admin --> Community --> State
- The interactions section shows incorrect numbers for incomplete applications
.From Tani: Currently the query looking for only current steps for application(Incomplete application)  we have to check with submitted At date is null  as well for Incomplete applications steps . 

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/6b4f2f57-16d3-4904-803b-e52a935635f1)

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-14-19 LHammond in testing
From what I can tell the report is working as the images below suggest.  Although the two numbers Under Student Internships and Internships for Successfully completed and Completed respectively I don't understand. I think they both represent completed internships which cause a bit of confusion being in two places.  Moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/64c4df84-bd7d-43df-94ce-0c2e8c053623)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2f97a528-2243-42d9-9ea1-db856f1a82de)

**Comment by kbwagner** [comment]
@Kibrahacha67 the completed is confusing.  The one on the left is for the entire internship being marked as completed.  The one on the right is for when the student has completed an internship but the internship itself may still be open.  I get it's still confusing though.

**Comment by kbwagner** [comment]
11/14/19 - KWagner tested in Chrome/Test
Ready for final review
