### ISSUE TITLE
State Submitted email - update link

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4172]
Environment: Production

Issue: Submitted email contains invalid link

Steps to Reproduce:
1) Apply to a state internship
2) Receive confirmation email of submitted application
- link to  "View your application in your dashboard" goes to https://openopps.usajobs.gov/home/  which takes you to a page not found.

Correct the link to take the user t:
1) if signed out - the open opps home page where they sign in and then go to the landing page instead of search
2) if signed in  - the landing page

Full email: 
Hello Katrina Student Wagner,
Thank you for submitting your application to the U.S. Department of State Student Internship Program (Unpaid) through Open Opportunities. You applied to the following internship opportunities:
•	COPY numquam omnis libero
•	COPY numquam omnis libero
•	COPY Mazime iusto deleniti II
View your application in your dashboard.
What happens next?
The U.S. Department of State Student Internship Program will:
1.	Review all applications.
They will begin to review applications after the application period closes on November 14, 2019.
2.	Set up interviews.
They will contact you if you're selected for an interview. However, some offices don't conduct interviews.
3.	Send offer emails.
They will send you an email with a conditional offer, if you're selected for an internship.
What happens if I'm not selected?
After all internships are filled, you will receive an email if you're not selected.
Learn more about the U.S. Department of State Student Internship Program (Unpaid) selection process.
Thanks,
The Open Opportunities Test Team

**Comment by jhanson12** [comment]
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment]
11-14-19 LHammond in testing
Testing completed in chrome, safari, edge and ie.  moving to review.

**Comment by kbwagner** [comment]
11/19/19 - KWagner tested in Chrome/Test 
Ready for final review
