### ISSUE TITLE
Change EST to ET on system pages

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4175]
Who: All users
What: Change EST to ET
Why: To be consistent and avoid confusion

Acceptance Criteria:
Change instances of EST to be ET
Reason: EST is only half of the year as well as EDT so ET should be used

Changes should be made:
- State: Next steps page

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/18ab2b05-21e0-4e62-acb4-52a531516ad8)

- State: What's next page
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/6b726558-b5ed-41b6-8dbf-c724ca18adc9)

- State: Update application page
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/75670f98-b291-4a02-aef7-32d280fa4795)

- State: Search page in the info box that tells applicants when they can apply
![image](https://user-images.githubusercontent.com/18709918/68869972-109a6080-06c8-11ea-9669-d416deafeccf.png)

**Comment by Kibrahacha67** [comment]
11-15-19 LHammond in testing



![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/bd0bcb44-80a8-4adc-a7f3-ad75df815d8b)

**Comment by kbwagner** [comment]
11/19/19 - KWagner tested in Chrome/test

ready for final review
