### ISSUE TITLE
Student interns: ability to see list of internships they applied to and a read only version of internship for interview

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4176]
Who: Student interns
What: Ability to view internships applied 
Why: In order to prepare for interview

Acceptance Criteria:

On the student internship dashboard, students would like to be able to see the list of the 3 internships they applied to and click on each on to have a read only version of the internship they can print to prepare for an interview
- Keep the cycle link active even when the internship apply cycle has closed
-  Display the current update/withdraw page with the buttons disabled.
- Allow the student to click on the internship to view the information as read only
<img width="376" alt="Dept_of_State_-_Open_Opps_-_Search_Apply_Profile" src="https://user-images.githubusercontent.com/18709918/70729268-dfb24900-1cd0-11ea-8fd0-1fe79f9158f9.png">

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-18-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
12/23/19 - KWagner tested in Chrome/Test
Ready for final review
