### ISSUE TITLE
Updates to State selectee email

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4192]
Who: State interns
What: Selectee email updates
Why: in order to avoid confusion

Acceptance Criteria: 
The following updates should be made to the selectee email for state:

•	If security clearance is "None", display "None (Public Trust Certificate)" on the email

-  the signature should be together and not separated the way that it currently shows below.
![image](https://user-images.githubusercontent.com/18709918/69566527-4ae7e580-0f85-11ea-9291-9ffec5a89358.png)

**Comment by bmcorum** [comment]
@kbwagner fonts are already set to a consistent font. If they are seeing something different their email client may have a setting that is interfering with the rendering of the email. We are using the font families from the US Design System and the USAJOBS Design System, neither of which uses Times New Roman.

![image](https://user-images.githubusercontent.com/1165615/69575931-49281d00-0f99-11ea-9658-fe28624b54a0.png)

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-3-19 LHammond in testing
couple of problems with the email  The signiture block alignment is totaly on the left boarder.  Second, the second #1 is missing the line completly and the alignment of 1 and two is off...screen shots attached.  Will forward email if needed.  sending back to development

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/70245381-f93d1900-1743-11ea-9ba7-31a1a5909d0f.png)

![image](https://user-images.githubusercontent.com/1165615/70245427-0528db00-1744-11ea-8831-21f835a50a4c.png)

**Comment by bmcorum** [comment]
Ready for testing. See above artifacts

**Comment by Kibrahacha67** [comment]
12-5-19 LHammond in testing
Testing competed via artifacts.  moving to review.

**Comment by kbwagner** [comment]
12/5/19 - KWagner reviewed artifact above
Ready for final review
