### ISSUE TITLE
Updates to State Alternate email

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4193]
Who: State interns
What: Alternate email updates
Why: in order to avoid confusion

Acceptance Criteria:
The following updates should be made to the alternate email for state:

• If security clearance is "None", display "None (Public Trust Certificate)" on the email
-  the signature should be together and not separated the way that it currently shows below.
![image](https://user-images.githubusercontent.com/18709918/69566527-4ae7e580-0f85-11ea-9291-9ffec5a89358.png)

**Comment by bmcorum** [comment]
@kbwagner fonts are already set to a consistent font. If they are seeing something different their email client may have a setting that is interfering with the rendering of the email.

![image](https://user-images.githubusercontent.com/1165615/69575931-49281d00-0f99-11ea-9658-fe28624b54a0.png)

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-3-19 LHammond in testing
The gap between the signature block and the dos line is still very large as well as the block is left justified into the boarder.  Moving back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/f281730f-7e55-4d99-99b6-579955564dac)

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/70245195-b3805080-1743-11ea-8557-c566ea55fcbd.png)

![image](https://user-images.githubusercontent.com/1165615/70245246-c3983000-1743-11ea-91ef-b2e025cb4fd0.png)

**Comment by bmcorum** [comment]
Ready for testing. See above artifacts

**Comment by Kibrahacha67** [comment]
12-5-19 LHammond in testing
Testing competed via artifacts.  moving to review.

**Comment by kbwagner** [comment]
12/5/19 - KWagner reviewed artifact.
Ready for final review
