### ISSUE TITLE
BUG: Clicking the next steps button, on an opportunity,  gets no results.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4194]

**Comment by bmcorum** [comment]
Ready for testing. **NOTE:** Please test in both the TEST and UAT environments.

**Comment by Kibrahacha67** [comment]
11-21-19 LHammond in testing 
testing completed moving to review(tested in both tst and uat)

**Comment by kbwagner** [comment]
11/21/19 - Kwagner in test
