### ISSUE TITLE
Bug: Do not display applicants that didn't apply to internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4195]
Environment: Production

Issue:
When the review cycle is open for ATP, students that didn't apply to an internship display when a community manager selects "view applicants"

Example: 
Internship title: American spaces Indonesia intern says zero applicants.  Click on the view applicants link and two display,  Neither applied to the internship so are displaying from ATP.

![image (32).png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/fddffc95-16f4-45bc-b444-106bf03ea615)

![image (33).png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/83ab2217-f650-43f1-97b9-60b13cf239e6)

Solution:
- Only display applicants that applied to the intership until the review process closes.
- When the review process closes, the title changes to "Selected interns" and displays the ATP selections

**Comment by bmcorum** [comment]
### ATP Review Board

Piper Legros displays on my board by the sorting algorithm, but did not apply to the internship.

![image](https://user-images.githubusercontent.com/1165615/69376407-3ac7c180-0c78-11ea-9205-5998500545c4.png)


### Applicant section in Open Opportunities

Piper Legros did not apply to my internship and therefore does not display as an applicant

![image](https://user-images.githubusercontent.com/1165615/69376666-add13800-0c78-11ea-8c90-b8dab3376c3b.png)


### Piper Legros's application

![image](https://user-images.githubusercontent.com/1165615/69377033-68f9d100-0c79-11ea-9fce-7f833e222c23.png)

**Comment by bmcorum** [comment]
See artifacts posted above.

**Comment by Kibrahacha67** [comment]
11-25-19 Moving to review.

**Comment by kbwagner** [comment]
11/25/19 - KWagner reviewed artifacts - moving to test
