### ISSUE TITLE
State Admin: Default cycle to current cycle

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4199]
Who: Department of State admin
What: default cycle to the current cycle
Why: So metrics viewed are current

Admin --> Community --> State
![image](https://user-images.githubusercontent.com/18709918/69576161-c2277480-0f99-11ea-8f72-4503bfd131a1.png)

For the cycle dropdown, default the cycle to the current cycle based on internship posting dates.

For example, the summer 2020 cycle is currently in review.  But the Fall 2020 cycle is the one that displays first even though it has not started accepting new internship postings.  
- Summer 2020 should display now because it has the most recent internship posting phase.
- Once Fall 2020 has started accepting new internships posting, this should become the default.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-5-19 LHammond in testing
Testing completed moving to review

**Comment by jhanson12** [comment]
@Kibrahacha67 we found an issue with this...it was not changing when selecting a different cycle.  Fixed now.

**Comment by Kibrahacha67** [comment]
12-6-19 lhammond in testing.

Testing completed moving to review.

**Comment by kbwagner** [comment]
12/9/19 - KWagner tested in Chrome/Test

@jhanson12 in Test it seems like Vero dolorum voluptatem  cycle with posting dates of | 12/05/19 - 12/17/19 should be the one defaulting.  But the default is displaying as Facilis cumque and it's posting dates are in the past.
- moving back to development but let me know if I'm missing something.

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested in Chrome/Test
Ready for final review
