### ISSUE TITLE
Require state creators to have bureau and office/post on profile before they can create.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4215]
Who: State creators
What: Require bureau and office/post to be on their profile before they can create
Why: to assist with BICs approving

Acceptance Criteria:
- If Create opportunity/internship is selected by a State community member and they do not yet have a bureau and office/post on their Open Opportunities profile, stop them from creating.  
Display the message that is displayed at login but in red:
![image](https://user-images.githubusercontent.com/18709918/70932417-b7e01f80-2007-11ea-8070-da7a62930c9c.png)

- This will prevent approval emails from going to all community managers as they will be able to be matched to the correct bureau approver

**Comment by tanichacko** [comment]
@kbwagner and @dalenard21 Do we have content ready for this ticket #4215?

**Comment by kbwagner** [comment]
@tanichacko I have some draft text but I'll check in with debbie today to see if she can take a look.  I'll let you know ASAP.

**Comment by tanichacko** [comment]
@kbwagner ok. Thanks

**Comment by kbwagner** [comment]
@tanichacko @dalenard21 and I just chatted and we'll use the same text they get at login but make the message red.  I included a screen shot above.

**Comment by tanichacko** [comment]
@kbwagner Thank you

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-19-19 LHammond in testing
Testing completed, moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/18c0100d-d04a-48e7-95bc-15668eaf6dc6)

**Comment by kbwagner** [comment]
@tanichacko the message should also have a "Go to profile" button at the bottom.  Is this possible?  

![image](https://user-images.githubusercontent.com/18709918/71366483-14938b00-2570-11ea-9771-345de5d122c1.png)

**Comment by tanichacko** [comment]
@kbwagner Yes I added . It will be in test once next deploy to test happens.

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-26-19 Testing completed moving to review

**Comment by kbwagner** [comment]
12/30/19 - 

Color is correct and profile button is there - but to meet design system standards profile button should in in bottom right corner like image in AC.  

Current message: 
![image](https://user-images.githubusercontent.com/18709918/71585297-0bf90280-2ae4-11ea-809d-ad5fa1de1599.png)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-31-19 LHammond in testing
Testing completed moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/24a7ace6-9d7e-46a9-a0cd-a894529bdb05)

**Comment by kbwagner** [comment]
12/31/19 - Ready for final review.
