### ISSUE TITLE
Bug: Drawers for experience and education aren't expanding on first click

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4225]
Environment: Test

Steps to reproduce:
1) Apply for an internship
2) on the work experience page, click on the plus sign for a work experience (or education) to expand
- on the first try the row expands and quickly closes 
- must click again for it to expand and stay open

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-11-19 LHammond in testing
Testing completed. moving to review.

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested in Chrome/Test
Ready for final review
