### ISSUE TITLE
Bug: Whoops page flashing

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4226]
Environment: Test

Issue: Whoops page is flashing up in two places during the application process

Steps to reproduce:
1) apply for an internship
2) click next steps - pulling data modal displays and then "Whoops page" for a few seconds
3) Select 3 internships and click next...whoops page displays again before taking user to education

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.  @raywilliams made an adjustment to the timeout and neither one of us sees the whoops page anymore.

**Comment by Kibrahacha67** [comment]
12-23-19 LHammond in testing

**Comment by kbwagner** [comment]
12/23/19 - KWagner tested in Chrome/Test
Ready for final review
