### ISSUE TITLE
Remove text from add/edit/update bureau/office/post confirmations so they make sense.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4227]
Who: Community managers
What: confirmation text updates
Why: so they make sense

Acceptance Criteria:
Remove "to your community" from the add/edit/delete bureau/office/post confirmations so they can make sense across the board.

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/5c904fa3-807c-4080-b80a-04a162b06673)

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/404aae65-efcd-46ff-b9c4-4745ca4d03e5)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-18-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
12/19/19 - KWagner tested in Chrome/Test
Ready for final review
