### ISSUE TITLE
Bug: Duplicate does not allow you to change cycle

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4229]
Environment: Test

Issue: Need to create an internship for the current cycle and duplicate my internship from the previous cycle.....when I duplicate it assigns it to the same cycle which is already passed and won't let me change it.

Resolution: Duplicate should allow for the changing of the cycle.  Can default to the current create cycle.

**Comment by bmcorum** [comment]
Ready for testing in UAT

**Comment by Kibrahacha67** [comment]
12-6-19 LHammond in testing

**Comment by kbwagner** [comment]
12/9/19 - KWagner tested in UAT
Ready for final review
