### ISSUE TITLE
State selectee email content update

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4231]
Who: Student internships
What: Update email to include internship name and additional wording
Why: to help the intern understand what they were selected for.

Acceptance criteria:
For the selectee email:
Acceptance criteria:
For the alternate email:
1) Add the word cycle after cycle name and add internship name - update the first paragraph to read:
Congratulations! We are pleased to conditionally offer you an internship with the U.S. Department of State Student Internship Program (Unpaid) for the [insert cycle name] cycle. You’ve been conditionally selected for [insert internship name]. 

2) If security clearance is none, the value that is displayed should be, "None - Low Risk Public Trust Certificate"

3) Add new line to include exclusive posting end date
Update Next Steps 3 to read, "3. Do not share this link with anyone else—it is only for students who have been selected for this internship. Please submit your responses to the questionnaire by [enter date].
[insert special link to internship posting ]
- Ticket 4255 will add the exclusive posting end date which is what should display here.

Full content of selectee email:
[Department-of-state-unpaid-student-internship-program-selected-for-internship-offer-email_v10_20191209.docx](https://github.com/openopps/openopps-platform/files/3952986/Department-of-state-unpaid-student-internship-program-selected-for-internship-offer-email_v10_20191209.docx)

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/71179615-8b621880-223e-11ea-899b-9370025b7be7.png)
![image](https://user-images.githubusercontent.com/1165615/71179702-b187b880-223e-11ea-833d-8cd024a97c75.png)

**Comment by Kibrahacha67** [comment]
12-23-19 Reviewed artifact, moving to review.

**Comment by kbwagner** [comment]
12/23/19 - KWagner reviewed artifact.  Ready for final review
