### ISSUE TITLE
Change Secondary application link on cycle table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4247]
Who: Cycle users 
What: Change field label for secondary application link
Why: in order to be consistent across products

Acceptance criteria:
On the add/edit cycle table, modify the Secondary application link label to instead read "Exclusive job announcement link".  This will better line up with the verbiage used on the ATP side.

**Comment by kbwagner** [comment]
This appears to be duplicate of 4107

**Comment by kbwagner** [comment]
@bmcorum let's just go ahead and do this and add the word "link"

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-18-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
12/19/19 -KWagner tested in Chrome/Test
Ready for final review
