### ISSUE TITLE
Limit cancel process to community managers

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4249]
Who: Community Managers (internship program office)
What: limit ability to cancel internship
Why: in order to prevent cancellations from accidentally happening

Acceptance Criteria:
- Limit the internship cancellation process to community managers (i.e. Khadijah and her office) or sitewide administrators
- creators will not have access to cancel their own internship unless they are a community manager

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-12-19 LHammond in testing
Testing completed moving to review.  

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/1233c715-b871-4fa4-ba22-91ab4e6472e1)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ada0dfd5-7039-4c27-b056-a0b92205f885)

**Comment by kbwagner** [comment]
12/12/19 - Reviewed artifact (thanks Larry!)
Moving to final review
