### ISSUE TITLE
Add security clearance to internship view

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4250]
Who: Internship applicants
What: Ability to see what type of security clearance they will be getting
Why: in order to help the process

Acceptance Criteria:
- add security clearance to the applicant view of the internship
- Field label should be "Required security level"
- Field should display last in the blue box on the right of the page.  (if this is too much for this box please advise)
-Display the value from the security clearance field on the created internship.  If value is none display ,"None (Low Risk Public Trust Certificate) "

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-18-19 LHammond in testing
Testing completed...moving to review.

**Comment by kbwagner** [comment]
12/19/19 - KWagner tested Chrome/Test 
Ready for final review
