### ISSUE TITLE
Bug: Internship .csv includes selectees prior to boards closing

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4251]
Environment: Production

Issue: Internship csv file displays selectees when the boards are still open

Steps to Recreate:
- Community --> State --> Manage Internships --> Run .CSV file

Resolution: Selectee information should only display when ATP boards have been closed.

[community_tasks (26).xlsx](https://github.com/openopps/openopps-platform/files/3929610/community_tasks.26.xlsx)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-12-19 LHammond in testing
Testing completed, moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/295df00e-89d4-4a0a-8192-63b99d1eb6dc)

**Comment by kbwagner** [comment]
12/12/19 - KWagner tested Chrome/Test 
Ready for final review
