### ISSUE TITLE
Add new field to cycle table for Exclusive posting end date

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4255]
Who: Community managers
What: Ability to add a close date for exclusive postings
Why: To display on selectee/alternate emails

Acceptance Criteria:
- Add a new field called "Exclusive job announcement close date" to the Cycle table.  This field should accept a date month/day/year
- The field can be hidden until the exclusive job announcement link has been added.
- This field should be located to the right or below the Exclusive posting link
- Once the Exclusive job announcement link has been added this field becomes required.

**Comment by bmcorum** [comment]
@kbwagner should we table the field "Exclusive job announcement close date"

**Comment by kbwagner** [comment]
@bmcorum since we can't pull it from USAJOBS we'll need to add it to the table...unless that's what you mean by "table the field" heh heh

**Comment by bmcorum** [comment]
@kbwagner sorry I meant to say label the field. On the UI should the label above the field be called "Exclusive job announcement close date"?

**Comment by kbwagner** [comment]
Exclusive job announcement  close date works yes...thanks

**Comment by bmcorum** [comment]
Ready for testing

**Comment by bmcorum** [comment]
Ready for testing

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/71175548-c0cb2e00-225f-11ea-8904-d29584f6a5de.png)

**Comment by Kibrahacha67** [comment]
12-19-19 LHammond in testing
Testing completed images below.  moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2a0c721f-f9be-4eb2-a7eb-996c02cd7136)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/cabdcab4-3ac8-4d20-957a-63c0eed83723)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/8e336269-8e77-462d-9667-da753c91c9a5)

**Comment by kbwagner** [comment]
12/19/19 - KWagner tested in Chrome/Test
Ready for final review
