### ISSUE TITLE
Create a new role for Bureau Internship Coordinators

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4258]
Who: Bureau Internship Coordinators
What: Create a new role
Why: So their permissions are restricted

Acceptance Criteria:
- Create a new role called Bureau internship coordinators that will be limited to State department

BICs will only be able to do the following:
- Add new members to the community
- Create internships
- Approve internships for their Bureau only (based on the bureau on their profile)

- See attached spreadsheet
- The community manager and community member roles will remain the same

[Proposed DOS Permissions 12December 2019 V2.xlsx](https://github.com/openopps/openopps-platform/files/3956250/Proposed.DOS.Permissions.12December.2019.V2.xlsx)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-19-19 LHammond in testing

**Comment by kbwagner** [comment]
12/23/19 - KWagner tested in Chrome/Test
Ready for final review

Created new ticket to add header to profile
