### ISSUE TITLE
Community Admin Manage users - BIC toggle

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4266]
Who: State community users
What: assign BIC role
Why: in order to allow BICs to approve but limit their access otherwise

Acceptance Criteria:
- Add a toggle for BIC on/off; default is off
- Add the toggle between the Member enabled and Community admin toggles
- Community managers and sitewide admins can assign the BIC role via the toggle

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
12-19-19 LHammond in testing
