### ISSUE TITLE
Add email to Manage User search

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4279]
Who: Administrators
What: Ability to search for users by email
Why: Many users contact us with only an email address and it will make it easier to find them.

Acceptance Criteria:
Admin --> Sitewide --> Users --> Manage

1) Add the ability to search by email
- Search against login.gov and federal email

2) Modify the default text to read:
Sitewide: "Filter by name, email, or agency"
Agency: "Filter by name or federal email"
Community: "Filter by name, federal email, or agency"

**Comment by raywilliams** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-23-19 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/23/19 - KWagner tested in Chrome/Test
Ready for final review
