### ISSUE TITLE
Assign Community Manager badge

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4286]
Who: Community managers
What: Assign badge to display on profile
Why: So they can show they are managers

Acceptance Criteria:
- anyone assigned as a community manager will receive the Community Manager badge on their profile
- Assign the badge to current community managers as well.
- Once a badge is assigned it will stay even if someone is removed the community manager role

Note: If possible, we should remove the State community manager privileges in production prior to this being released.  Most will become BICs.  

Related ticket: 
4292 - Create community manager badge

Request from Lisa Nelson

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing

**Comment by kbwagner** [comment]
1/13/20 - KWagner tested in Chrome/Test
Ready for final review
