### ISSUE TITLE
Vanity URL for Cyber 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4287]
Who: Cyber reskilling community
What: Vanity URL
Why: So they can share the URL with others

Acceptance Criteria:
- Create a vanity URL for Cyber: openopps.usajobs.gov/community/cyber
- only community of cyber will display on this page

Related Ticket: 
4290 - Opportunity search page for Cyber
4342 - Create cyber community

**Comment by bmcorum** [comment]
Need to add a new column to the community table of vanity_url.

**Comment by kbwagner** [comment]
@bmcorum do you need  a separate ticket for that new field or you're doing it as part of this ticket?

**Comment by bmcorum** [comment]
@kbwagner nope just notating a task to be completed for this ticket.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
1/13/20 - Tested in Test/Chrome
Ready for final review
