### ISSUE TITLE
Vanity URL for FAI

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4288]
Who: Acquisitions users
What: Create a vanity URL
Why: So they can provide the URL to their community of users

Acceptance Criteria: 
- Create a vanity URL for FAI/Acquisitions
- The URL should be: openopps.usajobs.gov/community/FAI
- Then URL should point to the existing acquisitions search results page 
- The criteria for acquisition opportunities displaying on this page will be the same as current.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing

**Comment by kbwagner** [comment]
1/13/10 - KWagner tested in Chrome/Test
Ready for final review.
