### ISSUE TITLE
Add search filter for communities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4289]
Who: All users
What: Ability to filter by community opportunities
Why: To aid my search

Acceptance criteria:
- Add a new search field called "Community" that is a dropdown of all Open Communities.  This should appear above skills with similar separator lines around it.
- if a community is selected, it will act as a filter and only display the selected community.
- If FAI or Cyber or selected, the appropriate search page will display.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-9-20 LHammond in testing

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-9-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/9/2020 - KWagner tested Chrome/Test and mobile
Ready for final review
