### ISSUE TITLE
Create opportunity search results page for Cyber reskilling

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4290]
Who: Cyber reskilling detail opportunities
What: Ability to have all opportunities on one page
Why: So they can provide their applicants a URL and make them easy to find

Acceptance Criteria:
- Create a search results page for Cyber similar to what has been done for Acquisitions
- Any opportunity created in the Cyber community will display on the page
- The page title will be: Cyber Open Opportunities
- The page subtitle will be: You're now viewing Cyber opportunities only.
- The remaining information in the blue box will be standard
- The search fields will be the standard search fields

Related tickets:
4287- Vanity URL for Cyber
4342 - Create cyber community

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing

**Comment by kbwagner** [comment]
1/13/20 - KWagner tested in Test/Chrome
Ready for final review
