### ISSUE TITLE
Community manager badge

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4292]
Who: Community managesr
What: Ability to receive a badge for being a community managers
Why: in order to show involvement

Acceptance Criteria:
- Add a new badge to the system for Community leaders.  See attached.

![OO-Badge-CommunityManager.svg](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/86c07962-89c9-4d3d-972a-b83280a00e31)

https://user-images.githubusercontent.com/11526811/71037331-7cb81c00-20ed-11ea-8a93-843e83b7ae19.png

Related ticket:
4286 will assign the badge to community managers

**Comment by bmcorum** [comment]
- [ ] Add an awardCommunityManagerBadge to Badge model
- [ ] Update unit tests for Badge model to cover newly added awardCommunityManagerBadge
- [ ] Attach unit tests artifacts

**Comment by tanichacko** [comment]
unit test artifact attached

![unit test artifact.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/009aae0b-9196-4105-b81e-bf6e1f65fefa)

**Comment by tanichacko** [comment]
unit test artifact attached

![unit test artifact.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/83be7680-1876-427c-825b-021d9642fb0d)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-6-20 LHammond, moving to review with artifact.

**Comment by kbwagner** [comment]
1/7/2020 - Reviewed artifact 
Ready for final review
