### ISSUE TITLE
Remove VSFS community 

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4293]
Who: VSFS community
What: Remove from all environments
Why: VSFS will not be using our product and this will keep our database clean

Acceptance criteria:
- Remove VSFS community from all environments (test, UAT , Production)

**Comment by bmcorum** [comment]
Ready for testing. The VSFS community should no longer appear in the community drop-down on the admin dashboards

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond in testing
In Test it does not show, in UAT and Prod it will show until this code gets pushed to those environments.  moving to review.

**Comment by kbwagner** [comment]
1/2/20 - Tested in Test
Ready for final review
