### ISSUE TITLE
Admin: Change display order of metrics for Quarter and Month options

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4294]
Who: Administrators
What: Ability to view current data first
Why: in order to view current data ahead of historic data

Acceptance Criteria:
admin metrics should display current data first followed by previous.

For the quarter sort: 
- display current quarter followed by last.  For example right now would display Q4 19, Q3 19, Q2 19, Q1 19, Q4 18, etc.

For the month sort:
- display current month first and then work backwards. Dec 2019, November 2019, October 2019, etc.

This should occur for sitewide, admin, and communities

Ticket 4052 made this change for the cycle dropdown

**Comment by jhanson12** [comment]
@Kibrahacha67 this is in testing.

**Comment by Kibrahacha67** [comment]
12-23-19 LHammond in testing 
Testing completed moving to review.

**Comment by kbwagner** [comment]
12/23/19 - Kwagner reviewed in Test
Ready for final review
