### ISSUE TITLE
Remove the demo functionality all together

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#430]
https://github.com/18F/midas/pull/427 changed the demo data to reflect a real-ish use case, but comments should be updated as well:
![image](https://cloud.githubusercontent.com/assets/41906/5267560/d441810c-7a06-11e4-8c20-1608fda2fab6.png)

**Comment by LisaLNelson** [comment]
Demo data could be hard to maintain in the future. We should consider removing the demo functionality all-together.  Here are the files/folders with the demo data.
https://github.com/openopps/openopps-platform/blob/2c8a055edaa9c3685a3bb2b735e4d7f33cc11971/tools/demo.js
https://github.com/openopps/openopps-platform/tree/2c8a055edaa9c3685a3bb2b735e4d7f33cc11971/tools/demo-data

**Comment by kbwagner** [comment]
Closing per backlog review
