### ISSUE TITLE
Add BIC label to profile of BIC community member

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4306]
Who: BICs
What: Display label on profile
Why: In order to indicate their role

Acceptance Criteria: 
Currently all of the other administrator, agency admin and Community managers have a tag next to their names on their profiles. BIC does not.  Add label for BIC users on their profile.
- This label should only show for Sitewide administrators for security reasons

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/47a05b8c-1e0d-4597-976a-7df2f07ba161)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/095409ff-262a-42a2-a404-3f1014068f6c)

Related tickets: 
4315 - will modify this to only display for other administrators

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond in testing, testing completed moving to review

**Comment by kbwagner** [comment]
1/2/20 - KWagner tested in Test/Chrome
Ready for final review
