### ISSUE TITLE
When disabiling from the consoul, the pop up has "BIC". BIC's are a limited role in the DoS community and should not display for disable in any other form.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4310]
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/5e4f6448-369c-4be3-9e3b-f02b682e055c)

**Comment by jhanson12** [comment]
@Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
12-26-19 LHammond in testing
Testing completed moving to review

**Comment by kbwagner** [comment]
12/30/19 - KWagner tested in Chrome/test
Ready for final review
