### ISSUE TITLE
Consider removing approval process for opportunities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4312]
Began discussion with Lisa and need to have further.  Adding here to keep up with for future enhancement

- Remove need to have every opportunity approved by admin in the future
- Would need to remove approval status and update dashboards
- low priority but very few get sent back.  
- Lisa wants to discuss with Michelle

Discussion between Lisa and Katrina 12/2019:
I think it’s a question that may need some discussion with Michelle and others. For example, there are some people who post regularly and I don’t really pay a whole lot of attention to the specifics when I publish.  But I think there may be a lot of push back from senior managers about just letting anybody publish directly.  Could open it up for something inappropriate to be published. So maybe there is some kind of graduated system.

From: Wagner, Katrina B. 
Sent: Tuesday, December 17, 2019 10:32 AM
To: Nelson, Lisa L. <Lisa.Nelson@opm.gov>; Orrison, Tracy L. <Tracy.Orrison@opm.gov>
Subject: RE: Response to slack questions

So up to you I guess…still want to keep the approval process?  If you don’t think it really does any good, maybe we just allow it to be submitted and skip the approve piece.  But that’s kind of a bigger deal so we’d need to map it out and not likely to happen quickly anyway.  But as more and more come in we may want to think about whether it’s necessary.  

Katrina Wagner
Business Analyst
US Office of Personnel Management
Katrina.Wagner@opm.gov | www.opm.gov/HRS
 
     

From: Nelson, Lisa L. 
Sent: Tuesday, December 17, 2019 10:29 AM
To: Wagner, Katrina B. <Katrina.Wagner@opm.gov>; Orrison, Tracy L. <Tracy.Orrison@opm.gov>
Subject: RE: Response to slack questions

No I don’t get a lot of junk now.

From: Wagner, Katrina B. 
Sent: Tuesday, December 17, 2019 10:26 AM
To: Nelson, Lisa L. <Lisa.Nelson@opm.gov>; Orrison, Tracy L. <Tracy.Orrison@opm.gov>
Subject: RE: Response to slack questions

we can continue the discussion in the future of whether we want to just allow them to be posted.  Do you get a lot of junk that you send back?

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41480&_a=edit
