### ISSUE TITLE
Label display on profile for user roles

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4315]
Who: Open Opps users
What: Do not display role/permission labels if not admin
Why: to prevent security issues

Acceptance Criteria:
- Currently the user role label displays on the profile for anyone using people search to see.
- Modify to only show the label for admins as defined below, not for general profile across the board
- only show agency admin to other agency admins for the agency
- admin can only be seen by other admin
- BIC can only be seen by another BIC
- Sitewide admins can see all of the above

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/095409ff-262a-42a2-a404-3f1014068f6c)

**Comment by Kibrahacha67** [comment]
@kbwagner Question: is there going to be a tag for Sitewide approver?

**Comment by kbwagner** [comment]
@Kibrahacha67 we probably don't have one yet and need to add it.  I'm on it.  Thanks!

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-17-20 lHammond in testing

**Comment by kbwagner** [comment]
1/20/20 - KWagner tested in Chrome/Test
Ready for final review
