### ISSUE TITLE
Remove login.gov transition page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4323]
Who: All Open Opportunities users
What: Remove login.gov transition page
Why: To streamline the sign in process

Acceptance Criteria:
When a user clicks sign in from Open Opportunties, they will no longer go to the login.gov transition page.  They will no go directly to the login.gov sign in page
- The login process will be the same as currently in USAJOBS production.

Related tickets: 
4338 - remove new way to sign in yellow banner
40704 - TFS ticket for removal on USAJOBS side

**Comment by kbwagner** [comment]
@bmcorum looks like we can close this ticket?

**Comment by kbwagner** [comment]
This will go out with Titan release 8.9.  Holding until they release so we can test.

**Comment by nia-johnson** [comment]
Passed in the test environment on Chrome. Moving to final review.

**Comment by kbwagner** [comment]
@nia-johnson we will leave this one in test with the hold tag for 2 weeks until it gets deployed via USAJOBS.  Even though it's right in our test system we want to test it in production when it goes out which won't be for 2 weeks with USAJOBS 8.9.

**Comment by kbwagner** [comment]
2/11/2020 - KWagner tested in production, page has been removed
Closing
