### ISSUE TITLE
Remove .gov from Edit at USAJOBS.gov button on profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4324]
Who: Open Opportunities users
What: Lable on Edit at USAJOBS.gov
Why: design

Acceptance Criteria
Recommendation from Matt/Design
: •	"Edit at USAJOBS.gov" - Do we really need the .gov in there? It looks odd to have a half uppercase and half-lowercase URL.
- Remove .gov and have the button only read Edit at USAJOBS

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-14-20 Lhammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/16/20 - KWagner tested in Chrome/Test
Ready for final review
