### ISSUE TITLE
Share Profile Updates

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4325]
Who: Open Opps users
What: ability to share profile
Why: in order to maintain my privacy if desired

Acceptance Criteria:
Design (Matt) comments on sharing of profile: 
•	The Share link doesn't belong here. Who am I sharing my own profile with? Mom? (Good one Drew)
•	There is no option to opt-out of sharing my information.
•	There is no clear indication of what information I am sharing (and what I'm not).

**Comment by kbwagner** [comment]
@abudz19 can you drop a link in here of what Matt had designed?

**Comment by abudz19** [comment]
https://opm.invisionapp.com/d/main#/console/15990896/340537467/preview

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41404&_a=edit
