### ISSUE TITLE
DoS - Student Withdraws Application After Application Cycle Closes

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4327]
### Who
Students

### What 
Students should be able to withdraw their application after the application cycle closes. 

### Why 
- Students that no longer want to be considered for an internship should be able to withdraw at any time.
- Hiring managers should have an up-to-date stream of interested applicants 

### Acceptance Criteria
- The withdraw button is active after the application cycle is closed
- The user should be able to withdraw their application after the application cycle is closed. 
- Information associated with the user withdrawing their application off-cycle should be retained. 
- Withdrawn internships should be hidden from the user

### Related Tickets

ATP - [TFS 40640](https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Agency%20Talent%20Portal/_workitems?id=40640&_a=edit)

### Mocks 
None

**Comment by bmcorum** [comment]
- [ ] Add a withdrawn date to the application table

**Comment by kbwagner** [comment]
Created 4389 to discuss how withdrawn applicants should be display in admin pages

**Comment by bmcorum** [comment]
Ready for testing

**Comment by jhanson12** [comment]
@nia-johnson, @bmcorum , @Kibrahacha67 After discussing with @kbwagner, decision was made to hide the internship once a student has withdrawn.  @nia-johnson could you please updated the AC for testing.  Thank you!

**Comment by nia-johnson** [comment]
@jhanson12 Done

**Comment by Kibrahacha67** [comment]
1-17-20 LHammond in testing

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-22-20 LHammond in testing
Testing completed.  Moving to review.
NOTE: The ATP side of the review still has some work to do.  I saw that the student that I withdrew the application on in open opps was removed from one of the internships, but the other board didnt remove her.  And she was selected for a primary, and shows on that internship in open opps in the administration page(may need a ticket to remedy that).  But on her home page that cycle is totally removed and the student cannot see the application as was requested.  The student received the withdrawal email but didn't receive the acceptance email.  So from the Open Opps side of things we seem to be working as normal.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2a26a9ed-1381-48cb-800f-ff81afc0df68)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/182a86c6-49d8-4f06-a6cb-d99249e16bab)

**Comment by kbwagner** [comment]
2/4/2020 - KWagner tested in UAT/Chrome

@jhanson12 I have one scenario that's action funny.   For cycle HOTFIX II I have one with a status of "not submitted"  If I click on the cycle link and the page flashes and I stay on the landing page This cycle in UAT is currently open for ATP review.
Not sure if it's related to this ticket or a separate bug?  Maybe if it's not submitted and the apply process has closed, the link should just go away?  Thoughts?
![image](https://user-images.githubusercontent.com/18709918/73749632-c1ddef00-4729-11ea-9891-85dfabc2d2b1.png)

**Comment by kbwagner** [comment]
Passing/closing
Will create a new bug for the not submitted issue.
