### ISSUE TITLE
DoS - Student Dashboard Enhancements

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4329]
### Who 
Students, Internal Staff 

### What
Updates to the student dashboard allowing them to view additional information related to their application status. 

### Why
- Reduce the number of students contacting DoS or Open Opps following up on their application statues
-  Students can easily find out their application status. 

### Acceptance Criteria
The user should be able to view the following: 
- Application received date should display - most recent application date 
- Applied to these internships - display the first/second/third choice with status pills and last updated date.  Application statuses will be pills  (note - mock does not reflect correct applicant status names)
- Selected for this internship along with internship name and bureau/office and a status pill.  This section will only display if the student is selected for an internship that wasn't their first second or third choice.
- Messages - Emails related to application status previously sent to the user.  For application received, show the most recent email sent.  All emails should display the date and time of when the email was sent (not in mock)
- Questions section with State email

### Mocks / Related Tickets
Mocks can be viewed [here](https://opm.invisionapp.com/share/ZEPNZR09Q54#/screens/400072525_Student_Dashboard_-_V2_-_Internships_First). 

Related tickets: 
4411 - Create applicant status pills
4412 - Display applicant status pills on student landing page
4329 - Applicant dashboard enhancements

**Comment by kbwagner** [comment]
@nia-johnson taking requirements ready off of this until @abudz19 has completed the design.  Then we can discuss how to break it down into multiple tickets.  This is a good placeholder for now.

**Comment by kbwagner** [comment]
@nia-johnson sent you an email with a few comments on this one.  Thanks!

**Comment by kbwagner** [comment]
@bmcorum let us know if the email portion of this should be moved to a separate ticket?

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
2-6-20 LHammond in testing

**Comment by Kibrahacha67** [comment]
2-7-20 LHammond in testing
Testing completed.  Moving to review
NOTE: was tested using Nam autem ducimus in tempore minus autem and Winter is here Cycle.  Data in both of those cycles is good.  If there are any questions please let me know.

**Comment by Kibrahacha67** [comment]
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/e59a730b-0d72-42ce-96b1-e07c95c05376)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ebd1686e-537e-4ced-aa30-fd2fb3de1d69)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/af598158-9688-4386-9688-7703f2272383)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/911cc82c-473d-452a-8c77-fa91576bb7d1)

**Comment by Kibrahacha67** [comment]
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/521a75ad-08bd-4374-ada2-245b14cfa153)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/804f9d45-4868-4bd6-b4cc-e06c72698003)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ed746364-5070-4af7-bf69-5ed24a383692)

**Comment by kbwagner** [comment]
2/11/2020 - KWAgner reviewed student test account and artifacts.
Closing
