### ISSUE TITLE
IE is spinning on the home page in all Environments once the "Sign in" button is clicked.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4331]
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/df5c22c8-4d38-4207-b300-d8332ef4bfba)

**Comment by jhanson12** [comment]
Ready for testing @Kibrahacha67

**Comment by Kibrahacha67** [comment]
1-2-20 LHammond Testing good in Test Environment.  Will have to test other environments as the code moves forward...

**Comment by kbwagner** [comment]
1/6/20 - KWagner reviewed in Test/IE

@bmcorum keep me posted on a hot fix for this.

**Comment by kbwagner** [comment]
1/6/20 - KWagner reviewed hot fix in UAT/IE

**Comment by kbwagner** [comment]
1/7/2020 - tested hot fix in production
Closing
