### ISSUE TITLE
Remove "New Way to sign in" yellow banner

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4338]
Who: Open Opportunities users
What: Remove new way to sign in banner
Why: it is no longer needed

Acceptance Criteria:
- Remove the yellow "New way to sign in" banner from the home page.
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/f2d76ac7-1d4a-49ab-95f0-6e8012eb1d4f)

Related tickets:
4323 - Remove login.gov transition page

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-14-20 LHammond in testing
completed testing moving to review.

**Comment by kbwagner** [comment]
1/16/20 - This has been removed
