### ISSUE TITLE
Display field size limit for internship opportunities during create process

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4339]
Who: Internship opportunity creators
What: Display field size limits for all large text fields
Why: In order to help creators plan their text

Acceptance Criteria:
- Display field size max/countdown on all large text field on Create/Edit Internship Opportunity.

The following fields on the internship create should display field size limits:
- Internship title - 100
- What you'll do - 5000
- Who we are - 5000

Create/Edit Screen shot: 
![image](https://user-images.githubusercontent.com/18709918/71823554-7c180300-3065-11ea-9f15-2131f5c02244.png)

Countdown example:
![image](https://user-images.githubusercontent.com/18709918/71823847-3a3b8c80-3066-11ea-8fd7-78d0f8033ef6.png)

Related ticket: 
3345 - display field limits for opportunities

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-23-20 LHammond in testing
All three fields hold the 5000 limit in the AC.  But the error checking on the Title field is still set to 100 characters so it is out of line with the request.  moving back to development 

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/4d92a97c-b6b6-444f-82f4-bbee7e00745a)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
01/27/2020 - Mdumas - in testing

**Comment by margaretdumas** [comment]
Mdumas - Moving back to development

**Comment by raywilliams** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
1/27/2020 - Mdumas - Moving to review

**Comment by kbwagner** [comment]
1/30/2020 - KWagner reviewed.
Closing
