### ISSUE TITLE
Create cyber reskilling community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4342]
Who: Cyber reskilling
What: Community setup
Why: to set up a new community for Cyber

Acceptance Criteria:
See attached template for fields that should be added for the new cyber community

[Community template - Cyber.docx](https://github.com/openopps/openopps-platform/files/4027317/Community.template.-.Cyber.docx)

**Comment by tanichacko** [comment]
@kbwagner The description field only allows 500 characters . The attached community template doc description has 534 characters

**Comment by kbwagner** [comment]
@tanichacko thanks - I'll reach out to them.

**Comment by kbwagner** [comment]
@tanichacko @bmcorum Cyber needs their community now in production so I will set it up manually.  Brice should I close this ticket?  I'm guessing you still need it set up in test?

**Comment by bmcorum** [comment]
@kbwagner this can be closed since the community was created via the admin UI in each environment. I completed TEST this evening.

**Comment by kbwagner** [comment]
Closing - created in test, UAT, and production
