### ISSUE TITLE
Add "Remove" Link Below Badges on User's Profile Page 

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4345]
### Who
Site wide Administrators 

### What
The ability for side wide admins to remove Community Manager badges from a user's profile via a link under the badge

### Why
Site wide administrators should be able to remove Community Manager badges from users' profiles 

### Acceptance Criteria
- The admin clicks the remove link under the Community Manager badge and the confirm modal appears
- If the user clicks "Cancel" in the modal, the Community Manager badge is left unchanged
- If the user clicks "Remove", the Community Manager badge is removed and the success alert banner is displayed

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4346, https://github.com/openopps/openopps-platform/issues/4347

### Mocks
Remove Link
<img width="993" alt="71752619-bad37080-2e4d-11ea-8592-b844baddd5b7" src="https://user-images.githubusercontent.com/57805715/71851597-ea2fea80-30a4-11ea-92ab-456a64984f8b.png">

Remove Modal
<img width="685" alt="71752689-02f29300-2e4e-11ea-90c7-9ea6dff9bfe2" src="https://user-images.githubusercontent.com/57805715/71851598-ea2fea80-30a4-11ea-83fc-aaf12a98f64a.png">

Success Alert
<img width="838" alt="71752764-4baa4c00-2e4e-11ea-98f5-ae21d07d5898" src="https://user-images.githubusercontent.com/57805715/71851596-ea2fea80-30a4-11ea-920d-38a10a112b41.png">

**Comment by kbwagner** [comment]
@nia-johnson this looks good. Under related tickets if you can just list out the other backlog items you entered for adding, etc.  Then it's good to go.

**Comment by bmcorum** [comment]
This is ready to test.

**Note** after you have run a few tests let me know and I will collect a data artifact to attach as evidence

**Comment by Kibrahacha67** [comment]
1-23-20 LHammond in testing...will do

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/73193532-b884cf00-40f8-11ea-976d-bce361ec81d2.png)

**Comment by margaretdumas** [comment]
01/27/20 - Mdumas - Remove link is present and working .  Artifact is added as well to confirm it works.  Moving on to review.

**Comment by nia-johnson** [comment]
Tested in Test. I don't see it. Moving back to testing. 

<img width="932" alt="Capture 1" src="https://user-images.githubusercontent.com/57805715/73205793-b2e6b380-410f-11ea-838c-e0bd3bfa2200.PNG">

**Comment by bmcorum** [comment]
@nia-johnson did you verify you are a sitewide administrator?

**Comment by nia-johnson** [comment]
Yes, I'm a sitewide. I wouldn't be able to look up the account otherwise.

**Comment by margaretdumas** [comment]
Moving back to review.  ![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/40222be9-c3a5-466b-8050-2f20001ef3b2)

**Comment by kbwagner** [comment]
@margaretdumas should the hold tag come off of this one now?

**Comment by nia-johnson** [comment]
Passed in Test. Moving to Final Approval.

**Comment by kbwagner** [comment]
@tanichacko the remove modal should have an apostrophe to show ownership so in this example Tracy Orrison's profile.  Please add the 's after the name per the screen shot of the modal in the AC. Returning to development.

![image](https://user-images.githubusercontent.com/18709918/73211985-48d40b80-411b-11ea-8e57-acb1f41734ee.png)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-28-20 LHammond in testing
Testing completed moving to review.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/97a2d533-a180-42e4-87db-cad6d032bcb7)

**Comment by kbwagner** [comment]
1/28/2020 - Kwagner reviewed
Ready for final review
