### ISSUE TITLE
Add "Add Badge" button to User Profile Page 

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4346]
### Who
Site wide Administrators 

### What
The ability for side wide admins to add a Community Manager badge to a user's profile via a button by the "Badges" title

### Why
Site wide administrators should be able to add a Community Manager badge to users' profiles 

### Acceptance Criteria
- The admin clicks the "Add Badge" and the Add modal appears
- If the user clicks "Cancel" in the modal, the profile is left unchanged
- The only available badge that the admin can select is Community Manager. Given this pre-selection,  the "Add" button will be active. 
- Given a that Community Manager has been pre-selected and the user clicks the "Add" button, the  Community Manager badge is added to the profile. 

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4345, https://github.com/openopps/openopps-platform/issues/4347

### Mocks
Add Button
<img width="993" alt="71752619-bad37080-2e4d-11ea-8592-b844baddd5b7" src="https://user-images.githubusercontent.com/57805715/71851597-ea2fea80-30a4-11ea-92ab-456a64984f8b.png">

Add Modal 
<img width="686" alt="71752669-ea827880-2e4d-11ea-9272-8ef09118c441" src="https://user-images.githubusercontent.com/57805715/71852237-45aea800-30a6-11ea-818e-bd003bad2f66.png">

Success Alert
<img width="838" alt="71752764-4baa4c00-2e4e-11ea-98f5-ae21d07d5898" src="https://user-images.githubusercontent.com/57805715/71852391-97573280-30a6-11ea-9bd4-1dcef8601a04.png">

**Comment by kbwagner** [comment]
@nia-johnson this one is fine if you can just add the related tickets for delete link and user name link.

**Comment by bmcorum** [comment]
This is ready to test.

**Note** after you have run a few tests let me know and I will collect a data artifact to attach as evidence

**Comment by Kibrahacha67** [comment]
1-23-20 LHammond in testing
testing completed moving to review.

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/73193513-b0c52a80-40f8-11ea-97d0-610e38cd67c4.png)

**Comment by margaretdumas** [comment]
01/27/20 - Mdumas - Moving on to review.

**Comment by nia-johnson** [comment]
Tested in Test. I don't see it. Moving back to testing. 

<img width="932" alt="Capture 1" src="https://user-images.githubusercontent.com/57805715/73205793-b2e6b380-410f-11ea-838c-e0bd3bfa2200.PNG">

**Comment by bmcorum** [comment]
@nia-johnson did you verify you are a sitewide administrator?

**Comment by nia-johnson** [comment]
@bmcorum Yes, I'm a sitewide. I wouldn't be able to look up the account otherwise.

**Comment by margaretdumas** [comment]
Nia, not sure if this is the account you are using but if so, you are not a sitewide admin.  ![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/eebbd791-f3dc-4547-b302-eaf6931cbc5d)

**Comment by margaretdumas** [comment]
Mdumas - Moving back to review with artifact.  ![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/3cbd47db-839b-4505-b58d-07ec1aa5e336)

**Comment by nia-johnson** [comment]
Passed in Test. Moving to Final Approval.

**Comment by kbwagner** [comment]
1/27/2020 - KWagner tested in Chrome/Test
Ready for final review
