### ISSUE TITLE
Link User's Names to Profile in Admin Dashboard

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4347]
### Who
Site wide, Agency, and Community Administrators 

### What
The ability for Site wide, Agency, and Community Administrators to navigate to a user's profile by clicking their name in the admin dashboard. 

### Why
Site wide, Agency, and Community Administrators should be able to easily navigate to users' profiles 

### Acceptance Criteria
- The admin clicks the user's name in the admin dashboard and directed to the user's corresponding profile. 

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4345, https://github.com/openopps/openopps-platform/issues/4346

### Mocks
<img width="818" alt="71752804-7b595400-2e4e-11ea-9ecc-4f4cdd69d56d" src="https://user-images.githubusercontent.com/57805715/71852870-cb7f2300-30a7-11ea-8332-13deb0823f51.png">

**Comment by kbwagner** [comment]
@nia-johnson same on this one - good to go if you can just update the related tickets.  Thanks!

**Comment by bmcorum** [comment]
ready for testing

**Comment by Kibrahacha67** [comment]
1-17-20 LHammond in testing

**Comment by nia-johnson** [comment]
@Kibrahacha67 @bmcorum Tested in UAT and I don't see the link. 

<img width="926" alt="No Link" src="https://user-images.githubusercontent.com/57805715/72633401-612b7580-3926-11ea-8a73-2e1c42f2bf80.PNG">

**Comment by nia-johnson** [comment]
Tested and passed in the Test environment on Chrome. Moving to Final Review.

**Comment by kbwagner** [comment]
1/27/2020 - KWagner tested in chrome/Test
Closing
