### ISSUE TITLE
State: Email to hiring managers to complete internship

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4348]
### Who
Department of State hiring managers

### What
Email to hiring managers to complete internship

### Why
to trigger them to complete the process

### Acceptance Criteria
- Email should be sent on the close date of the internship
- Content is being worked as part of design ticket https://github.com/USAJOBS/team-design/issues/144

### Related Tickets 
n/a
### Mocks
n/a

**Comment by kbwagner** [comment]
@nia-johnson I created this shell ticket as a placeholder while we wait for content.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41532&_a=edit
