### ISSUE TITLE
Adjust USAJOBS Logo to Correct Proportions in Manual Trigger Emails

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4350]
### Who
Open Opps users 

### What
The USAJOBS logo displayed in correct proportions in the manual trigger emails. 

### Why
Open Opps' emails should appear professional and easy to read.  

### Acceptance Criteria
Issue: The USAJOBS logo in the manual triggers emails is not the correct proportion. It’s either too wide for the height, or not tall enough for the width.

Resolution: The USAJOBS logo is replaced with one that is accurately proportioned for the manual trigger email 

### Related Tickets 
https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=38745&_a=edit

**Comment by kbwagner** [comment]
@nia-johnson approved this one - FYI I added the issue into this to help define the problem and added labels of bug and email.

**Comment by kbwagner** [comment]
@bmcorum is there a list of the manual trigger emails?  We can add that to this bug (sent to us from ATP).  Does each email need its own bug ticket?

**Comment by bmcorum** [comment]
@kbwagner this came to use from a Titan BA who noticed the USAJOBS logo is being stretched on the automated cycle emails that are sent when certain actions occur in ATP.

**Comment by kbwagner** [comment]
@bmcorum yes and they said it had to be worked on our side.  Does this bug give you enough info?

**Comment by bmcorum** [comment]
@kbwagner it does. I believe the issue was that the Open Opportunities logo is wider than the USAJOBS logo so when it was placed inside the same are it was stretched to fill the defined space. We may simply need to add some padding to the USAJOBS logo to prevent the stretching.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing
The logo didn't come over once the email was sent.  The message was that the image was moved or cannot be found (see image below.)  sending back to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/95c35fc7-f5a7-4722-8c81-0328e3bc3575)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-17-20 LHammond in testing

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-22-20 LHammond in testing
Testing completed moving to review.
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/150a76a0-79fb-4398-beee-c41dd3e963d2)

**Comment by kbwagner** [comment]
1/22/2020 - KWagner reviewed artifact 
ready for final review
