### ISSUE TITLE
Allow for State users to be associated to multiple bureaus/office/posts

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4353]
Who: State users
What: Ability to add multiple bureaus/office/posts to their profile
Why: To allow one BIC to serve as a BIC for multiple bureaus

Acceptance Criteria: 
Issue: One BIC can be a BIC for multiple bureaus
- Allow for a State user to add multiple bureaus/office/posts on their profile

- Change the display of the Bureau / Office / post module to match:
<img width="425" alt="Dept_of_State_-_Open_Opps_-_Search_Apply_Profile" src="https://user-images.githubusercontent.com/11526811/72018605-057e2f80-3236-11ea-9041-4adab8469370.png">

- add "Add" button.  Add will open the current page as a modal
![image](https://user-images.githubusercontent.com/18709918/72075280-6868d880-32c1-11ea-89d4-dac1a6f7a0cb.png)
- The buttons on this modal should be simply Cancel and Save with no wording behind them.

- add "Remove" link underneath each assigned Bureau/office/post
- Remove will include the standard remove are you sure you want to remove yes/no messaging
"Bureau and Office/post removed."
“You have successfully removed [User name] from the [Bureau name], [Office/post name].”

- Success modal for add to include text:
"Bureau and Office/post added."
“You have successfully added [User name] to the [Bureau name], [Office/post name].”
- Success modal for remove to include text:

Related tickets: 
4354 - Verify BIC approval

**Comment by bmcorum** [comment]
- [ ] Create join table user_bureau_office (user_id, bureau_id, office_id)
- [ ] Data migration to insert record for existing bureau/office profile data

**Comment by Kibrahacha67** [comment]
@kbwagner @bmcorum I have a question here, If a user wants to add and office/post how will they for a specific bureau.  If it worked like the Manage community page the add new would have a radio button to allow the user to select what they were trying to accomplish, is that what is going to happen here?  Because if they add more then one post then we are not going to be able to support with this AC...

**Comment by kbwagner** [comment]
Right now they can't have more than one office/post for a bureau.  That hasn't come to us as a requirement so I think we're safe.  But, I do have an email out to State asking them for more feedback so I'll confirm. But that would be a new ticket regardless.

**Comment by bmcorum** [comment]
ready for testing

**Comment by Kibrahacha67** [comment]
1-17-20 LHammond in testing
Testing completed moving to review
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/79b7cf2d-52fb-40ee-a68f-5eecda2f29ed)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/44d149a2-eec0-4cbb-9c5e-32ae3585c3ce)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/53043f94-3a92-43a7-8006-0d139dfe759c)

**Comment by Kibrahacha67** [comment]
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/6420c14c-a79c-4a68-a787-2828deddb1d1)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c1dca122-d3cb-4707-8005-534710d2083b)

**Comment by kbwagner** [comment]
1/20/20 - kwagner tested in Chrome/Test
Ready for final review
