### ISSUE TITLE
verify BIC approval process

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4354]
Who: Bureau Internship Coordinators
What: Ability to approve internship for multiple bureaus
Why: In order for them to complete their jobs

Acceptance Criteria:
- BICs can be a BIC for more than one bureau
- Verify a BIC with multiple bureaus can approve for all bureaus they are assigned to
- Verify a BIC with multiple bureaus receives the approval email for all bureaus that they are assigned to.

Related tickets:
4353 - Allow for state users to select more than one bureau

**Comment by jhanson12** [comment]
@Kibrahacha67  this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-21-20 LHammond in testing

**Comment by Kibrahacha67** [comment]
Testing completed based on AC update...moving to review.

**Comment by kbwagner** [comment]
1/21/20  - reviewed.
