### ISSUE TITLE
Bug: Modify language on Student internship create/edit for Internship Title

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4355]
Environment: All

Issue: When a user does not enter an Internship title when creating/editing a Student internship, the messaging reads, "You must enter a headline..."
Note: The edit message for a regular opportunity should not be changed.

Resolution: Change headline to match the field title of "Internship title"

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing,
completed testing moving to review...

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ff56ba4e-c4b2-46d2-8285-3a0f024788d1)

**Comment by kbwagner** [comment]
1/13/20 - KWagner reviewed in Test/Chrome
Ready for final review
