### ISSUE TITLE
Sitewide approver role: Ready to approve email should only go to approver role

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4359]
Who: Sitewide approvers
What: Email notification of an opportunity to approve
Why: In order to have sitewide admins have less emails.

Acceptance Criteria: 
- Email notification of an opportunity ready to approve should now only go to a person who is a sitewide approver
- Sitewide admin will no longer get the email

Use Case:
- a person who is a sitewide admin who wants to get email notifications of an opportunity submitted will mark themselves as an approver as well.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-28-20 LHammond in testing
Testing completed moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/933b2c53-06e4-4a08-8fca-38fa56ebc13e)

**Comment by kbwagner** [comment]
2/4/2020 - Kwagner tested in UAT
Closing
