### ISSUE TITLE
Bug: Error when deleting draft from dashboard

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4364]
Environment: UAT (does not occur in production at this time)

Steps to reproduce:
1) Create an opportunity and save for later
2)  Go to homepage and click delete beside the draft
3) The confirm modal displays and confirm delete
4) Unexpected error message displays although draft does get deleted correctly

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/0a3b4c94-beca-4663-837a-ac33497e48f3)

**Comment by bmcorum** [comment]
This appears to be working as intended. I attempted to look through some logs on Cloud.gov. It was hard to pin down but it appears as though it may have been related to some Redis issue we were experiencing over the past few weeks as the error code being returned was a 403 which is forbidden.

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/13/20 - Tested in UAT Chrome and mobile and this error is no longer occurring.  
Closing
