### ISSUE TITLE
Update Open Opps favicon

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4366]
Who: Open Opps users
What: Update the favicon that displays with the site
Why: To have it be consistent with all of our sites

Acceptance Criteria:
- For Test, UAT, and production update the favicon that displays in Open opportunities to be the same that displays for USAJOBS
- This favicon should also display for the help center for Open Opportunities in all environments

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-14-20 LHammond in testing

**Comment by kbwagner** [comment]
@raywilliams The area I was referring to for the favicon still shows up in test.  The tab photo and as you're typing in the URL, the icon shows in the bar but then goes away to a lock symbol once it's open

![image](https://user-images.githubusercontent.com/18709918/72533061-7af38c80-3842-11ea-9a6d-d4805f262249.png)

**Comment by raywilliams** [comment]
@kbwagner Brice fixed an Akamai cache issue so a Ctrl+F5 in Chrome should allow you to see the updated favicon.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-17-20 lHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
@raywilliams it shows up correctly now on the tab but what about in the search bar itself?  

![image](https://user-images.githubusercontent.com/18709918/72732955-e2704b80-3b64-11ea-992f-cc8a3e1eb921.png)

It appears while I'm typing but eventually gets changed to the lock icon.

**Comment by raywilliams** [comment]
@kbwagner It may be cached on your computer. I tested it and this is what I see. 

![image](https://user-images.githubusercontent.com/340340/72808920-971f7100-3c28-11ea-9b8f-8117f17418d7.png)

**Comment by kbwagner** [comment]
@raywilliams I got it - I thought the f5 from above would have worked but I cleared cache/shut down/rebooted and it's fine now.

Thanks!
