### ISSUE TITLE
Change name of Cyber community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4368]
Who: Cyber users
What: Update name of the cyber community
Why: to reflect the program function better

Acceptance Criteria:

Change community name from: 
Cyber Reskilling Academy Graduates

To: 
Cyber Reskilling Detail Program

Do so in Test, UAT, production

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing
Testing completed moving to review.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c5c97c35-3181-4cac-b37d-e373fe72e44b)

**Comment by kbwagner** [comment]
1/13/10 - tested
ready for final review
