### ISSUE TITLE
Add Mailto Link to User's Email in Admin Dashboard 

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4370]
### Who
Site wide, Agency, and Community Administrators

### What
The ability for side wide admins to create an email addresses to a particular user by clicking their email in the admin dashboard.

### Why
Most websites display email addresses as a mailto link. Doing so in the admin dashboard would be more intuitive for users. 

### Acceptance Criteria
The user should be able to do the following: 
- See the Federal and login.gov emails listed in the admin dashboard search results displayed as a link 
- Click either the Federal or Login.gov email link and have their default mail provider open a "New Email" window with the email they clicked in the To field. 
- This should happen for sitewide, agency, and community administrators (federal and/or login depending on what they see)

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4345, https://github.com/openopps/openopps-platform/issues/4346, 
https://github.com/openopps/openopps-platform/issues/4347

### Mocks
<img width="818" alt="71752804-7b595400-2e4e-11ea-9ecc-4f4cdd69d56d" src="https://user-images.githubusercontent.com/57805715/72097690-f2796700-32ea-11ea-8429-26e89ed535ed.png">

**Comment by kbwagner** [comment]
@nia-johnson this looks good.  I would just specify whether this should be their federal email, login.gov email or both and for sitewide, agency, and all communities

**Comment by nia-johnson** [comment]
Do most Open Ops users access their platform on their personal or government laptop? I assumed the latter, but I could be wrong. @kbwagner

**Comment by kbwagner** [comment]
@nia-johnson users are encouraged to use personal email addresses for login.gov so if they move from job to job they don't have to change their email.  However, we've also been told most users prefer to be contacted on their federal email address.  But...we also have students that don't have a federal email address.  So I guess to sum it up - probably should link to both but for user training/demos we should encourage the user of the federal email if available

**Comment by nia-johnson** [comment]
@kbwagner Understood. From my experience with mailto links, they usually lean on device settings on the user's end, not site configurations on our end. 

For example, if Outlook is my default mail program and it always logged into my email, if I click the mailto link, it'll open Outlook with the account(s) Outlook is logged into at the moment I clicked. This means that the user can configure their device setting for mailto links to open on the account/mail program they want. 

Technically, if we want to dictate which email to use, we could mock up a UI so the user can send the email in the browser, but that will probably be more work for us.

**Comment by kbwagner** [comment]
@nia-johnson correct on the mail to - I was just saying we need to specify which of the columns to include as mail to links which probably should be both.  Sitewide admins have a column for federal email and login.gov email and both should be their own mail to links so it opens with that email address.

**Comment by nia-johnson** [comment]
Ohhhh, so you want two email fields - one for personal and one for fed? I can do that. Want me to make a new ticket or add it to this one?

**Comment by kbwagner** [comment]
@nia-johnson there are already two email fields - so just have both of them no longer be links to the profile but both should be mail to links.  Can be one ticket.

For example, sitewide can see federal email and login.gov email, 
- Also should be done for agency and community which I think can all be done in this ticket

**Comment by nia-johnson** [comment]
@kbwagner Fixed

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41557&_a=edit
