### ISSUE TITLE
Update State community user .csv to include BIC

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4377]
Who: State admin
What: update the user .csv to include BIC role
Why: to be able to show complete information on the user population

Acceptance Criteria: 
Update the manage user .csv for the state community to include the BIC role.  Should appear as it does on the screen between member enabled and community admin.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-29-20 LHammond in testing

**Comment by Kibrahacha67** [comment]
1-29-20 LHammond in testing
the column headers in the csv are in the incorrect order.  They should appear in the same order as the page which is member enabled then BIC then Community admin.  sending back to development 

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/705f68e8-bb0b-4adf-80b6-f15685735a31)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/c828c06b-0f0d-4ab8-baa5-f730e49ca2e9)

**Comment by Kibrahacha67** [comment]
1-31-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
2/3/2020 - KWagner tested in Test/Chrome
Final review complete
Closing
