### ISSUE TITLE
Bug: Delete column for opportunities on profile page

### ISSUE THREAD

**Issue by bmcorum** [openopps/openopps-platform#4378]
### Who
General users

### What
The opportunity display card on user profiles should not include a delete capability.

### Why
Delete capability should only reside on user's home page or administration dashboards.

### Acceptance Criteria
Do not display delete capabilities on profile pages.

### Related Tickets 
N/A

### Mocks
Currently sitewide administrators can see a delete capability on user profiles.
![image](https://user-images.githubusercontent.com/1165615/72262885-cc531000-35e5-11ea-9551-e8ab67528e9c.png)

**Comment by kbwagner** [comment]
TFS https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41484&_a=edit
41484
