### ISSUE TITLE
FAI Vanity URL change

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4381]
### Who
Federal Acquisition Professionals 

### What
Modify vanity URL

### Why
FAI is not current and it should appropriately reflect Acquisition

### Acceptance Criteria
Modify the vanity URL for FAI to end in /Acquisition instead of /FAI
Current Vanity URL: openopps.usajobs.gov/community/FAI
New: openopps.usajobs.gov/community/Acquisition

### Related Tickets 
4288 created the original vanity URL 

### Mocks
n/a

**Comment by bmcorum** [comment]
Ready for testing in UAT

**Comment by Kibrahacha67** [comment]
1-17-20 LHammond in testing

**Comment by bmcorum** [comment]
Ready for testing in UAT

**Comment by Kibrahacha67** [comment]
1-22-20 LHammond in testing

**Comment by bmcorum** [comment]
Ready for testing in UAT

**Comment by Kibrahacha67** [comment]
1-23-20 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment]
1/24/2020 - KWagner tested in UAT
Ready for final review
