### ISSUE TITLE
Withdrawn students should not display in admin view

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4389]
Who: Withdrawn students
What: Do not display in admin views
Why: to avoid confustion

Acceptance criteria:
- If a student has withdrawn their application either during the apply cycle or after the apply cycle has closed, hide them from any admin views.
- Withdrawn students should not display as applicants on the .csv file or during search applicants.
- Withdrawn students should not be included in metric counts on the dashboards

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-28-20 LHammond in testing

**Comment by kbwagner** [comment]
1/30/2020 - KWagner reviewed test/Chrome
Closing
