### ISSUE TITLE
In Test: During Student Application process, add education link freezes page

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4395]
While setting up for testing, during the student application process on the Education & transcript page.  If I click on +Add education nothing happens...here is the error 
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/7feeda21-a2b6-43d1-9ac3-aae1a79f6e35)

**Comment by Kibrahacha67** [comment]
Same issue in UAT.  

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/3ade6c9c-beaf-482e-a3fd-2c87140d9bc5)

**Comment by jhanson12** [comment]
@Kibrahacha67  this is ready for testing.

**Comment by Kibrahacha67** [comment]
1-7-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/20/20 - KWagner tested - ready for final review
