### ISSUE TITLE
Create vanity URL for DOI

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4398]
Who: DOI users
What: Vanity URL for DOI community
Why: So they can market their Bison community

Acceptance Criteria:
- Create a custom URL for DOI: openopps.usajobs.gov/community/DOI
- This custom URL will return back anything that has been created within the Bison Career Network community

Note: The end of the URL could change in the future but need to get something created to start.

**Comment by bmcorum** [comment]
With the completion of #4413 this functionality will be available via the community management UI

**Comment by kbwagner** [comment]
Add manually once 4413 is completed

**Comment by kbwagner** [comment]
Closing - will be done offline
