### ISSUE TITLE
Create custom search page for DOI

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4399]
Who: DOI community
What: Custom search page
Why: so they can see only their Bison Career Network opportunities in one custom search

Acceptance Criteria:
- Create custom search page for DOI/Bison community
- Header should read, "Bison Career Network"
- Subheader should read, "You are now viewing Bison Career Network Open Opportunities only."
- Subtext should read, "WILL ASK ON 1/29"
- Branding will come later in a new ticket

Note: We fully expect some of the text on this page to change in a future ticket but this ticket will create the custom search page as a start.

**Comment by bmcorum** [comment]
With the completion of #4413 this functionality will be available via the community management UI

**Comment by kbwagner** [comment]
Adding hold tag - Add manually once 4413 is completed

**Comment by kbwagner** [comment]
Will be done offline - closing
