### ISSUE TITLE
Allow for office/post to be moved to a different bureau

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4400]
Who: State administrators
What: Ability to move an office/post to a different bureau
Why: in the event of a reorganization

Acceptance criteria:
- When edit is selected on an office/post, the bureau should also be displayed.

https://opm.invisionapp.com/share/U8R4CAV3HXF#/screens/388169633_Open_Opps_-_Add_Office_Or_Bureau_-_With_Modal_-_Edit_Step_2%20(edited)

This will allow users to select a different bureau to move the office/post under

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-28-20 LHammond in testing
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/30/2020 - KWagner tested in Chrome/Test
Closing
