### ISSUE TITLE
Rework open opps footers

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4409]
Who: Open Opps users
What: Rework footers so everything fits and aligns better
Why: to improve visibility

Acceptance criteria:
Rework footers to break apart columns so that the help desk can fit on the same line as the other links
Currently the help desk links are forced to a new line
- All other footer links should stay on one line and the help desk links should appear to the right of them.
- This should occur for regular and state footers

![image (38)](https://user-images.githubusercontent.com/18709918/72909435-0074b200-3d05-11ea-835d-a75f2da81101.png)
![image (37)](https://user-images.githubusercontent.com/18709918/72909441-02d70c00-3d05-11ea-8fda-3c64989c460e.png)

**Comment by nia-johnson** [comment]
Moving to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Atlas/_backlogs?level=Backlog%20items&showParents=false&_a=backlog
