### ISSUE TITLE
Create applicant status pills

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4411]
Who: Student applicants
What: status pills on the landing page
Why: in order to highlight the status

Acceptance criteria:
- Create pills for each applicant status based on the design system: https://usajobs.github.io/design-system/pill/  
- Pill names are in the application status for students section of the help center: https://usajobs.github.io/openopps-help/opportunity/application-status/
- Pill colors should be as follows: 

State applicant statuses:
-  In Progress is yellow, 
- Applied is green, 
- Primary select is green
- Not selected is red, 
- Alternate select (green) (this one is trick so if anyone disagrees on green I'm flexible)
- Completed (green), 
- Not completed (red)
- Not submitted (red)

Non state applicant statuses: 
- Applied - Green
- Assigned  - Green
- Not assigned - Red
- Complete - Green

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-30-20 LHammond in testing
The color for Alternate Select in the AC is green on the page it is Gray.  Also the use of caps in Alternate Select should be "Alternate select".  Sending back to development

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/ebe5e9f8-0370-498a-95d4-5c64ecffe9df)

**Comment by Kibrahacha67** [comment]
1-31-20 LHammond in testing

**Comment by kbwagner** [comment]
2/4/2020 - KWagner reviewed/tested 
Closing
