### ISSUE TITLE
Add applicant status pills to student landing page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4412]
Who: Student applicants
What:  Applicant status pills appear on landing page
Why: To provide visual status

Acceptance Criteria:
- Add student applicant status pills to student landing page.  Currently only the words appear

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/c8a7e11c-9e45-4e90-9a3b-9d4418d2a644)

Related tickets: 
4411 - Create applicant status pills
4412 - Display applicant status pills on student landing page
4329 - Applicant dashboard enhancements
4414 - Add applicant status pills to non student landing page

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-31-20 LHammond in testing

**Comment by kbwagner** [comment]
2/3/2020 - KWagner tested in Test
Pills appear correctly on student landing page
Closing
