### ISSUE TITLE
Updates to community attribute table

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4413]
### Who
Sitewide Admins 

### What
The ability of sitewide admins to customize community attributes. 

### Why
Sitewide admins need to be able to create custom communities that reflect an agency's design specifications

### Acceptance Criteria
The left column will contain the following:
- All existing data fields 
- Add Bureau/Office/Post fields specific to State can display at the bottom as they do now

The right column will contain the following: 
- Add Search display & appearance (follow AC not mock for the title)
- Title field
- Title color - display color selector
- Subtitle
- Subtitle color - display color selector
- Description
- Description color - display color selector
- Banner color
- Vanity URL (follow AC for column order not mock).  Display openopps.usajobs.gov/community/ and then a text box where they can enter the last piece

Note: Logo has been moved to TFS ticket

### Notes
- The search button will be the same as the title color
- For existing communities, leave the colors as the default or selected at this time.

### Related Tickets 
https://github.com/USAJOBS/team-design/issues/158, https://github.com/openopps/openopps-platform/issues/4416

### Mocks
<img width="540" alt="72569380-54584480-3888-11ea-8f6b-37364a0935fc" src="https://user-images.githubusercontent.com/18709918/72951413-40b34f00-3d5c-11ea-950d-c2f0ac856ce1.png">

**Comment by kbwagner** [comment]
@bmcorum wondering if we should break this one down a bit and do we need a new ticket to apply the right hand column wording and text to the search pages?

**Comment by nia-johnson** [comment]
@kbwagner @bmcorum Edited ticket. Let me know if you need me to split.

**Comment by bmcorum** [comment]
Research a way to verify title/subtitle/description color against banner color is 508 compliant

**Comment by jhanson12** [comment]
Are all of the fields optional?

**Comment by kbwagner** [comment]
@jhanson12 I think the new fields can be optional and if nothing is entered they don't get a custom search page.  @bmcorum may disagree with me on that one though once he's feeling better.

**Comment by bmcorum** [comment]
@kbwagner I would agree they should be optional. No value means no custom banner.

**Comment by bmcorum** [comment]
Ready for testing in UAT

**Comment by margaretdumas** [comment]
Mdumas - tested. Moving to review.

**Comment by nia-johnson** [comment]
Tested in Chrome on the Test environment. Moving to Final Review.

**Comment by kbwagner** [comment]
@jhanson12 one weird thing on this - it apears white is the default description color.  So I click on the color wheel and I click on white, and nothing defaults into the box.  I click another color and then white then I get ffffff in the box.  Not a big deal but wondering if the default is white if we should just put the color ffff in the box to avoid confusion?  Haven't tested the rest yet.

**Comment by bmcorum** [comment]
@kbwagner yes the default is white and the color wheel is already set to white so it didn't trigger a color change until you selected a different color and then changed it back to white. Since this field is optional if you never set it to something we don't need to store a value in the database. The code already knows what the default color value is.

**Comment by bmcorum** [comment]
@kbwagner basically trying to prevent having to store redundant data in the database

**Comment by bmcorum** [comment]
@kbwagner if you would still prefer we put the default color code values in the input boxes we will need a new ticket.

**Comment by kbwagner** [comment]
2/21/20 - Kwagner tested in Test/Chrome.
Closing
