### ISSUE TITLE
Add applicant status pills to non student landing page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4414]
Who: Non student applicants
What: Add application status pillls
Why: to provide visual and make the page consistent

Acceptance Criteria:
- Add applicant status pills to the non student landing page

![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/af68fb76-1687-4e91-9926-18cbb2732f52)

Related tickets: 
4411 - Create applicant status pills
4412 - Display applicant status pills on student landing page
4329 - Applicant dashboard enhancements
4414 - Add applicant status pills to non student landing page

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-31-20 Lhammond in testing
Testing completed moving to review.

**Comment by nia-johnson** [comment]
Tested on Chrome in the Test environment. Moving to Final Review.

**Comment by kbwagner** [comment]
2/3/2020 - KWagner tested Chrome/Test
Closing
