### ISSUE TITLE
Manager User page revamp

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4415]
Who: Sitewide administrators
What: Revamp view of manage users
Why: Too many fields is causing the need to scroll

Acceptance Criteria:
- when a sitewide administrator clicks on manage users, the following will display:
Name, agency, federal email  and login.gov email (federal and login can be stacked if needed), user type icon (with hover text), last login, and an icon to click on for account settings.
Note: mock does not have email on the main page but it should be added.
- if the gear icon is selected, a subpage will appear with the following information: 
Account settings header
User name
User type
Federal email
login.gov email
Last login
Create date
A blue section on the right will display a heading of Account setting and the toggles for Account enabled, Sitewide approver, Sitewide admin

- Sort by should work as it does now whether the value is display on the main card or sub-card

Main page mock: 
<img width="613" alt="72863026-1babd700-3c9d-11ea-9cba-b59ac983e20f" src="https://user-images.githubusercontent.com/18709918/72951234-ace18300-3d5b-11ea-9f97-aee262f12b49.png">

Secondary page mock: 
![72863292-1a2ede80-3c9e-11ea-91db-ba29000ede47.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/f86963c7-f62b-4105-ad54-52f07a553190)![72863026-1babd700-3c9d-11ea-9cba-b59ac983e20f.png]

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41558&_a=edit
