### ISSUE TITLE
Add Preview Button in Admin Panel

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4416]
### Who
Sitewide Admins

### What
Add the ability for sitewide admins to preview their changes to a particular community

### Why
Sitewide admins need to access whether our not their selection is 508 compliant, aesthetically pleasing and/or easy to read before saving the changes. 

### Acceptance Criteria
- Add preview button to the right-hand panel at the bottom 
--When clicked, open a new window/modal to display the information in the right-hand column as a mock search page with the selected colors 

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4413, https://github.com/USAJOBS/team-design/issues/158

### Mocks
<img width="540" alt="72569380-54584480-3888-11ea-8f6b-37364a0935fc" src="https://user-images.githubusercontent.com/18709918/72951413-40b34f00-3d5c-11ea-950d-c2f0ac856ce1.png">

**Comment by bmcorum** [comment]
Ready for testing in UAT

**Comment by margaretdumas** [comment]
Mdumas - Tested. Moving to review

**Comment by nia-johnson** [comment]
Tested in Chrome in the Test environment and passed. Moving to review.

**Comment by kbwagner** [comment]
2/21/20 - Kwagner tested - closing
