### ISSUE TITLE
Email to internship creators to complete the process

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4419]
### Who
Who is this ticket for? Who are the stakeholders?

### What
Enter goal(s) that the user wants the product to accomplish or implement.

### Why
Enter the reason(s) why the user needs the feature or functionality.

### Acceptance Criteria
Email to State internship creators to notify them to close the internship

### Related Tickets 
n/a

### Mocks
n/a

Email attached
[Department-of-State-student-internship-program-close-internship-hiring-manager_v2_20200123 (2).docx](https://github.com/openopps/openopps-platform/files/4104606/Department-of-State-student-internship-program-close-internship-hiring-manager_v2_20200123.2.docx)

On hold until we have confirmation from State

**Comment by nia-johnson** [comment]
Closed. Moved to TFS. https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41176&_a=edit
