### ISSUE TITLE
508 issues from the recent scan 

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4421]
Scan test report id 434447
Several pages tested during this test resulted in issues.  The report was distributed to the team for specifics.  Pages tested were:
Profile 5 issues
Search 9 issues
Sitewide-manage user 10 issues
Sitewide - landing 4 issues
DOS - manage - members 3 issues
Sitewide - metrics 30 issues
opportunity - edit  4 issues
DOS - Manage_members_bic 0 issues
create cycle 0 issues
create opportunity 0 issues
Issues range from 3  (minor) to 10 (major) run from and assigned by AMP, if there are any questions please contact Larry Hammond

**Comment by kbwagner** [comment]
@raywilliams I know you've been working on this ticket. Should we go ahead and move this one to TFS and close it here? Didn't want to mess you up. (@nia-johnson)

**Comment by kbwagner** [comment]
TFS 41657
