### ISSUE TITLE
In production: Sitewide adman page, Users Manage total active users has space between number a comma

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4422]
### Who
Sitewide Admins 

### What
Add space between a comma and the next character for numbers greater than 1000. Currently there is no space, as shown below. 

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2dc8e8fe-5335-4ac9-bda6-662a1286fd69)

All other numbers are rendered correctly

### Why
For aesthetic consistency within the Open Opps platform 

### Acceptance Criteria
- Numbers greater than 1000 on the site wide admin page are displayed with a space after the comma 

### Related Tickets 
None 

### Mocks
None

**Comment by kbwagner** [comment]
Moved to TFS 41487
