### ISSUE TITLE
Bug: Image size for User Type on manage users page sitewide do not maintain size.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4441]
### Environment
Test

### Browsers
Chrome, Edge, and IE 

### Steps to Replicate
1. Log in as a Sitewide admin
2. Navigate to the Manage users page.
3. Sort by Sitewide Admin
4. Page through users and watch the images in the User Type column change sizes

### Expected Results
User type icon size maintains 

### Actual Results
User type icon size changes sizes 

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/04e63236-42b2-4e25-9a30-ab01df758aed)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/0e3ad86a-170a-4397-b532-04a540632838)

**Comment by nia-johnson** [comment]
@kbwagner @Kibrahacha67  I don't see this in Test. I went through three pages of users.

**Comment by kbwagner** [comment]
@Kibrahacha67 can you confirm whether you still see this issue?

**Comment by Kibrahacha67** [comment]
Yes.

**Comment by Kibrahacha67** [comment]
I can.

**Comment by kbwagner** [comment]
Thanks!  Just making sure before we move it to TFS.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41542&_a=edit
