### ISSUE TITLE
BUG: Home Page - Read more link in the Latest achievements section overlaps the image for user.

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#4448]
### Environment
Test

### Browsers
IE Edge Chrome FF

### Steps to Replicate
1. Log into Open Opps
2. If not on the homepage, click on your name on the top right of the screen 
3. Scroll to the Latest achievements section on the Home page on the right side of the screen 

### Expected Results
Image doesn't overlap with the "Read More" link 

### Actual Results
Image overlaps with the "Read More" link as shown below in IE and Chrome 
![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/35c26d4f-fd1c-4e5f-bc4b-7672a192f5c7)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/7fb5b9ff-81bc-4b23-9fca-65526454b65b)

**Comment by kbwagner** [comment]
TFS 41178
