### ISSUE TITLE
Create/Edit Opportunity Page for DOI

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4449]
### Who
DOI Open Opps users 

### What
Adjust Create Opportunity page to meet DOI's specific requirements 

### Why
In order for DOI to display the information necessary to advertise details on Open Opps

### Acceptance Criteria
Users should be able to do the following while creating or editing a DOI opportunity: 

The following changes are for the create/edit template as a whole: 
- Rename due date to  "What is the estimated completion date?" 
- Rename Part time to Part time detail and modify the icon (see mock)
- Add a new icon for full time detail
- Allow for multiple selections in the Series field regardless of whether it's a detail or not

View the following additional fields only when part time or full time detail is selected. 
--> We're not creating a new template but making the existing template have new information display when part time or full time is selected
- Indicate whether the host agency is willing to reimburse the employee’s parent agency for a given opportunity done
- View new “up to 50% of the work week” verbiage 
- limit participation to agency will no longer be grayed out, the box can still be checked as a default but can be changed.
- Make a text entry in the field for "Requirements", needed training, safety risks and disclosures text box.  (optional field)
- Make an entry in the Pay Plan and Grade field (required fields)
- Pay Plan should be pulled from the table created in 4463.  Only display the code (i.e. GS). 
 Default to GS
- Make an entry in the "How to Apply" field (optional field)
- View whether each new field is required or optional.
- View character countdown for Title, Introduction, What You'll Do fields and How to apply and 
Requirements fields

### Related Tickets 
https://github.com/USAJOBS/team-design/issues/169, https://github.com/openopps/openopps-platform/issues/4453

### Mocks
https://opm.invisionapp.com/share/ZRVQ4C6J6QP#/403191334_Create_-_Ongoing
https://opm.invisionapp.com/share/ZRVQ4C6J6QP#/403205960_Create_-_Part-Time_Detail

**Comment by kbwagner** [comment]
@nia-johnson I added in the links to the mocks.  but can you please make the following updates:
- spell out the name of the renamed due date  -  I believe "Estimated completion date" is where we landed
- Make it clear that if part time or full time detail is selected is the only time the additional fields show
- For any new field list whether its required or optional.  For any larger text field like how to apply, indicate the size of the field and add the display of the character limitation to the field with a character countdown to be consistent.  
- The prerequisites box is called "Requirements" according to the mock
- In general spell out the mock in the AC wherever you can.
Thanks!
-

**Comment by nia-johnson** [comment]
@kbwagner Made the changes. Check the part time/ full time requirements to see if that's what you're getting at.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - In testing....

**Comment by margaretdumas** [comment]
Moving back to development for changes in the AC.  Also please add a space after "up".  ![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/37669dba-03c7-44d6-8e04-b8c6c4958213)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - testing completed. Moving to review.

**Comment by kbwagner** [comment]
2/21/20 - KWagner tested in Chrome/Test
Closing
