### ISSUE TITLE
Add Auto Join Toggle on Create/Edit Community Page

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4451]
### Who
Site wide Admins

### What
Make it possible to automatically add Open Opps users that fit the prerequisites of a closed community

### Why
To make sure that users have access to the communities they are eligible for 

### Acceptance Criteria
The user should be able to do the following: 
- View auto-join toggle on the Create/Edit Community page 
- Switch toggle on/off 

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4452

### Mocks
None

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - testing

**Comment by nia-johnson** [comment]
Passed in Test environment on Chrome. Moved to Final Review.

**Comment by kbwagner** [comment]
2/21/20 - KWagner reviewed in test.  Closing
