### ISSUE TITLE
Auto-Join Functionality

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4452]
### Who
Sitewide Admins

### What
The functionality behind the auto-join toggle in the Create/Edit Community panel 

### Why
So the system knows the conditions by which to automatically add/remove a user from a closed community

### Acceptance Criteria
- If the auto-join toggle is on for a closed community and there is an individual user who is in the same agency/department as the closed community,  the next time they log into Open Opps, they are automatically added to the community 
- If the auto-join toggle is on for a closed community and there is an individual user in the closed community that who is no longer in the same agency/department as the community, the next time the user logs into Open Opps, they are automatically removed from the community
- If the auto-join toggle is off and the above happens, nothing changes

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4451

### Mocks
None

**Comment by bmcorum** [comment]
@nia-johnson I think the requirement needs to be defined in the AC. @kbwagner, I believe the requirement is that the user belongs to the same agency or department that the community is assigned to.

**Comment by nia-johnson** [comment]
@bmcorum i left that open ended to be inclusive of all possible ways a closed community could restrict members. It would be easier to deal with if we encounter a community that wishes to restrict members by criteria that doesn't include agency or department.

**Comment by bmcorum** [comment]
@nia-johnson if an additional requirement come up we would need a new ticket. Currently there is no way to test the AC because there is no defined requirement at this point, and there is no way for a community to set their own requirements. At this point the only requirement is business case rule and thus should be defined in the AC.

**Comment by nia-johnson** [comment]
@bmcorum This ticket covers auto-join. It doesn't cover users setting requirements for a closed group. In fact, this is the first time I've heard that there isn't functionality to create a closed group. Given that is the case, that needs to be another ticket, which I can link to this one.

**Comment by nia-johnson** [comment]
@kbwagner I thought users setting requirements for closed groups was completed functionality. Does this ability currently not exist in Open Opps?

**Comment by bmcorum** [comment]
@nia-johnson we currently have all functionality and support for creating closed communities. This ticket is supposed to be adding functionality based on a newly identified business case specifically for automatically adding users as members to any closed communities that are within the same agency or department.

**Comment by nia-johnson** [comment]
@bmcorum I understand that. However, since this business case has been identified, we have to at least discuss how this could affect closed groups with other parameters - since users have the ability to create such groups, will auto-join be available to them as well? This is a call that needs to be made by @kbwagner

**Comment by bmcorum** [comment]
@nia-johnson, As far as I know the only requirement that has been identified is auto joining based on same agency/department. Agile is about iteration so we code what we know, not what we think may or may not happen in the future. Again, based on how this is written it cannot be tested and therefore will not be committed to.

**Comment by bmcorum** [comment]
Yes, any other closed community who decided to turn on the auto join feature would work exactly the same as the identified business case which is to automatically add new members based on agency/department. If we later defined a new need we then implement the new need which will most likely also require us to collect additional information which we do not collect today to implement a new requirement.

**Comment by nia-johnson** [comment]
@bmcorum I'm not implying that we should develop for all possible constraints right at this moment because Agile is about iteration, but it's also about thinking about functionality as a vertical slice. There is a very real possibility that another business case for auto-join can be identified and to mitigate future refactors, possible implementation risks should be discussed (not committed to) between me, you and @kbwagner.  

I'll re-write the requirements so you can pick this up.

**Comment by bmcorum** [comment]
@nia-johnson that is fine if you are concerned about future iteration, but then you also would need to have defined the functionality for how a community manager would define these supposed new business case rules in the UI which we do not have and therefore cannot possibly write code around a open ended requirement that cannot be defined by an end user.

**Comment by nia-johnson** [comment]
@bmcorum You said that there is functionality so that users can create closed groups. Are they able to create groups using criteria that is not agency/department? If so, wouldn't the users already be creating these business rules to begin with?

**Comment by bmcorum** [comment]
@nia-johnson closed communities functionality is used to prevent non member from posting opportunities to that community; that is all that functionality does. In order for a user to post to a closed community they would need to email a community manager who then needs to log in and invite them to the community. DoI has 1000s of employees that would need to be added manually (invited) to their new community if they make it a closed community. We identified a new business rule that would allow closed communities the option enable an auto-join feature that would add any users that belong to the same agency/department of the community as members to alleviate extra work for community managers.

**Comment by nia-johnson** [comment]
@bmcorum Okay. So there is no way for a user to set criteria to bar users from posting? It's either open or closed and in the latter case, it must be manually done, correct?

**Comment by bmcorum** [comment]
@nia-johnson the only way to currently bar users from posting into your community it to make it a closed community which requires that the user join your community by being invited by a community manager.

**Comment by bmcorum** [comment]
@nia-johnson the only piece of information we currently require and collect about a community that is also part of user profiles is agency. So at this point it is the only matching point of data that we can code around. If at some point in the future another need is identified it will require collecting another matching data point. All of this would require new tickets.

**Comment by nia-johnson** [comment]
@bmcorum I get it now. Thank you for your patience. I'll change the ticket. @kbwagner Do you think a it's worth creating a ticket that 1) allows users to bar users from posting communities using specific criteria 2) enables auto-join based on that criteria? If so, I can make that and put it at the bottom of the TFS backlog under customer experience.

**Comment by kbwagner** [comment]
@nia-johnson sorry I didn't get to these until today but sounds like it's been worked through.   I don't think we need those new tickets now as we really have no idea of what people want in the future.  If it comes up, we can add it. Thanks.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - Passed testing. Moving on to review

**Comment by nia-johnson** [comment]
Tested in Chrome. Passed in Test environment. Moving to Final Review

**Comment by kbwagner** [comment]
Tested in Test
Closing
