### ISSUE TITLE
View DOI Opportunity 

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4453]
### Who
DOI Open Opps Users 

### What
View DOI specific opportunities in the DOI community 

### Why
DOI users need to be able to see individual opportunities in detail. 

### Acceptance Criteria
The user should be able to view all existing opportunity fields in addition to the following if provided (part time and full time details only)
 - "How to Apply" Section
- Pay Plan fields
- Grade fields (blue box)
- Requirements field (located under the description fields)
- Reimbursable (blue box) - if no is selected, still display but with a "No" after the field label

For all opportunities including non details: 
- If multiple series selected  they will all display in blue box separated by a comma
- Change the "Due date" label to be "Estimated completion date"

Note: Future tickets will request the department/office logo of the creator displays in place of the profile picture for DOI opportunities.

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/4449

### Mocks
https://opm.invisionapp.com/d/main?origin=v7#/console/19275869/403419532/preview?scrollOffset=481

**Comment by kbwagner** [comment]
@nia-johnson a few comments: 
- prerequisite is called Requirements
- Point out which fields will only display if part time/full time is selected and will be not displayed otherwise (requirements, how to apply, reimbursable)
- point out multiple series, if selected, will display separated by a comma since that's an addition in blue box
- Reimbursable will display in blue box

**Comment by nia-johnson** [comment]
@kbwagner Done

**Comment by kbwagner** [comment]
@nia-johnson I don't think your changes saved but I went ahead and threw the updates in and it's approved. Thanks.

**Comment by nia-johnson** [comment]
@kbwagner Yikes. Thanks.

**Comment by tanichacko** [comment]
@nia-johnson   don't have access to this link
 https://opm.invisionapp.com/d/main?origin=v7#/console/19275869/403419532/preview?scrollOffset=481
Can you share public link for this mock ?

**Comment by kbwagner** [comment]
@tanichacko try this: https://opm.invisionapp.com/share/ZRVQ4C6J6QP#/403419532_State_-_Opportunity_-Desktop-

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - moving back to development.  All fields required in AC are not displayed on View.  Fields missing are :  
. "How to Apply" Section
•  Pay Plan fields
• Grade fields (blue box)
• Requirements field (located under the description fields)
• Reimbursable (blue box)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - testing completed

**Comment by margaretdumas** [comment]
Mdumas - Posed question as to whether Reimbursable should show is "No" is selected to slack channel.  If the answer is that it should display in the blue box regardless of what is selected then the ticket need to be moved back to development for more work.  It currently only displays with a "Yes" selection.

**Comment by kbwagner** [comment]
@tanichacko sent back per conversation above with Margaret that if reimbursable is "No" still display it on the view.

**Comment by bmcorum** [comment]
Ready for testing

**Comment by margaretdumas** [comment]
Mdumas - Verified Reimbursement option displays in blue box regardless of answer selected.  Moving back to review.

**Comment by kbwagner** [comment]
2/21/20 - Tested in Chrome/Test
Closing
