### ISSUE TITLE
Alphabetize All Dropdown Menu Selections 

### ISSUE THREAD

**Issue by nia-johnson** [openopps/openopps-platform#4456]
### Who
Open Opps Users 

### What
All possible sections within a dropdown menu are ordered alphabetically 

### Why
To improve usability of the Open Opps platform 

### Acceptance Criteria
The selections in the following dropdown menus Need to be alphabetized:
- Create / Edit  Opportunity Page 
   - Country (Internships) 
   - Suggested Security Clearance (Internships)  
- Admin Dashboard 
   - Agency (Under Agency Tab) 
   - Community (Under Community Tab) 
- Search 
   - Community 
   - Sort By (Under People Tab) 

The following are already Alphabetized (no change):
- Create / Edit  Opportunity Page 
   - Who 
   - Bureau  (Internships)
- Profile 
  - Bureau
- Admin Dashboard 
   - Period (Under Sitewide / Agency / Community Tab) 
- Search 
   - Career Field 
   - Bureau (Under Internship Tab) 

### Related Tickets 
None 

### Mocks
None

**Comment by kbwagner** [comment]
@nia-johnson some of these are already alphabetized - like career type in search.  Can you go through and note the ones that need to be done by development to save them some time?  Fine to note the other ones that are already complete for tracking.

**Comment by nia-johnson** [comment]
@kbwagner Done

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41548&_a=edit
