### ISSUE TITLE
Search updates for details/DOI

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4457]
Who: All Open Opps users
What: Ability to search on part time and full time details
Why: in order to improve their search experience

Acceptance Criteria:
- In the Time Commitment section of the search filters, add a new option for Part time detail above Full time detail
- If either part time or full time detail is selected, display another search option for Pay Plan Grade.
     - Pay Plan should be a list of valid values from the table.  
     -  Grade can be a free form box but entering 08 or 8 should both search against a grade 8.  
     - Restrict grade entry to 2 characters. 

Related tickets:
4449 - Create Opportunity updates for DOI

Mocks:
None

**Comment by bmcorum** [comment]
Don't forgot to update the elastic task mapping and search query

**Comment by kbwagner** [comment]
TFS 41647
