### ISSUE TITLE
Pull Pay plan from USAJOBS through API

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4463]
Who: Part time/full time detail users
What: pull pay plan from USAJOBS
Why: So it can be used in identifying detail opportunities

Acceptance criteria:
- Pull the pay plan table from USAJOBS through the API 
- Create a table to store the data in Open Opps
- Only the 2 character code of the pay plan should display in the system (i.e. GS)
- The pay plan will display in Create Opportunity and search filters for part time and full time details (separate tickets)

**Comment by bmcorum** [comment]
Partial table view of imported pay plan codes

![image](https://user-images.githubusercontent.com/1165615/74741920-b01d4100-522b-11ea-9ff4-d67731e1aab2.png)

**Comment by bmcorum** [comment]
See attached data artifact above

**Comment by margaretdumas** [comment]
Mdumas - Moving to review.  Artifact is attached

**Comment by kbwagner** [comment]
2/19/20 - Reviewed and closing
