### ISSUE TITLE
Bug -- Who maintains this repo in website footer

### ISSUE THREAD

**Issue by tallguyjenks** [openopps/openopps-platform#4506]
![image](https://user-images.githubusercontent.com/29872822/102674106-a0bb9c80-4149-11eb-8ab8-023044eb75f2.png)

Hyperlink also routes to local host port 4000 instead of perhaps a particular user/organization on github or an official `.gov` website

**Comment by tallguyjenks** [comment]
moving to the dev branch, issue is present across both branches.

**Comment by bmcorum** [comment]
Link updated to [https://usajobs.github.io/openopps-help/](https://usajobs.github.io/openopps-help/)
