### ISSUE TITLE
Search should AND and not OR.

### ISSUE THREAD

**Issue by polastre** [openopps/openopps-platform#48]
Search currently OR's together all the requests.  It should AND them, at least for the tags, such that the only things shown are projects that match all tags.

There's a lot more to do in search, but just wanted to document this point.

**Comment by ultrasaurus** [comment]
The expected behavior is that if you add a tag, it would refine the search (causing fewer results, not more).

**Comment by ultrasaurus** [comment]
The expected behavior is that if you add a tag, it would refine the search (causing fewer results, not more).

**Comment by kbwagner** [comment]
Closing per backlog review.  Will look at search as a whole down the road.
