### ISSUE TITLE
when I click on a link in opportunity description, it should open in a new window or tab

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#636]
On an opportunity detail page:
![image](https://cloud.githubusercontent.com/assets/41906/6561232/ca4ac3ce-c64c-11e4-9085-2226a9ed437a.png)

I expected the link to go to a new tab or window

**Comment by Sujakosa** [comment]
Hello, Ultrasaurus. Try making the target of the link blank. A blank-target usually opens a new window. I hope that helps.

**Comment by ultrasaurus** [comment]
@Sujakosa yep.  I know how to do it -- just need time to hunt down where it is in the source code and make the change.  I thought this might be a fun thing for someone new to the project!

**Comment by awhig** [comment]
Markdown doesn't let you put a target attribute on the link.

One option is to use some jQuery to set a blank target on any links on the page that link out of the site. Would that work?

$(document.links).filter(function() {
    return this.hostname != window.location.hostname;
}).attr('target', '_blank');

If that's too wide, then maybe only do that to links that are inside of the description div.

<div class="task-show-description">
</div>

http://stackoverflow.com/questions/4425198/markdown-target-blank

**Comment by awhig** [comment]
@dhcole Would the above solution work for you?

Rich
