### ISSUE TITLE
In Browse Tasks, I should see what state the Task is in

### ISSUE THREAD

**Issue by brandtheisey** [openopps/openopps-platform#638]
On the Browse Task page, there is no indication of what state a task is in, making a listing with multiple task states very confusing. 

The cards should have some kind of state indicator that says which state a task is in.

**Comment by LisaLNelson** [comment]
completed through filters
![screen shot 2017-09-12 at 1 46 22 pm](https://user-images.githubusercontent.com/9039852/30340548-df1e195c-97c0-11e7-9f53-4c173740c605.png)
