### ISSUE TITLE
As a developer, I'd like to be able to deploy to Heroku.

### ISSUE THREAD

**Issue by imf** [openopps/openopps-platform#677]
I'll work on this. Need to convert the big readme setup to something that can more readily be done by git push heroku master.

**Comment by dhcole** [comment]
Here's how we build our production server:

https://github.com/18F/midas-cookbook/blob/devel/recipes/app.rb

In general, I think we'd just need to configure heroku to set up a postgres db, run `npm install` to set up the dependencies, and run `npm run migrate && npm run init` to set up the DB for the first time.

Then the server should start with `node app.js --prod`

**Comment by jcontini** [comment]
Hi all, just wanted to +1 this request. Midas seems like a great app for an idea/ innovation marketplace and I'm planning on piloting it at my organization in a few weeks. Would love to host on Heroku's free tier. Cheers.

**Comment by ultrasaurus** [comment]
Not against this, just not specifically on our roadmap.  There are a lot of hosting platforms with a free tier now, so don't want to specifically call out Heroku.
