### ISSUE TITLE
Improve test data

### ISSUE THREAD

**Issue by sefk** [openopps/openopps-platform#712]
If the team made better test data available to open-source contributors then we would do a better job making sure our features worked well once they landed. 

Requirements
- **Breadth of data** - best for the test data to include all the interesting ways the site is being used, e.g. odd dates, missing fields, non-latin characters, different data sizes, etc. The best way to get this would be to take production data and remove sensitive info (names, email addresses, etc.) if possible.
- **Size** - the data set should be the size we want to build for, ideally 2x-10x the current size. Measured across relevant axes, like 10x number of users, 10x number of tasks, 10x comments, etc.
- **Corner cases** - nice to have the real-world data augmented by corner case data. I'm thinking of unicode characters in all fields, giant data sets, etc.
- **Optional** - would be nice to have this done as a fixture that could be loaded into a database and then re-loaded when needed.

**Comment by ultrasaurus** [comment]
@sefk this is a great description of the need for additional test data.  Thanks so much for writing it up!

**Comment by LisaLNelson** [comment]
Not a priority until we have more new contributors to Open Source.

**Comment by Piglady64** [comment]
Brice will work on this. Closing
