### ISSUE TITLE
Submit button is in wrong place when adding Project owners from Edit Project screen

### ISSUE THREAD

**Issue by brandtheisey** [openopps/openopps-platform#715]
If you go to add a Project Owner the css allows the submit and cancel buttons to be unaligned:
![screen shot 2015-04-15 at 4 11 35 pm](https://cloud.githubusercontent.com/assets/7915386/7168286/4025ef60-e38a-11e4-8e33-8eb7962abc9c.png)

At smaller screen resolutions (less than 1200px wide)they are at least next to each other:
![screen shot 2015-04-15 at 4 20 20 pm](https://cloud.githubusercontent.com/assets/7915386/7168422/521c74b8-e38b-11e4-81dd-2aa726cedeb6.png)
At the smallest (less than 768px wide) they behave correctly:
![screen shot 2015-04-15 at 4 18 42 pm](https://cloud.githubusercontent.com/assets/7915386/7168396/233d2502-e38b-11e4-9ff2-f5c5dc75cece.png)

These are all in chrome on a mac.

**Comment by ultrasaurus** [comment]
Projects / Working groups removed in 0.10.0 release
