### ISSUE TITLE
Project uses the default Sails favicon

### ISSUE THREAD

**Issue by ascott1** [openopps/openopps-platform#722]
Currently the project is using the default Express favicon:

![screen shot 2015-04-17 at 12 07 24 pm](https://cloud.githubusercontent.com/assets/212533/7205873/72a1a2f6-e4fa-11e4-9302-1872e401a746.png)

It should probably use the DigitalGov one instead:

![screen shot 2015-04-17 at 12 08 46 pm](https://cloud.githubusercontent.com/assets/212533/7205888/8a7adff0-e4fa-11e4-96e7-df0eae85abe2.png)

**Comment by dhcole** [comment]
Good catch. This would require setting up a `favicon.ico` image in the `/assets/` directory of the Open Opportunities theme repo: https://github.com/18F/midas-open-opportunities

#helpwanted

**Comment by ultrasaurus** [comment]
this is even stranger now that it is a sailboat!

**Comment by rogeruiz** [comment]
Closed in light of #1378
