### ISSUE TITLE
As a visitor to /tasks, I expect to see better use of space

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#732]
Weird break-point here when re-sizing on desktop, I would expect the filter to tuck itself under the search field until it gets within left-margin of the task cards:
![image](https://cloud.githubusercontent.com/assets/41906/7281266/5fbb1924-e8dd-11e4-9233-5f30bb929c1f.png)

instead I see this:

![image](https://cloud.githubusercontent.com/assets/41906/7281357/fcca5568-e8dd-11e4-8872-8705b6d98fda.png)

**Comment by LisaLNelson** [comment]
Does not appear to be an issue any more.
