### ISSUE TITLE
Email text should be able to be "internationalized" 

### ISSUE THREAD

**Issue by brandtheisey** [openopps/openopps-platform#745]
Currently none of the emails make use of the internationalization functionality that the rest of the app uses (i18next). This leads to the texts being over generic and/or allows it to make reference to specific deployments.

**Comment by jeremiak** [comment]
I realize this issue is old but I'm running into this fun bit of internationalization and would support a bit clearer naming convention for these files. Currently, I'm not quite sure the difference between `/assets/locales/en/translation.json` and `/assets/locales/en-US/translation.json` :confused:

**Comment by dhcole** [comment]
We should simplify this to use only one translation file that other users (like Crowdworks) can override.
