### ISSUE TITLE
Add AUTHORS file

### ISSUE THREAD

**Issue by sefk** [openopps/openopps-platform#760]
It'd be nice for everyone who contributed to this project (cough, cough) to have their name on it somewhere. How about a sequential list in an AUTHORS file? We should start with the original folks and then whenever people make their first contribution, that commit should have their name appended to the end of AUTHORS too.

**Comment by ultrasaurus** [comment]
I have historically just used the [contributors](https://github.com/18F/midas/graphs/contributors) for this, but have been a little bothered that the designers don't get listed that way.  I recently heard about [humans.txt](http://humanstxt.org/) which could also serve this purpose.

**Comment by sefk** [comment]
I meant to bring this up at retrospective today. @ultrasaurus is a bit ambivalent. What say you @brandtheisey and @dhcole ?

**Comment by brandtheisey** [comment]
I don't have a strong feeling about this, but I guess that's because I'm unclear how it will be used.

**Comment by clairesarsam-wf** [comment]
I think it's a good idea! Designers and people who report issues are important to any project. And, it seems unlikely now, but it's a possibility that one day something other than Git/Github will be used, and the contributors page won't roll over. I remember hearing DHH talk about how Rails has maintained a contributors log from the beginning, so when they moved from cvs to svn to git, they still had a record from the beginning of the project.

**Comment by csarsam** [comment]
I think it's a good idea! Designers and people who report issues are important to any project. And, it seems unlikely now, but it's a possibility that one day something other than Git/Github will be used, and the contributors page won't roll over. I remember hearing DHH talk about how Rails has maintained a contributors log from the beginning, so when they moved from cvs to svn to git, they still had a record from the beginning of the project.

**Comment by sefk** [comment]
@brandtheisey -- it's a way to show who worked on the project. Good for the project to show contributors, good for the contributors so they "get credit" for their work. It's not a big thing but worth doing IMO. Someone would need to just get it started.

**Comment by brandtheisey** [comment]
Can someone show me an example of an AUTHORS file that includes people who don't submit PRs or code?

**Comment by dhcole** [comment]
@gbinal what's your take on this? I think what we should do should match the general pattern of other 18F projects.

**Comment by gbinal** [comment]
Hmmmm...  

Well, it's not a norm with 18F and, given the manual nature of the maintaining it, probably won't become one anytime soon.  I haven't worked on any projects where they standardized doing this, but it doesn't hurt.
