### ISSUE TITLE
As a user I was confused how to log in with MyUSA

### ISSUE THREAD

**Issue by jtag** [openopps/openopps-platform#767]
It took me about 5 seconds to understand the Log in with MyUSA was a button OR I could create an account. I saw the MyUSA 'button" as a logo in a box.  The only button I perceived was the sign in button.

xo, Jtag

![screen shot 2015-05-05 at 10 20 52 am](https://cloud.githubusercontent.com/assets/339243/7478615/c9d1e99a-f310-11e4-8a07-2e3f97144a8a.png)

**Comment by ultrasaurus** [comment]
This was actually discovered in the early MyUSA usability testing that @dutchashell but we never captured it as an issue.  

thanks so much @jtag for writing this up with a screenshot and everything!

**Comment by dhcole** [comment]
:+1:

**Comment by jackiekazil** [comment]
This came up as an issue when I was demoing the MyUSA integration today. I was going to create a ticket, but then I found this one. :-)

**Comment by mkhandekar** [comment]
We're actively working on this in [myusa issue 617](https://github.com/18F/myusa/issues/617) @jtag @ultrasaurus @dhcole!

**Comment by awhig** [comment]
I think most sites make it clear that these are alternate logins by putting an OR in between the various login options.

See

https://accounts.spotify.com/en/login?continue=https:%2F%2Fwww.spotify.com%2Fus%2Faccount%2Foverview%2F

**Comment by esgoodman** [comment]
Work on MyUSA is frozen now. @jackiekazil how might we best respond to this issue?

**Comment by jackiekazil** [comment]
@esgoodman it my understanding that we supporting current functionality for midas but not making any updates at this time. That being the case --- this issue should be closed OR iceboxed.  

@jroo - Does this sound right to you? (Please chime in.)

**Comment by GailSwanson** [comment]
What direction are we taking this @dhcole? Should this issue be revised?

**Comment by ultrasaurus** [comment]
yeah, let's hold on this till we have more visibility on what federal government single-sign-on options are going to be supported
