### ISSUE TITLE
As a user, I want to be able to contact someone I discover via the people interface

### ISSUE THREAD

**Issue by sefk** [openopps/openopps-platform#782]
One of the use cases for people (see #673) is to discover other Midas users. But once you find someone, you need to be able to contact them. But how? We need to be thoughtful about the use cases. Here are some considerations when designing this:
- Do we want contact mediated through the product (like linked-in mail) or facilitate direct contact via your own email? 
- Should we expose email addresses? Concern about address harvesting by spammers
- Maybe an intro workflow? For example: person A requests to contact person B, email to B asking if OK to give email address to A, if you say OK then close-the-loop email back to A (cc'ing B?) saying here you go.

Personally I would recommend agains doing anything that would take Midas down the path of implementing a messaging system. LinkedIn does this, and poorly, and we wouldn't even do it as well as them.

**Comment by arena** [comment]
I like the way GitHub does this... there is no messaging system, there is not contact affordance at all.. but being resourceful people usually figure it out. ...and, in Midas, there are a bunch of good clues, like agency, name, maybe a link to linkedin.

**Comment by sefk** [comment]
GitHub does show me email addresses, for some people at least. For example,
I don't see yours Arena: https://github.com/arena, but I do see Claire's:
https://github.com/csarsam. I guess it's just opt-in?

**Comment by arena** [comment]
An opt-in system is interesting. I think I like it. ...a bunch of optional fields that people can fill in if they like the idea of getting email ...or leave blank if they like being mysterious (like me). :)

**Comment by dhcole** [comment]
I think we should avoid building any sort of user-to-user mailing system unless we want to make that a first-class feature of the platform. Giving users the permission to opt-in to displaying their email address on their profile (which is already only available to logged in users) makes sense to me though and seems like it gets at this intent.

**Comment by ultrasaurus** [comment]
adding design tag to make clear that this needs design -- conceptual design, as well as visual/interaction design

**Comment by kbwagner** [comment]
5/18/18 - @LisaLNelson I believe this can be closed.  You can now click on the email in the profile from the People interface.

**Comment by LisaLNelson** [comment]
Contact email addresses  can be found on profiles. approve to close
