### ISSUE TITLE
Update Email Comment Notification Rules

### ISSUE THREAD

**Issue by brandtheisey** [openopps/openopps-platform#783]
### Who
Open Opps Users 

### What
Updated email comment notification rules 

### Why
To decrease the number of irrelevant email notifications sent to users 

### Acceptance Criteria
The following should happen: 
- Comment authors will not be notified of the posting of their own comments 
- The users who have already replied to a thread and author of the original comment will be notified of subsequent replies to the thread 
- Authors of top level comments (non-replies) will be notified of subsequent top level comments 

### Related Tickets 
https://github.com/openopps/openopps-platform/issues/2275, https://github.com/openopps/openopps-platform/issues/2194, https://github.com/openopps/openopps-platform/issues/2184

### Mocks
None 

### Old Requirements 
Currently a comment author can get an email informing them that they have just commented in their own opportunity. 

--notifications should exclude comment authors from being notified that they just commented.
  Places to look:
 a) project / task owner audience(s)
 b) replied to a comment audience

**Comment by kbwagner** [comment]
Would like to rework comments work

**Comment by kbwagner** [comment]
TFS Ticket 41482 https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=41482&_a=edit
Entered in TFS - closing
