### ISSUE TITLE
People view: add zoom and pan to map

### ISSUE THREAD

**Issue by sefk** [openopps/openopps-platform#798]
Current world-scale map will be difficult for many use cases
- us-centric team -- then the rest of the world is irrelevant
- key parts of the team in a tight cluster, i.e. US Northeast. In that case selecting and/or hover will be difficult
- viewing anything on a small screen

Would be nice to zoom by either +/- buttons when viewing on a normal screen, and a pinch gesture when on a phone/tablet.

**Comment by austinkeeley** [comment]
It looks like the current map is just a static vector graphic. We could swap this out with a real GIS map. I have some experience with Leaflet and OpenLayers. I could build out a prototype and try to have it maintain the existing look and feel of the basemap.

This could also open up some interesting features, like being able to search for opportunities within a bounding polygon.

**Comment by ultrasaurus** [comment]
the current map is built with d3, it's just not dynamic (yet!).  Have you experience with the library?  agree there are lots of great possibilities here

**Comment by ultrasaurus** [comment]
this depends on https://github.com/openopps/openopps-platform/issues/1546

**Comment by Piglady64** [comment]
We will do usability testing to see if users want this feature. Moved to 1546. Closing
