### ISSUE TITLE
Remove Linkedin auth

### ISSUE THREAD

**Issue by esgoodman** [openopps/openopps-platform#812]
![screenshot of error I got while trying to log in via LinkedIn](https://cloud.githubusercontent.com/assets/10067318/7842542/9b7a7d74-0458-11e5-8f17-0624558d77bb.png)

**Comment by ultrasaurus** [comment]
Thanks for reporting @esgoodman -- I thought this was hooked up, but maybe we didn't get around to doing that.  I believe this is isolated to a configuration issue on Midas-dev; however, we should definitely hook it up at some point so we can experiment with it.

**Comment by dhcole** [comment]
Oh lame... https://developer.linkedin.com/blog/posts/2015/todays-changes

LinkedIn is basically scaling back access to their API. I'll see if we can work around it. It's not our doing though.

**Comment by dhcole** [comment]
> ## Access to "r_fullprofile" permission
> 
> Access to the r_fullprofile member permission now requires explicit approval from LinkedIn.  Additionally, the focus of this permission has changed to become much more specific.  Going forward, data received from the Profile API using the r_fullprofile permission can only be used to complement your company's careers pages, as described further on the Apply with LinkedIn page.
> 
> If you are already using member data provided by r_fullprofile and you believe your application meets new useage criteria, you will still be required to apply for permission on the Apply with LinkedIn page to maintain your application's ability to use the r_fullprofile member permission.

We need that scope in order to access skills. Without that, there's no point to using LinkedIn... Should we apply to get "explicit approval"? I think we should just discontinue our use on principle that we don't want support something that requires this kind of process. We may get it approved for Open Opportunities but that doesn't help anyone else using Midas on their own.

cc @gbinal

**Comment by dhcole** [comment]
They broke it and it's not coming back. Without support for accessing profile skills, I say we drop Linkedin completely.
