### ISSUE TITLE
Copy Opportunity is misleading, causing some new users to accidentally create duplicate tasks

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#824]
> I have gotten two notifications of tasks being created that are copies of other people's tasks today. Thought it is worth noting.
> 
> https://openopps.digitalgov.gov/tasks/95
> https://openopps.digitalgov.gov/tasks/96

Possibly related to copies created with "Copy opportunity"? #764

**Comment by ultrasaurus** [comment]
This looks like it could be just confusion on the part of the user.  I did verify that Copy Opportunity has a confirmation dialog, which should reduce it happening by accident.  

Might be worth reaching out to those people and finding out what they remember happening.

**Comment by ultrasaurus** [comment]
We definitely have to consider changing the language around this feature.  From a user:
"I was just clicking around exploring the web site – I didn’t realize that “copy opportunity” meant opening one!  I was trying to see if I could save it somewhere to reference it later."

Maybe it should be "Create New Opportunity Like This One" which is kind of long.  Or maybe we should consider using the same visual language from the [+ Opportunity] button on the /tasks page

**Comment by kbwagner** [comment]
5/18/18 - Kwagner - @LisaLNelson I believe this one is resolved.  Please confirm whether we can close.

**Comment by LisaLNelson** [comment]
Approved
