### ISSUE TITLE
As a opportunity creator, I would like an intuitive way to add links and lists

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#829]
Lisa is finding that people are confused by the markdown syntax and is needed to edit descriptions on behalf of the task owners to add links and lists before publishing.

We should look at some components that do all the WYSIWYG stuff, and still keep markdown under the hood.

**Comment by dhcole** [comment]
For review: https://github.com/yabwe/medium-editor#button-options

**Comment by dhcole** [comment]
Also https://github.com/IonicaBizau/medium-editor-markdown

**Comment by LisaLNelson** [comment]
Use a rich text editor.

**Comment by kbwagner** [comment]
Closing per backlog review
