### ISSUE TITLE
As a member, I would like to add a team to my profile

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#831]
This would be like "Agency" but at a more granular level, such as 18F or OCSIT or even something abstract like Midas or Open Opportunities.  We want to support the USDS use case where we have a new, growing team that would like to all know each other better.  

For now, it can be admin-added teams, but in the future it would be nice to have team owners be able to create their own teams and add/invite people to them.

People should be able to be on multiple teams and add themselves to any team they want.

(Then we would be able to add this as a column to the map)

**Comment by dhcole** [comment]
Can this just be a new tag type?

**Comment by LisaLNelson** [comment]
We need a tag roadmap to inform what we are doing here is need.

**Comment by kbwagner** [comment]
Closing per backlog review
