### ISSUE TITLE
As an admin, I would like Midas to automatically sign up all people creating new accounts to GovDelivery

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#869]
We send all our marketing info out through GovDelivery. Since I don't want people to have to signup 2 places it would help me save a very manual step of adding new account inforation to GovDelivery

originally reported by @LisaLNelson https://github.com/18F/midas-open-opportunities/issues/33

**Comment by ultrasaurus** [comment]
We'll not move forward on this until we know what will replace GovDelivery

**Comment by brandtheisey** [comment]
As a side note, of the close to 500 accounts that have been created in a similar manner since the Mexico pilot started for CW, only one person complained that an account was auto created for them just because they clicked a link in an email. I figured that complaint rate would be higher.
