### ISSUE TITLE
As a task taker I want to get notification when I have officially been assigned a task in a timely manner.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#874]
Workflow issue - If a task is open for more than one person to take, the task creator will not mark the task as assigned to the first individual(s)  until they have gotten all the task takers needed.  Then the task creator will mark it assigned and each task taker gets an email that says they have been assigned a task.  This can be several weeks after the first person has been assigned.

**Comment by GailSwanson** [comment]
Sounds like the task to assignee relationship may be restricted to a one to many relationship. This does keep many things simplified, but it seems we still have a need to manage individual communications. Or perhaps Each task can designate a number of assignees that can manage communications separately?

**Comment by dhcole** [comment]
how about user.tasks <=> task.participants many-to-many relationship. creators specify how many participants they need, participants "apply", creators acknowledge an application with an "accept" or "decline". once all the slots are filled, the task moves from "open" to "in progress", which is what we used to think of as assigned.

**Comment by GailSwanson** [comment]
Would we be able to accommodate communicating to accepted participants at the time that they are accepted so that they can start at that time? One of the requests we've had is to allow accepted participants to get going while the task is open and awaiting additional participants.

**Comment by dhcole** [comment]
yes

**Comment by LisaLNelson** [comment]
See #964
