### ISSUE TITLE
Consider moving to shared views for different content types

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#886]
Currently tasks, profiles, and profiles all have their own item and listing views. We could simplify the front-end architecture and share the features of each view across content types by moving to a single item view and single listing view. Any of the three content types could be presented in the item view or listing view.

This would allow for things like the search that is available to tasks and projects to be available to profiles as well.

The card in the listing view could be its own unique subview per content type to make sure that cards display the right information.

This would simplify the implementation of #863 by allowing tags to link to searches on the given tag in the listing page.

cc @jeremiak

**Comment by kbwagner** [comment]
No longer relevant since converted to the design system.
