### ISSUE TITLE
When I visit https://pages.18f.gov/midas/ I would like to see recent screenshots

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#893]
innovation gov in the header confuses people, also..
- Working Groups name change (along with a page that has the new images & non-images for project cards which makes for a nicer overview
- A Profile page (with some opportunities created and signed up for)

**Comment by dhcole** [comment]
This page can be edited by committing to the `18f-pages` branch.

**Comment by ultrasaurus** [comment]
I was thinking that it would be neat to have screenshots appear in the dashboard as well.  Maybe put in docs/screenshots?

**Comment by LisaLNelson** [comment]
Outdated.
