### ISSUE TITLE
Trading isAdmin for Permission groups

### ISSUE THREAD

**Issue by brendan-w** [openopps/openopps-platform#894]
Hi all,

Question, not an issue, but seemed like a good public forum for discussion.

In the implementation of Midas that I'm working on, there is a need for multiple account types. In particular, I'll be building a system that partitions:
- Applicants/Volunteers
- Project/Task posters
- Admins

I propose to do this using permission groups. Admins would have the power to escalate other user's priveleges by placing them in different groups. The current "Admin" checkbox would probably be replaced with a dropdown of group choices. Another tab on the admin pages could also be made for managing the details for these groups.
## Implementation details

I was planning on replacing the `isAdmin` flag with a foreign key into a table of named permissions, where one could hold arbitrary settings. For example, I'll probably end up with a table such as:

```
<--- general group properties -->|<------- permission settings --------->...


 name (PK)  |registration_option | admin | apply | project_creation | etc...
------------+--------------------+-------+-------+------------------+--------
 applicant  | 1                  | 0     | 1     | 0                |
 poster     | 1                  | 0     | 0     | 1                |
 admin      | 0                  | 1     | 1     | 1                |
```

**Reasoning**
- Easiest way to added new classes of users (ie, moderators).
- Using a seperate table helps bottle up the dangerous settings. When user models are sent from the client-side, one need only scrub the permission ID.
- The various permission groups won't be referenced by name in the policies. Rather than hard-coding them, the policies need only check the relevant permission flags attached to the given user.
- Might even obviate the need for a few of the "____ or admin" structures in the current policies, since the admin group will simply have permissions for everything.

---
### Is this something you would like submitted back to 18f/midas?

Obviously, any submission I made would come preloaded with only the `user` and `admin` groups, so as to not alter the existing behavior. But if you're interested, then you should have some say in how it gets implemented!

**Comment by dhcole** [comment]
Seems like an interesting idea. Have you looked at https://github.com/tjwebb/sails-permissions?
