### ISSUE TITLE
Consider using MyUSA authentication exclusively for Open Opportunities

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#899]
@GailSwanson @jeremiak @ultrasaurus 

Over the last few days, a few issues have come up:

- For people signing up with email, we need to verify they have control of the email address they use
- MyUSA login is confusing because the button looks like a logo. The "create an account" link is small
- We want to include additional information like agency and location at signup, so we're redesigning the sign-up process
- Duplicate accounts still creep up every now and then.
- The MyUSA ATO is on schedule to be completed this month

By using MyUSA as the exclusive authentication mechanism and deprecating user names and passwords, we simplify our architecture and address all of the above issues. 

MyUSA provides both Google oauth authentication as well as email-based authentication for any arbitrary email address.

<img width="710" alt="screen shot 2015-07-07 at 9 59 57 am" src="https://cloud.githubusercontent.com/assets/170641/8547833/7c5e077e-248f-11e5-8ab1-ba73d7d64645.png">

By only using MyUSA, we could simplify the log-in process to one-click and avoid the design confusion of offering and explaining the choice.

After authenticating with MyUSA, all potential users (Google oauth and email) would be validated against our approved domain list.

We would avoid the need to store passwords directly in the Open Opportunities database, as well as avoid the need to manage the password reset process, which would simplify our architecture and reduce the opportunities for bugs.

State would not be affected since they use SSPI and bypass our usual authentication flow.

Other users would have the ability to re-enable local authentication or use any Passport provider they like  simply by editing their `local.js` configuration.

Given this, what do you think about using MyUSA as the exclusive authentication method for Open Opportunities and making it better integrated with our user authentication flow?

**Comment by GailSwanson** [comment]
There are many user benefits to using a familiar single sign on. Would that experience take them out of open ops? Does it introduce any places the user would get lost or add more complexity?
If the only drawback is the poor usability of the button, perhaps we can make it more usable via the context surrounding the button.

**Comment by jeremiak** [comment]
I strongly support the idea of using MyUSA as an authentication service for all the points you've stated above, @dhcole.

Quick questions:

0. Do we know how many users in the current Open Opps instance have authenticated with MyUSA or email/password combinations?
0. Will MyUSA do the domain validation or will the application instance do that?

**Comment by ultrasaurus** [comment]
@dhcole I'm really glad you brought this up.  I see how this could be really great for streamlining our efforts.  Would we be able to use MyUSA attributes to request the Agency info?

The key challenge is that it would put all of the usability awkwardness of MyUSA authentication front-and-center, which would be great for improving that usability, but likely at the expense of increasing the scope of the authentication work short term.

Usability issues (off the top of my head -- @esgoodman might have more info):
- Most federal employees can't use Google Authentication (to put into perspective, only 12,000 people out of 3-5M if we count the Military) -- it will confuse people to have Google presented more prominently
- A lot of folks don't have gov email set up on their primary phones -- I don't know how important the mobile use case is, but password-less login is pretty problematic

**Comment by dhcole** [comment]
> Do we know how many users in the current Open Opps instance have authenticated with MyUSA or email/password combinations?

Not sure, but we can check. We'd need for figure out a migration path.

> Will MyUSA do the domain validation or will the application instance do that?

No, we'd still do that on our end after MyUSA authentication. Authenticating into MyUSA and authenticating into Midas are separate actions, but we can have Midas "trust" MyUSA that a user has access to the email they claim. We handle the rest

> Most federal employees can't use Google Authentication (to put into perspective, only 12,000 people out of 3-5M if we count the Military) -- it will confuse people to have Google presented more prominently
> 
> A lot of folks don't have gov email set up on their primary phones -- I don't know how important the mobile use case is, but password-less login is pretty problematic

@ultrasaurus agreed both of these could be improved. They're upstream though and out of our immediate control. So the question for us: are these ***blockers*** that outweigh the benefits?

**Comment by esgoodman** [comment]
Chiming in here. MyUSA is in the midst of building out a redesigned sign-in flow, so this is a _great_ time to raise these issues and offer suggestions. You can cc me here or stick them directly as issues into the MyUSA repo. 

1) Re: @ultrasaurus' [point](https://github.com/18F/midas/issues/899#issuecomment-119264048): We are radically de-emphasizing the Google button in the default login layout. All the research confirms that a prominent button confuses everyone who doesn't work for GSA. 

2) @GailSwanson, we are [working on](https://github.com/18F/myusa/issues/698) improving guidance/support/assets for integrators as part of the redesign. Would love to work with you to improve button visibility/legibility for Open Opportunities and Midas, since that will help all of our integrators. @mkhandekar is the person to talk to. 

3) Providing mobile sign-on for people who don't have their gov email on their main phone is going to be a challenge. Without more information about the proportion of users who are blocked from using Open Opportunities without mobile access, it's hard to prioritize it as an issue. @ultrasaurus and @dhcole, please let me or @jackiekazil know if/when you have any data on the extent of the problem.

You can see images of the new sign-in flow [here](https://github.com/18F/myusa/issues/698). Everything from the email on is basically set; the details of the first few screens are still being negotiated as we do more tests and iterate in wireframes.

**Comment by dhcole** [comment]
@esgoodman thanks for weighing in! This is really helpful context. 1) sounds great. 

As for 3), here are user operating systems over the last month:

<img width="569" alt="screen shot 2015-07-08 at 3 27 03 pm" src="https://cloud.githubusercontent.com/assets/170641/8579988/fbc8bc10-2585-11e5-8bcb-dbdd443f646a.png">

Mobile OSs are pretty small. Also, users would still be able to access all the unauthenticated content (searching for and browsing tasks and projects). And as @ultrasaurus pointed out over voice, the mobile email issue may not be too big a deal given that if you don't have access to your work email on a given device, you're probably not doing *work* on that device.

@GailSwanson is going to reach out about a few more follow ups; pending that conversation, it sounds like we may move in this direction.

**Comment by dhcole** [comment]
Another issue this solves for us is that we won't need to worry about what happens to users after they leave the federal government. By requiring that they prove access to their email account and validating on .gov addresses, if someone leaves, they wouldn't be able to get the link to log in again. I noticed we do have some users on Open Opportunities that no longer work for the government, and as we scale, it would be very hard to manage this manually.

**Comment by dhcole** [comment]
There's general support internally for this approach. This will become actionable once MyUSA has its authority to operate and when we have a need to further develop our authentication features. On ice until then.

**Comment by ultrasaurus** [comment]
Not sure about the future of MyUSA... we don't want to consider exclusive access, rather prefer moving to Google auth since there are usability issues with the way the sign up UI is (people don't recognize it as a button) and what people value is ability to auth with their Google account
