### ISSUE TITLE
Collect user feedback

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#920]
Users may want to leave feedback on their experience with Open Opportunities. To do this, we can add a link to an offline survey or community forum. Ideas for this but not sure if they are all approved by OPM
- 4Q Survey.com
- Survey Analytics
- SurveyMonkey
- UserVoice

**Comment by dhcole** [comment]
Open to PRs on this. Whatever we end up with those, I really prefer avoiding anything that pops up or interrupts a user's interaction with the website.

**Comment by GailSwanson** [comment]
Let me see if we can get ethnio hooked up.

**Comment by acolter** [comment]
This issue may also be addressed by https://github.com/openopps/openopps-platform/issues/1401

**Comment by kbwagner** [comment]
We have survey monkey links in emails now
