### ISSUE TITLE
As an admin I would like to be able to assign tasks to interested parties that have an account. 

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#955]
This will be helpful when someone has difficulty accessing the platform.

**Comment by dhcole** [comment]
:+1: This would also be useful for entering the participants of historic tasks that we imported from Wordpress.

**Comment by LisaLNelson** [comment]
@brodydittemore can you replicate?

**Comment by LisaLNelson** [comment]
This has been addressed. Working.
