### ISSUE TITLE
As a task creator I would like to be able to assign an individual to a task while keeping the task open for additional participants.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#964]
Acceptance Criteria:
- Add a "Continue accepting applicants" on/off toggle under the progress bar
- When the toggle is set to "on" the opportunity will remain open and additional participants may apply.
- When the toggle is set to "off" the opportunity will be closed and no longer visible on the site and therefore no additional participants may apply.

Screen Shot: 
![964 screen shot 2017-12-14 at 11 54 36 am](https://user-images.githubusercontent.com/18709918/34007245-111432a0-e0cf-11e7-913a-4a17b357a2d6.png)

Mock of Open Toggle: https://projects.invisionapp.com/d/main#/console/12657410/268504236/preview
Mock of Closed toggle: 
Full Mocks: 
Desktop- https://projects.invisionapp.com/d/main#/projects/prototypes/12657410
Mobile- https://projects.invisionapp.com/d/main#/projects/prototypes/12656859

Original Info:
Task creators now have to edit the task, remove the non-selected person and THEN change the status to assigned.

It'd help to allow the creator to choose the assignee in the same step/workflow (and ideally before!) and updating the status to assigned.

For additional information see https://github.com/openopps/openopps-platform/issues/874

**Comment by GailSwanson** [comment]
This should trigger the communications to the assigned task taker only. 

This uncouples the task status from the task taker status to better manage participants for tasks with more than one task taker. It is currently common for task creators to make mistakes using the system and accidentally triggering assignment emails to all volunteers and having to go back to the people whom they did not intend to select for the task to tell them they in fact were not selected (awkward!) 

There are interface improvements that will make the workflow clearer in conjunction with updating the assignment to the individual level.

**Comment by dhcole** [comment]
@LisaLNelson this is not currently in our scope of work for the rest of the quarter. Should we add it so you can prioritize this against the other issues?

**Comment by kbwagner** [comment]
Test comment for Jodie Young.

**Comment by Kibrahacha67** [comment]
LHammond 2-28-18 In Testing
