### ISSUE TITLE
As an admin, I want to see an agency (GSA) specific set of metrics including activity and users in a dashboard.

### ISSUE THREAD

**Issue by GailSwanson** [openopps/openopps-platform#991]
This will support GSA OHRM staff as admins for GSA opportunities.  GSA is the first customer that will administer an program that is focused on a single agency.  My hypothesis is that allowing agency admins to see the metrics and lists available in the admin panel, scoped to their specific agency will meet their needs.  The story as written is my hypothesis, which may be modified based on user research.  The requirement is that GSA OHRM be able to run their rotational details program and the GSA Project Network on the Open Opportunities platform, include admins having visibility into the health of their program (e.g. via seeing user activity and metrics) and the info to steer outreach effectively.

This is based on watching @LisaLNelson manage the cross-agency program for Open Opportunities.  I observed 
- she would set goals such as # tasks posted/completed and # of new members, # of participants per quarter or per year.  
- she would watch the activity as people signed up, noticing when someone was from a new agency or if it had been someone who attended of of her workshops or webinars, if it was someone from the mailing list, or a new person.  When people would sign up for tasks, she would remark on if they were from a new agency or how they got involved.  Even with 1000 members and hundreds of participants, she was still able to track patterns based on knowing a little bit about most of the active users.
- she would look at the montly and quarterly metrics to see if she was tracking to her goals, and if not, she would look at the lists of open tasks to see if she felt she needed to focus on outreach to task creators or to participants.  She would look at the distribution of tasks, across task creators, agency, and discipline to see if there was a good variety.

We also anticipate that adoption within any agency will likely happen at a smaller scale than the federal-wide adoption, so fine-grained analysis can be accomplished by exporting lists of members, participants and tasks for offline analysis, as long as we have enough common actions visible in the dashboard.  

For the initial implementation, my assumption is that "enough" could be defined by the tools that we have made available for Lisa for the wider Open Opportunities program.  Of course, as the communities grow, we will need to augment those tools, but this story would focus on the first set of tools need for GSA OHRM.

**Comment by ultrasaurus** [comment]
waiting for https://github.com/18F/midas/issues/1084
