### ISSUE TITLE
As a site visitor, I would like to see content such as the task creator toolkit without leaving Open Opportunities

### ISSUE THREAD

**Issue by GailSwanson** [openopps/openopps-platform#994]
Open Opportunities has static content currently residing on other sites. Moving it over to an integrated experience will:
- Put the right content in the right contexts so that users get a better understanding of the platform, it's benefits and how it works.
- Increase content discoverability
- Allow integration of content into relevant areas of the application
- Decrease disruption of task flow

**Comment by LisaLNelson** [comment]
Resources:
Process Map - https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2015/12/Open-Opportunities-Task-Creator-Process1.pdf
Tips for Task Creators - https://www.digitalgov.gov/resources/open-opportunities-task-creator-toolkit/10-tips-for-creating-the-perfect-open-opportunity-task/
How Open Opportunities works https://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/how-open-opportunities-works/
Terms of Use: https://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/open-opportunities-terms-of-use/

**Comment by kbwagner** [comment]
No longer an issue per backlog review.
