### ISSUE TITLE
Tags should be unique

### ISSUE THREAD

**Issue by dhcole** [openopps/openopps-platform#999]
There are currently a lot of duplicate tags. To address this, we need to do the following:
- Write a script to merge duplicate tags in the database by standardizing case and trimming whitespace
- Enforce the same case and whitespace rules on tag input fields

We may want to expand tags to include both an internal unique name and a display name, so that things like JavaScript are de-duplicated on javascript but display in the correct case.

**Comment by ultrasaurus** [comment]
We've talked about changing the model for tags, so we should think about where we are going with the user-facing behaviors before diving into this.

**Comment by Piglady64** [comment]
We will be implementing skills engine, this is no longer applicable. closing
